void eff_MS()
{
//=========Macro generated from canvas: Canvas_1/Canvas_1
//=========  (Sun Se  9 19:33:27 2018) by ROOT version 6.14/04
   TCanvas *Canvas_1 = new TCanvas("Canvas_1", "Canvas_1",0,0,1280,925);
   Canvas_1->Range(-0.06341146,0.7819976,0.6175781,0.9979438);
   gStyle->SetOptStat(0);
   Canvas_1->Range(-0.4860759,-0.2025316,2.551899,1.063291);
   Canvas_1->SetFillColor(0);
   Canvas_1->SetBorderMode(0);
   Canvas_1->SetBorderSize(2);
   Canvas_1->SetLeftMargin(0.15);
   Canvas_1->SetRightMargin(0.05);
   Canvas_1->SetTopMargin(0.05);
   Canvas_1->SetBottomMargin(0.15);
   Canvas_1->SetGridy();
   Canvas_1->SetTickx(1);
   Canvas_1->SetTicky(1);
   Canvas_1->SetFrameBorderMode(0);

   
   TEfficiency * AlgEffFitVsInvPt_KF4ParamsComb1 = new TEfficiency("noMS",";  Simulated track 1/p_{T} [GeV^{-1}]; Efficiency",24,0,0.75);
   
   AlgEffFitVsInvPt_KF4ParamsComb1->SetConfidenceLevel(0.6826895);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetBetaAlpha(1);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetBetaBeta(1);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetWeight(1);
//   AlgEffFitVsInvPt_KF4ParamsComb1->SetStatisticOption(0);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPosteriorMode(0);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetShortestInterval(0);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(0,0);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(0,0);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(1,3318);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(1,3178);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(2,7120);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(2,6813);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(3,8598);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(3,8241);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(4,8956);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(4,8595);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(5,8563);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(5,8219);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(6,8501);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(6,8123);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(7,8223);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(7,7828);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(8,7915);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(8,7488);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(9,7623);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(9,7188);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(10,7469);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(10,6990);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(11,7137);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(11,6636);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(12,7164);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(12,6669);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(13,6874);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(13,6349);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(14,6817);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(14,6230);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(15,6635);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(15,5975);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(16,6464);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(16,5319);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(17,0);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(17,0);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(18,0);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(18,0);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(19,0);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(19,0);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(20,0);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(20,0);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(21,0);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(21,0);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(22,0);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(22,0);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(23,0);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(23,0);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(24,0);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(24,0);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetTotalEvents(25,0);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetPassedEvents(25,0);

//   auto g = AlgEffFitVsInvPt_KF4ParamsComb1->GetPaintedGraph();
//   g->SetMinimum(80.);
//   g->SetMaximum(100.);
//   AlgEffFitVsInvPt_KF4ParamsComb1->GetXaxis()->SetTitle(" Simulated track 1/p_{T} [GeV^{-1}]");
//   AlgEffFitVsInvPt_KF4ParamsComb1->GetYaxis()->SetTitle(" Efficiency");

   AlgEffFitVsInvPt_KF4ParamsComb1->SetLineColor(2);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetFillColor(2);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetMarkerColor(2);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetMarkerStyle(4);
   AlgEffFitVsInvPt_KF4ParamsComb1->SetMarkerSize(2);
   AlgEffFitVsInvPt_KF4ParamsComb1->Draw("AP");

   Canvas_1->Update();

   gPad->Update();
   auto graph = AlgEffFitVsInvPt_KF4ParamsComb1->GetPaintedGraph();
   graph->SetMinimum(0.80);
   graph->SetMaximum(1.0);
   graph->GetXaxis()->SetTitleOffset(1.3);
   graph->GetXaxis()->SetTitleSize(0.05);
   graph->GetXaxis()->SetLabelSize(0.05);
   graph->GetYaxis()->SetTitleOffset(1.3);
   graph->GetYaxis()->SetTitleSize(0.05);
   graph->GetYaxis()->SetLabelSize(0.05);

   TEfficiency * AlgEffFitVsInvPt_KF4ParamsComb2=new TEfficiency("constantMS","",24,0,0.75);

   AlgEffFitVsInvPt_KF4ParamsComb2->SetConfidenceLevel(0.6826895);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetBetaAlpha(1);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetBetaBeta(1);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetWeight(1);
//   AlgEffFitVsInvPt_KF4ParamsComb2->SetStatisticOption(0);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPosteriorMode(0);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetShortestInterval(0);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(0,0);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(0,0);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(1,3318);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(1,3153);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(2,7120);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(2,6807);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(3,8598);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(3,8232);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(4,8956);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(4,8603);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(5,8563);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(5,8227);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(6,8501);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(6,8154);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(7,8223);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(7,7869);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(8,7915);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(8,7535);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(9,7623);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(9,7229);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(10,7469);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(10,7042);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(11,7137);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(11,6713);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(12,7164);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(12,6740);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(13,6874);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(13,6430);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(14,6817);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(14,6317);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(15,6635);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(15,6073);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(16,6464);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(16,5395);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(17,0);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(17,0);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(18,0);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(18,0);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(19,0);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(19,0);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(20,0);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(20,0);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(21,0);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(21,0);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(22,0);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(22,0);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(23,0);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(23,0);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(24,0);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(24,0);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetTotalEvents(25,0);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetPassedEvents(25,0);

   AlgEffFitVsInvPt_KF4ParamsComb2->SetLineStyle(7);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetLineColor(1);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetFillColor(1);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetMarkerColor(1);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetMarkerStyle(4);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetMarkerSize(2);

   AlgEffFitVsInvPt_KF4ParamsComb2->Draw("p,same");
   Canvas_1->Update();

   TEfficiency * AlgEffFitVsInvPt_KF4ParamsComb3 = new TEfficiency("layerMS","",24,0,0.75);

   AlgEffFitVsInvPt_KF4ParamsComb3->SetConfidenceLevel(0.6826895);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetBetaAlpha(1);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetBetaBeta(1);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetWeight(1);
//   AlgEffFitVsInvPt_KF4ParamsComb3->SetStatisticOption(0);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPosteriorMode(0);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetShortestInterval(0);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(0,0);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(0,0);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(1,3318);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(1,3156);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(2,7120);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(2,6808);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(3,8598);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(3,8236);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(4,8956);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(4,8612);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(5,8563);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(5,8229);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(6,8501);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(6,8146);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(7,8223);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(7,7876);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(8,7915);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(8,7539);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(9,7623);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(9,7234);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(10,7469);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(10,7043);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(11,7137);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(11,6712);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(12,7164);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(12,6740);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(13,6874);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(13,6434);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(14,6817);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(14,6310);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(15,6635);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(15,6081);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(16,6464);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(16,5397);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(17,0);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(17,0);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(18,0);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(18,0);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(19,0);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(19,0);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(20,0);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(20,0);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(21,0);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(21,0);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(22,0);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(22,0);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(23,0);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(23,0);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(24,0);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(24,0);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetTotalEvents(25,0);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetPassedEvents(25,0);

   AlgEffFitVsInvPt_KF4ParamsComb2->SetLineStyle(7);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetLineColor(1);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetFillColor(1);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetMarkerColor(1);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetMarkerStyle(4);
   AlgEffFitVsInvPt_KF4ParamsComb2->SetMarkerSize(2);

   AlgEffFitVsInvPt_KF4ParamsComb2->Draw("p,same");
   Canvas_1->Update();

   AlgEffFitVsInvPt_KF4ParamsComb3->SetLineStyle(2);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetLineColor(4);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetFillColor(4);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetMarkerColor(4);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetMarkerStyle(4);
   AlgEffFitVsInvPt_KF4ParamsComb3->SetMarkerSize(2);

   AlgEffFitVsInvPt_KF4ParamsComb3->Draw("p,same");
   Canvas_1->Update();

   TLegend *leg = new TLegend(0.2,0.47,0.27,0.68,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.04);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("noMS","k = 0","PEL");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(2);
   entry->SetMarkerStyle(4);
   entry->SetMarkerSize(2);
   entry->SetTextFont(42);

   entry=leg->AddEntry("constantMS","constant k","PEL");
   entry->SetLineColor(1);
   entry->SetLineStyle(7);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(4);
   entry->SetMarkerSize(2);
   entry->SetTextFont(42);

   entry=leg->AddEntry("layerMS","k (layer)","PEL");
   entry->SetLineColor(4);
   entry->SetLineStyle(2);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(4);
   entry->SetMarkerStyle(4);
   entry->SetMarkerSize(2);
   entry->SetTextFont(42);
   leg->Draw();

   Canvas_1->Modified();
   Canvas_1->cd();
   Canvas_1->SetSelected(Canvas_1);
}
