void zMass_wMassCuts()
{
//=========Macro generated from canvas: zPairMass_NPL_ee_wMass_ee_2016/zPairMass_NPL_ee_wMass_ee_2016
//=========  (Sun Sep 16 21:39:28 2018) by ROOT version 6.14/04
   TCanvas *zPairMass_NPL_ee_wMass_ee_2016 = new TCanvas("zPairMass_NPL_ee_wMass_ee_2016", "zPairMass_NPL_ee_wMass_ee_2016",0,0,1280,925);
   zPairMass_NPL_ee_wMass_ee_2016->Range(-0.4860759,-0.2025316,2.551899,1.063291);
   zPairMass_NPL_ee_wMass_ee_2016->SetHighLightColor(2);
   zPairMass_NPL_ee_wMass_ee_2016->Range(0,0,1,1);
   zPairMass_NPL_ee_wMass_ee_2016->SetFillColor(0);
   zPairMass_NPL_ee_wMass_ee_2016->SetBorderMode(0);
   zPairMass_NPL_ee_wMass_ee_2016->SetBorderSize(2);
   zPairMass_NPL_ee_wMass_ee_2016->SetLeftMargin(0.12);
   zPairMass_NPL_ee_wMass_ee_2016->SetRightMargin(0.04);
   zPairMass_NPL_ee_wMass_ee_2016->SetTopMargin(0.08);
   zPairMass_NPL_ee_wMass_ee_2016->SetBottomMargin(0.12);
   zPairMass_NPL_ee_wMass_ee_2016->SetFrameFillStyle(0);
   zPairMass_NPL_ee_wMass_ee_2016->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: canvy_1
   TPad *canvy_1 = new TPad("canvy_1", "newpad",0.01,0.315,0.99,0.99);
   canvy_1->Draw();
   canvy_1->cd();
   canvy_1->Range(37.14286,-83.58332,144.2857,2238.176);
   canvy_1->SetFillColor(0);
   canvy_1->SetBorderMode(0);
   canvy_1->SetBorderSize(2);
   canvy_1->SetLeftMargin(0.12);
   canvy_1->SetRightMargin(0.04);
   canvy_1->SetTopMargin(0.08);
   canvy_1->SetBottomMargin(0.036);
   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);
   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);
   
   THStack *zPairMass_NPL_ee_wMass_ee = new THStack();
   zPairMass_NPL_ee_wMass_ee->SetName("zPairMass_NPL_ee_wMass_ee");
   zPairMass_NPL_ee_wMass_ee->SetTitle("Invariant Z Mass;m_{ll} (GeV/c^{2});Events");
   zPairMass_NPL_ee_wMass_ee->SetMaximum(1954.7);
   
   TH1F *zPairMass_NPL_ee_wMass_ee_stack_1 = new TH1F("zPairMass_NPL_ee_wMass_ee_stack_1","Invariant Z Mass",20,50,140);
   zPairMass_NPL_ee_wMass_ee_stack_1->SetMinimum(0);
   zPairMass_NPL_ee_wMass_ee_stack_1->SetMaximum(2052.435);
   zPairMass_NPL_ee_wMass_ee_stack_1->SetDirectory(0);
   zPairMass_NPL_ee_wMass_ee_stack_1->SetStats(0);
   zPairMass_NPL_ee_wMass_ee_stack_1->SetLineStyle(0);
   zPairMass_NPL_ee_wMass_ee_stack_1->SetMarkerStyle(20);
   zPairMass_NPL_ee_wMass_ee_stack_1->GetXaxis()->SetTitle("m_{ll} (GeV/c^{2})");
   zPairMass_NPL_ee_wMass_ee_stack_1->GetXaxis()->SetNdivisions(506);
   zPairMass_NPL_ee_wMass_ee_stack_1->GetXaxis()->SetLabelFont(42);
   zPairMass_NPL_ee_wMass_ee_stack_1->GetXaxis()->SetLabelOffset(999);
   zPairMass_NPL_ee_wMass_ee_stack_1->GetXaxis()->SetLabelSize(0.05);
   zPairMass_NPL_ee_wMass_ee_stack_1->GetXaxis()->SetTitleSize(0.06);
   zPairMass_NPL_ee_wMass_ee_stack_1->GetXaxis()->SetTitleOffset(0.9);
   zPairMass_NPL_ee_wMass_ee_stack_1->GetXaxis()->SetTitleFont(42);
   zPairMass_NPL_ee_wMass_ee_stack_1->GetYaxis()->SetTitle("Events");
   zPairMass_NPL_ee_wMass_ee_stack_1->GetYaxis()->SetNdivisions(506);
   zPairMass_NPL_ee_wMass_ee_stack_1->GetYaxis()->SetLabelFont(42);
   zPairMass_NPL_ee_wMass_ee_stack_1->GetYaxis()->SetLabelOffset(0.007);
   zPairMass_NPL_ee_wMass_ee_stack_1->GetYaxis()->SetLabelSize(0.05);
   zPairMass_NPL_ee_wMass_ee_stack_1->GetYaxis()->SetTitleSize(0.06);
   zPairMass_NPL_ee_wMass_ee_stack_1->GetYaxis()->SetTitleOffset(1.032);
   zPairMass_NPL_ee_wMass_ee_stack_1->GetYaxis()->SetTitleFont(42);
   zPairMass_NPL_ee_wMass_ee_stack_1->GetZaxis()->SetLabelFont(42);
   zPairMass_NPL_ee_wMass_ee_stack_1->GetZaxis()->SetLabelOffset(0.007);
   zPairMass_NPL_ee_wMass_ee_stack_1->GetZaxis()->SetLabelSize(0.05);
   zPairMass_NPL_ee_wMass_ee_stack_1->GetZaxis()->SetTitleSize(0.06);
   zPairMass_NPL_ee_wMass_ee_stack_1->GetZaxis()->SetTitleFont(42);
   zPairMass_NPL_ee_wMass_ee->SetHistogram(zPairMass_NPL_ee_wMass_ee_stack_1);
   
   
   TH1D *zPairMass_tZq_wMass_ee_stack_1 = new TH1D("zPairMass_tZq_wMass_ee_stack_1","zPairMass_tZq_wMass_ee",20,50,140);
   zPairMass_tZq_wMass_ee_stack_1->SetBinContent(5,0.1103236);
   zPairMass_tZq_wMass_ee_stack_1->SetBinContent(6,0.3456542);
   zPairMass_tZq_wMass_ee_stack_1->SetBinContent(7,0.6430019);
   zPairMass_tZq_wMass_ee_stack_1->SetBinContent(8,2.122547);
   zPairMass_tZq_wMass_ee_stack_1->SetBinContent(9,10.64398);
   zPairMass_tZq_wMass_ee_stack_1->SetBinContent(10,13.25475);
   zPairMass_tZq_wMass_ee_stack_1->SetBinContent(11,2.272998);
   zPairMass_tZq_wMass_ee_stack_1->SetBinContent(12,0.6186994);
   zPairMass_tZq_wMass_ee_stack_1->SetBinContent(13,0.3381588);
   zPairMass_tZq_wMass_ee_stack_1->SetBinContent(14,0.1038027);
   zPairMass_tZq_wMass_ee_stack_1->SetEntries(183277);
   zPairMass_tZq_wMass_ee_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ffff00");
   zPairMass_tZq_wMass_ee_stack_1->SetFillColor(ci);
   zPairMass_tZq_wMass_ee_stack_1->GetXaxis()->SetTitle("m_{ll} (GeV/c^{2})");
   zPairMass_tZq_wMass_ee_stack_1->GetXaxis()->SetLabelFont(42);
   zPairMass_tZq_wMass_ee_stack_1->GetXaxis()->SetLabelSize(0.035);
   zPairMass_tZq_wMass_ee_stack_1->GetXaxis()->SetTitleSize(0.035);
   zPairMass_tZq_wMass_ee_stack_1->GetXaxis()->SetTitleFont(42);
   zPairMass_tZq_wMass_ee_stack_1->GetYaxis()->SetLabelFont(42);
   zPairMass_tZq_wMass_ee_stack_1->GetYaxis()->SetLabelSize(0.035);
   zPairMass_tZq_wMass_ee_stack_1->GetYaxis()->SetTitleSize(0.035);
   zPairMass_tZq_wMass_ee_stack_1->GetYaxis()->SetTitleFont(42);
   zPairMass_tZq_wMass_ee_stack_1->GetZaxis()->SetLabelFont(42);
   zPairMass_tZq_wMass_ee_stack_1->GetZaxis()->SetLabelSize(0.035);
   zPairMass_tZq_wMass_ee_stack_1->GetZaxis()->SetTitleSize(0.035);
   zPairMass_tZq_wMass_ee_stack_1->GetZaxis()->SetTitleFont(42);
   zPairMass_NPL_ee_wMass_ee->Add(zPairMass_tZq_wMass_ee_stack_1,"");
   
   TH1D *zPairMass_ttV_wMass_ee_stack_2 = new TH1D("zPairMass_ttV_wMass_ee_stack_2","zPairMass_ttV_wMass_ee",20,50,140);
   zPairMass_ttV_wMass_ee_stack_2->SetBinContent(5,0.7672612);
   zPairMass_ttV_wMass_ee_stack_2->SetBinContent(6,2.488088);
   zPairMass_ttV_wMass_ee_stack_2->SetBinContent(7,3.249828);
   zPairMass_ttV_wMass_ee_stack_2->SetBinContent(8,5.579175);
   zPairMass_ttV_wMass_ee_stack_2->SetBinContent(9,21.61803);
   zPairMass_ttV_wMass_ee_stack_2->SetBinContent(10,27.92537);
   zPairMass_ttV_wMass_ee_stack_2->SetBinContent(11,5.992803);
   zPairMass_ttV_wMass_ee_stack_2->SetBinContent(12,2.74987);
   zPairMass_ttV_wMass_ee_stack_2->SetBinContent(13,2.627423);
   zPairMass_ttV_wMass_ee_stack_2->SetBinContent(14,1.443784);
   zPairMass_ttV_wMass_ee_stack_2->SetEntries(96071);
   zPairMass_ttV_wMass_ee_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#00ff00");
   zPairMass_ttV_wMass_ee_stack_2->SetFillColor(ci);
   zPairMass_ttV_wMass_ee_stack_2->GetXaxis()->SetTitle("m_{ll} (GeV/c^{2})");
   zPairMass_ttV_wMass_ee_stack_2->GetXaxis()->SetLabelFont(42);
   zPairMass_ttV_wMass_ee_stack_2->GetXaxis()->SetLabelSize(0.035);
   zPairMass_ttV_wMass_ee_stack_2->GetXaxis()->SetTitleSize(0.035);
   zPairMass_ttV_wMass_ee_stack_2->GetXaxis()->SetTitleFont(42);
   zPairMass_ttV_wMass_ee_stack_2->GetYaxis()->SetLabelFont(42);
   zPairMass_ttV_wMass_ee_stack_2->GetYaxis()->SetLabelSize(0.035);
   zPairMass_ttV_wMass_ee_stack_2->GetYaxis()->SetTitleSize(0.035);
   zPairMass_ttV_wMass_ee_stack_2->GetYaxis()->SetTitleFont(42);
   zPairMass_ttV_wMass_ee_stack_2->GetZaxis()->SetLabelFont(42);
   zPairMass_ttV_wMass_ee_stack_2->GetZaxis()->SetLabelSize(0.035);
   zPairMass_ttV_wMass_ee_stack_2->GetZaxis()->SetTitleSize(0.035);
   zPairMass_ttV_wMass_ee_stack_2->GetZaxis()->SetTitleFont(42);
   zPairMass_NPL_ee_wMass_ee->Add(zPairMass_ttV_wMass_ee_stack_2,"");
   
   TH1D *zPairMass_wJets_wMass_ee_stack_3 = new TH1D("zPairMass_wJets_wMass_ee_stack_3","zPairMass_wJets_wMass_ee",20,50,140);
   zPairMass_wJets_wMass_ee_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   zPairMass_wJets_wMass_ee_stack_3->SetFillColor(ci);
   zPairMass_wJets_wMass_ee_stack_3->GetXaxis()->SetTitle("m_{ll} (GeV/c^{2})");
   zPairMass_wJets_wMass_ee_stack_3->GetXaxis()->SetLabelFont(42);
   zPairMass_wJets_wMass_ee_stack_3->GetXaxis()->SetLabelSize(0.035);
   zPairMass_wJets_wMass_ee_stack_3->GetXaxis()->SetTitleSize(0.035);
   zPairMass_wJets_wMass_ee_stack_3->GetXaxis()->SetTitleFont(42);
   zPairMass_wJets_wMass_ee_stack_3->GetYaxis()->SetLabelFont(42);
   zPairMass_wJets_wMass_ee_stack_3->GetYaxis()->SetLabelSize(0.035);
   zPairMass_wJets_wMass_ee_stack_3->GetYaxis()->SetTitleSize(0.035);
   zPairMass_wJets_wMass_ee_stack_3->GetYaxis()->SetTitleFont(42);
   zPairMass_wJets_wMass_ee_stack_3->GetZaxis()->SetLabelFont(42);
   zPairMass_wJets_wMass_ee_stack_3->GetZaxis()->SetLabelSize(0.035);
   zPairMass_wJets_wMass_ee_stack_3->GetZaxis()->SetTitleSize(0.035);
   zPairMass_wJets_wMass_ee_stack_3->GetZaxis()->SetTitleFont(42);
   zPairMass_NPL_ee_wMass_ee->Add(zPairMass_wJets_wMass_ee_stack_3,"");
   
   TH1D *zPairMass_VVV_wMass_ee_stack_4 = new TH1D("zPairMass_VVV_wMass_ee_stack_4","zPairMass_VVV_wMass_ee",20,50,140);
   zPairMass_VVV_wMass_ee_stack_4->SetBinContent(5,0.009643597);
   zPairMass_VVV_wMass_ee_stack_4->SetBinContent(6,0.07321026);
   zPairMass_VVV_wMass_ee_stack_4->SetBinContent(7,0.04327053);
   zPairMass_VVV_wMass_ee_stack_4->SetBinContent(8,0.2614885);
   zPairMass_VVV_wMass_ee_stack_4->SetBinContent(9,1.219908);
   zPairMass_VVV_wMass_ee_stack_4->SetBinContent(10,1.705702);
   zPairMass_VVV_wMass_ee_stack_4->SetBinContent(11,0.1422187);
   zPairMass_VVV_wMass_ee_stack_4->SetBinContent(12,0.1171834);
   zPairMass_VVV_wMass_ee_stack_4->SetBinContent(13,0.04107136);
   zPairMass_VVV_wMass_ee_stack_4->SetBinContent(14,0.002067603);
   zPairMass_VVV_wMass_ee_stack_4->SetEntries(617);
   zPairMass_VVV_wMass_ee_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#00ffff");
   zPairMass_VVV_wMass_ee_stack_4->SetFillColor(ci);
   zPairMass_VVV_wMass_ee_stack_4->GetXaxis()->SetTitle("m_{ll} (GeV/c^{2})");
   zPairMass_VVV_wMass_ee_stack_4->GetXaxis()->SetLabelFont(42);
   zPairMass_VVV_wMass_ee_stack_4->GetXaxis()->SetLabelSize(0.035);
   zPairMass_VVV_wMass_ee_stack_4->GetXaxis()->SetTitleSize(0.035);
   zPairMass_VVV_wMass_ee_stack_4->GetXaxis()->SetTitleFont(42);
   zPairMass_VVV_wMass_ee_stack_4->GetYaxis()->SetLabelFont(42);
   zPairMass_VVV_wMass_ee_stack_4->GetYaxis()->SetLabelSize(0.035);
   zPairMass_VVV_wMass_ee_stack_4->GetYaxis()->SetTitleSize(0.035);
   zPairMass_VVV_wMass_ee_stack_4->GetYaxis()->SetTitleFont(42);
   zPairMass_VVV_wMass_ee_stack_4->GetZaxis()->SetLabelFont(42);
   zPairMass_VVV_wMass_ee_stack_4->GetZaxis()->SetLabelSize(0.035);
   zPairMass_VVV_wMass_ee_stack_4->GetZaxis()->SetTitleSize(0.035);
   zPairMass_VVV_wMass_ee_stack_4->GetZaxis()->SetTitleFont(42);
   zPairMass_NPL_ee_wMass_ee->Add(zPairMass_VVV_wMass_ee_stack_4,"");
   
   TH1D *zPairMass_VV_wMass_ee_stack_5 = new TH1D("zPairMass_VV_wMass_ee_stack_5","zPairMass_VV_wMass_ee",20,50,140);
   zPairMass_VV_wMass_ee_stack_5->SetBinContent(5,0.2688891);
   zPairMass_VV_wMass_ee_stack_5->SetBinContent(6,1.657629);
   zPairMass_VV_wMass_ee_stack_5->SetBinContent(7,2.168054);
   zPairMass_VV_wMass_ee_stack_5->SetBinContent(8,8.741985);
   zPairMass_VV_wMass_ee_stack_5->SetBinContent(9,43.35078);
   zPairMass_VV_wMass_ee_stack_5->SetBinContent(10,56.37017);
   zPairMass_VV_wMass_ee_stack_5->SetBinContent(11,9.017086);
   zPairMass_VV_wMass_ee_stack_5->SetBinContent(12,3.430387);
   zPairMass_VV_wMass_ee_stack_5->SetBinContent(13,1.812737);
   zPairMass_VV_wMass_ee_stack_5->SetBinContent(14,0.7268279);
   zPairMass_VV_wMass_ee_stack_5->SetEntries(22886);
   zPairMass_VV_wMass_ee_stack_5->SetDirectory(0);

   ci = TColor::GetColor("#ffcc00");
   zPairMass_VV_wMass_ee_stack_5->SetFillColor(ci);
   zPairMass_VV_wMass_ee_stack_5->GetXaxis()->SetTitle("m_{ll} (GeV/c^{2})");
   zPairMass_VV_wMass_ee_stack_5->GetXaxis()->SetLabelFont(42);
   zPairMass_VV_wMass_ee_stack_5->GetXaxis()->SetLabelSize(0.035);
   zPairMass_VV_wMass_ee_stack_5->GetXaxis()->SetTitleSize(0.035);
   zPairMass_VV_wMass_ee_stack_5->GetXaxis()->SetTitleFont(42);
   zPairMass_VV_wMass_ee_stack_5->GetYaxis()->SetLabelFont(42);
   zPairMass_VV_wMass_ee_stack_5->GetYaxis()->SetLabelSize(0.035);
   zPairMass_VV_wMass_ee_stack_5->GetYaxis()->SetTitleSize(0.035);
   zPairMass_VV_wMass_ee_stack_5->GetYaxis()->SetTitleFont(42);
   zPairMass_VV_wMass_ee_stack_5->GetZaxis()->SetLabelFont(42);
   zPairMass_VV_wMass_ee_stack_5->GetZaxis()->SetLabelSize(0.035);
   zPairMass_VV_wMass_ee_stack_5->GetZaxis()->SetTitleSize(0.035);
   zPairMass_VV_wMass_ee_stack_5->GetZaxis()->SetTitleFont(42);
   zPairMass_NPL_ee_wMass_ee->Add(zPairMass_VV_wMass_ee_stack_5,"");
   
   TH1D *zPairMass_SingleTop_wMass_ee_stack_6 = new TH1D("zPairMass_SingleTop_wMass_ee_stack_6","zPairMass_SingleTop_wMass_ee",20,50,140);
   zPairMass_SingleTop_wMass_ee_stack_6->SetBinContent(5,2.197851);
   zPairMass_SingleTop_wMass_ee_stack_6->SetBinContent(6,6.725701);
   zPairMass_SingleTop_wMass_ee_stack_6->SetBinContent(7,7.097185);
   zPairMass_SingleTop_wMass_ee_stack_6->SetBinContent(8,7.106749);
   zPairMass_SingleTop_wMass_ee_stack_6->SetBinContent(9,9.596877);
   zPairMass_SingleTop_wMass_ee_stack_6->SetBinContent(10,9.648052);
   zPairMass_SingleTop_wMass_ee_stack_6->SetBinContent(11,6.571346);
   zPairMass_SingleTop_wMass_ee_stack_6->SetBinContent(12,6.269041);
   zPairMass_SingleTop_wMass_ee_stack_6->SetBinContent(13,6.278821);
   zPairMass_SingleTop_wMass_ee_stack_6->SetBinContent(14,1.912744);
   zPairMass_SingleTop_wMass_ee_stack_6->SetEntries(1524);
   zPairMass_SingleTop_wMass_ee_stack_6->SetDirectory(0);

   ci = TColor::GetColor("#ff00ff");
   zPairMass_SingleTop_wMass_ee_stack_6->SetFillColor(ci);
   zPairMass_SingleTop_wMass_ee_stack_6->GetXaxis()->SetTitle("m_{ll} (GeV/c^{2})");
   zPairMass_SingleTop_wMass_ee_stack_6->GetXaxis()->SetLabelFont(42);
   zPairMass_SingleTop_wMass_ee_stack_6->GetXaxis()->SetLabelSize(0.035);
   zPairMass_SingleTop_wMass_ee_stack_6->GetXaxis()->SetTitleSize(0.035);
   zPairMass_SingleTop_wMass_ee_stack_6->GetXaxis()->SetTitleFont(42);
   zPairMass_SingleTop_wMass_ee_stack_6->GetYaxis()->SetLabelFont(42);
   zPairMass_SingleTop_wMass_ee_stack_6->GetYaxis()->SetLabelSize(0.035);
   zPairMass_SingleTop_wMass_ee_stack_6->GetYaxis()->SetTitleSize(0.035);
   zPairMass_SingleTop_wMass_ee_stack_6->GetYaxis()->SetTitleFont(42);
   zPairMass_SingleTop_wMass_ee_stack_6->GetZaxis()->SetLabelFont(42);
   zPairMass_SingleTop_wMass_ee_stack_6->GetZaxis()->SetLabelSize(0.035);
   zPairMass_SingleTop_wMass_ee_stack_6->GetZaxis()->SetTitleSize(0.035);
   zPairMass_SingleTop_wMass_ee_stack_6->GetZaxis()->SetTitleFont(42);
   zPairMass_NPL_ee_wMass_ee->Add(zPairMass_SingleTop_wMass_ee_stack_6,"");
   
   TH1D *zPairMass_ttbarInc_wMass_ee_stack_7 = new TH1D("zPairMass_ttbarInc_wMass_ee_stack_7","zPairMass_ttbarInc_wMass_ee",20,50,140);
   zPairMass_ttbarInc_wMass_ee_stack_7->SetBinContent(5,58.35307);
   zPairMass_ttbarInc_wMass_ee_stack_7->SetBinContent(6,191.7508);
   zPairMass_ttbarInc_wMass_ee_stack_7->SetBinContent(7,191.427);
   zPairMass_ttbarInc_wMass_ee_stack_7->SetBinContent(8,196.1767);
   zPairMass_ttbarInc_wMass_ee_stack_7->SetBinContent(9,194.9598);
   zPairMass_ttbarInc_wMass_ee_stack_7->SetBinContent(10,184.7218);
   zPairMass_ttbarInc_wMass_ee_stack_7->SetBinContent(11,194.914);
   zPairMass_ttbarInc_wMass_ee_stack_7->SetBinContent(12,170.023);
   zPairMass_ttbarInc_wMass_ee_stack_7->SetBinContent(13,180.478);
   zPairMass_ttbarInc_wMass_ee_stack_7->SetBinContent(14,92.67214);
   zPairMass_ttbarInc_wMass_ee_stack_7->SetEntries(4858);
   zPairMass_ttbarInc_wMass_ee_stack_7->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   zPairMass_ttbarInc_wMass_ee_stack_7->SetFillColor(ci);
   zPairMass_ttbarInc_wMass_ee_stack_7->GetXaxis()->SetTitle("m_{ll} (GeV/c^{2})");
   zPairMass_ttbarInc_wMass_ee_stack_7->GetXaxis()->SetLabelFont(42);
   zPairMass_ttbarInc_wMass_ee_stack_7->GetXaxis()->SetLabelSize(0.035);
   zPairMass_ttbarInc_wMass_ee_stack_7->GetXaxis()->SetTitleSize(0.035);
   zPairMass_ttbarInc_wMass_ee_stack_7->GetXaxis()->SetTitleFont(42);
   zPairMass_ttbarInc_wMass_ee_stack_7->GetYaxis()->SetLabelFont(42);
   zPairMass_ttbarInc_wMass_ee_stack_7->GetYaxis()->SetLabelSize(0.035);
   zPairMass_ttbarInc_wMass_ee_stack_7->GetYaxis()->SetTitleSize(0.035);
   zPairMass_ttbarInc_wMass_ee_stack_7->GetYaxis()->SetTitleFont(42);
   zPairMass_ttbarInc_wMass_ee_stack_7->GetZaxis()->SetLabelFont(42);
   zPairMass_ttbarInc_wMass_ee_stack_7->GetZaxis()->SetLabelSize(0.035);
   zPairMass_ttbarInc_wMass_ee_stack_7->GetZaxis()->SetTitleSize(0.035);
   zPairMass_ttbarInc_wMass_ee_stack_7->GetZaxis()->SetTitleFont(42);
   zPairMass_NPL_ee_wMass_ee->Add(zPairMass_ttbarInc_wMass_ee_stack_7,"");
   
   TH1D *zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8 = new TH1D("zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8","zPairMass_zPlusJetsMadgraph_wMass_ee",20,50,140);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->SetBinContent(5,6.968028);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->SetBinContent(6,39.31016);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->SetBinContent(7,72.10781);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->SetBinContent(8,211.7359);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->SetBinContent(9,1138.228);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->SetBinContent(10,1314.311);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->SetBinContent(11,253.1926);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->SetBinContent(12,43.26316);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->SetBinContent(13,33.74005);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->SetBinContent(14,8.297511);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->SetEntries(2448);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->SetFillColor(ci);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->GetXaxis()->SetTitle("m_{ll} (GeV/c^{2})");
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->GetXaxis()->SetLabelFont(42);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->GetXaxis()->SetLabelSize(0.035);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->GetXaxis()->SetTitleSize(0.035);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->GetXaxis()->SetTitleFont(42);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->GetYaxis()->SetLabelFont(42);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->GetYaxis()->SetLabelSize(0.035);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->GetYaxis()->SetTitleSize(0.035);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->GetYaxis()->SetTitleFont(42);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->GetZaxis()->SetLabelFont(42);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->GetZaxis()->SetLabelSize(0.035);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->GetZaxis()->SetTitleSize(0.035);
   zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8->GetZaxis()->SetTitleFont(42);
   zPairMass_NPL_ee_wMass_ee->Add(zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8,"");
   
   TH1D *zPairMass_NPL_ee_wMass_ee_stack_9 = new TH1D("zPairMass_NPL_ee_wMass_ee_stack_9","zPairMass_NPL_ee_wMass_ee",20,50,140);
   zPairMass_NPL_ee_wMass_ee_stack_9->SetBinContent(5,1.701555);
   zPairMass_NPL_ee_wMass_ee_stack_9->SetBinContent(6,6.46123);
   zPairMass_NPL_ee_wMass_ee_stack_9->SetBinContent(7,6.134782);
   zPairMass_NPL_ee_wMass_ee_stack_9->SetBinContent(8,6.459122);
   zPairMass_NPL_ee_wMass_ee_stack_9->SetBinContent(9,13.15623);
   zPairMass_NPL_ee_wMass_ee_stack_9->SetBinContent(10,15.99319);
   zPairMass_NPL_ee_wMass_ee_stack_9->SetBinContent(11,4.746185);
   zPairMass_NPL_ee_wMass_ee_stack_9->SetBinContent(12,3.682344);
   zPairMass_NPL_ee_wMass_ee_stack_9->SetBinContent(13,6.607062);
   zPairMass_NPL_ee_wMass_ee_stack_9->SetBinContent(14,0.8380105);
   zPairMass_NPL_ee_wMass_ee_stack_9->SetEntries(7506);
   zPairMass_NPL_ee_wMass_ee_stack_9->SetDirectory(0);

   ci = TColor::GetColor("#660066");
   zPairMass_NPL_ee_wMass_ee_stack_9->SetFillColor(ci);
   zPairMass_NPL_ee_wMass_ee_stack_9->GetXaxis()->SetTitle("m_{ll} (GeV/c^{2})");
   zPairMass_NPL_ee_wMass_ee_stack_9->GetXaxis()->SetLabelFont(42);
   zPairMass_NPL_ee_wMass_ee_stack_9->GetXaxis()->SetLabelSize(0.035);
   zPairMass_NPL_ee_wMass_ee_stack_9->GetXaxis()->SetTitleSize(0.035);
   zPairMass_NPL_ee_wMass_ee_stack_9->GetXaxis()->SetTitleFont(42);
   zPairMass_NPL_ee_wMass_ee_stack_9->GetYaxis()->SetLabelFont(42);
   zPairMass_NPL_ee_wMass_ee_stack_9->GetYaxis()->SetLabelSize(0.035);
   zPairMass_NPL_ee_wMass_ee_stack_9->GetYaxis()->SetTitleSize(0.035);
   zPairMass_NPL_ee_wMass_ee_stack_9->GetYaxis()->SetTitleFont(42);
   zPairMass_NPL_ee_wMass_ee_stack_9->GetZaxis()->SetLabelFont(42);
   zPairMass_NPL_ee_wMass_ee_stack_9->GetZaxis()->SetLabelSize(0.035);
   zPairMass_NPL_ee_wMass_ee_stack_9->GetZaxis()->SetTitleSize(0.035);
   zPairMass_NPL_ee_wMass_ee_stack_9->GetZaxis()->SetTitleFont(42);
   zPairMass_NPL_ee_wMass_ee->Add(zPairMass_NPL_ee_wMass_ee_stack_9,"");
   zPairMass_NPL_ee_wMass_ee->Draw("");
   
   TH1D *zPairMass_data_wMass_ee__1 = new TH1D("zPairMass_data_wMass_ee__1","zPairMass_data_wMass_ee",20,50,140);
   zPairMass_data_wMass_ee__1->SetBinContent(5,59);
   zPairMass_data_wMass_ee__1->SetBinContent(6,208);
   zPairMass_data_wMass_ee__1->SetBinContent(7,279);
   zPairMass_data_wMass_ee__1->SetBinContent(8,449);
   zPairMass_data_wMass_ee__1->SetBinContent(9,1522);
   zPairMass_data_wMass_ee__1->SetBinContent(10,1777);
   zPairMass_data_wMass_ee__1->SetBinContent(11,457);
   zPairMass_data_wMass_ee__1->SetBinContent(12,235);
   zPairMass_data_wMass_ee__1->SetBinContent(13,198);
   zPairMass_data_wMass_ee__1->SetBinContent(14,90);
   zPairMass_data_wMass_ee__1->SetEntries(5274);
   zPairMass_data_wMass_ee__1->SetDirectory(0);
   zPairMass_data_wMass_ee__1->SetFillColor(1);
   zPairMass_data_wMass_ee__1->SetMarkerStyle(20);
   zPairMass_data_wMass_ee__1->SetMarkerSize(0.9);
   zPairMass_data_wMass_ee__1->GetXaxis()->SetTitle("m_{ll} (GeV/c^{2})");
   zPairMass_data_wMass_ee__1->GetXaxis()->SetLabelFont(42);
   zPairMass_data_wMass_ee__1->GetXaxis()->SetLabelSize(0.035);
   zPairMass_data_wMass_ee__1->GetXaxis()->SetTitleSize(0.035);
   zPairMass_data_wMass_ee__1->GetXaxis()->SetTitleFont(42);
   zPairMass_data_wMass_ee__1->GetYaxis()->SetLabelFont(42);
   zPairMass_data_wMass_ee__1->GetYaxis()->SetLabelSize(0.035);
   zPairMass_data_wMass_ee__1->GetYaxis()->SetTitleSize(0.035);
   zPairMass_data_wMass_ee__1->GetYaxis()->SetTitleFont(42);
   zPairMass_data_wMass_ee__1->GetZaxis()->SetLabelFont(42);
   zPairMass_data_wMass_ee__1->GetZaxis()->SetLabelSize(0.035);
   zPairMass_data_wMass_ee__1->GetZaxis()->SetTitleSize(0.035);
   zPairMass_data_wMass_ee__1->GetZaxis()->SetTitleFont(42);
   zPairMass_data_wMass_ee__1->Draw("e x0, same");
   
   TLegend *leg = new TLegend(0.72,0.62,0.98,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("zPairMass_NPL_ee_wMass_ee_stack_9","NPL","f");

   ci = TColor::GetColor("#660066");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("zPairMass_zPlusJetsMadgraph_wMass_ee_stack_8","Z+jets","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("zPairMass_ttbarInc_wMass_ee_stack_7","t#bar{t}","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("zPairMass_SingleTop_wMass_ee_stack_6","Single top","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("zPairMass_VV_wMass_ee_stack_5","VV","f");

   ci = TColor::GetColor("#ffcc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("zPairMass_VVV_wMass_ee_stack_4","VVV","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("zPairMass_wJets_wMass_ee_stack_3","w+jets","f");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("zPairMass_ttV_wMass_ee_stack_2","ttV","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("zPairMass_tZq_wMass_ee_stack_1","tZq","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("zPairMass_data_wMass_ee","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.9);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.96,0.936,"35.86 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.048);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.12,0.936,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *zPairMass_NPL_ee_wMass_ee__2 = new TH1F("zPairMass_NPL_ee_wMass_ee__2","Invariant Z Mass",20,50,140);
   zPairMass_NPL_ee_wMass_ee__2->SetMinimum(0);
   zPairMass_NPL_ee_wMass_ee__2->SetMaximum(2052.435);
   zPairMass_NPL_ee_wMass_ee__2->SetDirectory(0);
   zPairMass_NPL_ee_wMass_ee__2->SetStats(0);
   zPairMass_NPL_ee_wMass_ee__2->SetLineStyle(0);
   zPairMass_NPL_ee_wMass_ee__2->SetMarkerStyle(20);
   zPairMass_NPL_ee_wMass_ee__2->GetXaxis()->SetTitle("m_{ll} (GeV/c^{2})");
   zPairMass_NPL_ee_wMass_ee__2->GetXaxis()->SetNdivisions(506);
   zPairMass_NPL_ee_wMass_ee__2->GetXaxis()->SetLabelFont(42);
   zPairMass_NPL_ee_wMass_ee__2->GetXaxis()->SetLabelOffset(999);
   zPairMass_NPL_ee_wMass_ee__2->GetXaxis()->SetLabelSize(0.05);
   zPairMass_NPL_ee_wMass_ee__2->GetXaxis()->SetTitleSize(0.06);
   zPairMass_NPL_ee_wMass_ee__2->GetXaxis()->SetTitleOffset(0.9);
   zPairMass_NPL_ee_wMass_ee__2->GetXaxis()->SetTitleFont(42);
   zPairMass_NPL_ee_wMass_ee__2->GetYaxis()->SetTitle("Events");
   zPairMass_NPL_ee_wMass_ee__2->GetYaxis()->SetNdivisions(506);
   zPairMass_NPL_ee_wMass_ee__2->GetYaxis()->SetLabelFont(42);
   zPairMass_NPL_ee_wMass_ee__2->GetYaxis()->SetLabelOffset(0.007);
   zPairMass_NPL_ee_wMass_ee__2->GetYaxis()->SetLabelSize(0.05);
   zPairMass_NPL_ee_wMass_ee__2->GetYaxis()->SetTitleSize(0.06);
   zPairMass_NPL_ee_wMass_ee__2->GetYaxis()->SetTitleOffset(1.032);
   zPairMass_NPL_ee_wMass_ee__2->GetYaxis()->SetTitleFont(42);
   zPairMass_NPL_ee_wMass_ee__2->GetZaxis()->SetLabelFont(42);
   zPairMass_NPL_ee_wMass_ee__2->GetZaxis()->SetLabelOffset(0.007);
   zPairMass_NPL_ee_wMass_ee__2->GetZaxis()->SetLabelSize(0.05);
   zPairMass_NPL_ee_wMass_ee__2->GetZaxis()->SetTitleSize(0.06);
   zPairMass_NPL_ee_wMass_ee__2->GetZaxis()->SetTitleFont(42);
   zPairMass_NPL_ee_wMass_ee__2->Draw("sameaxis");
   
   TPaveText *pt = new TPaveText(0.3896215,0.94,0.6103785,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Invariant Z Mass");
   pt->Draw();
   canvy_1->Modified();
   zPairMass_NPL_ee_wMass_ee_2016->cd();
  
// ------------>Primitives in pad: canvy_2
   TPad *canvy_2 = new TPad("canvy_2", "newpad2",0.01,0.01,0.99,0.3275);
   canvy_2->Draw();
   canvy_2->cd();
   canvy_2->Range(37.14286,0.1227545,144.2857,1.61976);
   canvy_2->SetFillColor(0);
   canvy_2->SetBorderMode(0);
   canvy_2->SetBorderSize(2);
   canvy_2->SetGridy();
   canvy_2->SetLeftMargin(0.12);
   canvy_2->SetRightMargin(0.04);
   canvy_2->SetTopMargin(0.08);
   canvy_2->SetBottomMargin(0.252);
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   
   TH1D *zPairMass_data_wMass_ee__3 = new TH1D("zPairMass_data_wMass_ee__3","",20,50,140);
   zPairMass_data_wMass_ee__3->SetBinContent(5,0.8383465);
   zPairMass_data_wMass_ee__3->SetBinContent(6,0.835971);
   zPairMass_data_wMass_ee__3->SetBinContent(7,0.9863155);
   zPairMass_data_wMass_ee__3->SetBinContent(8,1.024684);
   zPairMass_data_wMass_ee__3->SetBinContent(9,1.062275);
   zPairMass_data_wMass_ee__3->SetBinContent(10,1.094259);
   zPairMass_data_wMass_ee__3->SetBinContent(11,0.9583743);
   zPairMass_data_wMass_ee__3->SetBinContent(12,1.021057);
   zPairMass_data_wMass_ee__3->SetBinContent(13,0.8537305);
   zPairMass_data_wMass_ee__3->SetBinContent(14,0.8490815);
   zPairMass_data_wMass_ee__3->SetBinError(5,0.1479828);
   zPairMass_data_wMass_ee__3->SetBinError(6,0.07854028);
   zPairMass_data_wMass_ee__3->SetBinError(7,0.08322194);
   zPairMass_data_wMass_ee__3->SetBinError(8,0.06880906);
   zPairMass_data_wMass_ee__3->SetBinError(9,0.03910237);
   zPairMass_data_wMass_ee__3->SetBinError(10,0.03756571);
   zPairMass_data_wMass_ee__3->SetBinError(11,0.06273717);
   zPairMass_data_wMass_ee__3->SetBinError(12,0.09469025);
   zPairMass_data_wMass_ee__3->SetBinError(13,0.08260598);
   zPairMass_data_wMass_ee__3->SetBinError(14,0.1217044);
   zPairMass_data_wMass_ee__3->SetMinimum(0.5);
   zPairMass_data_wMass_ee__3->SetMaximum(1.5);
   zPairMass_data_wMass_ee__3->SetEntries(1174.886);
   zPairMass_data_wMass_ee__3->SetDirectory(0);
   zPairMass_data_wMass_ee__3->SetStats(0);
   zPairMass_data_wMass_ee__3->SetFillColor(1);
   zPairMass_data_wMass_ee__3->SetMarkerStyle(20);
   zPairMass_data_wMass_ee__3->SetMarkerSize(0.85);
   zPairMass_data_wMass_ee__3->GetXaxis()->SetTitle("m_{ll} (GeV/c^{2})");
   zPairMass_data_wMass_ee__3->GetXaxis()->SetNdivisions(506);
   zPairMass_data_wMass_ee__3->GetXaxis()->SetLabelFont(42);
   zPairMass_data_wMass_ee__3->GetXaxis()->SetLabelOffset(0.018);
   zPairMass_data_wMass_ee__3->GetXaxis()->SetLabelSize(0.104);
   zPairMass_data_wMass_ee__3->GetXaxis()->SetTitleSize(0.11);
   zPairMass_data_wMass_ee__3->GetXaxis()->SetTitleFont(42);
   zPairMass_data_wMass_ee__3->GetYaxis()->SetTitle("data/MC");
   zPairMass_data_wMass_ee__3->GetYaxis()->CenterTitle(true);
   zPairMass_data_wMass_ee__3->GetYaxis()->SetNdivisions(506);
   zPairMass_data_wMass_ee__3->GetYaxis()->SetLabelFont(42);
   zPairMass_data_wMass_ee__3->GetYaxis()->SetLabelSize(0.06);
   zPairMass_data_wMass_ee__3->GetYaxis()->SetTitleSize(0.12);
   zPairMass_data_wMass_ee__3->GetYaxis()->SetTitleOffset(0.36);
   zPairMass_data_wMass_ee__3->GetYaxis()->SetTitleFont(42);
   zPairMass_data_wMass_ee__3->GetZaxis()->SetLabelFont(42);
   zPairMass_data_wMass_ee__3->GetZaxis()->SetLabelSize(0.035);
   zPairMass_data_wMass_ee__3->GetZaxis()->SetTitleSize(0.035);
   zPairMass_data_wMass_ee__3->GetZaxis()->SetTitleFont(42);
   zPairMass_data_wMass_ee__3->Draw("e x0, SCAT");
   canvy_2->Modified();
   zPairMass_NPL_ee_wMass_ee_2016->cd();
   zPairMass_NPL_ee_wMass_ee_2016->Modified();
   zPairMass_NPL_ee_wMass_ee_2016->cd();
   zPairMass_NPL_ee_wMass_ee_2016->SetSelected(zPairMass_NPL_ee_wMass_ee_2016);
}
