void fourthJetEta_SingleTop_wMass()
{
//=========Macro generated from canvas: fourthJetEta_SingleTop_wMass/fourthJetEta_SingleTop_wMass
//=========  (Wed Aug 21 19:46:20 2019) by ROOT version 6.18/00

   // Set up cavas
   int W = 1280;
   int H = 1024;
   int H_ref = 925;
   int W_ref = 1024;

   // references for T, B, L, R
   float T = 0.08*H_ref;
   float B = 0.12*H_ref;
   float L = 0.12*W_ref;
   float R = 0.04*W_ref;

   TCanvas *c1 = new TCanvas("c1","c1",50,50,W,H);
   c1->cd();
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetLeftMargin( L/W );
   c1->SetRightMargin( R/W );
   c1->SetTopMargin( T/H );
   c1->SetBottomMargin( B/H );
   c1->SetTickx(0);
   c1->SetTicky(0);
  
// ------------>Primitives in pad: canvy_1
   TPad *canvy_1 = new TPad("canvy_1", "newpad",0.01,0.315,0.99,0.99);
   canvy_1->Draw();
   canvy_1->cd();
   canvy_1->SetFillColor(0);
   canvy_1->SetBorderMode(0);

   canvy_1->SetLeftMargin( L/W );
   canvy_1->SetRightMargin( R/W );
   canvy_1->SetTopMargin( T/H );
   canvy_1->SetBottomMargin( B/H * 0.3 );

   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);
   
   THStack *fourthJetEta_SingleTop_wMass_emu = new THStack();
   fourthJetEta_SingleTop_wMass_emu->SetName("fourthJetEta_SingleTop_wMass_emu");
   fourthJetEta_SingleTop_wMass_emu->SetTitle("Fourth Jet #eta;Fourth jet #eta;Events");
   fourthJetEta_SingleTop_wMass_emu->SetMaximum(128.7);
   
   TH1F *fourthJetEta_SingleTop_wMass_emu_stack_1 = new TH1F("fourthJetEta_SingleTop_wMass_emu_stack_1","Fourth Jet #eta",25,0,5);
   fourthJetEta_SingleTop_wMass_emu_stack_1->SetMinimum(0);
   fourthJetEta_SingleTop_wMass_emu_stack_1->SetMaximum(135.135);
   fourthJetEta_SingleTop_wMass_emu_stack_1->SetDirectory(0);
   fourthJetEta_SingleTop_wMass_emu_stack_1->SetStats(0);
   fourthJetEta_SingleTop_wMass_emu_stack_1->SetLineStyle(0);
   fourthJetEta_SingleTop_wMass_emu_stack_1->SetLineWidth(0);
   fourthJetEta_SingleTop_wMass_emu_stack_1->SetMarkerStyle(20);
   fourthJetEta_SingleTop_wMass_emu_stack_1->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_SingleTop_wMass_emu_stack_1->GetXaxis()->SetNdivisions(506);
   fourthJetEta_SingleTop_wMass_emu_stack_1->GetXaxis()->SetLabelFont(42);
   fourthJetEta_SingleTop_wMass_emu_stack_1->GetXaxis()->SetLabelOffset(999);
   fourthJetEta_SingleTop_wMass_emu_stack_1->GetXaxis()->SetLabelSize(0.05);
   fourthJetEta_SingleTop_wMass_emu_stack_1->GetXaxis()->SetTitleSize(0.08);
   fourthJetEta_SingleTop_wMass_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_SingleTop_wMass_emu_stack_1->GetXaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_wMass_emu_stack_1->GetYaxis()->SetTitle("Events");
   fourthJetEta_SingleTop_wMass_emu_stack_1->GetYaxis()->SetNdivisions(506);
   fourthJetEta_SingleTop_wMass_emu_stack_1->GetYaxis()->SetLabelFont(42);
   fourthJetEta_SingleTop_wMass_emu_stack_1->GetYaxis()->SetLabelOffset(0.01);
   fourthJetEta_SingleTop_wMass_emu_stack_1->GetYaxis()->SetLabelSize(0.062);
   fourthJetEta_SingleTop_wMass_emu_stack_1->GetYaxis()->SetTitleSize(0.08);
   fourthJetEta_SingleTop_wMass_emu_stack_1->GetYaxis()->SetTitleOffset(0.6336);
   fourthJetEta_SingleTop_wMass_emu_stack_1->GetYaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_wMass_emu_stack_1->GetZaxis()->SetLabelFont(42);
   fourthJetEta_SingleTop_wMass_emu_stack_1->GetZaxis()->SetLabelOffset(0.007);
   fourthJetEta_SingleTop_wMass_emu_stack_1->GetZaxis()->SetLabelSize(0.05);
   fourthJetEta_SingleTop_wMass_emu_stack_1->GetZaxis()->SetTitleSize(0.08);
   fourthJetEta_SingleTop_wMass_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_SingleTop_wMass_emu_stack_1->GetZaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_wMass_emu->SetHistogram(fourthJetEta_SingleTop_wMass_emu_stack_1);
   
   
   TH1D *fourthJetEta_tZq_wMass_emu_stack_1 = new TH1D("fourthJetEta_tZq_wMass_emu_stack_1","fourthJetEta_tZq_wMass_emu",25,0,5);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(0,0.1727892);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(1,0.01721364);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(2,0.004116502);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(3,0.01580993);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(4,0.006432242);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(5,0.01627106);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(6,0.007380867);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(7,-0.0007639604);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(8,0.01003733);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(9,0.01359666);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(10,0.006979631);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(11,0.01340239);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(12,0.01570412);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(13,0.004780682);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(14,0.01131244);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(15,0.008278046);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(16,0.006300183);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(17,0.0008746511);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(18,0.003994055);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(19,0.004694355);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(20,0.004998137);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(21,0.0009693964);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(22,0.0004018593);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(23,0.0001441664);
   fourthJetEta_tZq_wMass_emu_stack_1->SetBinContent(24,-0.001309188);
   fourthJetEta_tZq_wMass_emu_stack_1->SetEntries(2170);
   fourthJetEta_tZq_wMass_emu_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ffff00");
   fourthJetEta_tZq_wMass_emu_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   fourthJetEta_tZq_wMass_emu_stack_1->SetLineColor(ci);
   fourthJetEta_tZq_wMass_emu_stack_1->SetLineWidth(0);
   fourthJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetLabelFont(42);
   fourthJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetLabelSize(0.035);
   fourthJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleSize(0.035);
   fourthJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleFont(42);
   fourthJetEta_tZq_wMass_emu_stack_1->GetYaxis()->SetLabelFont(42);
   fourthJetEta_tZq_wMass_emu_stack_1->GetYaxis()->SetLabelSize(0.035);
   fourthJetEta_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleSize(0.035);
   fourthJetEta_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleOffset(1);
   fourthJetEta_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleFont(42);
   fourthJetEta_tZq_wMass_emu_stack_1->GetZaxis()->SetLabelFont(42);
   fourthJetEta_tZq_wMass_emu_stack_1->GetZaxis()->SetLabelSize(0.035);
   fourthJetEta_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleSize(0.035);
   fourthJetEta_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_wMass_emu->Add(fourthJetEta_tZq_wMass_emu_stack_1,"");
   
   TH1D *fourthJetEta_ttV_wMass_emu_stack_2 = new TH1D("fourthJetEta_ttV_wMass_emu_stack_2","fourthJetEta_ttV_wMass_emu",25,0,5);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(0,13.98283);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(1,1.328764);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(2,1.588534);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(3,1.30034);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(4,1.755512);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(5,1.172528);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(6,0.7463471);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(7,1.000874);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(8,1.102563);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(9,0.6792122);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(10,0.6019729);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(11,0.4511124);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(12,0.5927888);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(13,0.3568562);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(14,0.4319443);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(15,0.1494709);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(16,0.1219124);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(17,0.1914889);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(18,0.1089614);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(19,0.0481394);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(20,0.01799033);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(21,0.01575733);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(22,0.1279819);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(23,0.00507069);
   fourthJetEta_ttV_wMass_emu_stack_2->SetBinContent(24,0.0002170024);
   fourthJetEta_ttV_wMass_emu_stack_2->SetEntries(14144);
   fourthJetEta_ttV_wMass_emu_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#00ff00");
   fourthJetEta_ttV_wMass_emu_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   fourthJetEta_ttV_wMass_emu_stack_2->SetLineColor(ci);
   fourthJetEta_ttV_wMass_emu_stack_2->SetLineWidth(0);
   fourthJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetLabelFont(42);
   fourthJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetLabelSize(0.035);
   fourthJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleSize(0.035);
   fourthJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleFont(42);
   fourthJetEta_ttV_wMass_emu_stack_2->GetYaxis()->SetLabelFont(42);
   fourthJetEta_ttV_wMass_emu_stack_2->GetYaxis()->SetLabelSize(0.035);
   fourthJetEta_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleSize(0.035);
   fourthJetEta_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleOffset(1);
   fourthJetEta_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleFont(42);
   fourthJetEta_ttV_wMass_emu_stack_2->GetZaxis()->SetLabelFont(42);
   fourthJetEta_ttV_wMass_emu_stack_2->GetZaxis()->SetLabelSize(0.035);
   fourthJetEta_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleSize(0.035);
   fourthJetEta_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_wMass_emu->Add(fourthJetEta_ttV_wMass_emu_stack_2,"");
   
   TH1D *fourthJetEta_wJets_wMass_emu_stack_3 = new TH1D("fourthJetEta_wJets_wMass_emu_stack_3","fourthJetEta_wJets_wMass_emu",25,0,5);
   fourthJetEta_wJets_wMass_emu_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   fourthJetEta_wJets_wMass_emu_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#cccccc");
   fourthJetEta_wJets_wMass_emu_stack_3->SetLineColor(ci);
   fourthJetEta_wJets_wMass_emu_stack_3->SetLineWidth(0);
   fourthJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetLabelFont(42);
   fourthJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetLabelSize(0.035);
   fourthJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleSize(0.035);
   fourthJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleFont(42);
   fourthJetEta_wJets_wMass_emu_stack_3->GetYaxis()->SetLabelFont(42);
   fourthJetEta_wJets_wMass_emu_stack_3->GetYaxis()->SetLabelSize(0.035);
   fourthJetEta_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleSize(0.035);
   fourthJetEta_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleOffset(1);
   fourthJetEta_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleFont(42);
   fourthJetEta_wJets_wMass_emu_stack_3->GetZaxis()->SetLabelFont(42);
   fourthJetEta_wJets_wMass_emu_stack_3->GetZaxis()->SetLabelSize(0.035);
   fourthJetEta_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleSize(0.035);
   fourthJetEta_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_wMass_emu->Add(fourthJetEta_wJets_wMass_emu_stack_3,"");
   
   TH1D *fourthJetEta_VVV_wMass_emu_stack_4 = new TH1D("fourthJetEta_VVV_wMass_emu_stack_4","fourthJetEta_VVV_wMass_emu",25,0,5);
   fourthJetEta_VVV_wMass_emu_stack_4->SetBinContent(0,0.1558246);
   fourthJetEta_VVV_wMass_emu_stack_4->SetBinContent(3,0.033447);
   fourthJetEta_VVV_wMass_emu_stack_4->SetBinContent(5,0.001068281);
   fourthJetEta_VVV_wMass_emu_stack_4->SetBinContent(9,0.03392089);
   fourthJetEta_VVV_wMass_emu_stack_4->SetEntries(9);
   fourthJetEta_VVV_wMass_emu_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#00ffff");
   fourthJetEta_VVV_wMass_emu_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   fourthJetEta_VVV_wMass_emu_stack_4->SetLineColor(ci);
   fourthJetEta_VVV_wMass_emu_stack_4->SetLineWidth(0);
   fourthJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetLabelFont(42);
   fourthJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetLabelSize(0.035);
   fourthJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleSize(0.035);
   fourthJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleFont(42);
   fourthJetEta_VVV_wMass_emu_stack_4->GetYaxis()->SetLabelFont(42);
   fourthJetEta_VVV_wMass_emu_stack_4->GetYaxis()->SetLabelSize(0.035);
   fourthJetEta_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleSize(0.035);
   fourthJetEta_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleOffset(1);
   fourthJetEta_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleFont(42);
   fourthJetEta_VVV_wMass_emu_stack_4->GetZaxis()->SetLabelFont(42);
   fourthJetEta_VVV_wMass_emu_stack_4->GetZaxis()->SetLabelSize(0.035);
   fourthJetEta_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleSize(0.035);
   fourthJetEta_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_wMass_emu->Add(fourthJetEta_VVV_wMass_emu_stack_4,"");
   
   TH1D *fourthJetEta_VV_wMass_emu_stack_5 = new TH1D("fourthJetEta_VV_wMass_emu_stack_5","fourthJetEta_VV_wMass_emu",25,0,5);
   fourthJetEta_VV_wMass_emu_stack_5->SetBinContent(0,1.455054);
   fourthJetEta_VV_wMass_emu_stack_5->SetBinContent(2,0.01678233);
   fourthJetEta_VV_wMass_emu_stack_5->SetBinContent(4,0.1348043);
   fourthJetEta_VV_wMass_emu_stack_5->SetBinContent(5,0.0001309747);
   fourthJetEta_VV_wMass_emu_stack_5->SetBinContent(6,0.006017765);
   fourthJetEta_VV_wMass_emu_stack_5->SetBinContent(8,0.006056648);
   fourthJetEta_VV_wMass_emu_stack_5->SetBinContent(9,0.004911191);
   fourthJetEta_VV_wMass_emu_stack_5->SetBinContent(10,0.2120378);
   fourthJetEta_VV_wMass_emu_stack_5->SetBinContent(12,-0.01229277);
   fourthJetEta_VV_wMass_emu_stack_5->SetBinContent(13,0.1753542);
   fourthJetEta_VV_wMass_emu_stack_5->SetBinContent(15,0.1531415);
   fourthJetEta_VV_wMass_emu_stack_5->SetBinContent(17,0.1942798);
   fourthJetEta_VV_wMass_emu_stack_5->SetBinContent(18,0.1333407);
   fourthJetEta_VV_wMass_emu_stack_5->SetEntries(45);
   fourthJetEta_VV_wMass_emu_stack_5->SetDirectory(0);

   ci = TColor::GetColor("#ff9933");
   fourthJetEta_VV_wMass_emu_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#ff9933");
   fourthJetEta_VV_wMass_emu_stack_5->SetLineColor(ci);
   fourthJetEta_VV_wMass_emu_stack_5->SetLineWidth(0);
   fourthJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetLabelFont(42);
   fourthJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetLabelSize(0.035);
   fourthJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetTitleSize(0.035);
   fourthJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetTitleFont(42);
   fourthJetEta_VV_wMass_emu_stack_5->GetYaxis()->SetLabelFont(42);
   fourthJetEta_VV_wMass_emu_stack_5->GetYaxis()->SetLabelSize(0.035);
   fourthJetEta_VV_wMass_emu_stack_5->GetYaxis()->SetTitleSize(0.035);
   fourthJetEta_VV_wMass_emu_stack_5->GetYaxis()->SetTitleOffset(1);
   fourthJetEta_VV_wMass_emu_stack_5->GetYaxis()->SetTitleFont(42);
   fourthJetEta_VV_wMass_emu_stack_5->GetZaxis()->SetLabelFont(42);
   fourthJetEta_VV_wMass_emu_stack_5->GetZaxis()->SetLabelSize(0.035);
   fourthJetEta_VV_wMass_emu_stack_5->GetZaxis()->SetTitleSize(0.035);
   fourthJetEta_VV_wMass_emu_stack_5->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_VV_wMass_emu_stack_5->GetZaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_wMass_emu->Add(fourthJetEta_VV_wMass_emu_stack_5,"");
   
   TH1D *fourthJetEta_SingleTop_wMass_emu_stack_6 = new TH1D("fourthJetEta_SingleTop_wMass_emu_stack_6","fourthJetEta_SingleTop_wMass_emu",25,0,5);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(0,55.73033);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(1,4.359764);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(2,4.70548);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(3,3.273698);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(4,4.820623);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(5,3.697101);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(6,3.456542);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(7,3.692351);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(8,3.000225);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(9,2.796358);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(10,1.336907);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(11,2.276647);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(12,1.294495);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(13,0.7929915);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(14,1.907174);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(15,2.336128);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(16,1.501489);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(17,1.155869);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(18,0.5256967);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(19,0.5665912);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(20,0.5398841);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(21,0.5317419);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(22,0.2512019);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(23,0.1848398);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetEntries(1034);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetDirectory(0);

   ci = TColor::GetColor("#ff00ff");
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetLineColor(ci);
   fourthJetEta_SingleTop_wMass_emu_stack_6->SetLineWidth(0);
   fourthJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetLabelFont(42);
   fourthJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetLabelSize(0.035);
   fourthJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleSize(0.035);
   fourthJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_wMass_emu_stack_6->GetYaxis()->SetLabelFont(42);
   fourthJetEta_SingleTop_wMass_emu_stack_6->GetYaxis()->SetLabelSize(0.035);
   fourthJetEta_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleSize(0.035);
   fourthJetEta_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleOffset(1);
   fourthJetEta_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_wMass_emu_stack_6->GetZaxis()->SetLabelFont(42);
   fourthJetEta_SingleTop_wMass_emu_stack_6->GetZaxis()->SetLabelSize(0.035);
   fourthJetEta_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleSize(0.035);
   fourthJetEta_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_wMass_emu->Add(fourthJetEta_SingleTop_wMass_emu_stack_6,"");
   
   TH1D *fourthJetEta_tt_wMass_emu_stack_7 = new TH1D("fourthJetEta_tt_wMass_emu_stack_7","fourthJetEta_tt_wMass_emu",25,0,5);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(0,1198.1);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(1,102.438);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(2,106.675);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(3,101.1703);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(4,108.1614);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(5,93.64329);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(6,87.50361);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(7,77.52077);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(8,65.87605);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(9,68.52386);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(10,59.33964);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(11,57.96611);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(12,49.53651);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(13,42.18547);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(14,49.68749);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(15,38.17191);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(16,20.07927);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(17,23.79752);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(18,12.22431);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(19,11.42121);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(20,8.686697);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(21,7.725602);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(22,5.294514);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(23,3.64566);
   fourthJetEta_tt_wMass_emu_stack_7->SetBinContent(24,1.405117);
   fourthJetEta_tt_wMass_emu_stack_7->SetEntries(7802);
   fourthJetEta_tt_wMass_emu_stack_7->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   fourthJetEta_tt_wMass_emu_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   fourthJetEta_tt_wMass_emu_stack_7->SetLineColor(ci);
   fourthJetEta_tt_wMass_emu_stack_7->SetLineWidth(0);
   fourthJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetLabelFont(42);
   fourthJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetLabelSize(0.035);
   fourthJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetTitleSize(0.035);
   fourthJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetTitleFont(42);
   fourthJetEta_tt_wMass_emu_stack_7->GetYaxis()->SetLabelFont(42);
   fourthJetEta_tt_wMass_emu_stack_7->GetYaxis()->SetLabelSize(0.035);
   fourthJetEta_tt_wMass_emu_stack_7->GetYaxis()->SetTitleSize(0.035);
   fourthJetEta_tt_wMass_emu_stack_7->GetYaxis()->SetTitleOffset(1);
   fourthJetEta_tt_wMass_emu_stack_7->GetYaxis()->SetTitleFont(42);
   fourthJetEta_tt_wMass_emu_stack_7->GetZaxis()->SetLabelFont(42);
   fourthJetEta_tt_wMass_emu_stack_7->GetZaxis()->SetLabelSize(0.035);
   fourthJetEta_tt_wMass_emu_stack_7->GetZaxis()->SetTitleSize(0.035);
   fourthJetEta_tt_wMass_emu_stack_7->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_tt_wMass_emu_stack_7->GetZaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_wMass_emu->Add(fourthJetEta_tt_wMass_emu_stack_7,"");
   
   TH1D *fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8 = new TH1D("fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8","fourthJetEta_zPlusJetsMadgraph_wMass_emu",25,0,5);
   fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->SetLineColor(ci);
   fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->SetLineWidth(0);
   fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetLabelFont(42);
   fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetLabelSize(0.035);
   fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleSize(0.035);
   fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleFont(42);
   fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetLabelFont(42);
   fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetLabelSize(0.035);
   fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleSize(0.035);
   fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleOffset(1);
   fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleFont(42);
   fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetLabelFont(42);
   fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetLabelSize(0.035);
   fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleSize(0.035);
   fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_wMass_emu->Add(fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8,"");
   fourthJetEta_SingleTop_wMass_emu->Draw("");
   
   TH1D *fourthJetEta_data_wMass_emu__1 = new TH1D("fourthJetEta_data_wMass_emu__1","fourthJetEta_data_wMass_emu",25,0,5);
   fourthJetEta_data_wMass_emu__1->SetBinContent(0,1333);
   fourthJetEta_data_wMass_emu__1->SetBinContent(1,116);
   fourthJetEta_data_wMass_emu__1->SetBinContent(2,116);
   fourthJetEta_data_wMass_emu__1->SetBinContent(3,117);
   fourthJetEta_data_wMass_emu__1->SetBinContent(4,111);
   fourthJetEta_data_wMass_emu__1->SetBinContent(5,89);
   fourthJetEta_data_wMass_emu__1->SetBinContent(6,96);
   fourthJetEta_data_wMass_emu__1->SetBinContent(7,105);
   fourthJetEta_data_wMass_emu__1->SetBinContent(8,87);
   fourthJetEta_data_wMass_emu__1->SetBinContent(9,79);
   fourthJetEta_data_wMass_emu__1->SetBinContent(10,69);
   fourthJetEta_data_wMass_emu__1->SetBinContent(11,70);
   fourthJetEta_data_wMass_emu__1->SetBinContent(12,51);
   fourthJetEta_data_wMass_emu__1->SetBinContent(13,42);
   fourthJetEta_data_wMass_emu__1->SetBinContent(14,57);
   fourthJetEta_data_wMass_emu__1->SetBinContent(15,38);
   fourthJetEta_data_wMass_emu__1->SetBinContent(16,18);
   fourthJetEta_data_wMass_emu__1->SetBinContent(17,23);
   fourthJetEta_data_wMass_emu__1->SetBinContent(18,10);
   fourthJetEta_data_wMass_emu__1->SetBinContent(19,11);
   fourthJetEta_data_wMass_emu__1->SetBinContent(20,5);
   fourthJetEta_data_wMass_emu__1->SetBinContent(21,12);
   fourthJetEta_data_wMass_emu__1->SetBinContent(22,7);
   fourthJetEta_data_wMass_emu__1->SetBinContent(23,4);
   fourthJetEta_data_wMass_emu__1->SetBinContent(24,2);
   fourthJetEta_data_wMass_emu__1->SetEntries(2668);
   fourthJetEta_data_wMass_emu__1->SetDirectory(0);
   fourthJetEta_data_wMass_emu__1->SetFillColor(1);
   fourthJetEta_data_wMass_emu__1->SetLineWidth(2);
   fourthJetEta_data_wMass_emu__1->SetLineColor(1); //
   fourthJetEta_data_wMass_emu__1->SetMarkerStyle(20);
   fourthJetEta_data_wMass_emu__1->SetMarkerSize(1.4);
   fourthJetEta_data_wMass_emu__1->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_data_wMass_emu__1->GetXaxis()->SetLabelFont(42);
   fourthJetEta_data_wMass_emu__1->GetXaxis()->SetLabelSize(0.035);
   fourthJetEta_data_wMass_emu__1->GetXaxis()->SetTitleSize(0.035);
   fourthJetEta_data_wMass_emu__1->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_data_wMass_emu__1->GetXaxis()->SetTitleFont(42);
   fourthJetEta_data_wMass_emu__1->GetYaxis()->SetLabelFont(42);
   fourthJetEta_data_wMass_emu__1->GetYaxis()->SetLabelSize(0.035);
   fourthJetEta_data_wMass_emu__1->GetYaxis()->SetTitleSize(0.035);
   fourthJetEta_data_wMass_emu__1->GetYaxis()->SetTitleOffset(1);
   fourthJetEta_data_wMass_emu__1->GetYaxis()->SetTitleFont(42);
   fourthJetEta_data_wMass_emu__1->GetZaxis()->SetLabelFont(42);
   fourthJetEta_data_wMass_emu__1->GetZaxis()->SetLabelSize(0.035);
   fourthJetEta_data_wMass_emu__1->GetZaxis()->SetTitleSize(0.035);
   fourthJetEta_data_wMass_emu__1->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_data_wMass_emu__1->GetZaxis()->SetTitleFont(42);
   fourthJetEta_data_wMass_emu__1->Draw("e x0, same");
   
   TLegend *leg = new TLegend(0.78,0.42,0.98,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("fourthJetEta_zPlusJetsMadgraph_wMass_emu_stack_8","Z+jets (LO)","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetEta_tt_wMass_emu_stack_7","t#bar{t}","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetEta_SingleTop_wMass_emu_stack_6","Single top","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetEta_VV_wMass_emu_stack_5","VV","f");

   ci = TColor::GetColor("#ff9933");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetEta_VVV_wMass_emu_stack_4","VVV","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetEta_wJets_wMass_emu_stack_3","W+jets","f");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetEta_ttV_wMass_emu_stack_2","t#bar{t}V","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetEta_tZq_wMass_emu_stack_1","tZq","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetEta_data_wMass_emu","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.4);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.968,0.9429101,"35.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06792969);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.096,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.05419922);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16899,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.04119141);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *fourthJetEta_SingleTop_wMass_emu__2 = new TH1F("fourthJetEta_SingleTop_wMass_emu__2","Fourth Jet #eta",25,0,5);
   fourthJetEta_SingleTop_wMass_emu__2->SetMinimum(0);
   fourthJetEta_SingleTop_wMass_emu__2->SetMaximum(135.135);
   fourthJetEta_SingleTop_wMass_emu__2->SetDirectory(0);
   fourthJetEta_SingleTop_wMass_emu__2->SetStats(0);
   fourthJetEta_SingleTop_wMass_emu__2->SetLineStyle(0);
   fourthJetEta_SingleTop_wMass_emu__2->SetLineWidth(0);
   fourthJetEta_SingleTop_wMass_emu__2->SetMarkerStyle(20);
   fourthJetEta_SingleTop_wMass_emu__2->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_SingleTop_wMass_emu__2->GetXaxis()->SetNdivisions(506);
   fourthJetEta_SingleTop_wMass_emu__2->GetXaxis()->SetLabelFont(42);
   fourthJetEta_SingleTop_wMass_emu__2->GetXaxis()->SetLabelOffset(999);
   fourthJetEta_SingleTop_wMass_emu__2->GetXaxis()->SetLabelSize(0.05);
   fourthJetEta_SingleTop_wMass_emu__2->GetXaxis()->SetTitleSize(0.08);
   fourthJetEta_SingleTop_wMass_emu__2->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_SingleTop_wMass_emu__2->GetXaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_wMass_emu__2->GetYaxis()->SetTitle("Events");
   fourthJetEta_SingleTop_wMass_emu__2->GetYaxis()->SetNdivisions(506);
   fourthJetEta_SingleTop_wMass_emu__2->GetYaxis()->SetLabelFont(42);
   fourthJetEta_SingleTop_wMass_emu__2->GetYaxis()->SetLabelOffset(0.01);
   fourthJetEta_SingleTop_wMass_emu__2->GetYaxis()->SetLabelSize(0.062);
   fourthJetEta_SingleTop_wMass_emu__2->GetYaxis()->SetTitleSize(0.08);
   fourthJetEta_SingleTop_wMass_emu__2->GetYaxis()->SetTitleOffset(0.6336);
   fourthJetEta_SingleTop_wMass_emu__2->GetYaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_wMass_emu__2->GetZaxis()->SetLabelFont(42);
   fourthJetEta_SingleTop_wMass_emu__2->GetZaxis()->SetLabelOffset(0.007);
   fourthJetEta_SingleTop_wMass_emu__2->GetZaxis()->SetLabelSize(0.05);
   fourthJetEta_SingleTop_wMass_emu__2->GetZaxis()->SetTitleSize(0.08);
   fourthJetEta_SingleTop_wMass_emu__2->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_SingleTop_wMass_emu__2->GetZaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_wMass_emu__2->Draw("sameaxis");
   
   TPaveText *pt = new TPaveText(0.4325122,0.9371861,0.5674878,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Fourth Jet #eta");
   pt->Draw();
   canvy_1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: canvy_2
   TPad *canvy_2 = new TPad("canvy_2", "newpad2",0.01,0.01,0.99,0.322);
   canvy_2->Draw();
   canvy_2->cd();
   canvy_2->SetFillColor(0);
   canvy_2->SetBorderMode(0);
   canvy_2->SetGridy();

   canvy_2->SetLeftMargin( L/W );
   canvy_2->SetRightMargin( R/W );
   canvy_2->SetTopMargin( T/H );
   canvy_2->SetBottomMargin( B/H * 2.6 );
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   
   TH1D *fourthJetEta_data_wMass_emu__3 = new TH1D("fourthJetEta_data_wMass_emu__3","",25,0,5);
   fourthJetEta_data_wMass_emu__3->SetBinContent(0,1.04994);
   fourthJetEta_data_wMass_emu__3->SetBinContent(1,1.072646);
   fourthJetEta_data_wMass_emu__3->SetBinContent(2,1.02664);
   fourthJetEta_data_wMass_emu__3->SetBinContent(3,1.105927);
   fourthJetEta_data_wMass_emu__3->SetBinContent(4,0.9662361);
   fourthJetEta_data_wMass_emu__3->SetBinContent(5,0.9032746);
   fourthJetEta_data_wMass_emu__3->SetBinContent(6,1.046665);
   fourthJetEta_data_wMass_emu__3->SetBinContent(7,1.277167);
   fourthJetEta_data_wMass_emu__3->SetBinContent(8,1.242947);
   fourthJetEta_data_wMass_emu__3->SetBinContent(9,1.096432);
   fourthJetEta_data_wMass_emu__3->SetBinContent(10,1.121996);
   fourthJetEta_data_wMass_emu__3->SetBinContent(11,1.153074);
   fourthJetEta_data_wMass_emu__3->SetBinContent(12,0.9916929);
   fourthJetEta_data_wMass_emu__3->SetBinContent(13,0.9651743);
   fourthJetEta_data_wMass_emu__3->SetBinContent(14,1.095355);
   fourthJetEta_data_wMass_emu__3->SetBinContent(15,0.9309405);
   fourthJetEta_data_wMass_emu__3->SetBinContent(16,0.8291503);
   fourthJetEta_data_wMass_emu__3->SetBinContent(17,0.9076548);
   fourthJetEta_data_wMass_emu__3->SetBinContent(18,0.7694498);
   fourthJetEta_data_wMass_emu__3->SetBinContent(19,0.9135729);
   fourthJetEta_data_wMass_emu__3->SetBinContent(20,0.5405657);
   fourthJetEta_data_wMass_emu__3->SetBinContent(21,1.450314);
   fourthJetEta_data_wMass_emu__3->SetBinContent(22,1.233676);
   fourthJetEta_data_wMass_emu__3->SetBinContent(23,1.04283);
   fourthJetEta_data_wMass_emu__3->SetBinContent(24,1.424477);
   fourthJetEta_data_wMass_emu__3->SetBinError(0,0.04117371);
   fourthJetEta_data_wMass_emu__3->SetBinError(1,0.1433805);
   fourthJetEta_data_wMass_emu__3->SetBinError(2,0.1356993);
   fourthJetEta_data_wMass_emu__3->SetBinError(3,0.1483731);
   fourthJetEta_data_wMass_emu__3->SetBinError(4,0.1285996);
   fourthJetEta_data_wMass_emu__3->SetBinError(5,0.1320917);
   fourthJetEta_data_wMass_emu__3->SetBinError(6,0.1528254);
   fourthJetEta_data_wMass_emu__3->SetBinError(7,0.1880833);
   fourthJetEta_data_wMass_emu__3->SetBinError(8,0.1995733);
   fourthJetEta_data_wMass_emu__3->SetBinError(9,0.1786112);
   fourthJetEta_data_wMass_emu__3->SetBinError(10,0.196761);
   fourthJetEta_data_wMass_emu__3->SetBinError(11,0.2022264);
   fourthJetEta_data_wMass_emu__3->SetBinError(12,0.1959762);
   fourthJetEta_data_wMass_emu__3->SetBinError(13,0.2087765);
   fourthJetEta_data_wMass_emu__3->SetBinError(14,0.2100131);
   fourthJetEta_data_wMass_emu__3->SetBinError(15,0.2098527);
   fourthJetEta_data_wMass_emu__3->SetBinError(16,0.2643149);
   fourthJetEta_data_wMass_emu__3->SetBinError(17,0.2614007);
   fourthJetEta_data_wMass_emu__3->SetBinError(18,0.3236677);
   fourthJetEta_data_wMass_emu__3->SetBinError(19,0.381039);
   fourthJetEta_data_wMass_emu__3->SetBinError(20,0.3000569);
   fourthJetEta_data_wMass_emu__3->SetBinError(21,0.6553635);
   fourthJetEta_data_wMass_emu__3->SetBinError(22,0.6968866);
   fourthJetEta_data_wMass_emu__3->SetBinError(23,0.7452464);
   fourthJetEta_data_wMass_emu__3->SetBinError(24,1.568373);
   fourthJetEta_data_wMass_emu__3->SetMinimum(0.5);
   fourthJetEta_data_wMass_emu__3->SetMaximum(1.5);
   fourthJetEta_data_wMass_emu__3->SetEntries(129.0834);
   fourthJetEta_data_wMass_emu__3->SetDirectory(0);
   fourthJetEta_data_wMass_emu__3->SetStats(0);
   fourthJetEta_data_wMass_emu__3->SetFillColor(1);
   fourthJetEta_data_wMass_emu__3->SetLineWidth(2);
   fourthJetEta_data_wMass_emu__3->SetLineColor(1); //
   fourthJetEta_data_wMass_emu__3->SetMarkerStyle(20);
   fourthJetEta_data_wMass_emu__3->SetMarkerSize(1.6);
   fourthJetEta_data_wMass_emu__3->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_data_wMass_emu__3->GetXaxis()->SetNdivisions(506);
   fourthJetEta_data_wMass_emu__3->GetXaxis()->SetLabelFont(42);
   fourthJetEta_data_wMass_emu__3->GetXaxis()->SetLabelOffset(0.013);
   fourthJetEta_data_wMass_emu__3->GetXaxis()->SetLabelSize(0.13);
   fourthJetEta_data_wMass_emu__3->GetXaxis()->SetTitleSize(0.13);
   fourthJetEta_data_wMass_emu__3->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_data_wMass_emu__3->GetXaxis()->SetTitleFont(42);
   fourthJetEta_data_wMass_emu__3->GetYaxis()->SetTitle("Data/MC");
   fourthJetEta_data_wMass_emu__3->GetYaxis()->CenterTitle(true);
   fourthJetEta_data_wMass_emu__3->GetYaxis()->SetNdivisions(506);
   fourthJetEta_data_wMass_emu__3->GetYaxis()->SetLabelFont(42);
   fourthJetEta_data_wMass_emu__3->GetYaxis()->SetLabelOffset(0.01);
   fourthJetEta_data_wMass_emu__3->GetYaxis()->SetLabelSize(0.12);
   fourthJetEta_data_wMass_emu__3->GetYaxis()->SetTitleSize(0.16);
   fourthJetEta_data_wMass_emu__3->GetYaxis()->SetTitleOffset(0.3);
   fourthJetEta_data_wMass_emu__3->GetYaxis()->SetTitleFont(42);
   fourthJetEta_data_wMass_emu__3->GetZaxis()->SetLabelFont(42);
   fourthJetEta_data_wMass_emu__3->GetZaxis()->SetLabelSize(0.035);
   fourthJetEta_data_wMass_emu__3->GetZaxis()->SetTitleSize(0.035);
   fourthJetEta_data_wMass_emu__3->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_data_wMass_emu__3->GetZaxis()->SetTitleFont(42);
   fourthJetEta_data_wMass_emu__3->Draw("e x0, SCAT");
   canvy_2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
//   c1->SetSelected(fourthJetEta_data_wMass_emu);
   c1->SaveAs("fourthJetEta_wMass.pdf");
}
