void fourthJetPt_SingleTop_jetSel()
{
//=========Macro generated from canvas: fourthJetPt_SingleTop_jetSel/fourthJetPt_SingleTop_jetSel
//=========  (Wed Aug 21 19:32:47 2019) by ROOT version 6.18/00

   // Set up cavas
   int W = 1280;
   int H = 1024;
   int H_ref = 925;
   int W_ref = 1024;

   // references for T, B, L, R
   float T = 0.08*H_ref;
   float B = 0.12*H_ref;
   float L = 0.12*W_ref;
   float R = 0.04*W_ref;

   TCanvas *c1 = new TCanvas("c1","c1",50,50,W,H);
   c1->cd();
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetLeftMargin( L/W );
   c1->SetRightMargin( R/W );
   c1->SetTopMargin( T/H );
   c1->SetBottomMargin( B/H );
   c1->SetTickx(0);
   c1->SetTicky(0);
  
// ------------>Primitives in pad: canvy_1
   TPad *canvy_1 = new TPad("canvy_1", "newpad",0.01,0.315,0.99,0.99);
   canvy_1->Draw();
   canvy_1->cd();
   canvy_1->SetFillColor(0);
   canvy_1->SetBorderMode(0);

   canvy_1->SetLeftMargin( L/W );
   canvy_1->SetRightMargin( R/W );
   canvy_1->SetTopMargin( T/H );
   canvy_1->SetBottomMargin( B/H * 0.3 );

   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);
   
   THStack *fourthJetPt_SingleTop_jetSel_emu = new THStack();
   fourthJetPt_SingleTop_jetSel_emu->SetName("fourthJetPt_SingleTop_jetSel_emu");
   fourthJetPt_SingleTop_jetSel_emu->SetTitle(";Fourth p_{T} (GeV);Events");
   fourthJetPt_SingleTop_jetSel_emu->SetMaximum(2473.9);
   
   TH1F *fourthJetPt_SingleTop_jetSel_emu_stack_1 = new TH1F("fourthJetPt_SingleTop_jetSel_emu_stack_1","Fourth Jet p_{T}",35,0,300);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->SetMinimum(-0.00135082);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->SetMaximum(2597.595);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->SetDirectory(0);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->SetStats(0);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->SetLineStyle(0);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->SetLineWidth(0);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->SetMarkerStyle(20);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetTitle("Fourth p_{T} (GeV)");
   fourthJetPt_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetNdivisions(506);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetLabelFont(42);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetLabelOffset(999);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetLabelSize(0.05);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetTitleSize(0.08);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetTitleFont(42);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetTitle("Events");
   fourthJetPt_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetNdivisions(506);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetLabelFont(42);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetLabelOffset(0.01);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetLabelSize(0.062);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetTitleSize(0.08);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetTitleOffset(0.6336);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetTitleFont(42);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->GetZaxis()->SetLabelFont(42);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->GetZaxis()->SetLabelOffset(0.007);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->GetZaxis()->SetLabelSize(0.05);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->GetZaxis()->SetTitleSize(0.08);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   fourthJetPt_SingleTop_jetSel_emu_stack_1->GetZaxis()->SetTitleFont(42);
   fourthJetPt_SingleTop_jetSel_emu->SetHistogram(fourthJetPt_SingleTop_jetSel_emu_stack_1);
   
   
   TH1D *fourthJetPt_tZq_jetSel_emu_stack_1 = new TH1D("fourthJetPt_tZq_jetSel_emu_stack_1","fourthJetPt_tZq_jetSel_emu",35,0,300);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(1,0.000898174);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(3,-0.0006146723);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(4,0.2501718);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(5,0.3437744);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(6,0.2282736);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(7,0.1159597);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(8,0.06161732);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(9,0.038708);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(10,0.01802527);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(11,0.01741135);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(12,0.0118433);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(13,0.009173464);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(14,0.00279318);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(15,0.005215824);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(16,-0.0003552965);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(17,0.000894747);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(18,-0.001416425);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(19,-0.00056657);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(20,-7.873977e-05);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(21,0.0006114188);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(22,0.0007787131);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(23,0.0008125707);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(24,0.0001048896);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(26,0.001462228);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(29,0.0006676422);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetBinContent(30,-0.0006732098);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetEntries(6672);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ffff00");
   fourthJetPt_tZq_jetSel_emu_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   fourthJetPt_tZq_jetSel_emu_stack_1->SetLineColor(ci);
   fourthJetPt_tZq_jetSel_emu_stack_1->SetLineWidth(0);
   fourthJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitle("Fourth p_{T} (GeV)");
   fourthJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetLabelFont(42);
   fourthJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetLabelSize(0.035);
   fourthJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleSize(0.035);
   fourthJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   fourthJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleFont(42);
   fourthJetPt_tZq_jetSel_emu_stack_1->GetYaxis()->SetLabelFont(42);
   fourthJetPt_tZq_jetSel_emu_stack_1->GetYaxis()->SetLabelSize(0.035);
   fourthJetPt_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleSize(0.035);
   fourthJetPt_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleOffset(1);
   fourthJetPt_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleFont(42);
   fourthJetPt_tZq_jetSel_emu_stack_1->GetZaxis()->SetLabelFont(42);
   fourthJetPt_tZq_jetSel_emu_stack_1->GetZaxis()->SetLabelSize(0.035);
   fourthJetPt_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleSize(0.035);
   fourthJetPt_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   fourthJetPt_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleFont(42);
   fourthJetPt_SingleTop_jetSel_emu->Add(fourthJetPt_tZq_jetSel_emu_stack_1,"");
   
   TH1D *fourthJetPt_ttV_jetSel_emu_stack_2 = new TH1D("fourthJetPt_ttV_jetSel_emu_stack_2","fourthJetPt_ttV_jetSel_emu",35,0,300);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(3,0.006913131);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(4,10.5087);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(5,16.15466);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(6,11.53231);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(7,7.370362);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(8,3.673338);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(9,2.889843);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(10,1.272462);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(11,1.285515);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(12,0.6422668);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(13,0.2951674);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(14,0.3647131);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(15,0.2820311);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(16,0.07350433);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(17,0.1491703);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(18,0.0420069);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(19,-0.04223478);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(20,0.01757025);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(21,-0.01665079);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(22,0.00422993);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(23,0.008296648);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(24,-0.001332544);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(25,0.004864397);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(27,0.001431404);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(28,0.001937971);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(29,0.001579998);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(31,-0.000518667);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(32,-0.00135082);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetBinContent(36,0.002657333);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetEntries(29408);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#00ff00");
   fourthJetPt_ttV_jetSel_emu_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   fourthJetPt_ttV_jetSel_emu_stack_2->SetLineColor(ci);
   fourthJetPt_ttV_jetSel_emu_stack_2->SetLineWidth(0);
   fourthJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitle("Fourth p_{T} (GeV)");
   fourthJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetLabelFont(42);
   fourthJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetLabelSize(0.035);
   fourthJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleSize(0.035);
   fourthJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   fourthJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleFont(42);
   fourthJetPt_ttV_jetSel_emu_stack_2->GetYaxis()->SetLabelFont(42);
   fourthJetPt_ttV_jetSel_emu_stack_2->GetYaxis()->SetLabelSize(0.035);
   fourthJetPt_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleSize(0.035);
   fourthJetPt_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleOffset(1);
   fourthJetPt_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleFont(42);
   fourthJetPt_ttV_jetSel_emu_stack_2->GetZaxis()->SetLabelFont(42);
   fourthJetPt_ttV_jetSel_emu_stack_2->GetZaxis()->SetLabelSize(0.035);
   fourthJetPt_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleSize(0.035);
   fourthJetPt_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   fourthJetPt_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleFont(42);
   fourthJetPt_SingleTop_jetSel_emu->Add(fourthJetPt_ttV_jetSel_emu_stack_2,"");
   
   TH1D *fourthJetPt_wJets_jetSel_emu_stack_3 = new TH1D("fourthJetPt_wJets_jetSel_emu_stack_3","fourthJetPt_wJets_jetSel_emu",35,0,300);
   fourthJetPt_wJets_jetSel_emu_stack_3->SetBinContent(1,12.53387);
   fourthJetPt_wJets_jetSel_emu_stack_3->SetBinContent(19,13.42844);
   fourthJetPt_wJets_jetSel_emu_stack_3->SetEntries(2);
   fourthJetPt_wJets_jetSel_emu_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   fourthJetPt_wJets_jetSel_emu_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#cccccc");
   fourthJetPt_wJets_jetSel_emu_stack_3->SetLineColor(ci);
   fourthJetPt_wJets_jetSel_emu_stack_3->SetLineWidth(0);
   fourthJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitle("Fourth p_{T} (GeV)");
   fourthJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetLabelFont(42);
   fourthJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetLabelSize(0.035);
   fourthJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleSize(0.035);
   fourthJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   fourthJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleFont(42);
   fourthJetPt_wJets_jetSel_emu_stack_3->GetYaxis()->SetLabelFont(42);
   fourthJetPt_wJets_jetSel_emu_stack_3->GetYaxis()->SetLabelSize(0.035);
   fourthJetPt_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleSize(0.035);
   fourthJetPt_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleOffset(1);
   fourthJetPt_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleFont(42);
   fourthJetPt_wJets_jetSel_emu_stack_3->GetZaxis()->SetLabelFont(42);
   fourthJetPt_wJets_jetSel_emu_stack_3->GetZaxis()->SetLabelSize(0.035);
   fourthJetPt_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleSize(0.035);
   fourthJetPt_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   fourthJetPt_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleFont(42);
   fourthJetPt_SingleTop_jetSel_emu->Add(fourthJetPt_wJets_jetSel_emu_stack_3,"");
   
   TH1D *fourthJetPt_VVV_jetSel_emu_stack_4 = new TH1D("fourthJetPt_VVV_jetSel_emu_stack_4","fourthJetPt_VVV_jetSel_emu",35,0,300);
   fourthJetPt_VVV_jetSel_emu_stack_4->SetBinContent(4,0.8431757);
   fourthJetPt_VVV_jetSel_emu_stack_4->SetBinContent(5,1.073242);
   fourthJetPt_VVV_jetSel_emu_stack_4->SetBinContent(6,0.5858958);
   fourthJetPt_VVV_jetSel_emu_stack_4->SetBinContent(7,0.3660353);
   fourthJetPt_VVV_jetSel_emu_stack_4->SetBinContent(8,0.3044376);
   fourthJetPt_VVV_jetSel_emu_stack_4->SetBinContent(9,0.193124);
   fourthJetPt_VVV_jetSel_emu_stack_4->SetBinContent(10,0.1061425);
   fourthJetPt_VVV_jetSel_emu_stack_4->SetBinContent(11,0.04125414);
   fourthJetPt_VVV_jetSel_emu_stack_4->SetBinContent(12,0.03798787);
   fourthJetPt_VVV_jetSel_emu_stack_4->SetBinContent(13,0.0378832);
   fourthJetPt_VVV_jetSel_emu_stack_4->SetBinContent(14,0.02608201);
   fourthJetPt_VVV_jetSel_emu_stack_4->SetBinContent(16,0.03487078);
   fourthJetPt_VVV_jetSel_emu_stack_4->SetBinContent(19,0.009105003);
   fourthJetPt_VVV_jetSel_emu_stack_4->SetBinContent(24,0.02511566);
   fourthJetPt_VVV_jetSel_emu_stack_4->SetEntries(147);
   fourthJetPt_VVV_jetSel_emu_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#00ffff");
   fourthJetPt_VVV_jetSel_emu_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   fourthJetPt_VVV_jetSel_emu_stack_4->SetLineColor(ci);
   fourthJetPt_VVV_jetSel_emu_stack_4->SetLineWidth(0);
   fourthJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitle("Fourth p_{T} (GeV)");
   fourthJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetLabelFont(42);
   fourthJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetLabelSize(0.035);
   fourthJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleSize(0.035);
   fourthJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   fourthJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleFont(42);
   fourthJetPt_VVV_jetSel_emu_stack_4->GetYaxis()->SetLabelFont(42);
   fourthJetPt_VVV_jetSel_emu_stack_4->GetYaxis()->SetLabelSize(0.035);
   fourthJetPt_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleSize(0.035);
   fourthJetPt_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleOffset(1);
   fourthJetPt_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleFont(42);
   fourthJetPt_VVV_jetSel_emu_stack_4->GetZaxis()->SetLabelFont(42);
   fourthJetPt_VVV_jetSel_emu_stack_4->GetZaxis()->SetLabelSize(0.035);
   fourthJetPt_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleSize(0.035);
   fourthJetPt_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   fourthJetPt_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleFont(42);
   fourthJetPt_SingleTop_jetSel_emu->Add(fourthJetPt_VVV_jetSel_emu_stack_4,"");
   
   TH1D *fourthJetPt_VV_jetSel_emu_stack_5 = new TH1D("fourthJetPt_VV_jetSel_emu_stack_5","fourthJetPt_VV_jetSel_emu",35,0,300);
   fourthJetPt_VV_jetSel_emu_stack_5->SetBinContent(1,0.3869896);
   fourthJetPt_VV_jetSel_emu_stack_5->SetBinContent(3,0.01117861);
   fourthJetPt_VV_jetSel_emu_stack_5->SetBinContent(4,25.04517);
   fourthJetPt_VV_jetSel_emu_stack_5->SetBinContent(5,19.85038);
   fourthJetPt_VV_jetSel_emu_stack_5->SetBinContent(6,6.755059);
   fourthJetPt_VV_jetSel_emu_stack_5->SetBinContent(7,3.171843);
   fourthJetPt_VV_jetSel_emu_stack_5->SetBinContent(8,2.362298);
   fourthJetPt_VV_jetSel_emu_stack_5->SetBinContent(9,1.340238);
   fourthJetPt_VV_jetSel_emu_stack_5->SetBinContent(10,0.3842983);
   fourthJetPt_VV_jetSel_emu_stack_5->SetBinContent(11,0.1528114);
   fourthJetPt_VV_jetSel_emu_stack_5->SetBinContent(12,0.6112728);
   fourthJetPt_VV_jetSel_emu_stack_5->SetBinContent(13,0.1624555);
   fourthJetPt_VV_jetSel_emu_stack_5->SetBinContent(14,0.09072468);
   fourthJetPt_VV_jetSel_emu_stack_5->SetBinContent(15,0.2188877);
   fourthJetPt_VV_jetSel_emu_stack_5->SetBinContent(16,0.3959306);
   fourthJetPt_VV_jetSel_emu_stack_5->SetBinContent(20,0.005841251);
   fourthJetPt_VV_jetSel_emu_stack_5->SetBinContent(21,0.0145952);
   fourthJetPt_VV_jetSel_emu_stack_5->SetBinContent(24,0.01250403);
   fourthJetPt_VV_jetSel_emu_stack_5->SetEntries(858);
   fourthJetPt_VV_jetSel_emu_stack_5->SetDirectory(0);

   ci = TColor::GetColor("#ff9933");
   fourthJetPt_VV_jetSel_emu_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#ff9933");
   fourthJetPt_VV_jetSel_emu_stack_5->SetLineColor(ci);
   fourthJetPt_VV_jetSel_emu_stack_5->SetLineWidth(0);
   fourthJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitle("Fourth p_{T} (GeV)");
   fourthJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetLabelFont(42);
   fourthJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetLabelSize(0.035);
   fourthJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleSize(0.035);
   fourthJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleOffset(1);
   fourthJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleFont(42);
   fourthJetPt_VV_jetSel_emu_stack_5->GetYaxis()->SetLabelFont(42);
   fourthJetPt_VV_jetSel_emu_stack_5->GetYaxis()->SetLabelSize(0.035);
   fourthJetPt_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleSize(0.035);
   fourthJetPt_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleOffset(1);
   fourthJetPt_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleFont(42);
   fourthJetPt_VV_jetSel_emu_stack_5->GetZaxis()->SetLabelFont(42);
   fourthJetPt_VV_jetSel_emu_stack_5->GetZaxis()->SetLabelSize(0.035);
   fourthJetPt_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleSize(0.035);
   fourthJetPt_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleOffset(1);
   fourthJetPt_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleFont(42);
   fourthJetPt_SingleTop_jetSel_emu->Add(fourthJetPt_VV_jetSel_emu_stack_5,"");
   
   TH1D *fourthJetPt_SingleTop_jetSel_emu_stack_6 = new TH1D("fourthJetPt_SingleTop_jetSel_emu_stack_6","fourthJetPt_SingleTop_jetSel_emu",35,0,300);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(1,2.505068);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(4,96.38299);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(5,89.50084);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(6,37.08893);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(7,24.75811);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(8,11.48157);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(9,7.461757);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(10,3.340629);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(11,2.648536);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(12,1.625655);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(13,0.5595657);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(14,1.371485);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(15,0.4992899);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(16,0.6058512);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(20,0.0005307676);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(27,0.1922669);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(36,0.1978142);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->SetEntries(2806);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->SetDirectory(0);

   ci = TColor::GetColor("#ff00ff");
   fourthJetPt_SingleTop_jetSel_emu_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   fourthJetPt_SingleTop_jetSel_emu_stack_6->SetLineColor(ci);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->SetLineWidth(0);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitle("Fourth p_{T} (GeV)");
   fourthJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetLabelFont(42);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetLabelSize(0.035);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleSize(0.035);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleOffset(1);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleFont(42);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetLabelFont(42);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetLabelSize(0.035);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleSize(0.035);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleOffset(1);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleFont(42);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetLabelFont(42);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetLabelSize(0.035);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleSize(0.035);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleOffset(1);
   fourthJetPt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleFont(42);
   fourthJetPt_SingleTop_jetSel_emu->Add(fourthJetPt_SingleTop_jetSel_emu_stack_6,"");
   
   TH1D *fourthJetPt_tt_jetSel_emu_stack_7 = new TH1D("fourthJetPt_tt_jetSel_emu_stack_7","fourthJetPt_tt_jetSel_emu",35,0,300);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(1,1.472346);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(3,3.709907);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(4,1764.01);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(5,2105.356);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(6,1046.537);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(7,572.3065);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(8,291.0912);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(9,187.9777);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(10,98.21231);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(11,63.08026);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(12,36.50176);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(13,20.71116);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(14,12.99433);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(15,7.835515);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(16,8.565261);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(17,4.294513);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(18,3.553674);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(19,0.6755657);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(20,3.367776);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(21,1.541055);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(22,1.567866);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(23,0.7198966);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(24,0.3094502);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(25,0.5613007);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(26,0.2993144);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(28,0.2892078);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(35,0.7007632);
   fourthJetPt_tt_jetSel_emu_stack_7->SetBinContent(36,0.2776144);
   fourthJetPt_tt_jetSel_emu_stack_7->SetEntries(19867);
   fourthJetPt_tt_jetSel_emu_stack_7->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   fourthJetPt_tt_jetSel_emu_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   fourthJetPt_tt_jetSel_emu_stack_7->SetLineColor(ci);
   fourthJetPt_tt_jetSel_emu_stack_7->SetLineWidth(0);
   fourthJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitle("Fourth p_{T} (GeV)");
   fourthJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetLabelFont(42);
   fourthJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetLabelSize(0.035);
   fourthJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleSize(0.035);
   fourthJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleOffset(1);
   fourthJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleFont(42);
   fourthJetPt_tt_jetSel_emu_stack_7->GetYaxis()->SetLabelFont(42);
   fourthJetPt_tt_jetSel_emu_stack_7->GetYaxis()->SetLabelSize(0.035);
   fourthJetPt_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleSize(0.035);
   fourthJetPt_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleOffset(1);
   fourthJetPt_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleFont(42);
   fourthJetPt_tt_jetSel_emu_stack_7->GetZaxis()->SetLabelFont(42);
   fourthJetPt_tt_jetSel_emu_stack_7->GetZaxis()->SetLabelSize(0.035);
   fourthJetPt_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleSize(0.035);
   fourthJetPt_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleOffset(1);
   fourthJetPt_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleFont(42);
   fourthJetPt_SingleTop_jetSel_emu->Add(fourthJetPt_tt_jetSel_emu_stack_7,"");
   
   TH1D *fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8 = new TH1D("fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8","fourthJetPt_zPlusJetsMadgraph_jetSel_emu",35,0,300);
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(1,11.88618);
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(5,1.429552);
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(6,1.422358);
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(9,2.932198);
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetEntries(12);
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetLineColor(ci);
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetLineWidth(0);
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitle("Fourth p_{T} (GeV)");
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetLabelFont(42);
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetLabelSize(0.035);
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleSize(0.035);
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleOffset(1);
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleFont(42);
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetLabelFont(42);
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetLabelSize(0.035);
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleSize(0.035);
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleOffset(1);
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleFont(42);
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetLabelFont(42);
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetLabelSize(0.035);
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleSize(0.035);
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleOffset(1);
   fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleFont(42);
   fourthJetPt_SingleTop_jetSel_emu->Add(fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8,"");
   fourthJetPt_SingleTop_jetSel_emu->Draw("");
   
   TH1D *fourthJetPt_data_jetSel_emu__1 = new TH1D("fourthJetPt_data_jetSel_emu__1","fourthJetPt_data_jetSel_emu",35,0,300);
   fourthJetPt_data_jetSel_emu__1->SetBinContent(4,1954);
   fourthJetPt_data_jetSel_emu__1->SetBinContent(5,2249);
   fourthJetPt_data_jetSel_emu__1->SetBinContent(6,1154);
   fourthJetPt_data_jetSel_emu__1->SetBinContent(7,578);
   fourthJetPt_data_jetSel_emu__1->SetBinContent(8,345);
   fourthJetPt_data_jetSel_emu__1->SetBinContent(9,172);
   fourthJetPt_data_jetSel_emu__1->SetBinContent(10,85);
   fourthJetPt_data_jetSel_emu__1->SetBinContent(11,55);
   fourthJetPt_data_jetSel_emu__1->SetBinContent(12,32);
   fourthJetPt_data_jetSel_emu__1->SetBinContent(13,13);
   fourthJetPt_data_jetSel_emu__1->SetBinContent(14,11);
   fourthJetPt_data_jetSel_emu__1->SetBinContent(15,4);
   fourthJetPt_data_jetSel_emu__1->SetBinContent(16,5);
   fourthJetPt_data_jetSel_emu__1->SetBinContent(17,3);
   fourthJetPt_data_jetSel_emu__1->SetBinContent(18,4);
   fourthJetPt_data_jetSel_emu__1->SetBinContent(19,1);
   fourthJetPt_data_jetSel_emu__1->SetBinContent(20,1);
   fourthJetPt_data_jetSel_emu__1->SetBinContent(21,1);
   fourthJetPt_data_jetSel_emu__1->SetBinContent(22,1);
   fourthJetPt_data_jetSel_emu__1->SetEntries(6668);
   fourthJetPt_data_jetSel_emu__1->SetDirectory(0);
   fourthJetPt_data_jetSel_emu__1->SetFillColor(1);
   fourthJetPt_data_jetSel_emu__1->SetLineWidth(2);
   fourthJetPt_data_jetSel_emu__1->SetLineColor(1); //
   fourthJetPt_data_jetSel_emu__1->SetMarkerStyle(20);
   fourthJetPt_data_jetSel_emu__1->SetMarkerSize(1.4);
   fourthJetPt_data_jetSel_emu__1->GetXaxis()->SetTitle("Fourth p_{T} (GeV)");
   fourthJetPt_data_jetSel_emu__1->GetXaxis()->SetLabelFont(42);
   fourthJetPt_data_jetSel_emu__1->GetXaxis()->SetLabelSize(0.035);
   fourthJetPt_data_jetSel_emu__1->GetXaxis()->SetTitleSize(0.035);
   fourthJetPt_data_jetSel_emu__1->GetXaxis()->SetTitleOffset(1);
   fourthJetPt_data_jetSel_emu__1->GetXaxis()->SetTitleFont(42);
   fourthJetPt_data_jetSel_emu__1->GetYaxis()->SetLabelFont(42);
   fourthJetPt_data_jetSel_emu__1->GetYaxis()->SetLabelSize(0.035);
   fourthJetPt_data_jetSel_emu__1->GetYaxis()->SetTitleSize(0.035);
   fourthJetPt_data_jetSel_emu__1->GetYaxis()->SetTitleOffset(1);
   fourthJetPt_data_jetSel_emu__1->GetYaxis()->SetTitleFont(42);
   fourthJetPt_data_jetSel_emu__1->GetZaxis()->SetLabelFont(42);
   fourthJetPt_data_jetSel_emu__1->GetZaxis()->SetLabelSize(0.035);
   fourthJetPt_data_jetSel_emu__1->GetZaxis()->SetTitleSize(0.035);
   fourthJetPt_data_jetSel_emu__1->GetZaxis()->SetTitleOffset(1);
   fourthJetPt_data_jetSel_emu__1->GetZaxis()->SetTitleFont(42);
   fourthJetPt_data_jetSel_emu__1->Draw("e x0, same");
   
   TLegend *leg = new TLegend(0.78,0.42,0.98,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("fourthJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8","Z+jets (LO)","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetPt_tt_jetSel_emu_stack_7","t#bar{t}","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetPt_SingleTop_jetSel_emu_stack_6","Single top","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetPt_VV_jetSel_emu_stack_5","VV","f");

   ci = TColor::GetColor("#ff9933");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetPt_VVV_jetSel_emu_stack_4","VVV","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetPt_wJets_jetSel_emu_stack_3","W+jets","f");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetPt_ttV_jetSel_emu_stack_2","t#bar{t}V","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetPt_tZq_jetSel_emu_stack_1","tZq","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetPt_data_jetSel_emu","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.4);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.968,0.9429101,"35.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06792969);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.096,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.05419922);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16899,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.04119141);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *fourthJetPt_SingleTop_jetSel_emu__2 = new TH1F("fourthJetPt_SingleTop_jetSel_emu__2","Fourth Jet p_{T}",35,0,300);
   fourthJetPt_SingleTop_jetSel_emu__2->SetMinimum(-0.00135082);
   fourthJetPt_SingleTop_jetSel_emu__2->SetMaximum(2597.595);
   fourthJetPt_SingleTop_jetSel_emu__2->SetDirectory(0);
   fourthJetPt_SingleTop_jetSel_emu__2->SetStats(0);
   fourthJetPt_SingleTop_jetSel_emu__2->SetLineStyle(0);
   fourthJetPt_SingleTop_jetSel_emu__2->SetLineWidth(0);
   fourthJetPt_SingleTop_jetSel_emu__2->SetMarkerStyle(20);
   fourthJetPt_SingleTop_jetSel_emu__2->GetXaxis()->SetTitle("Fourth p_{T} (GeV)");
   fourthJetPt_SingleTop_jetSel_emu__2->GetXaxis()->SetNdivisions(506);
   fourthJetPt_SingleTop_jetSel_emu__2->GetXaxis()->SetLabelFont(42);
   fourthJetPt_SingleTop_jetSel_emu__2->GetXaxis()->SetLabelOffset(999);
   fourthJetPt_SingleTop_jetSel_emu__2->GetXaxis()->SetLabelSize(0.05);
   fourthJetPt_SingleTop_jetSel_emu__2->GetXaxis()->SetTitleSize(0.08);
   fourthJetPt_SingleTop_jetSel_emu__2->GetXaxis()->SetTitleOffset(1);
   fourthJetPt_SingleTop_jetSel_emu__2->GetXaxis()->SetTitleFont(42);
   fourthJetPt_SingleTop_jetSel_emu__2->GetYaxis()->SetTitle("Events");
   fourthJetPt_SingleTop_jetSel_emu__2->GetYaxis()->SetNdivisions(506);
   fourthJetPt_SingleTop_jetSel_emu__2->GetYaxis()->SetLabelFont(42);
   fourthJetPt_SingleTop_jetSel_emu__2->GetYaxis()->SetLabelOffset(0.01);
   fourthJetPt_SingleTop_jetSel_emu__2->GetYaxis()->SetLabelSize(0.062);
   fourthJetPt_SingleTop_jetSel_emu__2->GetYaxis()->SetTitleSize(0.08);
   fourthJetPt_SingleTop_jetSel_emu__2->GetYaxis()->SetTitleOffset(0.6336);
   fourthJetPt_SingleTop_jetSel_emu__2->GetYaxis()->SetTitleFont(42);
   fourthJetPt_SingleTop_jetSel_emu__2->GetZaxis()->SetLabelFont(42);
   fourthJetPt_SingleTop_jetSel_emu__2->GetZaxis()->SetLabelOffset(0.007);
   fourthJetPt_SingleTop_jetSel_emu__2->GetZaxis()->SetLabelSize(0.05);
   fourthJetPt_SingleTop_jetSel_emu__2->GetZaxis()->SetTitleSize(0.08);
   fourthJetPt_SingleTop_jetSel_emu__2->GetZaxis()->SetTitleOffset(1);
   fourthJetPt_SingleTop_jetSel_emu__2->GetZaxis()->SetTitleFont(42);
   fourthJetPt_SingleTop_jetSel_emu__2->Draw("sameaxis");
   
/*   TPaveText *pt = new TPaveText(0.42852,0.9203237,0.57148,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Fourth Jet p_{T}");
   pt->Draw();*/
   canvy_1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: canvy_2
   TPad *canvy_2 = new TPad("canvy_2", "newpad2",0.01,0.01,0.99,0.322);
   canvy_2->Draw();
   canvy_2->cd();
   canvy_2->SetFillColor(0);
   canvy_2->SetBorderMode(0);
   canvy_2->SetGridy();

   canvy_2->SetLeftMargin( L/W );
   canvy_2->SetRightMargin( R/W );
   canvy_2->SetTopMargin( T/H );
   canvy_2->SetBottomMargin( B/H * 2.6 );
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   
   TH1D *fourthJetPt_data_jetSel_emu__3 = new TH1D("fourthJetPt_data_jetSel_emu__3","",35,0,300);
   fourthJetPt_data_jetSel_emu__3->SetBinContent(4,1.030026);
   fourthJetPt_data_jetSel_emu__3->SetBinContent(5,1.006846);
   fourthJetPt_data_jetSel_emu__3->SetBinContent(6,1.045148);
   fourthJetPt_data_jetSel_emu__3->SetBinContent(7,0.9505191);
   fourthJetPt_data_jetSel_emu__3->SetBinContent(8,1.116597);
   fourthJetPt_data_jetSel_emu__3->SetBinContent(9,0.847986);
   fourthJetPt_data_jetSel_emu__3->SetBinContent(10,0.8225764);
   fourthJetPt_data_jetSel_emu__3->SetBinContent(11,0.8181384);
   fourthJetPt_data_jetSel_emu__3->SetBinContent(12,0.8115486);
   fourthJetPt_data_jetSel_emu__3->SetBinContent(13,0.5970038);
   fourthJetPt_data_jetSel_emu__3->SetBinContent(14,0.7407342);
   fourthJetPt_data_jetSel_emu__3->SetBinContent(15,0.4524406);
   fourthJetPt_data_jetSel_emu__3->SetBinContent(16,0.5167925);
   fourthJetPt_data_jetSel_emu__3->SetBinContent(17,0.6749797);
   fourthJetPt_data_jetSel_emu__3->SetBinContent(18,1.112884);
   fourthJetPt_data_jetSel_emu__3->SetBinContent(19,0.07107164);
   fourthJetPt_data_jetSel_emu__3->SetBinContent(20,0.2948426);
   fourthJetPt_data_jetSel_emu__3->SetBinContent(21,0.6495147);
   fourthJetPt_data_jetSel_emu__3->SetBinContent(22,0.6357786);
   fourthJetPt_data_jetSel_emu__3->SetBinError(4,0.03319988);
   fourthJetPt_data_jetSel_emu__3->SetBinError(5,0.03007636);
   fourthJetPt_data_jetSel_emu__3->SetBinError(6,0.04399846);
   fourthJetPt_data_jetSel_emu__3->SetBinError(7,0.0552169);
   fourthJetPt_data_jetSel_emu__3->SetBinError(8,0.08745932);
   fourthJetPt_data_jetSel_emu__3->SetBinError(9,0.08789694);
   fourthJetPt_data_jetSel_emu__3->SetBinError(10,0.1204508);
   fourthJetPt_data_jetSel_emu__3->SetBinError(11,0.1487507);
   fourthJetPt_data_jetSel_emu__3->SetBinError(12,0.1930921);
   fourthJetPt_data_jetSel_emu__3->SetBinError(13,0.2092466);
   fourthJetPt_data_jetSel_emu__3->SetBinError(14,0.2946675);
   fourthJetPt_data_jetSel_emu__3->SetBinError(15,0.2726345);
   fourthJetPt_data_jetSel_emu__3->SetBinError(16,0.284639);
   fourthJetPt_data_jetSel_emu__3->SetBinError(17,0.5043533);
   fourthJetPt_data_jetSel_emu__3->SetBinError(18,0.8088309);
   fourthJetPt_data_jetSel_emu__3->SetBinError(19,0.07355388);
   fourthJetPt_data_jetSel_emu__3->SetBinError(20,0.3355048);
   fourthJetPt_data_jetSel_emu__3->SetBinError(21,0.834194);
   fourthJetPt_data_jetSel_emu__3->SetBinError(22,0.8131453);
   fourthJetPt_data_jetSel_emu__3->SetMinimum(0.5);
   fourthJetPt_data_jetSel_emu__3->SetMaximum(1.5);
   fourthJetPt_data_jetSel_emu__3->SetEntries(72.85555);
   fourthJetPt_data_jetSel_emu__3->SetDirectory(0);
   fourthJetPt_data_jetSel_emu__3->SetStats(0);
   fourthJetPt_data_jetSel_emu__3->SetFillColor(1);
   fourthJetPt_data_jetSel_emu__3->SetLineWidth(2);
   fourthJetPt_data_jetSel_emu__3->SetLineColor(1); //
   fourthJetPt_data_jetSel_emu__3->SetMarkerStyle(20);
   fourthJetPt_data_jetSel_emu__3->SetMarkerSize(1.6);
   fourthJetPt_data_jetSel_emu__3->GetXaxis()->SetTitle("Fourth p_{T} (GeV)");
   fourthJetPt_data_jetSel_emu__3->GetXaxis()->SetNdivisions(506);
   fourthJetPt_data_jetSel_emu__3->GetXaxis()->SetLabelFont(42);
   fourthJetPt_data_jetSel_emu__3->GetXaxis()->SetLabelOffset(0.013);
   fourthJetPt_data_jetSel_emu__3->GetXaxis()->SetLabelSize(0.13);
   fourthJetPt_data_jetSel_emu__3->GetXaxis()->SetTitleSize(0.13);
   fourthJetPt_data_jetSel_emu__3->GetXaxis()->SetTitleOffset(1);
   fourthJetPt_data_jetSel_emu__3->GetXaxis()->SetTitleFont(42);
   fourthJetPt_data_jetSel_emu__3->GetYaxis()->SetTitle("Data/MC");
   fourthJetPt_data_jetSel_emu__3->GetYaxis()->CenterTitle(true);
   fourthJetPt_data_jetSel_emu__3->GetYaxis()->SetNdivisions(506);
   fourthJetPt_data_jetSel_emu__3->GetYaxis()->SetLabelFont(42);
   fourthJetPt_data_jetSel_emu__3->GetYaxis()->SetLabelOffset(0.01);
   fourthJetPt_data_jetSel_emu__3->GetYaxis()->SetLabelSize(0.12);
   fourthJetPt_data_jetSel_emu__3->GetYaxis()->SetTitleSize(0.16);
   fourthJetPt_data_jetSel_emu__3->GetYaxis()->SetTitleOffset(0.3);
   fourthJetPt_data_jetSel_emu__3->GetYaxis()->SetTitleFont(42);
   fourthJetPt_data_jetSel_emu__3->GetZaxis()->SetLabelFont(42);
   fourthJetPt_data_jetSel_emu__3->GetZaxis()->SetLabelSize(0.035);
   fourthJetPt_data_jetSel_emu__3->GetZaxis()->SetTitleSize(0.035);
   fourthJetPt_data_jetSel_emu__3->GetZaxis()->SetTitleOffset(1);
   fourthJetPt_data_jetSel_emu__3->GetZaxis()->SetTitleFont(42);
   fourthJetPt_data_jetSel_emu__3->Draw("e x0, SCAT");
   canvy_2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
//   c1->SetSelected(fourthJetPt_data_jetSel_emu);
   c1->SaveAs("fourthJetPt_jetSel.pdf");
}
