void fourthJetEta_SingleTop_jetSel()
{
//=========Macro generated from canvas: fourthJetEta_SingleTop_jetSel/fourthJetEta_SingleTop_jetSel
//=========  (Wed Aug 21 19:45:41 2019) by ROOT version 6.18/00

   // Set up cavas
   int W = 1280;
   int H = 1024;
   int H_ref = 925;
   int W_ref = 1024;

   // references for T, B, L, R
   float T = 0.08*H_ref;
   float B = 0.12*H_ref;
   float L = 0.12*W_ref;
   float R = 0.04*W_ref;

   TCanvas *c1 = new TCanvas("c1","c1",50,50,W,H);
   c1->cd();
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetLeftMargin( L/W );
   c1->SetRightMargin( R/W );
   c1->SetTopMargin( T/H );
   c1->SetBottomMargin( B/H );
   c1->SetTickx(0);
   c1->SetTicky(0);
  
// ------------>Primitives in pad: canvy_1
   TPad *canvy_1 = new TPad("canvy_1", "newpad",0.01,0.315,0.99,0.99);
   canvy_1->Draw();
   canvy_1->cd();
   canvy_1->SetFillColor(0);
   canvy_1->SetBorderMode(0);

   canvy_1->SetLeftMargin( L/W );
   canvy_1->SetRightMargin( R/W );
   canvy_1->SetTopMargin( T/H );
   canvy_1->SetBottomMargin( B/H * 0.3 );

   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);
   
   THStack *fourthJetEta_SingleTop_jetSel_emu = new THStack();
   fourthJetEta_SingleTop_jetSel_emu->SetName("fourthJetEta_SingleTop_jetSel_emu");
   fourthJetEta_SingleTop_jetSel_emu->SetTitle(";Fourth jet #eta;Events");
   fourthJetEta_SingleTop_jetSel_emu->SetMaximum(301.4);
   
   TH1F *fourthJetEta_SingleTop_jetSel_emu_stack_1 = new TH1F("fourthJetEta_SingleTop_jetSel_emu_stack_1","Fourth Jet #eta",25,0,5);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->SetMinimum(0);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->SetMaximum(316.47);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->SetDirectory(0);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->SetStats(0);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->SetLineStyle(0);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->SetLineWidth(0);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->SetMarkerStyle(20);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetNdivisions(506);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetLabelFont(42);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetLabelOffset(999);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetLabelSize(0.05);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetTitleSize(0.08);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetTitle("Events");
   fourthJetEta_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetNdivisions(506);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetLabelFont(42);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetLabelOffset(0.01);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetLabelSize(0.062);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetTitleSize(0.08);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetTitleOffset(0.6336);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->GetZaxis()->SetLabelFont(42);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->GetZaxis()->SetLabelOffset(0.007);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->GetZaxis()->SetLabelSize(0.05);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->GetZaxis()->SetTitleSize(0.08);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_SingleTop_jetSel_emu_stack_1->GetZaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_jetSel_emu->SetHistogram(fourthJetEta_SingleTop_jetSel_emu_stack_1);
   
   
   TH1D *fourthJetEta_tZq_jetSel_emu_stack_1 = new TH1D("fourthJetEta_tZq_jetSel_emu_stack_1","fourthJetEta_tZq_jetSel_emu",25,0,5);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(0,0.5465187);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(1,0.05040102);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(2,0.03590629);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(3,0.03865847);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(4,0.01587792);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(5,0.04772873);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(6,0.02778532);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(7,0.01928274);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(8,0.03012593);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(9,0.02808738);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(10,0.03315607);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(11,0.03315274);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(12,0.0271149);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(13,0.02367409);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(14,0.03240675);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(15,0.03076937);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(16,0.009750623);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(17,0.01241633);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(18,0.01966416);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(19,0.01714189);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(20,0.00602592);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(21,0.01148357);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(22,0.004998248);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(23,0.004916011);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetBinContent(24,-0.001550541);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetEntries(6672);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ffff00");
   fourthJetEta_tZq_jetSel_emu_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   fourthJetEta_tZq_jetSel_emu_stack_1->SetLineColor(ci);
   fourthJetEta_tZq_jetSel_emu_stack_1->SetLineWidth(0);
   fourthJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetLabelFont(42);
   fourthJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetLabelSize(0.035);
   fourthJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleSize(0.035);
   fourthJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleFont(42);
   fourthJetEta_tZq_jetSel_emu_stack_1->GetYaxis()->SetLabelFont(42);
   fourthJetEta_tZq_jetSel_emu_stack_1->GetYaxis()->SetLabelSize(0.035);
   fourthJetEta_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleSize(0.035);
   fourthJetEta_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleOffset(1);
   fourthJetEta_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleFont(42);
   fourthJetEta_tZq_jetSel_emu_stack_1->GetZaxis()->SetLabelFont(42);
   fourthJetEta_tZq_jetSel_emu_stack_1->GetZaxis()->SetLabelSize(0.035);
   fourthJetEta_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleSize(0.035);
   fourthJetEta_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_jetSel_emu->Add(fourthJetEta_tZq_jetSel_emu_stack_1,"");
   
   TH1D *fourthJetEta_ttV_jetSel_emu_stack_2 = new TH1D("fourthJetEta_ttV_jetSel_emu_stack_2","fourthJetEta_ttV_jetSel_emu",25,0,5);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(0,27.82857);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(1,2.373826);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(2,2.817423);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(3,2.626856);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(4,2.858695);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(5,2.616889);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(6,1.901659);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(7,2.026479);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(8,1.857056);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(9,1.294491);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(10,1.215918);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(11,1.081595);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(12,1.272997);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(13,0.8641982);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(14,1.225383);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(15,0.5418542);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(16,0.3158525);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(17,0.5954978);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(18,0.5126667);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(19,0.2877778);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(20,0.1467053);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(21,0.07128283);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(22,0.1545302);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(23,0.02946703);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetBinContent(24,0.005776128);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetEntries(29408);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#00ff00");
   fourthJetEta_ttV_jetSel_emu_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   fourthJetEta_ttV_jetSel_emu_stack_2->SetLineColor(ci);
   fourthJetEta_ttV_jetSel_emu_stack_2->SetLineWidth(0);
   fourthJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetLabelFont(42);
   fourthJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetLabelSize(0.035);
   fourthJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleSize(0.035);
   fourthJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleFont(42);
   fourthJetEta_ttV_jetSel_emu_stack_2->GetYaxis()->SetLabelFont(42);
   fourthJetEta_ttV_jetSel_emu_stack_2->GetYaxis()->SetLabelSize(0.035);
   fourthJetEta_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleSize(0.035);
   fourthJetEta_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleOffset(1);
   fourthJetEta_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleFont(42);
   fourthJetEta_ttV_jetSel_emu_stack_2->GetZaxis()->SetLabelFont(42);
   fourthJetEta_ttV_jetSel_emu_stack_2->GetZaxis()->SetLabelSize(0.035);
   fourthJetEta_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleSize(0.035);
   fourthJetEta_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_jetSel_emu->Add(fourthJetEta_ttV_jetSel_emu_stack_2,"");
   
   TH1D *fourthJetEta_wJets_jetSel_emu_stack_3 = new TH1D("fourthJetEta_wJets_jetSel_emu_stack_3","fourthJetEta_wJets_jetSel_emu",25,0,5);
   fourthJetEta_wJets_jetSel_emu_stack_3->SetBinContent(1,12.53387);
   fourthJetEta_wJets_jetSel_emu_stack_3->SetBinContent(8,13.42844);
   fourthJetEta_wJets_jetSel_emu_stack_3->SetEntries(2);
   fourthJetEta_wJets_jetSel_emu_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   fourthJetEta_wJets_jetSel_emu_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#cccccc");
   fourthJetEta_wJets_jetSel_emu_stack_3->SetLineColor(ci);
   fourthJetEta_wJets_jetSel_emu_stack_3->SetLineWidth(0);
   fourthJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetLabelFont(42);
   fourthJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetLabelSize(0.035);
   fourthJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleSize(0.035);
   fourthJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleFont(42);
   fourthJetEta_wJets_jetSel_emu_stack_3->GetYaxis()->SetLabelFont(42);
   fourthJetEta_wJets_jetSel_emu_stack_3->GetYaxis()->SetLabelSize(0.035);
   fourthJetEta_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleSize(0.035);
   fourthJetEta_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleOffset(1);
   fourthJetEta_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleFont(42);
   fourthJetEta_wJets_jetSel_emu_stack_3->GetZaxis()->SetLabelFont(42);
   fourthJetEta_wJets_jetSel_emu_stack_3->GetZaxis()->SetLabelSize(0.035);
   fourthJetEta_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleSize(0.035);
   fourthJetEta_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_jetSel_emu->Add(fourthJetEta_wJets_jetSel_emu_stack_3,"");
   
   TH1D *fourthJetEta_VVV_jetSel_emu_stack_4 = new TH1D("fourthJetEta_VVV_jetSel_emu_stack_4","fourthJetEta_VVV_jetSel_emu",25,0,5);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetBinContent(0,1.837265);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetBinContent(1,0.1385032);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetBinContent(2,0.240373);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetBinContent(3,0.1053321);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetBinContent(4,0.0528391);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetBinContent(5,0.1133685);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetBinContent(6,0.1636027);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetBinContent(7,0.04680821);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetBinContent(8,0.2067287);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetBinContent(9,0.0698809);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetBinContent(10,0.1246759);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetBinContent(11,0.008203186);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetBinContent(12,0.09999735);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetBinContent(13,0.1679156);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetBinContent(14,0.08567644);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetBinContent(15,0.1219389);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetBinContent(17,0.02676835);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetBinContent(20,0.03374263);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetBinContent(22,0.005500864);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetBinContent(23,0.03523137);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetEntries(147);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#00ffff");
   fourthJetEta_VVV_jetSel_emu_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   fourthJetEta_VVV_jetSel_emu_stack_4->SetLineColor(ci);
   fourthJetEta_VVV_jetSel_emu_stack_4->SetLineWidth(0);
   fourthJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetLabelFont(42);
   fourthJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetLabelSize(0.035);
   fourthJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleSize(0.035);
   fourthJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleFont(42);
   fourthJetEta_VVV_jetSel_emu_stack_4->GetYaxis()->SetLabelFont(42);
   fourthJetEta_VVV_jetSel_emu_stack_4->GetYaxis()->SetLabelSize(0.035);
   fourthJetEta_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleSize(0.035);
   fourthJetEta_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleOffset(1);
   fourthJetEta_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleFont(42);
   fourthJetEta_VVV_jetSel_emu_stack_4->GetZaxis()->SetLabelFont(42);
   fourthJetEta_VVV_jetSel_emu_stack_4->GetZaxis()->SetLabelSize(0.035);
   fourthJetEta_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleSize(0.035);
   fourthJetEta_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_jetSel_emu->Add(fourthJetEta_VVV_jetSel_emu_stack_4,"");
   
   TH1D *fourthJetEta_VV_jetSel_emu_stack_5 = new TH1D("fourthJetEta_VV_jetSel_emu_stack_5","fourthJetEta_VV_jetSel_emu",25,0,5);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(0,28.76937);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(1,1.900937);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(2,2.680763);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(3,2.049374);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(4,3.218877);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(5,2.296724);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(6,1.088501);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(7,1.216266);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(8,2.004742);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(9,2.026698);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(10,1.931641);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(11,2.009203);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(12,0.7687979);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(13,0.7690287);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(14,2.588101);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(15,1.992096);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(16,0.678689);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(17,1.201156);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(18,0.6186082);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(19,0.2466647);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(20,0.1564763);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(21,-0.1480956);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(22,0.6618576);
   fourthJetEta_VV_jetSel_emu_stack_5->SetBinContent(24,0.2460059);
   fourthJetEta_VV_jetSel_emu_stack_5->SetEntries(858);
   fourthJetEta_VV_jetSel_emu_stack_5->SetDirectory(0);

   ci = TColor::GetColor("#ff9933");
   fourthJetEta_VV_jetSel_emu_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#ff9933");
   fourthJetEta_VV_jetSel_emu_stack_5->SetLineColor(ci);
   fourthJetEta_VV_jetSel_emu_stack_5->SetLineWidth(0);
   fourthJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetLabelFont(42);
   fourthJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetLabelSize(0.035);
   fourthJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleSize(0.035);
   fourthJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleFont(42);
   fourthJetEta_VV_jetSel_emu_stack_5->GetYaxis()->SetLabelFont(42);
   fourthJetEta_VV_jetSel_emu_stack_5->GetYaxis()->SetLabelSize(0.035);
   fourthJetEta_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleSize(0.035);
   fourthJetEta_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleOffset(1);
   fourthJetEta_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleFont(42);
   fourthJetEta_VV_jetSel_emu_stack_5->GetZaxis()->SetLabelFont(42);
   fourthJetEta_VV_jetSel_emu_stack_5->GetZaxis()->SetLabelSize(0.035);
   fourthJetEta_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleSize(0.035);
   fourthJetEta_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_jetSel_emu->Add(fourthJetEta_VV_jetSel_emu_stack_5,"");
   
   TH1D *fourthJetEta_SingleTop_jetSel_emu_stack_6 = new TH1D("fourthJetEta_SingleTop_jetSel_emu_stack_6","fourthJetEta_SingleTop_jetSel_emu",25,0,5);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(0,146.6539);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(1,12.54175);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(2,9.513094);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(3,7.905338);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(4,11.64461);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(5,9.768484);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(6,7.899825);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(7,8.181648);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(8,7.360019);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(9,6.128115);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(10,3.983158);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(11,4.677173);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(12,5.172162);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(13,5.771393);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(14,6.584662);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(15,5.649003);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(16,3.739545);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(17,4.138138);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(18,2.611261);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(19,2.8435);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(20,2.361346);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(21,1.94503);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(22,1.559617);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(23,1.587209);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(24,0.0008957905);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetEntries(2806);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetDirectory(0);

   ci = TColor::GetColor("#ff00ff");
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetLineColor(ci);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->SetLineWidth(0);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetLabelFont(42);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetLabelSize(0.035);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleSize(0.035);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetLabelFont(42);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetLabelSize(0.035);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleSize(0.035);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleOffset(1);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetLabelFont(42);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetLabelSize(0.035);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleSize(0.035);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_jetSel_emu->Add(fourthJetEta_SingleTop_jetSel_emu_stack_6,"");
   
   TH1D *fourthJetEta_tt_jetSel_emu_stack_7 = new TH1D("fourthJetEta_tt_jetSel_emu_stack_7","fourthJetEta_tt_jetSel_emu",25,0,5);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(0,3122.892);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(1,233.4049);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(2,244.5465);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(3,240.2498);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(4,237.8186);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(5,224.0366);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(6,212.026);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(7,192.7084);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(8,173.605);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(9,169.9432);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(10,149.2371);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(11,141.272);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(12,134.7721);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(13,111.8298);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(14,147.4771);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(15,123.6135);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(16,74.84805);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(17,77.70818);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(18,54.01721);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(19,49.21031);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(20,37.65284);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(21,31.74191);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(22,25.06347);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(23,20.00858);
   fourthJetEta_tt_jetSel_emu_stack_7->SetBinContent(24,8.834854);
   fourthJetEta_tt_jetSel_emu_stack_7->SetEntries(19867);
   fourthJetEta_tt_jetSel_emu_stack_7->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   fourthJetEta_tt_jetSel_emu_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   fourthJetEta_tt_jetSel_emu_stack_7->SetLineColor(ci);
   fourthJetEta_tt_jetSel_emu_stack_7->SetLineWidth(0);
   fourthJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetLabelFont(42);
   fourthJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetLabelSize(0.035);
   fourthJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleSize(0.035);
   fourthJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleFont(42);
   fourthJetEta_tt_jetSel_emu_stack_7->GetYaxis()->SetLabelFont(42);
   fourthJetEta_tt_jetSel_emu_stack_7->GetYaxis()->SetLabelSize(0.035);
   fourthJetEta_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleSize(0.035);
   fourthJetEta_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleOffset(1);
   fourthJetEta_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleFont(42);
   fourthJetEta_tt_jetSel_emu_stack_7->GetZaxis()->SetLabelFont(42);
   fourthJetEta_tt_jetSel_emu_stack_7->GetZaxis()->SetLabelSize(0.035);
   fourthJetEta_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleSize(0.035);
   fourthJetEta_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_jetSel_emu->Add(fourthJetEta_tt_jetSel_emu_stack_7,"");
   
   TH1D *fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8 = new TH1D("fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8","fourthJetEta_zPlusJetsMadgraph_jetSel_emu",25,0,5);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(0,7.418843);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(1,4.511549);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(3,2.885551);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(4,1.431985);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(12,1.422358);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetEntries(12);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetLineColor(ci);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetLineWidth(0);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetLabelFont(42);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetLabelSize(0.035);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleSize(0.035);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleFont(42);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetLabelFont(42);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetLabelSize(0.035);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleSize(0.035);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleOffset(1);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleFont(42);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetLabelFont(42);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetLabelSize(0.035);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleSize(0.035);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_jetSel_emu->Add(fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8,"");
   fourthJetEta_SingleTop_jetSel_emu->Draw("");
   
   TH1D *fourthJetEta_data_jetSel_emu__1 = new TH1D("fourthJetEta_data_jetSel_emu__1","fourthJetEta_data_jetSel_emu",25,0,5);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(0,3345);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(1,274);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(2,263);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(3,248);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(4,257);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(5,221);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(6,224);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(7,216);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(8,216);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(9,177);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(10,181);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(11,169);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(12,149);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(13,111);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(14,159);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(15,116);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(16,60);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(17,88);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(18,35);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(19,43);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(20,34);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(21,34);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(22,27);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(23,15);
   fourthJetEta_data_jetSel_emu__1->SetBinContent(24,6);
   fourthJetEta_data_jetSel_emu__1->SetEntries(6668);
   fourthJetEta_data_jetSel_emu__1->SetDirectory(0);
   fourthJetEta_data_jetSel_emu__1->SetFillColor(1);
   fourthJetEta_data_jetSel_emu__1->SetLineWidth(2);
   fourthJetEta_data_jetSel_emu__1->SetLineColor(1); //
   fourthJetEta_data_jetSel_emu__1->SetMarkerStyle(20);
   fourthJetEta_data_jetSel_emu__1->SetMarkerSize(1.4);
   fourthJetEta_data_jetSel_emu__1->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_data_jetSel_emu__1->GetXaxis()->SetLabelFont(42);
   fourthJetEta_data_jetSel_emu__1->GetXaxis()->SetLabelSize(0.035);
   fourthJetEta_data_jetSel_emu__1->GetXaxis()->SetTitleSize(0.035);
   fourthJetEta_data_jetSel_emu__1->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_data_jetSel_emu__1->GetXaxis()->SetTitleFont(42);
   fourthJetEta_data_jetSel_emu__1->GetYaxis()->SetLabelFont(42);
   fourthJetEta_data_jetSel_emu__1->GetYaxis()->SetLabelSize(0.035);
   fourthJetEta_data_jetSel_emu__1->GetYaxis()->SetTitleSize(0.035);
   fourthJetEta_data_jetSel_emu__1->GetYaxis()->SetTitleOffset(1);
   fourthJetEta_data_jetSel_emu__1->GetYaxis()->SetTitleFont(42);
   fourthJetEta_data_jetSel_emu__1->GetZaxis()->SetLabelFont(42);
   fourthJetEta_data_jetSel_emu__1->GetZaxis()->SetLabelSize(0.035);
   fourthJetEta_data_jetSel_emu__1->GetZaxis()->SetTitleSize(0.035);
   fourthJetEta_data_jetSel_emu__1->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_data_jetSel_emu__1->GetZaxis()->SetTitleFont(42);
   fourthJetEta_data_jetSel_emu__1->Draw("e x0, same");
   
   TLegend *leg = new TLegend(0.78,0.42,0.98,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("fourthJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8","Z+jets (LO)","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetEta_tt_jetSel_emu_stack_7","t#bar{t}","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetEta_SingleTop_jetSel_emu_stack_6","Single top","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetEta_VV_jetSel_emu_stack_5","VV","f");

   ci = TColor::GetColor("#ff9933");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetEta_VVV_jetSel_emu_stack_4","VVV","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetEta_wJets_jetSel_emu_stack_3","W+jets","f");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetEta_ttV_jetSel_emu_stack_2","t#bar{t}V","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetEta_tZq_jetSel_emu_stack_1","tZq","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("fourthJetEta_data_jetSel_emu","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.4);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.968,0.9429101,"35.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06792969);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.096,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.05419922);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16899,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.04119141);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *fourthJetEta_SingleTop_jetSel_emu__2 = new TH1F("fourthJetEta_SingleTop_jetSel_emu__2","Fourth Jet #eta",25,0,5);
   fourthJetEta_SingleTop_jetSel_emu__2->SetMinimum(0);
   fourthJetEta_SingleTop_jetSel_emu__2->SetMaximum(316.47);
   fourthJetEta_SingleTop_jetSel_emu__2->SetDirectory(0);
   fourthJetEta_SingleTop_jetSel_emu__2->SetStats(0);
   fourthJetEta_SingleTop_jetSel_emu__2->SetLineStyle(0);
   fourthJetEta_SingleTop_jetSel_emu__2->SetLineWidth(0);
   fourthJetEta_SingleTop_jetSel_emu__2->SetMarkerStyle(20);
   fourthJetEta_SingleTop_jetSel_emu__2->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_SingleTop_jetSel_emu__2->GetXaxis()->SetNdivisions(506);
   fourthJetEta_SingleTop_jetSel_emu__2->GetXaxis()->SetLabelFont(42);
   fourthJetEta_SingleTop_jetSel_emu__2->GetXaxis()->SetLabelOffset(999);
   fourthJetEta_SingleTop_jetSel_emu__2->GetXaxis()->SetLabelSize(0.05);
   fourthJetEta_SingleTop_jetSel_emu__2->GetXaxis()->SetTitleSize(0.08);
   fourthJetEta_SingleTop_jetSel_emu__2->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_SingleTop_jetSel_emu__2->GetXaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_jetSel_emu__2->GetYaxis()->SetTitle("Events");
   fourthJetEta_SingleTop_jetSel_emu__2->GetYaxis()->SetNdivisions(506);
   fourthJetEta_SingleTop_jetSel_emu__2->GetYaxis()->SetLabelFont(42);
   fourthJetEta_SingleTop_jetSel_emu__2->GetYaxis()->SetLabelOffset(0.01);
   fourthJetEta_SingleTop_jetSel_emu__2->GetYaxis()->SetLabelSize(0.062);
   fourthJetEta_SingleTop_jetSel_emu__2->GetYaxis()->SetTitleSize(0.08);
   fourthJetEta_SingleTop_jetSel_emu__2->GetYaxis()->SetTitleOffset(0.6336);
   fourthJetEta_SingleTop_jetSel_emu__2->GetYaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_jetSel_emu__2->GetZaxis()->SetLabelFont(42);
   fourthJetEta_SingleTop_jetSel_emu__2->GetZaxis()->SetLabelOffset(0.007);
   fourthJetEta_SingleTop_jetSel_emu__2->GetZaxis()->SetLabelSize(0.05);
   fourthJetEta_SingleTop_jetSel_emu__2->GetZaxis()->SetTitleSize(0.08);
   fourthJetEta_SingleTop_jetSel_emu__2->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_SingleTop_jetSel_emu__2->GetZaxis()->SetTitleFont(42);
   fourthJetEta_SingleTop_jetSel_emu__2->Draw("sameaxis");
   
/*   TPaveText *pt = new TPaveText(0.4325122,0.9371861,0.5674878,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Fourth Jet #eta");
   pt->Draw();*/
   canvy_1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: canvy_2
   TPad *canvy_2 = new TPad("canvy_2", "newpad2",0.01,0.01,0.99,0.322);
   canvy_2->Draw();
   canvy_2->cd();
   canvy_2->SetFillColor(0);
   canvy_2->SetBorderMode(0);
   canvy_2->SetGridy();

   canvy_2->SetLeftMargin( L/W );
   canvy_2->SetRightMargin( R/W );
   canvy_2->SetTopMargin( T/H );
   canvy_2->SetBottomMargin( B/H * 2.6 );
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   
   TH1D *fourthJetEta_data_jetSel_emu__3 = new TH1D("fourthJetEta_data_jetSel_emu__3","",25,0,5);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(0,1.002714);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(1,1.024468);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(2,1.012185);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(3,0.9692765);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(4,0.9998386);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(5,0.9251516);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(6,1.004001);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(7,1.057792);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(8,1.088204);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(9,0.9861247);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(10,1.15636);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(11,1.13361);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(12,1.03807);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(13,0.9294461);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(14,1.006372);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(15,0.8791263);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(16,0.7538457);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(17,1.051598);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(18,0.6057521);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(19,0.8174067);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(20,0.842478);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(21,1.011254);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(22,0.9836075);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(23,0.6923482);
   fourthJetEta_data_jetSel_emu__3->SetBinContent(24,0.6603579);
   fourthJetEta_data_jetSel_emu__3->SetBinError(0,0.02453513);
   fourthJetEta_data_jetSel_emu__3->SetBinError(1,0.08806003);
   fourthJetEta_data_jetSel_emu__3->SetBinError(2,0.08853516);
   fourthJetEta_data_jetSel_emu__3->SetBinError(3,0.08637244);
   fourthJetEta_data_jetSel_emu__3->SetBinError(4,0.08819842);
   fourthJetEta_data_jetSel_emu__3->SetBinError(5,0.08634739);
   fourthJetEta_data_jetSel_emu__3->SetBinError(6,0.094964);
   fourthJetEta_data_jetSel_emu__3->SetBinError(7,0.1032462);
   fourthJetEta_data_jetSel_emu__3->SetBinError(8,0.1069966);
   fourthJetEta_data_jetSel_emu__3->SetBinError(9,0.1044596);
   fourthJetEta_data_jetSel_emu__3->SetBinError(10,0.126216);
   fourthJetEta_data_jetSel_emu__3->SetBinError(11,0.1273731);
   fourthJetEta_data_jetSel_emu__3->SetBinError(12,0.1214069);
   fourthJetEta_data_jetSel_emu__3->SetBinError(13,0.1225403);
   fourthJetEta_data_jetSel_emu__3->SetBinError(14,0.1130487);
   fourthJetEta_data_jetSel_emu__3->SetBinError(15,0.1118923);
   fourthJetEta_data_jetSel_emu__3->SetBinError(16,0.128885);
   fourthJetEta_data_jetSel_emu__3->SetBinError(17,0.1605664);
   fourthJetEta_data_jetSel_emu__3->SetBinError(18,0.1297478);
   fourthJetEta_data_jetSel_emu__3->SetBinError(19,0.1680467);
   fourthJetEta_data_jetSel_emu__3->SetBinError(20,0.1961193);
   fourthJetEta_data_jetSel_emu__3->SetBinError(21,0.2459543);
   fourthJetEta_data_jetSel_emu__3->SetBinError(22,0.2666047);
   fourthJetEta_data_jetSel_emu__3->SetBinError(23,0.232554);
   fourthJetEta_data_jetSel_emu__3->SetBinError(24,0.3473799);
   fourthJetEta_data_jetSel_emu__3->SetMinimum(0.5);
   fourthJetEta_data_jetSel_emu__3->SetMaximum(1.5);
   fourthJetEta_data_jetSel_emu__3->SetEntries(853.7245);
   fourthJetEta_data_jetSel_emu__3->SetDirectory(0);
   fourthJetEta_data_jetSel_emu__3->SetStats(0);
   fourthJetEta_data_jetSel_emu__3->SetFillColor(1);
   fourthJetEta_data_jetSel_emu__3->SetLineWidth(2);
   fourthJetEta_data_jetSel_emu__3->SetLineColor(1); //
   fourthJetEta_data_jetSel_emu__3->SetMarkerStyle(20);
   fourthJetEta_data_jetSel_emu__3->SetMarkerSize(1.6);
   fourthJetEta_data_jetSel_emu__3->GetXaxis()->SetTitle("Fourth jet #eta");
   fourthJetEta_data_jetSel_emu__3->GetXaxis()->SetNdivisions(506);
   fourthJetEta_data_jetSel_emu__3->GetXaxis()->SetLabelFont(42);
   fourthJetEta_data_jetSel_emu__3->GetXaxis()->SetLabelOffset(0.013);
   fourthJetEta_data_jetSel_emu__3->GetXaxis()->SetLabelSize(0.13);
   fourthJetEta_data_jetSel_emu__3->GetXaxis()->SetTitleSize(0.13);
   fourthJetEta_data_jetSel_emu__3->GetXaxis()->SetTitleOffset(1);
   fourthJetEta_data_jetSel_emu__3->GetXaxis()->SetTitleFont(42);
   fourthJetEta_data_jetSel_emu__3->GetYaxis()->SetTitle("Data/MC");
   fourthJetEta_data_jetSel_emu__3->GetYaxis()->CenterTitle(true);
   fourthJetEta_data_jetSel_emu__3->GetYaxis()->SetNdivisions(506);
   fourthJetEta_data_jetSel_emu__3->GetYaxis()->SetLabelFont(42);
   fourthJetEta_data_jetSel_emu__3->GetYaxis()->SetLabelOffset(0.01);
   fourthJetEta_data_jetSel_emu__3->GetYaxis()->SetLabelSize(0.12);
   fourthJetEta_data_jetSel_emu__3->GetYaxis()->SetTitleSize(0.16);
   fourthJetEta_data_jetSel_emu__3->GetYaxis()->SetTitleOffset(0.3);
   fourthJetEta_data_jetSel_emu__3->GetYaxis()->SetTitleFont(42);
   fourthJetEta_data_jetSel_emu__3->GetZaxis()->SetLabelFont(42);
   fourthJetEta_data_jetSel_emu__3->GetZaxis()->SetLabelSize(0.035);
   fourthJetEta_data_jetSel_emu__3->GetZaxis()->SetTitleSize(0.035);
   fourthJetEta_data_jetSel_emu__3->GetZaxis()->SetTitleOffset(1);
   fourthJetEta_data_jetSel_emu__3->GetZaxis()->SetTitleFont(42);
   fourthJetEta_data_jetSel_emu__3->Draw("e x0, SCAT");
   canvy_2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
//   c1->SetSelected(fourthJetEta_data_jetSel_emu);
   c1->SaveAs("fourthJetEta_jetSel.pdf");
}
