void leadingJetEta_SingleTop_wMass()
{
//=========Macro generated from canvas: leadingJetEta_SingleTop_wMass/leadingJetEta_SingleTop_wMass
//=========  (Wed Aug 21 19:46:25 2019) by ROOT version 6.18/00

   // Set up cavas
   int W = 1280;
   int H = 1024;
   int H_ref = 925;
   int W_ref = 1024;

   // references for T, B, L, R
   float T = 0.08*H_ref;
   float B = 0.12*H_ref;
   float L = 0.12*W_ref;
   float R = 0.04*W_ref;

   TCanvas *c1 = new TCanvas("c1","c1",50,50,W,H);
   c1->cd();
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetLeftMargin( L/W );
   c1->SetRightMargin( R/W );
   c1->SetTopMargin( T/H );
   c1->SetBottomMargin( B/H );
   c1->SetTickx(0);
   c1->SetTicky(0);
  
// ------------>Primitives in pad: canvy_1
   TPad *canvy_1 = new TPad("canvy_1", "newpad",0.01,0.315,0.99,0.99);
   canvy_1->Draw();
   canvy_1->cd();
   canvy_1->SetFillColor(0);
   canvy_1->SetBorderMode(0);

   canvy_1->SetLeftMargin( L/W );
   canvy_1->SetRightMargin( R/W );
   canvy_1->SetTopMargin( T/H );
   canvy_1->SetBottomMargin( B/H * 0.3 );

   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);
   
   THStack *leadingJetEta_SingleTop_wMass_emu = new THStack();
   leadingJetEta_SingleTop_wMass_emu->SetName("leadingJetEta_SingleTop_wMass_emu");
   leadingJetEta_SingleTop_wMass_emu->SetTitle("Leading Jet #eta;Leading jet #eta;Events");
   leadingJetEta_SingleTop_wMass_emu->SetMaximum(183.7);
   
   TH1F *leadingJetEta_SingleTop_wMass_emu_stack_2 = new TH1F("leadingJetEta_SingleTop_wMass_emu_stack_2","Leading Jet #eta",25,0,5);
   leadingJetEta_SingleTop_wMass_emu_stack_2->SetMinimum(0);
   leadingJetEta_SingleTop_wMass_emu_stack_2->SetMaximum(192.885);
   leadingJetEta_SingleTop_wMass_emu_stack_2->SetDirectory(0);
   leadingJetEta_SingleTop_wMass_emu_stack_2->SetStats(0);
   leadingJetEta_SingleTop_wMass_emu_stack_2->SetLineStyle(0);
   leadingJetEta_SingleTop_wMass_emu_stack_2->SetLineWidth(0);
   leadingJetEta_SingleTop_wMass_emu_stack_2->SetMarkerStyle(20);
   leadingJetEta_SingleTop_wMass_emu_stack_2->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_SingleTop_wMass_emu_stack_2->GetXaxis()->SetNdivisions(506);
   leadingJetEta_SingleTop_wMass_emu_stack_2->GetXaxis()->SetLabelFont(42);
   leadingJetEta_SingleTop_wMass_emu_stack_2->GetXaxis()->SetLabelOffset(999);
   leadingJetEta_SingleTop_wMass_emu_stack_2->GetXaxis()->SetLabelSize(0.05);
   leadingJetEta_SingleTop_wMass_emu_stack_2->GetXaxis()->SetTitleSize(0.08);
   leadingJetEta_SingleTop_wMass_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_SingleTop_wMass_emu_stack_2->GetXaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_wMass_emu_stack_2->GetYaxis()->SetTitle("Events");
   leadingJetEta_SingleTop_wMass_emu_stack_2->GetYaxis()->SetNdivisions(506);
   leadingJetEta_SingleTop_wMass_emu_stack_2->GetYaxis()->SetLabelFont(42);
   leadingJetEta_SingleTop_wMass_emu_stack_2->GetYaxis()->SetLabelOffset(0.01);
   leadingJetEta_SingleTop_wMass_emu_stack_2->GetYaxis()->SetLabelSize(0.062);
   leadingJetEta_SingleTop_wMass_emu_stack_2->GetYaxis()->SetTitleSize(0.08);
   leadingJetEta_SingleTop_wMass_emu_stack_2->GetYaxis()->SetTitleOffset(0.6336);
   leadingJetEta_SingleTop_wMass_emu_stack_2->GetYaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_wMass_emu_stack_2->GetZaxis()->SetLabelFont(42);
   leadingJetEta_SingleTop_wMass_emu_stack_2->GetZaxis()->SetLabelOffset(0.007);
   leadingJetEta_SingleTop_wMass_emu_stack_2->GetZaxis()->SetLabelSize(0.05);
   leadingJetEta_SingleTop_wMass_emu_stack_2->GetZaxis()->SetTitleSize(0.08);
   leadingJetEta_SingleTop_wMass_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_SingleTop_wMass_emu_stack_2->GetZaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_wMass_emu->SetHistogram(leadingJetEta_SingleTop_wMass_emu_stack_2);
   
   
   TH1D *leadingJetEta_tZq_wMass_emu_stack_1 = new TH1D("leadingJetEta_tZq_wMass_emu_stack_1","leadingJetEta_tZq_wMass_emu",25,0,5);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(0,0.1565799);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(1,0.006521832);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(2,0.01396643);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(3,0.01848543);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(4,0.008489663);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(5,0.01451524);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(6,0.005896848);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(7,0.004445338);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(8,0.01431222);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(9,0.008434546);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(10,0.0250158);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(11,0.0123129);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(12,0.008447149);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(13,0.01545698);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(14,0.007868905);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(15,0.0009185759);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(16,0.003659311);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(17,0.008889314);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(18,0.003123906);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(19,0.003802332);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(20,0.000594564);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(21,-0.0003418423);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(22,0.002051612);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(23,0.0002015046);
   leadingJetEta_tZq_wMass_emu_stack_1->SetBinContent(24,0.000759933);
   leadingJetEta_tZq_wMass_emu_stack_1->SetEntries(2170);
   leadingJetEta_tZq_wMass_emu_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ffff00");
   leadingJetEta_tZq_wMass_emu_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   leadingJetEta_tZq_wMass_emu_stack_1->SetLineColor(ci);
   leadingJetEta_tZq_wMass_emu_stack_1->SetLineWidth(0);
   leadingJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetLabelFont(42);
   leadingJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetLabelSize(0.035);
   leadingJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleSize(0.035);
   leadingJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleFont(42);
   leadingJetEta_tZq_wMass_emu_stack_1->GetYaxis()->SetLabelFont(42);
   leadingJetEta_tZq_wMass_emu_stack_1->GetYaxis()->SetLabelSize(0.035);
   leadingJetEta_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleSize(0.035);
   leadingJetEta_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleOffset(1);
   leadingJetEta_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleFont(42);
   leadingJetEta_tZq_wMass_emu_stack_1->GetZaxis()->SetLabelFont(42);
   leadingJetEta_tZq_wMass_emu_stack_1->GetZaxis()->SetLabelSize(0.035);
   leadingJetEta_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleSize(0.035);
   leadingJetEta_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_wMass_emu->Add(leadingJetEta_tZq_wMass_emu_stack_1,"");
   
   TH1D *leadingJetEta_ttV_wMass_emu_stack_2 = new TH1D("leadingJetEta_ttV_wMass_emu_stack_2","leadingJetEta_ttV_wMass_emu",25,0,5);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(0,13.72478);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(1,1.469765);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(2,1.55242);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(3,1.857829);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(4,1.432852);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(5,1.693377);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(6,1.16584);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(7,0.9943552);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(8,0.9423246);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(9,0.7137694);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(10,0.8235931);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(11,0.2436705);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(12,0.5052787);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(13,0.3405746);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(14,0.2397412);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(15,0.07566424);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(16,0.05073069);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(17,0.0390645);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(18,0.008103274);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(19,-0.0006048739);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(20,0.001338114);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(21,0.001780561);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(22,0.001169439);
   leadingJetEta_ttV_wMass_emu_stack_2->SetBinContent(23,0.00175759);
   leadingJetEta_ttV_wMass_emu_stack_2->SetEntries(14144);
   leadingJetEta_ttV_wMass_emu_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#00ff00");
   leadingJetEta_ttV_wMass_emu_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   leadingJetEta_ttV_wMass_emu_stack_2->SetLineColor(ci);
   leadingJetEta_ttV_wMass_emu_stack_2->SetLineWidth(0);
   leadingJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetLabelFont(42);
   leadingJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetLabelSize(0.035);
   leadingJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleSize(0.035);
   leadingJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleFont(42);
   leadingJetEta_ttV_wMass_emu_stack_2->GetYaxis()->SetLabelFont(42);
   leadingJetEta_ttV_wMass_emu_stack_2->GetYaxis()->SetLabelSize(0.035);
   leadingJetEta_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleSize(0.035);
   leadingJetEta_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleOffset(1);
   leadingJetEta_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleFont(42);
   leadingJetEta_ttV_wMass_emu_stack_2->GetZaxis()->SetLabelFont(42);
   leadingJetEta_ttV_wMass_emu_stack_2->GetZaxis()->SetLabelSize(0.035);
   leadingJetEta_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleSize(0.035);
   leadingJetEta_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_wMass_emu->Add(leadingJetEta_ttV_wMass_emu_stack_2,"");
   
   TH1D *leadingJetEta_wJets_wMass_emu_stack_3 = new TH1D("leadingJetEta_wJets_wMass_emu_stack_3","leadingJetEta_wJets_wMass_emu",25,0,5);
   leadingJetEta_wJets_wMass_emu_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   leadingJetEta_wJets_wMass_emu_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#cccccc");
   leadingJetEta_wJets_wMass_emu_stack_3->SetLineColor(ci);
   leadingJetEta_wJets_wMass_emu_stack_3->SetLineWidth(0);
   leadingJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetLabelFont(42);
   leadingJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetLabelSize(0.035);
   leadingJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleSize(0.035);
   leadingJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleFont(42);
   leadingJetEta_wJets_wMass_emu_stack_3->GetYaxis()->SetLabelFont(42);
   leadingJetEta_wJets_wMass_emu_stack_3->GetYaxis()->SetLabelSize(0.035);
   leadingJetEta_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleSize(0.035);
   leadingJetEta_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleOffset(1);
   leadingJetEta_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleFont(42);
   leadingJetEta_wJets_wMass_emu_stack_3->GetZaxis()->SetLabelFont(42);
   leadingJetEta_wJets_wMass_emu_stack_3->GetZaxis()->SetLabelSize(0.035);
   leadingJetEta_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleSize(0.035);
   leadingJetEta_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_wMass_emu->Add(leadingJetEta_wJets_wMass_emu_stack_3,"");
   
   TH1D *leadingJetEta_VVV_wMass_emu_stack_4 = new TH1D("leadingJetEta_VVV_wMass_emu_stack_4","leadingJetEta_VVV_wMass_emu",25,0,5);
   leadingJetEta_VVV_wMass_emu_stack_4->SetBinContent(0,0.125076);
   leadingJetEta_VVV_wMass_emu_stack_4->SetBinContent(2,0.033447);
   leadingJetEta_VVV_wMass_emu_stack_4->SetBinContent(3,0.02946448);
   leadingJetEta_VVV_wMass_emu_stack_4->SetBinContent(6,0.03392089);
   leadingJetEta_VVV_wMass_emu_stack_4->SetBinContent(10,0.002352466);
   leadingJetEta_VVV_wMass_emu_stack_4->SetEntries(9);
   leadingJetEta_VVV_wMass_emu_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#00ffff");
   leadingJetEta_VVV_wMass_emu_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   leadingJetEta_VVV_wMass_emu_stack_4->SetLineColor(ci);
   leadingJetEta_VVV_wMass_emu_stack_4->SetLineWidth(0);
   leadingJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetLabelFont(42);
   leadingJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetLabelSize(0.035);
   leadingJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleSize(0.035);
   leadingJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleFont(42);
   leadingJetEta_VVV_wMass_emu_stack_4->GetYaxis()->SetLabelFont(42);
   leadingJetEta_VVV_wMass_emu_stack_4->GetYaxis()->SetLabelSize(0.035);
   leadingJetEta_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleSize(0.035);
   leadingJetEta_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleOffset(1);
   leadingJetEta_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleFont(42);
   leadingJetEta_VVV_wMass_emu_stack_4->GetZaxis()->SetLabelFont(42);
   leadingJetEta_VVV_wMass_emu_stack_4->GetZaxis()->SetLabelSize(0.035);
   leadingJetEta_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleSize(0.035);
   leadingJetEta_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_wMass_emu->Add(leadingJetEta_VVV_wMass_emu_stack_4,"");
   
   TH1D *leadingJetEta_VV_wMass_emu_stack_5 = new TH1D("leadingJetEta_VV_wMass_emu_stack_5","leadingJetEta_VV_wMass_emu",25,0,5);
   leadingJetEta_VV_wMass_emu_stack_5->SetBinContent(0,1.169151);
   leadingJetEta_VV_wMass_emu_stack_5->SetBinContent(1,-0.1808825);
   leadingJetEta_VV_wMass_emu_stack_5->SetBinContent(2,0.006187622);
   leadingJetEta_VV_wMass_emu_stack_5->SetBinContent(4,0.1547927);
   leadingJetEta_VV_wMass_emu_stack_5->SetBinContent(5,0.4186239);
   leadingJetEta_VV_wMass_emu_stack_5->SetBinContent(6,0.3396872);
   leadingJetEta_VV_wMass_emu_stack_5->SetBinContent(7,0.0114455);
   leadingJetEta_VV_wMass_emu_stack_5->SetBinContent(9,0.2142568);
   leadingJetEta_VV_wMass_emu_stack_5->SetBinContent(11,0.1964956);
   leadingJetEta_VV_wMass_emu_stack_5->SetBinContent(12,0.01066383);
   leadingJetEta_VV_wMass_emu_stack_5->SetBinContent(18,0.1391964);
   leadingJetEta_VV_wMass_emu_stack_5->SetEntries(45);
   leadingJetEta_VV_wMass_emu_stack_5->SetDirectory(0);

   ci = TColor::GetColor("#ff9933");
   leadingJetEta_VV_wMass_emu_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#ff9933");
   leadingJetEta_VV_wMass_emu_stack_5->SetLineColor(ci);
   leadingJetEta_VV_wMass_emu_stack_5->SetLineWidth(0);
   leadingJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetLabelFont(42);
   leadingJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetLabelSize(0.035);
   leadingJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetTitleSize(0.035);
   leadingJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetTitleFont(42);
   leadingJetEta_VV_wMass_emu_stack_5->GetYaxis()->SetLabelFont(42);
   leadingJetEta_VV_wMass_emu_stack_5->GetYaxis()->SetLabelSize(0.035);
   leadingJetEta_VV_wMass_emu_stack_5->GetYaxis()->SetTitleSize(0.035);
   leadingJetEta_VV_wMass_emu_stack_5->GetYaxis()->SetTitleOffset(1);
   leadingJetEta_VV_wMass_emu_stack_5->GetYaxis()->SetTitleFont(42);
   leadingJetEta_VV_wMass_emu_stack_5->GetZaxis()->SetLabelFont(42);
   leadingJetEta_VV_wMass_emu_stack_5->GetZaxis()->SetLabelSize(0.035);
   leadingJetEta_VV_wMass_emu_stack_5->GetZaxis()->SetTitleSize(0.035);
   leadingJetEta_VV_wMass_emu_stack_5->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_VV_wMass_emu_stack_5->GetZaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_wMass_emu->Add(leadingJetEta_VV_wMass_emu_stack_5,"");
   
   TH1D *leadingJetEta_SingleTop_wMass_emu_stack_6 = new TH1D("leadingJetEta_SingleTop_wMass_emu_stack_6","leadingJetEta_SingleTop_wMass_emu",25,0,5);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(0,54.3421);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(1,5.175141);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(2,7.557793);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(3,4.582636);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(4,6.506888);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(5,5.134992);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(6,2.73101);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(7,2.942856);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(8,4.036264);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(9,1.703933);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(10,2.477392);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(11,1.198814);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(12,2.101445);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(13,0.5470659);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(14,1.211068);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(15,0.5331959);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(16,0.8827516);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(17,0.3402744);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(18,0.3763149);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(19,0.181775);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(20,0.1689767);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(22,0.0007822226);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(23,0.0006550062);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetEntries(1034);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetDirectory(0);

   ci = TColor::GetColor("#ff00ff");
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetLineColor(ci);
   leadingJetEta_SingleTop_wMass_emu_stack_6->SetLineWidth(0);
   leadingJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetLabelFont(42);
   leadingJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetLabelSize(0.035);
   leadingJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleSize(0.035);
   leadingJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_wMass_emu_stack_6->GetYaxis()->SetLabelFont(42);
   leadingJetEta_SingleTop_wMass_emu_stack_6->GetYaxis()->SetLabelSize(0.035);
   leadingJetEta_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleSize(0.035);
   leadingJetEta_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleOffset(1);
   leadingJetEta_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_wMass_emu_stack_6->GetZaxis()->SetLabelFont(42);
   leadingJetEta_SingleTop_wMass_emu_stack_6->GetZaxis()->SetLabelSize(0.035);
   leadingJetEta_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleSize(0.035);
   leadingJetEta_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_wMass_emu->Add(leadingJetEta_SingleTop_wMass_emu_stack_6,"");
   
   TH1D *leadingJetEta_tt_wMass_emu_stack_7 = new TH1D("leadingJetEta_tt_wMass_emu_stack_7","leadingJetEta_tt_wMass_emu",25,0,5);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(0,1193.336);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(1,145.1524);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(2,127.6421);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(3,125.0072);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(4,119.8547);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(5,102.8933);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(6,103.4339);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(7,91.98216);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(8,79.36934);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(9,71.95562);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(10,51.4684);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(11,54.40957);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(12,40.39387);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(13,21.16002);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(14,26.26711);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(15,13.23951);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(16,9.653299);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(17,9.207968);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(18,6.119246);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(19,4.497943);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(20,3.114357);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(22,0.3262253);
   leadingJetEta_tt_wMass_emu_stack_7->SetBinContent(23,0.2944081);
   leadingJetEta_tt_wMass_emu_stack_7->SetEntries(7802);
   leadingJetEta_tt_wMass_emu_stack_7->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   leadingJetEta_tt_wMass_emu_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   leadingJetEta_tt_wMass_emu_stack_7->SetLineColor(ci);
   leadingJetEta_tt_wMass_emu_stack_7->SetLineWidth(0);
   leadingJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetLabelFont(42);
   leadingJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetLabelSize(0.035);
   leadingJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetTitleSize(0.035);
   leadingJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetTitleFont(42);
   leadingJetEta_tt_wMass_emu_stack_7->GetYaxis()->SetLabelFont(42);
   leadingJetEta_tt_wMass_emu_stack_7->GetYaxis()->SetLabelSize(0.035);
   leadingJetEta_tt_wMass_emu_stack_7->GetYaxis()->SetTitleSize(0.035);
   leadingJetEta_tt_wMass_emu_stack_7->GetYaxis()->SetTitleOffset(1);
   leadingJetEta_tt_wMass_emu_stack_7->GetYaxis()->SetTitleFont(42);
   leadingJetEta_tt_wMass_emu_stack_7->GetZaxis()->SetLabelFont(42);
   leadingJetEta_tt_wMass_emu_stack_7->GetZaxis()->SetLabelSize(0.035);
   leadingJetEta_tt_wMass_emu_stack_7->GetZaxis()->SetTitleSize(0.035);
   leadingJetEta_tt_wMass_emu_stack_7->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_tt_wMass_emu_stack_7->GetZaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_wMass_emu->Add(leadingJetEta_tt_wMass_emu_stack_7,"");
   
   TH1D *leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8 = new TH1D("leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8","leadingJetEta_zPlusJetsMadgraph_wMass_emu",25,0,5);
   leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->SetLineColor(ci);
   leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->SetLineWidth(0);
   leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetLabelFont(42);
   leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetLabelSize(0.035);
   leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleSize(0.035);
   leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleFont(42);
   leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetLabelFont(42);
   leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetLabelSize(0.035);
   leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleSize(0.035);
   leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleOffset(1);
   leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleFont(42);
   leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetLabelFont(42);
   leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetLabelSize(0.035);
   leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleSize(0.035);
   leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_wMass_emu->Add(leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8,"");
   leadingJetEta_SingleTop_wMass_emu->Draw("");
   
   TH1D *leadingJetEta_data_wMass_emu__4 = new TH1D("leadingJetEta_data_wMass_emu__4","leadingJetEta_data_wMass_emu",25,0,5);
   leadingJetEta_data_wMass_emu__4->SetBinContent(0,1336);
   leadingJetEta_data_wMass_emu__4->SetBinContent(1,167);
   leadingJetEta_data_wMass_emu__4->SetBinContent(2,138);
   leadingJetEta_data_wMass_emu__4->SetBinContent(3,137);
   leadingJetEta_data_wMass_emu__4->SetBinContent(4,143);
   leadingJetEta_data_wMass_emu__4->SetBinContent(5,114);
   leadingJetEta_data_wMass_emu__4->SetBinContent(6,108);
   leadingJetEta_data_wMass_emu__4->SetBinContent(7,90);
   leadingJetEta_data_wMass_emu__4->SetBinContent(8,87);
   leadingJetEta_data_wMass_emu__4->SetBinContent(9,74);
   leadingJetEta_data_wMass_emu__4->SetBinContent(10,67);
   leadingJetEta_data_wMass_emu__4->SetBinContent(11,56);
   leadingJetEta_data_wMass_emu__4->SetBinContent(12,36);
   leadingJetEta_data_wMass_emu__4->SetBinContent(13,30);
   leadingJetEta_data_wMass_emu__4->SetBinContent(14,30);
   leadingJetEta_data_wMass_emu__4->SetBinContent(15,17);
   leadingJetEta_data_wMass_emu__4->SetBinContent(16,10);
   leadingJetEta_data_wMass_emu__4->SetBinContent(17,8);
   leadingJetEta_data_wMass_emu__4->SetBinContent(18,8);
   leadingJetEta_data_wMass_emu__4->SetBinContent(19,5);
   leadingJetEta_data_wMass_emu__4->SetBinContent(20,1);
   leadingJetEta_data_wMass_emu__4->SetBinContent(21,2);
   leadingJetEta_data_wMass_emu__4->SetBinContent(22,2);
   leadingJetEta_data_wMass_emu__4->SetBinContent(23,1);
   leadingJetEta_data_wMass_emu__4->SetBinContent(24,1);
   leadingJetEta_data_wMass_emu__4->SetEntries(2668);
   leadingJetEta_data_wMass_emu__4->SetDirectory(0);
   leadingJetEta_data_wMass_emu__4->SetFillColor(1);
   leadingJetEta_data_wMass_emu__4->SetLineWidth(2);
   leadingJetEta_data_wMass_emu__4->SetLineColor(1); //
   leadingJetEta_data_wMass_emu__4->SetMarkerStyle(20);
   leadingJetEta_data_wMass_emu__4->SetMarkerSize(1.4);
   leadingJetEta_data_wMass_emu__4->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_data_wMass_emu__4->GetXaxis()->SetLabelFont(42);
   leadingJetEta_data_wMass_emu__4->GetXaxis()->SetLabelSize(0.035);
   leadingJetEta_data_wMass_emu__4->GetXaxis()->SetTitleSize(0.035);
   leadingJetEta_data_wMass_emu__4->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_data_wMass_emu__4->GetXaxis()->SetTitleFont(42);
   leadingJetEta_data_wMass_emu__4->GetYaxis()->SetLabelFont(42);
   leadingJetEta_data_wMass_emu__4->GetYaxis()->SetLabelSize(0.035);
   leadingJetEta_data_wMass_emu__4->GetYaxis()->SetTitleSize(0.035);
   leadingJetEta_data_wMass_emu__4->GetYaxis()->SetTitleOffset(1);
   leadingJetEta_data_wMass_emu__4->GetYaxis()->SetTitleFont(42);
   leadingJetEta_data_wMass_emu__4->GetZaxis()->SetLabelFont(42);
   leadingJetEta_data_wMass_emu__4->GetZaxis()->SetLabelSize(0.035);
   leadingJetEta_data_wMass_emu__4->GetZaxis()->SetTitleSize(0.035);
   leadingJetEta_data_wMass_emu__4->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_data_wMass_emu__4->GetZaxis()->SetTitleFont(42);
   leadingJetEta_data_wMass_emu__4->Draw("e x0, same");
   
   TLegend *leg = new TLegend(0.78,0.42,0.98,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("leadingJetEta_zPlusJetsMadgraph_wMass_emu_stack_8","Z+jets (LO)","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetEta_tt_wMass_emu_stack_7","t#bar{t}","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetEta_SingleTop_wMass_emu_stack_6","Single top","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetEta_VV_wMass_emu_stack_5","VV","f");

   ci = TColor::GetColor("#ff9933");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetEta_VVV_wMass_emu_stack_4","VVV","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetEta_wJets_wMass_emu_stack_3","W+jets","f");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetEta_ttV_wMass_emu_stack_2","t#bar{t}V","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetEta_tZq_wMass_emu_stack_1","tZq","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetEta_data_wMass_emu","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.4);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.968,0.9429101,"35.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06792969);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.096,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.05419922);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16899,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.04119141);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *leadingJetEta_SingleTop_wMass_emu__5 = new TH1F("leadingJetEta_SingleTop_wMass_emu__5","Leading Jet #eta",25,0,5);
   leadingJetEta_SingleTop_wMass_emu__5->SetMinimum(0);
   leadingJetEta_SingleTop_wMass_emu__5->SetMaximum(192.885);
   leadingJetEta_SingleTop_wMass_emu__5->SetDirectory(0);
   leadingJetEta_SingleTop_wMass_emu__5->SetStats(0);
   leadingJetEta_SingleTop_wMass_emu__5->SetLineStyle(0);
   leadingJetEta_SingleTop_wMass_emu__5->SetLineWidth(0);
   leadingJetEta_SingleTop_wMass_emu__5->SetMarkerStyle(20);
   leadingJetEta_SingleTop_wMass_emu__5->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_SingleTop_wMass_emu__5->GetXaxis()->SetNdivisions(506);
   leadingJetEta_SingleTop_wMass_emu__5->GetXaxis()->SetLabelFont(42);
   leadingJetEta_SingleTop_wMass_emu__5->GetXaxis()->SetLabelOffset(999);
   leadingJetEta_SingleTop_wMass_emu__5->GetXaxis()->SetLabelSize(0.05);
   leadingJetEta_SingleTop_wMass_emu__5->GetXaxis()->SetTitleSize(0.08);
   leadingJetEta_SingleTop_wMass_emu__5->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_SingleTop_wMass_emu__5->GetXaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_wMass_emu__5->GetYaxis()->SetTitle("Events");
   leadingJetEta_SingleTop_wMass_emu__5->GetYaxis()->SetNdivisions(506);
   leadingJetEta_SingleTop_wMass_emu__5->GetYaxis()->SetLabelFont(42);
   leadingJetEta_SingleTop_wMass_emu__5->GetYaxis()->SetLabelOffset(0.01);
   leadingJetEta_SingleTop_wMass_emu__5->GetYaxis()->SetLabelSize(0.062);
   leadingJetEta_SingleTop_wMass_emu__5->GetYaxis()->SetTitleSize(0.08);
   leadingJetEta_SingleTop_wMass_emu__5->GetYaxis()->SetTitleOffset(0.6336);
   leadingJetEta_SingleTop_wMass_emu__5->GetYaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_wMass_emu__5->GetZaxis()->SetLabelFont(42);
   leadingJetEta_SingleTop_wMass_emu__5->GetZaxis()->SetLabelOffset(0.007);
   leadingJetEta_SingleTop_wMass_emu__5->GetZaxis()->SetLabelSize(0.05);
   leadingJetEta_SingleTop_wMass_emu__5->GetZaxis()->SetTitleSize(0.08);
   leadingJetEta_SingleTop_wMass_emu__5->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_SingleTop_wMass_emu__5->GetZaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_wMass_emu__5->Draw("sameaxis");
   
   TPaveText *pt = new TPaveText(0.4261247,0.9371861,0.5738753,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Leading Jet #eta");
   pt->Draw();
   canvy_1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: canvy_2
   TPad *canvy_2 = new TPad("canvy_2", "newpad2",0.01,0.01,0.99,0.322);
   canvy_2->Draw();
   canvy_2->cd();
   canvy_2->SetFillColor(0);
   canvy_2->SetBorderMode(0);
   canvy_2->SetGridy();

   canvy_2->SetLeftMargin( L/W );
   canvy_2->SetRightMargin( R/W );
   canvy_2->SetTopMargin( T/H );
   canvy_2->SetBottomMargin( B/H * 2.6 );
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   
   TH1D *leadingJetEta_data_wMass_emu__6 = new TH1D("leadingJetEta_data_wMass_emu__6","",25,0,5);
   leadingJetEta_data_wMass_emu__6->SetBinContent(0,1.057921);
   leadingJetEta_data_wMass_emu__6->SetBinContent(1,1.101417);
   leadingJetEta_data_wMass_emu__6->SetBinContent(2,1.008729);
   leadingJetEta_data_wMass_emu__6->SetBinContent(3,1.04186);
   leadingJetEta_data_wMass_emu__6->SetBinContent(4,1.117557);
   leadingJetEta_data_wMass_emu__6->SetBinContent(5,1.034907);
   leadingJetEta_data_wMass_emu__6->SetBinContent(6,1.00269);
   leadingJetEta_data_wMass_emu__6->SetBinContent(7,0.9381326);
   leadingJetEta_data_wMass_emu__6->SetBinContent(8,1.031267);
   leadingJetEta_data_wMass_emu__6->SetBinContent(9,0.9920101);
   leadingJetEta_data_wMass_emu__6->SetBinContent(10,1.2227);
   leadingJetEta_data_wMass_emu__6->SetBinContent(11,0.9989143);
   leadingJetEta_data_wMass_emu__6->SetBinContent(12,0.8368258);
   leadingJetEta_data_wMass_emu__6->SetBinContent(13,1.359736);
   leadingJetEta_data_wMass_emu__6->SetBinContent(14,1.082025);
   leadingJetEta_data_wMass_emu__6->SetBinContent(15,1.2275);
   leadingJetEta_data_wMass_emu__6->SetBinContent(16,0.9442478);
   leadingJetEta_data_wMass_emu__6->SetBinContent(17,0.8336636);
   leadingJetEta_data_wMass_emu__6->SetBinContent(18,1.203734);
   leadingJetEta_data_wMass_emu__6->SetBinContent(19,1.067711);
   leadingJetEta_data_wMass_emu__6->SetBinContent(20,0.3043893);
   leadingJetEta_data_wMass_emu__6->SetBinContent(21,1390.125);
   leadingJetEta_data_wMass_emu__6->SetBinContent(22,6.056411);
   leadingJetEta_data_wMass_emu__6->SetBinContent(23,3.366751);
   leadingJetEta_data_wMass_emu__6->SetBinContent(24,1315.906);
   leadingJetEta_data_wMass_emu__6->SetBinError(0,0.04152067);
   leadingJetEta_data_wMass_emu__6->SetBinError(1,0.1235519);
   leadingJetEta_data_wMass_emu__6->SetBinError(2,0.1217014);
   leadingJetEta_data_wMass_emu__6->SetBinError(3,0.1271927);
   leadingJetEta_data_wMass_emu__6->SetBinError(4,0.1359938);
   leadingJetEta_data_wMass_emu__6->SetBinError(5,0.1382678);
   leadingJetEta_data_wMass_emu__6->SetBinError(6,0.1365406);
   leadingJetEta_data_wMass_emu__6->SetBinError(7,0.1376685);
   leadingJetEta_data_wMass_emu__6->SetBinError(8,0.1575778);
   leadingJetEta_data_wMass_emu__6->SetBinError(9,0.1627594);
   leadingJetEta_data_wMass_emu__6->SetBinError(10,0.2227014);
   leadingJetEta_data_wMass_emu__6->SetBinError(11,0.1887258);
   leadingJetEta_data_wMass_emu__6->SetBinError(12,0.1890244);
   leadingJetEta_data_wMass_emu__6->SetBinError(13,0.3813515);
   leadingJetEta_data_wMass_emu__6->SetBinError(14,0.2850491);
   leadingJetEta_data_wMass_emu__6->SetBinError(15,0.4443302);
   leadingJetEta_data_wMass_emu__6->SetBinError(16,0.4163531);
   leadingJetEta_data_wMass_emu__6->SetBinError(17,0.399122);
   leadingJetEta_data_wMass_emu__6->SetBinError(18,0.6317792);
   leadingJetEta_data_wMass_emu__6->SetBinError(19,0.6866156);
   leadingJetEta_data_wMass_emu__6->SetBinError(20,0.3476426);
   leadingJetEta_data_wMass_emu__6->SetBinError(21,36662.5);
   leadingJetEta_data_wMass_emu__6->SetBinError(22,11.37607);
   leadingJetEta_data_wMass_emu__6->SetBinError(23,7.035424);
   leadingJetEta_data_wMass_emu__6->SetBinError(24,47753.15);
   leadingJetEta_data_wMass_emu__6->SetMinimum(0.5);
   leadingJetEta_data_wMass_emu__6->SetMaximum(1.5);
   leadingJetEta_data_wMass_emu__6->SetEntries(0.002065007);
   leadingJetEta_data_wMass_emu__6->SetDirectory(0);
   leadingJetEta_data_wMass_emu__6->SetStats(0);
   leadingJetEta_data_wMass_emu__6->SetFillColor(1);
   leadingJetEta_data_wMass_emu__6->SetLineWidth(2);
   leadingJetEta_data_wMass_emu__6->SetLineColor(1); //
   leadingJetEta_data_wMass_emu__6->SetMarkerStyle(20);
   leadingJetEta_data_wMass_emu__6->SetMarkerSize(1.6);
   leadingJetEta_data_wMass_emu__6->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_data_wMass_emu__6->GetXaxis()->SetNdivisions(506);
   leadingJetEta_data_wMass_emu__6->GetXaxis()->SetLabelFont(42);
   leadingJetEta_data_wMass_emu__6->GetXaxis()->SetLabelOffset(0.013);
   leadingJetEta_data_wMass_emu__6->GetXaxis()->SetLabelSize(0.13);
   leadingJetEta_data_wMass_emu__6->GetXaxis()->SetTitleSize(0.13);
   leadingJetEta_data_wMass_emu__6->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_data_wMass_emu__6->GetXaxis()->SetTitleFont(42);
   leadingJetEta_data_wMass_emu__6->GetYaxis()->SetTitle("Data/MC");
   leadingJetEta_data_wMass_emu__6->GetYaxis()->CenterTitle(true);
   leadingJetEta_data_wMass_emu__6->GetYaxis()->SetNdivisions(506);
   leadingJetEta_data_wMass_emu__6->GetYaxis()->SetLabelFont(42);
   leadingJetEta_data_wMass_emu__6->GetYaxis()->SetLabelOffset(0.01);
   leadingJetEta_data_wMass_emu__6->GetYaxis()->SetLabelSize(0.12);
   leadingJetEta_data_wMass_emu__6->GetYaxis()->SetTitleSize(0.16);
   leadingJetEta_data_wMass_emu__6->GetYaxis()->SetTitleOffset(0.3);
   leadingJetEta_data_wMass_emu__6->GetYaxis()->SetTitleFont(42);
   leadingJetEta_data_wMass_emu__6->GetZaxis()->SetLabelFont(42);
   leadingJetEta_data_wMass_emu__6->GetZaxis()->SetLabelSize(0.035);
   leadingJetEta_data_wMass_emu__6->GetZaxis()->SetTitleSize(0.035);
   leadingJetEta_data_wMass_emu__6->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_data_wMass_emu__6->GetZaxis()->SetTitleFont(42);
   leadingJetEta_data_wMass_emu__6->Draw("e x0, SCAT");
   canvy_2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
//   c1->SetSelected(leadingJetEta_data_wMass_emu);
   c1->SaveAs("leadingJetEta_wMass.pdf");
}
