void leadingJetEta_SingleTop_jetSel()
{
//=========Macro generated from canvas: leadingJetEta_SingleTop_jetSel/leadingJetEta_SingleTop_jetSel
//=========  (Wed Aug 21 19:45:47 2019) by ROOT version 6.18/00

   // Set up cavas
   int W = 1280;
   int H = 1024;
   int H_ref = 925;
   int W_ref = 1024;

   // references for T, B, L, R
   float T = 0.08*H_ref;
   float B = 0.12*H_ref;
   float L = 0.12*W_ref;
   float R = 0.04*W_ref;

   TCanvas *c1 = new TCanvas("c1","c1",50,50,W,H);
   c1->cd();
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetLeftMargin( L/W );
   c1->SetRightMargin( R/W );
   c1->SetTopMargin( T/H );
   c1->SetBottomMargin( B/H );
   c1->SetTickx(0);
   c1->SetTicky(0);
  
// ------------>Primitives in pad: canvy_1
   TPad *canvy_1 = new TPad("canvy_1", "newpad",0.01,0.315,0.99,0.99);
   canvy_1->Draw();
   canvy_1->cd();
   canvy_1->SetFillColor(0);
   canvy_1->SetBorderMode(0);

   canvy_1->SetLeftMargin( L/W );
   canvy_1->SetRightMargin( R/W );
   canvy_1->SetTopMargin( T/H );
   canvy_1->SetBottomMargin( B/H * 0.3 );

   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);
   
   THStack *leadingJetEta_SingleTop_jetSel_emu = new THStack();
   leadingJetEta_SingleTop_jetSel_emu->SetName("leadingJetEta_SingleTop_jetSel_emu");
   leadingJetEta_SingleTop_jetSel_emu->SetTitle(";Leading jet #eta;Events");
   leadingJetEta_SingleTop_jetSel_emu->SetMaximum(392.743);
   
   TH1F *leadingJetEta_SingleTop_jetSel_emu_stack_2 = new TH1F("leadingJetEta_SingleTop_jetSel_emu_stack_2","Leading Jet #eta",25,0,5);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->SetMinimum(0);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->SetMaximum(412.3802);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->SetDirectory(0);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->SetStats(0);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->SetLineStyle(0);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->SetLineWidth(0);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->SetMarkerStyle(20);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_SingleTop_jetSel_emu_stack_2->GetXaxis()->SetNdivisions(506);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->GetXaxis()->SetLabelFont(42);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->GetXaxis()->SetLabelOffset(999);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->GetXaxis()->SetLabelSize(0.05);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->GetXaxis()->SetTitleSize(0.08);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->GetXaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->GetYaxis()->SetTitle("Events");
   leadingJetEta_SingleTop_jetSel_emu_stack_2->GetYaxis()->SetNdivisions(506);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->GetYaxis()->SetLabelFont(42);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->GetYaxis()->SetLabelOffset(0.01);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->GetYaxis()->SetLabelSize(0.062);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->GetYaxis()->SetTitleSize(0.08);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->GetYaxis()->SetTitleOffset(0.6336);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->GetYaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->GetZaxis()->SetLabelFont(42);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->GetZaxis()->SetLabelOffset(0.007);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->GetZaxis()->SetLabelSize(0.05);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->GetZaxis()->SetTitleSize(0.08);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_SingleTop_jetSel_emu_stack_2->GetZaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_jetSel_emu->SetHistogram(leadingJetEta_SingleTop_jetSel_emu_stack_2);
   
   
   TH1D *leadingJetEta_tZq_jetSel_emu_stack_1 = new TH1D("leadingJetEta_tZq_jetSel_emu_stack_1","leadingJetEta_tZq_jetSel_emu",25,0,5);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(0,0.5624584);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(1,0.0330022);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(2,0.03374755);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(3,0.03793552);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(4,0.01994551);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(5,0.03438445);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(6,0.03017866);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(7,0.03257703);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(8,0.03255888);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(9,0.04356327);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(10,0.03339049);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(11,0.02518068);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(12,0.02832029);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(13,0.02992584);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(14,0.02254213);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(15,0.0224307);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(16,0.02945622);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(17,0.02053012);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(18,0.002176037);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(19,0.01537913);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(20,0.007672659);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(21,0.003124508);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(22,0.003576346);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(23,0.001516921);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetBinContent(24,-8.089672e-05);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetEntries(6672);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ffff00");
   leadingJetEta_tZq_jetSel_emu_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   leadingJetEta_tZq_jetSel_emu_stack_1->SetLineColor(ci);
   leadingJetEta_tZq_jetSel_emu_stack_1->SetLineWidth(0);
   leadingJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetLabelFont(42);
   leadingJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetLabelSize(0.035);
   leadingJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleSize(0.035);
   leadingJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleFont(42);
   leadingJetEta_tZq_jetSel_emu_stack_1->GetYaxis()->SetLabelFont(42);
   leadingJetEta_tZq_jetSel_emu_stack_1->GetYaxis()->SetLabelSize(0.035);
   leadingJetEta_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleSize(0.035);
   leadingJetEta_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleOffset(1);
   leadingJetEta_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleFont(42);
   leadingJetEta_tZq_jetSel_emu_stack_1->GetZaxis()->SetLabelFont(42);
   leadingJetEta_tZq_jetSel_emu_stack_1->GetZaxis()->SetLabelSize(0.035);
   leadingJetEta_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleSize(0.035);
   leadingJetEta_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_jetSel_emu->Add(leadingJetEta_tZq_jetSel_emu_stack_1,"");
   
   TH1D *leadingJetEta_ttV_jetSel_emu_stack_2 = new TH1D("leadingJetEta_ttV_jetSel_emu_stack_2","leadingJetEta_ttV_jetSel_emu",25,0,5);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(0,26.9313);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(1,3.242426);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(2,2.841352);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(3,3.824996);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(4,3.081512);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(5,3.156926);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(6,2.448432);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(7,2.082452);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(8,2.255859);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(9,1.407448);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(10,1.360994);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(11,0.8967168);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(12,0.9735193);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(13,0.7571737);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(14,0.5829985);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(15,0.1781885);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(16,0.1895716);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(17,0.2337327);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(18,0.03901307);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(19,0.01475448);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(20,0.01089909);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(21,0.007186686);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(22,0.001169439);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetBinContent(23,0.004818833);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetEntries(29408);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#00ff00");
   leadingJetEta_ttV_jetSel_emu_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   leadingJetEta_ttV_jetSel_emu_stack_2->SetLineColor(ci);
   leadingJetEta_ttV_jetSel_emu_stack_2->SetLineWidth(0);
   leadingJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetLabelFont(42);
   leadingJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetLabelSize(0.035);
   leadingJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleSize(0.035);
   leadingJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleFont(42);
   leadingJetEta_ttV_jetSel_emu_stack_2->GetYaxis()->SetLabelFont(42);
   leadingJetEta_ttV_jetSel_emu_stack_2->GetYaxis()->SetLabelSize(0.035);
   leadingJetEta_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleSize(0.035);
   leadingJetEta_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleOffset(1);
   leadingJetEta_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleFont(42);
   leadingJetEta_ttV_jetSel_emu_stack_2->GetZaxis()->SetLabelFont(42);
   leadingJetEta_ttV_jetSel_emu_stack_2->GetZaxis()->SetLabelSize(0.035);
   leadingJetEta_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleSize(0.035);
   leadingJetEta_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_jetSel_emu->Add(leadingJetEta_ttV_jetSel_emu_stack_2,"");
   
   TH1D *leadingJetEta_wJets_jetSel_emu_stack_3 = new TH1D("leadingJetEta_wJets_jetSel_emu_stack_3","leadingJetEta_wJets_jetSel_emu",25,0,5);
   leadingJetEta_wJets_jetSel_emu_stack_3->SetBinContent(0,12.53387);
   leadingJetEta_wJets_jetSel_emu_stack_3->SetBinContent(9,13.42844);
   leadingJetEta_wJets_jetSel_emu_stack_3->SetEntries(2);
   leadingJetEta_wJets_jetSel_emu_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   leadingJetEta_wJets_jetSel_emu_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#cccccc");
   leadingJetEta_wJets_jetSel_emu_stack_3->SetLineColor(ci);
   leadingJetEta_wJets_jetSel_emu_stack_3->SetLineWidth(0);
   leadingJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetLabelFont(42);
   leadingJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetLabelSize(0.035);
   leadingJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleSize(0.035);
   leadingJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleFont(42);
   leadingJetEta_wJets_jetSel_emu_stack_3->GetYaxis()->SetLabelFont(42);
   leadingJetEta_wJets_jetSel_emu_stack_3->GetYaxis()->SetLabelSize(0.035);
   leadingJetEta_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleSize(0.035);
   leadingJetEta_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleOffset(1);
   leadingJetEta_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleFont(42);
   leadingJetEta_wJets_jetSel_emu_stack_3->GetZaxis()->SetLabelFont(42);
   leadingJetEta_wJets_jetSel_emu_stack_3->GetZaxis()->SetLabelSize(0.035);
   leadingJetEta_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleSize(0.035);
   leadingJetEta_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_jetSel_emu->Add(leadingJetEta_wJets_jetSel_emu_stack_3,"");
   
   TH1D *leadingJetEta_VVV_jetSel_emu_stack_4 = new TH1D("leadingJetEta_VVV_jetSel_emu_stack_4","leadingJetEta_VVV_jetSel_emu",25,0,5);
   leadingJetEta_VVV_jetSel_emu_stack_4->SetBinContent(0,2.101923);
   leadingJetEta_VVV_jetSel_emu_stack_4->SetBinContent(1,0.1735462);
   leadingJetEta_VVV_jetSel_emu_stack_4->SetBinContent(2,0.2022206);
   leadingJetEta_VVV_jetSel_emu_stack_4->SetBinContent(3,0.09532542);
   leadingJetEta_VVV_jetSel_emu_stack_4->SetBinContent(4,0.2628605);
   leadingJetEta_VVV_jetSel_emu_stack_4->SetBinContent(5,0.03274528);
   leadingJetEta_VVV_jetSel_emu_stack_4->SetBinContent(6,0.133464);
   leadingJetEta_VVV_jetSel_emu_stack_4->SetBinContent(7,0.2123132);
   leadingJetEta_VVV_jetSel_emu_stack_4->SetBinContent(8,0.1285239);
   leadingJetEta_VVV_jetSel_emu_stack_4->SetBinContent(9,0.08149166);
   leadingJetEta_VVV_jetSel_emu_stack_4->SetBinContent(10,0.04614654);
   leadingJetEta_VVV_jetSel_emu_stack_4->SetBinContent(11,0.06539443);
   leadingJetEta_VVV_jetSel_emu_stack_4->SetBinContent(12,0.03434761);
   leadingJetEta_VVV_jetSel_emu_stack_4->SetBinContent(13,0.03551877);
   leadingJetEta_VVV_jetSel_emu_stack_4->SetBinContent(15,0.07853043);
   leadingJetEta_VVV_jetSel_emu_stack_4->SetEntries(147);
   leadingJetEta_VVV_jetSel_emu_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#00ffff");
   leadingJetEta_VVV_jetSel_emu_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   leadingJetEta_VVV_jetSel_emu_stack_4->SetLineColor(ci);
   leadingJetEta_VVV_jetSel_emu_stack_4->SetLineWidth(0);
   leadingJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetLabelFont(42);
   leadingJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetLabelSize(0.035);
   leadingJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleSize(0.035);
   leadingJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleFont(42);
   leadingJetEta_VVV_jetSel_emu_stack_4->GetYaxis()->SetLabelFont(42);
   leadingJetEta_VVV_jetSel_emu_stack_4->GetYaxis()->SetLabelSize(0.035);
   leadingJetEta_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleSize(0.035);
   leadingJetEta_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleOffset(1);
   leadingJetEta_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleFont(42);
   leadingJetEta_VVV_jetSel_emu_stack_4->GetZaxis()->SetLabelFont(42);
   leadingJetEta_VVV_jetSel_emu_stack_4->GetZaxis()->SetLabelSize(0.035);
   leadingJetEta_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleSize(0.035);
   leadingJetEta_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_jetSel_emu->Add(leadingJetEta_VVV_jetSel_emu_stack_4,"");
   
   TH1D *leadingJetEta_VV_jetSel_emu_stack_5 = new TH1D("leadingJetEta_VV_jetSel_emu_stack_5","leadingJetEta_VV_jetSel_emu",25,0,5);
   leadingJetEta_VV_jetSel_emu_stack_5->SetBinContent(0,29.94626);
   leadingJetEta_VV_jetSel_emu_stack_5->SetBinContent(1,2.570924);
   leadingJetEta_VV_jetSel_emu_stack_5->SetBinContent(2,3.127085);
   leadingJetEta_VV_jetSel_emu_stack_5->SetBinContent(3,1.529481);
   leadingJetEta_VV_jetSel_emu_stack_5->SetBinContent(4,3.433594);
   leadingJetEta_VV_jetSel_emu_stack_5->SetBinContent(5,3.726008);
   leadingJetEta_VV_jetSel_emu_stack_5->SetBinContent(6,2.867578);
   leadingJetEta_VV_jetSel_emu_stack_5->SetBinContent(7,2.282059);
   leadingJetEta_VV_jetSel_emu_stack_5->SetBinContent(8,2.035931);
   leadingJetEta_VV_jetSel_emu_stack_5->SetBinContent(9,1.627262);
   leadingJetEta_VV_jetSel_emu_stack_5->SetBinContent(10,1.499578);
   leadingJetEta_VV_jetSel_emu_stack_5->SetBinContent(11,1.319057);
   leadingJetEta_VV_jetSel_emu_stack_5->SetBinContent(12,1.575228);
   leadingJetEta_VV_jetSel_emu_stack_5->SetBinContent(13,0.7570146);
   leadingJetEta_VV_jetSel_emu_stack_5->SetBinContent(14,0.9544956);
   leadingJetEta_VV_jetSel_emu_stack_5->SetBinContent(15,0.4903458);
   leadingJetEta_VV_jetSel_emu_stack_5->SetBinContent(16,0.4566052);
   leadingJetEta_VV_jetSel_emu_stack_5->SetBinContent(17,0.0231375);
   leadingJetEta_VV_jetSel_emu_stack_5->SetBinContent(18,0.720822);
   leadingJetEta_VV_jetSel_emu_stack_5->SetBinContent(20,0.03002454);
   leadingJetEta_VV_jetSel_emu_stack_5->SetEntries(858);
   leadingJetEta_VV_jetSel_emu_stack_5->SetDirectory(0);

   ci = TColor::GetColor("#ff9933");
   leadingJetEta_VV_jetSel_emu_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#ff9933");
   leadingJetEta_VV_jetSel_emu_stack_5->SetLineColor(ci);
   leadingJetEta_VV_jetSel_emu_stack_5->SetLineWidth(0);
   leadingJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetLabelFont(42);
   leadingJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetLabelSize(0.035);
   leadingJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleSize(0.035);
   leadingJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleFont(42);
   leadingJetEta_VV_jetSel_emu_stack_5->GetYaxis()->SetLabelFont(42);
   leadingJetEta_VV_jetSel_emu_stack_5->GetYaxis()->SetLabelSize(0.035);
   leadingJetEta_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleSize(0.035);
   leadingJetEta_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleOffset(1);
   leadingJetEta_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleFont(42);
   leadingJetEta_VV_jetSel_emu_stack_5->GetZaxis()->SetLabelFont(42);
   leadingJetEta_VV_jetSel_emu_stack_5->GetZaxis()->SetLabelSize(0.035);
   leadingJetEta_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleSize(0.035);
   leadingJetEta_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_jetSel_emu->Add(leadingJetEta_VV_jetSel_emu_stack_5,"");
   
   TH1D *leadingJetEta_SingleTop_jetSel_emu_stack_6 = new TH1D("leadingJetEta_SingleTop_jetSel_emu_stack_6","leadingJetEta_SingleTop_jetSel_emu",25,0,5);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(0,151.1043);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(1,12.90444);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(2,16.19454);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(3,12.70794);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(4,14.0873);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(5,12.95797);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(6,9.232281);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(7,7.966675);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(8,10.1085);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(9,6.077796);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(10,6.419364);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(11,4.129163);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(12,5.248756);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(13,2.406099);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(14,4.471438);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(15,1.14998);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(16,0.8903888);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(17,0.5183101);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(18,0.745298);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(19,0.3918988);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(20,0.5045993);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(21,0.00239097);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(22,0.0007822226);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(23,0.0006550062);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetEntries(2806);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetDirectory(0);

   ci = TColor::GetColor("#ff00ff");
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetLineColor(ci);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->SetLineWidth(0);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetLabelFont(42);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetLabelSize(0.035);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleSize(0.035);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetLabelFont(42);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetLabelSize(0.035);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleSize(0.035);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleOffset(1);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetLabelFont(42);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetLabelSize(0.035);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleSize(0.035);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_jetSel_emu->Add(leadingJetEta_SingleTop_jetSel_emu_stack_6,"");
   
   TH1D *leadingJetEta_tt_jetSel_emu_stack_7 = new TH1D("leadingJetEta_tt_jetSel_emu_stack_7","leadingJetEta_tt_jetSel_emu",25,0,5);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(0,3102.295);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(1,338.1148);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(2,327.2876);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(3,304.5113);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(4,301.6348);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(5,284.2556);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(6,260.8818);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(7,213.8726);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(8,204.1742);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(9,182.6067);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(10,138.2013);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(11,141.0354);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(12,111.9186);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(13,83.47735);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(14,81.95396);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(15,42.71047);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(16,38.1445);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(17,30.6637);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(18,21.0357);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(19,15.04773);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(20,8.411824);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(21,2.515081);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(22,2.812256);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(23,0.6389875);
   leadingJetEta_tt_jetSel_emu_stack_7->SetBinContent(24,0.3168315);
   leadingJetEta_tt_jetSel_emu_stack_7->SetEntries(19867);
   leadingJetEta_tt_jetSel_emu_stack_7->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   leadingJetEta_tt_jetSel_emu_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   leadingJetEta_tt_jetSel_emu_stack_7->SetLineColor(ci);
   leadingJetEta_tt_jetSel_emu_stack_7->SetLineWidth(0);
   leadingJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetLabelFont(42);
   leadingJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetLabelSize(0.035);
   leadingJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleSize(0.035);
   leadingJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleFont(42);
   leadingJetEta_tt_jetSel_emu_stack_7->GetYaxis()->SetLabelFont(42);
   leadingJetEta_tt_jetSel_emu_stack_7->GetYaxis()->SetLabelSize(0.035);
   leadingJetEta_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleSize(0.035);
   leadingJetEta_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleOffset(1);
   leadingJetEta_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleFont(42);
   leadingJetEta_tt_jetSel_emu_stack_7->GetZaxis()->SetLabelFont(42);
   leadingJetEta_tt_jetSel_emu_stack_7->GetZaxis()->SetLabelSize(0.035);
   leadingJetEta_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleSize(0.035);
   leadingJetEta_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_jetSel_emu->Add(leadingJetEta_tt_jetSel_emu_stack_7,"");
   
   TH1D *leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8 = new TH1D("leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8","leadingJetEta_zPlusJetsMadgraph_jetSel_emu",25,0,5);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(0,11.88893);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(4,1.443027);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(6,1.483989);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(8,1.422358);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(9,1.431985);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetEntries(12);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetLineColor(ci);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetLineWidth(0);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetLabelFont(42);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetLabelSize(0.035);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleSize(0.035);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleFont(42);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetLabelFont(42);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetLabelSize(0.035);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleSize(0.035);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleOffset(1);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleFont(42);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetLabelFont(42);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetLabelSize(0.035);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleSize(0.035);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_jetSel_emu->Add(leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8,"");
   leadingJetEta_SingleTop_jetSel_emu->Draw("");
   
   TH1D *leadingJetEta_data_jetSel_emu__4 = new TH1D("leadingJetEta_data_jetSel_emu__4","leadingJetEta_data_jetSel_emu",25,0,5);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(0,3328);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(1,356);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(2,341);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(3,335);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(4,322);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(5,279);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(6,290);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(7,241);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(8,225);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(9,200);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(10,171);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(11,146);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(12,103);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(13,94);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(14,73);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(15,46);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(16,34);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(17,30);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(18,18);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(19,18);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(20,4);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(21,5);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(22,4);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(23,4);
   leadingJetEta_data_jetSel_emu__4->SetBinContent(24,1);
   leadingJetEta_data_jetSel_emu__4->SetEntries(6668);
   leadingJetEta_data_jetSel_emu__4->SetDirectory(0);
   leadingJetEta_data_jetSel_emu__4->SetFillColor(1);
   leadingJetEta_data_jetSel_emu__4->SetLineWidth(2);
   leadingJetEta_data_jetSel_emu__4->SetLineColor(1); // 
   leadingJetEta_data_jetSel_emu__4->SetMarkerStyle(20);
   leadingJetEta_data_jetSel_emu__4->SetMarkerSize(1.4);
   leadingJetEta_data_jetSel_emu__4->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_data_jetSel_emu__4->GetXaxis()->SetLabelFont(42);
   leadingJetEta_data_jetSel_emu__4->GetXaxis()->SetLabelSize(0.035);
   leadingJetEta_data_jetSel_emu__4->GetXaxis()->SetTitleSize(0.035);
   leadingJetEta_data_jetSel_emu__4->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_data_jetSel_emu__4->GetXaxis()->SetTitleFont(42);
   leadingJetEta_data_jetSel_emu__4->GetYaxis()->SetLabelFont(42);
   leadingJetEta_data_jetSel_emu__4->GetYaxis()->SetLabelSize(0.035);
   leadingJetEta_data_jetSel_emu__4->GetYaxis()->SetTitleSize(0.035);
   leadingJetEta_data_jetSel_emu__4->GetYaxis()->SetTitleOffset(1);
   leadingJetEta_data_jetSel_emu__4->GetYaxis()->SetTitleFont(42);
   leadingJetEta_data_jetSel_emu__4->GetZaxis()->SetLabelFont(42);
   leadingJetEta_data_jetSel_emu__4->GetZaxis()->SetLabelSize(0.035);
   leadingJetEta_data_jetSel_emu__4->GetZaxis()->SetTitleSize(0.035);
   leadingJetEta_data_jetSel_emu__4->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_data_jetSel_emu__4->GetZaxis()->SetTitleFont(42);
   leadingJetEta_data_jetSel_emu__4->Draw("e x0, same");
   
   TLegend *leg = new TLegend(0.78,0.42,0.98,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("leadingJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8","Z+jets (LO)","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetEta_tt_jetSel_emu_stack_7","t#bar{t}","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetEta_SingleTop_jetSel_emu_stack_6","Single top","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetEta_VV_jetSel_emu_stack_5","VV","f");

   ci = TColor::GetColor("#ff9933");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetEta_VVV_jetSel_emu_stack_4","VVV","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetEta_wJets_jetSel_emu_stack_3","W+jets","f");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetEta_ttV_jetSel_emu_stack_2","t#bar{t}V","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetEta_tZq_jetSel_emu_stack_1","tZq","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetEta_data_jetSel_emu","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.4);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.968,0.9429101,"35.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06792969);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.096,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.05419922);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16899,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.04119141);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *leadingJetEta_SingleTop_jetSel_emu__5 = new TH1F("leadingJetEta_SingleTop_jetSel_emu__5","Leading Jet #eta",25,0,5);
   leadingJetEta_SingleTop_jetSel_emu__5->SetMinimum(0);
   leadingJetEta_SingleTop_jetSel_emu__5->SetMaximum(412.3802);
   leadingJetEta_SingleTop_jetSel_emu__5->SetDirectory(0);
   leadingJetEta_SingleTop_jetSel_emu__5->SetStats(0);
   leadingJetEta_SingleTop_jetSel_emu__5->SetLineStyle(0);
   leadingJetEta_SingleTop_jetSel_emu__5->SetLineWidth(0);
   leadingJetEta_SingleTop_jetSel_emu__5->SetMarkerStyle(20);
   leadingJetEta_SingleTop_jetSel_emu__5->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_SingleTop_jetSel_emu__5->GetXaxis()->SetNdivisions(506);
   leadingJetEta_SingleTop_jetSel_emu__5->GetXaxis()->SetLabelFont(42);
   leadingJetEta_SingleTop_jetSel_emu__5->GetXaxis()->SetLabelOffset(999);
   leadingJetEta_SingleTop_jetSel_emu__5->GetXaxis()->SetLabelSize(0.05);
   leadingJetEta_SingleTop_jetSel_emu__5->GetXaxis()->SetTitleSize(0.08);
   leadingJetEta_SingleTop_jetSel_emu__5->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_SingleTop_jetSel_emu__5->GetXaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_jetSel_emu__5->GetYaxis()->SetTitle("Events");
   leadingJetEta_SingleTop_jetSel_emu__5->GetYaxis()->SetNdivisions(506);
   leadingJetEta_SingleTop_jetSel_emu__5->GetYaxis()->SetLabelFont(42);
   leadingJetEta_SingleTop_jetSel_emu__5->GetYaxis()->SetLabelOffset(0.01);
   leadingJetEta_SingleTop_jetSel_emu__5->GetYaxis()->SetLabelSize(0.062);
   leadingJetEta_SingleTop_jetSel_emu__5->GetYaxis()->SetTitleSize(0.08);
   leadingJetEta_SingleTop_jetSel_emu__5->GetYaxis()->SetTitleOffset(0.6336);
   leadingJetEta_SingleTop_jetSel_emu__5->GetYaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_jetSel_emu__5->GetZaxis()->SetLabelFont(42);
   leadingJetEta_SingleTop_jetSel_emu__5->GetZaxis()->SetLabelOffset(0.007);
   leadingJetEta_SingleTop_jetSel_emu__5->GetZaxis()->SetLabelSize(0.05);
   leadingJetEta_SingleTop_jetSel_emu__5->GetZaxis()->SetTitleSize(0.08);
   leadingJetEta_SingleTop_jetSel_emu__5->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_SingleTop_jetSel_emu__5->GetZaxis()->SetTitleFont(42);
   leadingJetEta_SingleTop_jetSel_emu__5->Draw("sameaxis");
   
/*   TPaveText *pt = new TPaveText(0.4261247,0.9371861,0.5738753,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Leading Jet #eta");
   pt->Draw();*/
   canvy_1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: canvy_2
   TPad *canvy_2 = new TPad("canvy_2", "newpad2",0.01,0.01,0.99,0.322);
   canvy_2->Draw();
   canvy_2->cd();
   canvy_2->SetFillColor(0);
   canvy_2->SetBorderMode(0);
   canvy_2->SetGridy();

   canvy_2->SetLeftMargin( L/W );
   canvy_2->SetRightMargin( R/W );
   canvy_2->SetTopMargin( T/H );
   canvy_2->SetBottomMargin( B/H * 2.6 );
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   
   TH1D *leadingJetEta_data_jetSel_emu__6 = new TH1D("leadingJetEta_data_jetSel_emu__6","",25,0,5);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(0,0.9971942);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(1,0.9970896);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(2,0.975159);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(3,1.038094);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(4,0.9939406);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(5,0.9172694);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(6,1.046638);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(7,1.064259);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(8,1.021994);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(9,0.9675638);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(10,1.158845);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(11,0.9900255);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(12,0.8599186);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(13,1.074739);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(14,0.8296828);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(15,1.030698);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(16,0.8561963);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(17,0.9536099);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(18,0.7984738);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(19,1.16356);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(20,0.4461786);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(21,1.978018);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(22,1.419555);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(23,6.192159);
   leadingJetEta_data_jetSel_emu__6->SetBinContent(24,3.157058);
   leadingJetEta_data_jetSel_emu__6->SetBinError(0,0.02442858);
   leadingJetEta_data_jetSel_emu__6->SetBinError(1,0.07468063);
   leadingJetEta_data_jetSel_emu__6->SetBinError(2,0.0742163);
   leadingJetEta_data_jetSel_emu__6->SetBinError(3,0.08097038);
   leadingJetEta_data_jetSel_emu__6->SetBinError(4,0.07821474);
   leadingJetEta_data_jetSel_emu__6->SetBinError(5,0.076039);
   leadingJetEta_data_jetSel_emu__6->SetBinError(6,0.0879261);
   leadingJetEta_data_jetSel_emu__6->SetBinError(7,0.09849652);
   leadingJetEta_data_jetSel_emu__6->SetBinError(8,0.09688284);
   leadingJetEta_data_jetSel_emu__6->SetBinError(9,0.09596857);
   leadingJetEta_data_jetSel_emu__6->SetBinError(10,0.130208);
   leadingJetEta_data_jetSel_emu__6->SetBinError(11,0.1155844);
   leadingJetEta_data_jetSel_emu__6->SetBinError(12,0.1155542);
   leadingJetEta_data_jetSel_emu__6->SetBinError(13,0.1596691);
   leadingJetEta_data_jetSel_emu__6->SetBinError(14,0.1313526);
   leadingJetEta_data_jetSel_emu__6->SetBinError(15,0.2165585);
   leadingJetEta_data_jetSel_emu__6->SetBinError(16,0.2000534);
   leadingJetEta_data_jetSel_emu__6->SetBinError(17,0.2433487);
   leadingJetEta_data_jetSel_emu__6->SetBinError(18,0.2523925);
   leadingJetEta_data_jetSel_emu__6->SetBinError(19,0.4034011);
   leadingJetEta_data_jetSel_emu__6->SetBinError(20,0.2682809);
   leadingJetEta_data_jetSel_emu__6->SetBinError(21,1.526542);
   leadingJetEta_data_jetSel_emu__6->SetBinError(22,1.104053);
   leadingJetEta_data_jetSel_emu__6->SetBinError(23,8.303129);
   leadingJetEta_data_jetSel_emu__6->SetBinError(24,6.436883);
   leadingJetEta_data_jetSel_emu__6->SetMinimum(0.5);
   leadingJetEta_data_jetSel_emu__6->SetMaximum(1.5);
   leadingJetEta_data_jetSel_emu__6->SetEntries(8.902902);
   leadingJetEta_data_jetSel_emu__6->SetDirectory(0);
   leadingJetEta_data_jetSel_emu__6->SetStats(0);
   leadingJetEta_data_jetSel_emu__6->SetFillColor(1);
   leadingJetEta_data_jetSel_emu__6->SetLineWidth(2);
   leadingJetEta_data_jetSel_emu__6->SetLineColor(1); //
   leadingJetEta_data_jetSel_emu__6->SetMarkerStyle(20);
   leadingJetEta_data_jetSel_emu__6->SetMarkerSize(1.6);
   leadingJetEta_data_jetSel_emu__6->GetXaxis()->SetTitle("Leading jet #eta");
   leadingJetEta_data_jetSel_emu__6->GetXaxis()->SetNdivisions(506);
   leadingJetEta_data_jetSel_emu__6->GetXaxis()->SetLabelFont(42);
   leadingJetEta_data_jetSel_emu__6->GetXaxis()->SetLabelOffset(0.013);
   leadingJetEta_data_jetSel_emu__6->GetXaxis()->SetLabelSize(0.13);
   leadingJetEta_data_jetSel_emu__6->GetXaxis()->SetTitleSize(0.13);
   leadingJetEta_data_jetSel_emu__6->GetXaxis()->SetTitleOffset(1);
   leadingJetEta_data_jetSel_emu__6->GetXaxis()->SetTitleFont(42);
   leadingJetEta_data_jetSel_emu__6->GetYaxis()->SetTitle("Data/MC");
   leadingJetEta_data_jetSel_emu__6->GetYaxis()->CenterTitle(true);
   leadingJetEta_data_jetSel_emu__6->GetYaxis()->SetNdivisions(506);
   leadingJetEta_data_jetSel_emu__6->GetYaxis()->SetLabelFont(42);
   leadingJetEta_data_jetSel_emu__6->GetYaxis()->SetLabelOffset(0.01);
   leadingJetEta_data_jetSel_emu__6->GetYaxis()->SetLabelSize(0.12);
   leadingJetEta_data_jetSel_emu__6->GetYaxis()->SetTitleSize(0.16);
   leadingJetEta_data_jetSel_emu__6->GetYaxis()->SetTitleOffset(0.3);
   leadingJetEta_data_jetSel_emu__6->GetYaxis()->SetTitleFont(42);
   leadingJetEta_data_jetSel_emu__6->GetZaxis()->SetLabelFont(42);
   leadingJetEta_data_jetSel_emu__6->GetZaxis()->SetLabelSize(0.035);
   leadingJetEta_data_jetSel_emu__6->GetZaxis()->SetTitleSize(0.035);
   leadingJetEta_data_jetSel_emu__6->GetZaxis()->SetTitleOffset(1);
   leadingJetEta_data_jetSel_emu__6->GetZaxis()->SetTitleFont(42);
   leadingJetEta_data_jetSel_emu__6->Draw("e x0, SCAT");
   canvy_2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
//   c1->SetSelected(leadingJetEta_data_jetSel_emu);
   c1->SaveAs("leadingJetEta_jetSel.pdf");
}
