void leadingJetPt_SingleTop_jetSel()
{
//=========Macro generated from canvas: leadingJetPt_SingleTop_jetSel/leadingJetPt_SingleTop_jetSel
//=========  (Wed Aug 21 19:33:01 2019) by ROOT version 6.18/00

   // Set up cavas
   int W = 1280;
   int H = 1024;
   int H_ref = 925;
   int W_ref = 1024;

   // references for T, B, L, R
   float T = 0.08*H_ref;
   float B = 0.12*H_ref;
   float L = 0.12*W_ref;
   float R = 0.04*W_ref;

   TCanvas *c1 = new TCanvas("c1","c1",50,50,W,H);
   c1->cd();
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetLeftMargin( L/W );
   c1->SetRightMargin( R/W );
   c1->SetTopMargin( T/H );
   c1->SetBottomMargin( B/H );
   c1->SetTickx(0);
   c1->SetTicky(0);
  
// ------------>Primitives in pad: canvy_1
   TPad *canvy_1 = new TPad("canvy_1", "newpad",0.01,0.315,0.99,0.99);
   canvy_1->Draw();
   canvy_1->cd();
   canvy_1->SetFillColor(0);
   canvy_1->SetBorderMode(0);

   canvy_1->SetLeftMargin( L/W );
   canvy_1->SetRightMargin( R/W );
   canvy_1->SetTopMargin( T/H );
   canvy_1->SetBottomMargin( B/H * 0.3 );

   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);
   
   THStack *leadingJetPt_SingleTop_jetSel_emu = new THStack();
   leadingJetPt_SingleTop_jetSel_emu->SetName("leadingJetPt_SingleTop_jetSel_emu");
   leadingJetPt_SingleTop_jetSel_emu->SetTitle("Leading Jet p_{T};Leading jet p_{T} (GeV);Events");
   leadingJetPt_SingleTop_jetSel_emu->SetMaximum(569.8);
   
   TH1F *leadingJetPt_SingleTop_jetSel_emu_stack_2 = new TH1F("leadingJetPt_SingleTop_jetSel_emu_stack_2","Leading Jet p_{T}",35,0,300);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->SetMinimum(0);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->SetMaximum(598.29);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->SetDirectory(0);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->SetStats(0);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->SetLineStyle(0);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->SetLineWidth(0);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->SetMarkerStyle(20);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_SingleTop_jetSel_emu_stack_2->GetXaxis()->SetNdivisions(506);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->GetXaxis()->SetLabelFont(42);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->GetXaxis()->SetLabelOffset(999);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->GetXaxis()->SetLabelSize(0.05);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->GetXaxis()->SetTitleSize(0.08);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->GetXaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->GetYaxis()->SetTitle("Events");
   leadingJetPt_SingleTop_jetSel_emu_stack_2->GetYaxis()->SetNdivisions(506);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->GetYaxis()->SetLabelFont(42);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->GetYaxis()->SetLabelOffset(0.01);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->GetYaxis()->SetLabelSize(0.062);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->GetYaxis()->SetTitleSize(0.08);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->GetYaxis()->SetTitleOffset(0.6336);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->GetYaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->GetZaxis()->SetLabelFont(42);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->GetZaxis()->SetLabelOffset(0.007);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->GetZaxis()->SetLabelSize(0.05);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->GetZaxis()->SetTitleSize(0.08);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_SingleTop_jetSel_emu_stack_2->GetZaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_jetSel_emu->SetHistogram(leadingJetPt_SingleTop_jetSel_emu_stack_2);
   
   
   TH1D *leadingJetPt_tZq_jetSel_emu_stack_1 = new TH1D("leadingJetPt_tZq_jetSel_emu_stack_1","leadingJetPt_tZq_jetSel_emu",35,0,300);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(5,0.001884837);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(6,0.01157112);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(7,0.02776512);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(8,0.04289458);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(9,0.06871494);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(10,0.07215708);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(11,0.0759396);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(12,0.06891862);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(13,0.07304019);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(14,0.05892302);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(15,0.05999363);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(16,0.0711606);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(17,0.0469239);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(18,0.03165982);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(19,0.0407219);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(20,0.03132458);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(21,0.03279485);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(22,0.03493342);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(23,0.02966022);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(24,0.03459931);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(25,0.02634749);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(26,0.001030503);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(27,0.02695224);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(28,0.01079666);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(29,0.009215375);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(30,0.008331137);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(31,0.01626124);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(32,0.003573527);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(33,0.008574057);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(34,0.005525681);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(35,0.01502862);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetBinContent(36,0.05827475);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetEntries(6672);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ffff00");
   leadingJetPt_tZq_jetSel_emu_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   leadingJetPt_tZq_jetSel_emu_stack_1->SetLineColor(ci);
   leadingJetPt_tZq_jetSel_emu_stack_1->SetLineWidth(0);
   leadingJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetLabelFont(42);
   leadingJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetLabelSize(0.035);
   leadingJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleSize(0.035);
   leadingJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleFont(42);
   leadingJetPt_tZq_jetSel_emu_stack_1->GetYaxis()->SetLabelFont(42);
   leadingJetPt_tZq_jetSel_emu_stack_1->GetYaxis()->SetLabelSize(0.035);
   leadingJetPt_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleSize(0.035);
   leadingJetPt_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleOffset(1);
   leadingJetPt_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleFont(42);
   leadingJetPt_tZq_jetSel_emu_stack_1->GetZaxis()->SetLabelFont(42);
   leadingJetPt_tZq_jetSel_emu_stack_1->GetZaxis()->SetLabelSize(0.035);
   leadingJetPt_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleSize(0.035);
   leadingJetPt_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_jetSel_emu->Add(leadingJetPt_tZq_jetSel_emu_stack_1,"");
   
   TH1D *leadingJetPt_ttV_jetSel_emu_stack_2 = new TH1D("leadingJetPt_ttV_jetSel_emu_stack_2","leadingJetPt_ttV_jetSel_emu",35,0,300);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(4,0.000827336);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(5,0.09004421);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(6,0.5203725);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(7,1.399451);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(8,1.904592);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(9,2.261208);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(10,3.972655);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(11,3.422982);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(12,3.709706);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(13,3.156512);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(14,3.923078);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(15,3.582251);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(16,2.950213);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(17,2.202515);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(18,2.218181);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(19,2.87638);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(20,1.214723);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(21,2.016309);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(22,1.227185);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(23,1.377173);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(24,1.351583);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(25,0.570597);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(26,0.90374);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(27,0.9952461);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(28,1.023934);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(29,0.4942705);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(30,0.4825355);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(31,0.6971453);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(32,0.2764261);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(33,0.7089191);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(34,0.51098);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(35,0.3527943);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetBinContent(36,4.128912);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetEntries(29408);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#00ff00");
   leadingJetPt_ttV_jetSel_emu_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   leadingJetPt_ttV_jetSel_emu_stack_2->SetLineColor(ci);
   leadingJetPt_ttV_jetSel_emu_stack_2->SetLineWidth(0);
   leadingJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetLabelFont(42);
   leadingJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetLabelSize(0.035);
   leadingJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleSize(0.035);
   leadingJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleFont(42);
   leadingJetPt_ttV_jetSel_emu_stack_2->GetYaxis()->SetLabelFont(42);
   leadingJetPt_ttV_jetSel_emu_stack_2->GetYaxis()->SetLabelSize(0.035);
   leadingJetPt_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleSize(0.035);
   leadingJetPt_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleOffset(1);
   leadingJetPt_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleFont(42);
   leadingJetPt_ttV_jetSel_emu_stack_2->GetZaxis()->SetLabelFont(42);
   leadingJetPt_ttV_jetSel_emu_stack_2->GetZaxis()->SetLabelSize(0.035);
   leadingJetPt_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleSize(0.035);
   leadingJetPt_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_jetSel_emu->Add(leadingJetPt_ttV_jetSel_emu_stack_2,"");
   
   TH1D *leadingJetPt_wJets_jetSel_emu_stack_3 = new TH1D("leadingJetPt_wJets_jetSel_emu_stack_3","leadingJetPt_wJets_jetSel_emu",35,0,300);
   leadingJetPt_wJets_jetSel_emu_stack_3->SetBinContent(14,12.53387);
   leadingJetPt_wJets_jetSel_emu_stack_3->SetBinContent(36,13.42844);
   leadingJetPt_wJets_jetSel_emu_stack_3->SetEntries(2);
   leadingJetPt_wJets_jetSel_emu_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   leadingJetPt_wJets_jetSel_emu_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#cccccc");
   leadingJetPt_wJets_jetSel_emu_stack_3->SetLineColor(ci);
   leadingJetPt_wJets_jetSel_emu_stack_3->SetLineWidth(0);
   leadingJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetLabelFont(42);
   leadingJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetLabelSize(0.035);
   leadingJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleSize(0.035);
   leadingJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleFont(42);
   leadingJetPt_wJets_jetSel_emu_stack_3->GetYaxis()->SetLabelFont(42);
   leadingJetPt_wJets_jetSel_emu_stack_3->GetYaxis()->SetLabelSize(0.035);
   leadingJetPt_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleSize(0.035);
   leadingJetPt_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleOffset(1);
   leadingJetPt_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleFont(42);
   leadingJetPt_wJets_jetSel_emu_stack_3->GetZaxis()->SetLabelFont(42);
   leadingJetPt_wJets_jetSel_emu_stack_3->GetZaxis()->SetLabelSize(0.035);
   leadingJetPt_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleSize(0.035);
   leadingJetPt_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_jetSel_emu->Add(leadingJetPt_wJets_jetSel_emu_stack_3,"");
   
   TH1D *leadingJetPt_VVV_jetSel_emu_stack_4 = new TH1D("leadingJetPt_VVV_jetSel_emu_stack_4","leadingJetPt_VVV_jetSel_emu",35,0,300);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(6,0.1912633);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(7,0.119933);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(8,0.1573992);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(9,0.03538246);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(10,0.08544567);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(11,0.1635738);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(12,0.1905303);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(13,0.1071215);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(14,0.1301732);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(15,0.1424338);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(16,0.1576707);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(17,0.07713699);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(18,0.07342122);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(19,0.2086339);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(20,0.149969);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(21,0.1396834);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(23,0.1682383);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(24,0.138469);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(25,0.05323476);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(26,0.03619156);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(27,0.04822325);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(28,0.02622561);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(29,0.1430566);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(30,0.05509424);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(31,0.02710347);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(32,0.1010143);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(35,0.03802254);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetBinContent(36,0.7197068);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetEntries(147);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#00ffff");
   leadingJetPt_VVV_jetSel_emu_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   leadingJetPt_VVV_jetSel_emu_stack_4->SetLineColor(ci);
   leadingJetPt_VVV_jetSel_emu_stack_4->SetLineWidth(0);
   leadingJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetLabelFont(42);
   leadingJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetLabelSize(0.035);
   leadingJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleSize(0.035);
   leadingJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleFont(42);
   leadingJetPt_VVV_jetSel_emu_stack_4->GetYaxis()->SetLabelFont(42);
   leadingJetPt_VVV_jetSel_emu_stack_4->GetYaxis()->SetLabelSize(0.035);
   leadingJetPt_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleSize(0.035);
   leadingJetPt_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleOffset(1);
   leadingJetPt_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleFont(42);
   leadingJetPt_VVV_jetSel_emu_stack_4->GetZaxis()->SetLabelFont(42);
   leadingJetPt_VVV_jetSel_emu_stack_4->GetZaxis()->SetLabelSize(0.035);
   leadingJetPt_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleSize(0.035);
   leadingJetPt_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_jetSel_emu->Add(leadingJetPt_VVV_jetSel_emu_stack_4,"");
   
   TH1D *leadingJetPt_VV_jetSel_emu_stack_5 = new TH1D("leadingJetPt_VV_jetSel_emu_stack_5","leadingJetPt_VV_jetSel_emu",35,0,300);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(4,0.2363947);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(5,0.8337571);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(6,2.074591);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(7,2.81505);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(8,1.465411);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(9,3.69256);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(10,3.619384);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(11,1.485798);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(12,2.345859);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(13,1.552654);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(14,2.016703);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(15,3.095052);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(16,2.08275);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(17,1.037394);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(18,1.759815);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(19,2.321363);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(20,2.366118);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(21,2.205524);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(22,1.270704);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(23,1.646424);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(24,1.268458);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(25,2.241043);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(26,0.5967516);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(27,1.461437);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(28,0.4757168);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(29,0.8451429);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(30,1.182875);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(31,1.472739);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(32,1.112451);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(33,-0.004845148);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(34,0.4897381);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(35,0.6819616);
   leadingJetPt_VV_jetSel_emu_stack_5->SetBinContent(36,9.22571);
   leadingJetPt_VV_jetSel_emu_stack_5->SetEntries(858);
   leadingJetPt_VV_jetSel_emu_stack_5->SetDirectory(0);

   ci = TColor::GetColor("#ff9933");
   leadingJetPt_VV_jetSel_emu_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#ff9933");
   leadingJetPt_VV_jetSel_emu_stack_5->SetLineColor(ci);
   leadingJetPt_VV_jetSel_emu_stack_5->SetLineWidth(0);
   leadingJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetLabelFont(42);
   leadingJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetLabelSize(0.035);
   leadingJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleSize(0.035);
   leadingJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleFont(42);
   leadingJetPt_VV_jetSel_emu_stack_5->GetYaxis()->SetLabelFont(42);
   leadingJetPt_VV_jetSel_emu_stack_5->GetYaxis()->SetLabelSize(0.035);
   leadingJetPt_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleSize(0.035);
   leadingJetPt_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleOffset(1);
   leadingJetPt_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleFont(42);
   leadingJetPt_VV_jetSel_emu_stack_5->GetZaxis()->SetLabelFont(42);
   leadingJetPt_VV_jetSel_emu_stack_5->GetZaxis()->SetLabelSize(0.035);
   leadingJetPt_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleSize(0.035);
   leadingJetPt_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_jetSel_emu->Add(leadingJetPt_VV_jetSel_emu_stack_5,"");
   
   TH1D *leadingJetPt_SingleTop_jetSel_emu_stack_6 = new TH1D("leadingJetPt_SingleTop_jetSel_emu_stack_6","leadingJetPt_SingleTop_jetSel_emu",35,0,300);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(4,0.1960117);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(5,2.368426);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(6,8.228873);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(7,15.60269);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(8,17.83521);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(9,21.32741);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(10,18.15744);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(11,18.65991);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(12,18.31371);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(13,16.83961);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(14,15.57223);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(15,10.64182);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(16,10.02599);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(17,8.639564);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(18,9.594997);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(19,9.412442);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(20,6.3273);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(21,7.222149);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(22,4.85554);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(23,3.533953);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(24,5.768955);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(25,4.065472);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(26,5.479095);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(27,3.358015);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(28,3.045396);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(29,2.019689);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(30,2.555509);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(31,1.989624);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(32,2.395806);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(33,0.883392);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(34,1.425059);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(35,2.066464);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(36,21.81315);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetEntries(2806);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetDirectory(0);

   ci = TColor::GetColor("#ff00ff");
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetLineColor(ci);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->SetLineWidth(0);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetLabelFont(42);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetLabelSize(0.035);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleSize(0.035);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetLabelFont(42);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetLabelSize(0.035);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleSize(0.035);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleOffset(1);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetLabelFont(42);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetLabelSize(0.035);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleSize(0.035);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_jetSel_emu->Add(leadingJetPt_SingleTop_jetSel_emu_stack_6,"");
   
   TH1D *leadingJetPt_tt_jetSel_emu_stack_7 = new TH1D("leadingJetPt_tt_jetSel_emu_stack_7","leadingJetPt_tt_jetSel_emu",35,0,300);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(4,0.7226796);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(5,37.85495);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(6,124.8466);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(7,247.2983);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(8,350.1453);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(9,425.9645);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(10,464.5221);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(11,485.6455);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(12,443.0619);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(13,416.4445);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(14,405.6284);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(15,334.662);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(16,285.8694);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(17,263.5691);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(18,231.2988);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(19,205.6266);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(20,170.1217);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(21,156.5803);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(22,125.8187);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(23,119.6832);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(24,99.85214);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(25,90.0367);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(26,68.82369);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(27,65.76052);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(28,63.79664);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(29,47.58094);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(30,55.25651);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(31,34.81535);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(32,43.51727);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(33,34.50942);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(34,32.77591);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(35,24.55818);
   leadingJetPt_tt_jetSel_emu_stack_7->SetBinContent(36,281.8701);
   leadingJetPt_tt_jetSel_emu_stack_7->SetEntries(19867);
   leadingJetPt_tt_jetSel_emu_stack_7->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   leadingJetPt_tt_jetSel_emu_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   leadingJetPt_tt_jetSel_emu_stack_7->SetLineColor(ci);
   leadingJetPt_tt_jetSel_emu_stack_7->SetLineWidth(0);
   leadingJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetLabelFont(42);
   leadingJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetLabelSize(0.035);
   leadingJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleSize(0.035);
   leadingJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleFont(42);
   leadingJetPt_tt_jetSel_emu_stack_7->GetYaxis()->SetLabelFont(42);
   leadingJetPt_tt_jetSel_emu_stack_7->GetYaxis()->SetLabelSize(0.035);
   leadingJetPt_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleSize(0.035);
   leadingJetPt_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleOffset(1);
   leadingJetPt_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleFont(42);
   leadingJetPt_tt_jetSel_emu_stack_7->GetZaxis()->SetLabelFont(42);
   leadingJetPt_tt_jetSel_emu_stack_7->GetZaxis()->SetLabelSize(0.035);
   leadingJetPt_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleSize(0.035);
   leadingJetPt_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_jetSel_emu->Add(leadingJetPt_tt_jetSel_emu_stack_7,"");
   
   TH1D *leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8 = new TH1D("leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8","leadingJetPt_zPlusJetsMadgraph_jetSel_emu",35,0,300);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(6,1.438892);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(8,1.589814);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(11,7.294888);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(12,1.483989);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(13,1.500213);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(20,2.861537);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(31,1.500954);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetEntries(12);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetLineColor(ci);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetLineWidth(0);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetLabelFont(42);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetLabelSize(0.035);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleSize(0.035);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleFont(42);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetLabelFont(42);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetLabelSize(0.035);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleSize(0.035);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleOffset(1);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleFont(42);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetLabelFont(42);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetLabelSize(0.035);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleSize(0.035);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_jetSel_emu->Add(leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8,"");
   leadingJetPt_SingleTop_jetSel_emu->Draw("");
   
   TH1D *leadingJetPt_data_jetSel_emu__4 = new TH1D("leadingJetPt_data_jetSel_emu__4","leadingJetPt_data_jetSel_emu",35,0,300);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(4,2);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(5,43);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(6,155);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(7,283);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(8,414);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(9,483);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(10,483);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(11,518);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(12,470);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(13,494);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(14,373);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(15,354);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(16,321);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(17,269);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(18,240);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(19,215);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(20,189);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(21,135);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(22,135);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(23,135);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(24,106);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(25,91);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(26,71);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(27,75);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(28,65);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(29,60);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(30,53);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(31,40);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(32,39);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(33,41);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(34,26);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(35,37);
   leadingJetPt_data_jetSel_emu__4->SetBinContent(36,253);
   leadingJetPt_data_jetSel_emu__4->SetEntries(6668);
   leadingJetPt_data_jetSel_emu__4->SetDirectory(0);
   leadingJetPt_data_jetSel_emu__4->SetFillColor(1);
   leadingJetPt_data_jetSel_emu__4->SetLineWidth(2);
   leadingJetPt_data_jetSel_emu__4->SetLineColor(1); //
   leadingJetPt_data_jetSel_emu__4->SetMarkerStyle(20);
   leadingJetPt_data_jetSel_emu__4->SetMarkerSize(1.4);
   leadingJetPt_data_jetSel_emu__4->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_data_jetSel_emu__4->GetXaxis()->SetLabelFont(42);
   leadingJetPt_data_jetSel_emu__4->GetXaxis()->SetLabelSize(0.035);
   leadingJetPt_data_jetSel_emu__4->GetXaxis()->SetTitleSize(0.035);
   leadingJetPt_data_jetSel_emu__4->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_data_jetSel_emu__4->GetXaxis()->SetTitleFont(42);
   leadingJetPt_data_jetSel_emu__4->GetYaxis()->SetLabelFont(42);
   leadingJetPt_data_jetSel_emu__4->GetYaxis()->SetLabelSize(0.035);
   leadingJetPt_data_jetSel_emu__4->GetYaxis()->SetTitleSize(0.035);
   leadingJetPt_data_jetSel_emu__4->GetYaxis()->SetTitleOffset(1);
   leadingJetPt_data_jetSel_emu__4->GetYaxis()->SetTitleFont(42);
   leadingJetPt_data_jetSel_emu__4->GetZaxis()->SetLabelFont(42);
   leadingJetPt_data_jetSel_emu__4->GetZaxis()->SetLabelSize(0.035);
   leadingJetPt_data_jetSel_emu__4->GetZaxis()->SetTitleSize(0.035);
   leadingJetPt_data_jetSel_emu__4->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_data_jetSel_emu__4->GetZaxis()->SetTitleFont(42);
   leadingJetPt_data_jetSel_emu__4->Draw("e x0, same");
   
   TLegend *leg = new TLegend(0.78,0.42,0.98,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("leadingJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8","Z+jets (LO)","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetPt_tt_jetSel_emu_stack_7","t#bar{t}","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetPt_SingleTop_jetSel_emu_stack_6","Single top","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetPt_VV_jetSel_emu_stack_5","VV","f");

   ci = TColor::GetColor("#ff9933");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetPt_VVV_jetSel_emu_stack_4","VVV","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetPt_wJets_jetSel_emu_stack_3","W+jets","f");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetPt_ttV_jetSel_emu_stack_2","t#bar{t}V","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetPt_tZq_jetSel_emu_stack_1","tZq","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetPt_data_jetSel_emu","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.4);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.968,0.9429101,"35.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06792969);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.096,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.05419922);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16899,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.04119141);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *leadingJetPt_SingleTop_jetSel_emu__5 = new TH1F("leadingJetPt_SingleTop_jetSel_emu__5","Leading Jet p_{T}",35,0,300);
   leadingJetPt_SingleTop_jetSel_emu__5->SetMinimum(0);
   leadingJetPt_SingleTop_jetSel_emu__5->SetMaximum(598.29);
   leadingJetPt_SingleTop_jetSel_emu__5->SetDirectory(0);
   leadingJetPt_SingleTop_jetSel_emu__5->SetStats(0);
   leadingJetPt_SingleTop_jetSel_emu__5->SetLineStyle(0);
   leadingJetPt_SingleTop_jetSel_emu__5->SetLineWidth(0);
   leadingJetPt_SingleTop_jetSel_emu__5->SetMarkerStyle(20);
   leadingJetPt_SingleTop_jetSel_emu__5->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_SingleTop_jetSel_emu__5->GetXaxis()->SetNdivisions(506);
   leadingJetPt_SingleTop_jetSel_emu__5->GetXaxis()->SetLabelFont(42);
   leadingJetPt_SingleTop_jetSel_emu__5->GetXaxis()->SetLabelOffset(999);
   leadingJetPt_SingleTop_jetSel_emu__5->GetXaxis()->SetLabelSize(0.05);
   leadingJetPt_SingleTop_jetSel_emu__5->GetXaxis()->SetTitleSize(0.08);
   leadingJetPt_SingleTop_jetSel_emu__5->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_SingleTop_jetSel_emu__5->GetXaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_jetSel_emu__5->GetYaxis()->SetTitle("Events");
   leadingJetPt_SingleTop_jetSel_emu__5->GetYaxis()->SetNdivisions(506);
   leadingJetPt_SingleTop_jetSel_emu__5->GetYaxis()->SetLabelFont(42);
   leadingJetPt_SingleTop_jetSel_emu__5->GetYaxis()->SetLabelOffset(0.01);
   leadingJetPt_SingleTop_jetSel_emu__5->GetYaxis()->SetLabelSize(0.062);
   leadingJetPt_SingleTop_jetSel_emu__5->GetYaxis()->SetTitleSize(0.08);
   leadingJetPt_SingleTop_jetSel_emu__5->GetYaxis()->SetTitleOffset(0.6336);
   leadingJetPt_SingleTop_jetSel_emu__5->GetYaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_jetSel_emu__5->GetZaxis()->SetLabelFont(42);
   leadingJetPt_SingleTop_jetSel_emu__5->GetZaxis()->SetLabelOffset(0.007);
   leadingJetPt_SingleTop_jetSel_emu__5->GetZaxis()->SetLabelSize(0.05);
   leadingJetPt_SingleTop_jetSel_emu__5->GetZaxis()->SetTitleSize(0.08);
   leadingJetPt_SingleTop_jetSel_emu__5->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_SingleTop_jetSel_emu__5->GetZaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_jetSel_emu__5->Draw("sameaxis");
   
   TPaveText *pt = new TPaveText(0.4217333,0.9203237,0.5782667,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Leading Jet p_{T}");
   pt->Draw();
   canvy_1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: canvy_2
   TPad *canvy_2 = new TPad("canvy_2", "newpad2",0.01,0.01,0.99,0.322);
   canvy_2->Draw();
   canvy_2->cd();
   canvy_2->SetFillColor(0);
   canvy_2->SetBorderMode(0);
   canvy_2->SetGridy();

   canvy_2->SetLeftMargin( L/W );
   canvy_2->SetRightMargin( R/W );
   canvy_2->SetTopMargin( T/H );
   canvy_2->SetBottomMargin( B/H * 2.6 );
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   
   TH1D *leadingJetPt_data_jetSel_emu__6 = new TH1D("leadingJetPt_data_jetSel_emu__6","",35,0,300);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(4,1.730234);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(5,1.044981);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(6,1.128815);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(7,1.058881);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(8,1.109501);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(9,1.065402);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(10,0.9848517);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(11,1.002422);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(12,1.001759);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(13,1.123561);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(14,0.8479907);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(15,1.005158);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(16,1.065889);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(17,0.976149);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(18,0.9796843);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(19,0.975118);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(20,1.032377);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(21,0.8026312);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(22,1.01346);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(23,1.067712);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(24,0.9777317);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(25,0.9382082);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(26,0.9361753);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(27,1.046749);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(28,0.9505883);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(29,1.174345);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(30,0.8901451);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(31,0.9871868);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(32,0.8226712);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(33,1.135562);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(34,0.7384851);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(35,1.33514);
   leadingJetPt_data_jetSel_emu__6->SetBinContent(36,0.7637867);
   leadingJetPt_data_jetSel_emu__6->SetBinError(4,2.021574);
   leadingJetPt_data_jetSel_emu__6->SetBinError(5,0.2278867);
   leadingJetPt_data_jetSel_emu__6->SetBinError(6,0.1322896);
   leadingJetPt_data_jetSel_emu__6->SetBinError(7,0.09031703);
   leadingJetPt_data_jetSel_emu__6->SetBinError(8,0.0791986);
   leadingJetPt_data_jetSel_emu__6->SetBinError(9,0.06966946);
   leadingJetPt_data_jetSel_emu__6->SetBinError(10,0.06313371);
   leadingJetPt_data_jetSel_emu__6->SetBinError(11,0.06232515);
   leadingJetPt_data_jetSel_emu__6->SetBinError(12,0.0653763);
   leadingJetPt_data_jetSel_emu__6->SetBinError(13,0.0736657);
   leadingJetPt_data_jetSel_emu__6->SetBinError(14,0.05968793);
   leadingJetPt_data_jetSel_emu__6->SetBinError(15,0.07564963);
   leadingJetPt_data_jetSel_emu__6->SetBinError(16,0.08550918);
   leadingJetPt_data_jetSel_emu__6->SetBinError(17,0.08366616);
   leadingJetPt_data_jetSel_emu__6->SetBinError(18,0.08897715);
   leadingJetPt_data_jetSel_emu__6->SetBinError(19,0.09346187);
   leadingJetPt_data_jetSel_emu__6->SetBinError(20,0.1070556);
   leadingJetPt_data_jetSel_emu__6->SetBinError(21,0.09274759);
   leadingJetPt_data_jetSel_emu__6->SetBinError(22,0.1237688);
   leadingJetPt_data_jetSel_emu__6->SetBinError(23,0.1321394);
   leadingJetPt_data_jetSel_emu__6->SetBinError(24,0.133552);
   leadingJetPt_data_jetSel_emu__6->SetBinError(25,0.1369237);
   leadingJetPt_data_jetSel_emu__6->SetBinError(26,0.1545967);
   leadingJetPt_data_jetSel_emu__6->SetBinError(27,0.1729197);
   leadingJetPt_data_jetSel_emu__6->SetBinError(28,0.1646716);
   leadingJetPt_data_jetSel_emu__6->SetBinError(29,0.2235549);
   leadingJetPt_data_jetSel_emu__6->SetBinError(30,0.168101);
   leadingJetPt_data_jetSel_emu__6->SetBinError(31,0.2200334);
   leadingJetPt_data_jetSel_emu__6->SetBinError(32,0.1778477);
   leadingJetPt_data_jetSel_emu__6->SetBinError(33,0.2591643);
   leadingJetPt_data_jetSel_emu__6->SetBinError(34,0.1909592);
   leadingJetPt_data_jetSel_emu__6->SetBinError(35,0.3354149);
   leadingJetPt_data_jetSel_emu__6->SetBinError(36,0.06377271);
   leadingJetPt_data_jetSel_emu__6->SetMinimum(0.9);
   leadingJetPt_data_jetSel_emu__6->SetMaximum(1.1);
   leadingJetPt_data_jetSel_emu__6->SetEntries(227.2207);
   leadingJetPt_data_jetSel_emu__6->SetDirectory(0);
   leadingJetPt_data_jetSel_emu__6->SetStats(0);
   leadingJetPt_data_jetSel_emu__6->SetFillColor(1);
   leadingJetPt_data_jetSel_emu__6->SetLineWidth(2);
   leadingJetPt_data_jetSel_emu__6->SetLineColor(1); //
   leadingJetPt_data_jetSel_emu__6->SetMarkerStyle(20);
   leadingJetPt_data_jetSel_emu__6->SetMarkerSize(1.6);
   leadingJetPt_data_jetSel_emu__6->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_data_jetSel_emu__6->GetXaxis()->SetNdivisions(506);
   leadingJetPt_data_jetSel_emu__6->GetXaxis()->SetLabelFont(42);
   leadingJetPt_data_jetSel_emu__6->GetXaxis()->SetLabelOffset(0.013);
   leadingJetPt_data_jetSel_emu__6->GetXaxis()->SetLabelSize(0.13);
   leadingJetPt_data_jetSel_emu__6->GetXaxis()->SetTitleSize(0.13);
   leadingJetPt_data_jetSel_emu__6->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_data_jetSel_emu__6->GetXaxis()->SetTitleFont(42);
   leadingJetPt_data_jetSel_emu__6->GetYaxis()->SetTitle("Data/MC");
   leadingJetPt_data_jetSel_emu__6->GetYaxis()->CenterTitle(true);
   leadingJetPt_data_jetSel_emu__6->GetYaxis()->SetNdivisions(506);
   leadingJetPt_data_jetSel_emu__6->GetYaxis()->SetLabelFont(42);
   leadingJetPt_data_jetSel_emu__6->GetYaxis()->SetLabelOffset(0.01);
   leadingJetPt_data_jetSel_emu__6->GetYaxis()->SetLabelSize(0.12);
   leadingJetPt_data_jetSel_emu__6->GetYaxis()->SetTitleSize(0.16);
   leadingJetPt_data_jetSel_emu__6->GetYaxis()->SetTitleOffset(0.3);
   leadingJetPt_data_jetSel_emu__6->GetYaxis()->SetTitleFont(42);
   leadingJetPt_data_jetSel_emu__6->GetZaxis()->SetLabelFont(42);
   leadingJetPt_data_jetSel_emu__6->GetZaxis()->SetLabelSize(0.035);
   leadingJetPt_data_jetSel_emu__6->GetZaxis()->SetTitleSize(0.035);
   leadingJetPt_data_jetSel_emu__6->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_data_jetSel_emu__6->GetZaxis()->SetTitleFont(42);
   leadingJetPt_data_jetSel_emu__6->Draw("e x0, SCAT");
   canvy_2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
//   c1->SetSelected(leadingJetPt_data_jetSel_emu);
   c1->SaveAs("leadingJetPt_jetSel.pdf");
}
