void leadingJetPt_SingleTop_wMass()
{
//=========Macro generated from canvas: leadingJetPt_SingleTop_wMass/leadingJetPt_SingleTop_wMass
//=========  (Wed Aug 21 19:38:41 2019) by ROOT version 6.18/00
   // Set up cavas
   int W = 1280;
   int H = 1024;
   int H_ref = 925;
   int W_ref = 1024;

   // references for T, B, L, R
   float T = 0.08*H_ref;
   float B = 0.12*H_ref;
   float L = 0.12*W_ref;
   float R = 0.04*W_ref;

   TCanvas *c1 = new TCanvas("c1","c1",50,50,W,H);
   c1->cd();
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetLeftMargin( L/W );
   c1->SetRightMargin( R/W );
   c1->SetTopMargin( T/H );
   c1->SetBottomMargin( B/H );
   c1->SetTickx(0);
   c1->SetTicky(0);
  
// ------------>Primitives in pad: canvy_1
   TPad *canvy_1 = new TPad("canvy_1", "newpad",0.01,0.315,0.99,0.99);
   canvy_1->Draw();
   canvy_1->cd();
   canvy_1->SetFillColor(0);
   canvy_1->SetBorderMode(0);

   canvy_1->SetLeftMargin( L/W );
   canvy_1->SetRightMargin( R/W );
   canvy_1->SetTopMargin( T/H );
   canvy_1->SetBottomMargin( B/H * 0.3 );

   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);
   
   THStack *leadingJetPt_SingleTop_wMass_emu = new THStack();
   leadingJetPt_SingleTop_wMass_emu->SetName("leadingJetPt_SingleTop_wMass_emu");
   leadingJetPt_SingleTop_wMass_emu->SetTitle("Leading Jet p_{T};Leading jet p_{T} (GeV);Events");
   leadingJetPt_SingleTop_wMass_emu->SetMaximum(257.4);
   
   TH1F *leadingJetPt_SingleTop_wMass_emu_stack_2 = new TH1F("leadingJetPt_SingleTop_wMass_emu_stack_2","Leading Jet p_{T}",35,0,300);
   leadingJetPt_SingleTop_wMass_emu_stack_2->SetMinimum(0);
   leadingJetPt_SingleTop_wMass_emu_stack_2->SetMaximum(270.27);
   leadingJetPt_SingleTop_wMass_emu_stack_2->SetDirectory(0);
   leadingJetPt_SingleTop_wMass_emu_stack_2->SetStats(0);
   leadingJetPt_SingleTop_wMass_emu_stack_2->SetLineStyle(0);
   leadingJetPt_SingleTop_wMass_emu_stack_2->SetLineWidth(0);
   leadingJetPt_SingleTop_wMass_emu_stack_2->SetMarkerStyle(20);
   leadingJetPt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetNdivisions(506);
   leadingJetPt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetLabelFont(42);
   leadingJetPt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetLabelOffset(999);
   leadingJetPt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetLabelSize(0.05);
   leadingJetPt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetTitleSize(0.08);
   leadingJetPt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetTitle("Events");
   leadingJetPt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetNdivisions(506);
   leadingJetPt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetLabelFont(42);
   leadingJetPt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetLabelOffset(0.01);
   leadingJetPt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetLabelSize(0.062);
   leadingJetPt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetTitleSize(0.08);
   leadingJetPt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetTitleOffset(0.6336);
   leadingJetPt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_wMass_emu_stack_2->GetZaxis()->SetLabelFont(42);
   leadingJetPt_SingleTop_wMass_emu_stack_2->GetZaxis()->SetLabelOffset(0.007);
   leadingJetPt_SingleTop_wMass_emu_stack_2->GetZaxis()->SetLabelSize(0.05);
   leadingJetPt_SingleTop_wMass_emu_stack_2->GetZaxis()->SetTitleSize(0.08);
   leadingJetPt_SingleTop_wMass_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_SingleTop_wMass_emu_stack_2->GetZaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_wMass_emu->SetHistogram(leadingJetPt_SingleTop_wMass_emu_stack_2);
   
   
   TH1D *leadingJetPt_tZq_wMass_emu_stack_1 = new TH1D("leadingJetPt_tZq_wMass_emu_stack_1","leadingJetPt_tZq_wMass_emu",35,0,300);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(5,-0.0006351362);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(6,0.005520673);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(7,0.01144322);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(8,0.007896666);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(9,0.02593119);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(10,0.02845403);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(11,0.02881375);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(12,0.01240921);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(13,0.02760081);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(14,0.01944102);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(15,0.02588313);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(16,0.02388601);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(17,0.01328064);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(18,0.002887627);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(19,0.01714886);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(20,0.005289043);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(21,0.007124099);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(22,0.01672094);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(23,0.01165012);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(24,0.005643483);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(25,0.002679064);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(26,0.000828098);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(27,0.008581316);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(28,0.001735794);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(29,0.006142082);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(30,0.005286327);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(31,0.003026849);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(32,0.001141799);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(33,0.002190529);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(34,0.001679752);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(35,0.0007203751);
   leadingJetPt_tZq_wMass_emu_stack_1->SetBinContent(36,0.01400706);
   leadingJetPt_tZq_wMass_emu_stack_1->SetEntries(2170);
   leadingJetPt_tZq_wMass_emu_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ffff00");
   leadingJetPt_tZq_wMass_emu_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   leadingJetPt_tZq_wMass_emu_stack_1->SetLineColor(ci);
   leadingJetPt_tZq_wMass_emu_stack_1->SetLineWidth(0);
   leadingJetPt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_tZq_wMass_emu_stack_1->GetXaxis()->SetLabelFont(42);
   leadingJetPt_tZq_wMass_emu_stack_1->GetXaxis()->SetLabelSize(0.035);
   leadingJetPt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleSize(0.035);
   leadingJetPt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleFont(42);
   leadingJetPt_tZq_wMass_emu_stack_1->GetYaxis()->SetLabelFont(42);
   leadingJetPt_tZq_wMass_emu_stack_1->GetYaxis()->SetLabelSize(0.035);
   leadingJetPt_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleSize(0.035);
   leadingJetPt_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleOffset(1);
   leadingJetPt_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleFont(42);
   leadingJetPt_tZq_wMass_emu_stack_1->GetZaxis()->SetLabelFont(42);
   leadingJetPt_tZq_wMass_emu_stack_1->GetZaxis()->SetLabelSize(0.035);
   leadingJetPt_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleSize(0.035);
   leadingJetPt_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_wMass_emu->Add(leadingJetPt_tZq_wMass_emu_stack_1,"");
   
   TH1D *leadingJetPt_ttV_wMass_emu_stack_2 = new TH1D("leadingJetPt_ttV_wMass_emu_stack_2","leadingJetPt_ttV_wMass_emu",35,0,300);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(4,0.000827336);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(5,0.07078966);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(6,0.3562526);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(7,0.9289754);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(8,1.074978);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(9,1.357996);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(10,2.044845);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(11,1.59246);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(12,2.093192);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(13,1.270259);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(14,1.879078);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(15,2.209043);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(16,1.718722);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(17,1.127593);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(18,1.073435);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(19,1.418755);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(20,0.6844829);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(21,0.9414691);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(22,0.3882585);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(23,0.6171543);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(24,0.5784621);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(25,0.2551894);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(26,0.5462795);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(27,0.4083624);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(28,0.4384552);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(29,0.321995);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(30,0.2005951);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(31,0.3245138);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(32,0.01140297);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(33,0.3360671);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(34,0.1588589);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(35,0.0984144);
   leadingJetPt_ttV_wMass_emu_stack_2->SetBinContent(36,1.352008);
   leadingJetPt_ttV_wMass_emu_stack_2->SetEntries(14144);
   leadingJetPt_ttV_wMass_emu_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#00ff00");
   leadingJetPt_ttV_wMass_emu_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   leadingJetPt_ttV_wMass_emu_stack_2->SetLineColor(ci);
   leadingJetPt_ttV_wMass_emu_stack_2->SetLineWidth(0);
   leadingJetPt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_ttV_wMass_emu_stack_2->GetXaxis()->SetLabelFont(42);
   leadingJetPt_ttV_wMass_emu_stack_2->GetXaxis()->SetLabelSize(0.035);
   leadingJetPt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleSize(0.035);
   leadingJetPt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleFont(42);
   leadingJetPt_ttV_wMass_emu_stack_2->GetYaxis()->SetLabelFont(42);
   leadingJetPt_ttV_wMass_emu_stack_2->GetYaxis()->SetLabelSize(0.035);
   leadingJetPt_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleSize(0.035);
   leadingJetPt_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleOffset(1);
   leadingJetPt_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleFont(42);
   leadingJetPt_ttV_wMass_emu_stack_2->GetZaxis()->SetLabelFont(42);
   leadingJetPt_ttV_wMass_emu_stack_2->GetZaxis()->SetLabelSize(0.035);
   leadingJetPt_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleSize(0.035);
   leadingJetPt_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_wMass_emu->Add(leadingJetPt_ttV_wMass_emu_stack_2,"");
   
   TH1D *leadingJetPt_wJets_wMass_emu_stack_3 = new TH1D("leadingJetPt_wJets_wMass_emu_stack_3","leadingJetPt_wJets_wMass_emu",35,0,300);
   leadingJetPt_wJets_wMass_emu_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   leadingJetPt_wJets_wMass_emu_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#cccccc");
   leadingJetPt_wJets_wMass_emu_stack_3->SetLineColor(ci);
   leadingJetPt_wJets_wMass_emu_stack_3->SetLineWidth(0);
   leadingJetPt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_wJets_wMass_emu_stack_3->GetXaxis()->SetLabelFont(42);
   leadingJetPt_wJets_wMass_emu_stack_3->GetXaxis()->SetLabelSize(0.035);
   leadingJetPt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleSize(0.035);
   leadingJetPt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleFont(42);
   leadingJetPt_wJets_wMass_emu_stack_3->GetYaxis()->SetLabelFont(42);
   leadingJetPt_wJets_wMass_emu_stack_3->GetYaxis()->SetLabelSize(0.035);
   leadingJetPt_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleSize(0.035);
   leadingJetPt_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleOffset(1);
   leadingJetPt_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleFont(42);
   leadingJetPt_wJets_wMass_emu_stack_3->GetZaxis()->SetLabelFont(42);
   leadingJetPt_wJets_wMass_emu_stack_3->GetZaxis()->SetLabelSize(0.035);
   leadingJetPt_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleSize(0.035);
   leadingJetPt_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_wMass_emu->Add(leadingJetPt_wJets_wMass_emu_stack_3,"");
   
   TH1D *leadingJetPt_VVV_wMass_emu_stack_4 = new TH1D("leadingJetPt_VVV_wMass_emu_stack_4","leadingJetPt_VVV_wMass_emu",35,0,300);
   leadingJetPt_VVV_wMass_emu_stack_4->SetBinContent(6,0.03368239);
   leadingJetPt_VVV_wMass_emu_stack_4->SetBinContent(7,0.02946448);
   leadingJetPt_VVV_wMass_emu_stack_4->SetBinContent(9,0.002352466);
   leadingJetPt_VVV_wMass_emu_stack_4->SetBinContent(12,0.03458785);
   leadingJetPt_VVV_wMass_emu_stack_4->SetBinContent(23,0.03392089);
   leadingJetPt_VVV_wMass_emu_stack_4->SetBinContent(24,0.02384236);
   leadingJetPt_VVV_wMass_emu_stack_4->SetBinContent(29,0.001068281);
   leadingJetPt_VVV_wMass_emu_stack_4->SetBinContent(36,0.06534209);
   leadingJetPt_VVV_wMass_emu_stack_4->SetEntries(9);
   leadingJetPt_VVV_wMass_emu_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#00ffff");
   leadingJetPt_VVV_wMass_emu_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   leadingJetPt_VVV_wMass_emu_stack_4->SetLineColor(ci);
   leadingJetPt_VVV_wMass_emu_stack_4->SetLineWidth(0);
   leadingJetPt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_VVV_wMass_emu_stack_4->GetXaxis()->SetLabelFont(42);
   leadingJetPt_VVV_wMass_emu_stack_4->GetXaxis()->SetLabelSize(0.035);
   leadingJetPt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleSize(0.035);
   leadingJetPt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleFont(42);
   leadingJetPt_VVV_wMass_emu_stack_4->GetYaxis()->SetLabelFont(42);
   leadingJetPt_VVV_wMass_emu_stack_4->GetYaxis()->SetLabelSize(0.035);
   leadingJetPt_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleSize(0.035);
   leadingJetPt_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleOffset(1);
   leadingJetPt_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleFont(42);
   leadingJetPt_VVV_wMass_emu_stack_4->GetZaxis()->SetLabelFont(42);
   leadingJetPt_VVV_wMass_emu_stack_4->GetZaxis()->SetLabelSize(0.035);
   leadingJetPt_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleSize(0.035);
   leadingJetPt_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_wMass_emu->Add(leadingJetPt_VVV_wMass_emu_stack_4,"");
   
   TH1D *leadingJetPt_VV_wMass_emu_stack_5 = new TH1D("leadingJetPt_VV_wMass_emu_stack_5","leadingJetPt_VV_wMass_emu",35,0,300);
   leadingJetPt_VV_wMass_emu_stack_5->SetBinContent(6,0.1379206);
   leadingJetPt_VV_wMass_emu_stack_5->SetBinContent(7,0.216892);
   leadingJetPt_VV_wMass_emu_stack_5->SetBinContent(8,0.2462954);
   leadingJetPt_VV_wMass_emu_stack_5->SetBinContent(9,0.02319993);
   leadingJetPt_VV_wMass_emu_stack_5->SetBinContent(10,0.1617181);
   leadingJetPt_VV_wMass_emu_stack_5->SetBinContent(11,0.005527146);
   leadingJetPt_VV_wMass_emu_stack_5->SetBinContent(13,-0.1834996);
   leadingJetPt_VV_wMass_emu_stack_5->SetBinContent(14,0.01429016);
   leadingJetPt_VV_wMass_emu_stack_5->SetBinContent(15,0.00578657);
   leadingJetPt_VV_wMass_emu_stack_5->SetBinContent(16,0.007506404);
   leadingJetPt_VV_wMass_emu_stack_5->SetBinContent(19,0.02598447);
   leadingJetPt_VV_wMass_emu_stack_5->SetBinContent(20,0.1639006);
   leadingJetPt_VV_wMass_emu_stack_5->SetBinContent(23,0.1601829);
   leadingJetPt_VV_wMass_emu_stack_5->SetBinContent(24,0.2573654);
   leadingJetPt_VV_wMass_emu_stack_5->SetBinContent(25,0.1657343);
   leadingJetPt_VV_wMass_emu_stack_5->SetBinContent(27,0.1522081);
   leadingJetPt_VV_wMass_emu_stack_5->SetBinContent(28,-0.01148484);
   leadingJetPt_VV_wMass_emu_stack_5->SetBinContent(34,0.1753542);
   leadingJetPt_VV_wMass_emu_stack_5->SetBinContent(36,0.7547364);
   leadingJetPt_VV_wMass_emu_stack_5->SetEntries(45);
   leadingJetPt_VV_wMass_emu_stack_5->SetDirectory(0);

   ci = TColor::GetColor("#ff9933");
   leadingJetPt_VV_wMass_emu_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#ff9933");
   leadingJetPt_VV_wMass_emu_stack_5->SetLineColor(ci);
   leadingJetPt_VV_wMass_emu_stack_5->SetLineWidth(0);
   leadingJetPt_VV_wMass_emu_stack_5->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_VV_wMass_emu_stack_5->GetXaxis()->SetLabelFont(42);
   leadingJetPt_VV_wMass_emu_stack_5->GetXaxis()->SetLabelSize(0.035);
   leadingJetPt_VV_wMass_emu_stack_5->GetXaxis()->SetTitleSize(0.035);
   leadingJetPt_VV_wMass_emu_stack_5->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_VV_wMass_emu_stack_5->GetXaxis()->SetTitleFont(42);
   leadingJetPt_VV_wMass_emu_stack_5->GetYaxis()->SetLabelFont(42);
   leadingJetPt_VV_wMass_emu_stack_5->GetYaxis()->SetLabelSize(0.035);
   leadingJetPt_VV_wMass_emu_stack_5->GetYaxis()->SetTitleSize(0.035);
   leadingJetPt_VV_wMass_emu_stack_5->GetYaxis()->SetTitleOffset(1);
   leadingJetPt_VV_wMass_emu_stack_5->GetYaxis()->SetTitleFont(42);
   leadingJetPt_VV_wMass_emu_stack_5->GetZaxis()->SetLabelFont(42);
   leadingJetPt_VV_wMass_emu_stack_5->GetZaxis()->SetLabelSize(0.035);
   leadingJetPt_VV_wMass_emu_stack_5->GetZaxis()->SetTitleSize(0.035);
   leadingJetPt_VV_wMass_emu_stack_5->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_VV_wMass_emu_stack_5->GetZaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_wMass_emu->Add(leadingJetPt_VV_wMass_emu_stack_5,"");
   
   TH1D *leadingJetPt_SingleTop_wMass_emu_stack_6 = new TH1D("leadingJetPt_SingleTop_wMass_emu_stack_6","leadingJetPt_SingleTop_wMass_emu",35,0,300);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(4,0.1960117);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(5,0.3672714);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(6,2.611586);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(7,7.298911);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(8,7.21819);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(9,9.673476);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(10,8.088724);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(11,8.394306);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(12,7.074645);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(13,7.792945);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(14,5.393376);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(15,5.373303);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(16,4.014062);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(17,1.773864);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(18,3.195119);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(19,3.621364);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(20,2.187384);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(21,1.747763);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(22,1.497022);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(23,1.17109);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(24,2.114292);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(25,1.918879);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(26,1.709219);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(27,0.485022);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(28,0.8763982);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(29,0.4502138);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(30,0.5612131);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(31,0.7955236);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(32,0.7696504);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(33,0.5792383);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(34,0.4710873);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(35,0.7696825);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(36,4.543296);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetEntries(1034);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetDirectory(0);

   ci = TColor::GetColor("#ff00ff");
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetLineColor(ci);
   leadingJetPt_SingleTop_wMass_emu_stack_6->SetLineWidth(0);
   leadingJetPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetLabelFont(42);
   leadingJetPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetLabelSize(0.035);
   leadingJetPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleSize(0.035);
   leadingJetPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetLabelFont(42);
   leadingJetPt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetLabelSize(0.035);
   leadingJetPt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleSize(0.035);
   leadingJetPt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleOffset(1);
   leadingJetPt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetLabelFont(42);
   leadingJetPt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetLabelSize(0.035);
   leadingJetPt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleSize(0.035);
   leadingJetPt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_wMass_emu->Add(leadingJetPt_SingleTop_wMass_emu_stack_6,"");
   
   TH1D *leadingJetPt_tt_wMass_emu_stack_7 = new TH1D("leadingJetPt_tt_wMass_emu_stack_7","leadingJetPt_tt_wMass_emu",35,0,300);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(4,0.3054945);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(5,19.91753);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(6,57.41923);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(7,111.5904);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(8,154.5672);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(9,196.4171);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(10,196.2111);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(11,197.2632);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(12,180.0467);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(13,163.3366);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(14,152.5099);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(15,119.4414);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(16,106.339);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(17,97.92045);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(18,92.95464);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(19,71.27034);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(20,60.25849);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(21,53.02321);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(22,45.16171);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(23,40.38692);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(24,34.49893);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(25,31.54617);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(26,20.10442);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(27,18.28422);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(28,23.35439);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(29,17.16224);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(30,16.8995);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(31,9.619406);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(32,13.34886);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(33,12.23586);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(34,9.078399);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(35,6.724716);
   leadingJetPt_tt_wMass_emu_stack_7->SetBinContent(36,71.58125);
   leadingJetPt_tt_wMass_emu_stack_7->SetEntries(7802);
   leadingJetPt_tt_wMass_emu_stack_7->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   leadingJetPt_tt_wMass_emu_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   leadingJetPt_tt_wMass_emu_stack_7->SetLineColor(ci);
   leadingJetPt_tt_wMass_emu_stack_7->SetLineWidth(0);
   leadingJetPt_tt_wMass_emu_stack_7->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_tt_wMass_emu_stack_7->GetXaxis()->SetLabelFont(42);
   leadingJetPt_tt_wMass_emu_stack_7->GetXaxis()->SetLabelSize(0.035);
   leadingJetPt_tt_wMass_emu_stack_7->GetXaxis()->SetTitleSize(0.035);
   leadingJetPt_tt_wMass_emu_stack_7->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_tt_wMass_emu_stack_7->GetXaxis()->SetTitleFont(42);
   leadingJetPt_tt_wMass_emu_stack_7->GetYaxis()->SetLabelFont(42);
   leadingJetPt_tt_wMass_emu_stack_7->GetYaxis()->SetLabelSize(0.035);
   leadingJetPt_tt_wMass_emu_stack_7->GetYaxis()->SetTitleSize(0.035);
   leadingJetPt_tt_wMass_emu_stack_7->GetYaxis()->SetTitleOffset(1);
   leadingJetPt_tt_wMass_emu_stack_7->GetYaxis()->SetTitleFont(42);
   leadingJetPt_tt_wMass_emu_stack_7->GetZaxis()->SetLabelFont(42);
   leadingJetPt_tt_wMass_emu_stack_7->GetZaxis()->SetLabelSize(0.035);
   leadingJetPt_tt_wMass_emu_stack_7->GetZaxis()->SetTitleSize(0.035);
   leadingJetPt_tt_wMass_emu_stack_7->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_tt_wMass_emu_stack_7->GetZaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_wMass_emu->Add(leadingJetPt_tt_wMass_emu_stack_7,"");
   
   TH1D *leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8 = new TH1D("leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8","leadingJetPt_zPlusJetsMadgraph_wMass_emu",35,0,300);
   leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->SetLineColor(ci);
   leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->SetLineWidth(0);
   leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetLabelFont(42);
   leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetLabelSize(0.035);
   leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleSize(0.035);
   leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleFont(42);
   leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetLabelFont(42);
   leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetLabelSize(0.035);
   leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleSize(0.035);
   leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleOffset(1);
   leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleFont(42);
   leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetLabelFont(42);
   leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetLabelSize(0.035);
   leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleSize(0.035);
   leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_wMass_emu->Add(leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8,"");
   leadingJetPt_SingleTop_wMass_emu->Draw("");
   
   TH1D *leadingJetPt_data_wMass_emu__4 = new TH1D("leadingJetPt_data_wMass_emu__4","leadingJetPt_data_wMass_emu",35,0,300);
   leadingJetPt_data_wMass_emu__4->SetBinContent(4,1);
   leadingJetPt_data_wMass_emu__4->SetBinContent(5,21);
   leadingJetPt_data_wMass_emu__4->SetBinContent(6,78);
   leadingJetPt_data_wMass_emu__4->SetBinContent(7,121);
   leadingJetPt_data_wMass_emu__4->SetBinContent(8,201);
   leadingJetPt_data_wMass_emu__4->SetBinContent(9,234);
   leadingJetPt_data_wMass_emu__4->SetBinContent(10,211);
   leadingJetPt_data_wMass_emu__4->SetBinContent(11,217);
   leadingJetPt_data_wMass_emu__4->SetBinContent(12,192);
   leadingJetPt_data_wMass_emu__4->SetBinContent(13,203);
   leadingJetPt_data_wMass_emu__4->SetBinContent(14,153);
   leadingJetPt_data_wMass_emu__4->SetBinContent(15,133);
   leadingJetPt_data_wMass_emu__4->SetBinContent(16,130);
   leadingJetPt_data_wMass_emu__4->SetBinContent(17,111);
   leadingJetPt_data_wMass_emu__4->SetBinContent(18,97);
   leadingJetPt_data_wMass_emu__4->SetBinContent(19,82);
   leadingJetPt_data_wMass_emu__4->SetBinContent(20,65);
   leadingJetPt_data_wMass_emu__4->SetBinContent(21,45);
   leadingJetPt_data_wMass_emu__4->SetBinContent(22,41);
   leadingJetPt_data_wMass_emu__4->SetBinContent(23,41);
   leadingJetPt_data_wMass_emu__4->SetBinContent(24,42);
   leadingJetPt_data_wMass_emu__4->SetBinContent(25,23);
   leadingJetPt_data_wMass_emu__4->SetBinContent(26,28);
   leadingJetPt_data_wMass_emu__4->SetBinContent(27,28);
   leadingJetPt_data_wMass_emu__4->SetBinContent(28,23);
   leadingJetPt_data_wMass_emu__4->SetBinContent(29,20);
   leadingJetPt_data_wMass_emu__4->SetBinContent(30,19);
   leadingJetPt_data_wMass_emu__4->SetBinContent(31,13);
   leadingJetPt_data_wMass_emu__4->SetBinContent(32,12);
   leadingJetPt_data_wMass_emu__4->SetBinContent(33,9);
   leadingJetPt_data_wMass_emu__4->SetBinContent(34,5);
   leadingJetPt_data_wMass_emu__4->SetBinContent(35,14);
   leadingJetPt_data_wMass_emu__4->SetBinContent(36,55);
   leadingJetPt_data_wMass_emu__4->SetEntries(2668);
   leadingJetPt_data_wMass_emu__4->SetDirectory(0);
   leadingJetPt_data_wMass_emu__4->SetFillColor(1);
   leadingJetPt_data_wMass_emu__4->SetLineWidth(2);
   leadingJetPt_data_wMass_emu__4->SetLineColor(1); //
   leadingJetPt_data_wMass_emu__4->SetMarkerStyle(20);
   leadingJetPt_data_wMass_emu__4->SetMarkerSize(1.4);
   leadingJetPt_data_wMass_emu__4->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_data_wMass_emu__4->GetXaxis()->SetLabelFont(42);
   leadingJetPt_data_wMass_emu__4->GetXaxis()->SetLabelSize(0.035);
   leadingJetPt_data_wMass_emu__4->GetXaxis()->SetTitleSize(0.035);
   leadingJetPt_data_wMass_emu__4->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_data_wMass_emu__4->GetXaxis()->SetTitleFont(42);
   leadingJetPt_data_wMass_emu__4->GetYaxis()->SetLabelFont(42);
   leadingJetPt_data_wMass_emu__4->GetYaxis()->SetLabelSize(0.035);
   leadingJetPt_data_wMass_emu__4->GetYaxis()->SetTitleSize(0.035);
   leadingJetPt_data_wMass_emu__4->GetYaxis()->SetTitleOffset(1);
   leadingJetPt_data_wMass_emu__4->GetYaxis()->SetTitleFont(42);
   leadingJetPt_data_wMass_emu__4->GetZaxis()->SetLabelFont(42);
   leadingJetPt_data_wMass_emu__4->GetZaxis()->SetLabelSize(0.035);
   leadingJetPt_data_wMass_emu__4->GetZaxis()->SetTitleSize(0.035);
   leadingJetPt_data_wMass_emu__4->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_data_wMass_emu__4->GetZaxis()->SetTitleFont(42);
   leadingJetPt_data_wMass_emu__4->Draw("e x0, same");
   
   TLegend *leg = new TLegend(0.78,0.42,0.98,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("leadingJetPt_zPlusJetsMadgraph_wMass_emu_stack_8","Z+jets (LO)","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetPt_tt_wMass_emu_stack_7","t#bar{t}","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetPt_SingleTop_wMass_emu_stack_6","Single top","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetPt_VV_wMass_emu_stack_5","VV","f");

   ci = TColor::GetColor("#ff9933");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetPt_VVV_wMass_emu_stack_4","VVV","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetPt_wJets_wMass_emu_stack_3","W+jets","f");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetPt_ttV_wMass_emu_stack_2","t#bar{t}V","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetPt_tZq_wMass_emu_stack_1","tZq","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("leadingJetPt_data_wMass_emu","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.4);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.968,0.9429101,"35.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06792969);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.096,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.05419922);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16899,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.04119141);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *leadingJetPt_SingleTop_wMass_emu__5 = new TH1F("leadingJetPt_SingleTop_wMass_emu__5","Leading Jet p_{T}",35,0,300);
   leadingJetPt_SingleTop_wMass_emu__5->SetMinimum(0);
   leadingJetPt_SingleTop_wMass_emu__5->SetMaximum(270.27);
   leadingJetPt_SingleTop_wMass_emu__5->SetDirectory(0);
   leadingJetPt_SingleTop_wMass_emu__5->SetStats(0);
   leadingJetPt_SingleTop_wMass_emu__5->SetLineStyle(0);
   leadingJetPt_SingleTop_wMass_emu__5->SetLineWidth(0);
   leadingJetPt_SingleTop_wMass_emu__5->SetMarkerStyle(20);
   leadingJetPt_SingleTop_wMass_emu__5->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_SingleTop_wMass_emu__5->GetXaxis()->SetNdivisions(506);
   leadingJetPt_SingleTop_wMass_emu__5->GetXaxis()->SetLabelFont(42);
   leadingJetPt_SingleTop_wMass_emu__5->GetXaxis()->SetLabelOffset(999);
   leadingJetPt_SingleTop_wMass_emu__5->GetXaxis()->SetLabelSize(0.05);
   leadingJetPt_SingleTop_wMass_emu__5->GetXaxis()->SetTitleSize(0.08);
   leadingJetPt_SingleTop_wMass_emu__5->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_SingleTop_wMass_emu__5->GetXaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_wMass_emu__5->GetYaxis()->SetTitle("Events");
   leadingJetPt_SingleTop_wMass_emu__5->GetYaxis()->SetNdivisions(506);
   leadingJetPt_SingleTop_wMass_emu__5->GetYaxis()->SetLabelFont(42);
   leadingJetPt_SingleTop_wMass_emu__5->GetYaxis()->SetLabelOffset(0.01);
   leadingJetPt_SingleTop_wMass_emu__5->GetYaxis()->SetLabelSize(0.062);
   leadingJetPt_SingleTop_wMass_emu__5->GetYaxis()->SetTitleSize(0.08);
   leadingJetPt_SingleTop_wMass_emu__5->GetYaxis()->SetTitleOffset(0.6336);
   leadingJetPt_SingleTop_wMass_emu__5->GetYaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_wMass_emu__5->GetZaxis()->SetLabelFont(42);
   leadingJetPt_SingleTop_wMass_emu__5->GetZaxis()->SetLabelOffset(0.007);
   leadingJetPt_SingleTop_wMass_emu__5->GetZaxis()->SetLabelSize(0.05);
   leadingJetPt_SingleTop_wMass_emu__5->GetZaxis()->SetTitleSize(0.08);
   leadingJetPt_SingleTop_wMass_emu__5->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_SingleTop_wMass_emu__5->GetZaxis()->SetTitleFont(42);
   leadingJetPt_SingleTop_wMass_emu__5->Draw("sameaxis");
   
   TPaveText *pt = new TPaveText(0.4217333,0.9203237,0.5782667,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Leading Jet p_{T}");
   pt->Draw();
   canvy_1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: canvy_2
   TPad *canvy_2 = new TPad("canvy_2", "newpad2",0.01,0.01,0.99,0.322);
   canvy_2->Draw();
   canvy_2->cd();
   canvy_2->SetFillColor(0);
   canvy_2->SetBorderMode(0);
   canvy_2->SetGridy();

   canvy_2->SetLeftMargin( L/W );
   canvy_2->SetRightMargin( R/W );
   canvy_2->SetTopMargin( T/H );
   canvy_2->SetBottomMargin( B/H * 2.6 );
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   
   TH1D *leadingJetPt_data_wMass_emu__6 = new TH1D("leadingJetPt_data_wMass_emu__6","",35,0,300);
   leadingJetPt_data_wMass_emu__6->SetBinContent(4,1.990709);
   leadingJetPt_data_wMass_emu__6->SetBinContent(5,1.03169);
   leadingJetPt_data_wMass_emu__6->SetBinContent(6,1.28789);
   leadingJetPt_data_wMass_emu__6->SetBinContent(7,1.007695);
   leadingJetPt_data_wMass_emu__6->SetBinContent(8,1.232263);
   leadingJetPt_data_wMass_emu__6->SetBinContent(9,1.12771);
   leadingJetPt_data_wMass_emu__6->SetBinContent(10,1.021619);
   leadingJetPt_data_wMass_emu__6->SetBinContent(11,1.046871);
   leadingJetPt_data_wMass_emu__6->SetBinContent(12,1.014469);
   leadingJetPt_data_wMass_emu__6->SetBinContent(13,1.178561);
   leadingJetPt_data_wMass_emu__6->SetBinContent(14,0.9573504);
   leadingJetPt_data_wMass_emu__6->SetBinContent(15,1.046787);
   leadingJetPt_data_wMass_emu__6->SetBinContent(16,1.159646);
   leadingJetPt_data_wMass_emu__6->SetBinContent(17,1.100806);
   leadingJetPt_data_wMass_emu__6->SetBinContent(18,0.9976746);
   leadingJetPt_data_wMass_emu__6->SetBinContent(19,1.073951);
   leadingJetPt_data_wMass_emu__6->SetBinContent(20,1.026864);
   leadingJetPt_data_wMass_emu__6->SetBinContent(21,0.8076158);
   leadingJetPt_data_wMass_emu__6->SetBinContent(22,0.8711595);
   leadingJetPt_data_wMass_emu__6->SetBinContent(23,0.9674164);
   leadingJetPt_data_wMass_emu__6->SetBinContent(24,1.120641);
   leadingJetPt_data_wMass_emu__6->SetBinContent(25,0.6786933);
   leadingJetPt_data_wMass_emu__6->SetBinContent(26,1.252194);
   leadingJetPt_data_wMass_emu__6->SetBinContent(27,1.447897);
   leadingJetPt_data_wMass_emu__6->SetBinContent(28,0.9327038);
   leadingJetPt_data_wMass_emu__6->SetBinContent(29,1.114724);
   leadingJetPt_data_wMass_emu__6->SetBinContent(30,1.075476);
   leadingJetPt_data_wMass_emu__6->SetBinContent(31,1.21015);
   leadingJetPt_data_wMass_emu__6->SetBinContent(32,0.8491932);
   leadingJetPt_data_wMass_emu__6->SetBinContent(33,0.6842362);
   leadingJetPt_data_wMass_emu__6->SetBinContent(34,0.5057975);
   leadingJetPt_data_wMass_emu__6->SetBinContent(35,1.843674);
   leadingJetPt_data_wMass_emu__6->SetBinContent(36,0.7023311);
   leadingJetPt_data_wMass_emu__6->SetBinError(4,3.442666);
   leadingJetPt_data_wMass_emu__6->SetBinError(5,0.3208989);
   leadingJetPt_data_wMass_emu__6->SetBinError(6,0.2205713);
   leadingJetPt_data_wMass_emu__6->SetBinError(7,0.1298031);
   leadingJetPt_data_wMass_emu__6->SetBinError(8,0.1298608);
   leadingJetPt_data_wMass_emu__6->SetBinError(9,0.107534);
   leadingJetPt_data_wMass_emu__6->SetBinError(10,0.09999944);
   leadingJetPt_data_wMass_emu__6->SetBinError(11,0.1016737);
   leadingJetPt_data_wMass_emu__6->SetBinError(12,0.1039127);
   leadingJetPt_data_wMass_emu__6->SetBinError(13,0.1220925);
   leadingJetPt_data_wMass_emu__6->SetBinError(14,0.1082828);
   leadingJetPt_data_wMass_emu__6->SetBinError(15,0.1298581);
   leadingJetPt_data_wMass_emu__6->SetBinError(16,0.1494669);
   leadingJetPt_data_wMass_emu__6->SetBinError(17,0.1514406);
   leadingJetPt_data_wMass_emu__6->SetBinError(18,0.1431744);
   leadingJetPt_data_wMass_emu__6->SetBinError(19,0.1707956);
   leadingJetPt_data_wMass_emu__6->SetBinError(20,0.1813294);
   leadingJetPt_data_wMass_emu__6->SetBinError(21,0.1618645);
   leadingJetPt_data_wMass_emu__6->SetBinError(22,0.1861063);
   leadingJetPt_data_wMass_emu__6->SetBinError(23,0.2119189);
   leadingJetPt_data_wMass_emu__6->SetBinError(24,0.2518116);
   leadingJetPt_data_wMass_emu__6->SetBinError(25,0.1833561);
   leadingJetPt_data_wMass_emu__6->SetBinError(26,0.3551368);
   leadingJetPt_data_wMass_emu__6->SetBinError(27,0.4281098);
   leadingJetPt_data_wMass_emu__6->SetBinError(28,0.2703725);
   leadingJetPt_data_wMass_emu__6->SetBinError(29,0.3624759);
   leadingJetPt_data_wMass_emu__6->SetBinError(30,0.3554534);
   leadingJetPt_data_wMass_emu__6->SetBinError(31,0.4989746);
   leadingJetPt_data_wMass_emu__6->SetBinError(32,0.3333551);
   leadingJetPt_data_wMass_emu__6->SetBinError(33,0.2959963);
   leadingJetPt_data_wMass_emu__6->SetBinError(34,0.2775716);
   leadingJetPt_data_wMass_emu__6->SetBinError(35,0.8309216);
   leadingJetPt_data_wMass_emu__6->SetBinError(36,0.1235613);
   leadingJetPt_data_wMass_emu__6->SetMinimum(0.5);
   leadingJetPt_data_wMass_emu__6->SetMaximum(1.5);
   leadingJetPt_data_wMass_emu__6->SetEntries(83.97226);
   leadingJetPt_data_wMass_emu__6->SetDirectory(0);
   leadingJetPt_data_wMass_emu__6->SetStats(0);
   leadingJetPt_data_wMass_emu__6->SetFillColor(1);
   leadingJetPt_data_wMass_emu__6->SetLineWidth(2);
   leadingJetPt_data_wMass_emu__6->SetLineColor(1); //
   leadingJetPt_data_wMass_emu__6->SetMarkerStyle(20);
   leadingJetPt_data_wMass_emu__6->SetMarkerSize(1.6);
   leadingJetPt_data_wMass_emu__6->GetXaxis()->SetTitle("Leading jet p_{T} (GeV)");
   leadingJetPt_data_wMass_emu__6->GetXaxis()->SetNdivisions(506);
   leadingJetPt_data_wMass_emu__6->GetXaxis()->SetLabelFont(42);
   leadingJetPt_data_wMass_emu__6->GetXaxis()->SetLabelOffset(0.013);
   leadingJetPt_data_wMass_emu__6->GetXaxis()->SetLabelSize(0.13);
   leadingJetPt_data_wMass_emu__6->GetXaxis()->SetTitleSize(0.13);
   leadingJetPt_data_wMass_emu__6->GetXaxis()->SetTitleOffset(1);
   leadingJetPt_data_wMass_emu__6->GetXaxis()->SetTitleFont(42);
   leadingJetPt_data_wMass_emu__6->GetYaxis()->SetTitle("Data/MC");
   leadingJetPt_data_wMass_emu__6->GetYaxis()->CenterTitle(true);
   leadingJetPt_data_wMass_emu__6->GetYaxis()->SetNdivisions(506);
   leadingJetPt_data_wMass_emu__6->GetYaxis()->SetLabelFont(42);
   leadingJetPt_data_wMass_emu__6->GetYaxis()->SetLabelOffset(0.01);
   leadingJetPt_data_wMass_emu__6->GetYaxis()->SetLabelSize(0.12);
   leadingJetPt_data_wMass_emu__6->GetYaxis()->SetTitleSize(0.16);
   leadingJetPt_data_wMass_emu__6->GetYaxis()->SetTitleOffset(0.3);
   leadingJetPt_data_wMass_emu__6->GetYaxis()->SetTitleFont(42);
   leadingJetPt_data_wMass_emu__6->GetZaxis()->SetLabelFont(42);
   leadingJetPt_data_wMass_emu__6->GetZaxis()->SetLabelSize(0.035);
   leadingJetPt_data_wMass_emu__6->GetZaxis()->SetTitleSize(0.035);
   leadingJetPt_data_wMass_emu__6->GetZaxis()->SetTitleOffset(1);
   leadingJetPt_data_wMass_emu__6->GetZaxis()->SetTitleFont(42);
   leadingJetPt_data_wMass_emu__6->Draw("e x0, SCAT");
   canvy_2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
//   c1->SetSelected(leadingJetPt_data_wMass_emu);
   c1->SaveAs("leadingJetPt_wMass.pdf");
}
