void lep1Pt_SingleTop_lepSel()
{
//=========Macro generated from canvas: lep1Pt_SingleTop_lepSel/lep1Pt_SingleTop_lepSel
//=========  (Wed Aug 21 20:25:20 2019) by ROOT version 6.18/00

   // Set up cavas
   int W = 1280;
   int H = 1024;
   int H_ref = 925;
   int W_ref = 1024;

   // references for T, B, L, R
   float T = 0.08*H_ref;
   float B = 0.12*H_ref;
   float L = 0.12*W_ref;
   float R = 0.04*W_ref;

   TCanvas *c1 = new TCanvas("c1","c1",50,50,W,H);
   c1->cd();
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetLeftMargin( L/W );
   c1->SetRightMargin( R/W );
   c1->SetTopMargin( T/H );
   c1->SetBottomMargin( B/H );
   c1->SetTickx(0);
   c1->SetTicky(0);

// ------------>Primitives in pad: canvy_1
   TPad *canvy_1 = new TPad("canvy_1", "newpad",0.01,0.315,0.99,0.99);
   canvy_1->Draw();
   canvy_1->cd();
   canvy_1->SetFillColor(0);
   canvy_1->SetBorderMode(0);

   canvy_1->SetLeftMargin( L/W );
   canvy_1->SetRightMargin( R/W );
   canvy_1->SetTopMargin( T/H );
   canvy_1->SetBottomMargin( B/H * 0.3 );

   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);
   
   THStack *lep1Pt_SingleTop_lepSel_emu = new THStack();
   lep1Pt_SingleTop_lepSel_emu->SetName("lep1Pt_SingleTop_lepSel_emu");
   lep1Pt_SingleTop_lepSel_emu->SetTitle(";Electron p_{T} (GeV);Events");
   lep1Pt_SingleTop_lepSel_emu->SetMaximum(41914.4);
   
   TH1F *lep1Pt_SingleTop_lepSel_emu_stack_2 = new TH1F("lep1Pt_SingleTop_lepSel_emu_stack_2","Electron p_{T}",20,0,200);
   lep1Pt_SingleTop_lepSel_emu_stack_2->SetMinimum(0);
   lep1Pt_SingleTop_lepSel_emu_stack_2->SetMaximum(44010.12);
   lep1Pt_SingleTop_lepSel_emu_stack_2->SetDirectory(0);
   lep1Pt_SingleTop_lepSel_emu_stack_2->SetStats(0);
   lep1Pt_SingleTop_lepSel_emu_stack_2->SetLineStyle(0);
   lep1Pt_SingleTop_lepSel_emu_stack_2->SetLineWidth(0);
   lep1Pt_SingleTop_lepSel_emu_stack_2->SetMarkerStyle(20);
   lep1Pt_SingleTop_lepSel_emu_stack_2->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_SingleTop_lepSel_emu_stack_2->GetXaxis()->SetNdivisions(506);
   lep1Pt_SingleTop_lepSel_emu_stack_2->GetXaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_lepSel_emu_stack_2->GetXaxis()->SetLabelOffset(999);
   lep1Pt_SingleTop_lepSel_emu_stack_2->GetXaxis()->SetLabelSize(0.05);
   lep1Pt_SingleTop_lepSel_emu_stack_2->GetXaxis()->SetTitleSize(0.08);
   lep1Pt_SingleTop_lepSel_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   lep1Pt_SingleTop_lepSel_emu_stack_2->GetXaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_lepSel_emu_stack_2->GetYaxis()->SetTitle("Events");
   lep1Pt_SingleTop_lepSel_emu_stack_2->GetYaxis()->SetNdivisions(506);
   lep1Pt_SingleTop_lepSel_emu_stack_2->GetYaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_lepSel_emu_stack_2->GetYaxis()->SetLabelOffset(0.01);
   lep1Pt_SingleTop_lepSel_emu_stack_2->GetYaxis()->SetLabelSize(0.062);
   lep1Pt_SingleTop_lepSel_emu_stack_2->GetYaxis()->SetTitleSize(0.08);
   lep1Pt_SingleTop_lepSel_emu_stack_2->GetYaxis()->SetTitleOffset(0.6336);
   lep1Pt_SingleTop_lepSel_emu_stack_2->GetYaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_lepSel_emu_stack_2->GetZaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_lepSel_emu_stack_2->GetZaxis()->SetLabelOffset(0.007);
   lep1Pt_SingleTop_lepSel_emu_stack_2->GetZaxis()->SetLabelSize(0.05);
   lep1Pt_SingleTop_lepSel_emu_stack_2->GetZaxis()->SetTitleSize(0.08);
   lep1Pt_SingleTop_lepSel_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   lep1Pt_SingleTop_lepSel_emu_stack_2->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_lepSel_emu->SetHistogram(lep1Pt_SingleTop_lepSel_emu_stack_2);
   
   
   TH1D *lep1Pt_tZq_lepSel_emu_stack_1 = new TH1D("lep1Pt_tZq_lepSel_emu_stack_1","lep1Pt_tZq_lepSel_emu",20,0,200);
   lep1Pt_tZq_lepSel_emu_stack_1->SetBinContent(4,1.60243);
   lep1Pt_tZq_lepSel_emu_stack_1->SetBinContent(5,2.920907);
   lep1Pt_tZq_lepSel_emu_stack_1->SetBinContent(6,2.396104);
   lep1Pt_tZq_lepSel_emu_stack_1->SetBinContent(7,1.701115);
   lep1Pt_tZq_lepSel_emu_stack_1->SetBinContent(8,1.35504);
   lep1Pt_tZq_lepSel_emu_stack_1->SetBinContent(9,0.9328107);
   lep1Pt_tZq_lepSel_emu_stack_1->SetBinContent(10,0.8178099);
   lep1Pt_tZq_lepSel_emu_stack_1->SetBinContent(11,0.6683169);
   lep1Pt_tZq_lepSel_emu_stack_1->SetBinContent(12,0.4638681);
   lep1Pt_tZq_lepSel_emu_stack_1->SetBinContent(13,0.3803584);
   lep1Pt_tZq_lepSel_emu_stack_1->SetBinContent(14,0.3066399);
   lep1Pt_tZq_lepSel_emu_stack_1->SetBinContent(15,0.2555993);
   lep1Pt_tZq_lepSel_emu_stack_1->SetBinContent(16,0.1776093);
   lep1Pt_tZq_lepSel_emu_stack_1->SetBinContent(17,0.1586298);
   lep1Pt_tZq_lepSel_emu_stack_1->SetBinContent(18,0.1201962);
   lep1Pt_tZq_lepSel_emu_stack_1->SetBinContent(19,0.1289437);
   lep1Pt_tZq_lepSel_emu_stack_1->SetBinContent(20,0.04709718);
   lep1Pt_tZq_lepSel_emu_stack_1->SetBinContent(21,0.3944179);
   lep1Pt_tZq_lepSel_emu_stack_1->SetEntries(84055);
   lep1Pt_tZq_lepSel_emu_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ffff00");
   lep1Pt_tZq_lepSel_emu_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   lep1Pt_tZq_lepSel_emu_stack_1->SetLineColor(ci);
   lep1Pt_tZq_lepSel_emu_stack_1->SetLineWidth(0);
   lep1Pt_tZq_lepSel_emu_stack_1->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_tZq_lepSel_emu_stack_1->GetXaxis()->SetLabelFont(42);
   lep1Pt_tZq_lepSel_emu_stack_1->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_tZq_lepSel_emu_stack_1->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_tZq_lepSel_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   lep1Pt_tZq_lepSel_emu_stack_1->GetXaxis()->SetTitleFont(42);
   lep1Pt_tZq_lepSel_emu_stack_1->GetYaxis()->SetLabelFont(42);
   lep1Pt_tZq_lepSel_emu_stack_1->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_tZq_lepSel_emu_stack_1->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_tZq_lepSel_emu_stack_1->GetYaxis()->SetTitleOffset(1);
   lep1Pt_tZq_lepSel_emu_stack_1->GetYaxis()->SetTitleFont(42);
   lep1Pt_tZq_lepSel_emu_stack_1->GetZaxis()->SetLabelFont(42);
   lep1Pt_tZq_lepSel_emu_stack_1->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_tZq_lepSel_emu_stack_1->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_tZq_lepSel_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   lep1Pt_tZq_lepSel_emu_stack_1->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_lepSel_emu->Add(lep1Pt_tZq_lepSel_emu_stack_1,"");
   
   TH1D *lep1Pt_ttV_lepSel_emu_stack_2 = new TH1D("lep1Pt_ttV_lepSel_emu_stack_2","lep1Pt_ttV_lepSel_emu",20,0,200);
   lep1Pt_ttV_lepSel_emu_stack_2->SetBinContent(4,42.14568);
   lep1Pt_ttV_lepSel_emu_stack_2->SetBinContent(5,75.66102);
   lep1Pt_ttV_lepSel_emu_stack_2->SetBinContent(6,66.50569);
   lep1Pt_ttV_lepSel_emu_stack_2->SetBinContent(7,55.87371);
   lep1Pt_ttV_lepSel_emu_stack_2->SetBinContent(8,44.1179);
   lep1Pt_ttV_lepSel_emu_stack_2->SetBinContent(9,35.14523);
   lep1Pt_ttV_lepSel_emu_stack_2->SetBinContent(10,29.95311);
   lep1Pt_ttV_lepSel_emu_stack_2->SetBinContent(11,23.90375);
   lep1Pt_ttV_lepSel_emu_stack_2->SetBinContent(12,19.81464);
   lep1Pt_ttV_lepSel_emu_stack_2->SetBinContent(13,15.24524);
   lep1Pt_ttV_lepSel_emu_stack_2->SetBinContent(14,12.49773);
   lep1Pt_ttV_lepSel_emu_stack_2->SetBinContent(15,9.235306);
   lep1Pt_ttV_lepSel_emu_stack_2->SetBinContent(16,8.46419);
   lep1Pt_ttV_lepSel_emu_stack_2->SetBinContent(17,6.744361);
   lep1Pt_ttV_lepSel_emu_stack_2->SetBinContent(18,5.557014);
   lep1Pt_ttV_lepSel_emu_stack_2->SetBinContent(19,4.070047);
   lep1Pt_ttV_lepSel_emu_stack_2->SetBinContent(20,4.211139);
   lep1Pt_ttV_lepSel_emu_stack_2->SetBinContent(21,17.11479);
   lep1Pt_ttV_lepSel_emu_stack_2->SetEntries(262408);
   lep1Pt_ttV_lepSel_emu_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#00ff00");
   lep1Pt_ttV_lepSel_emu_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   lep1Pt_ttV_lepSel_emu_stack_2->SetLineColor(ci);
   lep1Pt_ttV_lepSel_emu_stack_2->SetLineWidth(0);
   lep1Pt_ttV_lepSel_emu_stack_2->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_ttV_lepSel_emu_stack_2->GetXaxis()->SetLabelFont(42);
   lep1Pt_ttV_lepSel_emu_stack_2->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_ttV_lepSel_emu_stack_2->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_ttV_lepSel_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   lep1Pt_ttV_lepSel_emu_stack_2->GetXaxis()->SetTitleFont(42);
   lep1Pt_ttV_lepSel_emu_stack_2->GetYaxis()->SetLabelFont(42);
   lep1Pt_ttV_lepSel_emu_stack_2->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_ttV_lepSel_emu_stack_2->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_ttV_lepSel_emu_stack_2->GetYaxis()->SetTitleOffset(1);
   lep1Pt_ttV_lepSel_emu_stack_2->GetYaxis()->SetTitleFont(42);
   lep1Pt_ttV_lepSel_emu_stack_2->GetZaxis()->SetLabelFont(42);
   lep1Pt_ttV_lepSel_emu_stack_2->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_ttV_lepSel_emu_stack_2->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_ttV_lepSel_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   lep1Pt_ttV_lepSel_emu_stack_2->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_lepSel_emu->Add(lep1Pt_ttV_lepSel_emu_stack_2,"");
   
   TH1D *lep1Pt_wJets_lepSel_emu_stack_3 = new TH1D("lep1Pt_wJets_lepSel_emu_stack_3","lep1Pt_wJets_lepSel_emu",20,0,200);
   lep1Pt_wJets_lepSel_emu_stack_3->SetBinContent(4,905.796);
   lep1Pt_wJets_lepSel_emu_stack_3->SetBinContent(5,1178.845);
   lep1Pt_wJets_lepSel_emu_stack_3->SetBinContent(6,447.406);
   lep1Pt_wJets_lepSel_emu_stack_3->SetBinContent(7,409.2288);
   lep1Pt_wJets_lepSel_emu_stack_3->SetBinContent(8,258.1919);
   lep1Pt_wJets_lepSel_emu_stack_3->SetBinContent(9,129.0921);
   lep1Pt_wJets_lepSel_emu_stack_3->SetBinContent(10,231.8023);
   lep1Pt_wJets_lepSel_emu_stack_3->SetBinContent(11,105.3564);
   lep1Pt_wJets_lepSel_emu_stack_3->SetBinContent(12,67.43259);
   lep1Pt_wJets_lepSel_emu_stack_3->SetBinContent(13,63.16517);
   lep1Pt_wJets_lepSel_emu_stack_3->SetBinContent(14,55.60638);
   lep1Pt_wJets_lepSel_emu_stack_3->SetBinContent(15,25.60722);
   lep1Pt_wJets_lepSel_emu_stack_3->SetBinContent(16,26.53303);
   lep1Pt_wJets_lepSel_emu_stack_3->SetBinContent(17,30.30405);
   lep1Pt_wJets_lepSel_emu_stack_3->SetBinContent(19,13.15176);
   lep1Pt_wJets_lepSel_emu_stack_3->SetBinContent(21,46.24543);
   lep1Pt_wJets_lepSel_emu_stack_3->SetEntries(385);
   lep1Pt_wJets_lepSel_emu_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   lep1Pt_wJets_lepSel_emu_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#cccccc");
   lep1Pt_wJets_lepSel_emu_stack_3->SetLineColor(ci);
   lep1Pt_wJets_lepSel_emu_stack_3->SetLineWidth(0);
   lep1Pt_wJets_lepSel_emu_stack_3->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_wJets_lepSel_emu_stack_3->GetXaxis()->SetLabelFont(42);
   lep1Pt_wJets_lepSel_emu_stack_3->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_wJets_lepSel_emu_stack_3->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_wJets_lepSel_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   lep1Pt_wJets_lepSel_emu_stack_3->GetXaxis()->SetTitleFont(42);
   lep1Pt_wJets_lepSel_emu_stack_3->GetYaxis()->SetLabelFont(42);
   lep1Pt_wJets_lepSel_emu_stack_3->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_wJets_lepSel_emu_stack_3->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_wJets_lepSel_emu_stack_3->GetYaxis()->SetTitleOffset(1);
   lep1Pt_wJets_lepSel_emu_stack_3->GetYaxis()->SetTitleFont(42);
   lep1Pt_wJets_lepSel_emu_stack_3->GetZaxis()->SetLabelFont(42);
   lep1Pt_wJets_lepSel_emu_stack_3->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_wJets_lepSel_emu_stack_3->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_wJets_lepSel_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   lep1Pt_wJets_lepSel_emu_stack_3->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_lepSel_emu->Add(lep1Pt_wJets_lepSel_emu_stack_3,"");
   
   TH1D *lep1Pt_VVV_lepSel_emu_stack_4 = new TH1D("lep1Pt_VVV_lepSel_emu_stack_4","lep1Pt_VVV_lepSel_emu",20,0,200);
   lep1Pt_VVV_lepSel_emu_stack_4->SetBinContent(4,9.457346);
   lep1Pt_VVV_lepSel_emu_stack_4->SetBinContent(5,18.07644);
   lep1Pt_VVV_lepSel_emu_stack_4->SetBinContent(6,14.7896);
   lep1Pt_VVV_lepSel_emu_stack_4->SetBinContent(7,12.10185);
   lep1Pt_VVV_lepSel_emu_stack_4->SetBinContent(8,9.153375);
   lep1Pt_VVV_lepSel_emu_stack_4->SetBinContent(9,7.447659);
   lep1Pt_VVV_lepSel_emu_stack_4->SetBinContent(10,6.688777);
   lep1Pt_VVV_lepSel_emu_stack_4->SetBinContent(11,5.409455);
   lep1Pt_VVV_lepSel_emu_stack_4->SetBinContent(12,4.090126);
   lep1Pt_VVV_lepSel_emu_stack_4->SetBinContent(13,3.750615);
   lep1Pt_VVV_lepSel_emu_stack_4->SetBinContent(14,2.783777);
   lep1Pt_VVV_lepSel_emu_stack_4->SetBinContent(15,2.092144);
   lep1Pt_VVV_lepSel_emu_stack_4->SetBinContent(16,2.071618);
   lep1Pt_VVV_lepSel_emu_stack_4->SetBinContent(17,2.34558);
   lep1Pt_VVV_lepSel_emu_stack_4->SetBinContent(18,1.60277);
   lep1Pt_VVV_lepSel_emu_stack_4->SetBinContent(19,1.107861);
   lep1Pt_VVV_lepSel_emu_stack_4->SetBinContent(20,0.9295353);
   lep1Pt_VVV_lepSel_emu_stack_4->SetBinContent(21,8.879619);
   lep1Pt_VVV_lepSel_emu_stack_4->SetEntries(4590);
   lep1Pt_VVV_lepSel_emu_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#00ffff");
   lep1Pt_VVV_lepSel_emu_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   lep1Pt_VVV_lepSel_emu_stack_4->SetLineColor(ci);
   lep1Pt_VVV_lepSel_emu_stack_4->SetLineWidth(0);
   lep1Pt_VVV_lepSel_emu_stack_4->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_VVV_lepSel_emu_stack_4->GetXaxis()->SetLabelFont(42);
   lep1Pt_VVV_lepSel_emu_stack_4->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_VVV_lepSel_emu_stack_4->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_VVV_lepSel_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   lep1Pt_VVV_lepSel_emu_stack_4->GetXaxis()->SetTitleFont(42);
   lep1Pt_VVV_lepSel_emu_stack_4->GetYaxis()->SetLabelFont(42);
   lep1Pt_VVV_lepSel_emu_stack_4->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_VVV_lepSel_emu_stack_4->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_VVV_lepSel_emu_stack_4->GetYaxis()->SetTitleOffset(1);
   lep1Pt_VVV_lepSel_emu_stack_4->GetYaxis()->SetTitleFont(42);
   lep1Pt_VVV_lepSel_emu_stack_4->GetZaxis()->SetLabelFont(42);
   lep1Pt_VVV_lepSel_emu_stack_4->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_VVV_lepSel_emu_stack_4->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_VVV_lepSel_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   lep1Pt_VVV_lepSel_emu_stack_4->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_lepSel_emu->Add(lep1Pt_VVV_lepSel_emu_stack_4,"");
   
   TH1D *lep1Pt_VV_lepSel_emu_stack_5 = new TH1D("lep1Pt_VV_lepSel_emu_stack_5","lep1Pt_VV_lepSel_emu",20,0,200);
   lep1Pt_VV_lepSel_emu_stack_5->SetBinContent(4,2386.576);
   lep1Pt_VV_lepSel_emu_stack_5->SetBinContent(5,4059.749);
   lep1Pt_VV_lepSel_emu_stack_5->SetBinContent(6,3051.122);
   lep1Pt_VV_lepSel_emu_stack_5->SetBinContent(7,2109.034);
   lep1Pt_VV_lepSel_emu_stack_5->SetBinContent(8,1484.565);
   lep1Pt_VV_lepSel_emu_stack_5->SetBinContent(9,1035.146);
   lep1Pt_VV_lepSel_emu_stack_5->SetBinContent(10,730.781);
   lep1Pt_VV_lepSel_emu_stack_5->SetBinContent(11,558.9483);
   lep1Pt_VV_lepSel_emu_stack_5->SetBinContent(12,408.4882);
   lep1Pt_VV_lepSel_emu_stack_5->SetBinContent(13,328.3922);
   lep1Pt_VV_lepSel_emu_stack_5->SetBinContent(14,240.1885);
   lep1Pt_VV_lepSel_emu_stack_5->SetBinContent(15,179.6601);
   lep1Pt_VV_lepSel_emu_stack_5->SetBinContent(16,148.0244);
   lep1Pt_VV_lepSel_emu_stack_5->SetBinContent(17,103.0987);
   lep1Pt_VV_lepSel_emu_stack_5->SetBinContent(18,98.90308);
   lep1Pt_VV_lepSel_emu_stack_5->SetBinContent(19,73.90139);
   lep1Pt_VV_lepSel_emu_stack_5->SetBinContent(20,58.97925);
   lep1Pt_VV_lepSel_emu_stack_5->SetBinContent(21,341.6583);
   lep1Pt_VV_lepSel_emu_stack_5->SetEntries(128335);
   lep1Pt_VV_lepSel_emu_stack_5->SetDirectory(0);

   ci = TColor::GetColor("#ff9933");
   lep1Pt_VV_lepSel_emu_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#ff9933");
   lep1Pt_VV_lepSel_emu_stack_5->SetLineColor(ci);
   lep1Pt_VV_lepSel_emu_stack_5->SetLineWidth(0);
   lep1Pt_VV_lepSel_emu_stack_5->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_VV_lepSel_emu_stack_5->GetXaxis()->SetLabelFont(42);
   lep1Pt_VV_lepSel_emu_stack_5->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_VV_lepSel_emu_stack_5->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_VV_lepSel_emu_stack_5->GetXaxis()->SetTitleOffset(1);
   lep1Pt_VV_lepSel_emu_stack_5->GetXaxis()->SetTitleFont(42);
   lep1Pt_VV_lepSel_emu_stack_5->GetYaxis()->SetLabelFont(42);
   lep1Pt_VV_lepSel_emu_stack_5->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_VV_lepSel_emu_stack_5->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_VV_lepSel_emu_stack_5->GetYaxis()->SetTitleOffset(1);
   lep1Pt_VV_lepSel_emu_stack_5->GetYaxis()->SetTitleFont(42);
   lep1Pt_VV_lepSel_emu_stack_5->GetZaxis()->SetLabelFont(42);
   lep1Pt_VV_lepSel_emu_stack_5->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_VV_lepSel_emu_stack_5->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_VV_lepSel_emu_stack_5->GetZaxis()->SetTitleOffset(1);
   lep1Pt_VV_lepSel_emu_stack_5->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_lepSel_emu->Add(lep1Pt_VV_lepSel_emu_stack_5,"");
   
   TH1D *lep1Pt_SingleTop_lepSel_emu_stack_6 = new TH1D("lep1Pt_SingleTop_lepSel_emu_stack_6","lep1Pt_SingleTop_lepSel_emu",20,0,200);
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetBinContent(4,1582.775);
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetBinContent(5,2852.284);
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetBinContent(6,2392.923);
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetBinContent(7,1938.146);
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetBinContent(8,1487.865);
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetBinContent(9,1142.706);
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetBinContent(10,899.7789);
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetBinContent(11,707.2474);
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetBinContent(12,545.534);
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetBinContent(13,423.1583);
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetBinContent(14,337.1854);
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetBinContent(15,258.2933);
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetBinContent(16,205.8);
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetBinContent(17,164.362);
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetBinContent(18,127.1032);
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetBinContent(19,98.6407);
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetBinContent(20,97.71036);
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetBinContent(21,456.1432);
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetEntries(104082);
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetDirectory(0);

   ci = TColor::GetColor("#ff00ff");
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetLineColor(ci);
   lep1Pt_SingleTop_lepSel_emu_stack_6->SetLineWidth(0);
   lep1Pt_SingleTop_lepSel_emu_stack_6->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_SingleTop_lepSel_emu_stack_6->GetXaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_lepSel_emu_stack_6->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_SingleTop_lepSel_emu_stack_6->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_SingleTop_lepSel_emu_stack_6->GetXaxis()->SetTitleOffset(1);
   lep1Pt_SingleTop_lepSel_emu_stack_6->GetXaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_lepSel_emu_stack_6->GetYaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_lepSel_emu_stack_6->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_SingleTop_lepSel_emu_stack_6->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_SingleTop_lepSel_emu_stack_6->GetYaxis()->SetTitleOffset(1);
   lep1Pt_SingleTop_lepSel_emu_stack_6->GetYaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_lepSel_emu_stack_6->GetZaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_lepSel_emu_stack_6->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_SingleTop_lepSel_emu_stack_6->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_SingleTop_lepSel_emu_stack_6->GetZaxis()->SetTitleOffset(1);
   lep1Pt_SingleTop_lepSel_emu_stack_6->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_lepSel_emu->Add(lep1Pt_SingleTop_lepSel_emu_stack_6,"");
   
   TH1D *lep1Pt_tt_lepSel_emu_stack_7 = new TH1D("lep1Pt_tt_lepSel_emu_stack_7","lep1Pt_tt_lepSel_emu",20,0,200);
   lep1Pt_tt_lepSel_emu_stack_7->SetBinContent(4,14450.04);
   lep1Pt_tt_lepSel_emu_stack_7->SetBinContent(5,26054.83);
   lep1Pt_tt_lepSel_emu_stack_7->SetBinContent(6,21771.34);
   lep1Pt_tt_lepSel_emu_stack_7->SetBinContent(7,17356.97);
   lep1Pt_tt_lepSel_emu_stack_7->SetBinContent(8,13465.86);
   lep1Pt_tt_lepSel_emu_stack_7->SetBinContent(9,10045.96);
   lep1Pt_tt_lepSel_emu_stack_7->SetBinContent(10,7813.617);
   lep1Pt_tt_lepSel_emu_stack_7->SetBinContent(11,5810.379);
   lep1Pt_tt_lepSel_emu_stack_7->SetBinContent(12,4351.186);
   lep1Pt_tt_lepSel_emu_stack_7->SetBinContent(13,3273.184);
   lep1Pt_tt_lepSel_emu_stack_7->SetBinContent(14,2445.731);
   lep1Pt_tt_lepSel_emu_stack_7->SetBinContent(15,1789.896);
   lep1Pt_tt_lepSel_emu_stack_7->SetBinContent(16,1392.428);
   lep1Pt_tt_lepSel_emu_stack_7->SetBinContent(17,1051.812);
   lep1Pt_tt_lepSel_emu_stack_7->SetBinContent(18,789.3257);
   lep1Pt_tt_lepSel_emu_stack_7->SetBinContent(19,613.948);
   lep1Pt_tt_lepSel_emu_stack_7->SetBinContent(20,477.8817);
   lep1Pt_tt_lepSel_emu_stack_7->SetBinContent(21,1689.556);
   lep1Pt_tt_lepSel_emu_stack_7->SetEntries(423159);
   lep1Pt_tt_lepSel_emu_stack_7->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   lep1Pt_tt_lepSel_emu_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   lep1Pt_tt_lepSel_emu_stack_7->SetLineColor(ci);
   lep1Pt_tt_lepSel_emu_stack_7->SetLineWidth(0);
   lep1Pt_tt_lepSel_emu_stack_7->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_tt_lepSel_emu_stack_7->GetXaxis()->SetLabelFont(42);
   lep1Pt_tt_lepSel_emu_stack_7->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_tt_lepSel_emu_stack_7->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_tt_lepSel_emu_stack_7->GetXaxis()->SetTitleOffset(1);
   lep1Pt_tt_lepSel_emu_stack_7->GetXaxis()->SetTitleFont(42);
   lep1Pt_tt_lepSel_emu_stack_7->GetYaxis()->SetLabelFont(42);
   lep1Pt_tt_lepSel_emu_stack_7->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_tt_lepSel_emu_stack_7->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_tt_lepSel_emu_stack_7->GetYaxis()->SetTitleOffset(1);
   lep1Pt_tt_lepSel_emu_stack_7->GetYaxis()->SetTitleFont(42);
   lep1Pt_tt_lepSel_emu_stack_7->GetZaxis()->SetLabelFont(42);
   lep1Pt_tt_lepSel_emu_stack_7->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_tt_lepSel_emu_stack_7->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_tt_lepSel_emu_stack_7->GetZaxis()->SetTitleOffset(1);
   lep1Pt_tt_lepSel_emu_stack_7->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_lepSel_emu->Add(lep1Pt_tt_lepSel_emu_stack_7,"");
   
   TH1D *lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8 = new TH1D("lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8","lep1Pt_zPlusJetsMadgraph_lepSel_emu",20,0,200);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetBinContent(4,4613.37);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetBinContent(5,3253.146);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetBinContent(6,962.7452);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetBinContent(7,468.6213);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetBinContent(8,255.062);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetBinContent(9,155.8719);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetBinContent(10,124.3035);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetBinContent(11,68.5441);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetBinContent(12,61.83802);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetBinContent(13,47.67325);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetBinContent(14,25.56799);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetBinContent(15,17.51311);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetBinContent(16,9.965957);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetBinContent(17,16.41528);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetBinContent(18,4.604613);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetBinContent(19,6.408189);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetBinContent(20,5.06043);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetBinContent(21,17.09729);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetEntries(7407);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetLineColor(ci);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->SetLineWidth(0);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->GetXaxis()->SetLabelFont(42);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->GetXaxis()->SetTitleOffset(1);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->GetXaxis()->SetTitleFont(42);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->GetYaxis()->SetLabelFont(42);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->GetYaxis()->SetTitleOffset(1);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->GetYaxis()->SetTitleFont(42);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->GetZaxis()->SetLabelFont(42);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->GetZaxis()->SetTitleOffset(1);
   lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_lepSel_emu->Add(lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8,"");
   lep1Pt_SingleTop_lepSel_emu->Draw("");
   
   TH1D *lep1Pt_data_lepSel_emu__4 = new TH1D("lep1Pt_data_lepSel_emu__4","lep1Pt_data_lepSel_emu",20,0,200);
   lep1Pt_data_lepSel_emu__4->SetBinContent(4,23903);
   lep1Pt_data_lepSel_emu__4->SetBinContent(5,38104);
   lep1Pt_data_lepSel_emu__4->SetBinContent(6,29531);
   lep1Pt_data_lepSel_emu__4->SetBinContent(7,22816);
   lep1Pt_data_lepSel_emu__4->SetBinContent(8,17224);
   lep1Pt_data_lepSel_emu__4->SetBinContent(9,12973);
   lep1Pt_data_lepSel_emu__4->SetBinContent(10,9659);
   lep1Pt_data_lepSel_emu__4->SetBinContent(11,7097);
   lep1Pt_data_lepSel_emu__4->SetBinContent(12,5201);
   lep1Pt_data_lepSel_emu__4->SetBinContent(13,3900);
   lep1Pt_data_lepSel_emu__4->SetBinContent(14,2930);
   lep1Pt_data_lepSel_emu__4->SetBinContent(15,2297);
   lep1Pt_data_lepSel_emu__4->SetBinContent(16,1803);
   lep1Pt_data_lepSel_emu__4->SetBinContent(17,1267);
   lep1Pt_data_lepSel_emu__4->SetBinContent(18,1026);
   lep1Pt_data_lepSel_emu__4->SetBinContent(19,803);
   lep1Pt_data_lepSel_emu__4->SetBinContent(20,614);
   lep1Pt_data_lepSel_emu__4->SetBinContent(21,2352);
   lep1Pt_data_lepSel_emu__4->SetEntries(183500);
   lep1Pt_data_lepSel_emu__4->SetDirectory(0);
   lep1Pt_data_lepSel_emu__4->SetFillColor(1);
   lep1Pt_data_lepSel_emu__4->SetLineWidth(2);
   lep1Pt_data_lepSel_emu__4->SetLineColor(1); //
   lep1Pt_data_lepSel_emu__4->SetMarkerStyle(20);
   lep1Pt_data_lepSel_emu__4->SetMarkerSize(1.4);
   lep1Pt_data_lepSel_emu__4->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_data_lepSel_emu__4->GetXaxis()->SetLabelFont(42);
   lep1Pt_data_lepSel_emu__4->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_data_lepSel_emu__4->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_data_lepSel_emu__4->GetXaxis()->SetTitleOffset(1);
   lep1Pt_data_lepSel_emu__4->GetXaxis()->SetTitleFont(42);
   lep1Pt_data_lepSel_emu__4->GetYaxis()->SetLabelFont(42);
   lep1Pt_data_lepSel_emu__4->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_data_lepSel_emu__4->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_data_lepSel_emu__4->GetYaxis()->SetTitleOffset(1);
   lep1Pt_data_lepSel_emu__4->GetYaxis()->SetTitleFont(42);
   lep1Pt_data_lepSel_emu__4->GetZaxis()->SetLabelFont(42);
   lep1Pt_data_lepSel_emu__4->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_data_lepSel_emu__4->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_data_lepSel_emu__4->GetZaxis()->SetTitleOffset(1);
   lep1Pt_data_lepSel_emu__4->GetZaxis()->SetTitleFont(42);
   lep1Pt_data_lepSel_emu__4->Draw("e x0, same");
   
   TLegend *leg = new TLegend(0.78,0.42,0.98,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("lep1Pt_zPlusJetsMadgraph_lepSel_emu_stack_8","Z+jets (LO)","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_tt_lepSel_emu_stack_7","t#bar{t}","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_SingleTop_lepSel_emu_stack_6","Single top","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_VV_lepSel_emu_stack_5","VV","f");

   ci = TColor::GetColor("#ff9933");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_VVV_lepSel_emu_stack_4","VVV","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_wJets_lepSel_emu_stack_3","W+jets","f");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_ttV_lepSel_emu_stack_2","t#bar{t}V","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_tZq_lepSel_emu_stack_1","tZq","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_data_lepSel_emu","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.4);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.968,0.9429101,"35.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06792969);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.096,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.05419922);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16899,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.04119141);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *lep1Pt_SingleTop_lepSel_emu__5 = new TH1F("lep1Pt_SingleTop_lepSel_emu__5","Electron p_{T}",20,0,200);
   lep1Pt_SingleTop_lepSel_emu__5->SetMinimum(0);
   lep1Pt_SingleTop_lepSel_emu__5->SetMaximum(44010.12);
   lep1Pt_SingleTop_lepSel_emu__5->SetDirectory(0);
   lep1Pt_SingleTop_lepSel_emu__5->SetStats(0);
   lep1Pt_SingleTop_lepSel_emu__5->SetLineStyle(0);
   lep1Pt_SingleTop_lepSel_emu__5->SetLineWidth(0);
   lep1Pt_SingleTop_lepSel_emu__5->SetMarkerStyle(20);
   lep1Pt_SingleTop_lepSel_emu__5->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_SingleTop_lepSel_emu__5->GetXaxis()->SetNdivisions(506);
   lep1Pt_SingleTop_lepSel_emu__5->GetXaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_lepSel_emu__5->GetXaxis()->SetLabelOffset(999);
   lep1Pt_SingleTop_lepSel_emu__5->GetXaxis()->SetLabelSize(0.05);
   lep1Pt_SingleTop_lepSel_emu__5->GetXaxis()->SetTitleSize(0.08);
   lep1Pt_SingleTop_lepSel_emu__5->GetXaxis()->SetTitleOffset(1);
   lep1Pt_SingleTop_lepSel_emu__5->GetXaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_lepSel_emu__5->GetYaxis()->SetTitle("Events");
   lep1Pt_SingleTop_lepSel_emu__5->GetYaxis()->SetNdivisions(506);
   lep1Pt_SingleTop_lepSel_emu__5->GetYaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_lepSel_emu__5->GetYaxis()->SetLabelOffset(0.01);
   lep1Pt_SingleTop_lepSel_emu__5->GetYaxis()->SetLabelSize(0.062);
   lep1Pt_SingleTop_lepSel_emu__5->GetYaxis()->SetTitleSize(0.08);
   lep1Pt_SingleTop_lepSel_emu__5->GetYaxis()->SetTitleOffset(0.6336);
   lep1Pt_SingleTop_lepSel_emu__5->GetYaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_lepSel_emu__5->GetZaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_lepSel_emu__5->GetZaxis()->SetLabelOffset(0.007);
   lep1Pt_SingleTop_lepSel_emu__5->GetZaxis()->SetLabelSize(0.05);
   lep1Pt_SingleTop_lepSel_emu__5->GetZaxis()->SetTitleSize(0.08);
   lep1Pt_SingleTop_lepSel_emu__5->GetZaxis()->SetTitleOffset(1);
   lep1Pt_SingleTop_lepSel_emu__5->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_lepSel_emu__5->Draw("sameaxis");
   
   TPaveText *pt = new TPaveText(0.4029699,0.9203237,0.5970301,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Electron p_{T}");
   pt->Draw();
   canvy_1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: canvy_2
   TPad *canvy_2 = new TPad("canvy_2", "newpad2",0.01,0.01,0.99,0.322);
   canvy_2->Draw();
   canvy_2->cd();
   canvy_2->SetFillColor(0);
   canvy_2->SetBorderMode(0);
   canvy_2->SetGridy();

   canvy_2->SetLeftMargin( L/W );
   canvy_2->SetRightMargin( R/W );
   canvy_2->SetTopMargin( T/H );
   canvy_2->SetBottomMargin( B/H * 2.6 );
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   
   TH1D *lep1Pt_data_lepSel_emu__6 = new TH1D("lep1Pt_data_lepSel_emu__6","",20,0,200);
   lep1Pt_data_lepSel_emu__6->SetBinContent(4,0.9963004);
   lep1Pt_data_lepSel_emu__6->SetBinContent(5,1.016228);
   lep1Pt_data_lepSel_emu__6->SetBinContent(6,1.028624);
   lep1Pt_data_lepSel_emu__6->SetBinContent(7,1.020774);
   lep1Pt_data_lepSel_emu__6->SetBinContent(8,1.012809);
   lep1Pt_data_lepSel_emu__6->SetBinContent(9,1.033516);
   lep1Pt_data_lepSel_emu__6->SetBinContent(10,0.9818309);
   lep1Pt_data_lepSel_emu__6->SetBinContent(11,0.9748015);
   lep1Pt_data_lepSel_emu__6->SetBinContent(12,0.9527653);
   lep1Pt_data_lepSel_emu__6->SetBinContent(13,0.9386397);
   lep1Pt_data_lepSel_emu__6->SetBinContent(14,0.9391423);
   lep1Pt_data_lepSel_emu__6->SetBinContent(15,1.00633);
   lep1Pt_data_lepSel_emu__6->SetBinContent(16,1.005317);
   lep1Pt_data_lepSel_emu__6->SetBinContent(17,0.9212933);
   lep1Pt_data_lepSel_emu__6->SetBinContent(18,0.9988156);
   lep1Pt_data_lepSel_emu__6->SetBinContent(19,0.9897001);
   lep1Pt_data_lepSel_emu__6->SetBinContent(20,0.9522044);
   lep1Pt_data_lepSel_emu__6->SetBinContent(21,0.9126577);
   lep1Pt_data_lepSel_emu__6->SetBinError(4,0.00910494);
   lep1Pt_data_lepSel_emu__6->SetBinError(5,0.007392237);
   lep1Pt_data_lepSel_emu__6->SetBinError(6,0.008525472);
   lep1Pt_data_lepSel_emu__6->SetBinError(7,0.009606574);
   lep1Pt_data_lepSel_emu__6->SetBinError(8,0.01094868);
   lep1Pt_data_lepSel_emu__6->SetBinError(9,0.0129396);
   lep1Pt_data_lepSel_emu__6->SetBinError(10,0.01406384);
   lep1Pt_data_lepSel_emu__6->SetBinError(11,0.01626075);
   lep1Pt_data_lepSel_emu__6->SetBinError(12,0.01846152);
   lep1Pt_data_lepSel_emu__6->SetBinError(13,0.02092739);
   lep1Pt_data_lepSel_emu__6->SetBinError(14,0.02416031);
   lep1Pt_data_lepSel_emu__6->SetBinError(15,0.02974136);
   lep1Pt_data_lepSel_emu__6->SetBinError(16,0.03352713);
   lep1Pt_data_lepSel_emu__6->SetBinError(17,0.0358762);
   lep1Pt_data_lepSel_emu__6->SetBinError(18,0.04408573);
   lep1Pt_data_lepSel_emu__6->SetBinError(19,0.04926513);
   lep1Pt_data_lepSel_emu__6->SetBinError(20,0.05369189);
   lep1Pt_data_lepSel_emu__6->SetBinError(21,0.02602603);
   lep1Pt_data_lepSel_emu__6->SetMinimum(0.5);
   lep1Pt_data_lepSel_emu__6->SetMaximum(1.5);
   lep1Pt_data_lepSel_emu__6->SetEntries(21691.57);
   lep1Pt_data_lepSel_emu__6->SetDirectory(0);
   lep1Pt_data_lepSel_emu__6->SetStats(0);
   lep1Pt_data_lepSel_emu__6->SetFillColor(1);
   lep1Pt_data_lepSel_emu__6->SetLineWidth(2);
   lep1Pt_data_lepSel_emu__6->SetLineColor(1); //
   lep1Pt_data_lepSel_emu__6->SetMarkerStyle(20);
   lep1Pt_data_lepSel_emu__6->SetMarkerSize(1.6);
   lep1Pt_data_lepSel_emu__6->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_data_lepSel_emu__6->GetXaxis()->SetNdivisions(506);
   lep1Pt_data_lepSel_emu__6->GetXaxis()->SetLabelFont(42);
   lep1Pt_data_lepSel_emu__6->GetXaxis()->SetLabelOffset(0.013);
   lep1Pt_data_lepSel_emu__6->GetXaxis()->SetLabelSize(0.13);
   lep1Pt_data_lepSel_emu__6->GetXaxis()->SetTitleSize(0.13);
   lep1Pt_data_lepSel_emu__6->GetXaxis()->SetTitleOffset(1);
   lep1Pt_data_lepSel_emu__6->GetXaxis()->SetTitleFont(42);
   lep1Pt_data_lepSel_emu__6->GetYaxis()->SetTitle("Data/MC");
   lep1Pt_data_lepSel_emu__6->GetYaxis()->CenterTitle(true);
   lep1Pt_data_lepSel_emu__6->GetYaxis()->SetNdivisions(506);
   lep1Pt_data_lepSel_emu__6->GetYaxis()->SetLabelFont(42);
   lep1Pt_data_lepSel_emu__6->GetYaxis()->SetLabelOffset(0.01);
   lep1Pt_data_lepSel_emu__6->GetYaxis()->SetLabelSize(0.12);
   lep1Pt_data_lepSel_emu__6->GetYaxis()->SetTitleSize(0.16);
   lep1Pt_data_lepSel_emu__6->GetYaxis()->SetTitleOffset(0.3);
   lep1Pt_data_lepSel_emu__6->GetYaxis()->SetTitleFont(42);
   lep1Pt_data_lepSel_emu__6->GetZaxis()->SetLabelFont(42);
   lep1Pt_data_lepSel_emu__6->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_data_lepSel_emu__6->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_data_lepSel_emu__6->GetZaxis()->SetTitleOffset(1);
   lep1Pt_data_lepSel_emu__6->GetZaxis()->SetTitleFont(42);
   lep1Pt_data_lepSel_emu__6->Draw("e x0, SCAT");
   canvy_2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
//   c1->SetSelected(lep1Pt_data_lepSel_emu);
   c1->SaveAs("lep1Pt_lepSel.pdf");
}
