void lep1Pt_SingleTop_wMass()
{
//=========Macro generated from canvas: lep1Pt_SingleTop_wMass/lep1Pt_SingleTop_wMass
//=========  (Wed Aug 21 20:26:38 2019) by ROOT version 6.18/00

   // Set up cavas
   int W = 1280;
   int H = 1024;
   int H_ref = 925;
   int W_ref = 1024;

   // references for T, B, L, R
   float T = 0.08*H_ref;
   float B = 0.12*H_ref;
   float L = 0.12*W_ref;
   float R = 0.04*W_ref;

   TCanvas *c1 = new TCanvas("c1","c1",50,50,W,H);
   c1->cd();
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetLeftMargin( L/W );
   c1->SetRightMargin( R/W );
   c1->SetTopMargin( T/H );
   c1->SetBottomMargin( B/H );
   c1->SetTickx(0);
   c1->SetTicky(0);

// ------------>Primitives in pad: canvy_1
   TPad *canvy_1 = new TPad("canvy_1", "newpad",0.01,0.315,0.99,0.99);
   canvy_1->Draw();
   canvy_1->cd();
   canvy_1->SetFillColor(0);
   canvy_1->SetBorderMode(0);

   canvy_1->SetLeftMargin( L/W );
   canvy_1->SetRightMargin( R/W );
   canvy_1->SetTopMargin( T/H );
   canvy_1->SetBottomMargin( B/H * 0.3 );

   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);
   
   THStack *lep1Pt_SingleTop_wMass_emu = new THStack();
   lep1Pt_SingleTop_wMass_emu->SetName("lep1Pt_SingleTop_wMass_emu");
   lep1Pt_SingleTop_wMass_emu->SetTitle(";Electron p_{T} (GeV);Events");
   lep1Pt_SingleTop_wMass_emu->SetMaximum(771.1);
   
   TH1F *lep1Pt_SingleTop_wMass_emu_stack_2 = new TH1F("lep1Pt_SingleTop_wMass_emu_stack_2","Electron p_{T}",20,0,200);
   lep1Pt_SingleTop_wMass_emu_stack_2->SetMinimum(0);
   lep1Pt_SingleTop_wMass_emu_stack_2->SetMaximum(809.655);
   lep1Pt_SingleTop_wMass_emu_stack_2->SetDirectory(0);
   lep1Pt_SingleTop_wMass_emu_stack_2->SetStats(0);
   lep1Pt_SingleTop_wMass_emu_stack_2->SetLineStyle(0);
   lep1Pt_SingleTop_wMass_emu_stack_2->SetLineWidth(0);
   lep1Pt_SingleTop_wMass_emu_stack_2->SetMarkerStyle(20);
   lep1Pt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetNdivisions(506);
   lep1Pt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetLabelOffset(999);
   lep1Pt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetLabelSize(0.05);
   lep1Pt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetTitleSize(0.08);
   lep1Pt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   lep1Pt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetTitle("Events");
   lep1Pt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetNdivisions(506);
   lep1Pt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetLabelOffset(0.01);
   lep1Pt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetLabelSize(0.062);
   lep1Pt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetTitleSize(0.08);
   lep1Pt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetTitleOffset(0.6336);
   lep1Pt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_wMass_emu_stack_2->GetZaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_wMass_emu_stack_2->GetZaxis()->SetLabelOffset(0.007);
   lep1Pt_SingleTop_wMass_emu_stack_2->GetZaxis()->SetLabelSize(0.05);
   lep1Pt_SingleTop_wMass_emu_stack_2->GetZaxis()->SetTitleSize(0.08);
   lep1Pt_SingleTop_wMass_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   lep1Pt_SingleTop_wMass_emu_stack_2->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_wMass_emu->SetHistogram(lep1Pt_SingleTop_wMass_emu_stack_2);
   
   
   TH1D *lep1Pt_tZq_wMass_emu_stack_1 = new TH1D("lep1Pt_tZq_wMass_emu_stack_1","lep1Pt_tZq_wMass_emu",20,0,200);
   lep1Pt_tZq_wMass_emu_stack_1->SetBinContent(4,0.04504407);
   lep1Pt_tZq_wMass_emu_stack_1->SetBinContent(5,0.110999);
   lep1Pt_tZq_wMass_emu_stack_1->SetBinContent(6,0.06151527);
   lep1Pt_tZq_wMass_emu_stack_1->SetBinContent(7,0.03203352);
   lep1Pt_tZq_wMass_emu_stack_1->SetBinContent(8,0.02673006);
   lep1Pt_tZq_wMass_emu_stack_1->SetBinContent(9,0.02692305);
   lep1Pt_tZq_wMass_emu_stack_1->SetBinContent(10,0.01526526);
   lep1Pt_tZq_wMass_emu_stack_1->SetBinContent(11,0.01257665);
   lep1Pt_tZq_wMass_emu_stack_1->SetBinContent(12,0.002429684);
   lep1Pt_tZq_wMass_emu_stack_1->SetBinContent(13,0.003296386);
   lep1Pt_tZq_wMass_emu_stack_1->SetBinContent(14,0.0003897316);
   lep1Pt_tZq_wMass_emu_stack_1->SetBinContent(15,0.003672921);
   lep1Pt_tZq_wMass_emu_stack_1->SetBinContent(16,0.002402416);
   lep1Pt_tZq_wMass_emu_stack_1->SetBinContent(17,-0.00145224);
   lep1Pt_tZq_wMass_emu_stack_1->SetBinContent(18,0.002469808);
   lep1Pt_tZq_wMass_emu_stack_1->SetBinContent(19,-0.001563871);
   lep1Pt_tZq_wMass_emu_stack_1->SetBinContent(20,0.000284819);
   lep1Pt_tZq_wMass_emu_stack_1->SetBinContent(21,0.001391907);
   lep1Pt_tZq_wMass_emu_stack_1->SetEntries(2170);
   lep1Pt_tZq_wMass_emu_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ffff00");
   lep1Pt_tZq_wMass_emu_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   lep1Pt_tZq_wMass_emu_stack_1->SetLineColor(ci);
   lep1Pt_tZq_wMass_emu_stack_1->SetLineWidth(0);
   lep1Pt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_tZq_wMass_emu_stack_1->GetXaxis()->SetLabelFont(42);
   lep1Pt_tZq_wMass_emu_stack_1->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   lep1Pt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleFont(42);
   lep1Pt_tZq_wMass_emu_stack_1->GetYaxis()->SetLabelFont(42);
   lep1Pt_tZq_wMass_emu_stack_1->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleOffset(1);
   lep1Pt_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleFont(42);
   lep1Pt_tZq_wMass_emu_stack_1->GetZaxis()->SetLabelFont(42);
   lep1Pt_tZq_wMass_emu_stack_1->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   lep1Pt_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_wMass_emu->Add(lep1Pt_tZq_wMass_emu_stack_1,"");
   
   TH1D *lep1Pt_ttV_wMass_emu_stack_2 = new TH1D("lep1Pt_ttV_wMass_emu_stack_2","lep1Pt_ttV_wMass_emu",20,0,200);
   lep1Pt_ttV_wMass_emu_stack_2->SetBinContent(4,3.763958);
   lep1Pt_ttV_wMass_emu_stack_2->SetBinContent(5,6.425266);
   lep1Pt_ttV_wMass_emu_stack_2->SetBinContent(6,4.84887);
   lep1Pt_ttV_wMass_emu_stack_2->SetBinContent(7,3.451754);
   lep1Pt_ttV_wMass_emu_stack_2->SetBinContent(8,2.928847);
   lep1Pt_ttV_wMass_emu_stack_2->SetBinContent(9,2.41016);
   lep1Pt_ttV_wMass_emu_stack_2->SetBinContent(10,1.184744);
   lep1Pt_ttV_wMass_emu_stack_2->SetBinContent(11,0.9219532);
   lep1Pt_ttV_wMass_emu_stack_2->SetBinContent(12,0.7710593);
   lep1Pt_ttV_wMass_emu_stack_2->SetBinContent(13,0.3354292);
   lep1Pt_ttV_wMass_emu_stack_2->SetBinContent(14,0.1020785);
   lep1Pt_ttV_wMass_emu_stack_2->SetBinContent(15,0.1642051);
   lep1Pt_ttV_wMass_emu_stack_2->SetBinContent(16,0.1895608);
   lep1Pt_ttV_wMass_emu_stack_2->SetBinContent(17,0.09989877);
   lep1Pt_ttV_wMass_emu_stack_2->SetBinContent(18,0.04485253);
   lep1Pt_ttV_wMass_emu_stack_2->SetBinContent(19,0.1004976);
   lep1Pt_ttV_wMass_emu_stack_2->SetBinContent(20,0.02425501);
   lep1Pt_ttV_wMass_emu_stack_2->SetBinContent(21,0.111781);
   lep1Pt_ttV_wMass_emu_stack_2->SetEntries(14144);
   lep1Pt_ttV_wMass_emu_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#00ff00");
   lep1Pt_ttV_wMass_emu_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   lep1Pt_ttV_wMass_emu_stack_2->SetLineColor(ci);
   lep1Pt_ttV_wMass_emu_stack_2->SetLineWidth(0);
   lep1Pt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_ttV_wMass_emu_stack_2->GetXaxis()->SetLabelFont(42);
   lep1Pt_ttV_wMass_emu_stack_2->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   lep1Pt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleFont(42);
   lep1Pt_ttV_wMass_emu_stack_2->GetYaxis()->SetLabelFont(42);
   lep1Pt_ttV_wMass_emu_stack_2->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleOffset(1);
   lep1Pt_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleFont(42);
   lep1Pt_ttV_wMass_emu_stack_2->GetZaxis()->SetLabelFont(42);
   lep1Pt_ttV_wMass_emu_stack_2->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   lep1Pt_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_wMass_emu->Add(lep1Pt_ttV_wMass_emu_stack_2,"");
   
   TH1D *lep1Pt_wJets_wMass_emu_stack_3 = new TH1D("lep1Pt_wJets_wMass_emu_stack_3","lep1Pt_wJets_wMass_emu",20,0,200);
   lep1Pt_wJets_wMass_emu_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   lep1Pt_wJets_wMass_emu_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#cccccc");
   lep1Pt_wJets_wMass_emu_stack_3->SetLineColor(ci);
   lep1Pt_wJets_wMass_emu_stack_3->SetLineWidth(0);
   lep1Pt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_wJets_wMass_emu_stack_3->GetXaxis()->SetLabelFont(42);
   lep1Pt_wJets_wMass_emu_stack_3->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   lep1Pt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleFont(42);
   lep1Pt_wJets_wMass_emu_stack_3->GetYaxis()->SetLabelFont(42);
   lep1Pt_wJets_wMass_emu_stack_3->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleOffset(1);
   lep1Pt_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleFont(42);
   lep1Pt_wJets_wMass_emu_stack_3->GetZaxis()->SetLabelFont(42);
   lep1Pt_wJets_wMass_emu_stack_3->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   lep1Pt_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_wMass_emu->Add(lep1Pt_wJets_wMass_emu_stack_3,"");
   
   TH1D *lep1Pt_VVV_wMass_emu_stack_4 = new TH1D("lep1Pt_VVV_wMass_emu_stack_4","lep1Pt_VVV_wMass_emu",20,0,200);
   lep1Pt_VVV_wMass_emu_stack_4->SetBinContent(4,0.05752475);
   lep1Pt_VVV_wMass_emu_stack_4->SetBinContent(6,0.02946448);
   lep1Pt_VVV_wMass_emu_stack_4->SetBinContent(7,0.003420748);
   lep1Pt_VVV_wMass_emu_stack_4->SetBinContent(8,0.033447);
   lep1Pt_VVV_wMass_emu_stack_4->SetBinContent(10,0.06581599);
   lep1Pt_VVV_wMass_emu_stack_4->SetBinContent(12,0.03458785);
   lep1Pt_VVV_wMass_emu_stack_4->SetEntries(9);
   lep1Pt_VVV_wMass_emu_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#00ffff");
   lep1Pt_VVV_wMass_emu_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   lep1Pt_VVV_wMass_emu_stack_4->SetLineColor(ci);
   lep1Pt_VVV_wMass_emu_stack_4->SetLineWidth(0);
   lep1Pt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_VVV_wMass_emu_stack_4->GetXaxis()->SetLabelFont(42);
   lep1Pt_VVV_wMass_emu_stack_4->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   lep1Pt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleFont(42);
   lep1Pt_VVV_wMass_emu_stack_4->GetYaxis()->SetLabelFont(42);
   lep1Pt_VVV_wMass_emu_stack_4->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleOffset(1);
   lep1Pt_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleFont(42);
   lep1Pt_VVV_wMass_emu_stack_4->GetZaxis()->SetLabelFont(42);
   lep1Pt_VVV_wMass_emu_stack_4->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   lep1Pt_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_wMass_emu->Add(lep1Pt_VVV_wMass_emu_stack_4,"");
   
   TH1D *lep1Pt_VV_wMass_emu_stack_5 = new TH1D("lep1Pt_VV_wMass_emu_stack_5","lep1Pt_VV_wMass_emu",20,0,200);
   lep1Pt_VV_wMass_emu_stack_5->SetBinContent(4,0.6482387);
   lep1Pt_VV_wMass_emu_stack_5->SetBinContent(5,0.8803587);
   lep1Pt_VV_wMass_emu_stack_5->SetBinContent(6,0.1507232);
   lep1Pt_VV_wMass_emu_stack_5->SetBinContent(7,0.01180418);
   lep1Pt_VV_wMass_emu_stack_5->SetBinContent(9,0.01797672);
   lep1Pt_VV_wMass_emu_stack_5->SetBinContent(10,0.1531139);
   lep1Pt_VV_wMass_emu_stack_5->SetBinContent(11,0.2142568);
   lep1Pt_VV_wMass_emu_stack_5->SetBinContent(12,0.1728033);
   lep1Pt_VV_wMass_emu_stack_5->SetBinContent(14,0.00323126);
   lep1Pt_VV_wMass_emu_stack_5->SetBinContent(15,-0.006176281);
   lep1Pt_VV_wMass_emu_stack_5->SetBinContent(16,0.006824238);
   lep1Pt_VV_wMass_emu_stack_5->SetBinContent(18,0.01182891);
   lep1Pt_VV_wMass_emu_stack_5->SetBinContent(19,-0.01229277);
   lep1Pt_VV_wMass_emu_stack_5->SetBinContent(20,0.2220164);
   lep1Pt_VV_wMass_emu_stack_5->SetBinContent(21,0.004911191);
   lep1Pt_VV_wMass_emu_stack_5->SetEntries(45);
   lep1Pt_VV_wMass_emu_stack_5->SetDirectory(0);

   ci = TColor::GetColor("#ff9933");
   lep1Pt_VV_wMass_emu_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#ff9933");
   lep1Pt_VV_wMass_emu_stack_5->SetLineColor(ci);
   lep1Pt_VV_wMass_emu_stack_5->SetLineWidth(0);
   lep1Pt_VV_wMass_emu_stack_5->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_VV_wMass_emu_stack_5->GetXaxis()->SetLabelFont(42);
   lep1Pt_VV_wMass_emu_stack_5->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_VV_wMass_emu_stack_5->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_VV_wMass_emu_stack_5->GetXaxis()->SetTitleOffset(1);
   lep1Pt_VV_wMass_emu_stack_5->GetXaxis()->SetTitleFont(42);
   lep1Pt_VV_wMass_emu_stack_5->GetYaxis()->SetLabelFont(42);
   lep1Pt_VV_wMass_emu_stack_5->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_VV_wMass_emu_stack_5->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_VV_wMass_emu_stack_5->GetYaxis()->SetTitleOffset(1);
   lep1Pt_VV_wMass_emu_stack_5->GetYaxis()->SetTitleFont(42);
   lep1Pt_VV_wMass_emu_stack_5->GetZaxis()->SetLabelFont(42);
   lep1Pt_VV_wMass_emu_stack_5->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_VV_wMass_emu_stack_5->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_VV_wMass_emu_stack_5->GetZaxis()->SetTitleOffset(1);
   lep1Pt_VV_wMass_emu_stack_5->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_wMass_emu->Add(lep1Pt_VV_wMass_emu_stack_5,"");
   
   TH1D *lep1Pt_SingleTop_wMass_emu_stack_6 = new TH1D("lep1Pt_SingleTop_wMass_emu_stack_6","lep1Pt_SingleTop_wMass_emu",20,0,200);
   lep1Pt_SingleTop_wMass_emu_stack_6->SetBinContent(4,13.33501);
   lep1Pt_SingleTop_wMass_emu_stack_6->SetBinContent(5,22.8453);
   lep1Pt_SingleTop_wMass_emu_stack_6->SetBinContent(6,15.21582);
   lep1Pt_SingleTop_wMass_emu_stack_6->SetBinContent(7,15.18181);
   lep1Pt_SingleTop_wMass_emu_stack_6->SetBinContent(8,10.32474);
   lep1Pt_SingleTop_wMass_emu_stack_6->SetBinContent(9,8.727368);
   lep1Pt_SingleTop_wMass_emu_stack_6->SetBinContent(10,3.952306);
   lep1Pt_SingleTop_wMass_emu_stack_6->SetBinContent(11,4.433364);
   lep1Pt_SingleTop_wMass_emu_stack_6->SetBinContent(12,2.929705);
   lep1Pt_SingleTop_wMass_emu_stack_6->SetBinContent(13,2.376966);
   lep1Pt_SingleTop_wMass_emu_stack_6->SetBinContent(14,1.341827);
   lep1Pt_SingleTop_wMass_emu_stack_6->SetBinContent(15,1.282479);
   lep1Pt_SingleTop_wMass_emu_stack_6->SetBinContent(16,0.2175237);
   lep1Pt_SingleTop_wMass_emu_stack_6->SetBinContent(17,0.258519);
   lep1Pt_SingleTop_wMass_emu_stack_6->SetBinContent(18,0.170602);
   lep1Pt_SingleTop_wMass_emu_stack_6->SetBinContent(20,0.5603959);
   lep1Pt_SingleTop_wMass_emu_stack_6->SetBinContent(21,1.580393);
   lep1Pt_SingleTop_wMass_emu_stack_6->SetEntries(1034);
   lep1Pt_SingleTop_wMass_emu_stack_6->SetDirectory(0);

   ci = TColor::GetColor("#ff00ff");
   lep1Pt_SingleTop_wMass_emu_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   lep1Pt_SingleTop_wMass_emu_stack_6->SetLineColor(ci);
   lep1Pt_SingleTop_wMass_emu_stack_6->SetLineWidth(0);
   lep1Pt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleOffset(1);
   lep1Pt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleOffset(1);
   lep1Pt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleOffset(1);
   lep1Pt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_wMass_emu->Add(lep1Pt_SingleTop_wMass_emu_stack_6,"");
   
   TH1D *lep1Pt_tt_wMass_emu_stack_7 = new TH1D("lep1Pt_tt_wMass_emu_stack_7","lep1Pt_tt_wMass_emu",20,0,200);
   lep1Pt_tt_wMass_emu_stack_7->SetBinContent(4,355.6934);
   lep1Pt_tt_wMass_emu_stack_7->SetBinContent(5,613.123);
   lep1Pt_tt_wMass_emu_stack_7->SetBinContent(6,480.446);
   lep1Pt_tt_wMass_emu_stack_7->SetBinContent(7,322.3457);
   lep1Pt_tt_wMass_emu_stack_7->SetBinContent(8,212.1275);
   lep1Pt_tt_wMass_emu_stack_7->SetBinContent(9,144.4706);
   lep1Pt_tt_wMass_emu_stack_7->SetBinContent(10,103.8837);
   lep1Pt_tt_wMass_emu_stack_7->SetBinContent(11,57.5247);
   lep1Pt_tt_wMass_emu_stack_7->SetBinContent(12,38.10656);
   lep1Pt_tt_wMass_emu_stack_7->SetBinContent(13,25.53893);
   lep1Pt_tt_wMass_emu_stack_7->SetBinContent(14,15.94486);
   lep1Pt_tt_wMass_emu_stack_7->SetBinContent(15,10.03701);
   lep1Pt_tt_wMass_emu_stack_7->SetBinContent(16,5.40664);
   lep1Pt_tt_wMass_emu_stack_7->SetBinContent(17,3.543002);
   lep1Pt_tt_wMass_emu_stack_7->SetBinContent(18,2.932116);
   lep1Pt_tt_wMass_emu_stack_7->SetBinContent(19,3.22536);
   lep1Pt_tt_wMass_emu_stack_7->SetBinContent(20,1.342974);
   lep1Pt_tt_wMass_emu_stack_7->SetBinContent(21,5.086953);
   lep1Pt_tt_wMass_emu_stack_7->SetEntries(7802);
   lep1Pt_tt_wMass_emu_stack_7->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   lep1Pt_tt_wMass_emu_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   lep1Pt_tt_wMass_emu_stack_7->SetLineColor(ci);
   lep1Pt_tt_wMass_emu_stack_7->SetLineWidth(0);
   lep1Pt_tt_wMass_emu_stack_7->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_tt_wMass_emu_stack_7->GetXaxis()->SetLabelFont(42);
   lep1Pt_tt_wMass_emu_stack_7->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_tt_wMass_emu_stack_7->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_tt_wMass_emu_stack_7->GetXaxis()->SetTitleOffset(1);
   lep1Pt_tt_wMass_emu_stack_7->GetXaxis()->SetTitleFont(42);
   lep1Pt_tt_wMass_emu_stack_7->GetYaxis()->SetLabelFont(42);
   lep1Pt_tt_wMass_emu_stack_7->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_tt_wMass_emu_stack_7->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_tt_wMass_emu_stack_7->GetYaxis()->SetTitleOffset(1);
   lep1Pt_tt_wMass_emu_stack_7->GetYaxis()->SetTitleFont(42);
   lep1Pt_tt_wMass_emu_stack_7->GetZaxis()->SetLabelFont(42);
   lep1Pt_tt_wMass_emu_stack_7->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_tt_wMass_emu_stack_7->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_tt_wMass_emu_stack_7->GetZaxis()->SetTitleOffset(1);
   lep1Pt_tt_wMass_emu_stack_7->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_wMass_emu->Add(lep1Pt_tt_wMass_emu_stack_7,"");
   
   TH1D *lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8 = new TH1D("lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8","lep1Pt_zPlusJetsMadgraph_wMass_emu",20,0,200);
   lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8->SetLineColor(ci);
   lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8->SetLineWidth(0);
   lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetLabelFont(42);
   lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleOffset(1);
   lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleFont(42);
   lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetLabelFont(42);
   lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleOffset(1);
   lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleFont(42);
   lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetLabelFont(42);
   lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleOffset(1);
   lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_wMass_emu->Add(lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8,"");
   lep1Pt_SingleTop_wMass_emu->Draw("");
   
   TH1D *lep1Pt_data_wMass_emu__4 = new TH1D("lep1Pt_data_wMass_emu__4","lep1Pt_data_wMass_emu",20,0,200);
   lep1Pt_data_wMass_emu__4->SetBinContent(4,373);
   lep1Pt_data_wMass_emu__4->SetBinContent(5,701);
   lep1Pt_data_wMass_emu__4->SetBinContent(6,532);
   lep1Pt_data_wMass_emu__4->SetBinContent(7,378);
   lep1Pt_data_wMass_emu__4->SetBinContent(8,249);
   lep1Pt_data_wMass_emu__4->SetBinContent(9,155);
   lep1Pt_data_wMass_emu__4->SetBinContent(10,104);
   lep1Pt_data_wMass_emu__4->SetBinContent(11,51);
   lep1Pt_data_wMass_emu__4->SetBinContent(12,45);
   lep1Pt_data_wMass_emu__4->SetBinContent(13,28);
   lep1Pt_data_wMass_emu__4->SetBinContent(14,12);
   lep1Pt_data_wMass_emu__4->SetBinContent(15,13);
   lep1Pt_data_wMass_emu__4->SetBinContent(16,13);
   lep1Pt_data_wMass_emu__4->SetBinContent(17,3);
   lep1Pt_data_wMass_emu__4->SetBinContent(18,6);
   lep1Pt_data_wMass_emu__4->SetBinContent(20,3);
   lep1Pt_data_wMass_emu__4->SetBinContent(21,2);
   lep1Pt_data_wMass_emu__4->SetEntries(2668);
   lep1Pt_data_wMass_emu__4->SetDirectory(0);
   lep1Pt_data_wMass_emu__4->SetFillColor(1);
   lep1Pt_data_wMass_emu__4->SetLineWidth(2);
   lep1Pt_data_wMass_emu__4->SetLineColor(1); //
   lep1Pt_data_wMass_emu__4->SetMarkerStyle(20);
   lep1Pt_data_wMass_emu__4->SetMarkerSize(1.4);
   lep1Pt_data_wMass_emu__4->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_data_wMass_emu__4->GetXaxis()->SetLabelFont(42);
   lep1Pt_data_wMass_emu__4->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_data_wMass_emu__4->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_data_wMass_emu__4->GetXaxis()->SetTitleOffset(1);
   lep1Pt_data_wMass_emu__4->GetXaxis()->SetTitleFont(42);
   lep1Pt_data_wMass_emu__4->GetYaxis()->SetLabelFont(42);
   lep1Pt_data_wMass_emu__4->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_data_wMass_emu__4->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_data_wMass_emu__4->GetYaxis()->SetTitleOffset(1);
   lep1Pt_data_wMass_emu__4->GetYaxis()->SetTitleFont(42);
   lep1Pt_data_wMass_emu__4->GetZaxis()->SetLabelFont(42);
   lep1Pt_data_wMass_emu__4->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_data_wMass_emu__4->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_data_wMass_emu__4->GetZaxis()->SetTitleOffset(1);
   lep1Pt_data_wMass_emu__4->GetZaxis()->SetTitleFont(42);
   lep1Pt_data_wMass_emu__4->Draw("e x0, same");
   
   TLegend *leg = new TLegend(0.78,0.42,0.98,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("lep1Pt_zPlusJetsMadgraph_wMass_emu_stack_8","Z+jets (LO)","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_tt_wMass_emu_stack_7","t#bar{t}","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_SingleTop_wMass_emu_stack_6","Single top","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_VV_wMass_emu_stack_5","VV","f");

   ci = TColor::GetColor("#ff9933");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_VVV_wMass_emu_stack_4","VVV","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_wJets_wMass_emu_stack_3","W+jets","f");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_ttV_wMass_emu_stack_2","t#bar{t}V","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_tZq_wMass_emu_stack_1","tZq","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_data_wMass_emu","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.4);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.968,0.9429101,"35.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06792969);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.096,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.05419922);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16899,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.04119141);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *lep1Pt_SingleTop_wMass_emu__5 = new TH1F("lep1Pt_SingleTop_wMass_emu__5","Electron p_{T}",20,0,200);
   lep1Pt_SingleTop_wMass_emu__5->SetMinimum(0);
   lep1Pt_SingleTop_wMass_emu__5->SetMaximum(809.655);
   lep1Pt_SingleTop_wMass_emu__5->SetDirectory(0);
   lep1Pt_SingleTop_wMass_emu__5->SetStats(0);
   lep1Pt_SingleTop_wMass_emu__5->SetLineStyle(0);
   lep1Pt_SingleTop_wMass_emu__5->SetLineWidth(0);
   lep1Pt_SingleTop_wMass_emu__5->SetMarkerStyle(20);
   lep1Pt_SingleTop_wMass_emu__5->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_SingleTop_wMass_emu__5->GetXaxis()->SetNdivisions(506);
   lep1Pt_SingleTop_wMass_emu__5->GetXaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_wMass_emu__5->GetXaxis()->SetLabelOffset(999);
   lep1Pt_SingleTop_wMass_emu__5->GetXaxis()->SetLabelSize(0.05);
   lep1Pt_SingleTop_wMass_emu__5->GetXaxis()->SetTitleSize(0.08);
   lep1Pt_SingleTop_wMass_emu__5->GetXaxis()->SetTitleOffset(1);
   lep1Pt_SingleTop_wMass_emu__5->GetXaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_wMass_emu__5->GetYaxis()->SetTitle("Events");
   lep1Pt_SingleTop_wMass_emu__5->GetYaxis()->SetNdivisions(506);
   lep1Pt_SingleTop_wMass_emu__5->GetYaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_wMass_emu__5->GetYaxis()->SetLabelOffset(0.01);
   lep1Pt_SingleTop_wMass_emu__5->GetYaxis()->SetLabelSize(0.062);
   lep1Pt_SingleTop_wMass_emu__5->GetYaxis()->SetTitleSize(0.08);
   lep1Pt_SingleTop_wMass_emu__5->GetYaxis()->SetTitleOffset(0.6336);
   lep1Pt_SingleTop_wMass_emu__5->GetYaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_wMass_emu__5->GetZaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_wMass_emu__5->GetZaxis()->SetLabelOffset(0.007);
   lep1Pt_SingleTop_wMass_emu__5->GetZaxis()->SetLabelSize(0.05);
   lep1Pt_SingleTop_wMass_emu__5->GetZaxis()->SetTitleSize(0.08);
   lep1Pt_SingleTop_wMass_emu__5->GetZaxis()->SetTitleOffset(1);
   lep1Pt_SingleTop_wMass_emu__5->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_wMass_emu__5->Draw("sameaxis");
   
   TPaveText *pt = new TPaveText(0.4029699,0.9203237,0.5970301,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Electron p_{T}");
   pt->Draw();
   canvy_1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: canvy_2
   TPad *canvy_2 = new TPad("canvy_2", "newpad2",0.01,0.01,0.99,0.322);
   canvy_2->Draw();
   canvy_2->cd();
   canvy_2->SetFillColor(0);
   canvy_2->SetBorderMode(0);
   canvy_2->SetGridy();

   canvy_2->SetLeftMargin( L/W );
   canvy_2->SetRightMargin( R/W );
   canvy_2->SetTopMargin( T/H );
   canvy_2->SetBottomMargin( B/H * 2.6 );
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   
   TH1D *lep1Pt_data_wMass_emu__6 = new TH1D("lep1Pt_data_wMass_emu__6","",20,0,200);
   lep1Pt_data_wMass_emu__6->SetBinContent(4,0.998546);
   lep1Pt_data_wMass_emu__6->SetBinContent(5,1.08955);
   lep1Pt_data_wMass_emu__6->SetBinContent(6,1.062401);
   lep1Pt_data_wMass_emu__6->SetBinContent(7,1.108418);
   lep1Pt_data_wMass_emu__6->SetBinContent(8,1.104501);
   lep1Pt_data_wMass_emu__6->SetBinContent(9,0.9958046);
   lep1Pt_data_wMass_emu__6->SetBinContent(10,0.9519018);
   lep1Pt_data_wMass_emu__6->SetBinContent(11,0.8081532);
   lep1Pt_data_wMass_emu__6->SetBinContent(12,1.070991);
   lep1Pt_data_wMass_emu__6->SetBinContent(13,0.9909884);
   lep1Pt_data_wMass_emu__6->SetBinContent(14,0.6899569);
   lep1Pt_data_wMass_emu__6->SetBinContent(15,1.132287);
   lep1Pt_data_wMass_emu__6->SetBinContent(16,2.232545);
   lep1Pt_data_wMass_emu__6->SetBinContent(17,0.7692372);
   lep1Pt_data_wMass_emu__6->SetBinContent(18,1.897612);
   lep1Pt_data_wMass_emu__6->SetBinContent(20,1.395397);
   lep1Pt_data_wMass_emu__6->SetBinContent(21,0.2947492);
   lep1Pt_data_wMass_emu__6->SetBinError(4,0.07309215);
   lep1Pt_data_wMass_emu__6->SetBinError(5,0.05948596);
   lep1Pt_data_wMass_emu__6->SetBinError(6,0.06614841);
   lep1Pt_data_wMass_emu__6->SetBinError(7,0.08278203);
   lep1Pt_data_wMass_emu__6->SetBinError(8,0.1015409);
   lep1Pt_data_wMass_emu__6->SetBinError(9,0.1129971);
   lep1Pt_data_wMass_emu__6->SetBinError(10,0.1304081);
   lep1Pt_data_wMass_emu__6->SetBinError(11,0.152169);
   lep1Pt_data_wMass_emu__6->SetBinError(12,0.2297571);
   lep1Pt_data_wMass_emu__6->SetBinError(13,0.2642554);
   lep1Pt_data_wMass_emu__6->SetBinError(14,0.2589221);
   lep1Pt_data_wMass_emu__6->SetBinError(15,0.4585719);
   lep1Pt_data_wMass_emu__6->SetBinError(16,1.113271);
   lep1Pt_data_wMass_emu__6->SetBinError(17,0.590735);
   lep1Pt_data_wMass_emu__6->SetBinError(18,1.318718);
   lep1Pt_data_wMass_emu__6->SetBinError(20,1.246884);
   lep1Pt_data_wMass_emu__6->SetBinError(21,0.237154);
   lep1Pt_data_wMass_emu__6->SetMinimum(0.5);
   lep1Pt_data_wMass_emu__6->SetMaximum(1.5);
   lep1Pt_data_wMass_emu__6->SetEntries(62.40525);
   lep1Pt_data_wMass_emu__6->SetDirectory(0);
   lep1Pt_data_wMass_emu__6->SetStats(0);
   lep1Pt_data_wMass_emu__6->SetFillColor(1);
   lep1Pt_data_wMass_emu__6->SetLineWidth(2);
   lep1Pt_data_wMass_emu__6->SetLineColor(1); //
   lep1Pt_data_wMass_emu__6->SetMarkerStyle(20);
   lep1Pt_data_wMass_emu__6->SetMarkerSize(1.6);
   lep1Pt_data_wMass_emu__6->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_data_wMass_emu__6->GetXaxis()->SetNdivisions(506);
   lep1Pt_data_wMass_emu__6->GetXaxis()->SetLabelFont(42);
   lep1Pt_data_wMass_emu__6->GetXaxis()->SetLabelOffset(0.013);
   lep1Pt_data_wMass_emu__6->GetXaxis()->SetLabelSize(0.13);
   lep1Pt_data_wMass_emu__6->GetXaxis()->SetTitleSize(0.13);
   lep1Pt_data_wMass_emu__6->GetXaxis()->SetTitleOffset(1);
   lep1Pt_data_wMass_emu__6->GetXaxis()->SetTitleFont(42);
   lep1Pt_data_wMass_emu__6->GetYaxis()->SetTitle("Data/MC");
   lep1Pt_data_wMass_emu__6->GetYaxis()->CenterTitle(true);
   lep1Pt_data_wMass_emu__6->GetYaxis()->SetNdivisions(506);
   lep1Pt_data_wMass_emu__6->GetYaxis()->SetLabelFont(42);
   lep1Pt_data_wMass_emu__6->GetYaxis()->SetLabelOffset(0.01);
   lep1Pt_data_wMass_emu__6->GetYaxis()->SetLabelSize(0.12);
   lep1Pt_data_wMass_emu__6->GetYaxis()->SetTitleSize(0.16);
   lep1Pt_data_wMass_emu__6->GetYaxis()->SetTitleOffset(0.3);
   lep1Pt_data_wMass_emu__6->GetYaxis()->SetTitleFont(42);
   lep1Pt_data_wMass_emu__6->GetZaxis()->SetLabelFont(42);
   lep1Pt_data_wMass_emu__6->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_data_wMass_emu__6->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_data_wMass_emu__6->GetZaxis()->SetTitleOffset(1);
   lep1Pt_data_wMass_emu__6->GetZaxis()->SetTitleFont(42);
   lep1Pt_data_wMass_emu__6->Draw("e x0, SCAT");
   canvy_2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
//   c1->SetSelected(lep1Pt_data_wMass_emu);
   c1->SaveAs("lep1Pt_wMass.pdf");
}
