void lep1Pt_SingleTop_jetSel()
{
//=========Macro generated from canvas: lep1Pt_SingleTop_jetSel/lep1Pt_SingleTop_jetSel
//=========  (Wed Aug 21 20:24:54 2019) by ROOT version 6.18/00

   // Set up cavas
   int W = 1280;
   int H = 1024;
   int H_ref = 925;
   int W_ref = 1024;

   // references for T, B, L, R
   float T = 0.08*H_ref;
   float B = 0.12*H_ref;
   float L = 0.12*W_ref;
   float R = 0.04*W_ref;

   TCanvas *c1 = new TCanvas("c1","c1",50,50,W,H);
   c1->cd();
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetLeftMargin( L/W );
   c1->SetRightMargin( R/W );
   c1->SetTopMargin( T/H );
   c1->SetBottomMargin( B/H );
   c1->SetTickx(0);
   c1->SetTicky(0);

// ------------>Primitives in pad: canvy_1
   TPad *canvy_1 = new TPad("canvy_1", "newpad",0.01,0.315,0.99,0.99);
   canvy_1->Draw();
   canvy_1->cd();
   canvy_1->SetFillColor(0);
   canvy_1->SetBorderMode(0);

   canvy_1->SetLeftMargin( L/W );
   canvy_1->SetRightMargin( R/W );
   canvy_1->SetTopMargin( T/H );
   canvy_1->SetBottomMargin( B/H * 0.3 );

   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);
   
   THStack *lep1Pt_SingleTop_jetSel_emu = new THStack();
   lep1Pt_SingleTop_jetSel_emu->SetName("lep1Pt_SingleTop_jetSel_emu");
   lep1Pt_SingleTop_jetSel_emu->SetTitle("Electron p_{T};Electron p_{T} (GeV);Events");
   lep1Pt_SingleTop_jetSel_emu->SetMaximum(1869.06);
   
   TH1F *lep1Pt_SingleTop_jetSel_emu_stack_1 = new TH1F("lep1Pt_SingleTop_jetSel_emu_stack_1","Electron p_{T}",20,0,200);
   lep1Pt_SingleTop_jetSel_emu_stack_1->SetMinimum(0);
   lep1Pt_SingleTop_jetSel_emu_stack_1->SetMaximum(1962.513);
   lep1Pt_SingleTop_jetSel_emu_stack_1->SetDirectory(0);
   lep1Pt_SingleTop_jetSel_emu_stack_1->SetStats(0);
   lep1Pt_SingleTop_jetSel_emu_stack_1->SetLineStyle(0);
   lep1Pt_SingleTop_jetSel_emu_stack_1->SetLineWidth(0);
   lep1Pt_SingleTop_jetSel_emu_stack_1->SetMarkerStyle(20);
   lep1Pt_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetNdivisions(506);
   lep1Pt_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetLabelOffset(999);
   lep1Pt_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetLabelSize(0.05);
   lep1Pt_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetTitleSize(0.08);
   lep1Pt_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   lep1Pt_SingleTop_jetSel_emu_stack_1->GetXaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetTitle("Events");
   lep1Pt_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetNdivisions(506);
   lep1Pt_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetLabelOffset(0.01);
   lep1Pt_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetLabelSize(0.062);
   lep1Pt_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetTitleSize(0.08);
   lep1Pt_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetTitleOffset(0.6336);
   lep1Pt_SingleTop_jetSel_emu_stack_1->GetYaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_jetSel_emu_stack_1->GetZaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_jetSel_emu_stack_1->GetZaxis()->SetLabelOffset(0.007);
   lep1Pt_SingleTop_jetSel_emu_stack_1->GetZaxis()->SetLabelSize(0.05);
   lep1Pt_SingleTop_jetSel_emu_stack_1->GetZaxis()->SetTitleSize(0.08);
   lep1Pt_SingleTop_jetSel_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   lep1Pt_SingleTop_jetSel_emu_stack_1->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_jetSel_emu->SetHistogram(lep1Pt_SingleTop_jetSel_emu_stack_1);
   
   
   TH1D *lep1Pt_tZq_jetSel_emu_stack_1 = new TH1D("lep1Pt_tZq_jetSel_emu_stack_1","lep1Pt_tZq_jetSel_emu",20,0,200);
   lep1Pt_tZq_jetSel_emu_stack_1->SetBinContent(4,0.1653477);
   lep1Pt_tZq_jetSel_emu_stack_1->SetBinContent(5,0.3149498);
   lep1Pt_tZq_jetSel_emu_stack_1->SetBinContent(6,0.2079954);
   lep1Pt_tZq_jetSel_emu_stack_1->SetBinContent(7,0.1408704);
   lep1Pt_tZq_jetSel_emu_stack_1->SetBinContent(8,0.09436922);
   lep1Pt_tZq_jetSel_emu_stack_1->SetBinContent(9,0.06128613);
   lep1Pt_tZq_jetSel_emu_stack_1->SetBinContent(10,0.03128476);
   lep1Pt_tZq_jetSel_emu_stack_1->SetBinContent(11,0.02917903);
   lep1Pt_tZq_jetSel_emu_stack_1->SetBinContent(12,0.01472187);
   lep1Pt_tZq_jetSel_emu_stack_1->SetBinContent(13,0.01376036);
   lep1Pt_tZq_jetSel_emu_stack_1->SetBinContent(14,0.00926044);
   lep1Pt_tZq_jetSel_emu_stack_1->SetBinContent(15,0.004072557);
   lep1Pt_tZq_jetSel_emu_stack_1->SetBinContent(16,0.008569047);
   lep1Pt_tZq_jetSel_emu_stack_1->SetBinContent(17,0.002212765);
   lep1Pt_tZq_jetSel_emu_stack_1->SetBinContent(18,-0.001391435);
   lep1Pt_tZq_jetSel_emu_stack_1->SetBinContent(19,-0.0005185145);
   lep1Pt_tZq_jetSel_emu_stack_1->SetBinContent(20,0.00312069);
   lep1Pt_tZq_jetSel_emu_stack_1->SetBinContent(21,0.006402349);
   lep1Pt_tZq_jetSel_emu_stack_1->SetEntries(6672);
   lep1Pt_tZq_jetSel_emu_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ffff00");
   lep1Pt_tZq_jetSel_emu_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   lep1Pt_tZq_jetSel_emu_stack_1->SetLineColor(ci);
   lep1Pt_tZq_jetSel_emu_stack_1->SetLineWidth(0);
   lep1Pt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_tZq_jetSel_emu_stack_1->GetXaxis()->SetLabelFont(42);
   lep1Pt_tZq_jetSel_emu_stack_1->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   lep1Pt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleFont(42);
   lep1Pt_tZq_jetSel_emu_stack_1->GetYaxis()->SetLabelFont(42);
   lep1Pt_tZq_jetSel_emu_stack_1->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleOffset(1);
   lep1Pt_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleFont(42);
   lep1Pt_tZq_jetSel_emu_stack_1->GetZaxis()->SetLabelFont(42);
   lep1Pt_tZq_jetSel_emu_stack_1->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   lep1Pt_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_jetSel_emu->Add(lep1Pt_tZq_jetSel_emu_stack_1,"");
   
   TH1D *lep1Pt_ttV_jetSel_emu_stack_2 = new TH1D("lep1Pt_ttV_jetSel_emu_stack_2","lep1Pt_ttV_jetSel_emu",20,0,200);
   lep1Pt_ttV_jetSel_emu_stack_2->SetBinContent(4,7.759005);
   lep1Pt_ttV_jetSel_emu_stack_2->SetBinContent(5,13.38947);
   lep1Pt_ttV_jetSel_emu_stack_2->SetBinContent(6,10.33556);
   lep1Pt_ttV_jetSel_emu_stack_2->SetBinContent(7,7.097283);
   lep1Pt_ttV_jetSel_emu_stack_2->SetBinContent(8,5.411554);
   lep1Pt_ttV_jetSel_emu_stack_2->SetBinContent(9,4.18207);
   lep1Pt_ttV_jetSel_emu_stack_2->SetBinContent(10,2.398611);
   lep1Pt_ttV_jetSel_emu_stack_2->SetBinContent(11,1.597294);
   lep1Pt_ttV_jetSel_emu_stack_2->SetBinContent(12,1.167946);
   lep1Pt_ttV_jetSel_emu_stack_2->SetBinContent(13,0.828801);
   lep1Pt_ttV_jetSel_emu_stack_2->SetBinContent(14,0.5584211);
   lep1Pt_ttV_jetSel_emu_stack_2->SetBinContent(15,0.4071426);
   lep1Pt_ttV_jetSel_emu_stack_2->SetBinContent(16,0.35922);
   lep1Pt_ttV_jetSel_emu_stack_2->SetBinContent(17,0.3709213);
   lep1Pt_ttV_jetSel_emu_stack_2->SetBinContent(18,0.1756011);
   lep1Pt_ttV_jetSel_emu_stack_2->SetBinContent(19,0.1777252);
   lep1Pt_ttV_jetSel_emu_stack_2->SetBinContent(20,0.0562149);
   lep1Pt_ttV_jetSel_emu_stack_2->SetBinContent(21,0.2505988);
   lep1Pt_ttV_jetSel_emu_stack_2->SetEntries(29408);
   lep1Pt_ttV_jetSel_emu_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#00ff00");
   lep1Pt_ttV_jetSel_emu_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   lep1Pt_ttV_jetSel_emu_stack_2->SetLineColor(ci);
   lep1Pt_ttV_jetSel_emu_stack_2->SetLineWidth(0);
   lep1Pt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_ttV_jetSel_emu_stack_2->GetXaxis()->SetLabelFont(42);
   lep1Pt_ttV_jetSel_emu_stack_2->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   lep1Pt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleFont(42);
   lep1Pt_ttV_jetSel_emu_stack_2->GetYaxis()->SetLabelFont(42);
   lep1Pt_ttV_jetSel_emu_stack_2->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleOffset(1);
   lep1Pt_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleFont(42);
   lep1Pt_ttV_jetSel_emu_stack_2->GetZaxis()->SetLabelFont(42);
   lep1Pt_ttV_jetSel_emu_stack_2->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   lep1Pt_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_jetSel_emu->Add(lep1Pt_ttV_jetSel_emu_stack_2,"");
   
   TH1D *lep1Pt_wJets_jetSel_emu_stack_3 = new TH1D("lep1Pt_wJets_jetSel_emu_stack_3","lep1Pt_wJets_jetSel_emu",20,0,200);
   lep1Pt_wJets_jetSel_emu_stack_3->SetBinContent(5,12.53387);
   lep1Pt_wJets_jetSel_emu_stack_3->SetBinContent(10,13.42844);
   lep1Pt_wJets_jetSel_emu_stack_3->SetEntries(2);
   lep1Pt_wJets_jetSel_emu_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   lep1Pt_wJets_jetSel_emu_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#cccccc");
   lep1Pt_wJets_jetSel_emu_stack_3->SetLineColor(ci);
   lep1Pt_wJets_jetSel_emu_stack_3->SetLineWidth(0);
   lep1Pt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_wJets_jetSel_emu_stack_3->GetXaxis()->SetLabelFont(42);
   lep1Pt_wJets_jetSel_emu_stack_3->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   lep1Pt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleFont(42);
   lep1Pt_wJets_jetSel_emu_stack_3->GetYaxis()->SetLabelFont(42);
   lep1Pt_wJets_jetSel_emu_stack_3->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleOffset(1);
   lep1Pt_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleFont(42);
   lep1Pt_wJets_jetSel_emu_stack_3->GetZaxis()->SetLabelFont(42);
   lep1Pt_wJets_jetSel_emu_stack_3->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   lep1Pt_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_jetSel_emu->Add(lep1Pt_wJets_jetSel_emu_stack_3,"");
   
   TH1D *lep1Pt_VVV_jetSel_emu_stack_4 = new TH1D("lep1Pt_VVV_jetSel_emu_stack_4","lep1Pt_VVV_jetSel_emu",20,0,200);
   lep1Pt_VVV_jetSel_emu_stack_4->SetBinContent(4,0.4248145);
   lep1Pt_VVV_jetSel_emu_stack_4->SetBinContent(5,0.6497797);
   lep1Pt_VVV_jetSel_emu_stack_4->SetBinContent(6,0.4339136);
   lep1Pt_VVV_jetSel_emu_stack_4->SetBinContent(7,0.4315521);
   lep1Pt_VVV_jetSel_emu_stack_4->SetBinContent(8,0.5092889);
   lep1Pt_VVV_jetSel_emu_stack_4->SetBinContent(9,0.1888359);
   lep1Pt_VVV_jetSel_emu_stack_4->SetBinContent(10,0.2071281);
   lep1Pt_VVV_jetSel_emu_stack_4->SetBinContent(11,0.3107929);
   lep1Pt_VVV_jetSel_emu_stack_4->SetBinContent(12,0.07084578);
   lep1Pt_VVV_jetSel_emu_stack_4->SetBinContent(13,0.1387097);
   lep1Pt_VVV_jetSel_emu_stack_4->SetBinContent(14,0.07637559);
   lep1Pt_VVV_jetSel_emu_stack_4->SetBinContent(15,0.03149699);
   lep1Pt_VVV_jetSel_emu_stack_4->SetBinContent(16,0.03046469);
   lep1Pt_VVV_jetSel_emu_stack_4->SetBinContent(17,0.002586923);
   lep1Pt_VVV_jetSel_emu_stack_4->SetBinContent(18,0.02913651);
   lep1Pt_VVV_jetSel_emu_stack_4->SetBinContent(19,0.06540107);
   lep1Pt_VVV_jetSel_emu_stack_4->SetBinContent(21,0.08322907);
   lep1Pt_VVV_jetSel_emu_stack_4->SetEntries(147);
   lep1Pt_VVV_jetSel_emu_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#00ffff");
   lep1Pt_VVV_jetSel_emu_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   lep1Pt_VVV_jetSel_emu_stack_4->SetLineColor(ci);
   lep1Pt_VVV_jetSel_emu_stack_4->SetLineWidth(0);
   lep1Pt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_VVV_jetSel_emu_stack_4->GetXaxis()->SetLabelFont(42);
   lep1Pt_VVV_jetSel_emu_stack_4->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   lep1Pt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleFont(42);
   lep1Pt_VVV_jetSel_emu_stack_4->GetYaxis()->SetLabelFont(42);
   lep1Pt_VVV_jetSel_emu_stack_4->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleOffset(1);
   lep1Pt_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleFont(42);
   lep1Pt_VVV_jetSel_emu_stack_4->GetZaxis()->SetLabelFont(42);
   lep1Pt_VVV_jetSel_emu_stack_4->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   lep1Pt_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_jetSel_emu->Add(lep1Pt_VVV_jetSel_emu_stack_4,"");
   
   TH1D *lep1Pt_VV_jetSel_emu_stack_5 = new TH1D("lep1Pt_VV_jetSel_emu_stack_5","lep1Pt_VV_jetSel_emu",20,0,200);
   lep1Pt_VV_jetSel_emu_stack_5->SetBinContent(4,6.360905);
   lep1Pt_VV_jetSel_emu_stack_5->SetBinContent(5,10.76674);
   lep1Pt_VV_jetSel_emu_stack_5->SetBinContent(6,8.642626);
   lep1Pt_VV_jetSel_emu_stack_5->SetBinContent(7,4.903092);
   lep1Pt_VV_jetSel_emu_stack_5->SetBinContent(8,6.340064);
   lep1Pt_VV_jetSel_emu_stack_5->SetBinContent(9,3.341757);
   lep1Pt_VV_jetSel_emu_stack_5->SetBinContent(10,2.199481);
   lep1Pt_VV_jetSel_emu_stack_5->SetBinContent(11,4.190659);
   lep1Pt_VV_jetSel_emu_stack_5->SetBinContent(12,2.85866);
   lep1Pt_VV_jetSel_emu_stack_5->SetBinContent(13,1.753916);
   lep1Pt_VV_jetSel_emu_stack_5->SetBinContent(14,1.492671);
   lep1Pt_VV_jetSel_emu_stack_5->SetBinContent(15,1.241664);
   lep1Pt_VV_jetSel_emu_stack_5->SetBinContent(16,1.49992);
   lep1Pt_VV_jetSel_emu_stack_5->SetBinContent(17,0.3448739);
   lep1Pt_VV_jetSel_emu_stack_5->SetBinContent(18,0.27107);
   lep1Pt_VV_jetSel_emu_stack_5->SetBinContent(19,1.05851);
   lep1Pt_VV_jetSel_emu_stack_5->SetBinContent(20,0.6116574);
   lep1Pt_VV_jetSel_emu_stack_5->SetBinContent(21,3.094224);
   lep1Pt_VV_jetSel_emu_stack_5->SetEntries(858);
   lep1Pt_VV_jetSel_emu_stack_5->SetDirectory(0);

   ci = TColor::GetColor("#ff9933");
   lep1Pt_VV_jetSel_emu_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#ff9933");
   lep1Pt_VV_jetSel_emu_stack_5->SetLineColor(ci);
   lep1Pt_VV_jetSel_emu_stack_5->SetLineWidth(0);
   lep1Pt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_VV_jetSel_emu_stack_5->GetXaxis()->SetLabelFont(42);
   lep1Pt_VV_jetSel_emu_stack_5->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleOffset(1);
   lep1Pt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleFont(42);
   lep1Pt_VV_jetSel_emu_stack_5->GetYaxis()->SetLabelFont(42);
   lep1Pt_VV_jetSel_emu_stack_5->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleOffset(1);
   lep1Pt_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleFont(42);
   lep1Pt_VV_jetSel_emu_stack_5->GetZaxis()->SetLabelFont(42);
   lep1Pt_VV_jetSel_emu_stack_5->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleOffset(1);
   lep1Pt_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_jetSel_emu->Add(lep1Pt_VV_jetSel_emu_stack_5,"");
   
   TH1D *lep1Pt_SingleTop_jetSel_emu_stack_6 = new TH1D("lep1Pt_SingleTop_jetSel_emu_stack_6","lep1Pt_SingleTop_jetSel_emu",20,0,200);
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(4,32.98228);
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(5,64.10824);
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(6,44.04126);
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(7,42.03001);
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(8,26.73973);
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(9,20.54982);
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(10,10.80433);
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(11,10.62394);
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(12,6.156555);
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(13,4.957517);
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(14,4.910825);
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(15,3.021393);
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(16,1.347501);
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(17,1.016844);
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(18,0.297594);
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(19,0.5235174);
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(20,1.162273);
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(21,4.947274);
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetEntries(2806);
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetDirectory(0);

   ci = TColor::GetColor("#ff00ff");
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetLineColor(ci);
   lep1Pt_SingleTop_jetSel_emu_stack_6->SetLineWidth(0);
   lep1Pt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleOffset(1);
   lep1Pt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleOffset(1);
   lep1Pt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleOffset(1);
   lep1Pt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_jetSel_emu->Add(lep1Pt_SingleTop_jetSel_emu_stack_6,"");
   
   TH1D *lep1Pt_tt_jetSel_emu_stack_7 = new TH1D("lep1Pt_tt_jetSel_emu_stack_7","lep1Pt_tt_jetSel_emu",20,0,200);
   lep1Pt_tt_jetSel_emu_stack_7->SetBinContent(4,895.3464);
   lep1Pt_tt_jetSel_emu_stack_7->SetBinContent(5,1594.514);
   lep1Pt_tt_jetSel_emu_stack_7->SetBinContent(6,1250.446);
   lep1Pt_tt_jetSel_emu_stack_7->SetBinContent(7,843.6259);
   lep1Pt_tt_jetSel_emu_stack_7->SetBinContent(8,563.9871);
   lep1Pt_tt_jetSel_emu_stack_7->SetBinContent(9,362.6781);
   lep1Pt_tt_jetSel_emu_stack_7->SetBinContent(10,254.6184);
   lep1Pt_tt_jetSel_emu_stack_7->SetBinContent(11,147.4165);
   lep1Pt_tt_jetSel_emu_stack_7->SetBinContent(12,113.8907);
   lep1Pt_tt_jetSel_emu_stack_7->SetBinContent(13,67.32551);
   lep1Pt_tt_jetSel_emu_stack_7->SetBinContent(14,45.4842);
   lep1Pt_tt_jetSel_emu_stack_7->SetBinContent(15,26.05631);
   lep1Pt_tt_jetSel_emu_stack_7->SetBinContent(16,19.32112);
   lep1Pt_tt_jetSel_emu_stack_7->SetBinContent(17,15.65042);
   lep1Pt_tt_jetSel_emu_stack_7->SetBinContent(18,9.149147);
   lep1Pt_tt_jetSel_emu_stack_7->SetBinContent(19,6.565574);
   lep1Pt_tt_jetSel_emu_stack_7->SetBinContent(20,5.088342);
   lep1Pt_tt_jetSel_emu_stack_7->SetBinContent(21,17.35438);
   lep1Pt_tt_jetSel_emu_stack_7->SetEntries(19867);
   lep1Pt_tt_jetSel_emu_stack_7->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   lep1Pt_tt_jetSel_emu_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   lep1Pt_tt_jetSel_emu_stack_7->SetLineColor(ci);
   lep1Pt_tt_jetSel_emu_stack_7->SetLineWidth(0);
   lep1Pt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_tt_jetSel_emu_stack_7->GetXaxis()->SetLabelFont(42);
   lep1Pt_tt_jetSel_emu_stack_7->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleOffset(1);
   lep1Pt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleFont(42);
   lep1Pt_tt_jetSel_emu_stack_7->GetYaxis()->SetLabelFont(42);
   lep1Pt_tt_jetSel_emu_stack_7->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleOffset(1);
   lep1Pt_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleFont(42);
   lep1Pt_tt_jetSel_emu_stack_7->GetZaxis()->SetLabelFont(42);
   lep1Pt_tt_jetSel_emu_stack_7->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleOffset(1);
   lep1Pt_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_jetSel_emu->Add(lep1Pt_tt_jetSel_emu_stack_7,"");
   
   TH1D *lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8 = new TH1D("lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8","lep1Pt_zPlusJetsMadgraph_jetSel_emu",20,0,200);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(4,2.875012);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(5,2.868444);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(6,5.892443);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(7,1.500954);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(9,1.549233);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(11,1.500213);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(12,1.483989);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetEntries(12);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetLineColor(ci);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetLineWidth(0);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetLabelFont(42);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleOffset(1);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleFont(42);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetLabelFont(42);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleOffset(1);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleFont(42);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetLabelFont(42);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleOffset(1);
   lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_jetSel_emu->Add(lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8,"");
   lep1Pt_SingleTop_jetSel_emu->Draw("");
   
   TH1D *lep1Pt_data_jetSel_emu__1 = new TH1D("lep1Pt_data_jetSel_emu__1","lep1Pt_data_jetSel_emu",20,0,200);
   lep1Pt_data_jetSel_emu__1->SetBinContent(4,935);
   lep1Pt_data_jetSel_emu__1->SetBinContent(5,1680);
   lep1Pt_data_jetSel_emu__1->SetBinContent(6,1331);
   lep1Pt_data_jetSel_emu__1->SetBinContent(7,934);
   lep1Pt_data_jetSel_emu__1->SetBinContent(8,628);
   lep1Pt_data_jetSel_emu__1->SetBinContent(9,395);
   lep1Pt_data_jetSel_emu__1->SetBinContent(10,276);
   lep1Pt_data_jetSel_emu__1->SetBinContent(11,141);
   lep1Pt_data_jetSel_emu__1->SetBinContent(12,106);
   lep1Pt_data_jetSel_emu__1->SetBinContent(13,70);
   lep1Pt_data_jetSel_emu__1->SetBinContent(14,42);
   lep1Pt_data_jetSel_emu__1->SetBinContent(15,37);
   lep1Pt_data_jetSel_emu__1->SetBinContent(16,35);
   lep1Pt_data_jetSel_emu__1->SetBinContent(17,15);
   lep1Pt_data_jetSel_emu__1->SetBinContent(18,15);
   lep1Pt_data_jetSel_emu__1->SetBinContent(19,4);
   lep1Pt_data_jetSel_emu__1->SetBinContent(20,8);
   lep1Pt_data_jetSel_emu__1->SetBinContent(21,16);
   lep1Pt_data_jetSel_emu__1->SetEntries(6668);
   lep1Pt_data_jetSel_emu__1->SetDirectory(0);
   lep1Pt_data_jetSel_emu__1->SetFillColor(1);
   lep1Pt_data_jetSel_emu__1->SetLineWidth(2);
   lep1Pt_data_jetSel_emu__1->SetLineColor(1); //
   lep1Pt_data_jetSel_emu__1->SetMarkerStyle(20);
   lep1Pt_data_jetSel_emu__1->SetMarkerSize(1.4);
   lep1Pt_data_jetSel_emu__1->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_data_jetSel_emu__1->GetXaxis()->SetLabelFont(42);
   lep1Pt_data_jetSel_emu__1->GetXaxis()->SetLabelSize(0.035);
   lep1Pt_data_jetSel_emu__1->GetXaxis()->SetTitleSize(0.035);
   lep1Pt_data_jetSel_emu__1->GetXaxis()->SetTitleOffset(1);
   lep1Pt_data_jetSel_emu__1->GetXaxis()->SetTitleFont(42);
   lep1Pt_data_jetSel_emu__1->GetYaxis()->SetLabelFont(42);
   lep1Pt_data_jetSel_emu__1->GetYaxis()->SetLabelSize(0.035);
   lep1Pt_data_jetSel_emu__1->GetYaxis()->SetTitleSize(0.035);
   lep1Pt_data_jetSel_emu__1->GetYaxis()->SetTitleOffset(1);
   lep1Pt_data_jetSel_emu__1->GetYaxis()->SetTitleFont(42);
   lep1Pt_data_jetSel_emu__1->GetZaxis()->SetLabelFont(42);
   lep1Pt_data_jetSel_emu__1->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_data_jetSel_emu__1->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_data_jetSel_emu__1->GetZaxis()->SetTitleOffset(1);
   lep1Pt_data_jetSel_emu__1->GetZaxis()->SetTitleFont(42);
   lep1Pt_data_jetSel_emu__1->Draw("e x0, same");
   
   TLegend *leg = new TLegend(0.78,0.42,0.98,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("lep1Pt_zPlusJetsMadgraph_jetSel_emu_stack_8","Z+jets (LO)","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_tt_jetSel_emu_stack_7","t#bar{t}","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_SingleTop_jetSel_emu_stack_6","Single top","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_VV_jetSel_emu_stack_5","VV","f");

   ci = TColor::GetColor("#ff9933");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_VVV_jetSel_emu_stack_4","VVV","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_wJets_jetSel_emu_stack_3","W+jets","f");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_ttV_jetSel_emu_stack_2","t#bar{t}V","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_tZq_jetSel_emu_stack_1","tZq","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep1Pt_data_jetSel_emu","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.4);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.968,0.9429101,"35.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06792969);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.096,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.05419922);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16899,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.04119141);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *lep1Pt_SingleTop_jetSel_emu__2 = new TH1F("lep1Pt_SingleTop_jetSel_emu__2","Electron p_{T}",20,0,200);
   lep1Pt_SingleTop_jetSel_emu__2->SetMinimum(0);
   lep1Pt_SingleTop_jetSel_emu__2->SetMaximum(1962.513);
   lep1Pt_SingleTop_jetSel_emu__2->SetDirectory(0);
   lep1Pt_SingleTop_jetSel_emu__2->SetStats(0);
   lep1Pt_SingleTop_jetSel_emu__2->SetLineStyle(0);
   lep1Pt_SingleTop_jetSel_emu__2->SetLineWidth(0);
   lep1Pt_SingleTop_jetSel_emu__2->SetMarkerStyle(20);
   lep1Pt_SingleTop_jetSel_emu__2->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_SingleTop_jetSel_emu__2->GetXaxis()->SetNdivisions(506);
   lep1Pt_SingleTop_jetSel_emu__2->GetXaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_jetSel_emu__2->GetXaxis()->SetLabelOffset(999);
   lep1Pt_SingleTop_jetSel_emu__2->GetXaxis()->SetLabelSize(0.05);
   lep1Pt_SingleTop_jetSel_emu__2->GetXaxis()->SetTitleSize(0.08);
   lep1Pt_SingleTop_jetSel_emu__2->GetXaxis()->SetTitleOffset(1);
   lep1Pt_SingleTop_jetSel_emu__2->GetXaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_jetSel_emu__2->GetYaxis()->SetTitle("Events");
   lep1Pt_SingleTop_jetSel_emu__2->GetYaxis()->SetNdivisions(506);
   lep1Pt_SingleTop_jetSel_emu__2->GetYaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_jetSel_emu__2->GetYaxis()->SetLabelOffset(0.01);
   lep1Pt_SingleTop_jetSel_emu__2->GetYaxis()->SetLabelSize(0.062);
   lep1Pt_SingleTop_jetSel_emu__2->GetYaxis()->SetTitleSize(0.08);
   lep1Pt_SingleTop_jetSel_emu__2->GetYaxis()->SetTitleOffset(0.6336);
   lep1Pt_SingleTop_jetSel_emu__2->GetYaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_jetSel_emu__2->GetZaxis()->SetLabelFont(42);
   lep1Pt_SingleTop_jetSel_emu__2->GetZaxis()->SetLabelOffset(0.007);
   lep1Pt_SingleTop_jetSel_emu__2->GetZaxis()->SetLabelSize(0.05);
   lep1Pt_SingleTop_jetSel_emu__2->GetZaxis()->SetTitleSize(0.08);
   lep1Pt_SingleTop_jetSel_emu__2->GetZaxis()->SetTitleOffset(1);
   lep1Pt_SingleTop_jetSel_emu__2->GetZaxis()->SetTitleFont(42);
   lep1Pt_SingleTop_jetSel_emu__2->Draw("sameaxis");
   
   TPaveText *pt = new TPaveText(0.4029699,0.9203237,0.5970301,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Electron p_{T}");
   pt->Draw();
   canvy_1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: canvy_2
   TPad *canvy_2 = new TPad("canvy_2", "newpad2",0.01,0.01,0.99,0.322);
   canvy_2->Draw();
   canvy_2->cd();
   canvy_2->SetFillColor(0);
   canvy_2->SetBorderMode(0);
   canvy_2->SetGridy();

   canvy_2->SetLeftMargin( L/W );
   canvy_2->SetRightMargin( R/W );
   canvy_2->SetTopMargin( T/H );
   canvy_2->SetBottomMargin( B/H * 2.6 );
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   
   TH1D *lep1Pt_data_jetSel_emu__3 = new TH1D("lep1Pt_data_jetSel_emu__3","",20,0,200);
   lep1Pt_data_jetSel_emu__3->SetBinContent(4,0.9884622);
   lep1Pt_data_jetSel_emu__3->SetBinContent(5,0.9887322);
   lep1Pt_data_jetSel_emu__3->SetBinContent(6,1.008334);
   lep1Pt_data_jetSel_emu__3->SetBinContent(7,1.03809);
   lep1Pt_data_jetSel_emu__3->SetBinContent(8,1.041318);
   lep1Pt_data_jetSel_emu__3->SetBinContent(9,1.006238);
   lep1Pt_data_jetSel_emu__3->SetBinContent(10,0.972901);
   lep1Pt_data_jetSel_emu__3->SetBinContent(11,0.8510968);
   lep1Pt_data_jetSel_emu__3->SetBinContent(12,0.8436572);
   lep1Pt_data_jetSel_emu__3->SetBinContent(13,0.9331068);
   lep1Pt_data_jetSel_emu__3->SetBinContent(14,0.7995164);
   lep1Pt_data_jetSel_emu__3->SetBinContent(15,1.20278);
   lep1Pt_data_jetSel_emu__3->SetBinContent(16,1.550951);
   lep1Pt_data_jetSel_emu__3->SetBinContent(17,0.8626709);
   lep1Pt_data_jetSel_emu__3->SetBinContent(18,1.51192);
   lep1Pt_data_jetSel_emu__3->SetBinContent(19,0.4767462);
   lep1Pt_data_jetSel_emu__3->SetBinContent(20,1.155801);
   lep1Pt_data_jetSel_emu__3->SetBinContent(21,0.6216945);
   lep1Pt_data_jetSel_emu__3->SetBinError(4,0.04558405);
   lep1Pt_data_jetSel_emu__3->SetBinError(5,0.03401827);
   lep1Pt_data_jetSel_emu__3->SetBinError(6,0.03916816);
   lep1Pt_data_jetSel_emu__3->SetBinError(7,0.04849233);
   lep1Pt_data_jetSel_emu__3->SetBinError(8,0.05936885);
   lep1Pt_data_jetSel_emu__3->SetBinError(9,0.0717123);
   lep1Pt_data_jetSel_emu__3->SetBinError(10,0.08225584);
   lep1Pt_data_jetSel_emu__3->SetBinError(11,0.09751782);
   lep1Pt_data_jetSel_emu__3->SetBinError(12,0.1112636);
   lep1Pt_data_jetSel_emu__3->SetBinError(13,0.1550637);
   lep1Pt_data_jetSel_emu__3->SetBinError(14,0.1654934);
   lep1Pt_data_jetSel_emu__3->SetBinError(15,0.2934747);
   lep1Pt_data_jetSel_emu__3->SetBinError(16,0.4187119);
   lep1Pt_data_jetSel_emu__3->SetBinError(17,0.3039958);
   lep1Pt_data_jetSel_emu__3->SetBinError(18,0.6187088);
   lep1Pt_data_jetSel_emu__3->SetBinError(19,0.2896744);
   lep1Pt_data_jetSel_emu__3->SetBinError(20,0.5999876);
   lep1Pt_data_jetSel_emu__3->SetBinError(21,0.1979254);
   lep1Pt_data_jetSel_emu__3->SetMinimum(0.5);
   lep1Pt_data_jetSel_emu__3->SetMaximum(1.5);
   lep1Pt_data_jetSel_emu__3->SetEntries(232.6426);
   lep1Pt_data_jetSel_emu__3->SetDirectory(0);
   lep1Pt_data_jetSel_emu__3->SetStats(0);
   lep1Pt_data_jetSel_emu__3->SetFillColor(1);
   lep1Pt_data_jetSel_emu__3->SetLineWidth(2);
   lep1Pt_data_jetSel_emu__3->SetLineColor(1); //
   lep1Pt_data_jetSel_emu__3->SetMarkerStyle(20);
   lep1Pt_data_jetSel_emu__3->SetMarkerSize(1.6);
   lep1Pt_data_jetSel_emu__3->GetXaxis()->SetTitle("Electron p_{T} (GeV)");
   lep1Pt_data_jetSel_emu__3->GetXaxis()->SetNdivisions(506);
   lep1Pt_data_jetSel_emu__3->GetXaxis()->SetLabelFont(42);
   lep1Pt_data_jetSel_emu__3->GetXaxis()->SetLabelOffset(0.013);
   lep1Pt_data_jetSel_emu__3->GetXaxis()->SetLabelSize(0.13);
   lep1Pt_data_jetSel_emu__3->GetXaxis()->SetTitleSize(0.13);
   lep1Pt_data_jetSel_emu__3->GetXaxis()->SetTitleOffset(1);
   lep1Pt_data_jetSel_emu__3->GetXaxis()->SetTitleFont(42);
   lep1Pt_data_jetSel_emu__3->GetYaxis()->SetTitle("Data/MC");
   lep1Pt_data_jetSel_emu__3->GetYaxis()->CenterTitle(true);
   lep1Pt_data_jetSel_emu__3->GetYaxis()->SetNdivisions(506);
   lep1Pt_data_jetSel_emu__3->GetYaxis()->SetLabelFont(42);
   lep1Pt_data_jetSel_emu__3->GetYaxis()->SetLabelOffset(0.01);
   lep1Pt_data_jetSel_emu__3->GetYaxis()->SetLabelSize(0.12);
   lep1Pt_data_jetSel_emu__3->GetYaxis()->SetTitleSize(0.16);
   lep1Pt_data_jetSel_emu__3->GetYaxis()->SetTitleOffset(0.3);
   lep1Pt_data_jetSel_emu__3->GetYaxis()->SetTitleFont(42);
   lep1Pt_data_jetSel_emu__3->GetZaxis()->SetLabelFont(42);
   lep1Pt_data_jetSel_emu__3->GetZaxis()->SetLabelSize(0.035);
   lep1Pt_data_jetSel_emu__3->GetZaxis()->SetTitleSize(0.035);
   lep1Pt_data_jetSel_emu__3->GetZaxis()->SetTitleOffset(1);
   lep1Pt_data_jetSel_emu__3->GetZaxis()->SetTitleFont(42);
   lep1Pt_data_jetSel_emu__3->Draw("e x0, SCAT");
   canvy_2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
//   c1->SetSelected(lep1Pt_data_jetSel_emu);
   c1->SaveAs("lep1Pt_jetSel.pdf");
}
