void lep2Pt_SingleTop_jetSel()
{
//=========Macro generated from canvas: lep2Pt_SingleTop_jetSel/lep2Pt_SingleTop_jetSel
//=========  (Wed Aug 21 20:25:28 2019) by ROOT version 6.18/00

   // Set up cavas
   int W = 1280;
   int H = 1024;
   int H_ref = 925;
   int W_ref = 1024;

   // references for T, B, L, R
   float T = 0.08*H_ref;
   float B = 0.12*H_ref;
   float L = 0.12*W_ref;
   float R = 0.04*W_ref;

   TCanvas *c1 = new TCanvas("c1","c1",50,50,W,H);
   c1->cd();
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetLeftMargin( L/W );
   c1->SetRightMargin( R/W );
   c1->SetTopMargin( T/H );
   c1->SetBottomMargin( B/H );
   c1->SetTickx(0);
   c1->SetTicky(0);

// ------------>Primitives in pad: canvy_1
   TPad *canvy_1 = new TPad("canvy_1", "newpad",0.01,0.315,0.99,0.99);
   canvy_1->Draw();
   canvy_1->cd();
   canvy_1->SetFillColor(0);
   canvy_1->SetBorderMode(0);

   canvy_1->SetLeftMargin( L/W );
   canvy_1->SetRightMargin( R/W );
   canvy_1->SetTopMargin( T/H );
   canvy_1->SetBottomMargin( B/H * 0.3 );

   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);
   
   THStack *lep2Pt_SingleTop_jetSel_emu = new THStack();
   lep2Pt_SingleTop_jetSel_emu->SetName("lep2Pt_SingleTop_jetSel_emu");
   lep2Pt_SingleTop_jetSel_emu->SetTitle("Muon p_{T};Muon p_{T} (GeV);Events");
   lep2Pt_SingleTop_jetSel_emu->SetMaximum(1976.991);
   
   TH1F *lep2Pt_SingleTop_jetSel_emu_stack_3 = new TH1F("lep2Pt_SingleTop_jetSel_emu_stack_3","Muon p_{T}",20,0,200);
   lep2Pt_SingleTop_jetSel_emu_stack_3->SetMinimum(0);
   lep2Pt_SingleTop_jetSel_emu_stack_3->SetMaximum(2075.841);
   lep2Pt_SingleTop_jetSel_emu_stack_3->SetDirectory(0);
   lep2Pt_SingleTop_jetSel_emu_stack_3->SetStats(0);
   lep2Pt_SingleTop_jetSel_emu_stack_3->SetLineStyle(0);
   lep2Pt_SingleTop_jetSel_emu_stack_3->SetLineWidth(0);
   lep2Pt_SingleTop_jetSel_emu_stack_3->SetMarkerStyle(20);
   lep2Pt_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetNdivisions(506);
   lep2Pt_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetLabelFont(42);
   lep2Pt_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetLabelOffset(999);
   lep2Pt_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetLabelSize(0.05);
   lep2Pt_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetTitleSize(0.08);
   lep2Pt_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   lep2Pt_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetTitle("Events");
   lep2Pt_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetNdivisions(506);
   lep2Pt_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetLabelFont(42);
   lep2Pt_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetLabelOffset(0.01);
   lep2Pt_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetLabelSize(0.062);
   lep2Pt_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetTitleSize(0.08);
   lep2Pt_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetTitleOffset(0.6336);
   lep2Pt_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_jetSel_emu_stack_3->GetZaxis()->SetLabelFont(42);
   lep2Pt_SingleTop_jetSel_emu_stack_3->GetZaxis()->SetLabelOffset(0.007);
   lep2Pt_SingleTop_jetSel_emu_stack_3->GetZaxis()->SetLabelSize(0.05);
   lep2Pt_SingleTop_jetSel_emu_stack_3->GetZaxis()->SetTitleSize(0.08);
   lep2Pt_SingleTop_jetSel_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   lep2Pt_SingleTop_jetSel_emu_stack_3->GetZaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_jetSel_emu->SetHistogram(lep2Pt_SingleTop_jetSel_emu_stack_3);
   
   
   TH1D *lep2Pt_tZq_jetSel_emu_stack_1 = new TH1D("lep2Pt_tZq_jetSel_emu_stack_1","lep2Pt_tZq_jetSel_emu",20,0,200);
   lep2Pt_tZq_jetSel_emu_stack_1->SetBinContent(3,0.1347989);
   lep2Pt_tZq_jetSel_emu_stack_1->SetBinContent(4,0.3189662);
   lep2Pt_tZq_jetSel_emu_stack_1->SetBinContent(5,0.2293562);
   lep2Pt_tZq_jetSel_emu_stack_1->SetBinContent(6,0.1425863);
   lep2Pt_tZq_jetSel_emu_stack_1->SetBinContent(7,0.08393426);
   lep2Pt_tZq_jetSel_emu_stack_1->SetBinContent(8,0.06922523);
   lep2Pt_tZq_jetSel_emu_stack_1->SetBinContent(9,0.03912983);
   lep2Pt_tZq_jetSel_emu_stack_1->SetBinContent(10,0.0165207);
   lep2Pt_tZq_jetSel_emu_stack_1->SetBinContent(11,0.03043234);
   lep2Pt_tZq_jetSel_emu_stack_1->SetBinContent(12,0.01147055);
   lep2Pt_tZq_jetSel_emu_stack_1->SetBinContent(13,0.0003377897);
   lep2Pt_tZq_jetSel_emu_stack_1->SetBinContent(14,0.007267254);
   lep2Pt_tZq_jetSel_emu_stack_1->SetBinContent(15,0.006338329);
   lep2Pt_tZq_jetSel_emu_stack_1->SetBinContent(16,0.001114545);
   lep2Pt_tZq_jetSel_emu_stack_1->SetBinContent(17,0.00376147);
   lep2Pt_tZq_jetSel_emu_stack_1->SetBinContent(18,0.001623152);
   lep2Pt_tZq_jetSel_emu_stack_1->SetBinContent(19,0.000484743);
   lep2Pt_tZq_jetSel_emu_stack_1->SetBinContent(20,0.00266155);
   lep2Pt_tZq_jetSel_emu_stack_1->SetBinContent(21,0.005483309);
   lep2Pt_tZq_jetSel_emu_stack_1->SetEntries(6672);
   lep2Pt_tZq_jetSel_emu_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ffff00");
   lep2Pt_tZq_jetSel_emu_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   lep2Pt_tZq_jetSel_emu_stack_1->SetLineColor(ci);
   lep2Pt_tZq_jetSel_emu_stack_1->SetLineWidth(0);
   lep2Pt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_tZq_jetSel_emu_stack_1->GetXaxis()->SetLabelFont(42);
   lep2Pt_tZq_jetSel_emu_stack_1->GetXaxis()->SetLabelSize(0.035);
   lep2Pt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleSize(0.035);
   lep2Pt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   lep2Pt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleFont(42);
   lep2Pt_tZq_jetSel_emu_stack_1->GetYaxis()->SetLabelFont(42);
   lep2Pt_tZq_jetSel_emu_stack_1->GetYaxis()->SetLabelSize(0.035);
   lep2Pt_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleSize(0.035);
   lep2Pt_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleOffset(1);
   lep2Pt_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleFont(42);
   lep2Pt_tZq_jetSel_emu_stack_1->GetZaxis()->SetLabelFont(42);
   lep2Pt_tZq_jetSel_emu_stack_1->GetZaxis()->SetLabelSize(0.035);
   lep2Pt_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleSize(0.035);
   lep2Pt_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   lep2Pt_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_jetSel_emu->Add(lep2Pt_tZq_jetSel_emu_stack_1,"");
   
   TH1D *lep2Pt_ttV_jetSel_emu_stack_2 = new TH1D("lep2Pt_ttV_jetSel_emu_stack_2","lep2Pt_ttV_jetSel_emu",20,0,200);
   lep2Pt_ttV_jetSel_emu_stack_2->SetBinContent(3,6.661889);
   lep2Pt_ttV_jetSel_emu_stack_2->SetBinContent(4,14.60354);
   lep2Pt_ttV_jetSel_emu_stack_2->SetBinContent(5,12.57233);
   lep2Pt_ttV_jetSel_emu_stack_2->SetBinContent(6,7.62219);
   lep2Pt_ttV_jetSel_emu_stack_2->SetBinContent(7,5.114314);
   lep2Pt_ttV_jetSel_emu_stack_2->SetBinContent(8,3.236165);
   lep2Pt_ttV_jetSel_emu_stack_2->SetBinContent(9,1.975009);
   lep2Pt_ttV_jetSel_emu_stack_2->SetBinContent(10,1.209986);
   lep2Pt_ttV_jetSel_emu_stack_2->SetBinContent(11,1.199774);
   lep2Pt_ttV_jetSel_emu_stack_2->SetBinContent(12,0.5789137);
   lep2Pt_ttV_jetSel_emu_stack_2->SetBinContent(13,0.4853906);
   lep2Pt_ttV_jetSel_emu_stack_2->SetBinContent(14,0.4264609);
   lep2Pt_ttV_jetSel_emu_stack_2->SetBinContent(15,0.2977271);
   lep2Pt_ttV_jetSel_emu_stack_2->SetBinContent(16,0.1953395);
   lep2Pt_ttV_jetSel_emu_stack_2->SetBinContent(17,0.01182305);
   lep2Pt_ttV_jetSel_emu_stack_2->SetBinContent(18,-0.01927666);
   lep2Pt_ttV_jetSel_emu_stack_2->SetBinContent(19,0.153584);
   lep2Pt_ttV_jetSel_emu_stack_2->SetBinContent(20,0.04537216);
   lep2Pt_ttV_jetSel_emu_stack_2->SetBinContent(21,0.152905);
   lep2Pt_ttV_jetSel_emu_stack_2->SetEntries(29408);
   lep2Pt_ttV_jetSel_emu_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#00ff00");
   lep2Pt_ttV_jetSel_emu_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   lep2Pt_ttV_jetSel_emu_stack_2->SetLineColor(ci);
   lep2Pt_ttV_jetSel_emu_stack_2->SetLineWidth(0);
   lep2Pt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_ttV_jetSel_emu_stack_2->GetXaxis()->SetLabelFont(42);
   lep2Pt_ttV_jetSel_emu_stack_2->GetXaxis()->SetLabelSize(0.035);
   lep2Pt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleSize(0.035);
   lep2Pt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   lep2Pt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleFont(42);
   lep2Pt_ttV_jetSel_emu_stack_2->GetYaxis()->SetLabelFont(42);
   lep2Pt_ttV_jetSel_emu_stack_2->GetYaxis()->SetLabelSize(0.035);
   lep2Pt_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleSize(0.035);
   lep2Pt_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleOffset(1);
   lep2Pt_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleFont(42);
   lep2Pt_ttV_jetSel_emu_stack_2->GetZaxis()->SetLabelFont(42);
   lep2Pt_ttV_jetSel_emu_stack_2->GetZaxis()->SetLabelSize(0.035);
   lep2Pt_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleSize(0.035);
   lep2Pt_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   lep2Pt_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_jetSel_emu->Add(lep2Pt_ttV_jetSel_emu_stack_2,"");
   
   TH1D *lep2Pt_wJets_jetSel_emu_stack_3 = new TH1D("lep2Pt_wJets_jetSel_emu_stack_3","lep2Pt_wJets_jetSel_emu",20,0,200);
   lep2Pt_wJets_jetSel_emu_stack_3->SetBinContent(6,13.42844);
   lep2Pt_wJets_jetSel_emu_stack_3->SetBinContent(7,12.53387);
   lep2Pt_wJets_jetSel_emu_stack_3->SetEntries(2);
   lep2Pt_wJets_jetSel_emu_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   lep2Pt_wJets_jetSel_emu_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#cccccc");
   lep2Pt_wJets_jetSel_emu_stack_3->SetLineColor(ci);
   lep2Pt_wJets_jetSel_emu_stack_3->SetLineWidth(0);
   lep2Pt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_wJets_jetSel_emu_stack_3->GetXaxis()->SetLabelFont(42);
   lep2Pt_wJets_jetSel_emu_stack_3->GetXaxis()->SetLabelSize(0.035);
   lep2Pt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleSize(0.035);
   lep2Pt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   lep2Pt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleFont(42);
   lep2Pt_wJets_jetSel_emu_stack_3->GetYaxis()->SetLabelFont(42);
   lep2Pt_wJets_jetSel_emu_stack_3->GetYaxis()->SetLabelSize(0.035);
   lep2Pt_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleSize(0.035);
   lep2Pt_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleOffset(1);
   lep2Pt_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleFont(42);
   lep2Pt_wJets_jetSel_emu_stack_3->GetZaxis()->SetLabelFont(42);
   lep2Pt_wJets_jetSel_emu_stack_3->GetZaxis()->SetLabelSize(0.035);
   lep2Pt_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleSize(0.035);
   lep2Pt_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   lep2Pt_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_jetSel_emu->Add(lep2Pt_wJets_jetSel_emu_stack_3,"");
   
   TH1D *lep2Pt_VVV_jetSel_emu_stack_4 = new TH1D("lep2Pt_VVV_jetSel_emu_stack_4","lep2Pt_VVV_jetSel_emu",20,0,200);
   lep2Pt_VVV_jetSel_emu_stack_4->SetBinContent(3,0.2162359);
   lep2Pt_VVV_jetSel_emu_stack_4->SetBinContent(4,1.122836);
   lep2Pt_VVV_jetSel_emu_stack_4->SetBinContent(5,0.6009264);
   lep2Pt_VVV_jetSel_emu_stack_4->SetBinContent(6,0.4796164);
   lep2Pt_VVV_jetSel_emu_stack_4->SetBinContent(7,0.3218804);
   lep2Pt_VVV_jetSel_emu_stack_4->SetBinContent(8,0.3902478);
   lep2Pt_VVV_jetSel_emu_stack_4->SetBinContent(9,0.1651277);
   lep2Pt_VVV_jetSel_emu_stack_4->SetBinContent(10,0.08646753);
   lep2Pt_VVV_jetSel_emu_stack_4->SetBinContent(11,0.1068064);
   lep2Pt_VVV_jetSel_emu_stack_4->SetBinContent(12,0.04002607);
   lep2Pt_VVV_jetSel_emu_stack_4->SetBinContent(14,0.06601102);
   lep2Pt_VVV_jetSel_emu_stack_4->SetBinContent(15,0.03905059);
   lep2Pt_VVV_jetSel_emu_stack_4->SetBinContent(16,-0.006682381);
   lep2Pt_VVV_jetSel_emu_stack_4->SetBinContent(21,0.0558021);
   lep2Pt_VVV_jetSel_emu_stack_4->SetEntries(147);
   lep2Pt_VVV_jetSel_emu_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#00ffff");
   lep2Pt_VVV_jetSel_emu_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   lep2Pt_VVV_jetSel_emu_stack_4->SetLineColor(ci);
   lep2Pt_VVV_jetSel_emu_stack_4->SetLineWidth(0);
   lep2Pt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_VVV_jetSel_emu_stack_4->GetXaxis()->SetLabelFont(42);
   lep2Pt_VVV_jetSel_emu_stack_4->GetXaxis()->SetLabelSize(0.035);
   lep2Pt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleSize(0.035);
   lep2Pt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   lep2Pt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleFont(42);
   lep2Pt_VVV_jetSel_emu_stack_4->GetYaxis()->SetLabelFont(42);
   lep2Pt_VVV_jetSel_emu_stack_4->GetYaxis()->SetLabelSize(0.035);
   lep2Pt_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleSize(0.035);
   lep2Pt_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleOffset(1);
   lep2Pt_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleFont(42);
   lep2Pt_VVV_jetSel_emu_stack_4->GetZaxis()->SetLabelFont(42);
   lep2Pt_VVV_jetSel_emu_stack_4->GetZaxis()->SetLabelSize(0.035);
   lep2Pt_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleSize(0.035);
   lep2Pt_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   lep2Pt_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_jetSel_emu->Add(lep2Pt_VVV_jetSel_emu_stack_4,"");
   
   TH1D *lep2Pt_VV_jetSel_emu_stack_5 = new TH1D("lep2Pt_VV_jetSel_emu_stack_5","lep2Pt_VV_jetSel_emu",20,0,200);
   lep2Pt_VV_jetSel_emu_stack_5->SetBinContent(3,6.792146);
   lep2Pt_VV_jetSel_emu_stack_5->SetBinContent(4,13.49105);
   lep2Pt_VV_jetSel_emu_stack_5->SetBinContent(5,8.423995);
   lep2Pt_VV_jetSel_emu_stack_5->SetBinContent(6,8.258657);
   lep2Pt_VV_jetSel_emu_stack_5->SetBinContent(7,5.171116);
   lep2Pt_VV_jetSel_emu_stack_5->SetBinContent(8,5.085235);
   lep2Pt_VV_jetSel_emu_stack_5->SetBinContent(9,3.369111);
   lep2Pt_VV_jetSel_emu_stack_5->SetBinContent(10,2.836235);
   lep2Pt_VV_jetSel_emu_stack_5->SetBinContent(11,2.199648);
   lep2Pt_VV_jetSel_emu_stack_5->SetBinContent(12,1.162212);
   lep2Pt_VV_jetSel_emu_stack_5->SetBinContent(13,0.6959682);
   lep2Pt_VV_jetSel_emu_stack_5->SetBinContent(14,0.4881764);
   lep2Pt_VV_jetSel_emu_stack_5->SetBinContent(15,0.250675);
   lep2Pt_VV_jetSel_emu_stack_5->SetBinContent(16,0.3904213);
   lep2Pt_VV_jetSel_emu_stack_5->SetBinContent(17,0.2198674);
   lep2Pt_VV_jetSel_emu_stack_5->SetBinContent(18,-0.1397216);
   lep2Pt_VV_jetSel_emu_stack_5->SetBinContent(19,0.1150634);
   lep2Pt_VV_jetSel_emu_stack_5->SetBinContent(20,0.4409092);
   lep2Pt_VV_jetSel_emu_stack_5->SetBinContent(21,1.721719);
   lep2Pt_VV_jetSel_emu_stack_5->SetEntries(858);
   lep2Pt_VV_jetSel_emu_stack_5->SetDirectory(0);

   ci = TColor::GetColor("#ff9933");
   lep2Pt_VV_jetSel_emu_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#ff9933");
   lep2Pt_VV_jetSel_emu_stack_5->SetLineColor(ci);
   lep2Pt_VV_jetSel_emu_stack_5->SetLineWidth(0);
   lep2Pt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_VV_jetSel_emu_stack_5->GetXaxis()->SetLabelFont(42);
   lep2Pt_VV_jetSel_emu_stack_5->GetXaxis()->SetLabelSize(0.035);
   lep2Pt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleSize(0.035);
   lep2Pt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleOffset(1);
   lep2Pt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleFont(42);
   lep2Pt_VV_jetSel_emu_stack_5->GetYaxis()->SetLabelFont(42);
   lep2Pt_VV_jetSel_emu_stack_5->GetYaxis()->SetLabelSize(0.035);
   lep2Pt_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleSize(0.035);
   lep2Pt_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleOffset(1);
   lep2Pt_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleFont(42);
   lep2Pt_VV_jetSel_emu_stack_5->GetZaxis()->SetLabelFont(42);
   lep2Pt_VV_jetSel_emu_stack_5->GetZaxis()->SetLabelSize(0.035);
   lep2Pt_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleSize(0.035);
   lep2Pt_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleOffset(1);
   lep2Pt_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_jetSel_emu->Add(lep2Pt_VV_jetSel_emu_stack_5,"");
   
   TH1D *lep2Pt_SingleTop_jetSel_emu_stack_6 = new TH1D("lep2Pt_SingleTop_jetSel_emu_stack_6","lep2Pt_SingleTop_jetSel_emu",20,0,200);
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(3,29.1531);
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(4,69.96327);
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(5,58.19826);
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(6,38.62952);
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(7,25.60644);
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(8,19.83919);
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(9,11.59213);
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(10,7.258689);
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(11,5.729848);
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(12,3.156155);
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(13,2.473721);
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(14,2.044724);
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(15,1.297242);
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(16,1.449787);
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(17,0.566723);
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(18,0.5764523);
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(19,0.4198229);
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(20,0.002197569);
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetBinContent(21,2.263617);
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetEntries(2806);
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetDirectory(0);

   ci = TColor::GetColor("#ff00ff");
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetLineColor(ci);
   lep2Pt_SingleTop_jetSel_emu_stack_6->SetLineWidth(0);
   lep2Pt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetLabelFont(42);
   lep2Pt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetLabelSize(0.035);
   lep2Pt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleSize(0.035);
   lep2Pt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleOffset(1);
   lep2Pt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetLabelFont(42);
   lep2Pt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetLabelSize(0.035);
   lep2Pt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleSize(0.035);
   lep2Pt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleOffset(1);
   lep2Pt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetLabelFont(42);
   lep2Pt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetLabelSize(0.035);
   lep2Pt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleSize(0.035);
   lep2Pt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleOffset(1);
   lep2Pt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_jetSel_emu->Add(lep2Pt_SingleTop_jetSel_emu_stack_6,"");
   
   TH1D *lep2Pt_tt_jetSel_emu_stack_7 = new TH1D("lep2Pt_tt_jetSel_emu_stack_7","lep2Pt_tt_jetSel_emu",20,0,200);
   lep2Pt_tt_jetSel_emu_stack_7->SetBinContent(3,693.9062);
   lep2Pt_tt_jetSel_emu_stack_7->SetBinContent(4,1690.322);
   lep2Pt_tt_jetSel_emu_stack_7->SetBinContent(5,1335.838);
   lep2Pt_tt_jetSel_emu_stack_7->SetBinContent(6,956.2238);
   lep2Pt_tt_jetSel_emu_stack_7->SetBinContent(7,585.8033);
   lep2Pt_tt_jetSel_emu_stack_7->SetBinContent(8,383.2339);
   lep2Pt_tt_jetSel_emu_stack_7->SetBinContent(9,213.648);
   lep2Pt_tt_jetSel_emu_stack_7->SetBinContent(10,129.8858);
   lep2Pt_tt_jetSel_emu_stack_7->SetBinContent(11,79.94992);
   lep2Pt_tt_jetSel_emu_stack_7->SetBinContent(12,56.12348);
   lep2Pt_tt_jetSel_emu_stack_7->SetBinContent(13,34.23952);
   lep2Pt_tt_jetSel_emu_stack_7->SetBinContent(14,20.96642);
   lep2Pt_tt_jetSel_emu_stack_7->SetBinContent(15,19.0646);
   lep2Pt_tt_jetSel_emu_stack_7->SetBinContent(16,10.10801);
   lep2Pt_tt_jetSel_emu_stack_7->SetBinContent(17,7.794744);
   lep2Pt_tt_jetSel_emu_stack_7->SetBinContent(18,4.588562);
   lep2Pt_tt_jetSel_emu_stack_7->SetBinContent(19,4.316655);
   lep2Pt_tt_jetSel_emu_stack_7->SetBinContent(20,3.013465);
   lep2Pt_tt_jetSel_emu_stack_7->SetBinContent(21,9.491429);
   lep2Pt_tt_jetSel_emu_stack_7->SetEntries(19867);
   lep2Pt_tt_jetSel_emu_stack_7->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   lep2Pt_tt_jetSel_emu_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   lep2Pt_tt_jetSel_emu_stack_7->SetLineColor(ci);
   lep2Pt_tt_jetSel_emu_stack_7->SetLineWidth(0);
   lep2Pt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_tt_jetSel_emu_stack_7->GetXaxis()->SetLabelFont(42);
   lep2Pt_tt_jetSel_emu_stack_7->GetXaxis()->SetLabelSize(0.035);
   lep2Pt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleSize(0.035);
   lep2Pt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleOffset(1);
   lep2Pt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleFont(42);
   lep2Pt_tt_jetSel_emu_stack_7->GetYaxis()->SetLabelFont(42);
   lep2Pt_tt_jetSel_emu_stack_7->GetYaxis()->SetLabelSize(0.035);
   lep2Pt_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleSize(0.035);
   lep2Pt_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleOffset(1);
   lep2Pt_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleFont(42);
   lep2Pt_tt_jetSel_emu_stack_7->GetZaxis()->SetLabelFont(42);
   lep2Pt_tt_jetSel_emu_stack_7->GetZaxis()->SetLabelSize(0.035);
   lep2Pt_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleSize(0.035);
   lep2Pt_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleOffset(1);
   lep2Pt_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_jetSel_emu->Add(lep2Pt_tt_jetSel_emu_stack_7,"");
   
   TH1D *lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8 = new TH1D("lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8","lep2Pt_zPlusJetsMadgraph_jetSel_emu",20,0,200);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(3,1.429552);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(4,7.442822);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(5,4.369944);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(6,1.483989);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(9,1.443027);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(21,1.500954);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetEntries(12);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetLineColor(ci);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetLineWidth(0);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetLabelFont(42);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetLabelSize(0.035);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleSize(0.035);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleOffset(1);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleFont(42);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetLabelFont(42);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetLabelSize(0.035);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleSize(0.035);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleOffset(1);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleFont(42);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetLabelFont(42);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetLabelSize(0.035);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleSize(0.035);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleOffset(1);
   lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_jetSel_emu->Add(lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8,"");
   lep2Pt_SingleTop_jetSel_emu->Draw("");
   
   TH1D *lep2Pt_data_jetSel_emu__7 = new TH1D("lep2Pt_data_jetSel_emu__7","lep2Pt_data_jetSel_emu",20,0,200);
   lep2Pt_data_jetSel_emu__7->SetBinContent(3,751);
   lep2Pt_data_jetSel_emu__7->SetBinContent(4,1757);
   lep2Pt_data_jetSel_emu__7->SetBinContent(5,1468);
   lep2Pt_data_jetSel_emu__7->SetBinContent(6,1005);
   lep2Pt_data_jetSel_emu__7->SetBinContent(7,642);
   lep2Pt_data_jetSel_emu__7->SetBinContent(8,384);
   lep2Pt_data_jetSel_emu__7->SetBinContent(9,240);
   lep2Pt_data_jetSel_emu__7->SetBinContent(10,134);
   lep2Pt_data_jetSel_emu__7->SetBinContent(11,100);
   lep2Pt_data_jetSel_emu__7->SetBinContent(12,60);
   lep2Pt_data_jetSel_emu__7->SetBinContent(13,44);
   lep2Pt_data_jetSel_emu__7->SetBinContent(14,20);
   lep2Pt_data_jetSel_emu__7->SetBinContent(15,16);
   lep2Pt_data_jetSel_emu__7->SetBinContent(16,18);
   lep2Pt_data_jetSel_emu__7->SetBinContent(17,6);
   lep2Pt_data_jetSel_emu__7->SetBinContent(18,6);
   lep2Pt_data_jetSel_emu__7->SetBinContent(19,3);
   lep2Pt_data_jetSel_emu__7->SetBinContent(20,2);
   lep2Pt_data_jetSel_emu__7->SetBinContent(21,12);
   lep2Pt_data_jetSel_emu__7->SetEntries(6668);
   lep2Pt_data_jetSel_emu__7->SetDirectory(0);
   lep2Pt_data_jetSel_emu__7->SetFillColor(1);
   lep2Pt_data_jetSel_emu__7->SetLineWidth(2);
   lep2Pt_data_jetSel_emu__7->SetLineColor(1); //
   lep2Pt_data_jetSel_emu__7->SetMarkerStyle(20);
   lep2Pt_data_jetSel_emu__7->SetMarkerSize(1.4);
   lep2Pt_data_jetSel_emu__7->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_data_jetSel_emu__7->GetXaxis()->SetLabelFont(42);
   lep2Pt_data_jetSel_emu__7->GetXaxis()->SetLabelSize(0.035);
   lep2Pt_data_jetSel_emu__7->GetXaxis()->SetTitleSize(0.035);
   lep2Pt_data_jetSel_emu__7->GetXaxis()->SetTitleOffset(1);
   lep2Pt_data_jetSel_emu__7->GetXaxis()->SetTitleFont(42);
   lep2Pt_data_jetSel_emu__7->GetYaxis()->SetLabelFont(42);
   lep2Pt_data_jetSel_emu__7->GetYaxis()->SetLabelSize(0.035);
   lep2Pt_data_jetSel_emu__7->GetYaxis()->SetTitleSize(0.035);
   lep2Pt_data_jetSel_emu__7->GetYaxis()->SetTitleOffset(1);
   lep2Pt_data_jetSel_emu__7->GetYaxis()->SetTitleFont(42);
   lep2Pt_data_jetSel_emu__7->GetZaxis()->SetLabelFont(42);
   lep2Pt_data_jetSel_emu__7->GetZaxis()->SetLabelSize(0.035);
   lep2Pt_data_jetSel_emu__7->GetZaxis()->SetTitleSize(0.035);
   lep2Pt_data_jetSel_emu__7->GetZaxis()->SetTitleOffset(1);
   lep2Pt_data_jetSel_emu__7->GetZaxis()->SetTitleFont(42);
   lep2Pt_data_jetSel_emu__7->Draw("e x0, same");
   
   TLegend *leg = new TLegend(0.78,0.42,0.98,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("lep2Pt_zPlusJetsMadgraph_jetSel_emu_stack_8","Z+jets (LO)","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep2Pt_tt_jetSel_emu_stack_7","t#bar{t}","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep2Pt_SingleTop_jetSel_emu_stack_6","Single top","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep2Pt_VV_jetSel_emu_stack_5","VV","f");

   ci = TColor::GetColor("#ff9933");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep2Pt_VVV_jetSel_emu_stack_4","VVV","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep2Pt_wJets_jetSel_emu_stack_3","W+jets","f");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep2Pt_ttV_jetSel_emu_stack_2","t#bar{t}V","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep2Pt_tZq_jetSel_emu_stack_1","tZq","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep2Pt_data_jetSel_emu","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.4);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.968,0.9429101,"35.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06792969);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.096,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.05419922);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16899,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.04119141);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *lep2Pt_SingleTop_jetSel_emu__8 = new TH1F("lep2Pt_SingleTop_jetSel_emu__8","Muon p_{T}",20,0,200);
   lep2Pt_SingleTop_jetSel_emu__8->SetMinimum(0);
   lep2Pt_SingleTop_jetSel_emu__8->SetMaximum(2075.841);
   lep2Pt_SingleTop_jetSel_emu__8->SetDirectory(0);
   lep2Pt_SingleTop_jetSel_emu__8->SetStats(0);
   lep2Pt_SingleTop_jetSel_emu__8->SetLineStyle(0);
   lep2Pt_SingleTop_jetSel_emu__8->SetLineWidth(0);
   lep2Pt_SingleTop_jetSel_emu__8->SetMarkerStyle(20);
   lep2Pt_SingleTop_jetSel_emu__8->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_SingleTop_jetSel_emu__8->GetXaxis()->SetNdivisions(506);
   lep2Pt_SingleTop_jetSel_emu__8->GetXaxis()->SetLabelFont(42);
   lep2Pt_SingleTop_jetSel_emu__8->GetXaxis()->SetLabelOffset(999);
   lep2Pt_SingleTop_jetSel_emu__8->GetXaxis()->SetLabelSize(0.05);
   lep2Pt_SingleTop_jetSel_emu__8->GetXaxis()->SetTitleSize(0.08);
   lep2Pt_SingleTop_jetSel_emu__8->GetXaxis()->SetTitleOffset(1);
   lep2Pt_SingleTop_jetSel_emu__8->GetXaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_jetSel_emu__8->GetYaxis()->SetTitle("Events");
   lep2Pt_SingleTop_jetSel_emu__8->GetYaxis()->SetNdivisions(506);
   lep2Pt_SingleTop_jetSel_emu__8->GetYaxis()->SetLabelFont(42);
   lep2Pt_SingleTop_jetSel_emu__8->GetYaxis()->SetLabelOffset(0.01);
   lep2Pt_SingleTop_jetSel_emu__8->GetYaxis()->SetLabelSize(0.062);
   lep2Pt_SingleTop_jetSel_emu__8->GetYaxis()->SetTitleSize(0.08);
   lep2Pt_SingleTop_jetSel_emu__8->GetYaxis()->SetTitleOffset(0.6336);
   lep2Pt_SingleTop_jetSel_emu__8->GetYaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_jetSel_emu__8->GetZaxis()->SetLabelFont(42);
   lep2Pt_SingleTop_jetSel_emu__8->GetZaxis()->SetLabelOffset(0.007);
   lep2Pt_SingleTop_jetSel_emu__8->GetZaxis()->SetLabelSize(0.05);
   lep2Pt_SingleTop_jetSel_emu__8->GetZaxis()->SetTitleSize(0.08);
   lep2Pt_SingleTop_jetSel_emu__8->GetZaxis()->SetTitleOffset(1);
   lep2Pt_SingleTop_jetSel_emu__8->GetZaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_jetSel_emu__8->Draw("sameaxis");
   
   TPaveText *pt = new TPaveText(0.4053652,0.9203237,0.5946348,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Muon p_{T}");
   pt->Draw();
   canvy_1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: canvy_2
   TPad *canvy_2 = new TPad("canvy_2", "newpad2",0.01,0.01,0.99,0.322);
   canvy_2->Draw();
   canvy_2->cd();
   canvy_2->SetFillColor(0);
   canvy_2->SetBorderMode(0);
   canvy_2->SetGridy();

   canvy_2->SetLeftMargin( L/W );
   canvy_2->SetRightMargin( R/W );
   canvy_2->SetTopMargin( T/H );
   canvy_2->SetBottomMargin( B/H * 2.6 );
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   
   TH1D *lep2Pt_data_jetSel_emu__9 = new TH1D("lep2Pt_data_jetSel_emu__9","",20,0,200);
   lep2Pt_data_jetSel_emu__9->SetBinContent(3,1.01721);
   lep2Pt_data_jetSel_emu__9->SetBinContent(4,0.9775966);
   lep2Pt_data_jetSel_emu__9->SetBinContent(5,1.033633);
   lep2Pt_data_jetSel_emu__9->SetBinContent(6,0.9792756);
   lep2Pt_data_jetSel_emu__9->SetBinContent(7,1.011605);
   lep2Pt_data_jetSel_emu__9->SetBinContent(8,0.9323692);
   lep2Pt_data_jetSel_emu__9->SetBinContent(9,1.033451);
   lep2Pt_data_jetSel_emu__9->SetBinContent(10,0.9483795);
   lep2Pt_data_jetSel_emu__9->SetBinContent(11,1.12087);
   lep2Pt_data_jetSel_emu__9->SetBinContent(12,0.9824428);
   lep2Pt_data_jetSel_emu__9->SetBinContent(13,1.161105);
   lep2Pt_data_jetSel_emu__9->SetBinContent(14,0.8333661);
   lep2Pt_data_jetSel_emu__9->SetBinContent(15,0.7635178);
   lep2Pt_data_jetSel_emu__9->SetBinContent(16,1.482947);
   lep2Pt_data_jetSel_emu__9->SetBinContent(17,0.6979244);
   lep2Pt_data_jetSel_emu__9->SetBinContent(18,1.198169);
   lep2Pt_data_jetSel_emu__9->SetBinContent(19,0.5993275);
   lep2Pt_data_jetSel_emu__9->SetBinContent(20,0.5706777);
   lep2Pt_data_jetSel_emu__9->SetBinContent(21,0.7898941);
   lep2Pt_data_jetSel_emu__9->SetBinError(3,0.05271889);
   lep2Pt_data_jetSel_emu__9->SetBinError(4,0.03279764);
   lep2Pt_data_jetSel_emu__9->SetBinError(5,0.03847157);
   lep2Pt_data_jetSel_emu__9->SetBinError(6,0.04345853);
   lep2Pt_data_jetSel_emu__9->SetBinError(7,0.05662589);
   lep2Pt_data_jetSel_emu__9->SetBinError(8,0.06614048);
   lep2Pt_data_jetSel_emu__9->SetBinError(9,0.09512644);
   lep2Pt_data_jetSel_emu__9->SetBinError(10,0.114358);
   lep2Pt_data_jetSel_emu__9->SetBinError(11,0.1632346);
   lep2Pt_data_jetSel_emu__9->SetBinError(12,0.1785796);
   lep2Pt_data_jetSel_emu__9->SetBinError(13,0.2573257);
   lep2Pt_data_jetSel_emu__9->SetBinError(14,0.2523164);
   lep2Pt_data_jetSel_emu__9->SetBinError(15,0.2534832);
   lep2Pt_data_jetSel_emu__9->SetBinError(16,0.5507735);
   lep2Pt_data_jetSel_emu__9->SetBinError(17,0.3712718);
   lep2Pt_data_jetSel_emu__9->SetBinError(18,0.7252256);
   lep2Pt_data_jetSel_emu__9->SetBinError(19,0.4375949);
   lep2Pt_data_jetSel_emu__9->SetBinError(20,0.5057308);
   lep2Pt_data_jetSel_emu__9->SetBinError(21,0.3050647);
   lep2Pt_data_jetSel_emu__9->SetMinimum(0.5);
   lep2Pt_data_jetSel_emu__9->SetMaximum(1.5);
   lep2Pt_data_jetSel_emu__9->SetEntries(176.5315);
   lep2Pt_data_jetSel_emu__9->SetDirectory(0);
   lep2Pt_data_jetSel_emu__9->SetStats(0);
   lep2Pt_data_jetSel_emu__9->SetFillColor(1);
   lep2Pt_data_jetSel_emu__9->SetLineWidth(2);
   lep2Pt_data_jetSel_emu__9->SetLineColor(1); //
   lep2Pt_data_jetSel_emu__9->SetMarkerStyle(20);
   lep2Pt_data_jetSel_emu__9->SetMarkerSize(1.6);
   lep2Pt_data_jetSel_emu__9->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_data_jetSel_emu__9->GetXaxis()->SetNdivisions(506);
   lep2Pt_data_jetSel_emu__9->GetXaxis()->SetLabelFont(42);
   lep2Pt_data_jetSel_emu__9->GetXaxis()->SetLabelOffset(0.013);
   lep2Pt_data_jetSel_emu__9->GetXaxis()->SetLabelSize(0.13);
   lep2Pt_data_jetSel_emu__9->GetXaxis()->SetTitleSize(0.13);
   lep2Pt_data_jetSel_emu__9->GetXaxis()->SetTitleOffset(1);
   lep2Pt_data_jetSel_emu__9->GetXaxis()->SetTitleFont(42);
   lep2Pt_data_jetSel_emu__9->GetYaxis()->SetTitle("Data/MC");
   lep2Pt_data_jetSel_emu__9->GetYaxis()->CenterTitle(true);
   lep2Pt_data_jetSel_emu__9->GetYaxis()->SetNdivisions(506);
   lep2Pt_data_jetSel_emu__9->GetYaxis()->SetLabelFont(42);
   lep2Pt_data_jetSel_emu__9->GetYaxis()->SetLabelOffset(0.01);
   lep2Pt_data_jetSel_emu__9->GetYaxis()->SetLabelSize(0.12);
   lep2Pt_data_jetSel_emu__9->GetYaxis()->SetTitleSize(0.16);
   lep2Pt_data_jetSel_emu__9->GetYaxis()->SetTitleOffset(0.3);
   lep2Pt_data_jetSel_emu__9->GetYaxis()->SetTitleFont(42);
   lep2Pt_data_jetSel_emu__9->GetZaxis()->SetLabelFont(42);
   lep2Pt_data_jetSel_emu__9->GetZaxis()->SetLabelSize(0.035);
   lep2Pt_data_jetSel_emu__9->GetZaxis()->SetTitleSize(0.035);
   lep2Pt_data_jetSel_emu__9->GetZaxis()->SetTitleOffset(1);
   lep2Pt_data_jetSel_emu__9->GetZaxis()->SetTitleFont(42);
   lep2Pt_data_jetSel_emu__9->Draw("e x0, SCAT");
   canvy_2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
//   c1->SetSelected(lep2Pt_data_jetSel_emu);
   c1->SaveAs("lep2Pt_jetSel.pdf");
}
