void lep2Pt_SingleTop_wMass()
{
//=========Macro generated from canvas: lep2Pt_SingleTop_wMass/lep2Pt_SingleTop_wMass
//=========  (Wed Aug 21 20:26:32 2019) by ROOT version 6.18/00

   // Set up cavas
   int W = 1280;
   int H = 1024;
   int H_ref = 925;
   int W_ref = 1024;

   // references for T, B, L, R
   float T = 0.08*H_ref;
   float B = 0.12*H_ref;
   float L = 0.12*W_ref;
   float R = 0.04*W_ref;

   TCanvas *c1 = new TCanvas("c1","c1",50,50,W,H);
   c1->cd();
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetLeftMargin( L/W );
   c1->SetRightMargin( R/W );
   c1->SetTopMargin( T/H );
   c1->SetBottomMargin( B/H );
   c1->SetTickx(0);
   c1->SetTicky(0);

// ------------>Primitives in pad: canvy_1
   TPad *canvy_1 = new TPad("canvy_1", "newpad",0.01,0.315,0.99,0.99);
   canvy_1->Draw();
   canvy_1->cd();
   canvy_1->SetFillColor(0);
   canvy_1->SetBorderMode(0);

   canvy_1->SetLeftMargin( L/W );
   canvy_1->SetRightMargin( R/W );
   canvy_1->SetTopMargin( T/H );
   canvy_1->SetBottomMargin( B/H * 0.3 );

   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);
   
   THStack *lep2Pt_SingleTop_wMass_emu = new THStack();
   lep2Pt_SingleTop_wMass_emu->SetName("lep2Pt_SingleTop_wMass_emu");
   lep2Pt_SingleTop_wMass_emu->SetTitle("Muon p_{T};Muon p_{T} (GeV);Events");
   lep2Pt_SingleTop_wMass_emu->SetMaximum(797.5);
   
   TH1F *lep2Pt_SingleTop_wMass_emu_stack_1 = new TH1F("lep2Pt_SingleTop_wMass_emu_stack_1","Muon p_{T}",20,0,200);
   lep2Pt_SingleTop_wMass_emu_stack_1->SetMinimum(0);
   lep2Pt_SingleTop_wMass_emu_stack_1->SetMaximum(837.375);
   lep2Pt_SingleTop_wMass_emu_stack_1->SetDirectory(0);
   lep2Pt_SingleTop_wMass_emu_stack_1->SetStats(0);
   lep2Pt_SingleTop_wMass_emu_stack_1->SetLineStyle(0);
   lep2Pt_SingleTop_wMass_emu_stack_1->SetLineWidth(0);
   lep2Pt_SingleTop_wMass_emu_stack_1->SetMarkerStyle(20);
   lep2Pt_SingleTop_wMass_emu_stack_1->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_SingleTop_wMass_emu_stack_1->GetXaxis()->SetNdivisions(506);
   lep2Pt_SingleTop_wMass_emu_stack_1->GetXaxis()->SetLabelFont(42);
   lep2Pt_SingleTop_wMass_emu_stack_1->GetXaxis()->SetLabelOffset(999);
   lep2Pt_SingleTop_wMass_emu_stack_1->GetXaxis()->SetLabelSize(0.05);
   lep2Pt_SingleTop_wMass_emu_stack_1->GetXaxis()->SetTitleSize(0.08);
   lep2Pt_SingleTop_wMass_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   lep2Pt_SingleTop_wMass_emu_stack_1->GetXaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_wMass_emu_stack_1->GetYaxis()->SetTitle("Events");
   lep2Pt_SingleTop_wMass_emu_stack_1->GetYaxis()->SetNdivisions(506);
   lep2Pt_SingleTop_wMass_emu_stack_1->GetYaxis()->SetLabelFont(42);
   lep2Pt_SingleTop_wMass_emu_stack_1->GetYaxis()->SetLabelOffset(0.01);
   lep2Pt_SingleTop_wMass_emu_stack_1->GetYaxis()->SetLabelSize(0.062);
   lep2Pt_SingleTop_wMass_emu_stack_1->GetYaxis()->SetTitleSize(0.08);
   lep2Pt_SingleTop_wMass_emu_stack_1->GetYaxis()->SetTitleOffset(0.6336);
   lep2Pt_SingleTop_wMass_emu_stack_1->GetYaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_wMass_emu_stack_1->GetZaxis()->SetLabelFont(42);
   lep2Pt_SingleTop_wMass_emu_stack_1->GetZaxis()->SetLabelOffset(0.007);
   lep2Pt_SingleTop_wMass_emu_stack_1->GetZaxis()->SetLabelSize(0.05);
   lep2Pt_SingleTop_wMass_emu_stack_1->GetZaxis()->SetTitleSize(0.08);
   lep2Pt_SingleTop_wMass_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   lep2Pt_SingleTop_wMass_emu_stack_1->GetZaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_wMass_emu->SetHistogram(lep2Pt_SingleTop_wMass_emu_stack_1);
   
   
   TH1D *lep2Pt_tZq_wMass_emu_stack_1 = new TH1D("lep2Pt_tZq_wMass_emu_stack_1","lep2Pt_tZq_wMass_emu",20,0,200);
   lep2Pt_tZq_wMass_emu_stack_1->SetBinContent(3,0.04294236);
   lep2Pt_tZq_wMass_emu_stack_1->SetBinContent(4,0.09963492);
   lep2Pt_tZq_wMass_emu_stack_1->SetBinContent(5,0.07041243);
   lep2Pt_tZq_wMass_emu_stack_1->SetBinContent(6,0.03207358);
   lep2Pt_tZq_wMass_emu_stack_1->SetBinContent(7,0.04620148);
   lep2Pt_tZq_wMass_emu_stack_1->SetBinContent(8,0.01270933);
   lep2Pt_tZq_wMass_emu_stack_1->SetBinContent(9,0.006509973);
   lep2Pt_tZq_wMass_emu_stack_1->SetBinContent(10,-0.000391138);
   lep2Pt_tZq_wMass_emu_stack_1->SetBinContent(11,0.006035855);
   lep2Pt_tZq_wMass_emu_stack_1->SetBinContent(12,0.00892478);
   lep2Pt_tZq_wMass_emu_stack_1->SetBinContent(13,0.001270054);
   lep2Pt_tZq_wMass_emu_stack_1->SetBinContent(14,0.006765117);
   lep2Pt_tZq_wMass_emu_stack_1->SetBinContent(15,0.002587442);
   lep2Pt_tZq_wMass_emu_stack_1->SetBinContent(16,0.000684807);
   lep2Pt_tZq_wMass_emu_stack_1->SetBinContent(17,0.0002988347);
   lep2Pt_tZq_wMass_emu_stack_1->SetBinContent(18,0.001378487);
   lep2Pt_tZq_wMass_emu_stack_1->SetBinContent(19,0.0006204054);
   lep2Pt_tZq_wMass_emu_stack_1->SetBinContent(20,0.002093084);
   lep2Pt_tZq_wMass_emu_stack_1->SetBinContent(21,0.00365662);
   lep2Pt_tZq_wMass_emu_stack_1->SetEntries(2170);
   lep2Pt_tZq_wMass_emu_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ffff00");
   lep2Pt_tZq_wMass_emu_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   lep2Pt_tZq_wMass_emu_stack_1->SetLineColor(ci);
   lep2Pt_tZq_wMass_emu_stack_1->SetLineWidth(0);
   lep2Pt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_tZq_wMass_emu_stack_1->GetXaxis()->SetLabelFont(42);
   lep2Pt_tZq_wMass_emu_stack_1->GetXaxis()->SetLabelSize(0.035);
   lep2Pt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleSize(0.035);
   lep2Pt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   lep2Pt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleFont(42);
   lep2Pt_tZq_wMass_emu_stack_1->GetYaxis()->SetLabelFont(42);
   lep2Pt_tZq_wMass_emu_stack_1->GetYaxis()->SetLabelSize(0.035);
   lep2Pt_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleSize(0.035);
   lep2Pt_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleOffset(1);
   lep2Pt_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleFont(42);
   lep2Pt_tZq_wMass_emu_stack_1->GetZaxis()->SetLabelFont(42);
   lep2Pt_tZq_wMass_emu_stack_1->GetZaxis()->SetLabelSize(0.035);
   lep2Pt_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleSize(0.035);
   lep2Pt_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   lep2Pt_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_wMass_emu->Add(lep2Pt_tZq_wMass_emu_stack_1,"");
   
   TH1D *lep2Pt_ttV_wMass_emu_stack_2 = new TH1D("lep2Pt_ttV_wMass_emu_stack_2","lep2Pt_ttV_wMass_emu",20,0,200);
   lep2Pt_ttV_wMass_emu_stack_2->SetBinContent(3,3.445553);
   lep2Pt_ttV_wMass_emu_stack_2->SetBinContent(4,7.568688);
   lep2Pt_ttV_wMass_emu_stack_2->SetBinContent(5,6.315018);
   lep2Pt_ttV_wMass_emu_stack_2->SetBinContent(6,3.773973);
   lep2Pt_ttV_wMass_emu_stack_2->SetBinContent(7,2.128696);
   lep2Pt_ttV_wMass_emu_stack_2->SetBinContent(8,1.451653);
   lep2Pt_ttV_wMass_emu_stack_2->SetBinContent(9,1.041781);
   lep2Pt_ttV_wMass_emu_stack_2->SetBinContent(10,0.5903559);
   lep2Pt_ttV_wMass_emu_stack_2->SetBinContent(11,0.4889144);
   lep2Pt_ttV_wMass_emu_stack_2->SetBinContent(12,0.2896291);
   lep2Pt_ttV_wMass_emu_stack_2->SetBinContent(13,0.1625545);
   lep2Pt_ttV_wMass_emu_stack_2->SetBinContent(14,0.2243093);
   lep2Pt_ttV_wMass_emu_stack_2->SetBinContent(15,0.1636108);
   lep2Pt_ttV_wMass_emu_stack_2->SetBinContent(16,0.04829576);
   lep2Pt_ttV_wMass_emu_stack_2->SetBinContent(17,0.03663702);
   lep2Pt_ttV_wMass_emu_stack_2->SetBinContent(18,0.02485229);
   lep2Pt_ttV_wMass_emu_stack_2->SetBinContent(19,0.05147906);
   lep2Pt_ttV_wMass_emu_stack_2->SetBinContent(20,0.02653998);
   lep2Pt_ttV_wMass_emu_stack_2->SetBinContent(21,0.04662938);
   lep2Pt_ttV_wMass_emu_stack_2->SetEntries(14144);
   lep2Pt_ttV_wMass_emu_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#00ff00");
   lep2Pt_ttV_wMass_emu_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   lep2Pt_ttV_wMass_emu_stack_2->SetLineColor(ci);
   lep2Pt_ttV_wMass_emu_stack_2->SetLineWidth(0);
   lep2Pt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_ttV_wMass_emu_stack_2->GetXaxis()->SetLabelFont(42);
   lep2Pt_ttV_wMass_emu_stack_2->GetXaxis()->SetLabelSize(0.035);
   lep2Pt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleSize(0.035);
   lep2Pt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   lep2Pt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleFont(42);
   lep2Pt_ttV_wMass_emu_stack_2->GetYaxis()->SetLabelFont(42);
   lep2Pt_ttV_wMass_emu_stack_2->GetYaxis()->SetLabelSize(0.035);
   lep2Pt_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleSize(0.035);
   lep2Pt_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleOffset(1);
   lep2Pt_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleFont(42);
   lep2Pt_ttV_wMass_emu_stack_2->GetZaxis()->SetLabelFont(42);
   lep2Pt_ttV_wMass_emu_stack_2->GetZaxis()->SetLabelSize(0.035);
   lep2Pt_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleSize(0.035);
   lep2Pt_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   lep2Pt_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_wMass_emu->Add(lep2Pt_ttV_wMass_emu_stack_2,"");
   
   TH1D *lep2Pt_wJets_wMass_emu_stack_3 = new TH1D("lep2Pt_wJets_wMass_emu_stack_3","lep2Pt_wJets_wMass_emu",20,0,200);
   lep2Pt_wJets_wMass_emu_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   lep2Pt_wJets_wMass_emu_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#cccccc");
   lep2Pt_wJets_wMass_emu_stack_3->SetLineColor(ci);
   lep2Pt_wJets_wMass_emu_stack_3->SetLineWidth(0);
   lep2Pt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_wJets_wMass_emu_stack_3->GetXaxis()->SetLabelFont(42);
   lep2Pt_wJets_wMass_emu_stack_3->GetXaxis()->SetLabelSize(0.035);
   lep2Pt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleSize(0.035);
   lep2Pt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   lep2Pt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleFont(42);
   lep2Pt_wJets_wMass_emu_stack_3->GetYaxis()->SetLabelFont(42);
   lep2Pt_wJets_wMass_emu_stack_3->GetYaxis()->SetLabelSize(0.035);
   lep2Pt_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleSize(0.035);
   lep2Pt_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleOffset(1);
   lep2Pt_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleFont(42);
   lep2Pt_wJets_wMass_emu_stack_3->GetZaxis()->SetLabelFont(42);
   lep2Pt_wJets_wMass_emu_stack_3->GetZaxis()->SetLabelSize(0.035);
   lep2Pt_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleSize(0.035);
   lep2Pt_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   lep2Pt_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_wMass_emu->Add(lep2Pt_wJets_wMass_emu_stack_3,"");
   
   TH1D *lep2Pt_VVV_wMass_emu_stack_4 = new TH1D("lep2Pt_VVV_wMass_emu_stack_4","lep2Pt_VVV_wMass_emu",20,0,200);
   lep2Pt_VVV_wMass_emu_stack_4->SetBinContent(3,0.03392089);
   lep2Pt_VVV_wMass_emu_stack_4->SetBinContent(4,0.03424756);
   lep2Pt_VVV_wMass_emu_stack_4->SetBinContent(5,0.02384236);
   lep2Pt_VVV_wMass_emu_stack_4->SetBinContent(6,0.02946448);
   lep2Pt_VVV_wMass_emu_stack_4->SetBinContent(8,0.03458785);
   lep2Pt_VVV_wMass_emu_stack_4->SetBinContent(10,0.03368239);
   lep2Pt_VVV_wMass_emu_stack_4->SetBinContent(12,0.001068281);
   lep2Pt_VVV_wMass_emu_stack_4->SetBinContent(14,0.033447);
   lep2Pt_VVV_wMass_emu_stack_4->SetEntries(9);
   lep2Pt_VVV_wMass_emu_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#00ffff");
   lep2Pt_VVV_wMass_emu_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   lep2Pt_VVV_wMass_emu_stack_4->SetLineColor(ci);
   lep2Pt_VVV_wMass_emu_stack_4->SetLineWidth(0);
   lep2Pt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_VVV_wMass_emu_stack_4->GetXaxis()->SetLabelFont(42);
   lep2Pt_VVV_wMass_emu_stack_4->GetXaxis()->SetLabelSize(0.035);
   lep2Pt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleSize(0.035);
   lep2Pt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   lep2Pt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleFont(42);
   lep2Pt_VVV_wMass_emu_stack_4->GetYaxis()->SetLabelFont(42);
   lep2Pt_VVV_wMass_emu_stack_4->GetYaxis()->SetLabelSize(0.035);
   lep2Pt_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleSize(0.035);
   lep2Pt_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleOffset(1);
   lep2Pt_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleFont(42);
   lep2Pt_VVV_wMass_emu_stack_4->GetZaxis()->SetLabelFont(42);
   lep2Pt_VVV_wMass_emu_stack_4->GetZaxis()->SetLabelSize(0.035);
   lep2Pt_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleSize(0.035);
   lep2Pt_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   lep2Pt_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_wMass_emu->Add(lep2Pt_VVV_wMass_emu_stack_4,"");
   
   TH1D *lep2Pt_VV_wMass_emu_stack_5 = new TH1D("lep2Pt_VV_wMass_emu_stack_5","lep2Pt_VV_wMass_emu",20,0,200);
   lep2Pt_VV_wMass_emu_stack_5->SetBinContent(3,-0.001656415);
   lep2Pt_VV_wMass_emu_stack_5->SetBinContent(4,0.5047474);
   lep2Pt_VV_wMass_emu_stack_5->SetBinContent(5,0.2505178);
   lep2Pt_VV_wMass_emu_stack_5->SetBinContent(6,0.3263071);
   lep2Pt_VV_wMass_emu_stack_5->SetBinContent(7,0.01953587);
   lep2Pt_VV_wMass_emu_stack_5->SetBinContent(8,0.3996126);
   lep2Pt_VV_wMass_emu_stack_5->SetBinContent(9,0.2619576);
   lep2Pt_VV_wMass_emu_stack_5->SetBinContent(10,0.208869);
   lep2Pt_VV_wMass_emu_stack_5->SetBinContent(12,0.2072768);
   lep2Pt_VV_wMass_emu_stack_5->SetBinContent(15,-0.007183164);
   lep2Pt_VV_wMass_emu_stack_5->SetBinContent(16,-0.01148484);
   lep2Pt_VV_wMass_emu_stack_5->SetBinContent(21,0.3211187);
   lep2Pt_VV_wMass_emu_stack_5->SetEntries(45);
   lep2Pt_VV_wMass_emu_stack_5->SetDirectory(0);

   ci = TColor::GetColor("#ff9933");
   lep2Pt_VV_wMass_emu_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#ff9933");
   lep2Pt_VV_wMass_emu_stack_5->SetLineColor(ci);
   lep2Pt_VV_wMass_emu_stack_5->SetLineWidth(0);
   lep2Pt_VV_wMass_emu_stack_5->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_VV_wMass_emu_stack_5->GetXaxis()->SetLabelFont(42);
   lep2Pt_VV_wMass_emu_stack_5->GetXaxis()->SetLabelSize(0.035);
   lep2Pt_VV_wMass_emu_stack_5->GetXaxis()->SetTitleSize(0.035);
   lep2Pt_VV_wMass_emu_stack_5->GetXaxis()->SetTitleOffset(1);
   lep2Pt_VV_wMass_emu_stack_5->GetXaxis()->SetTitleFont(42);
   lep2Pt_VV_wMass_emu_stack_5->GetYaxis()->SetLabelFont(42);
   lep2Pt_VV_wMass_emu_stack_5->GetYaxis()->SetLabelSize(0.035);
   lep2Pt_VV_wMass_emu_stack_5->GetYaxis()->SetTitleSize(0.035);
   lep2Pt_VV_wMass_emu_stack_5->GetYaxis()->SetTitleOffset(1);
   lep2Pt_VV_wMass_emu_stack_5->GetYaxis()->SetTitleFont(42);
   lep2Pt_VV_wMass_emu_stack_5->GetZaxis()->SetLabelFont(42);
   lep2Pt_VV_wMass_emu_stack_5->GetZaxis()->SetLabelSize(0.035);
   lep2Pt_VV_wMass_emu_stack_5->GetZaxis()->SetTitleSize(0.035);
   lep2Pt_VV_wMass_emu_stack_5->GetZaxis()->SetTitleOffset(1);
   lep2Pt_VV_wMass_emu_stack_5->GetZaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_wMass_emu->Add(lep2Pt_VV_wMass_emu_stack_5,"");
   
   TH1D *lep2Pt_SingleTop_wMass_emu_stack_6 = new TH1D("lep2Pt_SingleTop_wMass_emu_stack_6","lep2Pt_SingleTop_wMass_emu",20,0,200);
   lep2Pt_SingleTop_wMass_emu_stack_6->SetBinContent(3,12.3196);
   lep2Pt_SingleTop_wMass_emu_stack_6->SetBinContent(4,26.16135);
   lep2Pt_SingleTop_wMass_emu_stack_6->SetBinContent(5,19.09807);
   lep2Pt_SingleTop_wMass_emu_stack_6->SetBinContent(6,14.0155);
   lep2Pt_SingleTop_wMass_emu_stack_6->SetBinContent(7,10.8084);
   lep2Pt_SingleTop_wMass_emu_stack_6->SetBinContent(8,6.317987);
   lep2Pt_SingleTop_wMass_emu_stack_6->SetBinContent(9,4.975805);
   lep2Pt_SingleTop_wMass_emu_stack_6->SetBinContent(10,3.299694);
   lep2Pt_SingleTop_wMass_emu_stack_6->SetBinContent(11,1.470336);
   lep2Pt_SingleTop_wMass_emu_stack_6->SetBinContent(12,1.119433);
   lep2Pt_SingleTop_wMass_emu_stack_6->SetBinContent(13,1.317393);
   lep2Pt_SingleTop_wMass_emu_stack_6->SetBinContent(14,0.8392139);
   lep2Pt_SingleTop_wMass_emu_stack_6->SetBinContent(15,0.5718217);
   lep2Pt_SingleTop_wMass_emu_stack_6->SetBinContent(16,0.6671192);
   lep2Pt_SingleTop_wMass_emu_stack_6->SetBinContent(17,0.3682432);
   lep2Pt_SingleTop_wMass_emu_stack_6->SetBinContent(18,0.181124);
   lep2Pt_SingleTop_wMass_emu_stack_6->SetBinContent(19,0.4190318);
   lep2Pt_SingleTop_wMass_emu_stack_6->SetBinContent(20,0.0008489289);
   lep2Pt_SingleTop_wMass_emu_stack_6->SetBinContent(21,0.7831759);
   lep2Pt_SingleTop_wMass_emu_stack_6->SetEntries(1034);
   lep2Pt_SingleTop_wMass_emu_stack_6->SetDirectory(0);

   ci = TColor::GetColor("#ff00ff");
   lep2Pt_SingleTop_wMass_emu_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   lep2Pt_SingleTop_wMass_emu_stack_6->SetLineColor(ci);
   lep2Pt_SingleTop_wMass_emu_stack_6->SetLineWidth(0);
   lep2Pt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetLabelFont(42);
   lep2Pt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetLabelSize(0.035);
   lep2Pt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleSize(0.035);
   lep2Pt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleOffset(1);
   lep2Pt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetLabelFont(42);
   lep2Pt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetLabelSize(0.035);
   lep2Pt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleSize(0.035);
   lep2Pt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleOffset(1);
   lep2Pt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetLabelFont(42);
   lep2Pt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetLabelSize(0.035);
   lep2Pt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleSize(0.035);
   lep2Pt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleOffset(1);
   lep2Pt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_wMass_emu->Add(lep2Pt_SingleTop_wMass_emu_stack_6,"");
   
   TH1D *lep2Pt_tt_wMass_emu_stack_7 = new TH1D("lep2Pt_tt_wMass_emu_stack_7","lep2Pt_tt_wMass_emu",20,0,200);
   lep2Pt_tt_wMass_emu_stack_7->SetBinContent(3,259.4419);
   lep2Pt_tt_wMass_emu_stack_7->SetBinContent(4,637.791);
   lep2Pt_tt_wMass_emu_stack_7->SetBinContent(5,526.7444);
   lep2Pt_tt_wMass_emu_stack_7->SetBinContent(6,377.0084);
   lep2Pt_tt_wMass_emu_stack_7->SetBinContent(7,226.609);
   lep2Pt_tt_wMass_emu_stack_7->SetBinContent(8,146.3421);
   lep2Pt_tt_wMass_emu_stack_7->SetBinContent(9,77.93277);
   lep2Pt_tt_wMass_emu_stack_7->SetBinContent(10,55.58388);
   lep2Pt_tt_wMass_emu_stack_7->SetBinContent(11,31.55909);
   lep2Pt_tt_wMass_emu_stack_7->SetBinContent(12,22.22732);
   lep2Pt_tt_wMass_emu_stack_7->SetBinContent(13,14.49975);
   lep2Pt_tt_wMass_emu_stack_7->SetBinContent(14,8.087653);
   lep2Pt_tt_wMass_emu_stack_7->SetBinContent(15,7.302232);
   lep2Pt_tt_wMass_emu_stack_7->SetBinContent(16,4.618066);
   lep2Pt_tt_wMass_emu_stack_7->SetBinContent(17,1.795727);
   lep2Pt_tt_wMass_emu_stack_7->SetBinContent(18,0.6896248);
   lep2Pt_tt_wMass_emu_stack_7->SetBinContent(19,0.3351719);
   lep2Pt_tt_wMass_emu_stack_7->SetBinContent(20,0.3196447);
   lep2Pt_tt_wMass_emu_stack_7->SetBinContent(21,1.891184);
   lep2Pt_tt_wMass_emu_stack_7->SetEntries(7802);
   lep2Pt_tt_wMass_emu_stack_7->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   lep2Pt_tt_wMass_emu_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   lep2Pt_tt_wMass_emu_stack_7->SetLineColor(ci);
   lep2Pt_tt_wMass_emu_stack_7->SetLineWidth(0);
   lep2Pt_tt_wMass_emu_stack_7->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_tt_wMass_emu_stack_7->GetXaxis()->SetLabelFont(42);
   lep2Pt_tt_wMass_emu_stack_7->GetXaxis()->SetLabelSize(0.035);
   lep2Pt_tt_wMass_emu_stack_7->GetXaxis()->SetTitleSize(0.035);
   lep2Pt_tt_wMass_emu_stack_7->GetXaxis()->SetTitleOffset(1);
   lep2Pt_tt_wMass_emu_stack_7->GetXaxis()->SetTitleFont(42);
   lep2Pt_tt_wMass_emu_stack_7->GetYaxis()->SetLabelFont(42);
   lep2Pt_tt_wMass_emu_stack_7->GetYaxis()->SetLabelSize(0.035);
   lep2Pt_tt_wMass_emu_stack_7->GetYaxis()->SetTitleSize(0.035);
   lep2Pt_tt_wMass_emu_stack_7->GetYaxis()->SetTitleOffset(1);
   lep2Pt_tt_wMass_emu_stack_7->GetYaxis()->SetTitleFont(42);
   lep2Pt_tt_wMass_emu_stack_7->GetZaxis()->SetLabelFont(42);
   lep2Pt_tt_wMass_emu_stack_7->GetZaxis()->SetLabelSize(0.035);
   lep2Pt_tt_wMass_emu_stack_7->GetZaxis()->SetTitleSize(0.035);
   lep2Pt_tt_wMass_emu_stack_7->GetZaxis()->SetTitleOffset(1);
   lep2Pt_tt_wMass_emu_stack_7->GetZaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_wMass_emu->Add(lep2Pt_tt_wMass_emu_stack_7,"");
   
   TH1D *lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8 = new TH1D("lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8","lep2Pt_zPlusJetsMadgraph_wMass_emu",20,0,200);
   lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8->SetLineColor(ci);
   lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8->SetLineWidth(0);
   lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetLabelFont(42);
   lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetLabelSize(0.035);
   lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleSize(0.035);
   lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleOffset(1);
   lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleFont(42);
   lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetLabelFont(42);
   lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetLabelSize(0.035);
   lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleSize(0.035);
   lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleOffset(1);
   lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleFont(42);
   lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetLabelFont(42);
   lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetLabelSize(0.035);
   lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleSize(0.035);
   lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleOffset(1);
   lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_wMass_emu->Add(lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8,"");
   lep2Pt_SingleTop_wMass_emu->Draw("");
   
   TH1D *lep2Pt_data_wMass_emu__1 = new TH1D("lep2Pt_data_wMass_emu__1","lep2Pt_data_wMass_emu",20,0,200);
   lep2Pt_data_wMass_emu__1->SetBinContent(3,303);
   lep2Pt_data_wMass_emu__1->SetBinContent(4,725);
   lep2Pt_data_wMass_emu__1->SetBinContent(5,602);
   lep2Pt_data_wMass_emu__1->SetBinContent(6,405);
   lep2Pt_data_wMass_emu__1->SetBinContent(7,234);
   lep2Pt_data_wMass_emu__1->SetBinContent(8,154);
   lep2Pt_data_wMass_emu__1->SetBinContent(9,102);
   lep2Pt_data_wMass_emu__1->SetBinContent(10,55);
   lep2Pt_data_wMass_emu__1->SetBinContent(11,34);
   lep2Pt_data_wMass_emu__1->SetBinContent(12,17);
   lep2Pt_data_wMass_emu__1->SetBinContent(13,13);
   lep2Pt_data_wMass_emu__1->SetBinContent(14,5);
   lep2Pt_data_wMass_emu__1->SetBinContent(15,7);
   lep2Pt_data_wMass_emu__1->SetBinContent(16,5);
   lep2Pt_data_wMass_emu__1->SetBinContent(18,2);
   lep2Pt_data_wMass_emu__1->SetBinContent(19,2);
   lep2Pt_data_wMass_emu__1->SetBinContent(21,3);
   lep2Pt_data_wMass_emu__1->SetEntries(2668);
   lep2Pt_data_wMass_emu__1->SetDirectory(0);
   lep2Pt_data_wMass_emu__1->SetFillColor(1);
   lep2Pt_data_wMass_emu__1->SetLineWidth(2);
   lep2Pt_data_wMass_emu__1->SetLineColor(1); //
   lep2Pt_data_wMass_emu__1->SetMarkerStyle(20);
   lep2Pt_data_wMass_emu__1->SetMarkerSize(1.4);
   lep2Pt_data_wMass_emu__1->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_data_wMass_emu__1->GetXaxis()->SetLabelFont(42);
   lep2Pt_data_wMass_emu__1->GetXaxis()->SetLabelSize(0.035);
   lep2Pt_data_wMass_emu__1->GetXaxis()->SetTitleSize(0.035);
   lep2Pt_data_wMass_emu__1->GetXaxis()->SetTitleOffset(1);
   lep2Pt_data_wMass_emu__1->GetXaxis()->SetTitleFont(42);
   lep2Pt_data_wMass_emu__1->GetYaxis()->SetLabelFont(42);
   lep2Pt_data_wMass_emu__1->GetYaxis()->SetLabelSize(0.035);
   lep2Pt_data_wMass_emu__1->GetYaxis()->SetTitleSize(0.035);
   lep2Pt_data_wMass_emu__1->GetYaxis()->SetTitleOffset(1);
   lep2Pt_data_wMass_emu__1->GetYaxis()->SetTitleFont(42);
   lep2Pt_data_wMass_emu__1->GetZaxis()->SetLabelFont(42);
   lep2Pt_data_wMass_emu__1->GetZaxis()->SetLabelSize(0.035);
   lep2Pt_data_wMass_emu__1->GetZaxis()->SetTitleSize(0.035);
   lep2Pt_data_wMass_emu__1->GetZaxis()->SetTitleOffset(1);
   lep2Pt_data_wMass_emu__1->GetZaxis()->SetTitleFont(42);
   lep2Pt_data_wMass_emu__1->Draw("e x0, same");
   
   TLegend *leg = new TLegend(0.78,0.42,0.98,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("lep2Pt_zPlusJetsMadgraph_wMass_emu_stack_8","Z+jets (LO)","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep2Pt_tt_wMass_emu_stack_7","t#bar{t}","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep2Pt_SingleTop_wMass_emu_stack_6","Single top","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep2Pt_VV_wMass_emu_stack_5","VV","f");

   ci = TColor::GetColor("#ff9933");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep2Pt_VVV_wMass_emu_stack_4","VVV","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep2Pt_wJets_wMass_emu_stack_3","W+jets","f");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep2Pt_ttV_wMass_emu_stack_2","t#bar{t}V","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep2Pt_tZq_wMass_emu_stack_1","tZq","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("lep2Pt_data_wMass_emu","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.4);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.968,0.9429101,"35.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06792969);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.096,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.05419922);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16899,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.04119141);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *lep2Pt_SingleTop_wMass_emu__2 = new TH1F("lep2Pt_SingleTop_wMass_emu__2","Muon p_{T}",20,0,200);
   lep2Pt_SingleTop_wMass_emu__2->SetMinimum(0);
   lep2Pt_SingleTop_wMass_emu__2->SetMaximum(837.375);
   lep2Pt_SingleTop_wMass_emu__2->SetDirectory(0);
   lep2Pt_SingleTop_wMass_emu__2->SetStats(0);
   lep2Pt_SingleTop_wMass_emu__2->SetLineStyle(0);
   lep2Pt_SingleTop_wMass_emu__2->SetLineWidth(0);
   lep2Pt_SingleTop_wMass_emu__2->SetMarkerStyle(20);
   lep2Pt_SingleTop_wMass_emu__2->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_SingleTop_wMass_emu__2->GetXaxis()->SetNdivisions(506);
   lep2Pt_SingleTop_wMass_emu__2->GetXaxis()->SetLabelFont(42);
   lep2Pt_SingleTop_wMass_emu__2->GetXaxis()->SetLabelOffset(999);
   lep2Pt_SingleTop_wMass_emu__2->GetXaxis()->SetLabelSize(0.05);
   lep2Pt_SingleTop_wMass_emu__2->GetXaxis()->SetTitleSize(0.08);
   lep2Pt_SingleTop_wMass_emu__2->GetXaxis()->SetTitleOffset(1);
   lep2Pt_SingleTop_wMass_emu__2->GetXaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_wMass_emu__2->GetYaxis()->SetTitle("Events");
   lep2Pt_SingleTop_wMass_emu__2->GetYaxis()->SetNdivisions(506);
   lep2Pt_SingleTop_wMass_emu__2->GetYaxis()->SetLabelFont(42);
   lep2Pt_SingleTop_wMass_emu__2->GetYaxis()->SetLabelOffset(0.01);
   lep2Pt_SingleTop_wMass_emu__2->GetYaxis()->SetLabelSize(0.062);
   lep2Pt_SingleTop_wMass_emu__2->GetYaxis()->SetTitleSize(0.08);
   lep2Pt_SingleTop_wMass_emu__2->GetYaxis()->SetTitleOffset(0.6336);
   lep2Pt_SingleTop_wMass_emu__2->GetYaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_wMass_emu__2->GetZaxis()->SetLabelFont(42);
   lep2Pt_SingleTop_wMass_emu__2->GetZaxis()->SetLabelOffset(0.007);
   lep2Pt_SingleTop_wMass_emu__2->GetZaxis()->SetLabelSize(0.05);
   lep2Pt_SingleTop_wMass_emu__2->GetZaxis()->SetTitleSize(0.08);
   lep2Pt_SingleTop_wMass_emu__2->GetZaxis()->SetTitleOffset(1);
   lep2Pt_SingleTop_wMass_emu__2->GetZaxis()->SetTitleFont(42);
   lep2Pt_SingleTop_wMass_emu__2->Draw("sameaxis");
   
   TPaveText *pt = new TPaveText(0.4053652,0.9203237,0.5946348,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Muon p_{T}");
   pt->Draw();
   canvy_1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: canvy_2
   TPad *canvy_2 = new TPad("canvy_2", "newpad2",0.01,0.01,0.99,0.322);
   canvy_2->Draw();
   canvy_2->cd();
   canvy_2->SetFillColor(0);
   canvy_2->SetBorderMode(0);
   canvy_2->SetGridy();

   canvy_2->SetLeftMargin( L/W );
   canvy_2->SetRightMargin( R/W );
   canvy_2->SetTopMargin( T/H );
   canvy_2->SetBottomMargin( B/H * 2.6 );
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   
   TH1D *lep2Pt_data_wMass_emu__3 = new TH1D("lep2Pt_data_wMass_emu__3","",20,0,200);
   lep2Pt_data_wMass_emu__3->SetBinContent(3,1.100688);
   lep2Pt_data_wMass_emu__3->SetBinContent(4,1.078613);
   lep2Pt_data_wMass_emu__3->SetBinContent(5,1.089588);
   lep2Pt_data_wMass_emu__3->SetBinContent(6,1.024835);
   lep2Pt_data_wMass_emu__3->SetBinContent(7,0.9765795);
   lep2Pt_data_wMass_emu__3->SetBinContent(8,0.9963858);
   lep2Pt_data_wMass_emu__3->SetBinContent(9,1.211131);
   lep2Pt_data_wMass_emu__3->SetBinContent(10,0.9210249);
   lep2Pt_data_wMass_emu__3->SetBinContent(11,1.014187);
   lep2Pt_data_wMass_emu__3->SetBinContent(12,0.7126791);
   lep2Pt_data_wMass_emu__3->SetBinContent(13,0.8134676);
   lep2Pt_data_wMass_emu__3->SetBinContent(14,0.5439875);
   lep2Pt_data_wMass_emu__3->SetBinContent(15,0.871398);
   lep2Pt_data_wMass_emu__3->SetBinContent(16,0.9393763);
   lep2Pt_data_wMass_emu__3->SetBinContent(18,2.229705);
   lep2Pt_data_wMass_emu__3->SetBinContent(19,2.480456);
   lep2Pt_data_wMass_emu__3->SetBinContent(21,0.9849744);
   lep2Pt_data_wMass_emu__3->SetBinError(3,0.09164818);
   lep2Pt_data_wMass_emu__3->SetBinError(4,0.05775417);
   lep2Pt_data_wMass_emu__3->SetBinError(5,0.06419401);
   lep2Pt_data_wMass_emu__3->SetBinError(6,0.07246378);
   lep2Pt_data_wMass_emu__3->SetBinError(7,0.08975462);
   lep2Pt_data_wMass_emu__3->SetBinError(8,0.1134461);
   lep2Pt_data_wMass_emu__3->SetBinError(9,0.1783192);
   lep2Pt_data_wMass_emu__3->SetBinError(10,0.17213);
   lep2Pt_data_wMass_emu__3->SetBinError(11,0.2468474);
   lep2Pt_data_wMass_emu__3->SetBinError(12,0.2262078);
   lep2Pt_data_wMass_emu__3->SetBinError(13,0.303825);
   lep2Pt_data_wMass_emu__3->SetBinError(14,0.3022914);
   lep2Pt_data_wMass_emu__3->SetBinError(15,0.4505579);
   lep2Pt_data_wMass_emu__3->SetBinError(16,0.5850401);
   lep2Pt_data_wMass_emu__3->SetBinError(18,2.833439);
   lep2Pt_data_wMass_emu__3->SetBinError(19,3.272161);
   lep2Pt_data_wMass_emu__3->SetBinError(21,0.8012016);
   lep2Pt_data_wMass_emu__3->SetMinimum(0.5);
   lep2Pt_data_wMass_emu__3->SetMaximum(1.5);
   lep2Pt_data_wMass_emu__3->SetEntries(16.47097);
   lep2Pt_data_wMass_emu__3->SetDirectory(0);
   lep2Pt_data_wMass_emu__3->SetStats(0);
   lep2Pt_data_wMass_emu__3->SetFillColor(1);
   lep2Pt_data_wMass_emu__3->SetLineWidth(2);
   lep2Pt_data_wMass_emu__3->SetLineColor(1); //
   lep2Pt_data_wMass_emu__3->SetMarkerStyle(20);
   lep2Pt_data_wMass_emu__3->SetMarkerSize(1.6);
   lep2Pt_data_wMass_emu__3->GetXaxis()->SetTitle("Muon p_{T} (GeV)");
   lep2Pt_data_wMass_emu__3->GetXaxis()->SetNdivisions(506);
   lep2Pt_data_wMass_emu__3->GetXaxis()->SetLabelFont(42);
   lep2Pt_data_wMass_emu__3->GetXaxis()->SetLabelOffset(0.013);
   lep2Pt_data_wMass_emu__3->GetXaxis()->SetLabelSize(0.13);
   lep2Pt_data_wMass_emu__3->GetXaxis()->SetTitleSize(0.13);
   lep2Pt_data_wMass_emu__3->GetXaxis()->SetTitleOffset(1);
   lep2Pt_data_wMass_emu__3->GetXaxis()->SetTitleFont(42);
   lep2Pt_data_wMass_emu__3->GetYaxis()->SetTitle("Data/MC");
   lep2Pt_data_wMass_emu__3->GetYaxis()->CenterTitle(true);
   lep2Pt_data_wMass_emu__3->GetYaxis()->SetNdivisions(506);
   lep2Pt_data_wMass_emu__3->GetYaxis()->SetLabelFont(42);
   lep2Pt_data_wMass_emu__3->GetYaxis()->SetLabelOffset(0.01);
   lep2Pt_data_wMass_emu__3->GetYaxis()->SetLabelSize(0.12);
   lep2Pt_data_wMass_emu__3->GetYaxis()->SetTitleSize(0.16);
   lep2Pt_data_wMass_emu__3->GetYaxis()->SetTitleOffset(0.3);
   lep2Pt_data_wMass_emu__3->GetYaxis()->SetTitleFont(42);
   lep2Pt_data_wMass_emu__3->GetZaxis()->SetLabelFont(42);
   lep2Pt_data_wMass_emu__3->GetZaxis()->SetLabelSize(0.035);
   lep2Pt_data_wMass_emu__3->GetZaxis()->SetTitleSize(0.035);
   lep2Pt_data_wMass_emu__3->GetZaxis()->SetTitleOffset(1);
   lep2Pt_data_wMass_emu__3->GetZaxis()->SetTitleFont(42);
   lep2Pt_data_wMass_emu__3->Draw("e x0, SCAT");
   canvy_2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
//   c1->SetSelected(lep2Pt_data_wMass_emu);
   c1->SaveAs("lep2Pt_wMass.pdf");
}
