void secondJetEta_SingleTop_jetSel()
{
//=========Macro generated from canvas: secondJetEta_SingleTop_jetSel/secondJetEta_SingleTop_jetSel
//=========  (Wed Aug 21 19:45:53 2019) by ROOT version 6.18/00

   // Set up cavas
   int W = 1280;
   int H = 1024;
   int H_ref = 925;
   int W_ref = 1024;

   // references for T, B, L, R
   float T = 0.08*H_ref;
   float B = 0.12*H_ref;
   float L = 0.12*W_ref;
   float R = 0.04*W_ref;

   TCanvas *c1 = new TCanvas("c1","c1",50,50,W,H);
   c1->cd();
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetLeftMargin( L/W );
   c1->SetRightMargin( R/W );
   c1->SetTopMargin( T/H );
   c1->SetBottomMargin( B/H );
   c1->SetTickx(0);
   c1->SetTicky(0);

  
// ------------>Primitives in pad: canvy_1
   TPad *canvy_1 = new TPad("canvy_1", "newpad",0.01,0.315,0.99,0.99);
   canvy_1->Draw();
   canvy_1->cd();
   canvy_1->SetFillColor(0);
   canvy_1->SetBorderMode(0);

   canvy_1->SetLeftMargin( L/W );
   canvy_1->SetRightMargin( R/W );
   canvy_1->SetTopMargin( T/H );
   canvy_1->SetBottomMargin( B/H * 0.3 );

   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);
   
   THStack *secondJetEta_SingleTop_jetSel_emu = new THStack();
   secondJetEta_SingleTop_jetSel_emu->SetName("secondJetEta_SingleTop_jetSel_emu");
   secondJetEta_SingleTop_jetSel_emu->SetTitle(";Subleading jet #eta;Events");
   secondJetEta_SingleTop_jetSel_emu->SetMaximum(390.637);
   
   TH1F *secondJetEta_SingleTop_jetSel_emu_stack_3 = new TH1F("secondJetEta_SingleTop_jetSel_emu_stack_3","Second Jet #eta",25,0,5);
   secondJetEta_SingleTop_jetSel_emu_stack_3->SetMinimum(0);
   secondJetEta_SingleTop_jetSel_emu_stack_3->SetMaximum(410.1688);
   secondJetEta_SingleTop_jetSel_emu_stack_3->SetDirectory(0);
   secondJetEta_SingleTop_jetSel_emu_stack_3->SetStats(0);
   secondJetEta_SingleTop_jetSel_emu_stack_3->SetLineStyle(0);
   secondJetEta_SingleTop_jetSel_emu_stack_3->SetLineWidth(0);
   secondJetEta_SingleTop_jetSel_emu_stack_3->SetMarkerStyle(20);
   secondJetEta_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetNdivisions(506);
   secondJetEta_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetLabelFont(42);
   secondJetEta_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetLabelOffset(999);
   secondJetEta_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetLabelSize(0.05);
   secondJetEta_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetTitleSize(0.08);
   secondJetEta_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   secondJetEta_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetTitle("Events");
   secondJetEta_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetNdivisions(506);
   secondJetEta_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetLabelFont(42);
   secondJetEta_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetLabelOffset(0.01);
   secondJetEta_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetLabelSize(0.062);
   secondJetEta_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetTitleSize(0.08);
   secondJetEta_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetTitleOffset(0.6336);
   secondJetEta_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_jetSel_emu_stack_3->GetZaxis()->SetLabelFont(42);
   secondJetEta_SingleTop_jetSel_emu_stack_3->GetZaxis()->SetLabelOffset(0.007);
   secondJetEta_SingleTop_jetSel_emu_stack_3->GetZaxis()->SetLabelSize(0.05);
   secondJetEta_SingleTop_jetSel_emu_stack_3->GetZaxis()->SetTitleSize(0.08);
   secondJetEta_SingleTop_jetSel_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   secondJetEta_SingleTop_jetSel_emu_stack_3->GetZaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_jetSel_emu->SetHistogram(secondJetEta_SingleTop_jetSel_emu_stack_3);
   
   
   TH1D *secondJetEta_tZq_jetSel_emu_stack_1 = new TH1D("secondJetEta_tZq_jetSel_emu_stack_1","secondJetEta_tZq_jetSel_emu",25,0,5);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(0,0.4940813);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(1,0.03977798);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(2,0.05746164);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(3,0.06523994);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(4,0.03636128);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(5,0.04795566);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(6,0.05228838);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(7,0.02067325);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(8,0.04524158);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(9,0.03693869);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(10,0.02318491);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(11,0.01768607);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(12,0.03051218);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(13,0.01538573);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(14,0.01474447);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(15,0.02018891);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(16,0.01197932);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(17,0.03478228);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(18,0.01387623);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(19,0.01500696);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(20,0.004651965);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(21,0.00134886);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(22,0.0009725812);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(23,0.003853145);
   secondJetEta_tZq_jetSel_emu_stack_1->SetBinContent(24,0.001299232);
   secondJetEta_tZq_jetSel_emu_stack_1->SetEntries(6672);
   secondJetEta_tZq_jetSel_emu_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ffff00");
   secondJetEta_tZq_jetSel_emu_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   secondJetEta_tZq_jetSel_emu_stack_1->SetLineColor(ci);
   secondJetEta_tZq_jetSel_emu_stack_1->SetLineWidth(0);
   secondJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetLabelFont(42);
   secondJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetLabelSize(0.035);
   secondJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleSize(0.035);
   secondJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   secondJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleFont(42);
   secondJetEta_tZq_jetSel_emu_stack_1->GetYaxis()->SetLabelFont(42);
   secondJetEta_tZq_jetSel_emu_stack_1->GetYaxis()->SetLabelSize(0.035);
   secondJetEta_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleSize(0.035);
   secondJetEta_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleOffset(1);
   secondJetEta_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleFont(42);
   secondJetEta_tZq_jetSel_emu_stack_1->GetZaxis()->SetLabelFont(42);
   secondJetEta_tZq_jetSel_emu_stack_1->GetZaxis()->SetLabelSize(0.035);
   secondJetEta_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleSize(0.035);
   secondJetEta_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   secondJetEta_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_jetSel_emu->Add(secondJetEta_tZq_jetSel_emu_stack_1,"");
   
   TH1D *secondJetEta_ttV_jetSel_emu_stack_2 = new TH1D("secondJetEta_ttV_jetSel_emu_stack_2","secondJetEta_ttV_jetSel_emu",25,0,5);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(0,27.4826);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(1,3.428171);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(2,3.486649);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(3,3.894822);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(4,2.821007);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(5,2.548098);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(6,2.399485);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(7,2.419561);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(8,1.650791);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(9,1.157905);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(10,1.503268);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(11,0.8698991);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(12,1.042964);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(13,0.3036656);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(14,0.244552);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(15,0.3949071);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(16,0.2516661);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(17,0.2925044);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(18,0.1348748);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(19,0.03652572);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(20,0.04160212);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(21,0.05401306);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(22,0.05881482);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(23,0.003076861);
   secondJetEta_ttV_jetSel_emu_stack_2->SetBinContent(24,0.002018824);
   secondJetEta_ttV_jetSel_emu_stack_2->SetEntries(29408);
   secondJetEta_ttV_jetSel_emu_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#00ff00");
   secondJetEta_ttV_jetSel_emu_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   secondJetEta_ttV_jetSel_emu_stack_2->SetLineColor(ci);
   secondJetEta_ttV_jetSel_emu_stack_2->SetLineWidth(0);
   secondJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetLabelFont(42);
   secondJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetLabelSize(0.035);
   secondJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleSize(0.035);
   secondJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   secondJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleFont(42);
   secondJetEta_ttV_jetSel_emu_stack_2->GetYaxis()->SetLabelFont(42);
   secondJetEta_ttV_jetSel_emu_stack_2->GetYaxis()->SetLabelSize(0.035);
   secondJetEta_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleSize(0.035);
   secondJetEta_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleOffset(1);
   secondJetEta_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleFont(42);
   secondJetEta_ttV_jetSel_emu_stack_2->GetZaxis()->SetLabelFont(42);
   secondJetEta_ttV_jetSel_emu_stack_2->GetZaxis()->SetLabelSize(0.035);
   secondJetEta_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleSize(0.035);
   secondJetEta_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   secondJetEta_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_jetSel_emu->Add(secondJetEta_ttV_jetSel_emu_stack_2,"");
   
   TH1D *secondJetEta_wJets_jetSel_emu_stack_3 = new TH1D("secondJetEta_wJets_jetSel_emu_stack_3","secondJetEta_wJets_jetSel_emu",25,0,5);
   secondJetEta_wJets_jetSel_emu_stack_3->SetBinContent(0,13.42844);
   secondJetEta_wJets_jetSel_emu_stack_3->SetBinContent(8,12.53387);
   secondJetEta_wJets_jetSel_emu_stack_3->SetEntries(2);
   secondJetEta_wJets_jetSel_emu_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   secondJetEta_wJets_jetSel_emu_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#cccccc");
   secondJetEta_wJets_jetSel_emu_stack_3->SetLineColor(ci);
   secondJetEta_wJets_jetSel_emu_stack_3->SetLineWidth(0);
   secondJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetLabelFont(42);
   secondJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetLabelSize(0.035);
   secondJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleSize(0.035);
   secondJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   secondJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleFont(42);
   secondJetEta_wJets_jetSel_emu_stack_3->GetYaxis()->SetLabelFont(42);
   secondJetEta_wJets_jetSel_emu_stack_3->GetYaxis()->SetLabelSize(0.035);
   secondJetEta_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleSize(0.035);
   secondJetEta_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleOffset(1);
   secondJetEta_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleFont(42);
   secondJetEta_wJets_jetSel_emu_stack_3->GetZaxis()->SetLabelFont(42);
   secondJetEta_wJets_jetSel_emu_stack_3->GetZaxis()->SetLabelSize(0.035);
   secondJetEta_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleSize(0.035);
   secondJetEta_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   secondJetEta_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_jetSel_emu->Add(secondJetEta_wJets_jetSel_emu_stack_3,"");
   
   TH1D *secondJetEta_VVV_jetSel_emu_stack_4 = new TH1D("secondJetEta_VVV_jetSel_emu_stack_4","secondJetEta_VVV_jetSel_emu",25,0,5);
   secondJetEta_VVV_jetSel_emu_stack_4->SetBinContent(0,1.560927);
   secondJetEta_VVV_jetSel_emu_stack_4->SetBinContent(1,0.4566614);
   secondJetEta_VVV_jetSel_emu_stack_4->SetBinContent(2,0.1076454);
   secondJetEta_VVV_jetSel_emu_stack_4->SetBinContent(3,0.272925);
   secondJetEta_VVV_jetSel_emu_stack_4->SetBinContent(4,0.10729);
   secondJetEta_VVV_jetSel_emu_stack_4->SetBinContent(5,0.1331595);
   secondJetEta_VVV_jetSel_emu_stack_4->SetBinContent(6,0.1243656);
   secondJetEta_VVV_jetSel_emu_stack_4->SetBinContent(7,0.005626538);
   secondJetEta_VVV_jetSel_emu_stack_4->SetBinContent(8,0.1226304);
   secondJetEta_VVV_jetSel_emu_stack_4->SetBinContent(9,0.1025598);
   secondJetEta_VVV_jetSel_emu_stack_4->SetBinContent(10,0.1671547);
   secondJetEta_VVV_jetSel_emu_stack_4->SetBinContent(11,0.05975188);
   secondJetEta_VVV_jetSel_emu_stack_4->SetBinContent(12,0.1070364);
   secondJetEta_VVV_jetSel_emu_stack_4->SetBinContent(13,0.07275032);
   secondJetEta_VVV_jetSel_emu_stack_4->SetBinContent(14,0.110626);
   secondJetEta_VVV_jetSel_emu_stack_4->SetBinContent(15,0.02561543);
   secondJetEta_VVV_jetSel_emu_stack_4->SetBinContent(16,0.0634499);
   secondJetEta_VVV_jetSel_emu_stack_4->SetBinContent(17,-0.02589801);
   secondJetEta_VVV_jetSel_emu_stack_4->SetBinContent(18,0.07127397);
   secondJetEta_VVV_jetSel_emu_stack_4->SetBinContent(22,0.03880109);
   secondJetEta_VVV_jetSel_emu_stack_4->SetEntries(147);
   secondJetEta_VVV_jetSel_emu_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#00ffff");
   secondJetEta_VVV_jetSel_emu_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   secondJetEta_VVV_jetSel_emu_stack_4->SetLineColor(ci);
   secondJetEta_VVV_jetSel_emu_stack_4->SetLineWidth(0);
   secondJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetLabelFont(42);
   secondJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetLabelSize(0.035);
   secondJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleSize(0.035);
   secondJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   secondJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleFont(42);
   secondJetEta_VVV_jetSel_emu_stack_4->GetYaxis()->SetLabelFont(42);
   secondJetEta_VVV_jetSel_emu_stack_4->GetYaxis()->SetLabelSize(0.035);
   secondJetEta_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleSize(0.035);
   secondJetEta_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleOffset(1);
   secondJetEta_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleFont(42);
   secondJetEta_VVV_jetSel_emu_stack_4->GetZaxis()->SetLabelFont(42);
   secondJetEta_VVV_jetSel_emu_stack_4->GetZaxis()->SetLabelSize(0.035);
   secondJetEta_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleSize(0.035);
   secondJetEta_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   secondJetEta_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_jetSel_emu->Add(secondJetEta_VVV_jetSel_emu_stack_4,"");
   
   TH1D *secondJetEta_VV_jetSel_emu_stack_5 = new TH1D("secondJetEta_VV_jetSel_emu_stack_5","secondJetEta_VV_jetSel_emu",25,0,5);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(0,31.56767);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(1,2.953076);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(2,1.762573);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(3,1.665993);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(4,3.724148);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(5,2.240819);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(6,1.989646);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(7,2.140412);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(8,2.057163);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(9,2.258163);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(10,1.122618);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(11,1.067267);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(12,1.222038);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(13,0.5000094);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(14,1.210594);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(15,0.678611);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(16,0.2435936);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(17,1.706042);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(18,0.5697212);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(19,0.005757676);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(20,0.2947252);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(21,0.005782863);
   secondJetEta_VV_jetSel_emu_stack_5->SetBinContent(22,-0.01394085);
   secondJetEta_VV_jetSel_emu_stack_5->SetEntries(858);
   secondJetEta_VV_jetSel_emu_stack_5->SetDirectory(0);

   ci = TColor::GetColor("#ff9933");
   secondJetEta_VV_jetSel_emu_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#ff9933");
   secondJetEta_VV_jetSel_emu_stack_5->SetLineColor(ci);
   secondJetEta_VV_jetSel_emu_stack_5->SetLineWidth(0);
   secondJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetLabelFont(42);
   secondJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetLabelSize(0.035);
   secondJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleSize(0.035);
   secondJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleOffset(1);
   secondJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleFont(42);
   secondJetEta_VV_jetSel_emu_stack_5->GetYaxis()->SetLabelFont(42);
   secondJetEta_VV_jetSel_emu_stack_5->GetYaxis()->SetLabelSize(0.035);
   secondJetEta_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleSize(0.035);
   secondJetEta_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleOffset(1);
   secondJetEta_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleFont(42);
   secondJetEta_VV_jetSel_emu_stack_5->GetZaxis()->SetLabelFont(42);
   secondJetEta_VV_jetSel_emu_stack_5->GetZaxis()->SetLabelSize(0.035);
   secondJetEta_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleSize(0.035);
   secondJetEta_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleOffset(1);
   secondJetEta_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_jetSel_emu->Add(secondJetEta_VV_jetSel_emu_stack_5,"");
   
   TH1D *secondJetEta_SingleTop_jetSel_emu_stack_6 = new TH1D("secondJetEta_SingleTop_jetSel_emu_stack_6","secondJetEta_SingleTop_jetSel_emu",25,0,5);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(0,144.0448);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(1,12.08257);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(2,12.8369);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(3,12.21758);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(4,12.06474);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(5,13.61573);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(6,12.12733);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(7,6.910403);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(8,11.42474);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(9,7.601833);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(10,6.495525);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(11,5.115);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(12,4.308288);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(13,1.927788);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(14,4.167687);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(15,4.379055);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(16,1.404596);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(17,1.962734);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(18,1.960496);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(19,1.340932);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(20,0.9534117);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(21,0.1982435);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(22,0.7238062);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(23,0.004233778);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(24,0.3525077);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetEntries(2806);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetDirectory(0);

   ci = TColor::GetColor("#ff00ff");
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetLineColor(ci);
   secondJetEta_SingleTop_jetSel_emu_stack_6->SetLineWidth(0);
   secondJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetLabelFont(42);
   secondJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetLabelSize(0.035);
   secondJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleSize(0.035);
   secondJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleOffset(1);
   secondJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetLabelFont(42);
   secondJetEta_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetLabelSize(0.035);
   secondJetEta_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleSize(0.035);
   secondJetEta_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleOffset(1);
   secondJetEta_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetLabelFont(42);
   secondJetEta_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetLabelSize(0.035);
   secondJetEta_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleSize(0.035);
   secondJetEta_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleOffset(1);
   secondJetEta_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_jetSel_emu->Add(secondJetEta_SingleTop_jetSel_emu_stack_6,"");
   
   TH1D *secondJetEta_tt_jetSel_emu_stack_7 = new TH1D("secondJetEta_tt_jetSel_emu_stack_7","secondJetEta_tt_jetSel_emu",25,0,5);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(0,3103.606);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(1,336.1643);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(2,320.2876);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(3,318.2749);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(4,294.5501);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(5,261.6286);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(6,235.3256);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(7,210.315);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(8,202.3211);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(9,170.9786);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(10,136.042);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(11,124.2972);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(12,107.0815);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(13,89.24937);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(14,89.55016);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(15,67.23151);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(16,43.2618);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(17,38.56075);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(18,31.28364);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(19,24.69933);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(20,17.19653);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(21,7.825001);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(22,5.779336);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(23,2.03359);
   secondJetEta_tt_jetSel_emu_stack_7->SetBinContent(24,0.974752);
   secondJetEta_tt_jetSel_emu_stack_7->SetEntries(19867);
   secondJetEta_tt_jetSel_emu_stack_7->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   secondJetEta_tt_jetSel_emu_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   secondJetEta_tt_jetSel_emu_stack_7->SetLineColor(ci);
   secondJetEta_tt_jetSel_emu_stack_7->SetLineWidth(0);
   secondJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetLabelFont(42);
   secondJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetLabelSize(0.035);
   secondJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleSize(0.035);
   secondJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleOffset(1);
   secondJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleFont(42);
   secondJetEta_tt_jetSel_emu_stack_7->GetYaxis()->SetLabelFont(42);
   secondJetEta_tt_jetSel_emu_stack_7->GetYaxis()->SetLabelSize(0.035);
   secondJetEta_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleSize(0.035);
   secondJetEta_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleOffset(1);
   secondJetEta_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleFont(42);
   secondJetEta_tt_jetSel_emu_stack_7->GetZaxis()->SetLabelFont(42);
   secondJetEta_tt_jetSel_emu_stack_7->GetZaxis()->SetLabelSize(0.035);
   secondJetEta_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleSize(0.035);
   secondJetEta_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleOffset(1);
   secondJetEta_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_jetSel_emu->Add(secondJetEta_tt_jetSel_emu_stack_7,"");
   
   TH1D *secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8 = new TH1D("secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8","secondJetEta_zPlusJetsMadgraph_jetSel_emu",25,0,5);
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(0,13.26095);
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(3,1.549233);
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(6,1.437746);
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(11,1.422358);
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetEntries(12);
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetLineColor(ci);
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetLineWidth(0);
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetLabelFont(42);
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetLabelSize(0.035);
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleSize(0.035);
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleOffset(1);
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleFont(42);
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetLabelFont(42);
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetLabelSize(0.035);
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleSize(0.035);
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleOffset(1);
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleFont(42);
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetLabelFont(42);
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetLabelSize(0.035);
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleSize(0.035);
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleOffset(1);
   secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_jetSel_emu->Add(secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8,"");
   secondJetEta_SingleTop_jetSel_emu->Draw("");
   
   TH1D *secondJetEta_data_jetSel_emu__7 = new TH1D("secondJetEta_data_jetSel_emu__7","secondJetEta_data_jetSel_emu",25,0,5);
   secondJetEta_data_jetSel_emu__7->SetBinContent(0,3398);
   secondJetEta_data_jetSel_emu__7->SetBinContent(1,342);
   secondJetEta_data_jetSel_emu__7->SetBinContent(2,352);
   secondJetEta_data_jetSel_emu__7->SetBinContent(3,311);
   secondJetEta_data_jetSel_emu__7->SetBinContent(4,273);
   secondJetEta_data_jetSel_emu__7->SetBinContent(5,277);
   secondJetEta_data_jetSel_emu__7->SetBinContent(6,260);
   secondJetEta_data_jetSel_emu__7->SetBinContent(7,222);
   secondJetEta_data_jetSel_emu__7->SetBinContent(8,212);
   secondJetEta_data_jetSel_emu__7->SetBinContent(9,177);
   secondJetEta_data_jetSel_emu__7->SetBinContent(10,176);
   secondJetEta_data_jetSel_emu__7->SetBinContent(11,134);
   secondJetEta_data_jetSel_emu__7->SetBinContent(12,103);
   secondJetEta_data_jetSel_emu__7->SetBinContent(13,106);
   secondJetEta_data_jetSel_emu__7->SetBinContent(14,96);
   secondJetEta_data_jetSel_emu__7->SetBinContent(15,65);
   secondJetEta_data_jetSel_emu__7->SetBinContent(16,35);
   secondJetEta_data_jetSel_emu__7->SetBinContent(17,31);
   secondJetEta_data_jetSel_emu__7->SetBinContent(18,33);
   secondJetEta_data_jetSel_emu__7->SetBinContent(19,21);
   secondJetEta_data_jetSel_emu__7->SetBinContent(20,18);
   secondJetEta_data_jetSel_emu__7->SetBinContent(21,10);
   secondJetEta_data_jetSel_emu__7->SetBinContent(22,10);
   secondJetEta_data_jetSel_emu__7->SetBinContent(23,6);
   secondJetEta_data_jetSel_emu__7->SetEntries(6668);
   secondJetEta_data_jetSel_emu__7->SetDirectory(0);
   secondJetEta_data_jetSel_emu__7->SetFillColor(1);
   secondJetEta_data_jetSel_emu__7->SetLineWidth(2);
   secondJetEta_data_jetSel_emu__7->SetLineColor(1); //
   secondJetEta_data_jetSel_emu__7->SetMarkerStyle(20);
   secondJetEta_data_jetSel_emu__7->SetMarkerSize(1.4);
   secondJetEta_data_jetSel_emu__7->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_data_jetSel_emu__7->GetXaxis()->SetLabelFont(42);
   secondJetEta_data_jetSel_emu__7->GetXaxis()->SetLabelSize(0.035);
   secondJetEta_data_jetSel_emu__7->GetXaxis()->SetTitleSize(0.035);
   secondJetEta_data_jetSel_emu__7->GetXaxis()->SetTitleOffset(1);
   secondJetEta_data_jetSel_emu__7->GetXaxis()->SetTitleFont(42);
   secondJetEta_data_jetSel_emu__7->GetYaxis()->SetLabelFont(42);
   secondJetEta_data_jetSel_emu__7->GetYaxis()->SetLabelSize(0.035);
   secondJetEta_data_jetSel_emu__7->GetYaxis()->SetTitleSize(0.035);
   secondJetEta_data_jetSel_emu__7->GetYaxis()->SetTitleOffset(1);
   secondJetEta_data_jetSel_emu__7->GetYaxis()->SetTitleFont(42);
   secondJetEta_data_jetSel_emu__7->GetZaxis()->SetLabelFont(42);
   secondJetEta_data_jetSel_emu__7->GetZaxis()->SetLabelSize(0.035);
   secondJetEta_data_jetSel_emu__7->GetZaxis()->SetTitleSize(0.035);
   secondJetEta_data_jetSel_emu__7->GetZaxis()->SetTitleOffset(1);
   secondJetEta_data_jetSel_emu__7->GetZaxis()->SetTitleFont(42);
   secondJetEta_data_jetSel_emu__7->Draw("e x0, same");
   
   TLegend *leg = new TLegend(0.78,0.42,0.98,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("secondJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8","Z+jets (LO)","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetEta_tt_jetSel_emu_stack_7","t#bar{t}","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetEta_SingleTop_jetSel_emu_stack_6","Single top","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetEta_VV_jetSel_emu_stack_5","VV","f");

   ci = TColor::GetColor("#ff9933");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetEta_VVV_jetSel_emu_stack_4","VVV","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetEta_wJets_jetSel_emu_stack_3","W+jets","f");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetEta_ttV_jetSel_emu_stack_2","t#bar{t}V","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetEta_tZq_jetSel_emu_stack_1","tZq","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetEta_data_jetSel_emu","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.4);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.968,0.9429101,"35.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06792969);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.096,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.05419922);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16899,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.04119141);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *secondJetEta_SingleTop_jetSel_emu__8 = new TH1F("secondJetEta_SingleTop_jetSel_emu__8","Second Jet #eta",25,0,5);
   secondJetEta_SingleTop_jetSel_emu__8->SetMinimum(0);
   secondJetEta_SingleTop_jetSel_emu__8->SetMaximum(410.1688);
   secondJetEta_SingleTop_jetSel_emu__8->SetDirectory(0);
   secondJetEta_SingleTop_jetSel_emu__8->SetStats(0);
   secondJetEta_SingleTop_jetSel_emu__8->SetLineStyle(0);
   secondJetEta_SingleTop_jetSel_emu__8->SetLineWidth(0);
   secondJetEta_SingleTop_jetSel_emu__8->SetMarkerStyle(20);
   secondJetEta_SingleTop_jetSel_emu__8->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_SingleTop_jetSel_emu__8->GetXaxis()->SetNdivisions(506);
   secondJetEta_SingleTop_jetSel_emu__8->GetXaxis()->SetLabelFont(42);
   secondJetEta_SingleTop_jetSel_emu__8->GetXaxis()->SetLabelOffset(999);
   secondJetEta_SingleTop_jetSel_emu__8->GetXaxis()->SetLabelSize(0.05);
   secondJetEta_SingleTop_jetSel_emu__8->GetXaxis()->SetTitleSize(0.08);
   secondJetEta_SingleTop_jetSel_emu__8->GetXaxis()->SetTitleOffset(1);
   secondJetEta_SingleTop_jetSel_emu__8->GetXaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_jetSel_emu__8->GetYaxis()->SetTitle("Events");
   secondJetEta_SingleTop_jetSel_emu__8->GetYaxis()->SetNdivisions(506);
   secondJetEta_SingleTop_jetSel_emu__8->GetYaxis()->SetLabelFont(42);
   secondJetEta_SingleTop_jetSel_emu__8->GetYaxis()->SetLabelOffset(0.01);
   secondJetEta_SingleTop_jetSel_emu__8->GetYaxis()->SetLabelSize(0.062);
   secondJetEta_SingleTop_jetSel_emu__8->GetYaxis()->SetTitleSize(0.08);
   secondJetEta_SingleTop_jetSel_emu__8->GetYaxis()->SetTitleOffset(0.6336);
   secondJetEta_SingleTop_jetSel_emu__8->GetYaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_jetSel_emu__8->GetZaxis()->SetLabelFont(42);
   secondJetEta_SingleTop_jetSel_emu__8->GetZaxis()->SetLabelOffset(0.007);
   secondJetEta_SingleTop_jetSel_emu__8->GetZaxis()->SetLabelSize(0.05);
   secondJetEta_SingleTop_jetSel_emu__8->GetZaxis()->SetTitleSize(0.08);
   secondJetEta_SingleTop_jetSel_emu__8->GetZaxis()->SetTitleOffset(1);
   secondJetEta_SingleTop_jetSel_emu__8->GetZaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_jetSel_emu__8->Draw("sameaxis");
   
   TPaveText *pt = new TPaveText(0.4281208,0.9347772,0.5718792,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Second Jet #eta");
   pt->Draw();
   canvy_1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: canvy_2
   TPad *canvy_2 = new TPad("canvy_2", "newpad2",0.01,0.01,0.99,0.322);
   canvy_2->Draw();
   canvy_2->cd();
   canvy_2->SetFillColor(0);
   canvy_2->SetBorderMode(0);
   canvy_2->SetGridy();

   canvy_2->SetLeftMargin( L/W );
   canvy_2->SetRightMargin( R/W );
   canvy_2->SetTopMargin( T/H );
   canvy_2->SetBottomMargin( B/H * 2.6 );
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   
   TH1D *secondJetEta_data_jetSel_emu__9 = new TH1D("secondJetEta_data_jetSel_emu__9","",25,0,5);
   secondJetEta_data_jetSel_emu__9->SetBinContent(0,1.018755);
   secondJetEta_data_jetSel_emu__9->SetBinContent(1,0.9630425);
   secondJetEta_data_jetSel_emu__9->SetBinContent(2,1.039762);
   secondJetEta_data_jetSel_emu__9->SetBinContent(3,0.9202798);
   secondJetEta_data_jetSel_emu__9->SetBinContent(4,0.8713591);
   secondJetEta_data_jetSel_emu__9->SetBinContent(5,0.9885288);
   secondJetEta_data_jetSel_emu__9->SetBinContent(6,1.025817);
   secondJetEta_data_jetSel_emu__9->SetBinContent(7,1.000849);
   secondJetEta_data_jetSel_emu__9->SetBinContent(8,0.9211162);
   secondJetEta_data_jetSel_emu__9->SetBinContent(9,0.9718015);
   secondJetEta_data_jetSel_emu__9->SetBinContent(10,1.210839);
   secondJetEta_data_jetSel_emu__9->SetBinContent(11,1.008662);
   secondJetEta_data_jetSel_emu__9->SetBinContent(12,0.905158);
   secondJetEta_data_jetSel_emu__9->SetBinContent(13,1.151311);
   secondJetEta_data_jetSel_emu__9->SetBinContent(14,1.007363);
   secondJetEta_data_jetSel_emu__9->SetBinContent(15,0.8937179);
   secondJetEta_data_jetSel_emu__9->SetBinContent(16,0.7737015);
   secondJetEta_data_jetSel_emu__9->SetBinContent(17,0.7288815);
   secondJetEta_data_jetSel_emu__9->SetBinContent(18,0.969622);
   secondJetEta_data_jetSel_emu__9->SetBinContent(19,0.8046731);
   secondJetEta_data_jetSel_emu__9->SetBinContent(20,0.9734506);
   secondJetEta_data_jetSel_emu__9->SetBinContent(21,1.236952);
   secondJetEta_data_jetSel_emu__9->SetBinContent(22,1.51796);
   secondJetEta_data_jetSel_emu__9->SetBinContent(23,2.934339);
   secondJetEta_data_jetSel_emu__9->SetBinError(0,0.02483131);
   secondJetEta_data_jetSel_emu__9->SetBinError(1,0.07296209);
   secondJetEta_data_jetSel_emu__9->SetBinError(2,0.07915031);
   secondJetEta_data_jetSel_emu__9->SetBinError(3,0.07231393);
   secondJetEta_data_jetSel_emu__9->SetBinError(4,0.07214304);
   secondJetEta_data_jetSel_emu__9->SetBinError(5,0.08375589);
   secondJetEta_data_jetSel_emu__9->SetBinError(6,0.09054894);
   secondJetEta_data_jetSel_emu__9->SetBinError(7,0.09501654);
   secondJetEta_data_jetSel_emu__9->SetBinError(8,0.08768459);
   secondJetEta_data_jetSel_emu__9->SetBinError(9,0.1025705);
   secondJetEta_data_jetSel_emu__9->SetBinError(10,0.135709);
   secondJetEta_data_jetSel_emu__9->SetBinError(11,0.1234943);
   secondJetEta_data_jetSel_emu__9->SetBinError(12,0.1231037);
   secondJetEta_data_jetSel_emu__9->SetBinError(13,0.1640179);
   secondJetEta_data_jetSel_emu__9->SetBinError(14,0.1456676);
   secondJetEta_data_jetSel_emu__9->SetBinError(15,0.1525462);
   secondJetEta_data_jetSel_emu__9->SetBinError(16,0.1741725);
   secondJetEta_data_jetSel_emu__9->SetBinError(17,0.1721309);
   secondJetEta_data_jetSel_emu__9->SetBinError(18,0.2368847);
   secondJetEta_data_jetSel_emu__9->SetBinError(19,0.2358898);
   secondJetEta_data_jetSel_emu__9->SetBinError(20,0.3223226);
   secondJetEta_data_jetSel_emu__9->SetBinError(21,0.585034);
   secondJetEta_data_jetSel_emu__9->SetBinError(22,0.7617013);
   secondJetEta_data_jetSel_emu__9->SetBinError(23,2.376132);
   secondJetEta_data_jetSel_emu__9->SetMinimum(0.5);
   secondJetEta_data_jetSel_emu__9->SetMaximum(1.5);
   secondJetEta_data_jetSel_emu__9->SetEntries(87.63882);
   secondJetEta_data_jetSel_emu__9->SetDirectory(0);
   secondJetEta_data_jetSel_emu__9->SetStats(0);
   secondJetEta_data_jetSel_emu__9->SetFillColor(1);
   secondJetEta_data_jetSel_emu__9->SetLineWidth(2);
   secondJetEta_data_jetSel_emu__9->SetLineColor(1); //
   secondJetEta_data_jetSel_emu__9->SetMarkerStyle(20);
   secondJetEta_data_jetSel_emu__9->SetMarkerSize(1.6);
   secondJetEta_data_jetSel_emu__9->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_data_jetSel_emu__9->GetXaxis()->SetNdivisions(506);
   secondJetEta_data_jetSel_emu__9->GetXaxis()->SetLabelFont(42);
   secondJetEta_data_jetSel_emu__9->GetXaxis()->SetLabelOffset(0.013);
   secondJetEta_data_jetSel_emu__9->GetXaxis()->SetLabelSize(0.13);
   secondJetEta_data_jetSel_emu__9->GetXaxis()->SetTitleSize(0.13);
   secondJetEta_data_jetSel_emu__9->GetXaxis()->SetTitleOffset(1);
   secondJetEta_data_jetSel_emu__9->GetXaxis()->SetTitleFont(42);
   secondJetEta_data_jetSel_emu__9->GetYaxis()->SetTitle("Data/MC");
   secondJetEta_data_jetSel_emu__9->GetYaxis()->CenterTitle(true);
   secondJetEta_data_jetSel_emu__9->GetYaxis()->SetNdivisions(506);
   secondJetEta_data_jetSel_emu__9->GetYaxis()->SetLabelFont(42);
   secondJetEta_data_jetSel_emu__9->GetYaxis()->SetLabelOffset(0.01);
   secondJetEta_data_jetSel_emu__9->GetYaxis()->SetLabelSize(0.12);
   secondJetEta_data_jetSel_emu__9->GetYaxis()->SetTitleSize(0.16);
   secondJetEta_data_jetSel_emu__9->GetYaxis()->SetTitleOffset(0.3);
   secondJetEta_data_jetSel_emu__9->GetYaxis()->SetTitleFont(42);
   secondJetEta_data_jetSel_emu__9->GetZaxis()->SetLabelFont(42);
   secondJetEta_data_jetSel_emu__9->GetZaxis()->SetLabelSize(0.035);
   secondJetEta_data_jetSel_emu__9->GetZaxis()->SetTitleSize(0.035);
   secondJetEta_data_jetSel_emu__9->GetZaxis()->SetTitleOffset(1);
   secondJetEta_data_jetSel_emu__9->GetZaxis()->SetTitleFont(42);
   secondJetEta_data_jetSel_emu__9->Draw("e x0, SCAT");
   canvy_2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
//   c1->SetSelected(secondJetEta_data_jetSel_emu);
   c1->SaveAs("secondJetEta_jetSel.pdf");
}
