void secondJetPt_SingleTop_wMass()
{
//=========Macro generated from canvas: secondJetPt_SingleTop_wMass/secondJetPt_SingleTop_wMass
//=========  (Wed Aug 21 19:38:49 2019) by ROOT version 6.18/00

   // Set up cavas
   int W = 1280;
   int H = 1024;
   int H_ref = 925;
   int W_ref = 1024;

   // references for T, B, L, R
   float T = 0.08*H_ref;
   float B = 0.12*H_ref;
   float L = 0.12*W_ref;
   float R = 0.04*W_ref;

   TCanvas *c1 = new TCanvas("c1","c1",50,50,W,H);
   c1->cd();
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetLeftMargin( L/W );
   c1->SetRightMargin( R/W );
   c1->SetTopMargin( T/H );
   c1->SetBottomMargin( B/H );
   c1->SetTickx(0);
   c1->SetTicky(0);
  
// ------------>Primitives in pad: canvy_1
   TPad *canvy_1 = new TPad("canvy_1", "newpad",0.01,0.315,0.99,0.99);
   canvy_1->Draw();
   canvy_1->cd();
   canvy_1->SetFillColor(0);
   canvy_1->SetBorderMode(0);

   canvy_1->SetLeftMargin( L/W );
   canvy_1->SetRightMargin( R/W );
   canvy_1->SetTopMargin( T/H );
   canvy_1->SetBottomMargin( B/H * 0.3 );

   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);
   
   THStack *secondJetPt_SingleTop_wMass_emu = new THStack();
   secondJetPt_SingleTop_wMass_emu->SetName("secondJetPt_SingleTop_wMass_emu");
   secondJetPt_SingleTop_wMass_emu->SetTitle("Second Jet p_{T};Subleading jet p_{T} (GeV);Events");
   secondJetPt_SingleTop_wMass_emu->SetMaximum(463.1);
   
   TH1F *secondJetPt_SingleTop_wMass_emu_stack_3 = new TH1F("secondJetPt_SingleTop_wMass_emu_stack_3","Second Jet p_{T}",35,0,300);
   secondJetPt_SingleTop_wMass_emu_stack_3->SetMinimum(0);
   secondJetPt_SingleTop_wMass_emu_stack_3->SetMaximum(486.255);
   secondJetPt_SingleTop_wMass_emu_stack_3->SetDirectory(0);
   secondJetPt_SingleTop_wMass_emu_stack_3->SetStats(0);
   secondJetPt_SingleTop_wMass_emu_stack_3->SetLineStyle(0);
   secondJetPt_SingleTop_wMass_emu_stack_3->SetLineWidth(0);
   secondJetPt_SingleTop_wMass_emu_stack_3->SetMarkerStyle(20);
   secondJetPt_SingleTop_wMass_emu_stack_3->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_SingleTop_wMass_emu_stack_3->GetXaxis()->SetNdivisions(506);
   secondJetPt_SingleTop_wMass_emu_stack_3->GetXaxis()->SetLabelFont(42);
   secondJetPt_SingleTop_wMass_emu_stack_3->GetXaxis()->SetLabelOffset(999);
   secondJetPt_SingleTop_wMass_emu_stack_3->GetXaxis()->SetLabelSize(0.05);
   secondJetPt_SingleTop_wMass_emu_stack_3->GetXaxis()->SetTitleSize(0.08);
   secondJetPt_SingleTop_wMass_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   secondJetPt_SingleTop_wMass_emu_stack_3->GetXaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_wMass_emu_stack_3->GetYaxis()->SetTitle("Events");
   secondJetPt_SingleTop_wMass_emu_stack_3->GetYaxis()->SetNdivisions(506);
   secondJetPt_SingleTop_wMass_emu_stack_3->GetYaxis()->SetLabelFont(42);
   secondJetPt_SingleTop_wMass_emu_stack_3->GetYaxis()->SetLabelOffset(0.01);
   secondJetPt_SingleTop_wMass_emu_stack_3->GetYaxis()->SetLabelSize(0.062);
   secondJetPt_SingleTop_wMass_emu_stack_3->GetYaxis()->SetTitleSize(0.08);
   secondJetPt_SingleTop_wMass_emu_stack_3->GetYaxis()->SetTitleOffset(0.6336);
   secondJetPt_SingleTop_wMass_emu_stack_3->GetYaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_wMass_emu_stack_3->GetZaxis()->SetLabelFont(42);
   secondJetPt_SingleTop_wMass_emu_stack_3->GetZaxis()->SetLabelOffset(0.007);
   secondJetPt_SingleTop_wMass_emu_stack_3->GetZaxis()->SetLabelSize(0.05);
   secondJetPt_SingleTop_wMass_emu_stack_3->GetZaxis()->SetTitleSize(0.08);
   secondJetPt_SingleTop_wMass_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   secondJetPt_SingleTop_wMass_emu_stack_3->GetZaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_wMass_emu->SetHistogram(secondJetPt_SingleTop_wMass_emu_stack_3);
   
   
   TH1D *secondJetPt_tZq_wMass_emu_stack_1 = new TH1D("secondJetPt_tZq_wMass_emu_stack_1","secondJetPt_tZq_wMass_emu",35,0,300);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(4,-0.0006986611);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(5,0.00993959);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(6,0.02313405);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(7,0.03985321);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(8,0.06283614);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(9,0.03727335);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(10,0.03863803);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(11,0.01514646);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(12,0.0317374);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(13,0.01379308);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(14,0.006033316);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(15,0.01367249);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(16,0.01192606);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(17,0.005280164);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(18,0.002244537);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(19,0.007504405);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(20,0.004672972);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(21,0.002748793);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(22,-0.001540356);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(23,0.002385531);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(24,0.002222607);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(25,0.002874319);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(26,0.005552191);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(27,-0.0014053);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(28,-0.001506214);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(29,0.001594957);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(30,0.001320062);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(31,0.001423601);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(32,0.002802897);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(33,1.381425e-05);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(34,-0.000710084);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(35,0.002388746);
   secondJetPt_tZq_wMass_emu_stack_1->SetBinContent(36,0.001256269);
   secondJetPt_tZq_wMass_emu_stack_1->SetEntries(2170);
   secondJetPt_tZq_wMass_emu_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ffff00");
   secondJetPt_tZq_wMass_emu_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   secondJetPt_tZq_wMass_emu_stack_1->SetLineColor(ci);
   secondJetPt_tZq_wMass_emu_stack_1->SetLineWidth(0);
   secondJetPt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_tZq_wMass_emu_stack_1->GetXaxis()->SetLabelFont(42);
   secondJetPt_tZq_wMass_emu_stack_1->GetXaxis()->SetLabelSize(0.035);
   secondJetPt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleSize(0.035);
   secondJetPt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   secondJetPt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleFont(42);
   secondJetPt_tZq_wMass_emu_stack_1->GetYaxis()->SetLabelFont(42);
   secondJetPt_tZq_wMass_emu_stack_1->GetYaxis()->SetLabelSize(0.035);
   secondJetPt_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleSize(0.035);
   secondJetPt_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleOffset(1);
   secondJetPt_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleFont(42);
   secondJetPt_tZq_wMass_emu_stack_1->GetZaxis()->SetLabelFont(42);
   secondJetPt_tZq_wMass_emu_stack_1->GetZaxis()->SetLabelSize(0.035);
   secondJetPt_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleSize(0.035);
   secondJetPt_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   secondJetPt_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_wMass_emu->Add(secondJetPt_tZq_wMass_emu_stack_1,"");
   
   TH1D *secondJetPt_ttV_wMass_emu_stack_2 = new TH1D("secondJetPt_ttV_wMass_emu_stack_2","secondJetPt_ttV_wMass_emu",35,0,300);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(4,0.07818444);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(5,0.6264881);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(6,2.178475);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(7,2.936573);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(8,2.678668);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(9,3.524089);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(10,2.899061);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(11,2.181543);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(12,1.8625);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(13,2.057486);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(14,1.184807);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(15,0.912655);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(16,0.7997689);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(17,0.7440886);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(18,0.7477355);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(19,0.31491);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(20,0.5388204);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(21,0.1150403);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(22,0.3217745);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(23,0.3796989);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(24,0.06284094);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(25,0.170911);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(26,0.1311264);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(27,0.0432774);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(28,0.1206517);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(29,0.07337073);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(30,-0.02752581);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(31,0.02195696);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(32,0.01662864);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(33,-0.01300329);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(34,0.007918936);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(35,0.03960449);
   secondJetPt_ttV_wMass_emu_stack_2->SetBinContent(36,0.1490455);
   secondJetPt_ttV_wMass_emu_stack_2->SetEntries(14144);
   secondJetPt_ttV_wMass_emu_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#00ff00");
   secondJetPt_ttV_wMass_emu_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   secondJetPt_ttV_wMass_emu_stack_2->SetLineColor(ci);
   secondJetPt_ttV_wMass_emu_stack_2->SetLineWidth(0);
   secondJetPt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_ttV_wMass_emu_stack_2->GetXaxis()->SetLabelFont(42);
   secondJetPt_ttV_wMass_emu_stack_2->GetXaxis()->SetLabelSize(0.035);
   secondJetPt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleSize(0.035);
   secondJetPt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   secondJetPt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleFont(42);
   secondJetPt_ttV_wMass_emu_stack_2->GetYaxis()->SetLabelFont(42);
   secondJetPt_ttV_wMass_emu_stack_2->GetYaxis()->SetLabelSize(0.035);
   secondJetPt_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleSize(0.035);
   secondJetPt_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleOffset(1);
   secondJetPt_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleFont(42);
   secondJetPt_ttV_wMass_emu_stack_2->GetZaxis()->SetLabelFont(42);
   secondJetPt_ttV_wMass_emu_stack_2->GetZaxis()->SetLabelSize(0.035);
   secondJetPt_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleSize(0.035);
   secondJetPt_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   secondJetPt_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_wMass_emu->Add(secondJetPt_ttV_wMass_emu_stack_2,"");
   
   TH1D *secondJetPt_wJets_wMass_emu_stack_3 = new TH1D("secondJetPt_wJets_wMass_emu_stack_3","secondJetPt_wJets_wMass_emu",35,0,300);
   secondJetPt_wJets_wMass_emu_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   secondJetPt_wJets_wMass_emu_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#cccccc");
   secondJetPt_wJets_wMass_emu_stack_3->SetLineColor(ci);
   secondJetPt_wJets_wMass_emu_stack_3->SetLineWidth(0);
   secondJetPt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_wJets_wMass_emu_stack_3->GetXaxis()->SetLabelFont(42);
   secondJetPt_wJets_wMass_emu_stack_3->GetXaxis()->SetLabelSize(0.035);
   secondJetPt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleSize(0.035);
   secondJetPt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   secondJetPt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleFont(42);
   secondJetPt_wJets_wMass_emu_stack_3->GetYaxis()->SetLabelFont(42);
   secondJetPt_wJets_wMass_emu_stack_3->GetYaxis()->SetLabelSize(0.035);
   secondJetPt_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleSize(0.035);
   secondJetPt_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleOffset(1);
   secondJetPt_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleFont(42);
   secondJetPt_wJets_wMass_emu_stack_3->GetZaxis()->SetLabelFont(42);
   secondJetPt_wJets_wMass_emu_stack_3->GetZaxis()->SetLabelSize(0.035);
   secondJetPt_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleSize(0.035);
   secondJetPt_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   secondJetPt_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_wMass_emu->Add(secondJetPt_wJets_wMass_emu_stack_3,"");
   
   TH1D *secondJetPt_VVV_wMass_emu_stack_4 = new TH1D("secondJetPt_VVV_wMass_emu_stack_4","secondJetPt_VVV_wMass_emu",35,0,300);
   secondJetPt_VVV_wMass_emu_stack_4->SetBinContent(6,0.06421515);
   secondJetPt_VVV_wMass_emu_stack_4->SetBinContent(8,0.03694032);
   secondJetPt_VVV_wMass_emu_stack_4->SetBinContent(10,0.033447);
   secondJetPt_VVV_wMass_emu_stack_4->SetBinContent(14,0.05776325);
   secondJetPt_VVV_wMass_emu_stack_4->SetBinContent(22,0.0318951);
   secondJetPt_VVV_wMass_emu_stack_4->SetEntries(9);
   secondJetPt_VVV_wMass_emu_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#00ffff");
   secondJetPt_VVV_wMass_emu_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   secondJetPt_VVV_wMass_emu_stack_4->SetLineColor(ci);
   secondJetPt_VVV_wMass_emu_stack_4->SetLineWidth(0);
   secondJetPt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_VVV_wMass_emu_stack_4->GetXaxis()->SetLabelFont(42);
   secondJetPt_VVV_wMass_emu_stack_4->GetXaxis()->SetLabelSize(0.035);
   secondJetPt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleSize(0.035);
   secondJetPt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   secondJetPt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleFont(42);
   secondJetPt_VVV_wMass_emu_stack_4->GetYaxis()->SetLabelFont(42);
   secondJetPt_VVV_wMass_emu_stack_4->GetYaxis()->SetLabelSize(0.035);
   secondJetPt_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleSize(0.035);
   secondJetPt_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleOffset(1);
   secondJetPt_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleFont(42);
   secondJetPt_VVV_wMass_emu_stack_4->GetZaxis()->SetLabelFont(42);
   secondJetPt_VVV_wMass_emu_stack_4->GetZaxis()->SetLabelSize(0.035);
   secondJetPt_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleSize(0.035);
   secondJetPt_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   secondJetPt_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_wMass_emu->Add(secondJetPt_VVV_wMass_emu_stack_4,"");
   
   TH1D *secondJetPt_VV_wMass_emu_stack_5 = new TH1D("secondJetPt_VV_wMass_emu_stack_5","secondJetPt_VV_wMass_emu",35,0,300);
   secondJetPt_VV_wMass_emu_stack_5->SetBinContent(5,0.4271973);
   secondJetPt_VV_wMass_emu_stack_5->SetBinContent(6,0.1666826);
   secondJetPt_VV_wMass_emu_stack_5->SetBinContent(7,0.559414);
   secondJetPt_VV_wMass_emu_stack_5->SetBinContent(8,0.2076252);
   secondJetPt_VV_wMass_emu_stack_5->SetBinContent(9,0.1866252);
   secondJetPt_VV_wMass_emu_stack_5->SetBinContent(10,0.2398217);
   secondJetPt_VV_wMass_emu_stack_5->SetBinContent(11,0.1735187);
   secondJetPt_VV_wMass_emu_stack_5->SetBinContent(12,0.03539526);
   secondJetPt_VV_wMass_emu_stack_5->SetBinContent(13,-0.02284423);
   secondJetPt_VV_wMass_emu_stack_5->SetBinContent(14,0.004911191);
   secondJetPt_VV_wMass_emu_stack_5->SetBinContent(16,0.1531139);
   secondJetPt_VV_wMass_emu_stack_5->SetBinContent(18,0.1753542);
   secondJetPt_VV_wMass_emu_stack_5->SetBinContent(20,0.1601829);
   secondJetPt_VV_wMass_emu_stack_5->SetBinContent(24,0.0126204);
   secondJetPt_VV_wMass_emu_stack_5->SetEntries(45);
   secondJetPt_VV_wMass_emu_stack_5->SetDirectory(0);

   ci = TColor::GetColor("#ff9933");
   secondJetPt_VV_wMass_emu_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#ff9933");
   secondJetPt_VV_wMass_emu_stack_5->SetLineColor(ci);
   secondJetPt_VV_wMass_emu_stack_5->SetLineWidth(0);
   secondJetPt_VV_wMass_emu_stack_5->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_VV_wMass_emu_stack_5->GetXaxis()->SetLabelFont(42);
   secondJetPt_VV_wMass_emu_stack_5->GetXaxis()->SetLabelSize(0.035);
   secondJetPt_VV_wMass_emu_stack_5->GetXaxis()->SetTitleSize(0.035);
   secondJetPt_VV_wMass_emu_stack_5->GetXaxis()->SetTitleOffset(1);
   secondJetPt_VV_wMass_emu_stack_5->GetXaxis()->SetTitleFont(42);
   secondJetPt_VV_wMass_emu_stack_5->GetYaxis()->SetLabelFont(42);
   secondJetPt_VV_wMass_emu_stack_5->GetYaxis()->SetLabelSize(0.035);
   secondJetPt_VV_wMass_emu_stack_5->GetYaxis()->SetTitleSize(0.035);
   secondJetPt_VV_wMass_emu_stack_5->GetYaxis()->SetTitleOffset(1);
   secondJetPt_VV_wMass_emu_stack_5->GetYaxis()->SetTitleFont(42);
   secondJetPt_VV_wMass_emu_stack_5->GetZaxis()->SetLabelFont(42);
   secondJetPt_VV_wMass_emu_stack_5->GetZaxis()->SetLabelSize(0.035);
   secondJetPt_VV_wMass_emu_stack_5->GetZaxis()->SetTitleSize(0.035);
   secondJetPt_VV_wMass_emu_stack_5->GetZaxis()->SetTitleOffset(1);
   secondJetPt_VV_wMass_emu_stack_5->GetZaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_wMass_emu->Add(secondJetPt_VV_wMass_emu_stack_5,"");
   
   TH1D *secondJetPt_SingleTop_wMass_emu_stack_6 = new TH1D("secondJetPt_SingleTop_wMass_emu_stack_6","secondJetPt_SingleTop_wMass_emu",35,0,300);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(4,0.4867655);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(5,8.981791);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(6,16.17762);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(7,17.14144);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(8,11.3923);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(9,8.19826);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(10,9.42827);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(11,7.174116);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(12,5.021844);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(13,4.606319);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(14,2.559128);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(15,2.016046);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(16,1.840596);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(17,1.615596);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(18,1.236519);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(19,1.035662);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(20,0.5298572);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(21,0.5383315);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(22,1.336841);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(23,0.3507154);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(24,0.2087893);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(25,0.3933661);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(26,0.38143);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(27,0.000960385);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(28,0.2074295);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(29,0.4094602);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(30,0.0008317265);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(31,0.2670567);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(32,0.3870924);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(34,0.0005307676);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(35,0.2133765);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(36,0.5957805);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetEntries(1034);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetDirectory(0);

   ci = TColor::GetColor("#ff00ff");
   secondJetPt_SingleTop_wMass_emu_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   secondJetPt_SingleTop_wMass_emu_stack_6->SetLineColor(ci);
   secondJetPt_SingleTop_wMass_emu_stack_6->SetLineWidth(0);
   secondJetPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetLabelFont(42);
   secondJetPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetLabelSize(0.035);
   secondJetPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleSize(0.035);
   secondJetPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleOffset(1);
   secondJetPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetLabelFont(42);
   secondJetPt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetLabelSize(0.035);
   secondJetPt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleSize(0.035);
   secondJetPt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleOffset(1);
   secondJetPt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetLabelFont(42);
   secondJetPt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetLabelSize(0.035);
   secondJetPt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleSize(0.035);
   secondJetPt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleOffset(1);
   secondJetPt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_wMass_emu->Add(secondJetPt_SingleTop_wMass_emu_stack_6,"");
   
   TH1D *secondJetPt_tt_wMass_emu_stack_7 = new TH1D("secondJetPt_tt_wMass_emu_stack_7","secondJetPt_tt_wMass_emu",35,0,300);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(4,12.1813);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(5,156.7622);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(6,292.9951);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(7,337.9815);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(8,327.3944);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(9,268.3909);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(10,224.9275);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(11,159.964);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(12,140.7624);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(13,100.9908);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(14,85.38843);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(15,62.92919);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(16,43.67068);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(17,36.16643);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(18,30.35911);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(19,25.1719);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(20,16.71516);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(21,15.58274);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(22,11.5952);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(23,9.868061);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(24,8.396133);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(25,4.172179);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(26,7.034879);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(27,4.239653);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(28,1.570154);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(29,2.787149);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(30,1.261974);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(31,1.380146);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(32,2.256596);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(33,1.070028);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(34,0.2870474);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(35,1.299396);
   secondJetPt_tt_wMass_emu_stack_7->SetBinContent(36,5.226538);
   secondJetPt_tt_wMass_emu_stack_7->SetEntries(7802);
   secondJetPt_tt_wMass_emu_stack_7->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   secondJetPt_tt_wMass_emu_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   secondJetPt_tt_wMass_emu_stack_7->SetLineColor(ci);
   secondJetPt_tt_wMass_emu_stack_7->SetLineWidth(0);
   secondJetPt_tt_wMass_emu_stack_7->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_tt_wMass_emu_stack_7->GetXaxis()->SetLabelFont(42);
   secondJetPt_tt_wMass_emu_stack_7->GetXaxis()->SetLabelSize(0.035);
   secondJetPt_tt_wMass_emu_stack_7->GetXaxis()->SetTitleSize(0.035);
   secondJetPt_tt_wMass_emu_stack_7->GetXaxis()->SetTitleOffset(1);
   secondJetPt_tt_wMass_emu_stack_7->GetXaxis()->SetTitleFont(42);
   secondJetPt_tt_wMass_emu_stack_7->GetYaxis()->SetLabelFont(42);
   secondJetPt_tt_wMass_emu_stack_7->GetYaxis()->SetLabelSize(0.035);
   secondJetPt_tt_wMass_emu_stack_7->GetYaxis()->SetTitleSize(0.035);
   secondJetPt_tt_wMass_emu_stack_7->GetYaxis()->SetTitleOffset(1);
   secondJetPt_tt_wMass_emu_stack_7->GetYaxis()->SetTitleFont(42);
   secondJetPt_tt_wMass_emu_stack_7->GetZaxis()->SetLabelFont(42);
   secondJetPt_tt_wMass_emu_stack_7->GetZaxis()->SetLabelSize(0.035);
   secondJetPt_tt_wMass_emu_stack_7->GetZaxis()->SetTitleSize(0.035);
   secondJetPt_tt_wMass_emu_stack_7->GetZaxis()->SetTitleOffset(1);
   secondJetPt_tt_wMass_emu_stack_7->GetZaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_wMass_emu->Add(secondJetPt_tt_wMass_emu_stack_7,"");
   
   TH1D *secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8 = new TH1D("secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8","secondJetPt_zPlusJetsMadgraph_wMass_emu",35,0,300);
   secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->SetLineColor(ci);
   secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->SetLineWidth(0);
   secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetLabelFont(42);
   secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetLabelSize(0.035);
   secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleSize(0.035);
   secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleOffset(1);
   secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleFont(42);
   secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetLabelFont(42);
   secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetLabelSize(0.035);
   secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleSize(0.035);
   secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleOffset(1);
   secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleFont(42);
   secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetLabelFont(42);
   secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetLabelSize(0.035);
   secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleSize(0.035);
   secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleOffset(1);
   secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_wMass_emu->Add(secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8,"");
   secondJetPt_SingleTop_wMass_emu->Draw("");
   
   TH1D *secondJetPt_data_wMass_emu__7 = new TH1D("secondJetPt_data_wMass_emu__7","secondJetPt_data_wMass_emu",35,0,300);
   secondJetPt_data_wMass_emu__7->SetBinContent(4,9);
   secondJetPt_data_wMass_emu__7->SetBinContent(5,187);
   secondJetPt_data_wMass_emu__7->SetBinContent(6,319);
   secondJetPt_data_wMass_emu__7->SetBinContent(7,421);
   secondJetPt_data_wMass_emu__7->SetBinContent(8,351);
   secondJetPt_data_wMass_emu__7->SetBinContent(9,307);
   secondJetPt_data_wMass_emu__7->SetBinContent(10,234);
   secondJetPt_data_wMass_emu__7->SetBinContent(11,186);
   secondJetPt_data_wMass_emu__7->SetBinContent(12,147);
   secondJetPt_data_wMass_emu__7->SetBinContent(13,114);
   secondJetPt_data_wMass_emu__7->SetBinContent(14,88);
   secondJetPt_data_wMass_emu__7->SetBinContent(15,60);
   secondJetPt_data_wMass_emu__7->SetBinContent(16,47);
   secondJetPt_data_wMass_emu__7->SetBinContent(17,49);
   secondJetPt_data_wMass_emu__7->SetBinContent(18,41);
   secondJetPt_data_wMass_emu__7->SetBinContent(19,15);
   secondJetPt_data_wMass_emu__7->SetBinContent(20,21);
   secondJetPt_data_wMass_emu__7->SetBinContent(21,17);
   secondJetPt_data_wMass_emu__7->SetBinContent(22,11);
   secondJetPt_data_wMass_emu__7->SetBinContent(23,9);
   secondJetPt_data_wMass_emu__7->SetBinContent(24,8);
   secondJetPt_data_wMass_emu__7->SetBinContent(25,3);
   secondJetPt_data_wMass_emu__7->SetBinContent(26,6);
   secondJetPt_data_wMass_emu__7->SetBinContent(27,3);
   secondJetPt_data_wMass_emu__7->SetBinContent(28,3);
   secondJetPt_data_wMass_emu__7->SetBinContent(29,2);
   secondJetPt_data_wMass_emu__7->SetBinContent(30,2);
   secondJetPt_data_wMass_emu__7->SetBinContent(31,1);
   secondJetPt_data_wMass_emu__7->SetBinContent(32,1);
   secondJetPt_data_wMass_emu__7->SetBinContent(33,2);
   secondJetPt_data_wMass_emu__7->SetBinContent(34,1);
   secondJetPt_data_wMass_emu__7->SetBinContent(36,3);
   secondJetPt_data_wMass_emu__7->SetEntries(2668);
   secondJetPt_data_wMass_emu__7->SetDirectory(0);
   secondJetPt_data_wMass_emu__7->SetFillColor(1);
   secondJetPt_data_wMass_emu__7->SetLineWidth(2);
   secondJetPt_data_wMass_emu__7->SetLineColor(1); //
   secondJetPt_data_wMass_emu__7->SetMarkerStyle(20);
   secondJetPt_data_wMass_emu__7->SetMarkerSize(1.4);
   secondJetPt_data_wMass_emu__7->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_data_wMass_emu__7->GetXaxis()->SetLabelFont(42);
   secondJetPt_data_wMass_emu__7->GetXaxis()->SetLabelSize(0.035);
   secondJetPt_data_wMass_emu__7->GetXaxis()->SetTitleSize(0.035);
   secondJetPt_data_wMass_emu__7->GetXaxis()->SetTitleOffset(1);
   secondJetPt_data_wMass_emu__7->GetXaxis()->SetTitleFont(42);
   secondJetPt_data_wMass_emu__7->GetYaxis()->SetLabelFont(42);
   secondJetPt_data_wMass_emu__7->GetYaxis()->SetLabelSize(0.035);
   secondJetPt_data_wMass_emu__7->GetYaxis()->SetTitleSize(0.035);
   secondJetPt_data_wMass_emu__7->GetYaxis()->SetTitleOffset(1);
   secondJetPt_data_wMass_emu__7->GetYaxis()->SetTitleFont(42);
   secondJetPt_data_wMass_emu__7->GetZaxis()->SetLabelFont(42);
   secondJetPt_data_wMass_emu__7->GetZaxis()->SetLabelSize(0.035);
   secondJetPt_data_wMass_emu__7->GetZaxis()->SetTitleSize(0.035);
   secondJetPt_data_wMass_emu__7->GetZaxis()->SetTitleOffset(1);
   secondJetPt_data_wMass_emu__7->GetZaxis()->SetTitleFont(42);
   secondJetPt_data_wMass_emu__7->Draw("e x0, same");
   
   TLegend *leg = new TLegend(0.78,0.42,0.98,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("secondJetPt_zPlusJetsMadgraph_wMass_emu_stack_8","Z+jets (LO)","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetPt_tt_wMass_emu_stack_7","t#bar{t}","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetPt_SingleTop_wMass_emu_stack_6","Single top","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetPt_VV_wMass_emu_stack_5","VV","f");

   ci = TColor::GetColor("#ff9933");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetPt_VVV_wMass_emu_stack_4","VVV","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetPt_wJets_wMass_emu_stack_3","W+jets","f");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetPt_ttV_wMass_emu_stack_2","t#bar{t}V","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetPt_tZq_wMass_emu_stack_1","tZq","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetPt_data_wMass_emu","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.4);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.968,0.9429101,"35.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06792969);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.096,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.05419922);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16899,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.04119141);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *secondJetPt_SingleTop_wMass_emu__8 = new TH1F("secondJetPt_SingleTop_wMass_emu__8","Second Jet p_{T}",35,0,300);
   secondJetPt_SingleTop_wMass_emu__8->SetMinimum(0);
   secondJetPt_SingleTop_wMass_emu__8->SetMaximum(486.255);
   secondJetPt_SingleTop_wMass_emu__8->SetDirectory(0);
   secondJetPt_SingleTop_wMass_emu__8->SetStats(0);
   secondJetPt_SingleTop_wMass_emu__8->SetLineStyle(0);
   secondJetPt_SingleTop_wMass_emu__8->SetLineWidth(0);
   secondJetPt_SingleTop_wMass_emu__8->SetMarkerStyle(20);
   secondJetPt_SingleTop_wMass_emu__8->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_SingleTop_wMass_emu__8->GetXaxis()->SetNdivisions(506);
   secondJetPt_SingleTop_wMass_emu__8->GetXaxis()->SetLabelFont(42);
   secondJetPt_SingleTop_wMass_emu__8->GetXaxis()->SetLabelOffset(999);
   secondJetPt_SingleTop_wMass_emu__8->GetXaxis()->SetLabelSize(0.05);
   secondJetPt_SingleTop_wMass_emu__8->GetXaxis()->SetTitleSize(0.08);
   secondJetPt_SingleTop_wMass_emu__8->GetXaxis()->SetTitleOffset(1);
   secondJetPt_SingleTop_wMass_emu__8->GetXaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_wMass_emu__8->GetYaxis()->SetTitle("Events");
   secondJetPt_SingleTop_wMass_emu__8->GetYaxis()->SetNdivisions(506);
   secondJetPt_SingleTop_wMass_emu__8->GetYaxis()->SetLabelFont(42);
   secondJetPt_SingleTop_wMass_emu__8->GetYaxis()->SetLabelOffset(0.01);
   secondJetPt_SingleTop_wMass_emu__8->GetYaxis()->SetLabelSize(0.062);
   secondJetPt_SingleTop_wMass_emu__8->GetYaxis()->SetTitleSize(0.08);
   secondJetPt_SingleTop_wMass_emu__8->GetYaxis()->SetTitleOffset(0.6336);
   secondJetPt_SingleTop_wMass_emu__8->GetYaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_wMass_emu__8->GetZaxis()->SetLabelFont(42);
   secondJetPt_SingleTop_wMass_emu__8->GetZaxis()->SetLabelOffset(0.007);
   secondJetPt_SingleTop_wMass_emu__8->GetZaxis()->SetLabelSize(0.05);
   secondJetPt_SingleTop_wMass_emu__8->GetZaxis()->SetTitleSize(0.08);
   secondJetPt_SingleTop_wMass_emu__8->GetZaxis()->SetTitleOffset(1);
   secondJetPt_SingleTop_wMass_emu__8->GetZaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_wMass_emu__8->Draw("sameaxis");
   
   TPaveText *pt = new TPaveText(0.4241286,0.9203237,0.5758714,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Second Jet p_{T}");
   pt->Draw();
   canvy_1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: canvy_2
   TPad *canvy_2 = new TPad("canvy_2", "newpad2",0.01,0.01,0.99,0.322);
   canvy_2->Draw();
   canvy_2->cd();
   canvy_2->SetFillColor(0);
   canvy_2->SetBorderMode(0);
   canvy_2->SetGridy();

   canvy_2->SetLeftMargin( L/W );
   canvy_2->SetRightMargin( R/W );
   canvy_2->SetTopMargin( T/H );
   canvy_2->SetBottomMargin( B/H * 2.6 );
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   
   TH1D *secondJetPt_data_wMass_emu__9 = new TH1D("secondJetPt_data_wMass_emu__9","",35,0,300);
   secondJetPt_data_wMass_emu__9->SetBinContent(4,0.7061289);
   secondJetPt_data_wMass_emu__9->SetBinContent(5,1.121052);
   secondJetPt_data_wMass_emu__9->SetBinContent(6,1.023731);
   secondJetPt_data_wMass_emu__9->SetBinContent(7,1.173818);
   secondJetPt_data_wMass_emu__9->SetBinContent(8,1.026998);
   secondJetPt_data_wMass_emu__9->SetBinContent(9,1.09511);
   secondJetPt_data_wMass_emu__9->SetBinContent(10,0.9849862);
   secondJetPt_data_wMass_emu__9->SetBinContent(11,1.097291);
   secondJetPt_data_wMass_emu__9->SetBinContent(12,0.995167);
   secondJetPt_data_wMass_emu__9->SetBinContent(13,1.059031);
   secondJetPt_data_wMass_emu__9->SetBinContent(14,0.9865352);
   secondJetPt_data_wMass_emu__9->SetBinContent(15,0.9108634);
   secondJetPt_data_wMass_emu__9->SetBinContent(16,1.011273);
   secondJetPt_data_wMass_emu__9->SetBinContent(17,1.27169);
   secondJetPt_data_wMass_emu__9->SetBinContent(18,1.260725);
   secondJetPt_data_wMass_emu__9->SetBinContent(19,0.5653982);
   secondJetPt_data_wMass_emu__9->SetBinContent(20,1.170002);
   secondJetPt_data_wMass_emu__9->SetBinContent(21,1.046871);
   secondJetPt_data_wMass_emu__9->SetBinContent(22,0.8280535);
   secondJetPt_data_wMass_emu__9->SetBinContent(23,0.8489876);
   secondJetPt_data_wMass_emu__9->SetBinContent(24,0.9213823);
   secondJetPt_data_wMass_emu__9->SetBinContent(25,0.6330008);
   secondJetPt_data_wMass_emu__9->SetBinContent(26,0.7943876);
   secondJetPt_data_wMass_emu__9->SetBinContent(27,0.7005278);
   secondJetPt_data_wMass_emu__9->SetBinContent(28,1.581671);
   secondJetPt_data_wMass_emu__9->SetBinContent(29,0.6113263);
   secondJetPt_data_wMass_emu__9->SetBinContent(30,1.617337);
   secondJetPt_data_wMass_emu__9->SetBinContent(31,0.5985934);
   secondJetPt_data_wMass_emu__9->SetBinContent(32,0.3754994);
   secondJetPt_data_wMass_emu__9->SetBinContent(33,1.892078);
   secondJetPt_data_wMass_emu__9->SetBinContent(34,3.392279);
   secondJetPt_data_wMass_emu__9->SetBinContent(36,0.5022921);
   secondJetPt_data_wMass_emu__9->SetBinError(4,0.3074459);
   secondJetPt_data_wMass_emu__9->SetBinError(5,0.1193934);
   secondJetPt_data_wMass_emu__9->SetBinError(6,0.08153929);
   secondJetPt_data_wMass_emu__9->SetBinError(7,0.08434729);
   secondJetPt_data_wMass_emu__9->SetBinError(8,0.0780446);
   secondJetPt_data_wMass_emu__9->SetBinError(9,0.09046736);
   secondJetPt_data_wMass_emu__9->SetBinError(10,0.09071957);
   secondJetPt_data_wMass_emu__9->SetBinError(11,0.1165185);
   secondJetPt_data_wMass_emu__9->SetBinError(12,0.1159383);
   secondJetPt_data_wMass_emu__9->SetBinError(13,0.1423272);
   secondJetPt_data_wMass_emu__9->SetBinError(14,0.1482243);
   secondJetPt_data_wMass_emu__9->SetBinError(15,0.162552);
   secondJetPt_data_wMass_emu__9->SetBinError(16,0.2091967);
   secondJetPt_data_wMass_emu__9->SetBinError(17,0.2738154);
   secondJetPt_data_wMass_emu__9->SetBinError(18,0.2960413);
   secondJetPt_data_wMass_emu__9->SetBinError(19,0.1826507);
   secondJetPt_data_wMass_emu__9->SetBinError(20,0.3761031);
   secondJetPt_data_wMass_emu__9->SetBinError(21,0.3632571);
   secondJetPt_data_wMass_emu__9->SetBinError(22,0.3375643);
   secondJetPt_data_wMass_emu__9->SetBinError(23,0.3848107);
   secondJetPt_data_wMass_emu__9->SetBinError(24,0.4515458);
   secondJetPt_data_wMass_emu__9->SetBinError(25,0.4670215);
   secondJetPt_data_wMass_emu__9->SetBinError(26,0.4344252);
   secondJetPt_data_wMass_emu__9->SetBinError(27,0.52742);
   secondJetPt_data_wMass_emu__9->SetBinError(28,1.467256);
   secondJetPt_data_wMass_emu__9->SetBinError(29,0.5487188);
   secondJetPt_data_wMass_emu__9->SetBinError(30,1.850186);
   secondJetPt_data_wMass_emu__9->SetBinError(31,0.7568346);
   secondJetPt_data_wMass_emu__9->SetBinError(32,0.4403921);
   secondJetPt_data_wMass_emu__9->SetBinError(33,2.27525);
   secondJetPt_data_wMass_emu__9->SetBinError(34,7.109459);
   secondJetPt_data_wMass_emu__9->SetBinError(36,0.3554454);
   secondJetPt_data_wMass_emu__9->SetMinimum(0.5);
   secondJetPt_data_wMass_emu__9->SetMaximum(1.5);
   secondJetPt_data_wMass_emu__9->SetEntries(17.25553);
   secondJetPt_data_wMass_emu__9->SetDirectory(0);
   secondJetPt_data_wMass_emu__9->SetStats(0);
   secondJetPt_data_wMass_emu__9->SetFillColor(1);
   secondJetPt_data_wMass_emu__9->SetLineWidth(2);
   secondJetPt_data_wMass_emu__9->SetLineColor(1); //
   secondJetPt_data_wMass_emu__9->SetMarkerStyle(20);
   secondJetPt_data_wMass_emu__9->SetMarkerSize(1.6);
   secondJetPt_data_wMass_emu__9->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_data_wMass_emu__9->GetXaxis()->SetNdivisions(506);
   secondJetPt_data_wMass_emu__9->GetXaxis()->SetLabelFont(42);
   secondJetPt_data_wMass_emu__9->GetXaxis()->SetLabelOffset(0.013);
   secondJetPt_data_wMass_emu__9->GetXaxis()->SetLabelSize(0.13);
   secondJetPt_data_wMass_emu__9->GetXaxis()->SetTitleSize(0.13);
   secondJetPt_data_wMass_emu__9->GetXaxis()->SetTitleOffset(1);
   secondJetPt_data_wMass_emu__9->GetXaxis()->SetTitleFont(42);
   secondJetPt_data_wMass_emu__9->GetYaxis()->SetTitle("Data/MC");
   secondJetPt_data_wMass_emu__9->GetYaxis()->CenterTitle(true);
   secondJetPt_data_wMass_emu__9->GetYaxis()->SetNdivisions(506);
   secondJetPt_data_wMass_emu__9->GetYaxis()->SetLabelFont(42);
   secondJetPt_data_wMass_emu__9->GetYaxis()->SetLabelOffset(0.01);
   secondJetPt_data_wMass_emu__9->GetYaxis()->SetLabelSize(0.12);
   secondJetPt_data_wMass_emu__9->GetYaxis()->SetTitleSize(0.16);
   secondJetPt_data_wMass_emu__9->GetYaxis()->SetTitleOffset(0.3);
   secondJetPt_data_wMass_emu__9->GetYaxis()->SetTitleFont(42);
   secondJetPt_data_wMass_emu__9->GetZaxis()->SetLabelFont(42);
   secondJetPt_data_wMass_emu__9->GetZaxis()->SetLabelSize(0.035);
   secondJetPt_data_wMass_emu__9->GetZaxis()->SetTitleSize(0.035);
   secondJetPt_data_wMass_emu__9->GetZaxis()->SetTitleOffset(1);
   secondJetPt_data_wMass_emu__9->GetZaxis()->SetTitleFont(42);
   secondJetPt_data_wMass_emu__9->Draw("e x0, SCAT");
   canvy_2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
//   c1->SetSelected(secondJetPt_data_wMass_emu);
   c1->SaveAs("secondJetPt_wMass.pdf");
}
