void secondJetEta_SingleTop_wMass()
{
//=========Macro generated from canvas: secondJetEta_SingleTop_wMass/secondJetEta_SingleTop_wMass
//=========  (Wed Aug 21 19:46:33 2019) by ROOT version 6.18/00

   // Set up cavas
   int W = 1280;
   int H = 1024;
   int H_ref = 925;
   int W_ref = 1024;

   // references for T, B, L, R
   float T = 0.08*H_ref;
   float B = 0.12*H_ref;
   float L = 0.12*W_ref;
   float R = 0.04*W_ref;

   TCanvas *c1 = new TCanvas("c1","c1",50,50,W,H);
   c1->cd();
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetLeftMargin( L/W );
   c1->SetRightMargin( R/W );
   c1->SetTopMargin( T/H );
   c1->SetBottomMargin( B/H );
   c1->SetTickx(0);
   c1->SetTicky(0);
  
// ------------>Primitives in pad: canvy_1
   TPad *canvy_1 = new TPad("canvy_1", "newpad",0.01,0.315,0.99,0.99);
   canvy_1->Draw();
   canvy_1->cd();
   canvy_1->SetFillColor(0);
   canvy_1->SetBorderMode(0);

   canvy_1->SetLeftMargin( L/W );
   canvy_1->SetRightMargin( R/W );
   canvy_1->SetTopMargin( T/H );
   canvy_1->SetBottomMargin( B/H * 0.3 );

   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);
   
   THStack *secondJetEta_SingleTop_wMass_emu = new THStack();
   secondJetEta_SingleTop_wMass_emu->SetName("secondJetEta_SingleTop_wMass_emu");
   secondJetEta_SingleTop_wMass_emu->SetTitle(";Subleading jet #eta;Events");
   secondJetEta_SingleTop_wMass_emu->SetMaximum(177.1);
   
   TH1F *secondJetEta_SingleTop_wMass_emu_stack_3 = new TH1F("secondJetEta_SingleTop_wMass_emu_stack_3","Second Jet #eta",25,0,5);
   secondJetEta_SingleTop_wMass_emu_stack_3->SetMinimum(0);
   secondJetEta_SingleTop_wMass_emu_stack_3->SetMaximum(185.955);
   secondJetEta_SingleTop_wMass_emu_stack_3->SetDirectory(0);
   secondJetEta_SingleTop_wMass_emu_stack_3->SetStats(0);
   secondJetEta_SingleTop_wMass_emu_stack_3->SetLineStyle(0);
   secondJetEta_SingleTop_wMass_emu_stack_3->SetLineWidth(0);
   secondJetEta_SingleTop_wMass_emu_stack_3->SetMarkerStyle(20);
   secondJetEta_SingleTop_wMass_emu_stack_3->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_SingleTop_wMass_emu_stack_3->GetXaxis()->SetNdivisions(506);
   secondJetEta_SingleTop_wMass_emu_stack_3->GetXaxis()->SetLabelFont(42);
   secondJetEta_SingleTop_wMass_emu_stack_3->GetXaxis()->SetLabelOffset(999);
   secondJetEta_SingleTop_wMass_emu_stack_3->GetXaxis()->SetLabelSize(0.05);
   secondJetEta_SingleTop_wMass_emu_stack_3->GetXaxis()->SetTitleSize(0.08);
   secondJetEta_SingleTop_wMass_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   secondJetEta_SingleTop_wMass_emu_stack_3->GetXaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_wMass_emu_stack_3->GetYaxis()->SetTitle("Events");
   secondJetEta_SingleTop_wMass_emu_stack_3->GetYaxis()->SetNdivisions(506);
   secondJetEta_SingleTop_wMass_emu_stack_3->GetYaxis()->SetLabelFont(42);
   secondJetEta_SingleTop_wMass_emu_stack_3->GetYaxis()->SetLabelOffset(0.01);
   secondJetEta_SingleTop_wMass_emu_stack_3->GetYaxis()->SetLabelSize(0.062);
   secondJetEta_SingleTop_wMass_emu_stack_3->GetYaxis()->SetTitleSize(0.08);
   secondJetEta_SingleTop_wMass_emu_stack_3->GetYaxis()->SetTitleOffset(0.6336);
   secondJetEta_SingleTop_wMass_emu_stack_3->GetYaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_wMass_emu_stack_3->GetZaxis()->SetLabelFont(42);
   secondJetEta_SingleTop_wMass_emu_stack_3->GetZaxis()->SetLabelOffset(0.007);
   secondJetEta_SingleTop_wMass_emu_stack_3->GetZaxis()->SetLabelSize(0.05);
   secondJetEta_SingleTop_wMass_emu_stack_3->GetZaxis()->SetTitleSize(0.08);
   secondJetEta_SingleTop_wMass_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   secondJetEta_SingleTop_wMass_emu_stack_3->GetZaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_wMass_emu->SetHistogram(secondJetEta_SingleTop_wMass_emu_stack_3);
   
   
   TH1D *secondJetEta_tZq_wMass_emu_stack_1 = new TH1D("secondJetEta_tZq_wMass_emu_stack_1","secondJetEta_tZq_wMass_emu",25,0,5);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(0,0.1537351);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(1,0.01609083);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(2,0.01620063);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(3,0.01074517);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(4,0.02500435);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(5,0.01297274);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(6,0.01206354);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(7,0.005182706);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(8,0.01424925);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(9,0.01230154);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(10,0.002114729);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(11,0.01074022);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(12,0.01079603);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(13,0.008886167);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(14,0.01196488);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(15,0.004969728);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(16,0.004662737);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(17,0.00896551);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(18,0.001430358);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(19,0.002345207);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(20,-0.0006325148);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(21,-0.0006885962);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(22,-0.000602721);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(23,0.0009086917);
   secondJetEta_tZq_wMass_emu_stack_1->SetBinContent(24,2.121553e-06);
   secondJetEta_tZq_wMass_emu_stack_1->SetEntries(2170);
   secondJetEta_tZq_wMass_emu_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ffff00");
   secondJetEta_tZq_wMass_emu_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   secondJetEta_tZq_wMass_emu_stack_1->SetLineColor(ci);
   secondJetEta_tZq_wMass_emu_stack_1->SetLineWidth(0);
   secondJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetLabelFont(42);
   secondJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetLabelSize(0.035);
   secondJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleSize(0.035);
   secondJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   secondJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleFont(42);
   secondJetEta_tZq_wMass_emu_stack_1->GetYaxis()->SetLabelFont(42);
   secondJetEta_tZq_wMass_emu_stack_1->GetYaxis()->SetLabelSize(0.035);
   secondJetEta_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleSize(0.035);
   secondJetEta_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleOffset(1);
   secondJetEta_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleFont(42);
   secondJetEta_tZq_wMass_emu_stack_1->GetZaxis()->SetLabelFont(42);
   secondJetEta_tZq_wMass_emu_stack_1->GetZaxis()->SetLabelSize(0.035);
   secondJetEta_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleSize(0.035);
   secondJetEta_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   secondJetEta_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_wMass_emu->Add(secondJetEta_tZq_wMass_emu_stack_1,"");
   
   TH1D *secondJetEta_ttV_wMass_emu_stack_2 = new TH1D("secondJetEta_ttV_wMass_emu_stack_2","secondJetEta_ttV_wMass_emu",25,0,5);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(0,13.5241);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(1,1.806942);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(2,1.904875);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(3,1.905917);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(4,1.3729);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(5,1.195098);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(6,1.200108);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(7,1.184851);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(8,1.053301);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(9,0.6372222);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(10,0.6998849);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(11,0.4563003);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(12,0.3718356);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(13,0.1654345);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(14,0.08783097);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(15,0.2015712);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(16,-0.05197428);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(17,0.03500742);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(18,0.09505737);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(19,0.003189197);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(20,0.01745725);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(21,0.00806271);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(22,0.005115306);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(23,0.0004001971);
   secondJetEta_ttV_wMass_emu_stack_2->SetBinContent(24,-0.001316237);
   secondJetEta_ttV_wMass_emu_stack_2->SetEntries(14144);
   secondJetEta_ttV_wMass_emu_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#00ff00");
   secondJetEta_ttV_wMass_emu_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   secondJetEta_ttV_wMass_emu_stack_2->SetLineColor(ci);
   secondJetEta_ttV_wMass_emu_stack_2->SetLineWidth(0);
   secondJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetLabelFont(42);
   secondJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetLabelSize(0.035);
   secondJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleSize(0.035);
   secondJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   secondJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleFont(42);
   secondJetEta_ttV_wMass_emu_stack_2->GetYaxis()->SetLabelFont(42);
   secondJetEta_ttV_wMass_emu_stack_2->GetYaxis()->SetLabelSize(0.035);
   secondJetEta_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleSize(0.035);
   secondJetEta_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleOffset(1);
   secondJetEta_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleFont(42);
   secondJetEta_ttV_wMass_emu_stack_2->GetZaxis()->SetLabelFont(42);
   secondJetEta_ttV_wMass_emu_stack_2->GetZaxis()->SetLabelSize(0.035);
   secondJetEta_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleSize(0.035);
   secondJetEta_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   secondJetEta_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_wMass_emu->Add(secondJetEta_ttV_wMass_emu_stack_2,"");
   
   TH1D *secondJetEta_wJets_wMass_emu_stack_3 = new TH1D("secondJetEta_wJets_wMass_emu_stack_3","secondJetEta_wJets_wMass_emu",25,0,5);
   secondJetEta_wJets_wMass_emu_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   secondJetEta_wJets_wMass_emu_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#cccccc");
   secondJetEta_wJets_wMass_emu_stack_3->SetLineColor(ci);
   secondJetEta_wJets_wMass_emu_stack_3->SetLineWidth(0);
   secondJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetLabelFont(42);
   secondJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetLabelSize(0.035);
   secondJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleSize(0.035);
   secondJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   secondJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleFont(42);
   secondJetEta_wJets_wMass_emu_stack_3->GetYaxis()->SetLabelFont(42);
   secondJetEta_wJets_wMass_emu_stack_3->GetYaxis()->SetLabelSize(0.035);
   secondJetEta_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleSize(0.035);
   secondJetEta_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleOffset(1);
   secondJetEta_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleFont(42);
   secondJetEta_wJets_wMass_emu_stack_3->GetZaxis()->SetLabelFont(42);
   secondJetEta_wJets_wMass_emu_stack_3->GetZaxis()->SetLabelSize(0.035);
   secondJetEta_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleSize(0.035);
   secondJetEta_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   secondJetEta_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_wMass_emu->Add(secondJetEta_wJets_wMass_emu_stack_3,"");
   
   TH1D *secondJetEta_VVV_wMass_emu_stack_4 = new TH1D("secondJetEta_VVV_wMass_emu_stack_4","secondJetEta_VVV_wMass_emu",25,0,5);
   secondJetEta_VVV_wMass_emu_stack_4->SetBinContent(0,0.1573765);
   secondJetEta_VVV_wMass_emu_stack_4->SetBinContent(1,0.03392089);
   secondJetEta_VVV_wMass_emu_stack_4->SetBinContent(2,0.001068281);
   secondJetEta_VVV_wMass_emu_stack_4->SetBinContent(3,0.0318951);
   secondJetEta_VVV_wMass_emu_stack_4->SetEntries(9);
   secondJetEta_VVV_wMass_emu_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#00ffff");
   secondJetEta_VVV_wMass_emu_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   secondJetEta_VVV_wMass_emu_stack_4->SetLineColor(ci);
   secondJetEta_VVV_wMass_emu_stack_4->SetLineWidth(0);
   secondJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetLabelFont(42);
   secondJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetLabelSize(0.035);
   secondJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleSize(0.035);
   secondJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   secondJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleFont(42);
   secondJetEta_VVV_wMass_emu_stack_4->GetYaxis()->SetLabelFont(42);
   secondJetEta_VVV_wMass_emu_stack_4->GetYaxis()->SetLabelSize(0.035);
   secondJetEta_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleSize(0.035);
   secondJetEta_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleOffset(1);
   secondJetEta_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleFont(42);
   secondJetEta_VVV_wMass_emu_stack_4->GetZaxis()->SetLabelFont(42);
   secondJetEta_VVV_wMass_emu_stack_4->GetZaxis()->SetLabelSize(0.035);
   secondJetEta_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleSize(0.035);
   secondJetEta_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   secondJetEta_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_wMass_emu->Add(secondJetEta_VVV_wMass_emu_stack_4,"");
   
   TH1D *secondJetEta_VV_wMass_emu_stack_5 = new TH1D("secondJetEta_VV_wMass_emu_stack_5","secondJetEta_VV_wMass_emu",25,0,5);
   secondJetEta_VV_wMass_emu_stack_5->SetBinContent(0,1.361314);
   secondJetEta_VV_wMass_emu_stack_5->SetBinContent(1,0.02519466);
   secondJetEta_VV_wMass_emu_stack_5->SetBinContent(2,0.02487442);
   secondJetEta_VV_wMass_emu_stack_5->SetBinContent(3,-0.007084249);
   secondJetEta_VV_wMass_emu_stack_5->SetBinContent(4,0.2834474);
   secondJetEta_VV_wMass_emu_stack_5->SetBinContent(6,0.3874233);
   secondJetEta_VV_wMass_emu_stack_5->SetBinContent(8,-0.002419416);
   secondJetEta_VV_wMass_emu_stack_5->SetBinContent(9,0.1753542);
   secondJetEta_VV_wMass_emu_stack_5->SetBinContent(10,0.01255555);
   secondJetEta_VV_wMass_emu_stack_5->SetBinContent(11,0.00578657);
   secondJetEta_VV_wMass_emu_stack_5->SetBinContent(12,0.01667675);
   secondJetEta_VV_wMass_emu_stack_5->SetBinContent(15,0.002215747);
   secondJetEta_VV_wMass_emu_stack_5->SetBinContent(17,0.1942798);
   secondJetEta_VV_wMass_emu_stack_5->SetEntries(45);
   secondJetEta_VV_wMass_emu_stack_5->SetDirectory(0);

   ci = TColor::GetColor("#ff9933");
   secondJetEta_VV_wMass_emu_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#ff9933");
   secondJetEta_VV_wMass_emu_stack_5->SetLineColor(ci);
   secondJetEta_VV_wMass_emu_stack_5->SetLineWidth(0);
   secondJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetLabelFont(42);
   secondJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetLabelSize(0.035);
   secondJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetTitleSize(0.035);
   secondJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetTitleOffset(1);
   secondJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetTitleFont(42);
   secondJetEta_VV_wMass_emu_stack_5->GetYaxis()->SetLabelFont(42);
   secondJetEta_VV_wMass_emu_stack_5->GetYaxis()->SetLabelSize(0.035);
   secondJetEta_VV_wMass_emu_stack_5->GetYaxis()->SetTitleSize(0.035);
   secondJetEta_VV_wMass_emu_stack_5->GetYaxis()->SetTitleOffset(1);
   secondJetEta_VV_wMass_emu_stack_5->GetYaxis()->SetTitleFont(42);
   secondJetEta_VV_wMass_emu_stack_5->GetZaxis()->SetLabelFont(42);
   secondJetEta_VV_wMass_emu_stack_5->GetZaxis()->SetLabelSize(0.035);
   secondJetEta_VV_wMass_emu_stack_5->GetZaxis()->SetTitleSize(0.035);
   secondJetEta_VV_wMass_emu_stack_5->GetZaxis()->SetTitleOffset(1);
   secondJetEta_VV_wMass_emu_stack_5->GetZaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_wMass_emu->Add(secondJetEta_VV_wMass_emu_stack_5,"");
   
   TH1D *secondJetEta_SingleTop_wMass_emu_stack_6 = new TH1D("secondJetEta_SingleTop_wMass_emu_stack_6","secondJetEta_SingleTop_wMass_emu",25,0,5);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(0,55.15565);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(1,4.059214);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(2,3.87563);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(3,5.135993);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(4,4.762908);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(5,6.103318);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(6,4.421076);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(7,3.070252);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(8,3.627083);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(9,3.655192);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(10,2.114187);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(11,1.843149);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(12,0.7818309);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(13,0.5444111);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(14,1.588023);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(15,1.548371);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(16,0.3594436);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(17,0.6113556);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(18,0.449216);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(19,0.6864462);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(20,0.1661525);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(21,0.001429729);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(23,0.00144155);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(24,0.1723553);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetEntries(1034);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetDirectory(0);

   ci = TColor::GetColor("#ff00ff");
   secondJetEta_SingleTop_wMass_emu_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   secondJetEta_SingleTop_wMass_emu_stack_6->SetLineColor(ci);
   secondJetEta_SingleTop_wMass_emu_stack_6->SetLineWidth(0);
   secondJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetLabelFont(42);
   secondJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetLabelSize(0.035);
   secondJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleSize(0.035);
   secondJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleOffset(1);
   secondJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_wMass_emu_stack_6->GetYaxis()->SetLabelFont(42);
   secondJetEta_SingleTop_wMass_emu_stack_6->GetYaxis()->SetLabelSize(0.035);
   secondJetEta_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleSize(0.035);
   secondJetEta_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleOffset(1);
   secondJetEta_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_wMass_emu_stack_6->GetZaxis()->SetLabelFont(42);
   secondJetEta_SingleTop_wMass_emu_stack_6->GetZaxis()->SetLabelSize(0.035);
   secondJetEta_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleSize(0.035);
   secondJetEta_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleOffset(1);
   secondJetEta_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_wMass_emu->Add(secondJetEta_SingleTop_wMass_emu_stack_6,"");
   
   TH1D *secondJetEta_tt_wMass_emu_stack_7 = new TH1D("secondJetEta_tt_wMass_emu_stack_7","secondJetEta_tt_wMass_emu",25,0,5);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(0,1190.594);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(1,133.3078);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(2,124.0958);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(3,131.2127);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(4,120.4334);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(5,103.9506);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(6,92.39661);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(7,86.63212);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(8,78.15177);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(9,68.95466);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(10,49.97024);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(11,46.53661);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(12,37.72827);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(13,24.29386);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(14,33.92849);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(15,21.92189);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(16,14.12619);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(17,12.46173);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(18,10.71259);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(19,5.824197);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(20,5.403363);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(21,3.821714);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(22,2.677706);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(23,1.367797);
   secondJetEta_tt_wMass_emu_stack_7->SetBinContent(24,0.2749566);
   secondJetEta_tt_wMass_emu_stack_7->SetEntries(7802);
   secondJetEta_tt_wMass_emu_stack_7->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   secondJetEta_tt_wMass_emu_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   secondJetEta_tt_wMass_emu_stack_7->SetLineColor(ci);
   secondJetEta_tt_wMass_emu_stack_7->SetLineWidth(0);
   secondJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetLabelFont(42);
   secondJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetLabelSize(0.035);
   secondJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetTitleSize(0.035);
   secondJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetTitleOffset(1);
   secondJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetTitleFont(42);
   secondJetEta_tt_wMass_emu_stack_7->GetYaxis()->SetLabelFont(42);
   secondJetEta_tt_wMass_emu_stack_7->GetYaxis()->SetLabelSize(0.035);
   secondJetEta_tt_wMass_emu_stack_7->GetYaxis()->SetTitleSize(0.035);
   secondJetEta_tt_wMass_emu_stack_7->GetYaxis()->SetTitleOffset(1);
   secondJetEta_tt_wMass_emu_stack_7->GetYaxis()->SetTitleFont(42);
   secondJetEta_tt_wMass_emu_stack_7->GetZaxis()->SetLabelFont(42);
   secondJetEta_tt_wMass_emu_stack_7->GetZaxis()->SetLabelSize(0.035);
   secondJetEta_tt_wMass_emu_stack_7->GetZaxis()->SetTitleSize(0.035);
   secondJetEta_tt_wMass_emu_stack_7->GetZaxis()->SetTitleOffset(1);
   secondJetEta_tt_wMass_emu_stack_7->GetZaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_wMass_emu->Add(secondJetEta_tt_wMass_emu_stack_7,"");
   
   TH1D *secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8 = new TH1D("secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8","secondJetEta_zPlusJetsMadgraph_wMass_emu",25,0,5);
   secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->SetLineColor(ci);
   secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->SetLineWidth(0);
   secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetLabelFont(42);
   secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetLabelSize(0.035);
   secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleSize(0.035);
   secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleOffset(1);
   secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleFont(42);
   secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetLabelFont(42);
   secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetLabelSize(0.035);
   secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleSize(0.035);
   secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleOffset(1);
   secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleFont(42);
   secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetLabelFont(42);
   secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetLabelSize(0.035);
   secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleSize(0.035);
   secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleOffset(1);
   secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_wMass_emu->Add(secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8,"");
   secondJetEta_SingleTop_wMass_emu->Draw("");
   
   TH1D *secondJetEta_data_wMass_emu__7 = new TH1D("secondJetEta_data_wMass_emu__7","secondJetEta_data_wMass_emu",25,0,5);
   secondJetEta_data_wMass_emu__7->SetBinContent(0,1356);
   secondJetEta_data_wMass_emu__7->SetBinContent(1,155);
   secondJetEta_data_wMass_emu__7->SetBinContent(2,161);
   secondJetEta_data_wMass_emu__7->SetBinContent(3,127);
   secondJetEta_data_wMass_emu__7->SetBinContent(4,106);
   secondJetEta_data_wMass_emu__7->SetBinContent(5,108);
   secondJetEta_data_wMass_emu__7->SetBinContent(6,107);
   secondJetEta_data_wMass_emu__7->SetBinContent(7,100);
   secondJetEta_data_wMass_emu__7->SetBinContent(8,78);
   secondJetEta_data_wMass_emu__7->SetBinContent(9,67);
   secondJetEta_data_wMass_emu__7->SetBinContent(10,81);
   secondJetEta_data_wMass_emu__7->SetBinContent(11,45);
   secondJetEta_data_wMass_emu__7->SetBinContent(12,43);
   secondJetEta_data_wMass_emu__7->SetBinContent(13,34);
   secondJetEta_data_wMass_emu__7->SetBinContent(14,35);
   secondJetEta_data_wMass_emu__7->SetBinContent(15,18);
   secondJetEta_data_wMass_emu__7->SetBinContent(16,12);
   secondJetEta_data_wMass_emu__7->SetBinContent(17,10);
   secondJetEta_data_wMass_emu__7->SetBinContent(18,10);
   secondJetEta_data_wMass_emu__7->SetBinContent(19,5);
   secondJetEta_data_wMass_emu__7->SetBinContent(20,6);
   secondJetEta_data_wMass_emu__7->SetBinContent(21,2);
   secondJetEta_data_wMass_emu__7->SetBinContent(22,2);
   secondJetEta_data_wMass_emu__7->SetEntries(2668);
   secondJetEta_data_wMass_emu__7->SetDirectory(0);
   secondJetEta_data_wMass_emu__7->SetFillColor(1);
   secondJetEta_data_wMass_emu__7->SetLineColor(1); //
   secondJetEta_data_wMass_emu__7->SetLineWidth(2);
   secondJetEta_data_wMass_emu__7->SetMarkerStyle(20);
   secondJetEta_data_wMass_emu__7->SetMarkerSize(1.4);
   secondJetEta_data_wMass_emu__7->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_data_wMass_emu__7->GetXaxis()->SetLabelFont(42);
   secondJetEta_data_wMass_emu__7->GetXaxis()->SetLabelSize(0.035);
   secondJetEta_data_wMass_emu__7->GetXaxis()->SetTitleSize(0.035);
   secondJetEta_data_wMass_emu__7->GetXaxis()->SetTitleOffset(1);
   secondJetEta_data_wMass_emu__7->GetXaxis()->SetTitleFont(42);
   secondJetEta_data_wMass_emu__7->GetYaxis()->SetLabelFont(42);
   secondJetEta_data_wMass_emu__7->GetYaxis()->SetLabelSize(0.035);
   secondJetEta_data_wMass_emu__7->GetYaxis()->SetTitleSize(0.035);
   secondJetEta_data_wMass_emu__7->GetYaxis()->SetTitleOffset(1);
   secondJetEta_data_wMass_emu__7->GetYaxis()->SetTitleFont(42);
   secondJetEta_data_wMass_emu__7->GetZaxis()->SetLabelFont(42);
   secondJetEta_data_wMass_emu__7->GetZaxis()->SetLabelSize(0.035);
   secondJetEta_data_wMass_emu__7->GetZaxis()->SetTitleSize(0.035);
   secondJetEta_data_wMass_emu__7->GetZaxis()->SetTitleOffset(1);
   secondJetEta_data_wMass_emu__7->GetZaxis()->SetTitleFont(42);
   secondJetEta_data_wMass_emu__7->Draw("e x0, same");
   
   TLegend *leg = new TLegend(0.78,0.42,0.98,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("secondJetEta_zPlusJetsMadgraph_wMass_emu_stack_8","Z+jets (LO)","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetEta_tt_wMass_emu_stack_7","t#bar{t}","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetEta_SingleTop_wMass_emu_stack_6","Single top","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetEta_VV_wMass_emu_stack_5","VV","f");

   ci = TColor::GetColor("#ff9933");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetEta_VVV_wMass_emu_stack_4","VVV","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetEta_wJets_wMass_emu_stack_3","W+jets","f");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetEta_ttV_wMass_emu_stack_2","t#bar{t}V","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetEta_tZq_wMass_emu_stack_1","tZq","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetEta_data_wMass_emu","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.4);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.968,0.9429101,"35.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06792969);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.096,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.05419922);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16899,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.04119141);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *secondJetEta_SingleTop_wMass_emu__8 = new TH1F("secondJetEta_SingleTop_wMass_emu__8","Second Jet #eta",25,0,5);
   secondJetEta_SingleTop_wMass_emu__8->SetMinimum(0);
   secondJetEta_SingleTop_wMass_emu__8->SetMaximum(185.955);
   secondJetEta_SingleTop_wMass_emu__8->SetDirectory(0);
   secondJetEta_SingleTop_wMass_emu__8->SetStats(0);
   secondJetEta_SingleTop_wMass_emu__8->SetLineStyle(0);
   secondJetEta_SingleTop_wMass_emu__8->SetLineWidth(0);
   secondJetEta_SingleTop_wMass_emu__8->SetMarkerStyle(20);
   secondJetEta_SingleTop_wMass_emu__8->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_SingleTop_wMass_emu__8->GetXaxis()->SetNdivisions(506);
   secondJetEta_SingleTop_wMass_emu__8->GetXaxis()->SetLabelFont(42);
   secondJetEta_SingleTop_wMass_emu__8->GetXaxis()->SetLabelOffset(999);
   secondJetEta_SingleTop_wMass_emu__8->GetXaxis()->SetLabelSize(0.05);
   secondJetEta_SingleTop_wMass_emu__8->GetXaxis()->SetTitleSize(0.08);
   secondJetEta_SingleTop_wMass_emu__8->GetXaxis()->SetTitleOffset(1);
   secondJetEta_SingleTop_wMass_emu__8->GetXaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_wMass_emu__8->GetYaxis()->SetTitle("Events");
   secondJetEta_SingleTop_wMass_emu__8->GetYaxis()->SetNdivisions(506);
   secondJetEta_SingleTop_wMass_emu__8->GetYaxis()->SetLabelFont(42);
   secondJetEta_SingleTop_wMass_emu__8->GetYaxis()->SetLabelOffset(0.01);
   secondJetEta_SingleTop_wMass_emu__8->GetYaxis()->SetLabelSize(0.062);
   secondJetEta_SingleTop_wMass_emu__8->GetYaxis()->SetTitleSize(0.08);
   secondJetEta_SingleTop_wMass_emu__8->GetYaxis()->SetTitleOffset(0.6336);
   secondJetEta_SingleTop_wMass_emu__8->GetYaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_wMass_emu__8->GetZaxis()->SetLabelFont(42);
   secondJetEta_SingleTop_wMass_emu__8->GetZaxis()->SetLabelOffset(0.007);
   secondJetEta_SingleTop_wMass_emu__8->GetZaxis()->SetLabelSize(0.05);
   secondJetEta_SingleTop_wMass_emu__8->GetZaxis()->SetTitleSize(0.08);
   secondJetEta_SingleTop_wMass_emu__8->GetZaxis()->SetTitleOffset(1);
   secondJetEta_SingleTop_wMass_emu__8->GetZaxis()->SetTitleFont(42);
   secondJetEta_SingleTop_wMass_emu__8->Draw("sameaxis");
   
   TPaveText *pt = new TPaveText(0.4281208,0.9347772,0.5718792,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Second Jet #eta");
   pt->Draw();
   canvy_1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: canvy_2
   TPad *canvy_2 = new TPad("canvy_2", "newpad2",0.01,0.01,0.99,0.322);
   canvy_2->Draw();
   canvy_2->cd();
   canvy_2->SetFillColor(0);
   canvy_2->SetBorderMode(0);
   canvy_2->SetGridy();

   canvy_2->SetLeftMargin( L/W );
   canvy_2->SetRightMargin( R/W );
   canvy_2->SetTopMargin( T/H );
   canvy_2->SetBottomMargin( B/H * 2.6 );
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   
   TH1D *secondJetEta_data_wMass_emu__9 = new TH1D("secondJetEta_data_wMass_emu__9","",25,0,5);
   secondJetEta_data_wMass_emu__9->SetBinContent(0,1.075383);
   secondJetEta_data_wMass_emu__9->SetBinContent(1,1.113113);
   secondJetEta_data_wMass_emu__9->SetBinContent(2,1.239239);
   secondJetEta_data_wMass_emu__9->SetBinContent(3,0.9183586);
   secondJetEta_data_wMass_emu__9->SetBinContent(4,0.8354505);
   secondJetEta_data_wMass_emu__9->SetBinContent(5,0.9706816);
   secondJetEta_data_wMass_emu__9->SetBinContent(6,1.087207);
   secondJetEta_data_wMass_emu__9->SetBinContent(7,1.100202);
   secondJetEta_data_wMass_emu__9->SetBinContent(8,0.9415288);
   secondJetEta_data_wMass_emu__9->SetBinContent(9,0.9123748);
   secondJetEta_data_wMass_emu__9->SetBinContent(10,1.534121);
   secondJetEta_data_wMass_emu__9->SetBinContent(11,0.9211386);
   secondJetEta_data_wMass_emu__9->SetBinContent(12,1.105131);
   secondJetEta_data_wMass_emu__9->SetBinContent(13,1.359315);
   secondJetEta_data_wMass_emu__9->SetBinContent(14,0.9826958);
   secondJetEta_data_wMass_emu__9->SetBinContent(15,0.7601668);
   secondJetEta_data_wMass_emu__9->SetBinContent(16,0.8311213);
   secondJetEta_data_wMass_emu__9->SetBinContent(17,0.7512394);
   secondJetEta_data_wMass_emu__9->SetBinContent(18,0.8882344);
   secondJetEta_data_wMass_emu__9->SetBinContent(19,0.7673211);
   secondJetEta_data_wMass_emu__9->SetBinContent(20,1.074048);
   secondJetEta_data_wMass_emu__9->SetBinContent(21,0.5221226);
   secondJetEta_data_wMass_emu__9->SetBinContent(22,0.7456513);
   secondJetEta_data_wMass_emu__9->SetBinError(0,0.04207096);
   secondJetEta_data_wMass_emu__9->SetBinError(1,0.1299674);
   secondJetEta_data_wMass_emu__9->SetBinError(2,0.1461479);
   secondJetEta_data_wMass_emu__9->SetBinError(3,0.1128692);
   secondJetEta_data_wMass_emu__9->SetBinError(4,0.1099358);
   secondJetEta_data_wMass_emu__9->SetBinError(5,0.1311213);
   secondJetEta_data_wMass_emu__9->SetBinError(6,0.151846);
   secondJetEta_data_wMass_emu__9->SetBinError(7,0.1594421);
   secondJetEta_data_wMass_emu__9->SetBinError(8,0.1485451);
   secondJetEta_data_wMass_emu__9->SetBinError(9,0.1541425);
   secondJetEta_data_wMass_emu__9->SetBinError(10,0.2713505);
   secondJetEta_data_wMass_emu__9->SetBinError(11,0.190326);
   secondJetEta_data_wMass_emu__9->SetBinError(12,0.2445227);
   secondJetEta_data_wMass_emu__9->SetBinError(13,0.3580748);
   secondJetEta_data_wMass_emu__9->SetBinError(14,0.2338908);
   secondJetEta_data_wMass_emu__9->SetBinError(15,0.2377112);
   secondJetEta_data_wMass_emu__9->SetBinError(16,0.3246627);
   secondJetEta_data_wMass_emu__9->SetBinError(17,0.3143773);
   secondJetEta_data_wMass_emu__9->SetBinError(18,0.3859717);
   secondJetEta_data_wMass_emu__9->SetBinError(19,0.4561943);
   secondJetEta_data_wMass_emu__9->SetBinError(20,0.6314772);
   secondJetEta_data_wMass_emu__9->SetBinError(21,0.4554936);
   secondJetEta_data_wMass_emu__9->SetBinError(22,0.6966258);
   secondJetEta_data_wMass_emu__9->SetMinimum(0.5);
   secondJetEta_data_wMass_emu__9->SetMaximum(1.5);
   secondJetEta_data_wMass_emu__9->SetEntries(204.0104);
   secondJetEta_data_wMass_emu__9->SetDirectory(0);
   secondJetEta_data_wMass_emu__9->SetStats(0);
   secondJetEta_data_wMass_emu__9->SetFillColor(1);
   secondJetEta_data_wMass_emu__9->SetLineWidth(2);
   secondJetEta_data_wMass_emu__9->SetLineColor(1); //
   secondJetEta_data_wMass_emu__9->SetMarkerStyle(20);
   secondJetEta_data_wMass_emu__9->SetMarkerSize(1.6);
   secondJetEta_data_wMass_emu__9->GetXaxis()->SetTitle("Subleading jet #eta");
   secondJetEta_data_wMass_emu__9->GetXaxis()->SetNdivisions(506);
   secondJetEta_data_wMass_emu__9->GetXaxis()->SetLabelFont(42);
   secondJetEta_data_wMass_emu__9->GetXaxis()->SetLabelOffset(0.013);
   secondJetEta_data_wMass_emu__9->GetXaxis()->SetLabelSize(0.13);
   secondJetEta_data_wMass_emu__9->GetXaxis()->SetTitleSize(0.13);
   secondJetEta_data_wMass_emu__9->GetXaxis()->SetTitleOffset(1);
   secondJetEta_data_wMass_emu__9->GetXaxis()->SetTitleFont(42);
   secondJetEta_data_wMass_emu__9->GetYaxis()->SetTitle("Data/MC");
   secondJetEta_data_wMass_emu__9->GetYaxis()->CenterTitle(true);
   secondJetEta_data_wMass_emu__9->GetYaxis()->SetNdivisions(506);
   secondJetEta_data_wMass_emu__9->GetYaxis()->SetLabelFont(42);
   secondJetEta_data_wMass_emu__9->GetYaxis()->SetLabelOffset(0.01);
   secondJetEta_data_wMass_emu__9->GetYaxis()->SetLabelSize(0.12);
   secondJetEta_data_wMass_emu__9->GetYaxis()->SetTitleSize(0.16);
   secondJetEta_data_wMass_emu__9->GetYaxis()->SetTitleOffset(0.3);
   secondJetEta_data_wMass_emu__9->GetYaxis()->SetTitleFont(42);
   secondJetEta_data_wMass_emu__9->GetZaxis()->SetLabelFont(42);
   secondJetEta_data_wMass_emu__9->GetZaxis()->SetLabelSize(0.035);
   secondJetEta_data_wMass_emu__9->GetZaxis()->SetTitleSize(0.035);
   secondJetEta_data_wMass_emu__9->GetZaxis()->SetTitleOffset(1);
   secondJetEta_data_wMass_emu__9->GetZaxis()->SetTitleFont(42);
   secondJetEta_data_wMass_emu__9->Draw("e x0, SCAT");
   canvy_2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
//   c1->SetSelected(secondJetEta_data_wMass_emu);
   c1->SaveAs("secondJetEta_wMass.pdf");
}
