void secondJetPt_SingleTop_jetSel()
{
//=========Macro generated from canvas: secondJetPt_SingleTop_jetSel/secondJetPt_SingleTop_jetSel
//=========  (Wed Aug 21 19:33:09 2019) by ROOT version 6.18/00
   // Set up cavas
   int W = 1280;
   int H = 1024;
   int H_ref = 925;
   int W_ref = 1024;

   // references for T, B, L, R
   float T = 0.08*H_ref;
   float B = 0.12*H_ref;
   float L = 0.12*W_ref;
   float R = 0.04*W_ref;

   TCanvas *c1 = new TCanvas("c1","c1",50,50,W,H);
   c1->cd();
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetLeftMargin( L/W );
   c1->SetRightMargin( R/W );
   c1->SetTopMargin( T/H );
   c1->SetBottomMargin( B/H );
   c1->SetTickx(0);
   c1->SetTicky(0);
  
// ------------>Primitives in pad: canvy_1
   TPad *canvy_1 = new TPad("canvy_1", "newpad",0.01,0.315,0.99,0.99);
   canvy_1->Draw();
   canvy_1->cd();
   canvy_1->SetFillColor(0);
   canvy_1->SetBorderMode(0);

   canvy_1->SetLeftMargin( L/W );
   canvy_1->SetRightMargin( R/W );
   canvy_1->SetTopMargin( T/H );
   canvy_1->SetBottomMargin( B/H * 0.3 );

   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);
   
   THStack *secondJetPt_SingleTop_jetSel_emu = new THStack();
   secondJetPt_SingleTop_jetSel_emu->SetName("secondJetPt_SingleTop_jetSel_emu");
   secondJetPt_SingleTop_jetSel_emu->SetTitle("Second Jet p_{T};Subleading jet p_{T} (GeV);Events");
   secondJetPt_SingleTop_jetSel_emu->SetMaximum(1024.1);
   
   TH1F *secondJetPt_SingleTop_jetSel_emu_stack_3 = new TH1F("secondJetPt_SingleTop_jetSel_emu_stack_3","Second Jet p_{T}",35,0,300);
   secondJetPt_SingleTop_jetSel_emu_stack_3->SetMinimum(0);
   secondJetPt_SingleTop_jetSel_emu_stack_3->SetMaximum(1075.305);
   secondJetPt_SingleTop_jetSel_emu_stack_3->SetDirectory(0);
   secondJetPt_SingleTop_jetSel_emu_stack_3->SetStats(0);
   secondJetPt_SingleTop_jetSel_emu_stack_3->SetLineStyle(0);
   secondJetPt_SingleTop_jetSel_emu_stack_3->SetLineWidth(0);
   secondJetPt_SingleTop_jetSel_emu_stack_3->SetMarkerStyle(20);
   secondJetPt_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetNdivisions(506);
   secondJetPt_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetLabelFont(42);
   secondJetPt_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetLabelOffset(999);
   secondJetPt_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetLabelSize(0.05);
   secondJetPt_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetTitleSize(0.08);
   secondJetPt_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   secondJetPt_SingleTop_jetSel_emu_stack_3->GetXaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetTitle("Events");
   secondJetPt_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetNdivisions(506);
   secondJetPt_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetLabelFont(42);
   secondJetPt_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetLabelOffset(0.01);
   secondJetPt_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetLabelSize(0.062);
   secondJetPt_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetTitleSize(0.08);
   secondJetPt_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetTitleOffset(0.6336);
   secondJetPt_SingleTop_jetSel_emu_stack_3->GetYaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_jetSel_emu_stack_3->GetZaxis()->SetLabelFont(42);
   secondJetPt_SingleTop_jetSel_emu_stack_3->GetZaxis()->SetLabelOffset(0.007);
   secondJetPt_SingleTop_jetSel_emu_stack_3->GetZaxis()->SetLabelSize(0.05);
   secondJetPt_SingleTop_jetSel_emu_stack_3->GetZaxis()->SetTitleSize(0.08);
   secondJetPt_SingleTop_jetSel_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   secondJetPt_SingleTop_jetSel_emu_stack_3->GetZaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_jetSel_emu->SetHistogram(secondJetPt_SingleTop_jetSel_emu_stack_3);
   
   
   TH1D *secondJetPt_tZq_jetSel_emu_stack_1 = new TH1D("secondJetPt_tZq_jetSel_emu_stack_1","secondJetPt_tZq_jetSel_emu",35,0,300);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(4,0.001673945);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(5,0.04465254);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(6,0.07915266);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(7,0.1195268);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(8,0.1591782);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(9,0.1262771);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(10,0.09673008);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(11,0.05539137);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(12,0.09315991);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(13,0.05517421);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(14,0.03880549);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(15,0.04519055);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(16,0.02970228);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(17,0.02596905);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(18,0.00925889);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(19,0.0264195);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(20,0.01254952);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(21,0.008517502);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(22,0.01454262);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(23,0.01037454);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(24,0.00526604);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(25,0.009461395);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(26,0.01045088);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(27,-0.00202116);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(28,0.003439697);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(29,0.007286427);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(30,0.002036414);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(31,0.005214768);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(32,0.006327497);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(33,0.002172421);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(34,-0.0007870381);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(35,0.003680982);
   secondJetPt_tZq_jetSel_emu_stack_1->SetBinContent(36,0.0007174509);
   secondJetPt_tZq_jetSel_emu_stack_1->SetEntries(6672);
   secondJetPt_tZq_jetSel_emu_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ffff00");
   secondJetPt_tZq_jetSel_emu_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   secondJetPt_tZq_jetSel_emu_stack_1->SetLineColor(ci);
   secondJetPt_tZq_jetSel_emu_stack_1->SetLineWidth(0);
   secondJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetLabelFont(42);
   secondJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetLabelSize(0.035);
   secondJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleSize(0.035);
   secondJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   secondJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleFont(42);
   secondJetPt_tZq_jetSel_emu_stack_1->GetYaxis()->SetLabelFont(42);
   secondJetPt_tZq_jetSel_emu_stack_1->GetYaxis()->SetLabelSize(0.035);
   secondJetPt_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleSize(0.035);
   secondJetPt_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleOffset(1);
   secondJetPt_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleFont(42);
   secondJetPt_tZq_jetSel_emu_stack_1->GetZaxis()->SetLabelFont(42);
   secondJetPt_tZq_jetSel_emu_stack_1->GetZaxis()->SetLabelSize(0.035);
   secondJetPt_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleSize(0.035);
   secondJetPt_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   secondJetPt_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_jetSel_emu->Add(secondJetPt_tZq_jetSel_emu_stack_1,"");
   
   TH1D *secondJetPt_ttV_jetSel_emu_stack_2 = new TH1D("secondJetPt_ttV_jetSel_emu_stack_2","secondJetPt_ttV_jetSel_emu",35,0,300);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(4,0.09326319);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(5,1.390475);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(6,3.602977);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(7,5.175187);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(8,5.877815);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(9,6.580465);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(10,5.748041);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(11,4.950537);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(12,3.960095);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(13,3.264467);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(14,2.08609);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(15,1.986289);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(16,1.980993);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(17,1.292372);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(18,1.290609);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(19,0.7063884);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(20,1.088182);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(21,0.5818796);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(22,0.7702889);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(23,0.905543);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(24,0.5474609);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(25,0.4108607);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(26,0.4990759);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(27,0.2117081);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(28,0.3110546);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(29,0.2332363);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(30,0.1894983);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(31,0.08427512);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(32,0.08323516);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(33,0.03281997);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(34,0.1204344);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(35,0.09867394);
   secondJetPt_ttV_jetSel_emu_stack_2->SetBinContent(36,0.3691506);
   secondJetPt_ttV_jetSel_emu_stack_2->SetEntries(29408);
   secondJetPt_ttV_jetSel_emu_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#00ff00");
   secondJetPt_ttV_jetSel_emu_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   secondJetPt_ttV_jetSel_emu_stack_2->SetLineColor(ci);
   secondJetPt_ttV_jetSel_emu_stack_2->SetLineWidth(0);
   secondJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetLabelFont(42);
   secondJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetLabelSize(0.035);
   secondJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleSize(0.035);
   secondJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   secondJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleFont(42);
   secondJetPt_ttV_jetSel_emu_stack_2->GetYaxis()->SetLabelFont(42);
   secondJetPt_ttV_jetSel_emu_stack_2->GetYaxis()->SetLabelSize(0.035);
   secondJetPt_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleSize(0.035);
   secondJetPt_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleOffset(1);
   secondJetPt_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleFont(42);
   secondJetPt_ttV_jetSel_emu_stack_2->GetZaxis()->SetLabelFont(42);
   secondJetPt_ttV_jetSel_emu_stack_2->GetZaxis()->SetLabelSize(0.035);
   secondJetPt_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleSize(0.035);
   secondJetPt_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   secondJetPt_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_jetSel_emu->Add(secondJetPt_ttV_jetSel_emu_stack_2,"");
   
   TH1D *secondJetPt_wJets_jetSel_emu_stack_3 = new TH1D("secondJetPt_wJets_jetSel_emu_stack_3","secondJetPt_wJets_jetSel_emu",35,0,300);
   secondJetPt_wJets_jetSel_emu_stack_3->SetBinContent(9,12.53387);
   secondJetPt_wJets_jetSel_emu_stack_3->SetBinContent(36,13.42844);
   secondJetPt_wJets_jetSel_emu_stack_3->SetEntries(2);
   secondJetPt_wJets_jetSel_emu_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   secondJetPt_wJets_jetSel_emu_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#cccccc");
   secondJetPt_wJets_jetSel_emu_stack_3->SetLineColor(ci);
   secondJetPt_wJets_jetSel_emu_stack_3->SetLineWidth(0);
   secondJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetLabelFont(42);
   secondJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetLabelSize(0.035);
   secondJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleSize(0.035);
   secondJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   secondJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleFont(42);
   secondJetPt_wJets_jetSel_emu_stack_3->GetYaxis()->SetLabelFont(42);
   secondJetPt_wJets_jetSel_emu_stack_3->GetYaxis()->SetLabelSize(0.035);
   secondJetPt_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleSize(0.035);
   secondJetPt_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleOffset(1);
   secondJetPt_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleFont(42);
   secondJetPt_wJets_jetSel_emu_stack_3->GetZaxis()->SetLabelFont(42);
   secondJetPt_wJets_jetSel_emu_stack_3->GetZaxis()->SetLabelSize(0.035);
   secondJetPt_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleSize(0.035);
   secondJetPt_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   secondJetPt_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_jetSel_emu->Add(secondJetPt_wJets_jetSel_emu_stack_3,"");
   
   TH1D *secondJetPt_VVV_jetSel_emu_stack_4 = new TH1D("secondJetPt_VVV_jetSel_emu_stack_4","secondJetPt_VVV_jetSel_emu",35,0,300);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(5,0.1693429);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(6,0.3703938);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(7,0.2919361);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(8,0.3009593);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(9,0.1588798);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(10,0.3525798);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(11,0.3179241);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(12,0.1167764);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(13,0.2005169);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(14,0.2150088);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(15,0.1153504);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(16,0.0733528);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(17,0.1997021);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(18,0.1191762);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(19,0.06765218);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(20,0.09421561);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(21,0.007982881);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(22,0.0700349);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(23,0.05630057);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(24,0.03648083);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(26,0.05103436);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(28,0.0378832);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(31,0.04299621);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(32,0.009105003);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(35,0.02816807);
   secondJetPt_VVV_jetSel_emu_stack_4->SetBinContent(36,0.1805987);
   secondJetPt_VVV_jetSel_emu_stack_4->SetEntries(147);
   secondJetPt_VVV_jetSel_emu_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#00ffff");
   secondJetPt_VVV_jetSel_emu_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   secondJetPt_VVV_jetSel_emu_stack_4->SetLineColor(ci);
   secondJetPt_VVV_jetSel_emu_stack_4->SetLineWidth(0);
   secondJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetLabelFont(42);
   secondJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetLabelSize(0.035);
   secondJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleSize(0.035);
   secondJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   secondJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleFont(42);
   secondJetPt_VVV_jetSel_emu_stack_4->GetYaxis()->SetLabelFont(42);
   secondJetPt_VVV_jetSel_emu_stack_4->GetYaxis()->SetLabelSize(0.035);
   secondJetPt_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleSize(0.035);
   secondJetPt_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleOffset(1);
   secondJetPt_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleFont(42);
   secondJetPt_VVV_jetSel_emu_stack_4->GetZaxis()->SetLabelFont(42);
   secondJetPt_VVV_jetSel_emu_stack_4->GetZaxis()->SetLabelSize(0.035);
   secondJetPt_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleSize(0.035);
   secondJetPt_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   secondJetPt_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_jetSel_emu->Add(secondJetPt_VVV_jetSel_emu_stack_4,"");
   
   TH1D *secondJetPt_VV_jetSel_emu_stack_5 = new TH1D("secondJetPt_VV_jetSel_emu_stack_5","secondJetPt_VV_jetSel_emu",35,0,300);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(4,0.3444787);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(5,4.280298);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(6,6.527228);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(7,8.061283);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(8,6.56929);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(9,5.820222);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(10,4.049302);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(11,3.873226);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(12,3.478364);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(13,1.921012);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(14,1.193194);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(15,2.497962);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(16,1.724906);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(17,0.6037417);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(18,1.668028);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(19,0.9096256);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(20,1.389215);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(21,0.6032626);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(22,0.4031222);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(23,1.108906);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(24,0.1723369);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(25,0.377244);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(26,0.3588366);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(27,0.1633625);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(28,0.1724581);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(29,0.00637404);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(30,0.2801856);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(31,0.1617315);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(32,0.2523691);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(33,0.2346409);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(35,0.1859401);
   secondJetPt_VV_jetSel_emu_stack_5->SetBinContent(36,1.58034);
   secondJetPt_VV_jetSel_emu_stack_5->SetEntries(858);
   secondJetPt_VV_jetSel_emu_stack_5->SetDirectory(0);

   ci = TColor::GetColor("#ff9933");
   secondJetPt_VV_jetSel_emu_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#ff9933");
   secondJetPt_VV_jetSel_emu_stack_5->SetLineColor(ci);
   secondJetPt_VV_jetSel_emu_stack_5->SetLineWidth(0);
   secondJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetLabelFont(42);
   secondJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetLabelSize(0.035);
   secondJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleSize(0.035);
   secondJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleOffset(1);
   secondJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleFont(42);
   secondJetPt_VV_jetSel_emu_stack_5->GetYaxis()->SetLabelFont(42);
   secondJetPt_VV_jetSel_emu_stack_5->GetYaxis()->SetLabelSize(0.035);
   secondJetPt_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleSize(0.035);
   secondJetPt_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleOffset(1);
   secondJetPt_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleFont(42);
   secondJetPt_VV_jetSel_emu_stack_5->GetZaxis()->SetLabelFont(42);
   secondJetPt_VV_jetSel_emu_stack_5->GetZaxis()->SetLabelSize(0.035);
   secondJetPt_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleSize(0.035);
   secondJetPt_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleOffset(1);
   secondJetPt_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_jetSel_emu->Add(secondJetPt_VV_jetSel_emu_stack_5,"");
   
   TH1D *secondJetPt_SingleTop_jetSel_emu_stack_6 = new TH1D("secondJetPt_SingleTop_jetSel_emu_stack_6","secondJetPt_SingleTop_jetSel_emu",35,0,300);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(4,1.29206);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(5,21.5192);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(6,35.54771);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(7,37.3025);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(8,29.10431);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(9,26.35709);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(10,22.69524);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(11,19.36597);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(12,15.63247);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(13,12.82281);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(14,9.002394);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(15,7.23929);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(16,6.433252);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(17,5.126713);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(18,5.128733);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(19,3.292072);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(20,3.725339);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(21,1.761412);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(22,2.985767);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(23,2.082121);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(24,1.852379);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(25,0.9676255);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(26,1.287377);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(27,0.8412541);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(28,0.9579948);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(29,0.826435);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(30,0.9333613);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(31,0.4364386);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(32,0.5844366);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(33,0.5376668);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(34,0.1783134);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(35,0.2141676);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(36,2.18698);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetEntries(2806);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetDirectory(0);

   ci = TColor::GetColor("#ff00ff");
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetLineColor(ci);
   secondJetPt_SingleTop_jetSel_emu_stack_6->SetLineWidth(0);
   secondJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetLabelFont(42);
   secondJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetLabelSize(0.035);
   secondJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleSize(0.035);
   secondJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleOffset(1);
   secondJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetLabelFont(42);
   secondJetPt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetLabelSize(0.035);
   secondJetPt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleSize(0.035);
   secondJetPt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleOffset(1);
   secondJetPt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetLabelFont(42);
   secondJetPt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetLabelSize(0.035);
   secondJetPt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleSize(0.035);
   secondJetPt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleOffset(1);
   secondJetPt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_jetSel_emu->Add(secondJetPt_SingleTop_jetSel_emu_stack_6,"");
   
   TH1D *secondJetPt_tt_jetSel_emu_stack_7 = new TH1D("secondJetPt_tt_jetSel_emu_stack_7","secondJetPt_tt_jetSel_emu",35,0,300);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(4,24.97731);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(5,329.7571);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(6,669.2887);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(7,778.988);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(8,779.7143);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(9,692.4251);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(10,581.2136);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(11,452.4169);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(12,394.5209);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(13,311.2283);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(14,247.3622);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(15,192.574);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(16,141.6086);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(17,117.1632);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(18,90.85242);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(19,83.38355);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(20,66.54117);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(21,46.36953);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(22,38.15799);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(23,31.75545);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(24,24.1141);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(25,23.18505);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(26,22.34744);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(27,17.27094);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(28,12.0151);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(29,9.358904);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(30,7.830327);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(31,7.856757);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(32,7.805182);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(33,5.806862);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(34,2.604412);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(35,3.963403);
   secondJetPt_tt_jetSel_emu_stack_7->SetBinContent(36,24.06124);
   secondJetPt_tt_jetSel_emu_stack_7->SetEntries(19867);
   secondJetPt_tt_jetSel_emu_stack_7->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   secondJetPt_tt_jetSel_emu_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   secondJetPt_tt_jetSel_emu_stack_7->SetLineColor(ci);
   secondJetPt_tt_jetSel_emu_stack_7->SetLineWidth(0);
   secondJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetLabelFont(42);
   secondJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetLabelSize(0.035);
   secondJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleSize(0.035);
   secondJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleOffset(1);
   secondJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleFont(42);
   secondJetPt_tt_jetSel_emu_stack_7->GetYaxis()->SetLabelFont(42);
   secondJetPt_tt_jetSel_emu_stack_7->GetYaxis()->SetLabelSize(0.035);
   secondJetPt_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleSize(0.035);
   secondJetPt_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleOffset(1);
   secondJetPt_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleFont(42);
   secondJetPt_tt_jetSel_emu_stack_7->GetZaxis()->SetLabelFont(42);
   secondJetPt_tt_jetSel_emu_stack_7->GetZaxis()->SetLabelSize(0.035);
   secondJetPt_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleSize(0.035);
   secondJetPt_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleOffset(1);
   secondJetPt_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_jetSel_emu->Add(secondJetPt_tt_jetSel_emu_stack_7,"");
   
   TH1D *secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8 = new TH1D("secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8","secondJetPt_zPlusJetsMadgraph_jetSel_emu",35,0,300);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(5,1.549233);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(6,1.438892);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(7,5.94588);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(8,2.860104);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(10,1.443027);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(12,2.932198);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(15,1.500954);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetEntries(12);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetLineColor(ci);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetLineWidth(0);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetLabelFont(42);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetLabelSize(0.035);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleSize(0.035);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleOffset(1);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleFont(42);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetLabelFont(42);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetLabelSize(0.035);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleSize(0.035);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleOffset(1);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleFont(42);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetLabelFont(42);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetLabelSize(0.035);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleSize(0.035);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleOffset(1);
   secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_jetSel_emu->Add(secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8,"");
   secondJetPt_SingleTop_jetSel_emu->Draw("");
   
   TH1D *secondJetPt_data_jetSel_emu__7 = new TH1D("secondJetPt_data_jetSel_emu__7","secondJetPt_data_jetSel_emu",35,0,300);
   secondJetPt_data_jetSel_emu__7->SetBinContent(4,23);
   secondJetPt_data_jetSel_emu__7->SetBinContent(5,373);
   secondJetPt_data_jetSel_emu__7->SetBinContent(6,705);
   secondJetPt_data_jetSel_emu__7->SetBinContent(7,931);
   secondJetPt_data_jetSel_emu__7->SetBinContent(8,799);
   secondJetPt_data_jetSel_emu__7->SetBinContent(9,765);
   secondJetPt_data_jetSel_emu__7->SetBinContent(10,602);
   secondJetPt_data_jetSel_emu__7->SetBinContent(11,513);
   secondJetPt_data_jetSel_emu__7->SetBinContent(12,424);
   secondJetPt_data_jetSel_emu__7->SetBinContent(13,309);
   secondJetPt_data_jetSel_emu__7->SetBinContent(14,241);
   secondJetPt_data_jetSel_emu__7->SetBinContent(15,181);
   secondJetPt_data_jetSel_emu__7->SetBinContent(16,154);
   secondJetPt_data_jetSel_emu__7->SetBinContent(17,122);
   secondJetPt_data_jetSel_emu__7->SetBinContent(18,110);
   secondJetPt_data_jetSel_emu__7->SetBinContent(19,69);
   secondJetPt_data_jetSel_emu__7->SetBinContent(20,68);
   secondJetPt_data_jetSel_emu__7->SetBinContent(21,59);
   secondJetPt_data_jetSel_emu__7->SetBinContent(22,49);
   secondJetPt_data_jetSel_emu__7->SetBinContent(23,27);
   secondJetPt_data_jetSel_emu__7->SetBinContent(24,28);
   secondJetPt_data_jetSel_emu__7->SetBinContent(25,14);
   secondJetPt_data_jetSel_emu__7->SetBinContent(26,12);
   secondJetPt_data_jetSel_emu__7->SetBinContent(27,12);
   secondJetPt_data_jetSel_emu__7->SetBinContent(28,13);
   secondJetPt_data_jetSel_emu__7->SetBinContent(29,5);
   secondJetPt_data_jetSel_emu__7->SetBinContent(30,8);
   secondJetPt_data_jetSel_emu__7->SetBinContent(31,8);
   secondJetPt_data_jetSel_emu__7->SetBinContent(32,10);
   secondJetPt_data_jetSel_emu__7->SetBinContent(33,6);
   secondJetPt_data_jetSel_emu__7->SetBinContent(34,4);
   secondJetPt_data_jetSel_emu__7->SetBinContent(35,4);
   secondJetPt_data_jetSel_emu__7->SetBinContent(36,20);
   secondJetPt_data_jetSel_emu__7->SetEntries(6668);
   secondJetPt_data_jetSel_emu__7->SetDirectory(0);
   secondJetPt_data_jetSel_emu__7->SetFillColor(1);
   secondJetPt_data_jetSel_emu__7->SetLineWidth(2);
   secondJetPt_data_jetSel_emu__7->SetLineColor(1); //
   secondJetPt_data_jetSel_emu__7->SetMarkerStyle(20);
   secondJetPt_data_jetSel_emu__7->SetMarkerSize(1.4);
   secondJetPt_data_jetSel_emu__7->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_data_jetSel_emu__7->GetXaxis()->SetLabelFont(42);
   secondJetPt_data_jetSel_emu__7->GetXaxis()->SetLabelSize(0.035);
   secondJetPt_data_jetSel_emu__7->GetXaxis()->SetTitleSize(0.035);
   secondJetPt_data_jetSel_emu__7->GetXaxis()->SetTitleOffset(1);
   secondJetPt_data_jetSel_emu__7->GetXaxis()->SetTitleFont(42);
   secondJetPt_data_jetSel_emu__7->GetYaxis()->SetLabelFont(42);
   secondJetPt_data_jetSel_emu__7->GetYaxis()->SetLabelSize(0.035);
   secondJetPt_data_jetSel_emu__7->GetYaxis()->SetTitleSize(0.035);
   secondJetPt_data_jetSel_emu__7->GetYaxis()->SetTitleOffset(1);
   secondJetPt_data_jetSel_emu__7->GetYaxis()->SetTitleFont(42);
   secondJetPt_data_jetSel_emu__7->GetZaxis()->SetLabelFont(42);
   secondJetPt_data_jetSel_emu__7->GetZaxis()->SetLabelSize(0.035);
   secondJetPt_data_jetSel_emu__7->GetZaxis()->SetTitleSize(0.035);
   secondJetPt_data_jetSel_emu__7->GetZaxis()->SetTitleOffset(1);
   secondJetPt_data_jetSel_emu__7->GetZaxis()->SetTitleFont(42);
   secondJetPt_data_jetSel_emu__7->Draw("e x0, same");
   
   TLegend *leg = new TLegend(0.78,0.42,0.98,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("secondJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8","Z+jets (LO)","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetPt_tt_jetSel_emu_stack_7","t#bar{t}","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetPt_SingleTop_jetSel_emu_stack_6","Single top","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetPt_VV_jetSel_emu_stack_5","VV","f");

   ci = TColor::GetColor("#ff9933");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetPt_VVV_jetSel_emu_stack_4","VVV","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetPt_wJets_jetSel_emu_stack_3","W+jets","f");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetPt_ttV_jetSel_emu_stack_2","t#bar{t}V","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetPt_tZq_jetSel_emu_stack_1","tZq","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("secondJetPt_data_jetSel_emu","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.4);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.968,0.9429101,"35.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06792969);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.096,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.05419922);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16899,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.04119141);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *secondJetPt_SingleTop_jetSel_emu__8 = new TH1F("secondJetPt_SingleTop_jetSel_emu__8","Second Jet p_{T}",35,0,300);
   secondJetPt_SingleTop_jetSel_emu__8->SetMinimum(0);
   secondJetPt_SingleTop_jetSel_emu__8->SetMaximum(1075.305);
   secondJetPt_SingleTop_jetSel_emu__8->SetDirectory(0);
   secondJetPt_SingleTop_jetSel_emu__8->SetStats(0);
   secondJetPt_SingleTop_jetSel_emu__8->SetLineStyle(0);
   secondJetPt_SingleTop_jetSel_emu__8->SetLineWidth(0);
   secondJetPt_SingleTop_jetSel_emu__8->SetMarkerStyle(20);
   secondJetPt_SingleTop_jetSel_emu__8->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_SingleTop_jetSel_emu__8->GetXaxis()->SetNdivisions(506);
   secondJetPt_SingleTop_jetSel_emu__8->GetXaxis()->SetLabelFont(42);
   secondJetPt_SingleTop_jetSel_emu__8->GetXaxis()->SetLabelOffset(999);
   secondJetPt_SingleTop_jetSel_emu__8->GetXaxis()->SetLabelSize(0.05);
   secondJetPt_SingleTop_jetSel_emu__8->GetXaxis()->SetTitleSize(0.08);
   secondJetPt_SingleTop_jetSel_emu__8->GetXaxis()->SetTitleOffset(1);
   secondJetPt_SingleTop_jetSel_emu__8->GetXaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_jetSel_emu__8->GetYaxis()->SetTitle("Events");
   secondJetPt_SingleTop_jetSel_emu__8->GetYaxis()->SetNdivisions(506);
   secondJetPt_SingleTop_jetSel_emu__8->GetYaxis()->SetLabelFont(42);
   secondJetPt_SingleTop_jetSel_emu__8->GetYaxis()->SetLabelOffset(0.01);
   secondJetPt_SingleTop_jetSel_emu__8->GetYaxis()->SetLabelSize(0.062);
   secondJetPt_SingleTop_jetSel_emu__8->GetYaxis()->SetTitleSize(0.08);
   secondJetPt_SingleTop_jetSel_emu__8->GetYaxis()->SetTitleOffset(0.6336);
   secondJetPt_SingleTop_jetSel_emu__8->GetYaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_jetSel_emu__8->GetZaxis()->SetLabelFont(42);
   secondJetPt_SingleTop_jetSel_emu__8->GetZaxis()->SetLabelOffset(0.007);
   secondJetPt_SingleTop_jetSel_emu__8->GetZaxis()->SetLabelSize(0.05);
   secondJetPt_SingleTop_jetSel_emu__8->GetZaxis()->SetTitleSize(0.08);
   secondJetPt_SingleTop_jetSel_emu__8->GetZaxis()->SetTitleOffset(1);
   secondJetPt_SingleTop_jetSel_emu__8->GetZaxis()->SetTitleFont(42);
   secondJetPt_SingleTop_jetSel_emu__8->Draw("sameaxis");
   
   TPaveText *pt = new TPaveText(0.4241286,0.9203237,0.5758714,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Second Jet p_{T}");
   pt->Draw();
   canvy_1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: canvy_2
   TPad *canvy_2 = new TPad("canvy_2", "newpad2",0.01,0.01,0.99,0.322);
   canvy_2->Draw();
   canvy_2->cd();
   canvy_2->SetFillColor(0);
   canvy_2->SetBorderMode(0);
   canvy_2->SetGridy();

   canvy_2->SetLeftMargin( L/W );
   canvy_2->SetRightMargin( R/W );
   canvy_2->SetTopMargin( T/H );
   canvy_2->SetBottomMargin( B/H * 2.6 );
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   
   TH1D *secondJetPt_data_jetSel_emu__9 = new TH1D("secondJetPt_data_jetSel_emu__9","",35,0,300);
   secondJetPt_data_jetSel_emu__9->SetBinContent(4,0.86114);
   secondJetPt_data_jetSel_emu__9->SetBinContent(5,1.039836);
   secondJetPt_data_jetSel_emu__9->SetBinContent(6,0.9834623);
   secondJetPt_data_jetSel_emu__9->SetBinContent(7,1.113791);
   secondJetPt_data_jetSel_emu__9->SetBinContent(8,0.9689712);
   secondJetPt_data_jetSel_emu__9->SetBinContent(9,1.028223);
   secondJetPt_data_jetSel_emu__9->SetBinContent(10,0.97791);
   secondJetPt_data_jetSel_emu__9->SetBinContent(11,1.066573);
   secondJetPt_data_jetSel_emu__9->SetBinContent(12,1.007763);
   secondJetPt_data_jetSel_emu__9->SetBinContent(13,0.9378065);
   secondJetPt_data_jetSel_emu__9->SetBinContent(14,0.9272879);
   secondJetPt_data_jetSel_emu__9->SetBinContent(15,0.8788156);
   secondJetPt_data_jetSel_emu__9->SetBinContent(16,1.014153);
   secondJetPt_data_jetSel_emu__9->SetBinContent(17,0.9806152);
   secondJetPt_data_jetSel_emu__9->SetBinContent(18,1.110346);
   secondJetPt_data_jetSel_emu__9->SetBinContent(19,0.7806692);
   secondJetPt_data_jetSel_emu__9->SetBinContent(20,0.9334163);
   secondJetPt_data_jetSel_emu__9->SetBinContent(21,1.195964);
   secondJetPt_data_jetSel_emu__9->SetBinContent(22,1.155613);
   secondJetPt_data_jetSel_emu__9->SetBinContent(23,0.7516977);
   secondJetPt_data_jetSel_emu__9->SetBinContent(24,1.04759);
   secondJetPt_data_jetSel_emu__9->SetBinContent(25,0.5611168);
   secondJetPt_data_jetSel_emu__9->SetBinContent(26,0.4887144);
   secondJetPt_data_jetSel_emu__9->SetBinContent(27,0.6491666);
   secondJetPt_data_jetSel_emu__9->SetBinContent(28,0.9631107);
   secondJetPt_data_jetSel_emu__9->SetBinContent(29,0.4792837);
   secondJetPt_data_jetSel_emu__9->SetBinContent(30,0.8662313);
   secondJetPt_data_jetSel_emu__9->SetBinContent(31,0.931596);
   secondJetPt_data_jetSel_emu__9->SetBinContent(32,1.144079);
   secondJetPt_data_jetSel_emu__9->SetBinContent(33,0.9071444);
   secondJetPt_data_jetSel_emu__9->SetBinContent(34,1.378183);
   secondJetPt_data_jetSel_emu__9->SetBinContent(35,0.890069);
   secondJetPt_data_jetSel_emu__9->SetBinContent(36,0.4783834);
   secondJetPt_data_jetSel_emu__9->SetBinError(4,0.2449624);
   secondJetPt_data_jetSel_emu__9->SetBinError(5,0.07689678);
   secondJetPt_data_jetSel_emu__9->SetBinError(6,0.05216451);
   secondJetPt_data_jetSel_emu__9->SetBinError(7,0.05307129);
   secondJetPt_data_jetSel_emu__9->SetBinError(8,0.04810134);
   secondJetPt_data_jetSel_emu__9->SetBinError(9,0.05294373);
   secondJetPt_data_jetSel_emu__9->SetBinError(10,0.05605365);
   secondJetPt_data_jetSel_emu__9->SetBinError(11,0.06769507);
   secondJetPt_data_jetSel_emu__9->SetBinError(12,0.06934762);
   secondJetPt_data_jetSel_emu__9->SetBinError(13,0.07426586);
   secondJetPt_data_jetSel_emu__9->SetBinError(14,0.08292384);
   secondJetPt_data_jetSel_emu__9->SetBinError(15,0.08953659);
   secondJetPt_data_jetSel_emu__9->SetBinError(16,0.1159817);
   secondJetPt_data_jetSel_emu__9->SetBinError(17,0.124945);
   secondJetPt_data_jetSel_emu__9->SetBinError(18,0.1537938);
   secondJetPt_data_jetSel_emu__9->SetBinError(19,0.1254106);
   secondJetPt_data_jetSel_emu__9->SetBinError(20,0.1573923);
   secondJetPt_data_jetSel_emu__9->SetBinError(21,0.2307303);
   secondJetPt_data_jetSel_emu__9->SetBinError(22,0.2423816);
   secondJetPt_data_jetSel_emu__9->SetBinError(23,0.1914657);
   secondJetPt_data_jetSel_emu__9->SetBinError(24,0.2832916);
   secondJetPt_data_jetSel_emu__9->SetBinError(25,0.187373);
   secondJetPt_data_jetSel_emu__9->SetBinError(26,0.1721354);
   secondJetPt_data_jetSel_emu__9->SetBinError(27,0.2406566);
   secondJetPt_data_jetSel_emu__9->SetBinError(28,0.374263);
   secondJetPt_data_jetSel_emu__9->SetBinError(29,0.2606954);
   secondJetPt_data_jetSel_emu__9->SetBinError(30,0.4183807);
   secondJetPt_data_jetSel_emu__9->SetBinError(31,0.4577631);
   secondJetPt_data_jetSel_emu__9->SetBinError(32,0.5297566);
   secondJetPt_data_jetSel_emu__9->SetBinError(33,0.5114375);
   secondJetPt_data_jetSel_emu__9->SetBinError(34,1.062672);
   secondJetPt_data_jetSel_emu__9->SetBinError(35,0.6118325);
   secondJetPt_data_jetSel_emu__9->SetBinError(36,0.1300633);
   secondJetPt_data_jetSel_emu__9->SetMinimum(0.5);
   secondJetPt_data_jetSel_emu__9->SetMaximum(1.5);
   secondJetPt_data_jetSel_emu__9->SetEntries(282.2726);
   secondJetPt_data_jetSel_emu__9->SetDirectory(0);
   secondJetPt_data_jetSel_emu__9->SetStats(0);
   secondJetPt_data_jetSel_emu__9->SetFillColor(1);
   secondJetPt_data_jetSel_emu__9->SetLineWidth(2);
   secondJetPt_data_jetSel_emu__9->SetLineColor(1); //
   secondJetPt_data_jetSel_emu__9->SetMarkerStyle(20);
   secondJetPt_data_jetSel_emu__9->SetMarkerSize(1.6);
   secondJetPt_data_jetSel_emu__9->GetXaxis()->SetTitle("Subleading jet p_{T} (GeV)");
   secondJetPt_data_jetSel_emu__9->GetXaxis()->SetNdivisions(506);
   secondJetPt_data_jetSel_emu__9->GetXaxis()->SetLabelFont(42);
   secondJetPt_data_jetSel_emu__9->GetXaxis()->SetLabelOffset(0.013);
   secondJetPt_data_jetSel_emu__9->GetXaxis()->SetLabelSize(0.13);
   secondJetPt_data_jetSel_emu__9->GetXaxis()->SetTitleSize(0.13);
   secondJetPt_data_jetSel_emu__9->GetXaxis()->SetTitleOffset(1);
   secondJetPt_data_jetSel_emu__9->GetXaxis()->SetTitleFont(42);
   secondJetPt_data_jetSel_emu__9->GetYaxis()->SetTitle("Data/MC");
   secondJetPt_data_jetSel_emu__9->GetYaxis()->CenterTitle(true);
   secondJetPt_data_jetSel_emu__9->GetYaxis()->SetNdivisions(506);
   secondJetPt_data_jetSel_emu__9->GetYaxis()->SetLabelFont(42);
   secondJetPt_data_jetSel_emu__9->GetYaxis()->SetLabelOffset(0.01);
   secondJetPt_data_jetSel_emu__9->GetYaxis()->SetLabelSize(0.12);
   secondJetPt_data_jetSel_emu__9->GetYaxis()->SetTitleSize(0.16);
   secondJetPt_data_jetSel_emu__9->GetYaxis()->SetTitleOffset(0.3);
   secondJetPt_data_jetSel_emu__9->GetYaxis()->SetTitleFont(42);
   secondJetPt_data_jetSel_emu__9->GetZaxis()->SetLabelFont(42);
   secondJetPt_data_jetSel_emu__9->GetZaxis()->SetLabelSize(0.035);
   secondJetPt_data_jetSel_emu__9->GetZaxis()->SetTitleSize(0.035);
   secondJetPt_data_jetSel_emu__9->GetZaxis()->SetTitleOffset(1);
   secondJetPt_data_jetSel_emu__9->GetZaxis()->SetTitleFont(42);
   secondJetPt_data_jetSel_emu__9->Draw("e x0, SCAT");
   canvy_2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
//   c1->SetSelected(secondJetPt_data_jetSel_emu);
   c1->SaveAs("secondJetPt_jetSel.pdf");
}
