void thirdJetPt_SingleTop_wMass()
{
//=========Macro generated from canvas: thirdJetPt_SingleTop_wMass/thirdJetPt_SingleTop_wMass
//=========  (Wed Aug 21 19:38:57 2019) by ROOT version 6.18/00

   // Set up cavas
   int W = 1280;
   int H = 1024;
   int H_ref = 925;
   int W_ref = 1024;

   // references for T, B, L, R
   float T = 0.08*H_ref;
   float B = 0.12*H_ref;
   float L = 0.12*W_ref;
   float R = 0.04*W_ref;

   TCanvas *c1 = new TCanvas("c1","c1",50,50,W,H);
   c1->cd();
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetLeftMargin( L/W );
   c1->SetRightMargin( R/W );
   c1->SetTopMargin( T/H );
   c1->SetBottomMargin( B/H );
   c1->SetTickx(0);
   c1->SetTicky(0);
  
// ------------>Primitives in pad: canvy_1
   TPad *canvy_1 = new TPad("canvy_1", "newpad",0.01,0.315,0.99,0.99);
   canvy_1->Draw();
   canvy_1->cd();
   canvy_1->SetFillColor(0);
   canvy_1->SetBorderMode(0);

   canvy_1->SetLeftMargin( L/W );
   canvy_1->SetRightMargin( R/W );
   canvy_1->SetTopMargin( T/H );
   canvy_1->SetBottomMargin( B/H * 0.3 );

   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);

   THStack *thirdJetPt_SingleTop_wMass_emu = new THStack();
   thirdJetPt_SingleTop_wMass_emu->SetName("thirdJetPt_SingleTop_wMass_emu");
   thirdJetPt_SingleTop_wMass_emu->SetTitle(";Third jet p_{T} (GeV);Events");
   thirdJetPt_SingleTop_wMass_emu->SetMaximum(712.8);
   
   TH1F *thirdJetPt_SingleTop_wMass_emu_stack_4 = new TH1F("thirdJetPt_SingleTop_wMass_emu_stack_4","Third Jet p_{T}",35,0,300);
   thirdJetPt_SingleTop_wMass_emu_stack_4->SetMinimum(-0.00135082);
   thirdJetPt_SingleTop_wMass_emu_stack_4->SetMaximum(748.44);
   thirdJetPt_SingleTop_wMass_emu_stack_4->SetDirectory(0);
   thirdJetPt_SingleTop_wMass_emu_stack_4->SetStats(0);
   thirdJetPt_SingleTop_wMass_emu_stack_4->SetLineStyle(0);
   thirdJetPt_SingleTop_wMass_emu_stack_4->SetLineWidth(0);
   thirdJetPt_SingleTop_wMass_emu_stack_4->SetMarkerStyle(20);
   thirdJetPt_SingleTop_wMass_emu_stack_4->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_SingleTop_wMass_emu_stack_4->GetXaxis()->SetNdivisions(506);
   thirdJetPt_SingleTop_wMass_emu_stack_4->GetXaxis()->SetLabelFont(42);
   thirdJetPt_SingleTop_wMass_emu_stack_4->GetXaxis()->SetLabelOffset(999);
   thirdJetPt_SingleTop_wMass_emu_stack_4->GetXaxis()->SetLabelSize(0.05);
   thirdJetPt_SingleTop_wMass_emu_stack_4->GetXaxis()->SetTitleSize(0.08);
   thirdJetPt_SingleTop_wMass_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_SingleTop_wMass_emu_stack_4->GetXaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_wMass_emu_stack_4->GetYaxis()->SetTitle("Events");
   thirdJetPt_SingleTop_wMass_emu_stack_4->GetYaxis()->SetNdivisions(506);
   thirdJetPt_SingleTop_wMass_emu_stack_4->GetYaxis()->SetLabelFont(42);
   thirdJetPt_SingleTop_wMass_emu_stack_4->GetYaxis()->SetLabelOffset(0.01);
   thirdJetPt_SingleTop_wMass_emu_stack_4->GetYaxis()->SetLabelSize(0.062);
   thirdJetPt_SingleTop_wMass_emu_stack_4->GetYaxis()->SetTitleSize(0.08);
   thirdJetPt_SingleTop_wMass_emu_stack_4->GetYaxis()->SetTitleOffset(0.6336);
   thirdJetPt_SingleTop_wMass_emu_stack_4->GetYaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_wMass_emu_stack_4->GetZaxis()->SetLabelFont(42);
   thirdJetPt_SingleTop_wMass_emu_stack_4->GetZaxis()->SetLabelOffset(0.007);
   thirdJetPt_SingleTop_wMass_emu_stack_4->GetZaxis()->SetLabelSize(0.05);
   thirdJetPt_SingleTop_wMass_emu_stack_4->GetZaxis()->SetTitleSize(0.08);
   thirdJetPt_SingleTop_wMass_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_SingleTop_wMass_emu_stack_4->GetZaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_wMass_emu->SetHistogram(thirdJetPt_SingleTop_wMass_emu_stack_4);
   
   
   TH1D *thirdJetPt_tZq_wMass_emu_stack_1 = new TH1D("thirdJetPt_tZq_wMass_emu_stack_1","thirdJetPt_tZq_wMass_emu",35,0,300);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(4,0.01201098);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(5,0.0584745);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(6,0.07209694);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(7,0.05056354);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(8,0.04430466);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(9,0.02270177);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(10,0.02371089);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(11,0.01028026);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(12,0.01366006);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(13,0.008663798);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(14,0.009324195);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(15,0.001614776);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(16,0.009590456);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(17,0.002171421);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(18,1.739265e-05);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(19,0.002325016);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(20,0.002172079);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(21,-0.001136212);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(22,0.0006807222);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(23,0.0007058487);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(24,-0.0006730286);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(25,0.0007856049);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(28,-0.0003939803);
   thirdJetPt_tZq_wMass_emu_stack_1->SetBinContent(36,0.0007567225);
   thirdJetPt_tZq_wMass_emu_stack_1->SetEntries(2170);
   thirdJetPt_tZq_wMass_emu_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ffff00");
   thirdJetPt_tZq_wMass_emu_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   thirdJetPt_tZq_wMass_emu_stack_1->SetLineColor(ci);
   thirdJetPt_tZq_wMass_emu_stack_1->SetLineWidth(0);
   thirdJetPt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_tZq_wMass_emu_stack_1->GetXaxis()->SetLabelFont(42);
   thirdJetPt_tZq_wMass_emu_stack_1->GetXaxis()->SetLabelSize(0.035);
   thirdJetPt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleSize(0.035);
   thirdJetPt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleFont(42);
   thirdJetPt_tZq_wMass_emu_stack_1->GetYaxis()->SetLabelFont(42);
   thirdJetPt_tZq_wMass_emu_stack_1->GetYaxis()->SetLabelSize(0.035);
   thirdJetPt_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleSize(0.035);
   thirdJetPt_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleOffset(1);
   thirdJetPt_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleFont(42);
   thirdJetPt_tZq_wMass_emu_stack_1->GetZaxis()->SetLabelFont(42);
   thirdJetPt_tZq_wMass_emu_stack_1->GetZaxis()->SetLabelSize(0.035);
   thirdJetPt_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleSize(0.035);
   thirdJetPt_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_wMass_emu->Add(thirdJetPt_tZq_wMass_emu_stack_1,"");
   
   TH1D *thirdJetPt_ttV_wMass_emu_stack_2 = new TH1D("thirdJetPt_ttV_wMass_emu_stack_2","thirdJetPt_ttV_wMass_emu",35,0,300);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(4,0.5748348);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(5,3.745115);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(6,5.079955);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(7,5.220342);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(8,3.364867);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(9,2.827378);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(10,1.984688);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(11,1.291517);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(12,0.8148004);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(13,0.9045226);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(14,0.6855303);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(15,0.2744604);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(16,0.5000083);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(17,0.1732669);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(18,0.2179654);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(19,0.05396162);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(20,0.04803754);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(21,-0.01170027);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(22,0.0710817);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(23,0.04918649);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(24,0.03525574);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(25,-0.0006723035);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(26,0.007632898);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(27,0.001182497);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(28,-0.001514284);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(29,0.009465271);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(31,0.002078651);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(32,-0.00135082);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(33,0.0001791029);
   thirdJetPt_ttV_wMass_emu_stack_2->SetBinContent(36,-0.0429044);
   thirdJetPt_ttV_wMass_emu_stack_2->SetEntries(14144);
   thirdJetPt_ttV_wMass_emu_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#00ff00");
   thirdJetPt_ttV_wMass_emu_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   thirdJetPt_ttV_wMass_emu_stack_2->SetLineColor(ci);
   thirdJetPt_ttV_wMass_emu_stack_2->SetLineWidth(0);
   thirdJetPt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_ttV_wMass_emu_stack_2->GetXaxis()->SetLabelFont(42);
   thirdJetPt_ttV_wMass_emu_stack_2->GetXaxis()->SetLabelSize(0.035);
   thirdJetPt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleSize(0.035);
   thirdJetPt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleFont(42);
   thirdJetPt_ttV_wMass_emu_stack_2->GetYaxis()->SetLabelFont(42);
   thirdJetPt_ttV_wMass_emu_stack_2->GetYaxis()->SetLabelSize(0.035);
   thirdJetPt_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleSize(0.035);
   thirdJetPt_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleOffset(1);
   thirdJetPt_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleFont(42);
   thirdJetPt_ttV_wMass_emu_stack_2->GetZaxis()->SetLabelFont(42);
   thirdJetPt_ttV_wMass_emu_stack_2->GetZaxis()->SetLabelSize(0.035);
   thirdJetPt_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleSize(0.035);
   thirdJetPt_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_wMass_emu->Add(thirdJetPt_ttV_wMass_emu_stack_2,"");
   
   TH1D *thirdJetPt_wJets_wMass_emu_stack_3 = new TH1D("thirdJetPt_wJets_wMass_emu_stack_3","thirdJetPt_wJets_wMass_emu",35,0,300);
   thirdJetPt_wJets_wMass_emu_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   thirdJetPt_wJets_wMass_emu_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#cccccc");
   thirdJetPt_wJets_wMass_emu_stack_3->SetLineColor(ci);
   thirdJetPt_wJets_wMass_emu_stack_3->SetLineWidth(0);
   thirdJetPt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_wJets_wMass_emu_stack_3->GetXaxis()->SetLabelFont(42);
   thirdJetPt_wJets_wMass_emu_stack_3->GetXaxis()->SetLabelSize(0.035);
   thirdJetPt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleSize(0.035);
   thirdJetPt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleFont(42);
   thirdJetPt_wJets_wMass_emu_stack_3->GetYaxis()->SetLabelFont(42);
   thirdJetPt_wJets_wMass_emu_stack_3->GetYaxis()->SetLabelSize(0.035);
   thirdJetPt_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleSize(0.035);
   thirdJetPt_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleOffset(1);
   thirdJetPt_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleFont(42);
   thirdJetPt_wJets_wMass_emu_stack_3->GetZaxis()->SetLabelFont(42);
   thirdJetPt_wJets_wMass_emu_stack_3->GetZaxis()->SetLabelSize(0.035);
   thirdJetPt_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleSize(0.035);
   thirdJetPt_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_wMass_emu->Add(thirdJetPt_wJets_wMass_emu_stack_3,"");
   
   TH1D *thirdJetPt_VVV_wMass_emu_stack_4 = new TH1D("thirdJetPt_VVV_wMass_emu_stack_4","thirdJetPt_VVV_wMass_emu",35,0,300);
   thirdJetPt_VVV_wMass_emu_stack_4->SetBinContent(5,0.05859303);
   thirdJetPt_VVV_wMass_emu_stack_4->SetBinContent(6,0.03181695);
   thirdJetPt_VVV_wMass_emu_stack_4->SetBinContent(7,0.06803485);
   thirdJetPt_VVV_wMass_emu_stack_4->SetBinContent(10,0.03392089);
   thirdJetPt_VVV_wMass_emu_stack_4->SetBinContent(22,0.0318951);
   thirdJetPt_VVV_wMass_emu_stack_4->SetEntries(9);
   thirdJetPt_VVV_wMass_emu_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#00ffff");
   thirdJetPt_VVV_wMass_emu_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   thirdJetPt_VVV_wMass_emu_stack_4->SetLineColor(ci);
   thirdJetPt_VVV_wMass_emu_stack_4->SetLineWidth(0);
   thirdJetPt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_VVV_wMass_emu_stack_4->GetXaxis()->SetLabelFont(42);
   thirdJetPt_VVV_wMass_emu_stack_4->GetXaxis()->SetLabelSize(0.035);
   thirdJetPt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleSize(0.035);
   thirdJetPt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleFont(42);
   thirdJetPt_VVV_wMass_emu_stack_4->GetYaxis()->SetLabelFont(42);
   thirdJetPt_VVV_wMass_emu_stack_4->GetYaxis()->SetLabelSize(0.035);
   thirdJetPt_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleSize(0.035);
   thirdJetPt_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleOffset(1);
   thirdJetPt_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleFont(42);
   thirdJetPt_VVV_wMass_emu_stack_4->GetZaxis()->SetLabelFont(42);
   thirdJetPt_VVV_wMass_emu_stack_4->GetZaxis()->SetLabelSize(0.035);
   thirdJetPt_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleSize(0.035);
   thirdJetPt_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_wMass_emu->Add(thirdJetPt_VVV_wMass_emu_stack_4,"");
   
   TH1D *thirdJetPt_VV_wMass_emu_stack_5 = new TH1D("thirdJetPt_VV_wMass_emu_stack_5","thirdJetPt_VV_wMass_emu",35,0,300);
   thirdJetPt_VV_wMass_emu_stack_5->SetBinContent(4,0.3928633);
   thirdJetPt_VV_wMass_emu_stack_5->SetBinContent(5,0.3955384);
   thirdJetPt_VV_wMass_emu_stack_5->SetBinContent(6,0.7553072);
   thirdJetPt_VV_wMass_emu_stack_5->SetBinContent(7,0.1730929);
   thirdJetPt_VV_wMass_emu_stack_5->SetBinContent(8,0.1834852);
   thirdJetPt_VV_wMass_emu_stack_5->SetBinContent(9,0.164458);
   thirdJetPt_VV_wMass_emu_stack_5->SetBinContent(10,0.2200434);
   thirdJetPt_VV_wMass_emu_stack_5->SetBinContent(11,0.001944076);
   thirdJetPt_VV_wMass_emu_stack_5->SetBinContent(14,0.004911191);
   thirdJetPt_VV_wMass_emu_stack_5->SetBinContent(16,0.1753542);
   thirdJetPt_VV_wMass_emu_stack_5->SetBinContent(21,0.0126204);
   thirdJetPt_VV_wMass_emu_stack_5->SetEntries(45);
   thirdJetPt_VV_wMass_emu_stack_5->SetDirectory(0);

   ci = TColor::GetColor("#ff9933");
   thirdJetPt_VV_wMass_emu_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#ff9933");
   thirdJetPt_VV_wMass_emu_stack_5->SetLineColor(ci);
   thirdJetPt_VV_wMass_emu_stack_5->SetLineWidth(0);
   thirdJetPt_VV_wMass_emu_stack_5->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_VV_wMass_emu_stack_5->GetXaxis()->SetLabelFont(42);
   thirdJetPt_VV_wMass_emu_stack_5->GetXaxis()->SetLabelSize(0.035);
   thirdJetPt_VV_wMass_emu_stack_5->GetXaxis()->SetTitleSize(0.035);
   thirdJetPt_VV_wMass_emu_stack_5->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_VV_wMass_emu_stack_5->GetXaxis()->SetTitleFont(42);
   thirdJetPt_VV_wMass_emu_stack_5->GetYaxis()->SetLabelFont(42);
   thirdJetPt_VV_wMass_emu_stack_5->GetYaxis()->SetLabelSize(0.035);
   thirdJetPt_VV_wMass_emu_stack_5->GetYaxis()->SetTitleSize(0.035);
   thirdJetPt_VV_wMass_emu_stack_5->GetYaxis()->SetTitleOffset(1);
   thirdJetPt_VV_wMass_emu_stack_5->GetYaxis()->SetTitleFont(42);
   thirdJetPt_VV_wMass_emu_stack_5->GetZaxis()->SetLabelFont(42);
   thirdJetPt_VV_wMass_emu_stack_5->GetZaxis()->SetLabelSize(0.035);
   thirdJetPt_VV_wMass_emu_stack_5->GetZaxis()->SetTitleSize(0.035);
   thirdJetPt_VV_wMass_emu_stack_5->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_VV_wMass_emu_stack_5->GetZaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_wMass_emu->Add(thirdJetPt_VV_wMass_emu_stack_5,"");
   
   TH1D *thirdJetPt_SingleTop_wMass_emu_stack_6 = new TH1D("thirdJetPt_SingleTop_wMass_emu_stack_6","thirdJetPt_SingleTop_wMass_emu",35,0,300);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(4,6.90248);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(5,29.70224);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(6,23.5369);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(7,13.00419);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(8,9.631584);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(9,6.511859);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(10,5.305085);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(11,3.947573);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(12,1.202996);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(13,1.574471);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(14,0.4358185);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(15,0.6927953);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(16,0.5411869);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(17,0.3681513);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(18,0.5123778);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(19,0.2209408);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(24,0.2067062);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(28,0.08868854);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(34,0.1792295);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetBinContent(36,0.1688538);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetEntries(1034);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetDirectory(0);

   ci = TColor::GetColor("#ff00ff");
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetLineColor(ci);
   thirdJetPt_SingleTop_wMass_emu_stack_6->SetLineWidth(0);
   thirdJetPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetLabelFont(42);
   thirdJetPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetLabelSize(0.035);
   thirdJetPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleSize(0.035);
   thirdJetPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetLabelFont(42);
   thirdJetPt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetLabelSize(0.035);
   thirdJetPt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleSize(0.035);
   thirdJetPt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleOffset(1);
   thirdJetPt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetLabelFont(42);
   thirdJetPt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetLabelSize(0.035);
   thirdJetPt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleSize(0.035);
   thirdJetPt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_wMass_emu->Add(thirdJetPt_SingleTop_wMass_emu_stack_6,"");
   
   TH1D *thirdJetPt_tt_wMass_emu_stack_7 = new TH1D("thirdJetPt_tt_wMass_emu_stack_7","thirdJetPt_tt_wMass_emu",35,0,300);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(4,131.3662);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(5,561.6731);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(6,541.7989);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(7,395.1662);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(8,255.3435);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(9,177.2738);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(10,103.4679);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(11,72.01484);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(12,48.33922);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(13,32.74689);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(14,23.90278);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(15,19.03096);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(16,11.56271);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(17,8.308784);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(18,5.463516);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(19,3.826876);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(20,1.085886);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(21,1.985499);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(22,2.302636);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(23,0.589595);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(24,1.324036);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(25,0.50992);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(27,0.3541745);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(28,0.3199248);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(29,0.3083111);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(31,0.5928203);
   thirdJetPt_tt_wMass_emu_stack_7->SetBinContent(35,0.1198347);
   thirdJetPt_tt_wMass_emu_stack_7->SetEntries(7802);
   thirdJetPt_tt_wMass_emu_stack_7->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   thirdJetPt_tt_wMass_emu_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   thirdJetPt_tt_wMass_emu_stack_7->SetLineColor(ci);
   thirdJetPt_tt_wMass_emu_stack_7->SetLineWidth(0);
   thirdJetPt_tt_wMass_emu_stack_7->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_tt_wMass_emu_stack_7->GetXaxis()->SetLabelFont(42);
   thirdJetPt_tt_wMass_emu_stack_7->GetXaxis()->SetLabelSize(0.035);
   thirdJetPt_tt_wMass_emu_stack_7->GetXaxis()->SetTitleSize(0.035);
   thirdJetPt_tt_wMass_emu_stack_7->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_tt_wMass_emu_stack_7->GetXaxis()->SetTitleFont(42);
   thirdJetPt_tt_wMass_emu_stack_7->GetYaxis()->SetLabelFont(42);
   thirdJetPt_tt_wMass_emu_stack_7->GetYaxis()->SetLabelSize(0.035);
   thirdJetPt_tt_wMass_emu_stack_7->GetYaxis()->SetTitleSize(0.035);
   thirdJetPt_tt_wMass_emu_stack_7->GetYaxis()->SetTitleOffset(1);
   thirdJetPt_tt_wMass_emu_stack_7->GetYaxis()->SetTitleFont(42);
   thirdJetPt_tt_wMass_emu_stack_7->GetZaxis()->SetLabelFont(42);
   thirdJetPt_tt_wMass_emu_stack_7->GetZaxis()->SetLabelSize(0.035);
   thirdJetPt_tt_wMass_emu_stack_7->GetZaxis()->SetTitleSize(0.035);
   thirdJetPt_tt_wMass_emu_stack_7->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_tt_wMass_emu_stack_7->GetZaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_wMass_emu->Add(thirdJetPt_tt_wMass_emu_stack_7,"");
   
   TH1D *thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8 = new TH1D("thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8","thirdJetPt_zPlusJetsMadgraph_wMass_emu",35,0,300);
   thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->SetLineColor(ci);
   thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->SetLineWidth(0);
   thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetLabelFont(42);
   thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetLabelSize(0.035);
   thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleSize(0.035);
   thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleFont(42);
   thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetLabelFont(42);
   thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetLabelSize(0.035);
   thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleSize(0.035);
   thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleOffset(1);
   thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleFont(42);
   thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetLabelFont(42);
   thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetLabelSize(0.035);
   thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleSize(0.035);
   thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_wMass_emu->Add(thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8,"");
   thirdJetPt_SingleTop_wMass_emu->Draw("");
   
   TH1D *thirdJetPt_data_wMass_emu__10 = new TH1D("thirdJetPt_data_wMass_emu__10","thirdJetPt_data_wMass_emu",35,0,300);
   thirdJetPt_data_wMass_emu__10->SetBinContent(4,142);
   thirdJetPt_data_wMass_emu__10->SetBinContent(5,648);
   thirdJetPt_data_wMass_emu__10->SetBinContent(6,599);
   thirdJetPt_data_wMass_emu__10->SetBinContent(7,471);
   thirdJetPt_data_wMass_emu__10->SetBinContent(8,264);
   thirdJetPt_data_wMass_emu__10->SetBinContent(9,193);
   thirdJetPt_data_wMass_emu__10->SetBinContent(10,110);
   thirdJetPt_data_wMass_emu__10->SetBinContent(11,73);
   thirdJetPt_data_wMass_emu__10->SetBinContent(12,54);
   thirdJetPt_data_wMass_emu__10->SetBinContent(13,41);
   thirdJetPt_data_wMass_emu__10->SetBinContent(14,17);
   thirdJetPt_data_wMass_emu__10->SetBinContent(15,20);
   thirdJetPt_data_wMass_emu__10->SetBinContent(16,9);
   thirdJetPt_data_wMass_emu__10->SetBinContent(17,8);
   thirdJetPt_data_wMass_emu__10->SetBinContent(18,5);
   thirdJetPt_data_wMass_emu__10->SetBinContent(19,1);
   thirdJetPt_data_wMass_emu__10->SetBinContent(20,5);
   thirdJetPt_data_wMass_emu__10->SetBinContent(22,3);
   thirdJetPt_data_wMass_emu__10->SetBinContent(23,1);
   thirdJetPt_data_wMass_emu__10->SetBinContent(24,1);
   thirdJetPt_data_wMass_emu__10->SetBinContent(25,1);
   thirdJetPt_data_wMass_emu__10->SetBinContent(30,1);
   thirdJetPt_data_wMass_emu__10->SetBinContent(36,1);
   thirdJetPt_data_wMass_emu__10->SetEntries(2668);
   thirdJetPt_data_wMass_emu__10->SetDirectory(0);
   thirdJetPt_data_wMass_emu__10->SetFillColor(1);
   thirdJetPt_data_wMass_emu__10->SetLineWidth(2);
   thirdJetPt_data_wMass_emu__10->SetLineColor(1); //
   thirdJetPt_data_wMass_emu__10->SetMarkerStyle(20);
   thirdJetPt_data_wMass_emu__10->SetMarkerSize(1.4);
   thirdJetPt_data_wMass_emu__10->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_data_wMass_emu__10->GetXaxis()->SetLabelFont(42);
   thirdJetPt_data_wMass_emu__10->GetXaxis()->SetLabelSize(0.035);
   thirdJetPt_data_wMass_emu__10->GetXaxis()->SetTitleSize(0.035);
   thirdJetPt_data_wMass_emu__10->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_data_wMass_emu__10->GetXaxis()->SetTitleFont(42);
   thirdJetPt_data_wMass_emu__10->GetYaxis()->SetLabelFont(42);
   thirdJetPt_data_wMass_emu__10->GetYaxis()->SetLabelSize(0.035);
   thirdJetPt_data_wMass_emu__10->GetYaxis()->SetTitleSize(0.035);
   thirdJetPt_data_wMass_emu__10->GetYaxis()->SetTitleOffset(1);
   thirdJetPt_data_wMass_emu__10->GetYaxis()->SetTitleFont(42);
   thirdJetPt_data_wMass_emu__10->GetZaxis()->SetLabelFont(42);
   thirdJetPt_data_wMass_emu__10->GetZaxis()->SetLabelSize(0.035);
   thirdJetPt_data_wMass_emu__10->GetZaxis()->SetTitleSize(0.035);
   thirdJetPt_data_wMass_emu__10->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_data_wMass_emu__10->GetZaxis()->SetTitleFont(42);
   thirdJetPt_data_wMass_emu__10->Draw("e x0, same");
   
   TLegend *leg = new TLegend(0.78,0.42,0.98,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("thirdJetPt_zPlusJetsMadgraph_wMass_emu_stack_8","Z+jets (LO)","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetPt_tt_wMass_emu_stack_7","t#bar{t}","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetPt_SingleTop_wMass_emu_stack_6","Single top","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetPt_VV_wMass_emu_stack_5","VV","f");

   ci = TColor::GetColor("#ff9933");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetPt_VVV_wMass_emu_stack_4","VVV","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetPt_wJets_wMass_emu_stack_3","W+jets","f");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetPt_ttV_wMass_emu_stack_2","t#bar{t}V","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetPt_tZq_wMass_emu_stack_1","tZq","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetPt_data_wMass_emu","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.4);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.968,0.9429101,"35.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06792969);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.096,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.05419922);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16899,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.04119141);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *thirdJetPt_SingleTop_wMass_emu__11 = new TH1F("thirdJetPt_SingleTop_wMass_emu__11","Third Jet p_{T}",35,0,300);
   thirdJetPt_SingleTop_wMass_emu__11->SetMinimum(-0.00135082);
   thirdJetPt_SingleTop_wMass_emu__11->SetMaximum(748.44);
   thirdJetPt_SingleTop_wMass_emu__11->SetDirectory(0);
   thirdJetPt_SingleTop_wMass_emu__11->SetStats(0);
   thirdJetPt_SingleTop_wMass_emu__11->SetLineStyle(0);
   thirdJetPt_SingleTop_wMass_emu__11->SetLineWidth(0);
   thirdJetPt_SingleTop_wMass_emu__11->SetMarkerStyle(20);
   thirdJetPt_SingleTop_wMass_emu__11->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_SingleTop_wMass_emu__11->GetXaxis()->SetNdivisions(506);
   thirdJetPt_SingleTop_wMass_emu__11->GetXaxis()->SetLabelFont(42);
   thirdJetPt_SingleTop_wMass_emu__11->GetXaxis()->SetLabelOffset(999);
   thirdJetPt_SingleTop_wMass_emu__11->GetXaxis()->SetLabelSize(0.05);
   thirdJetPt_SingleTop_wMass_emu__11->GetXaxis()->SetTitleSize(0.08);
   thirdJetPt_SingleTop_wMass_emu__11->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_SingleTop_wMass_emu__11->GetXaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_wMass_emu__11->GetYaxis()->SetTitle("Events");
   thirdJetPt_SingleTop_wMass_emu__11->GetYaxis()->SetNdivisions(506);
   thirdJetPt_SingleTop_wMass_emu__11->GetYaxis()->SetLabelFont(42);
   thirdJetPt_SingleTop_wMass_emu__11->GetYaxis()->SetLabelOffset(0.01);
   thirdJetPt_SingleTop_wMass_emu__11->GetYaxis()->SetLabelSize(0.062);
   thirdJetPt_SingleTop_wMass_emu__11->GetYaxis()->SetTitleSize(0.08);
   thirdJetPt_SingleTop_wMass_emu__11->GetYaxis()->SetTitleOffset(0.6336);
   thirdJetPt_SingleTop_wMass_emu__11->GetYaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_wMass_emu__11->GetZaxis()->SetLabelFont(42);
   thirdJetPt_SingleTop_wMass_emu__11->GetZaxis()->SetLabelOffset(0.007);
   thirdJetPt_SingleTop_wMass_emu__11->GetZaxis()->SetLabelSize(0.05);
   thirdJetPt_SingleTop_wMass_emu__11->GetZaxis()->SetTitleSize(0.08);
   thirdJetPt_SingleTop_wMass_emu__11->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_SingleTop_wMass_emu__11->GetZaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_wMass_emu__11->Draw("sameaxis");
   
   TPaveText *pt = new TPaveText(0.4353068,0.9203237,0.5646932,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Third Jet p_{T}");
   pt->Draw();
   canvy_1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: canvy_2
   TPad *canvy_2 = new TPad("canvy_2", "newpad2",0.01,0.01,0.99,0.322);
   canvy_2->Draw();
   canvy_2->cd();
   canvy_2->SetFillColor(0);
   canvy_2->SetBorderMode(0);
   canvy_2->SetGridy();

   canvy_2->SetLeftMargin( L/W );
   canvy_2->SetRightMargin( R/W );
   canvy_2->SetTopMargin( T/H );
   canvy_2->SetBottomMargin( B/H * 2.6 );
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   
   TH1D *thirdJetPt_data_wMass_emu__12 = new TH1D("thirdJetPt_data_wMass_emu__12","",35,0,300);
   thirdJetPt_data_wMass_emu__12->SetBinContent(4,1.01976);
   thirdJetPt_data_wMass_emu__12->SetBinContent(5,1.087918);
   thirdJetPt_data_wMass_emu__12->SetBinContent(6,1.048532);
   thirdJetPt_data_wMass_emu__12->SetBinContent(7,1.138554);
   thirdJetPt_data_wMass_emu__12->SetBinContent(8,0.9829921);
   thirdJetPt_data_wMass_emu__12->SetBinContent(9,1.033189);
   thirdJetPt_data_wMass_emu__12->SetBinContent(10,0.9906751);
   thirdJetPt_data_wMass_emu__12->SetBinContent(11,0.9447862);
   thirdJetPt_data_wMass_emu__12->SetBinContent(12,1.072052);
   thirdJetPt_data_wMass_emu__12->SetBinContent(13,1.163631);
   thirdJetPt_data_wMass_emu__12->SetBinContent(14,0.678958);
   thirdJetPt_data_wMass_emu__12->SetBinContent(15,1.000008);
   thirdJetPt_data_wMass_emu__12->SetBinContent(16,0.7037378);
   thirdJetPt_data_wMass_emu__12->SetBinContent(17,0.9037124);
   thirdJetPt_data_wMass_emu__12->SetBinContent(18,0.8072488);
   thirdJetPt_data_wMass_emu__12->SetBinContent(19,0.2436586);
   thirdJetPt_data_wMass_emu__12->SetBinContent(20,4.401037);
   thirdJetPt_data_wMass_emu__12->SetBinContent(22,1.246731);
   thirdJetPt_data_wMass_emu__12->SetBinContent(23,1.563753);
   thirdJetPt_data_wMass_emu__12->SetBinContent(24,0.6388449);
   thirdJetPt_data_wMass_emu__12->SetBinContent(25,1.960656);
   thirdJetPt_data_wMass_emu__12->SetBinContent(36,7.892281);
   thirdJetPt_data_wMass_emu__12->SetBinError(4,0.1216197);
   thirdJetPt_data_wMass_emu__12->SetBinError(5,0.06175405);
   thirdJetPt_data_wMass_emu__12->SetBinError(6,0.06131822);
   thirdJetPt_data_wMass_emu__12->SetBinError(7,0.07671911);
   thirdJetPt_data_wMass_emu__12->SetBinError(8,0.08519391);
   thirdJetPt_data_wMass_emu__12->SetBinError(9,0.106045);
   thirdJetPt_data_wMass_emu__12->SetBinError(10,0.1332708);
   thirdJetPt_data_wMass_emu__12->SetBinError(11,0.1542084);
   thirdJetPt_data_wMass_emu__12->SetBinError(12,0.2100001);
   thirdJetPt_data_wMass_emu__12->SetBinError(13,0.2673098);
   thirdJetPt_data_wMass_emu__12->SetBinError(14,0.2133725);
   thirdJetPt_data_wMass_emu__12->SetBinError(15,0.3162311);
   thirdJetPt_data_wMass_emu__12->SetBinError(16,0.30619);
   thirdJetPt_data_wMass_emu__12->SetBinError(17,0.440845);
   thirdJetPt_data_wMass_emu__12->SetBinError(18,0.4853236);
   thirdJetPt_data_wMass_emu__12->SetBinError(19,0.2717267);
   thirdJetPt_data_wMass_emu__12->SetBinError(20,4.574131);
   thirdJetPt_data_wMass_emu__12->SetBinError(22,1.078916);
   thirdJetPt_data_wMass_emu__12->SetBinError(23,2.503838);
   thirdJetPt_data_wMass_emu__12->SetBinError(24,0.8178325);
   thirdJetPt_data_wMass_emu__12->SetBinError(25,3.373614);
   thirdJetPt_data_wMass_emu__12->SetBinError(36,23.53472);
   thirdJetPt_data_wMass_emu__12->SetMinimum(0.5);
   thirdJetPt_data_wMass_emu__12->SetMaximum(1.5);
   thirdJetPt_data_wMass_emu__12->SetEntries(14.67027);
   thirdJetPt_data_wMass_emu__12->SetDirectory(0);
   thirdJetPt_data_wMass_emu__12->SetStats(0);
   thirdJetPt_data_wMass_emu__12->SetFillColor(1);
   thirdJetPt_data_wMass_emu__12->SetLineWidth(2);
   thirdJetPt_data_wMass_emu__12->SetLineColor(1); //
   thirdJetPt_data_wMass_emu__12->SetMarkerStyle(20);
   thirdJetPt_data_wMass_emu__12->SetMarkerSize(1.6);
   thirdJetPt_data_wMass_emu__12->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_data_wMass_emu__12->GetXaxis()->SetNdivisions(506);
   thirdJetPt_data_wMass_emu__12->GetXaxis()->SetLabelFont(42);
   thirdJetPt_data_wMass_emu__12->GetXaxis()->SetLabelOffset(0.013);
   thirdJetPt_data_wMass_emu__12->GetXaxis()->SetLabelSize(0.13);
   thirdJetPt_data_wMass_emu__12->GetXaxis()->SetTitleSize(0.13);
   thirdJetPt_data_wMass_emu__12->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_data_wMass_emu__12->GetXaxis()->SetTitleFont(42);
   thirdJetPt_data_wMass_emu__12->GetYaxis()->SetTitle("Data/MC");
   thirdJetPt_data_wMass_emu__12->GetYaxis()->CenterTitle(true);
   thirdJetPt_data_wMass_emu__12->GetYaxis()->SetNdivisions(506);
   thirdJetPt_data_wMass_emu__12->GetYaxis()->SetLabelFont(42);
   thirdJetPt_data_wMass_emu__12->GetYaxis()->SetLabelOffset(0.01);
   thirdJetPt_data_wMass_emu__12->GetYaxis()->SetLabelSize(0.12);
   thirdJetPt_data_wMass_emu__12->GetYaxis()->SetTitleSize(0.16);
   thirdJetPt_data_wMass_emu__12->GetYaxis()->SetTitleOffset(0.3);
   thirdJetPt_data_wMass_emu__12->GetYaxis()->SetTitleFont(42);
   thirdJetPt_data_wMass_emu__12->GetZaxis()->SetLabelFont(42);
   thirdJetPt_data_wMass_emu__12->GetZaxis()->SetLabelSize(0.035);
   thirdJetPt_data_wMass_emu__12->GetZaxis()->SetTitleSize(0.035);
   thirdJetPt_data_wMass_emu__12->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_data_wMass_emu__12->GetZaxis()->SetTitleFont(42);
   thirdJetPt_data_wMass_emu__12->Draw("e x0, SCAT");
   canvy_2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
//   c1->SetSelected(thirdJetPt_data_wMass_emu);
   c1->SaveAs("thirdJetPt_wMass.pdf");
}
