void thirdJetEta_SingleTop_jetSel()
{
//=========Macro generated from canvas: thirdJetEta_SingleTop_jetSel/thirdJetEta_SingleTop_jetSel
//=========  (Wed Aug 21 19:45:59 2019) by ROOT version 6.18/00

   // Set up cavas
   int W = 1280;
   int H = 1024;
   int H_ref = 925;
   int W_ref = 1024;

   // references for T, B, L, R
   float T = 0.08*H_ref;
   float B = 0.12*H_ref;
   float L = 0.12*W_ref;
   float R = 0.04*W_ref;

   TCanvas *c1 = new TCanvas("c1","c1",50,50,W,H);
   c1->cd();
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetLeftMargin( L/W );
   c1->SetRightMargin( R/W );
   c1->SetTopMargin( T/H );
   c1->SetBottomMargin( B/H );
   c1->SetTickx(0);
   c1->SetTicky(0);
  
// ------------>Primitives in pad: canvy_1
   TPad *canvy_1 = new TPad("canvy_1", "newpad",0.01,0.315,0.99,0.99);
   canvy_1->Draw();
   canvy_1->cd();
   canvy_1->SetFillColor(0);
   canvy_1->SetBorderMode(0);

   canvy_1->SetLeftMargin( L/W );
   canvy_1->SetRightMargin( R/W );
   canvy_1->SetTopMargin( T/H );
   canvy_1->SetBottomMargin( B/H * 0.3 );

   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);
   
   THStack *thirdJetEta_SingleTop_jetSel_emu = new THStack();
   thirdJetEta_SingleTop_jetSel_emu->SetName("thirdJetEta_SingleTop_jetSel_emu");
   thirdJetEta_SingleTop_jetSel_emu->SetTitle("Third Jet #eta;Third Jet #eta;Events");
   thirdJetEta_SingleTop_jetSel_emu->SetMaximum(331.1);
   
   TH1F *thirdJetEta_SingleTop_jetSel_emu_stack_4 = new TH1F("thirdJetEta_SingleTop_jetSel_emu_stack_4","Third Jet #eta",25,0,5);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->SetMinimum(0);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->SetMaximum(347.655);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->SetDirectory(0);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->SetStats(0);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->SetLineStyle(0);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->SetLineWidth(0);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->SetMarkerStyle(20);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_SingleTop_jetSel_emu_stack_4->GetXaxis()->SetNdivisions(506);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->GetXaxis()->SetLabelFont(42);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->GetXaxis()->SetLabelOffset(999);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->GetXaxis()->SetLabelSize(0.05);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->GetXaxis()->SetTitleSize(0.08);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->GetXaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->GetYaxis()->SetTitle("Events");
   thirdJetEta_SingleTop_jetSel_emu_stack_4->GetYaxis()->SetNdivisions(506);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->GetYaxis()->SetLabelFont(42);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->GetYaxis()->SetLabelOffset(0.01);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->GetYaxis()->SetLabelSize(0.062);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->GetYaxis()->SetTitleSize(0.08);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->GetYaxis()->SetTitleOffset(0.6336);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->GetYaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->GetZaxis()->SetLabelFont(42);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->GetZaxis()->SetLabelOffset(0.007);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->GetZaxis()->SetLabelSize(0.05);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->GetZaxis()->SetTitleSize(0.08);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_SingleTop_jetSel_emu_stack_4->GetZaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_jetSel_emu->SetHistogram(thirdJetEta_SingleTop_jetSel_emu_stack_4);
   
   
   TH1D *thirdJetEta_tZq_jetSel_emu_stack_1 = new TH1D("thirdJetEta_tZq_jetSel_emu_stack_1","thirdJetEta_tZq_jetSel_emu",25,0,5);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(0,0.5330416);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(1,0.03695226);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(2,0.04804471);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(3,0.03677858);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(4,0.0210276);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(5,0.04651332);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(6,0.0471487);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(7,0.03166976);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(8,0.05202881);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(9,0.04559758);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(10,0.02620635);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(11,0.02750496);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(12,0.02203069);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(13,0.0220406);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(14,0.04553257);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(15,0.02122138);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(16,0.01030873);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(17,0.003998244);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(18,0.002489517);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(19,0.008888158);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(20,0.008017877);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(21,0.004061606);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(22,0.003505543);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(23,0.002187866);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetBinContent(24,-0.00130445);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetEntries(6672);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ffff00");
   thirdJetEta_tZq_jetSel_emu_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   thirdJetEta_tZq_jetSel_emu_stack_1->SetLineColor(ci);
   thirdJetEta_tZq_jetSel_emu_stack_1->SetLineWidth(0);
   thirdJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetLabelFont(42);
   thirdJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetLabelSize(0.035);
   thirdJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleSize(0.035);
   thirdJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleFont(42);
   thirdJetEta_tZq_jetSel_emu_stack_1->GetYaxis()->SetLabelFont(42);
   thirdJetEta_tZq_jetSel_emu_stack_1->GetYaxis()->SetLabelSize(0.035);
   thirdJetEta_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleSize(0.035);
   thirdJetEta_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleOffset(1);
   thirdJetEta_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleFont(42);
   thirdJetEta_tZq_jetSel_emu_stack_1->GetZaxis()->SetLabelFont(42);
   thirdJetEta_tZq_jetSel_emu_stack_1->GetZaxis()->SetLabelSize(0.035);
   thirdJetEta_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleSize(0.035);
   thirdJetEta_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_jetSel_emu->Add(thirdJetEta_tZq_jetSel_emu_stack_1,"");
   
   TH1D *thirdJetEta_ttV_jetSel_emu_stack_2 = new TH1D("thirdJetEta_ttV_jetSel_emu_stack_2","thirdJetEta_ttV_jetSel_emu",25,0,5);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(0,28.73512);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(1,3.805018);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(2,1.949444);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(3,3.617789);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(4,2.362189);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(5,2.475699);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(6,1.727867);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(7,2.05089);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(8,1.931263);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(9,1.706388);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(10,0.9138545);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(11,1.083992);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(12,0.9606006);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(13,0.6912458);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(14,0.6841749);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(15,0.530882);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(16,0.2397325);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(17,0.3828118);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(18,0.1855117);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(19,0.1835022);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(20,0.1126456);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(21,0.02603869);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(22,0.1255653);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(23,0.0271088);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetBinContent(24,0.01410943);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetEntries(29408);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#00ff00");
   thirdJetEta_ttV_jetSel_emu_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   thirdJetEta_ttV_jetSel_emu_stack_2->SetLineColor(ci);
   thirdJetEta_ttV_jetSel_emu_stack_2->SetLineWidth(0);
   thirdJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetLabelFont(42);
   thirdJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetLabelSize(0.035);
   thirdJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleSize(0.035);
   thirdJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleFont(42);
   thirdJetEta_ttV_jetSel_emu_stack_2->GetYaxis()->SetLabelFont(42);
   thirdJetEta_ttV_jetSel_emu_stack_2->GetYaxis()->SetLabelSize(0.035);
   thirdJetEta_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleSize(0.035);
   thirdJetEta_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleOffset(1);
   thirdJetEta_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleFont(42);
   thirdJetEta_ttV_jetSel_emu_stack_2->GetZaxis()->SetLabelFont(42);
   thirdJetEta_ttV_jetSel_emu_stack_2->GetZaxis()->SetLabelSize(0.035);
   thirdJetEta_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleSize(0.035);
   thirdJetEta_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_jetSel_emu->Add(thirdJetEta_ttV_jetSel_emu_stack_2,"");
   
   TH1D *thirdJetEta_wJets_jetSel_emu_stack_3 = new TH1D("thirdJetEta_wJets_jetSel_emu_stack_3","thirdJetEta_wJets_jetSel_emu",25,0,5);
   thirdJetEta_wJets_jetSel_emu_stack_3->SetBinContent(0,25.96231);
   thirdJetEta_wJets_jetSel_emu_stack_3->SetEntries(2);
   thirdJetEta_wJets_jetSel_emu_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   thirdJetEta_wJets_jetSel_emu_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#cccccc");
   thirdJetEta_wJets_jetSel_emu_stack_3->SetLineColor(ci);
   thirdJetEta_wJets_jetSel_emu_stack_3->SetLineWidth(0);
   thirdJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetLabelFont(42);
   thirdJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetLabelSize(0.035);
   thirdJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleSize(0.035);
   thirdJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleFont(42);
   thirdJetEta_wJets_jetSel_emu_stack_3->GetYaxis()->SetLabelFont(42);
   thirdJetEta_wJets_jetSel_emu_stack_3->GetYaxis()->SetLabelSize(0.035);
   thirdJetEta_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleSize(0.035);
   thirdJetEta_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleOffset(1);
   thirdJetEta_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleFont(42);
   thirdJetEta_wJets_jetSel_emu_stack_3->GetZaxis()->SetLabelFont(42);
   thirdJetEta_wJets_jetSel_emu_stack_3->GetZaxis()->SetLabelSize(0.035);
   thirdJetEta_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleSize(0.035);
   thirdJetEta_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_jetSel_emu->Add(thirdJetEta_wJets_jetSel_emu_stack_3,"");
   
   TH1D *thirdJetEta_VVV_jetSel_emu_stack_4 = new TH1D("thirdJetEta_VVV_jetSel_emu_stack_4","thirdJetEta_VVV_jetSel_emu",25,0,5);
   thirdJetEta_VVV_jetSel_emu_stack_4->SetBinContent(0,2.09541);
   thirdJetEta_VVV_jetSel_emu_stack_4->SetBinContent(1,0.1170967);
   thirdJetEta_VVV_jetSel_emu_stack_4->SetBinContent(2,0.2827259);
   thirdJetEta_VVV_jetSel_emu_stack_4->SetBinContent(3,0.1843129);
   thirdJetEta_VVV_jetSel_emu_stack_4->SetBinContent(4,0.247376);
   thirdJetEta_VVV_jetSel_emu_stack_4->SetBinContent(5,0.09306109);
   thirdJetEta_VVV_jetSel_emu_stack_4->SetBinContent(6,0.08880931);
   thirdJetEta_VVV_jetSel_emu_stack_4->SetBinContent(7,0.04867203);
   thirdJetEta_VVV_jetSel_emu_stack_4->SetBinContent(8,0.1171658);
   thirdJetEta_VVV_jetSel_emu_stack_4->SetBinContent(10,0.07444611);
   thirdJetEta_VVV_jetSel_emu_stack_4->SetBinContent(11,0.06310358);
   thirdJetEta_VVV_jetSel_emu_stack_4->SetBinContent(12,0.09819271);
   thirdJetEta_VVV_jetSel_emu_stack_4->SetBinContent(13,0.03625792);
   thirdJetEta_VVV_jetSel_emu_stack_4->SetBinContent(14,0.05182671);
   thirdJetEta_VVV_jetSel_emu_stack_4->SetBinContent(15,0.05321664);
   thirdJetEta_VVV_jetSel_emu_stack_4->SetBinContent(17,0.03267903);
   thirdJetEta_VVV_jetSel_emu_stack_4->SetEntries(147);
   thirdJetEta_VVV_jetSel_emu_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#00ffff");
   thirdJetEta_VVV_jetSel_emu_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   thirdJetEta_VVV_jetSel_emu_stack_4->SetLineColor(ci);
   thirdJetEta_VVV_jetSel_emu_stack_4->SetLineWidth(0);
   thirdJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetLabelFont(42);
   thirdJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetLabelSize(0.035);
   thirdJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleSize(0.035);
   thirdJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleFont(42);
   thirdJetEta_VVV_jetSel_emu_stack_4->GetYaxis()->SetLabelFont(42);
   thirdJetEta_VVV_jetSel_emu_stack_4->GetYaxis()->SetLabelSize(0.035);
   thirdJetEta_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleSize(0.035);
   thirdJetEta_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleOffset(1);
   thirdJetEta_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleFont(42);
   thirdJetEta_VVV_jetSel_emu_stack_4->GetZaxis()->SetLabelFont(42);
   thirdJetEta_VVV_jetSel_emu_stack_4->GetZaxis()->SetLabelSize(0.035);
   thirdJetEta_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleSize(0.035);
   thirdJetEta_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_jetSel_emu->Add(thirdJetEta_VVV_jetSel_emu_stack_4,"");
   
   TH1D *thirdJetEta_VV_jetSel_emu_stack_5 = new TH1D("thirdJetEta_VV_jetSel_emu_stack_5","thirdJetEta_VV_jetSel_emu",25,0,5);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(0,30.51002);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(1,2.640453);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(2,2.043857);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(3,2.070562);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(4,3.733864);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(5,2.057906);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(6,2.203448);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(7,2.599049);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(8,1.756133);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(9,0.8232001);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(10,2.074546);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(11,1.4397);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(12,1.414114);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(13,1.409465);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(14,0.7367303);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(15,1.209316);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(16,0.5413421);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(17,0.3192127);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(18,0.6919111);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(19,0.1001149);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(20,0.2288748);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(21,0.01159772);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(22,0.22237);
   thirdJetEta_VV_jetSel_emu_stack_5->SetBinContent(24,0.1346967);
   thirdJetEta_VV_jetSel_emu_stack_5->SetEntries(858);
   thirdJetEta_VV_jetSel_emu_stack_5->SetDirectory(0);

   ci = TColor::GetColor("#ff9933");
   thirdJetEta_VV_jetSel_emu_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#ff9933");
   thirdJetEta_VV_jetSel_emu_stack_5->SetLineColor(ci);
   thirdJetEta_VV_jetSel_emu_stack_5->SetLineWidth(0);
   thirdJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetLabelFont(42);
   thirdJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetLabelSize(0.035);
   thirdJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleSize(0.035);
   thirdJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleFont(42);
   thirdJetEta_VV_jetSel_emu_stack_5->GetYaxis()->SetLabelFont(42);
   thirdJetEta_VV_jetSel_emu_stack_5->GetYaxis()->SetLabelSize(0.035);
   thirdJetEta_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleSize(0.035);
   thirdJetEta_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleOffset(1);
   thirdJetEta_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleFont(42);
   thirdJetEta_VV_jetSel_emu_stack_5->GetZaxis()->SetLabelFont(42);
   thirdJetEta_VV_jetSel_emu_stack_5->GetZaxis()->SetLabelSize(0.035);
   thirdJetEta_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleSize(0.035);
   thirdJetEta_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_jetSel_emu->Add(thirdJetEta_VV_jetSel_emu_stack_5,"");
   
   TH1D *thirdJetEta_SingleTop_jetSel_emu_stack_6 = new TH1D("thirdJetEta_SingleTop_jetSel_emu_stack_6","thirdJetEta_SingleTop_jetSel_emu",25,0,5);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(0,138.4408);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(1,12.51026);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(2,10.80616);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(3,13.204);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(4,9.289982);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(5,7.519174);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(6,10.72747);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(7,8.630942);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(8,9.465713);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(9,8.007336);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(10,5.424863);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(11,5.643319);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(12,5.064006);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(13,6.607194);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(14,6.053905);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(15,5.314411);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(16,3.262244);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(17,4.130724);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(18,3.781648);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(19,1.702148);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(20,1.709817);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(21,0.745122);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(22,0.7836174);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(23,1.329936);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetBinContent(24,0.0660897);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetEntries(2806);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetDirectory(0);

   ci = TColor::GetColor("#ff00ff");
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetLineColor(ci);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->SetLineWidth(0);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetLabelFont(42);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetLabelSize(0.035);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleSize(0.035);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetLabelFont(42);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetLabelSize(0.035);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleSize(0.035);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleOffset(1);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetLabelFont(42);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetLabelSize(0.035);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleSize(0.035);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_jetSel_emu->Add(thirdJetEta_SingleTop_jetSel_emu_stack_6,"");
   
   TH1D *thirdJetEta_tt_jetSel_emu_stack_7 = new TH1D("thirdJetEta_tt_jetSel_emu_stack_7","thirdJetEta_tt_jetSel_emu",25,0,5);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(0,3102.498);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(1,276.5315);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(2,275.7472);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(3,275.5458);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(4,270.9658);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(5,236.0033);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(6,231.5112);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(7,203.9074);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(8,195.5075);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(9,190.4422);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(10,145.3257);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(11,135.7564);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(12,130.1638);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(13,97.00915);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(14,122.2903);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(15,67.49937);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(16,52.13808);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(17,68.65601);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(18,47.11991);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(19,39.01749);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(20,25.52851);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(21,22.56609);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(22,13.95461);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(23,9.833775);
   thirdJetEta_tt_jetSel_emu_stack_7->SetBinContent(24,2.999531);
   thirdJetEta_tt_jetSel_emu_stack_7->SetEntries(19867);
   thirdJetEta_tt_jetSel_emu_stack_7->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   thirdJetEta_tt_jetSel_emu_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   thirdJetEta_tt_jetSel_emu_stack_7->SetLineColor(ci);
   thirdJetEta_tt_jetSel_emu_stack_7->SetLineWidth(0);
   thirdJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetLabelFont(42);
   thirdJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetLabelSize(0.035);
   thirdJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleSize(0.035);
   thirdJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleFont(42);
   thirdJetEta_tt_jetSel_emu_stack_7->GetYaxis()->SetLabelFont(42);
   thirdJetEta_tt_jetSel_emu_stack_7->GetYaxis()->SetLabelSize(0.035);
   thirdJetEta_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleSize(0.035);
   thirdJetEta_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleOffset(1);
   thirdJetEta_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleFont(42);
   thirdJetEta_tt_jetSel_emu_stack_7->GetZaxis()->SetLabelFont(42);
   thirdJetEta_tt_jetSel_emu_stack_7->GetZaxis()->SetLabelSize(0.035);
   thirdJetEta_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleSize(0.035);
   thirdJetEta_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_jetSel_emu->Add(thirdJetEta_tt_jetSel_emu_stack_7,"");
   
   TH1D *thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8 = new TH1D("thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8","thirdJetEta_zPlusJetsMadgraph_jetSel_emu",25,0,5);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(0,11.81033);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(3,1.483989);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(5,1.500954);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(6,1.431985);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(7,1.443027);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetEntries(12);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetLineColor(ci);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->SetLineWidth(0);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetLabelFont(42);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetLabelSize(0.035);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleSize(0.035);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleFont(42);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetLabelFont(42);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetLabelSize(0.035);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleSize(0.035);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleOffset(1);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleFont(42);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetLabelFont(42);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetLabelSize(0.035);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleSize(0.035);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_jetSel_emu->Add(thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8,"");
   thirdJetEta_SingleTop_jetSel_emu->Draw("");
   
   TH1D *thirdJetEta_data_jetSel_emu__10 = new TH1D("thirdJetEta_data_jetSel_emu__10","thirdJetEta_data_jetSel_emu",25,0,5);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(0,3416);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(1,262);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(2,273);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(3,301);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(4,284);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(5,256);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(6,237);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(7,231);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(8,190);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(9,197);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(10,156);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(11,127);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(12,141);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(13,107);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(14,117);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(15,95);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(16,50);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(17,60);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(18,48);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(19,34);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(20,25);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(21,24);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(22,25);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(23,9);
   thirdJetEta_data_jetSel_emu__10->SetBinContent(24,3);
   thirdJetEta_data_jetSel_emu__10->SetEntries(6668);
   thirdJetEta_data_jetSel_emu__10->SetDirectory(0);
   thirdJetEta_data_jetSel_emu__10->SetFillColor(1);
   thirdJetEta_data_jetSel_emu__10->SetLineWidth(2);
   thirdJetEta_data_jetSel_emu__10->SetLineColor(1); //
   thirdJetEta_data_jetSel_emu__10->SetMarkerStyle(20);
   thirdJetEta_data_jetSel_emu__10->SetMarkerSize(1.4);
   thirdJetEta_data_jetSel_emu__10->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_data_jetSel_emu__10->GetXaxis()->SetLabelFont(42);
   thirdJetEta_data_jetSel_emu__10->GetXaxis()->SetLabelSize(0.035);
   thirdJetEta_data_jetSel_emu__10->GetXaxis()->SetTitleSize(0.035);
   thirdJetEta_data_jetSel_emu__10->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_data_jetSel_emu__10->GetXaxis()->SetTitleFont(42);
   thirdJetEta_data_jetSel_emu__10->GetYaxis()->SetLabelFont(42);
   thirdJetEta_data_jetSel_emu__10->GetYaxis()->SetLabelSize(0.035);
   thirdJetEta_data_jetSel_emu__10->GetYaxis()->SetTitleSize(0.035);
   thirdJetEta_data_jetSel_emu__10->GetYaxis()->SetTitleOffset(1);
   thirdJetEta_data_jetSel_emu__10->GetYaxis()->SetTitleFont(42);
   thirdJetEta_data_jetSel_emu__10->GetZaxis()->SetLabelFont(42);
   thirdJetEta_data_jetSel_emu__10->GetZaxis()->SetLabelSize(0.035);
   thirdJetEta_data_jetSel_emu__10->GetZaxis()->SetTitleSize(0.035);
   thirdJetEta_data_jetSel_emu__10->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_data_jetSel_emu__10->GetZaxis()->SetTitleFont(42);
   thirdJetEta_data_jetSel_emu__10->Draw("e x0, same");
   
   TLegend *leg = new TLegend(0.78,0.42,0.98,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("thirdJetEta_zPlusJetsMadgraph_jetSel_emu_stack_8","Z+jets (LO)","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetEta_tt_jetSel_emu_stack_7","t#bar{t}","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetEta_SingleTop_jetSel_emu_stack_6","Single top","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetEta_VV_jetSel_emu_stack_5","VV","f");

   ci = TColor::GetColor("#ff9933");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetEta_VVV_jetSel_emu_stack_4","VVV","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetEta_wJets_jetSel_emu_stack_3","W+jets","f");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetEta_ttV_jetSel_emu_stack_2","t#bar{t}V","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetEta_tZq_jetSel_emu_stack_1","tZq","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetEta_data_jetSel_emu","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.4);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.968,0.9429101,"35.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06792969);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.096,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.05419922);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16899,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.04119141);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *thirdJetEta_SingleTop_jetSel_emu__11 = new TH1F("thirdJetEta_SingleTop_jetSel_emu__11","Third Jet #eta",25,0,5);
   thirdJetEta_SingleTop_jetSel_emu__11->SetMinimum(0);
   thirdJetEta_SingleTop_jetSel_emu__11->SetMaximum(347.655);
   thirdJetEta_SingleTop_jetSel_emu__11->SetDirectory(0);
   thirdJetEta_SingleTop_jetSel_emu__11->SetStats(0);
   thirdJetEta_SingleTop_jetSel_emu__11->SetLineStyle(0);
   thirdJetEta_SingleTop_jetSel_emu__11->SetLineWidth(0);
   thirdJetEta_SingleTop_jetSel_emu__11->SetMarkerStyle(20);
   thirdJetEta_SingleTop_jetSel_emu__11->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_SingleTop_jetSel_emu__11->GetXaxis()->SetNdivisions(506);
   thirdJetEta_SingleTop_jetSel_emu__11->GetXaxis()->SetLabelFont(42);
   thirdJetEta_SingleTop_jetSel_emu__11->GetXaxis()->SetLabelOffset(999);
   thirdJetEta_SingleTop_jetSel_emu__11->GetXaxis()->SetLabelSize(0.05);
   thirdJetEta_SingleTop_jetSel_emu__11->GetXaxis()->SetTitleSize(0.08);
   thirdJetEta_SingleTop_jetSel_emu__11->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_SingleTop_jetSel_emu__11->GetXaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_jetSel_emu__11->GetYaxis()->SetTitle("Events");
   thirdJetEta_SingleTop_jetSel_emu__11->GetYaxis()->SetNdivisions(506);
   thirdJetEta_SingleTop_jetSel_emu__11->GetYaxis()->SetLabelFont(42);
   thirdJetEta_SingleTop_jetSel_emu__11->GetYaxis()->SetLabelOffset(0.01);
   thirdJetEta_SingleTop_jetSel_emu__11->GetYaxis()->SetLabelSize(0.062);
   thirdJetEta_SingleTop_jetSel_emu__11->GetYaxis()->SetTitleSize(0.08);
   thirdJetEta_SingleTop_jetSel_emu__11->GetYaxis()->SetTitleOffset(0.6336);
   thirdJetEta_SingleTop_jetSel_emu__11->GetYaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_jetSel_emu__11->GetZaxis()->SetLabelFont(42);
   thirdJetEta_SingleTop_jetSel_emu__11->GetZaxis()->SetLabelOffset(0.007);
   thirdJetEta_SingleTop_jetSel_emu__11->GetZaxis()->SetLabelSize(0.05);
   thirdJetEta_SingleTop_jetSel_emu__11->GetZaxis()->SetTitleSize(0.08);
   thirdJetEta_SingleTop_jetSel_emu__11->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_SingleTop_jetSel_emu__11->GetZaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_jetSel_emu__11->Draw("sameaxis");
   
   TPaveText *pt = new TPaveText(0.439299,0.9371861,0.560701,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Third Jet #eta");
   pt->Draw();
   canvy_1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: canvy_2
   TPad *canvy_2 = new TPad("canvy_2", "newpad2",0.01,0.01,0.99,0.322);
   canvy_2->Draw();
   canvy_2->cd();
   canvy_2->SetFillColor(0);
   canvy_2->SetBorderMode(0);
   canvy_2->SetGridy();

   canvy_2->SetLeftMargin( L/W );
   canvy_2->SetRightMargin( R/W );
   canvy_2->SetTopMargin( T/H );
   canvy_2->SetBottomMargin( B/H * 2.6 );
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   
   TH1D *thirdJetEta_data_jetSel_emu__12 = new TH1D("thirdJetEta_data_jetSel_emu__12","",25,0,5);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(0,1.022576);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(1,0.8862092);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(2,0.9385398);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(3,1.0164);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(4,0.9908583);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(5,1.025244);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(6,0.9566561);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(7,1.056185);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(8,0.9098319);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(9,0.9799789);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(10,1.014043);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(11,0.8818584);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(12,1.023796);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(13,1.011578);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(14,0.9009532);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(15,1.272973);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(16,0.8898109);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(17,0.8160442);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(18,0.9269726);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(19,0.8290227);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(20,0.9061954);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(21,1.027709);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(22,1.656763);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(23,0.8040734);
   thirdJetEta_data_jetSel_emu__12->SetBinContent(24,0.9336713);
   thirdJetEta_data_jetSel_emu__12->SetBinError(0,0.0248822);
   thirdJetEta_data_jetSel_emu__12->SetBinError(1,0.07519354);
   thirdJetEta_data_jetSel_emu__12->SetBinError(2,0.07908766);
   thirdJetEta_data_jetSel_emu__12->SetBinError(3,0.08318974);
   thirdJetEta_data_jetSel_emu__12->SetBinError(4,0.08296073);
   thirdJetEta_data_jetSel_emu__12->SetBinError(5,0.09118976);
   thirdJetEta_data_jetSel_emu__12->SetBinError(6,0.08692384);
   thirdJetEta_data_jetSel_emu__12->SetBinError(7,0.0996472);
   thirdJetEta_data_jetSel_emu__12->SetBinError(8,0.0912183);
   thirdJetEta_data_jetSel_emu__12->SetBinError(9,0.09824577);
   thirdJetEta_data_jetSel_emu__12->SetBinError(10,0.1152202);
   thirdJetEta_data_jetSel_emu__12->SetBinError(11,0.1073471);
   thirdJetEta_data_jetSel_emu__12->SetBinError(12,0.1226555);
   thirdJetEta_data_jetSel_emu__12->SetBinError(13,0.1386998);
   thirdJetEta_data_jetSel_emu__12->SetBinError(14,0.1148405);
   thirdJetEta_data_jetSel_emu__12->SetBinError(15,0.1969041);
   thirdJetEta_data_jetSel_emu__12->SetBinError(16,0.1729904);
   thirdJetEta_data_jetSel_emu__12->SetBinError(17,0.1419715);
   thirdJetEta_data_jetSel_emu__12->SetBinError(18,0.1857309);
   thirdJetEta_data_jetSel_emu__12->SetBinError(19,0.1922811);
   thirdJetEta_data_jetSel_emu__12->SetBinError(20,0.2502278);
   thirdJetEta_data_jetSel_emu__12->SetBinError(21,0.2987222);
   thirdJetEta_data_jetSel_emu__12->SetBinError(22,0.5400908);
   thirdJetEta_data_jetSel_emu__12->SetBinError(23,0.3599992);
   thirdJetEta_data_jetSel_emu__12->SetBinError(24,0.7495915);
   thirdJetEta_data_jetSel_emu__12->SetMinimum(0.5);
   thirdJetEta_data_jetSel_emu__12->SetMaximum(1.5);
   thirdJetEta_data_jetSel_emu__12->SetEntries(389.3762);
   thirdJetEta_data_jetSel_emu__12->SetDirectory(0);
   thirdJetEta_data_jetSel_emu__12->SetStats(0);
   thirdJetEta_data_jetSel_emu__12->SetFillColor(1);
   thirdJetEta_data_jetSel_emu__12->SetLineWidth(2);
   thirdJetEta_data_jetSel_emu__12->SetLineColor(1); //
   thirdJetEta_data_jetSel_emu__12->SetMarkerStyle(20);
   thirdJetEta_data_jetSel_emu__12->SetMarkerSize(1.6);
   thirdJetEta_data_jetSel_emu__12->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_data_jetSel_emu__12->GetXaxis()->SetNdivisions(506);
   thirdJetEta_data_jetSel_emu__12->GetXaxis()->SetLabelFont(42);
   thirdJetEta_data_jetSel_emu__12->GetXaxis()->SetLabelOffset(0.013);
   thirdJetEta_data_jetSel_emu__12->GetXaxis()->SetLabelSize(0.13);
   thirdJetEta_data_jetSel_emu__12->GetXaxis()->SetTitleSize(0.13);
   thirdJetEta_data_jetSel_emu__12->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_data_jetSel_emu__12->GetXaxis()->SetTitleFont(42);
   thirdJetEta_data_jetSel_emu__12->GetYaxis()->SetTitle("Data/MC");
   thirdJetEta_data_jetSel_emu__12->GetYaxis()->CenterTitle(true);
   thirdJetEta_data_jetSel_emu__12->GetYaxis()->SetNdivisions(506);
   thirdJetEta_data_jetSel_emu__12->GetYaxis()->SetLabelFont(42);
   thirdJetEta_data_jetSel_emu__12->GetYaxis()->SetLabelOffset(0.01);
   thirdJetEta_data_jetSel_emu__12->GetYaxis()->SetLabelSize(0.12);
   thirdJetEta_data_jetSel_emu__12->GetYaxis()->SetTitleSize(0.16);
   thirdJetEta_data_jetSel_emu__12->GetYaxis()->SetTitleOffset(0.3);
   thirdJetEta_data_jetSel_emu__12->GetYaxis()->SetTitleFont(42);
   thirdJetEta_data_jetSel_emu__12->GetZaxis()->SetLabelFont(42);
   thirdJetEta_data_jetSel_emu__12->GetZaxis()->SetLabelSize(0.035);
   thirdJetEta_data_jetSel_emu__12->GetZaxis()->SetTitleSize(0.035);
   thirdJetEta_data_jetSel_emu__12->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_data_jetSel_emu__12->GetZaxis()->SetTitleFont(42);
   thirdJetEta_data_jetSel_emu__12->Draw("e x0, SCAT");
   canvy_2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
//   c1->SetSelected(thirdJetEta_data_jetSel_emu);
   c1->SaveAs("thirdJetEta_jetSel.pdf");
}
