void thirdJetPt_SingleTop_jetSel()
{
//=========Macro generated from canvas: thirdJetPt_SingleTop_jetSel/thirdJetPt_SingleTop_jetSel
//=========  (Wed Aug 21 19:33:17 2019) by ROOT version 6.18/00

   // Set up cavas
   int W = 1280;
   int H = 1024;
   int H_ref = 925;
   int W_ref = 1024;

   // references for T, B, L, R
   float T = 0.08*H_ref;
   float B = 0.12*H_ref;
   float L = 0.12*W_ref;
   float R = 0.04*W_ref;

   TCanvas *c1 = new TCanvas("c1","c1",50,50,W,H);
   c1->cd();
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetLeftMargin( L/W );
   c1->SetRightMargin( R/W );
   c1->SetTopMargin( T/H );
   c1->SetBottomMargin( B/H );
   c1->SetTickx(0);
   c1->SetTicky(0);
  
// ------------>Primitives in pad: canvy_1
   TPad *canvy_1 = new TPad("canvy_1", "newpad",0.01,0.315,0.99,0.99);
   canvy_1->Draw();
   canvy_1->cd();
   canvy_1->SetFillColor(0);
   canvy_1->SetBorderMode(0);

   canvy_1->SetLeftMargin( L/W );
   canvy_1->SetRightMargin( R/W );
   canvy_1->SetTopMargin( T/H );
   canvy_1->SetBottomMargin( B/H * 0.3 );

   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);
   
   THStack *thirdJetPt_SingleTop_jetSel_emu = new THStack();
   thirdJetPt_SingleTop_jetSel_emu->SetName("thirdJetPt_SingleTop_jetSel_emu");
   thirdJetPt_SingleTop_jetSel_emu->SetTitle(";Third jet p_{T} (GeV);Events");
   thirdJetPt_SingleTop_jetSel_emu->SetMaximum(1604.9);
   
   TH1F *thirdJetPt_SingleTop_jetSel_emu_stack_4 = new TH1F("thirdJetPt_SingleTop_jetSel_emu_stack_4","Third Jet p_{T}",35,0,300);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->SetMinimum(0);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->SetMaximum(1685.145);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->SetDirectory(0);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->SetStats(0);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->SetLineStyle(0);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->SetLineWidth(0);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->SetMarkerStyle(20);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_SingleTop_jetSel_emu_stack_4->GetXaxis()->SetNdivisions(506);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->GetXaxis()->SetLabelFont(42);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->GetXaxis()->SetLabelOffset(999);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->GetXaxis()->SetLabelSize(0.05);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->GetXaxis()->SetTitleSize(0.08);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->GetXaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->GetYaxis()->SetTitle("Events");
   thirdJetPt_SingleTop_jetSel_emu_stack_4->GetYaxis()->SetNdivisions(506);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->GetYaxis()->SetLabelFont(42);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->GetYaxis()->SetLabelOffset(0.01);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->GetYaxis()->SetLabelSize(0.062);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->GetYaxis()->SetTitleSize(0.08);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->GetYaxis()->SetTitleOffset(0.6336);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->GetYaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->GetZaxis()->SetLabelFont(42);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->GetZaxis()->SetLabelOffset(0.007);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->GetZaxis()->SetLabelSize(0.05);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->GetZaxis()->SetTitleSize(0.08);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_SingleTop_jetSel_emu_stack_4->GetZaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_jetSel_emu->SetHistogram(thirdJetPt_SingleTop_jetSel_emu_stack_4);
   
   
   TH1D *thirdJetPt_tZq_jetSel_emu_stack_1 = new TH1D("thirdJetPt_tZq_jetSel_emu_stack_1","thirdJetPt_tZq_jetSel_emu",35,0,300);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(4,0.04182906);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(5,0.1869793);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(6,0.2139579);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(7,0.1711855);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(8,0.1508981);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(9,0.0814419);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(10,0.0704532);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(11,0.03128914);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(12,0.04276019);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(13,0.03127828);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(14,0.01690518);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(15,0.01151509);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(16,0.02013412);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(17,0.009178782);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(18,0.006462051);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(19,0.009194994);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(20,0.004354203);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(21,0.001840204);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(22,0.0007506855);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(23,-0.0008612997);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(24,0.001642453);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(25,0.002351203);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(26,0.001497534);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(27,0.0007234371);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(28,0.000283811);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(30,-2.908468e-05);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(31,-0.0007213533);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(33,-6.054208e-05);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(35,-0.002033224);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetBinContent(36,0.0002917828);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetEntries(6672);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ffff00");
   thirdJetPt_tZq_jetSel_emu_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   thirdJetPt_tZq_jetSel_emu_stack_1->SetLineColor(ci);
   thirdJetPt_tZq_jetSel_emu_stack_1->SetLineWidth(0);
   thirdJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetLabelFont(42);
   thirdJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetLabelSize(0.035);
   thirdJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleSize(0.035);
   thirdJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_tZq_jetSel_emu_stack_1->GetXaxis()->SetTitleFont(42);
   thirdJetPt_tZq_jetSel_emu_stack_1->GetYaxis()->SetLabelFont(42);
   thirdJetPt_tZq_jetSel_emu_stack_1->GetYaxis()->SetLabelSize(0.035);
   thirdJetPt_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleSize(0.035);
   thirdJetPt_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleOffset(1);
   thirdJetPt_tZq_jetSel_emu_stack_1->GetYaxis()->SetTitleFont(42);
   thirdJetPt_tZq_jetSel_emu_stack_1->GetZaxis()->SetLabelFont(42);
   thirdJetPt_tZq_jetSel_emu_stack_1->GetZaxis()->SetLabelSize(0.035);
   thirdJetPt_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleSize(0.035);
   thirdJetPt_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_tZq_jetSel_emu_stack_1->GetZaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_jetSel_emu->Add(thirdJetPt_tZq_jetSel_emu_stack_1,"");
   
   TH1D *thirdJetPt_ttV_jetSel_emu_stack_2 = new TH1D("thirdJetPt_ttV_jetSel_emu_stack_2","thirdJetPt_ttV_jetSel_emu",35,0,300);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(4,1.227125);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(5,7.114556);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(6,9.157066);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(7,9.171879);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(8,7.945175);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(9,5.972726);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(10,4.39973);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(11,2.626155);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(12,1.59934);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(13,2.138859);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(14,1.632485);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(15,0.7946147);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(16,0.9136154);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(17,0.4950429);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(18,0.4992737);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(19,0.2449153);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(20,0.1122046);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(21,0.1175371);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(22,0.1501798);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(23,0.1428175);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(24,0.03198548);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(25,0.03857649);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(26,0.03037358);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(27,0.01120517);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(28,0.004834883);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(29,0.02097097);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(30,0.009538667);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(31,0.01951653);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(32,0.003200232);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(33,0.004954927);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(34,-0.06304573);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(35,0.001313412);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetBinContent(36,-0.04527903);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetEntries(29408);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#00ff00");
   thirdJetPt_ttV_jetSel_emu_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   thirdJetPt_ttV_jetSel_emu_stack_2->SetLineColor(ci);
   thirdJetPt_ttV_jetSel_emu_stack_2->SetLineWidth(0);
   thirdJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetLabelFont(42);
   thirdJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetLabelSize(0.035);
   thirdJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleSize(0.035);
   thirdJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_ttV_jetSel_emu_stack_2->GetXaxis()->SetTitleFont(42);
   thirdJetPt_ttV_jetSel_emu_stack_2->GetYaxis()->SetLabelFont(42);
   thirdJetPt_ttV_jetSel_emu_stack_2->GetYaxis()->SetLabelSize(0.035);
   thirdJetPt_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleSize(0.035);
   thirdJetPt_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleOffset(1);
   thirdJetPt_ttV_jetSel_emu_stack_2->GetYaxis()->SetTitleFont(42);
   thirdJetPt_ttV_jetSel_emu_stack_2->GetZaxis()->SetLabelFont(42);
   thirdJetPt_ttV_jetSel_emu_stack_2->GetZaxis()->SetLabelSize(0.035);
   thirdJetPt_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleSize(0.035);
   thirdJetPt_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_ttV_jetSel_emu_stack_2->GetZaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_jetSel_emu->Add(thirdJetPt_ttV_jetSel_emu_stack_2,"");
   
   TH1D *thirdJetPt_wJets_jetSel_emu_stack_3 = new TH1D("thirdJetPt_wJets_jetSel_emu_stack_3","thirdJetPt_wJets_jetSel_emu",35,0,300);
   thirdJetPt_wJets_jetSel_emu_stack_3->SetBinContent(8,12.53387);
   thirdJetPt_wJets_jetSel_emu_stack_3->SetBinContent(30,13.42844);
   thirdJetPt_wJets_jetSel_emu_stack_3->SetEntries(2);
   thirdJetPt_wJets_jetSel_emu_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   thirdJetPt_wJets_jetSel_emu_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#cccccc");
   thirdJetPt_wJets_jetSel_emu_stack_3->SetLineColor(ci);
   thirdJetPt_wJets_jetSel_emu_stack_3->SetLineWidth(0);
   thirdJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetLabelFont(42);
   thirdJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetLabelSize(0.035);
   thirdJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleSize(0.035);
   thirdJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_wJets_jetSel_emu_stack_3->GetXaxis()->SetTitleFont(42);
   thirdJetPt_wJets_jetSel_emu_stack_3->GetYaxis()->SetLabelFont(42);
   thirdJetPt_wJets_jetSel_emu_stack_3->GetYaxis()->SetLabelSize(0.035);
   thirdJetPt_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleSize(0.035);
   thirdJetPt_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleOffset(1);
   thirdJetPt_wJets_jetSel_emu_stack_3->GetYaxis()->SetTitleFont(42);
   thirdJetPt_wJets_jetSel_emu_stack_3->GetZaxis()->SetLabelFont(42);
   thirdJetPt_wJets_jetSel_emu_stack_3->GetZaxis()->SetLabelSize(0.035);
   thirdJetPt_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleSize(0.035);
   thirdJetPt_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_wJets_jetSel_emu_stack_3->GetZaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_jetSel_emu->Add(thirdJetPt_wJets_jetSel_emu_stack_3,"");
   
   TH1D *thirdJetPt_VVV_jetSel_emu_stack_4 = new TH1D("thirdJetPt_VVV_jetSel_emu_stack_4","thirdJetPt_VVV_jetSel_emu",35,0,300);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(4,0.1178055);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(5,0.5803863);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(6,0.8418474);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(7,0.3848793);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(8,0.3306973);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(9,0.2934405);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(10,0.2210836);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(11,0.1737189);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(12,0.1579055);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(13,0.127931);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(14,0.0293509);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(15,0.0105937);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(16,0.1388141);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(17,0.03273001);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(18,0.03046469);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(19,0.05595727);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(21,0.01001821);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(22,0.0318951);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(23,0.0288043);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(24,0.02501547);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(25,0.02511566);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(29,0.009105003);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetBinContent(32,0.02679223);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetEntries(147);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#00ffff");
   thirdJetPt_VVV_jetSel_emu_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   thirdJetPt_VVV_jetSel_emu_stack_4->SetLineColor(ci);
   thirdJetPt_VVV_jetSel_emu_stack_4->SetLineWidth(0);
   thirdJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetLabelFont(42);
   thirdJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetLabelSize(0.035);
   thirdJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleSize(0.035);
   thirdJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_VVV_jetSel_emu_stack_4->GetXaxis()->SetTitleFont(42);
   thirdJetPt_VVV_jetSel_emu_stack_4->GetYaxis()->SetLabelFont(42);
   thirdJetPt_VVV_jetSel_emu_stack_4->GetYaxis()->SetLabelSize(0.035);
   thirdJetPt_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleSize(0.035);
   thirdJetPt_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleOffset(1);
   thirdJetPt_VVV_jetSel_emu_stack_4->GetYaxis()->SetTitleFont(42);
   thirdJetPt_VVV_jetSel_emu_stack_4->GetZaxis()->SetLabelFont(42);
   thirdJetPt_VVV_jetSel_emu_stack_4->GetZaxis()->SetLabelSize(0.035);
   thirdJetPt_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleSize(0.035);
   thirdJetPt_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_VVV_jetSel_emu_stack_4->GetZaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_jetSel_emu->Add(thirdJetPt_VVV_jetSel_emu_stack_4,"");
   
   TH1D *thirdJetPt_VV_jetSel_emu_stack_5 = new TH1D("thirdJetPt_VV_jetSel_emu_stack_5","thirdJetPt_VV_jetSel_emu",35,0,300);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(4,3.945077);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(5,15.55369);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(6,12.71247);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(7,9.992389);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(8,6.956593);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(9,2.80884);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(10,1.83248);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(11,1.233673);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(12,1.496659);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(13,1.399682);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(14,0.8870393);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(15,0.5527591);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(16,0.7591634);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(17,0.2065917);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(18,0.1571269);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(19,0.003226639);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(20,-0.006848725);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(21,0.0126204);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(22,0.0160921);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(23,0.0004282395);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(24,0.1624555);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(26,0.1724581);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(31,0.01250403);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(34,0.0145952);
   thirdJetPt_VV_jetSel_emu_stack_5->SetBinContent(36,0.09072468);
   thirdJetPt_VV_jetSel_emu_stack_5->SetEntries(858);
   thirdJetPt_VV_jetSel_emu_stack_5->SetDirectory(0);

   ci = TColor::GetColor("#ff9933");
   thirdJetPt_VV_jetSel_emu_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#ff9933");
   thirdJetPt_VV_jetSel_emu_stack_5->SetLineColor(ci);
   thirdJetPt_VV_jetSel_emu_stack_5->SetLineWidth(0);
   thirdJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetLabelFont(42);
   thirdJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetLabelSize(0.035);
   thirdJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleSize(0.035);
   thirdJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_VV_jetSel_emu_stack_5->GetXaxis()->SetTitleFont(42);
   thirdJetPt_VV_jetSel_emu_stack_5->GetYaxis()->SetLabelFont(42);
   thirdJetPt_VV_jetSel_emu_stack_5->GetYaxis()->SetLabelSize(0.035);
   thirdJetPt_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleSize(0.035);
   thirdJetPt_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleOffset(1);
   thirdJetPt_VV_jetSel_emu_stack_5->GetYaxis()->SetTitleFont(42);
   thirdJetPt_VV_jetSel_emu_stack_5->GetZaxis()->SetLabelFont(42);
   thirdJetPt_VV_jetSel_emu_stack_5->GetZaxis()->SetLabelSize(0.035);
   thirdJetPt_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleSize(0.035);
   thirdJetPt_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_VV_jetSel_emu_stack_5->GetZaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_jetSel_emu->Add(thirdJetPt_VV_jetSel_emu_stack_5,"");
   
   TH1D *thirdJetPt_SingleTop_jetSel_emu_stack_6 = new TH1D("thirdJetPt_SingleTop_jetSel_emu_stack_6","thirdJetPt_SingleTop_jetSel_emu",35,0,300);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(4,17.7163);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(5,67.31834);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(6,57.97513);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(7,36.81454);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(8,31.38222);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(9,19.08873);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(10,14.4846);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(11,8.970663);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(12,7.614893);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(13,4.089063);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(14,2.199119);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(15,2.598838);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(16,2.832329);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(17,1.82723);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(18,1.633176);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(19,0.2209408);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(20,0.2033239);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(21,0.845058);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(24,0.5811066);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(25,0.1841838);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(26,0.1787892);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(27,0.2152545);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(28,0.08868854);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(29,0.1822402);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(32,0.0007233207);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(34,0.1792295);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetBinContent(36,0.7961821);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetEntries(2806);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetDirectory(0);

   ci = TColor::GetColor("#ff00ff");
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetLineColor(ci);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->SetLineWidth(0);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetLabelFont(42);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetLabelSize(0.035);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleSize(0.035);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->GetXaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetLabelFont(42);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetLabelSize(0.035);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleSize(0.035);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleOffset(1);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->GetYaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetLabelFont(42);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetLabelSize(0.035);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleSize(0.035);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_SingleTop_jetSel_emu_stack_6->GetZaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_jetSel_emu->Add(thirdJetPt_SingleTop_jetSel_emu_stack_6,"");
   
   TH1D *thirdJetPt_tt_jetSel_emu_stack_7 = new TH1D("thirdJetPt_tt_jetSel_emu_stack_7","thirdJetPt_tt_jetSel_emu",35,0,300);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(4,306.2359);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(5,1304.874);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(6,1296.869);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(7,995.0638);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(8,710.215);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(9,494.3071);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(10,324.0985);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(11,235.8035);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(12,156.9633);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(13,123.6068);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(14,73.9134);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(15,59.79199);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(16,41.42944);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(17,27.43916);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(18,24.32312);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(19,15.76461);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(20,10.45442);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(21,7.765385);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(22,7.277351);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(23,4.167105);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(24,4.265794);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(25,1.8581);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(26,1.726315);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(27,1.610987);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(28,0.9027192);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(29,1.57425);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(30,1.046235);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(31,1.024864);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(32,0.3004476);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(33,0.6236004);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(35,1.173925);
   thirdJetPt_tt_jetSel_emu_stack_7->SetBinContent(36,2.04829);
   thirdJetPt_tt_jetSel_emu_stack_7->SetEntries(19867);
   thirdJetPt_tt_jetSel_emu_stack_7->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   thirdJetPt_tt_jetSel_emu_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   thirdJetPt_tt_jetSel_emu_stack_7->SetLineColor(ci);
   thirdJetPt_tt_jetSel_emu_stack_7->SetLineWidth(0);
   thirdJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetLabelFont(42);
   thirdJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetLabelSize(0.035);
   thirdJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleSize(0.035);
   thirdJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_tt_jetSel_emu_stack_7->GetXaxis()->SetTitleFont(42);
   thirdJetPt_tt_jetSel_emu_stack_7->GetYaxis()->SetLabelFont(42);
   thirdJetPt_tt_jetSel_emu_stack_7->GetYaxis()->SetLabelSize(0.035);
   thirdJetPt_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleSize(0.035);
   thirdJetPt_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleOffset(1);
   thirdJetPt_tt_jetSel_emu_stack_7->GetYaxis()->SetTitleFont(42);
   thirdJetPt_tt_jetSel_emu_stack_7->GetZaxis()->SetLabelFont(42);
   thirdJetPt_tt_jetSel_emu_stack_7->GetZaxis()->SetLabelSize(0.035);
   thirdJetPt_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleSize(0.035);
   thirdJetPt_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_tt_jetSel_emu_stack_7->GetZaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_jetSel_emu->Add(thirdJetPt_tt_jetSel_emu_stack_7,"");
   
   TH1D *thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8 = new TH1D("thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8","thirdJetPt_zPlusJetsMadgraph_jetSel_emu",35,0,300);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(4,4.430649);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(5,2.921735);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(6,2.930506);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(7,1.422358);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(8,3.032841);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(10,1.500213);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetBinContent(11,1.431985);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetEntries(12);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetLineColor(ci);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->SetLineWidth(0);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetLabelFont(42);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetLabelSize(0.035);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleSize(0.035);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetXaxis()->SetTitleFont(42);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetLabelFont(42);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetLabelSize(0.035);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleSize(0.035);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleOffset(1);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetYaxis()->SetTitleFont(42);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetLabelFont(42);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetLabelSize(0.035);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleSize(0.035);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8->GetZaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_jetSel_emu->Add(thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8,"");
   thirdJetPt_SingleTop_jetSel_emu->Draw("");
   
   TH1D *thirdJetPt_data_jetSel_emu__10 = new TH1D("thirdJetPt_data_jetSel_emu__10","thirdJetPt_data_jetSel_emu",35,0,300);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(4,310);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(5,1423);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(6,1459);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(7,1111);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(8,723);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(9,524);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(10,342);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(11,245);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(12,156);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(13,116);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(14,72);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(15,46);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(16,39);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(17,23);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(18,23);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(19,10);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(20,12);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(21,4);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(22,11);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(23,4);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(24,2);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(25,3);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(26,2);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(27,1);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(30,1);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(31,1);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(32,1);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(34,1);
   thirdJetPt_data_jetSel_emu__10->SetBinContent(36,3);
   thirdJetPt_data_jetSel_emu__10->SetEntries(6668);
   thirdJetPt_data_jetSel_emu__10->SetDirectory(0);
   thirdJetPt_data_jetSel_emu__10->SetFillColor(1);
   thirdJetPt_data_jetSel_emu__10->SetLineWidth(2);
   thirdJetPt_data_jetSel_emu__10->SetLineColor(1); //
   thirdJetPt_data_jetSel_emu__10->SetMarkerStyle(20);
   thirdJetPt_data_jetSel_emu__10->SetMarkerSize(1.4);
   thirdJetPt_data_jetSel_emu__10->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_data_jetSel_emu__10->GetXaxis()->SetLabelFont(42);
   thirdJetPt_data_jetSel_emu__10->GetXaxis()->SetLabelSize(0.035);
   thirdJetPt_data_jetSel_emu__10->GetXaxis()->SetTitleSize(0.035);
   thirdJetPt_data_jetSel_emu__10->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_data_jetSel_emu__10->GetXaxis()->SetTitleFont(42);
   thirdJetPt_data_jetSel_emu__10->GetYaxis()->SetLabelFont(42);
   thirdJetPt_data_jetSel_emu__10->GetYaxis()->SetLabelSize(0.035);
   thirdJetPt_data_jetSel_emu__10->GetYaxis()->SetTitleSize(0.035);
   thirdJetPt_data_jetSel_emu__10->GetYaxis()->SetTitleOffset(1);
   thirdJetPt_data_jetSel_emu__10->GetYaxis()->SetTitleFont(42);
   thirdJetPt_data_jetSel_emu__10->GetZaxis()->SetLabelFont(42);
   thirdJetPt_data_jetSel_emu__10->GetZaxis()->SetLabelSize(0.035);
   thirdJetPt_data_jetSel_emu__10->GetZaxis()->SetTitleSize(0.035);
   thirdJetPt_data_jetSel_emu__10->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_data_jetSel_emu__10->GetZaxis()->SetTitleFont(42);
   thirdJetPt_data_jetSel_emu__10->Draw("e x0, same");
   
   TLegend *leg = new TLegend(0.78,0.42,0.98,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("thirdJetPt_zPlusJetsMadgraph_jetSel_emu_stack_8","Z+jets (LO)","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetPt_tt_jetSel_emu_stack_7","t#bar{t}","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetPt_SingleTop_jetSel_emu_stack_6","Single top","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetPt_VV_jetSel_emu_stack_5","VV","f");

   ci = TColor::GetColor("#ff9933");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetPt_VVV_jetSel_emu_stack_4","VVV","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetPt_wJets_jetSel_emu_stack_3","W+jets","f");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetPt_ttV_jetSel_emu_stack_2","t#bar{t}V","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetPt_tZq_jetSel_emu_stack_1","tZq","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetPt_data_jetSel_emu","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.4);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.968,0.9429101,"35.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06792969);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.096,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.05419922);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16899,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.04119141);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *thirdJetPt_SingleTop_jetSel_emu__11 = new TH1F("thirdJetPt_SingleTop_jetSel_emu__11","Third Jet p_{T}",35,0,300);
   thirdJetPt_SingleTop_jetSel_emu__11->SetMinimum(0);
   thirdJetPt_SingleTop_jetSel_emu__11->SetMaximum(1685.145);
   thirdJetPt_SingleTop_jetSel_emu__11->SetDirectory(0);
   thirdJetPt_SingleTop_jetSel_emu__11->SetStats(0);
   thirdJetPt_SingleTop_jetSel_emu__11->SetLineStyle(0);
   thirdJetPt_SingleTop_jetSel_emu__11->SetLineWidth(0);
   thirdJetPt_SingleTop_jetSel_emu__11->SetMarkerStyle(20);
   thirdJetPt_SingleTop_jetSel_emu__11->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_SingleTop_jetSel_emu__11->GetXaxis()->SetNdivisions(506);
   thirdJetPt_SingleTop_jetSel_emu__11->GetXaxis()->SetLabelFont(42);
   thirdJetPt_SingleTop_jetSel_emu__11->GetXaxis()->SetLabelOffset(999);
   thirdJetPt_SingleTop_jetSel_emu__11->GetXaxis()->SetLabelSize(0.05);
   thirdJetPt_SingleTop_jetSel_emu__11->GetXaxis()->SetTitleSize(0.08);
   thirdJetPt_SingleTop_jetSel_emu__11->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_SingleTop_jetSel_emu__11->GetXaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_jetSel_emu__11->GetYaxis()->SetTitle("Events");
   thirdJetPt_SingleTop_jetSel_emu__11->GetYaxis()->SetNdivisions(506);
   thirdJetPt_SingleTop_jetSel_emu__11->GetYaxis()->SetLabelFont(42);
   thirdJetPt_SingleTop_jetSel_emu__11->GetYaxis()->SetLabelOffset(0.01);
   thirdJetPt_SingleTop_jetSel_emu__11->GetYaxis()->SetLabelSize(0.062);
   thirdJetPt_SingleTop_jetSel_emu__11->GetYaxis()->SetTitleSize(0.08);
   thirdJetPt_SingleTop_jetSel_emu__11->GetYaxis()->SetTitleOffset(0.6336);
   thirdJetPt_SingleTop_jetSel_emu__11->GetYaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_jetSel_emu__11->GetZaxis()->SetLabelFont(42);
   thirdJetPt_SingleTop_jetSel_emu__11->GetZaxis()->SetLabelOffset(0.007);
   thirdJetPt_SingleTop_jetSel_emu__11->GetZaxis()->SetLabelSize(0.05);
   thirdJetPt_SingleTop_jetSel_emu__11->GetZaxis()->SetTitleSize(0.08);
   thirdJetPt_SingleTop_jetSel_emu__11->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_SingleTop_jetSel_emu__11->GetZaxis()->SetTitleFont(42);
   thirdJetPt_SingleTop_jetSel_emu__11->Draw("sameaxis");
   
   TPaveText *pt = new TPaveText(0.4353068,0.9203237,0.5646932,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Third Jet p_{T}");
   pt->Draw();
   canvy_1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: canvy_2
   TPad *canvy_2 = new TPad("canvy_2", "newpad2",0.01,0.01,0.99,0.322);
   canvy_2->Draw();
   canvy_2->cd();
   canvy_2->SetFillColor(0);
   canvy_2->SetBorderMode(0);
   canvy_2->SetGridy();

   canvy_2->SetLeftMargin( L/W );
   canvy_2->SetRightMargin( R/W );
   canvy_2->SetTopMargin( T/H );
   canvy_2->SetBottomMargin( B/H * 2.6 );
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   
   TH1D *thirdJetPt_data_jetSel_emu__12 = new TH1D("thirdJetPt_data_jetSel_emu__12","",35,0,300);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(4,0.9289372);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(5,1.017483);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(6,1.056711);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(7,1.05506);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(8,0.935865);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(9,1.002771);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(10,0.9867081);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(11,0.9789389);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(12,0.9292635);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(13,0.8828438);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(14,0.915119);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(15,0.7214519);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(16,0.8461064);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(17,0.7664129);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(18,0.8630517);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(19,0.6135402);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(20,1.114469);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(21,0.4570145);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(22,1.471322);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(23,0.9220214);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(24,0.394633);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(25,1.422929);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(26,0.948122);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(27,0.5440192);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(30,0.06904082);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(31,0.9468233);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(32,3.019657);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(34,7.646487);
   thirdJetPt_data_jetSel_emu__12->SetBinContent(36,1.037987);
   thirdJetPt_data_jetSel_emu__12->SetBinError(4,0.07327648);
   thirdJetPt_data_jetSel_emu__12->SetBinError(5,0.03831153);
   thirdJetPt_data_jetSel_emu__12->SetBinError(6,0.03967482);
   thirdJetPt_data_jetSel_emu__12->SetBinError(7,0.04537663);
   thirdJetPt_data_jetSel_emu__12->SetBinError(8,0.04842633);
   thirdJetPt_data_jetSel_emu__12->SetBinError(9,0.06199427);
   thirdJetPt_data_jetSel_emu__12->SetBinError(10,0.0752043);
   thirdJetPt_data_jetSel_emu__12->SetBinError(11,0.08798097);
   thirdJetPt_data_jetSel_emu__12->SetBinError(12,0.1033409);
   thirdJetPt_data_jetSel_emu__12->SetBinError(13,0.1124766);
   thirdJetPt_data_jetSel_emu__12->SetBinError(14,0.1492482);
   thirdJetPt_data_jetSel_emu__12->SetBinError(15,0.1395648);
   thirdJetPt_data_jetSel_emu__12->SetBinError(16,0.1840861);
   thirdJetPt_data_jetSel_emu__12->SetBinError(17,0.2123954);
   thirdJetPt_data_jetSel_emu__12->SetBinError(18,0.2456322);
   thirdJetPt_data_jetSel_emu__12->SetBinError(19,0.2464523);
   thirdJetPt_data_jetSel_emu__12->SetBinError(20,0.4678193);
   thirdJetPt_data_jetSel_emu__12->SetBinError(21,0.2758239);
   thirdJetPt_data_jetSel_emu__12->SetBinError(22,0.6973907);
   thirdJetPt_data_jetSel_emu__12->SetBinError(23,0.6391314);
   thirdJetPt_data_jetSel_emu__12->SetBinError(24,0.3295402);
   thirdJetPt_data_jetSel_emu__12->SetBinError(25,1.278772);
   thirdJetPt_data_jetSel_emu__12->SetBinError(26,0.9357445);
   thirdJetPt_data_jetSel_emu__12->SetBinError(27,0.6759904);
   thirdJetPt_data_jetSel_emu__12->SetBinError(30,0.07138436);
   thirdJetPt_data_jetSel_emu__12->SetBinError(31,1.321089);
   thirdJetPt_data_jetSel_emu__12->SetBinError(32,6.054136);
   thirdJetPt_data_jetSel_emu__12->SetBinError(34,22.48443);
   thirdJetPt_data_jetSel_emu__12->SetBinError(36,0.8555237);
   thirdJetPt_data_jetSel_emu__12->SetMinimum(0.5);
   thirdJetPt_data_jetSel_emu__12->SetMaximum(1.5);
   thirdJetPt_data_jetSel_emu__12->SetEntries(2.04071);
   thirdJetPt_data_jetSel_emu__12->SetDirectory(0);
   thirdJetPt_data_jetSel_emu__12->SetStats(0);
   thirdJetPt_data_jetSel_emu__12->SetFillColor(1);
   thirdJetPt_data_jetSel_emu__12->SetLineWidth(2);
   thirdJetPt_data_jetSel_emu__12->SetLineColor(1); //
   thirdJetPt_data_jetSel_emu__12->SetMarkerStyle(20);
   thirdJetPt_data_jetSel_emu__12->SetMarkerSize(1.6);
   thirdJetPt_data_jetSel_emu__12->GetXaxis()->SetTitle("Third jet p_{T} (GeV)");
   thirdJetPt_data_jetSel_emu__12->GetXaxis()->SetNdivisions(506);
   thirdJetPt_data_jetSel_emu__12->GetXaxis()->SetLabelFont(42);
   thirdJetPt_data_jetSel_emu__12->GetXaxis()->SetLabelOffset(0.013);
   thirdJetPt_data_jetSel_emu__12->GetXaxis()->SetLabelSize(0.13);
   thirdJetPt_data_jetSel_emu__12->GetXaxis()->SetTitleSize(0.13);
   thirdJetPt_data_jetSel_emu__12->GetXaxis()->SetTitleOffset(1);
   thirdJetPt_data_jetSel_emu__12->GetXaxis()->SetTitleFont(42);
   thirdJetPt_data_jetSel_emu__12->GetYaxis()->SetTitle("Data/MC");
   thirdJetPt_data_jetSel_emu__12->GetYaxis()->CenterTitle(true);
   thirdJetPt_data_jetSel_emu__12->GetYaxis()->SetNdivisions(506);
   thirdJetPt_data_jetSel_emu__12->GetYaxis()->SetLabelFont(42);
   thirdJetPt_data_jetSel_emu__12->GetYaxis()->SetLabelOffset(0.01);
   thirdJetPt_data_jetSel_emu__12->GetYaxis()->SetLabelSize(0.12);
   thirdJetPt_data_jetSel_emu__12->GetYaxis()->SetTitleSize(0.16);
   thirdJetPt_data_jetSel_emu__12->GetYaxis()->SetTitleOffset(0.3);
   thirdJetPt_data_jetSel_emu__12->GetYaxis()->SetTitleFont(42);
   thirdJetPt_data_jetSel_emu__12->GetZaxis()->SetLabelFont(42);
   thirdJetPt_data_jetSel_emu__12->GetZaxis()->SetLabelSize(0.035);
   thirdJetPt_data_jetSel_emu__12->GetZaxis()->SetTitleSize(0.035);
   thirdJetPt_data_jetSel_emu__12->GetZaxis()->SetTitleOffset(1);
   thirdJetPt_data_jetSel_emu__12->GetZaxis()->SetTitleFont(42);
   thirdJetPt_data_jetSel_emu__12->Draw("e x0, SCAT");
   canvy_2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
//   c1->SetSelected(thirdJetPt_data_jetSel_emu);
   c1->SaveAs("thirdJetPt_jetSel.pdf");
}
