void thirdJetEta_SingleTop_wMass()
{
//=========Macro generated from canvas: thirdJetEta_SingleTop_wMass/thirdJetEta_SingleTop_wMass
//=========  (Wed Aug 21 19:46:41 2019) by ROOT version 6.18/00

   // Set up cavas
   int W = 1280;
   int H = 1024;
   int H_ref = 925;
   int W_ref = 1024;

   // references for T, B, L, R
   float T = 0.08*H_ref;
   float B = 0.12*H_ref;
   float L = 0.12*W_ref;
   float R = 0.04*W_ref;

   TCanvas *c1 = new TCanvas("c1","c1",50,50,W,H);
   c1->cd();
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetLeftMargin( L/W );
   c1->SetRightMargin( R/W );
   c1->SetTopMargin( T/H );
   c1->SetBottomMargin( B/H );
   c1->SetTickx(0);
   c1->SetTicky(0);
  
// ------------>Primitives in pad: canvy_1
   TPad *canvy_1 = new TPad("canvy_1", "newpad",0.01,0.315,0.99,0.99);
   canvy_1->Draw();
   canvy_1->cd();
   canvy_1->SetFillColor(0);
   canvy_1->SetBorderMode(0);

   canvy_1->SetLeftMargin( L/W );
   canvy_1->SetRightMargin( R/W );
   canvy_1->SetTopMargin( T/H );
   canvy_1->SetBottomMargin( B/H * 0.3 );

   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);
   
   THStack *thirdJetEta_SingleTop_wMass_emu = new THStack();
   thirdJetEta_SingleTop_wMass_emu->SetName("thirdJetEta_SingleTop_wMass_emu");
   thirdJetEta_SingleTop_wMass_emu->SetTitle("Third Jet #eta;Third Jet #eta;Events");
   thirdJetEta_SingleTop_wMass_emu->SetMaximum(148.5);
   
   TH1F *thirdJetEta_SingleTop_wMass_emu_stack_4 = new TH1F("thirdJetEta_SingleTop_wMass_emu_stack_4","Third Jet #eta",25,0,5);
   thirdJetEta_SingleTop_wMass_emu_stack_4->SetMinimum(0);
   thirdJetEta_SingleTop_wMass_emu_stack_4->SetMaximum(155.925);
   thirdJetEta_SingleTop_wMass_emu_stack_4->SetDirectory(0);
   thirdJetEta_SingleTop_wMass_emu_stack_4->SetStats(0);
   thirdJetEta_SingleTop_wMass_emu_stack_4->SetLineStyle(0);
   thirdJetEta_SingleTop_wMass_emu_stack_4->SetLineWidth(0);
   thirdJetEta_SingleTop_wMass_emu_stack_4->SetMarkerStyle(20);
   thirdJetEta_SingleTop_wMass_emu_stack_4->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_SingleTop_wMass_emu_stack_4->GetXaxis()->SetNdivisions(506);
   thirdJetEta_SingleTop_wMass_emu_stack_4->GetXaxis()->SetLabelFont(42);
   thirdJetEta_SingleTop_wMass_emu_stack_4->GetXaxis()->SetLabelOffset(999);
   thirdJetEta_SingleTop_wMass_emu_stack_4->GetXaxis()->SetLabelSize(0.05);
   thirdJetEta_SingleTop_wMass_emu_stack_4->GetXaxis()->SetTitleSize(0.08);
   thirdJetEta_SingleTop_wMass_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_SingleTop_wMass_emu_stack_4->GetXaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_wMass_emu_stack_4->GetYaxis()->SetTitle("Events");
   thirdJetEta_SingleTop_wMass_emu_stack_4->GetYaxis()->SetNdivisions(506);
   thirdJetEta_SingleTop_wMass_emu_stack_4->GetYaxis()->SetLabelFont(42);
   thirdJetEta_SingleTop_wMass_emu_stack_4->GetYaxis()->SetLabelOffset(0.01);
   thirdJetEta_SingleTop_wMass_emu_stack_4->GetYaxis()->SetLabelSize(0.062);
   thirdJetEta_SingleTop_wMass_emu_stack_4->GetYaxis()->SetTitleSize(0.08);
   thirdJetEta_SingleTop_wMass_emu_stack_4->GetYaxis()->SetTitleOffset(0.6336);
   thirdJetEta_SingleTop_wMass_emu_stack_4->GetYaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_wMass_emu_stack_4->GetZaxis()->SetLabelFont(42);
   thirdJetEta_SingleTop_wMass_emu_stack_4->GetZaxis()->SetLabelOffset(0.007);
   thirdJetEta_SingleTop_wMass_emu_stack_4->GetZaxis()->SetLabelSize(0.05);
   thirdJetEta_SingleTop_wMass_emu_stack_4->GetZaxis()->SetTitleSize(0.08);
   thirdJetEta_SingleTop_wMass_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_SingleTop_wMass_emu_stack_4->GetZaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_wMass_emu->SetHistogram(thirdJetEta_SingleTop_wMass_emu_stack_4);
   
   
   TH1D *thirdJetEta_tZq_wMass_emu_stack_1 = new TH1D("thirdJetEta_tZq_wMass_emu_stack_1","thirdJetEta_tZq_wMass_emu",25,0,5);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(0,0.1742014);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(1,0.009930917);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(2,0.01843148);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(3,0.00875455);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(4,0.003764493);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(5,0.01529566);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(6,0.01829411);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(7,0.005509994);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(8,0.01925489);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(9,0.01500354);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(10,0.00602573);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(11,0.01190465);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(12,0.006013596);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(13,0.0006191833);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(14,0.01972233);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(15,0.004780616);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(16,-0.002848561);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(17,-0.001349286);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(18,0.001966584);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(19,0.0005425758);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(20,0.00332718);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(21,0.003133196);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(22,0.0007105176);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(23,0.000698996);
   thirdJetEta_tZq_wMass_emu_stack_1->SetBinContent(24,0.0007201129);
   thirdJetEta_tZq_wMass_emu_stack_1->SetEntries(2170);
   thirdJetEta_tZq_wMass_emu_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ffff00");
   thirdJetEta_tZq_wMass_emu_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   thirdJetEta_tZq_wMass_emu_stack_1->SetLineColor(ci);
   thirdJetEta_tZq_wMass_emu_stack_1->SetLineWidth(0);
   thirdJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetLabelFont(42);
   thirdJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetLabelSize(0.035);
   thirdJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleSize(0.035);
   thirdJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleFont(42);
   thirdJetEta_tZq_wMass_emu_stack_1->GetYaxis()->SetLabelFont(42);
   thirdJetEta_tZq_wMass_emu_stack_1->GetYaxis()->SetLabelSize(0.035);
   thirdJetEta_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleSize(0.035);
   thirdJetEta_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleOffset(1);
   thirdJetEta_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleFont(42);
   thirdJetEta_tZq_wMass_emu_stack_1->GetZaxis()->SetLabelFont(42);
   thirdJetEta_tZq_wMass_emu_stack_1->GetZaxis()->SetLabelSize(0.035);
   thirdJetEta_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleSize(0.035);
   thirdJetEta_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_wMass_emu->Add(thirdJetEta_tZq_wMass_emu_stack_1,"");
   
   TH1D *thirdJetEta_ttV_wMass_emu_stack_2 = new TH1D("thirdJetEta_ttV_wMass_emu_stack_2","thirdJetEta_ttV_wMass_emu",25,0,5);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(0,13.31306);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(1,1.952408);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(2,0.9425328);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(3,2.02874);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(4,1.59501);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(5,1.383506);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(6,0.8894308);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(7,1.13331);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(8,1.109509);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(9,0.8487141);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(10,0.4392597);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(11,0.3024462);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(12,0.4574859);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(13,0.3007419);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(14,0.4469538);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(15,0.314331);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(16,0.04718915);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(17,0.1870652);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(18,0.04813745);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(19,0.05064105);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(20,0.02335573);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(21,0.003562437);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(22,0.05205263);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(23,0.00407123);
   thirdJetEta_ttV_wMass_emu_stack_2->SetBinContent(24,0.005660237);
   thirdJetEta_ttV_wMass_emu_stack_2->SetEntries(14144);
   thirdJetEta_ttV_wMass_emu_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#00ff00");
   thirdJetEta_ttV_wMass_emu_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   thirdJetEta_ttV_wMass_emu_stack_2->SetLineColor(ci);
   thirdJetEta_ttV_wMass_emu_stack_2->SetLineWidth(0);
   thirdJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetLabelFont(42);
   thirdJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetLabelSize(0.035);
   thirdJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleSize(0.035);
   thirdJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleFont(42);
   thirdJetEta_ttV_wMass_emu_stack_2->GetYaxis()->SetLabelFont(42);
   thirdJetEta_ttV_wMass_emu_stack_2->GetYaxis()->SetLabelSize(0.035);
   thirdJetEta_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleSize(0.035);
   thirdJetEta_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleOffset(1);
   thirdJetEta_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleFont(42);
   thirdJetEta_ttV_wMass_emu_stack_2->GetZaxis()->SetLabelFont(42);
   thirdJetEta_ttV_wMass_emu_stack_2->GetZaxis()->SetLabelSize(0.035);
   thirdJetEta_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleSize(0.035);
   thirdJetEta_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_wMass_emu->Add(thirdJetEta_ttV_wMass_emu_stack_2,"");
   
   TH1D *thirdJetEta_wJets_wMass_emu_stack_3 = new TH1D("thirdJetEta_wJets_wMass_emu_stack_3","thirdJetEta_wJets_wMass_emu",25,0,5);
   thirdJetEta_wJets_wMass_emu_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   thirdJetEta_wJets_wMass_emu_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#cccccc");
   thirdJetEta_wJets_wMass_emu_stack_3->SetLineColor(ci);
   thirdJetEta_wJets_wMass_emu_stack_3->SetLineWidth(0);
   thirdJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetLabelFont(42);
   thirdJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetLabelSize(0.035);
   thirdJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleSize(0.035);
   thirdJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleFont(42);
   thirdJetEta_wJets_wMass_emu_stack_3->GetYaxis()->SetLabelFont(42);
   thirdJetEta_wJets_wMass_emu_stack_3->GetYaxis()->SetLabelSize(0.035);
   thirdJetEta_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleSize(0.035);
   thirdJetEta_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleOffset(1);
   thirdJetEta_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleFont(42);
   thirdJetEta_wJets_wMass_emu_stack_3->GetZaxis()->SetLabelFont(42);
   thirdJetEta_wJets_wMass_emu_stack_3->GetZaxis()->SetLabelSize(0.035);
   thirdJetEta_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleSize(0.035);
   thirdJetEta_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_wMass_emu->Add(thirdJetEta_wJets_wMass_emu_stack_3,"");
   
   TH1D *thirdJetEta_VVV_wMass_emu_stack_4 = new TH1D("thirdJetEta_VVV_wMass_emu_stack_4","thirdJetEta_VVV_wMass_emu",25,0,5);
   thirdJetEta_VVV_wMass_emu_stack_4->SetBinContent(0,0.06185096);
   thirdJetEta_VVV_wMass_emu_stack_4->SetBinContent(1,0.03368239);
   thirdJetEta_VVV_wMass_emu_stack_4->SetBinContent(2,0.033447);
   thirdJetEta_VVV_wMass_emu_stack_4->SetBinContent(4,0.03392089);
   thirdJetEta_VVV_wMass_emu_stack_4->SetBinContent(5,0.0318951);
   thirdJetEta_VVV_wMass_emu_stack_4->SetBinContent(6,0.02946448);
   thirdJetEta_VVV_wMass_emu_stack_4->SetEntries(9);
   thirdJetEta_VVV_wMass_emu_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#00ffff");
   thirdJetEta_VVV_wMass_emu_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   thirdJetEta_VVV_wMass_emu_stack_4->SetLineColor(ci);
   thirdJetEta_VVV_wMass_emu_stack_4->SetLineWidth(0);
   thirdJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetLabelFont(42);
   thirdJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetLabelSize(0.035);
   thirdJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleSize(0.035);
   thirdJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleFont(42);
   thirdJetEta_VVV_wMass_emu_stack_4->GetYaxis()->SetLabelFont(42);
   thirdJetEta_VVV_wMass_emu_stack_4->GetYaxis()->SetLabelSize(0.035);
   thirdJetEta_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleSize(0.035);
   thirdJetEta_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleOffset(1);
   thirdJetEta_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleFont(42);
   thirdJetEta_VVV_wMass_emu_stack_4->GetZaxis()->SetLabelFont(42);
   thirdJetEta_VVV_wMass_emu_stack_4->GetZaxis()->SetLabelSize(0.035);
   thirdJetEta_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleSize(0.035);
   thirdJetEta_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_wMass_emu->Add(thirdJetEta_VVV_wMass_emu_stack_4,"");
   
   TH1D *thirdJetEta_VV_wMass_emu_stack_5 = new TH1D("thirdJetEta_VV_wMass_emu_stack_5","thirdJetEta_VV_wMass_emu",25,0,5);
   thirdJetEta_VV_wMass_emu_stack_5->SetBinContent(0,1.919336);
   thirdJetEta_VV_wMass_emu_stack_5->SetBinContent(1,0.003683787);
   thirdJetEta_VV_wMass_emu_stack_5->SetBinContent(2,0.02108473);
   thirdJetEta_VV_wMass_emu_stack_5->SetBinContent(3,0.001022344);
   thirdJetEta_VV_wMass_emu_stack_5->SetBinContent(4,0.005308559);
   thirdJetEta_VV_wMass_emu_stack_5->SetBinContent(5,-0.00400656);
   thirdJetEta_VV_wMass_emu_stack_5->SetBinContent(6,0.002215747);
   thirdJetEta_VV_wMass_emu_stack_5->SetBinContent(8,0.374323);
   thirdJetEta_VV_wMass_emu_stack_5->SetBinContent(9,-0.03099644);
   thirdJetEta_VV_wMass_emu_stack_5->SetBinContent(10,0.1939275);
   thirdJetEta_VV_wMass_emu_stack_5->SetBinContent(11,0.006012922);
   thirdJetEta_VV_wMass_emu_stack_5->SetBinContent(12,-0.01229277);
   thirdJetEta_VV_wMass_emu_stack_5->SetEntries(45);
   thirdJetEta_VV_wMass_emu_stack_5->SetDirectory(0);

   ci = TColor::GetColor("#ff9933");
   thirdJetEta_VV_wMass_emu_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#ff9933");
   thirdJetEta_VV_wMass_emu_stack_5->SetLineColor(ci);
   thirdJetEta_VV_wMass_emu_stack_5->SetLineWidth(0);
   thirdJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetLabelFont(42);
   thirdJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetLabelSize(0.035);
   thirdJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetTitleSize(0.035);
   thirdJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_VV_wMass_emu_stack_5->GetXaxis()->SetTitleFont(42);
   thirdJetEta_VV_wMass_emu_stack_5->GetYaxis()->SetLabelFont(42);
   thirdJetEta_VV_wMass_emu_stack_5->GetYaxis()->SetLabelSize(0.035);
   thirdJetEta_VV_wMass_emu_stack_5->GetYaxis()->SetTitleSize(0.035);
   thirdJetEta_VV_wMass_emu_stack_5->GetYaxis()->SetTitleOffset(1);
   thirdJetEta_VV_wMass_emu_stack_5->GetYaxis()->SetTitleFont(42);
   thirdJetEta_VV_wMass_emu_stack_5->GetZaxis()->SetLabelFont(42);
   thirdJetEta_VV_wMass_emu_stack_5->GetZaxis()->SetLabelSize(0.035);
   thirdJetEta_VV_wMass_emu_stack_5->GetZaxis()->SetTitleSize(0.035);
   thirdJetEta_VV_wMass_emu_stack_5->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_VV_wMass_emu_stack_5->GetZaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_wMass_emu->Add(thirdJetEta_VV_wMass_emu_stack_5,"");
   
   TH1D *thirdJetEta_SingleTop_wMass_emu_stack_6 = new TH1D("thirdJetEta_SingleTop_wMass_emu_stack_6","thirdJetEta_SingleTop_wMass_emu",25,0,5);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(0,51.54118);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(1,4.868685);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(2,3.587012);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(3,6.492906);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(4,2.814599);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(5,3.154632);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(6,4.62088);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(7,3.053224);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(8,2.852435);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(9,3.837124);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(10,2.5379);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(11,2.213261);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(12,1.933143);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(13,2.014524);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(14,2.239118);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(15,2.261651);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(16,1.009015);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(17,1.106616);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(18,0.8954259);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(19,0.3811942);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(20,0.5688955);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(21,0.0007154237);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(22,0.3798805);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetBinContent(23,0.3701055);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetEntries(1034);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetDirectory(0);

   ci = TColor::GetColor("#ff00ff");
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetLineColor(ci);
   thirdJetEta_SingleTop_wMass_emu_stack_6->SetLineWidth(0);
   thirdJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetLabelFont(42);
   thirdJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetLabelSize(0.035);
   thirdJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleSize(0.035);
   thirdJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_wMass_emu_stack_6->GetYaxis()->SetLabelFont(42);
   thirdJetEta_SingleTop_wMass_emu_stack_6->GetYaxis()->SetLabelSize(0.035);
   thirdJetEta_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleSize(0.035);
   thirdJetEta_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleOffset(1);
   thirdJetEta_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_wMass_emu_stack_6->GetZaxis()->SetLabelFont(42);
   thirdJetEta_SingleTop_wMass_emu_stack_6->GetZaxis()->SetLabelSize(0.035);
   thirdJetEta_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleSize(0.035);
   thirdJetEta_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_wMass_emu->Add(thirdJetEta_SingleTop_wMass_emu_stack_6,"");
   
   TH1D *thirdJetEta_tt_wMass_emu_stack_7 = new TH1D("thirdJetEta_tt_wMass_emu_stack_7","thirdJetEta_tt_wMass_emu",25,0,5);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(0,1193.341);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(1,112.8782);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(2,108.2506);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(3,110.8538);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(4,107.6524);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(5,101.5902);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(6,90.47944);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(7,79.9798);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(8,85.80458);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(9,77.91664);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(10,54.66369);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(11,46.4672);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(12,45.36277);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(13,34.70561);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(14,36.89952);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(15,24.21787);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(16,19.93089);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(17,21.20234);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(18,13.65943);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(19,12.73243);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(20,6.666421);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(21,8.451234);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(22,3.681249);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(23,2.773429);
   thirdJetEta_tt_wMass_emu_stack_7->SetBinContent(24,0.6177837);
   thirdJetEta_tt_wMass_emu_stack_7->SetEntries(7802);
   thirdJetEta_tt_wMass_emu_stack_7->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   thirdJetEta_tt_wMass_emu_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   thirdJetEta_tt_wMass_emu_stack_7->SetLineColor(ci);
   thirdJetEta_tt_wMass_emu_stack_7->SetLineWidth(0);
   thirdJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetLabelFont(42);
   thirdJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetLabelSize(0.035);
   thirdJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetTitleSize(0.035);
   thirdJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_tt_wMass_emu_stack_7->GetXaxis()->SetTitleFont(42);
   thirdJetEta_tt_wMass_emu_stack_7->GetYaxis()->SetLabelFont(42);
   thirdJetEta_tt_wMass_emu_stack_7->GetYaxis()->SetLabelSize(0.035);
   thirdJetEta_tt_wMass_emu_stack_7->GetYaxis()->SetTitleSize(0.035);
   thirdJetEta_tt_wMass_emu_stack_7->GetYaxis()->SetTitleOffset(1);
   thirdJetEta_tt_wMass_emu_stack_7->GetYaxis()->SetTitleFont(42);
   thirdJetEta_tt_wMass_emu_stack_7->GetZaxis()->SetLabelFont(42);
   thirdJetEta_tt_wMass_emu_stack_7->GetZaxis()->SetLabelSize(0.035);
   thirdJetEta_tt_wMass_emu_stack_7->GetZaxis()->SetTitleSize(0.035);
   thirdJetEta_tt_wMass_emu_stack_7->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_tt_wMass_emu_stack_7->GetZaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_wMass_emu->Add(thirdJetEta_tt_wMass_emu_stack_7,"");
   
   TH1D *thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8 = new TH1D("thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8","thirdJetEta_zPlusJetsMadgraph_wMass_emu",25,0,5);
   thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->SetLineColor(ci);
   thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->SetLineWidth(0);
   thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetLabelFont(42);
   thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetLabelSize(0.035);
   thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleSize(0.035);
   thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleFont(42);
   thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetLabelFont(42);
   thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetLabelSize(0.035);
   thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleSize(0.035);
   thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleOffset(1);
   thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleFont(42);
   thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetLabelFont(42);
   thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetLabelSize(0.035);
   thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleSize(0.035);
   thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_wMass_emu->Add(thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8,"");
   thirdJetEta_SingleTop_wMass_emu->Draw("");
   
   TH1D *thirdJetEta_data_wMass_emu__10 = new TH1D("thirdJetEta_data_wMass_emu__10","thirdJetEta_data_wMass_emu",25,0,5);
   thirdJetEta_data_wMass_emu__10->SetBinContent(0,1372);
   thirdJetEta_data_wMass_emu__10->SetBinContent(1,104);
   thirdJetEta_data_wMass_emu__10->SetBinContent(2,107);
   thirdJetEta_data_wMass_emu__10->SetBinContent(3,135);
   thirdJetEta_data_wMass_emu__10->SetBinContent(4,130);
   thirdJetEta_data_wMass_emu__10->SetBinContent(5,107);
   thirdJetEta_data_wMass_emu__10->SetBinContent(6,100);
   thirdJetEta_data_wMass_emu__10->SetBinContent(7,92);
   thirdJetEta_data_wMass_emu__10->SetBinContent(8,83);
   thirdJetEta_data_wMass_emu__10->SetBinContent(9,70);
   thirdJetEta_data_wMass_emu__10->SetBinContent(10,66);
   thirdJetEta_data_wMass_emu__10->SetBinContent(11,61);
   thirdJetEta_data_wMass_emu__10->SetBinContent(12,51);
   thirdJetEta_data_wMass_emu__10->SetBinContent(13,26);
   thirdJetEta_data_wMass_emu__10->SetBinContent(14,41);
   thirdJetEta_data_wMass_emu__10->SetBinContent(15,35);
   thirdJetEta_data_wMass_emu__10->SetBinContent(16,14);
   thirdJetEta_data_wMass_emu__10->SetBinContent(17,19);
   thirdJetEta_data_wMass_emu__10->SetBinContent(18,15);
   thirdJetEta_data_wMass_emu__10->SetBinContent(19,15);
   thirdJetEta_data_wMass_emu__10->SetBinContent(20,4);
   thirdJetEta_data_wMass_emu__10->SetBinContent(21,9);
   thirdJetEta_data_wMass_emu__10->SetBinContent(22,9);
   thirdJetEta_data_wMass_emu__10->SetBinContent(23,1);
   thirdJetEta_data_wMass_emu__10->SetBinContent(24,2);
   thirdJetEta_data_wMass_emu__10->SetEntries(2668);
   thirdJetEta_data_wMass_emu__10->SetDirectory(0);
   thirdJetEta_data_wMass_emu__10->SetFillColor(1);
   thirdJetEta_data_wMass_emu__10->SetLineWidth(2);
   thirdJetEta_data_wMass_emu__10->SetLineColor(1); //
   thirdJetEta_data_wMass_emu__10->SetMarkerStyle(20);
   thirdJetEta_data_wMass_emu__10->SetMarkerSize(1.4);
   thirdJetEta_data_wMass_emu__10->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_data_wMass_emu__10->GetXaxis()->SetLabelFont(42);
   thirdJetEta_data_wMass_emu__10->GetXaxis()->SetLabelSize(0.035);
   thirdJetEta_data_wMass_emu__10->GetXaxis()->SetTitleSize(0.035);
   thirdJetEta_data_wMass_emu__10->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_data_wMass_emu__10->GetXaxis()->SetTitleFont(42);
   thirdJetEta_data_wMass_emu__10->GetYaxis()->SetLabelFont(42);
   thirdJetEta_data_wMass_emu__10->GetYaxis()->SetLabelSize(0.035);
   thirdJetEta_data_wMass_emu__10->GetYaxis()->SetTitleSize(0.035);
   thirdJetEta_data_wMass_emu__10->GetYaxis()->SetTitleOffset(1);
   thirdJetEta_data_wMass_emu__10->GetYaxis()->SetTitleFont(42);
   thirdJetEta_data_wMass_emu__10->GetZaxis()->SetLabelFont(42);
   thirdJetEta_data_wMass_emu__10->GetZaxis()->SetLabelSize(0.035);
   thirdJetEta_data_wMass_emu__10->GetZaxis()->SetTitleSize(0.035);
   thirdJetEta_data_wMass_emu__10->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_data_wMass_emu__10->GetZaxis()->SetTitleFont(42);
   thirdJetEta_data_wMass_emu__10->Draw("e x0, same");
   
   TLegend *leg = new TLegend(0.78,0.42,0.98,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("thirdJetEta_zPlusJetsMadgraph_wMass_emu_stack_8","Z+jets (LO)","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetEta_tt_wMass_emu_stack_7","t#bar{t}","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetEta_SingleTop_wMass_emu_stack_6","Single top","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetEta_VV_wMass_emu_stack_5","VV","f");

   ci = TColor::GetColor("#ff9933");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetEta_VVV_wMass_emu_stack_4","VVV","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetEta_wJets_wMass_emu_stack_3","W+jets","f");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetEta_ttV_wMass_emu_stack_2","t#bar{t}V","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetEta_tZq_wMass_emu_stack_1","tZq","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("thirdJetEta_data_wMass_emu","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.4);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.968,0.9429101,"35.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06792969);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.096,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.05419922);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16899,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.04119141);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *thirdJetEta_SingleTop_wMass_emu__11 = new TH1F("thirdJetEta_SingleTop_wMass_emu__11","Third Jet #eta",25,0,5);
   thirdJetEta_SingleTop_wMass_emu__11->SetMinimum(0);
   thirdJetEta_SingleTop_wMass_emu__11->SetMaximum(155.925);
   thirdJetEta_SingleTop_wMass_emu__11->SetDirectory(0);
   thirdJetEta_SingleTop_wMass_emu__11->SetStats(0);
   thirdJetEta_SingleTop_wMass_emu__11->SetLineStyle(0);
   thirdJetEta_SingleTop_wMass_emu__11->SetLineWidth(0);
   thirdJetEta_SingleTop_wMass_emu__11->SetMarkerStyle(20);
   thirdJetEta_SingleTop_wMass_emu__11->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_SingleTop_wMass_emu__11->GetXaxis()->SetNdivisions(506);
   thirdJetEta_SingleTop_wMass_emu__11->GetXaxis()->SetLabelFont(42);
   thirdJetEta_SingleTop_wMass_emu__11->GetXaxis()->SetLabelOffset(999);
   thirdJetEta_SingleTop_wMass_emu__11->GetXaxis()->SetLabelSize(0.05);
   thirdJetEta_SingleTop_wMass_emu__11->GetXaxis()->SetTitleSize(0.08);
   thirdJetEta_SingleTop_wMass_emu__11->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_SingleTop_wMass_emu__11->GetXaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_wMass_emu__11->GetYaxis()->SetTitle("Events");
   thirdJetEta_SingleTop_wMass_emu__11->GetYaxis()->SetNdivisions(506);
   thirdJetEta_SingleTop_wMass_emu__11->GetYaxis()->SetLabelFont(42);
   thirdJetEta_SingleTop_wMass_emu__11->GetYaxis()->SetLabelOffset(0.01);
   thirdJetEta_SingleTop_wMass_emu__11->GetYaxis()->SetLabelSize(0.062);
   thirdJetEta_SingleTop_wMass_emu__11->GetYaxis()->SetTitleSize(0.08);
   thirdJetEta_SingleTop_wMass_emu__11->GetYaxis()->SetTitleOffset(0.6336);
   thirdJetEta_SingleTop_wMass_emu__11->GetYaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_wMass_emu__11->GetZaxis()->SetLabelFont(42);
   thirdJetEta_SingleTop_wMass_emu__11->GetZaxis()->SetLabelOffset(0.007);
   thirdJetEta_SingleTop_wMass_emu__11->GetZaxis()->SetLabelSize(0.05);
   thirdJetEta_SingleTop_wMass_emu__11->GetZaxis()->SetTitleSize(0.08);
   thirdJetEta_SingleTop_wMass_emu__11->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_SingleTop_wMass_emu__11->GetZaxis()->SetTitleFont(42);
   thirdJetEta_SingleTop_wMass_emu__11->Draw("sameaxis");
   
   TPaveText *pt = new TPaveText(0.439299,0.9371861,0.560701,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Third Jet #eta");
   pt->Draw();
   canvy_1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: canvy_2
   TPad *canvy_2 = new TPad("canvy_2", "newpad2",0.01,0.01,0.99,0.322);
   canvy_2->Draw();
   canvy_2->cd();
   canvy_2->SetFillColor(0);
   canvy_2->SetBorderMode(0);
   canvy_2->SetGridy();

   canvy_2->SetLeftMargin( L/W );
   canvy_2->SetRightMargin( R/W );
   canvy_2->SetTopMargin( T/H );
   canvy_2->SetBottomMargin( B/H * 2.6 );
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   
   TH1D *thirdJetEta_data_wMass_emu__12 = new TH1D("thirdJetEta_data_wMass_emu__12","",25,0,5);
   thirdJetEta_data_wMass_emu__12->SetBinContent(0,1.088586);
   thirdJetEta_data_wMass_emu__12->SetBinContent(1,0.8685004);
   thirdJetEta_data_wMass_emu__12->SetBinContent(2,0.9481354);
   thirdJetEta_data_wMass_emu__12->SetBinContent(3,1.130793);
   thirdJetEta_data_wMass_emu__12->SetBinContent(4,1.159627);
   thirdJetEta_data_wMass_emu__12->SetBinContent(5,1.007804);
   thirdJetEta_data_wMass_emu__12->SetBinContent(6,1.041236);
   thirdJetEta_data_wMass_emu__12->SetBinContent(7,1.093002);
   thirdJetEta_data_wMass_emu__12->SetBinContent(8,0.9205846);
   thirdJetEta_data_wMass_emu__12->SetBinContent(9,0.8475963);
   thirdJetEta_data_wMass_emu__12->SetBinContent(10,1.141063);
   thirdJetEta_data_wMass_emu__12->SetBinContent(11,1.244877);
   thirdJetEta_data_wMass_emu__12->SetBinContent(12,1.068127);
   thirdJetEta_data_wMass_emu__12->SetBinContent(13,0.7022948);
   thirdJetEta_data_wMass_emu__12->SetBinContent(14,1.035215);
   thirdJetEta_data_wMass_emu__12->SetBinContent(15,1.306037);
   thirdJetEta_data_wMass_emu__12->SetBinContent(16,0.6671672);
   thirdJetEta_data_wMass_emu__12->SetBinContent(17,0.8446446);
   thirdJetEta_data_wMass_emu__12->SetBinContent(18,1.027049);
   thirdJetEta_data_wMass_emu__12->SetBinContent(19,1.139401);
   thirdJetEta_data_wMass_emu__12->SetBinContent(20,0.5508125);
   thirdJetEta_data_wMass_emu__12->SetBinContent(21,1.064);
   thirdJetEta_data_wMass_emu__12->SetBinContent(22,2.187709);
   thirdJetEta_data_wMass_emu__12->SetBinContent(23,0.3176313);
   thirdJetEta_data_wMass_emu__12->SetBinContent(24,3.204286);
   thirdJetEta_data_wMass_emu__12->SetBinError(0,0.04247287);
   thirdJetEta_data_wMass_emu__12->SetBinError(1,0.1164126);
   thirdJetEta_data_wMass_emu__12->SetBinError(2,0.1279346);
   thirdJetEta_data_wMass_emu__12->SetBinError(3,0.142065);
   thirdJetEta_data_wMass_emu__12->SetBinError(4,0.1494637);
   thirdJetEta_data_wMass_emu__12->SetBinError(5,0.1380526);
   thirdJetEta_data_wMass_emu__12->SetBinError(6,0.1487632);
   thirdJetEta_data_wMass_emu__12->SetBinError(7,0.1648587);
   thirdJetEta_data_wMass_emu__12->SetBinError(8,0.1400365);
   thirdJetEta_data_wMass_emu__12->SetBinError(9,0.137703);
   thirdJetEta_data_wMass_emu__12->SetBinError(10,0.2055192);
   thirdJetEta_data_wMass_emu__12->SetBinError(11,0.2388129);
   thirdJetEta_data_wMass_emu__12->SetBinError(12,0.2150931);
   thirdJetEta_data_wMass_emu__12->SetBinError(13,0.1797009);
   thirdJetEta_data_wMass_emu__12->SetBinError(14,0.2306447);
   thirdJetEta_data_wMass_emu__12->SetBinError(15,0.3352389);
   thirdJetEta_data_wMass_emu__12->SetBinError(16,0.2302291);
   thirdJetEta_data_wMass_emu__12->SetBinError(17,0.2631804);
   thirdJetEta_data_wMass_emu__12->SetBinError(18,0.3775526);
   thirdJetEta_data_wMass_emu__12->SetBinError(19,0.4303058);
   thirdJetEta_data_wMass_emu__12->SetBinError(20,0.3429679);
   thirdJetEta_data_wMass_emu__12->SetBinError(21,0.5095365);
   thirdJetEta_data_wMass_emu__12->SetBinError(22,1.30199);
   thirdJetEta_data_wMass_emu__12->SetBinError(23,0.364603);
   thirdJetEta_data_wMass_emu__12->SetBinError(24,4.64582);
   thirdJetEta_data_wMass_emu__12->SetMinimum(0.5);
   thirdJetEta_data_wMass_emu__12->SetMaximum(1.5);
   thirdJetEta_data_wMass_emu__12->SetEntries(28.39791);
   thirdJetEta_data_wMass_emu__12->SetDirectory(0);
   thirdJetEta_data_wMass_emu__12->SetStats(0);
   thirdJetEta_data_wMass_emu__12->SetFillColor(1);
   thirdJetEta_data_wMass_emu__12->SetLineWidth(2);
   thirdJetEta_data_wMass_emu__12->SetLineColor(1); //
   thirdJetEta_data_wMass_emu__12->SetMarkerStyle(20);
   thirdJetEta_data_wMass_emu__12->SetMarkerSize(1.6);
   thirdJetEta_data_wMass_emu__12->GetXaxis()->SetTitle("Third Jet #eta");
   thirdJetEta_data_wMass_emu__12->GetXaxis()->SetNdivisions(506);
   thirdJetEta_data_wMass_emu__12->GetXaxis()->SetLabelFont(42);
   thirdJetEta_data_wMass_emu__12->GetXaxis()->SetLabelOffset(0.013);
   thirdJetEta_data_wMass_emu__12->GetXaxis()->SetLabelSize(0.13);
   thirdJetEta_data_wMass_emu__12->GetXaxis()->SetTitleSize(0.13);
   thirdJetEta_data_wMass_emu__12->GetXaxis()->SetTitleOffset(1);
   thirdJetEta_data_wMass_emu__12->GetXaxis()->SetTitleFont(42);
   thirdJetEta_data_wMass_emu__12->GetYaxis()->SetTitle("Data/MC");
   thirdJetEta_data_wMass_emu__12->GetYaxis()->CenterTitle(true);
   thirdJetEta_data_wMass_emu__12->GetYaxis()->SetNdivisions(506);
   thirdJetEta_data_wMass_emu__12->GetYaxis()->SetLabelFont(42);
   thirdJetEta_data_wMass_emu__12->GetYaxis()->SetLabelOffset(0.01);
   thirdJetEta_data_wMass_emu__12->GetYaxis()->SetLabelSize(0.12);
   thirdJetEta_data_wMass_emu__12->GetYaxis()->SetTitleSize(0.16);
   thirdJetEta_data_wMass_emu__12->GetYaxis()->SetTitleOffset(0.3);
   thirdJetEta_data_wMass_emu__12->GetYaxis()->SetTitleFont(42);
   thirdJetEta_data_wMass_emu__12->GetZaxis()->SetLabelFont(42);
   thirdJetEta_data_wMass_emu__12->GetZaxis()->SetLabelSize(0.035);
   thirdJetEta_data_wMass_emu__12->GetZaxis()->SetTitleSize(0.035);
   thirdJetEta_data_wMass_emu__12->GetZaxis()->SetTitleOffset(1);
   thirdJetEta_data_wMass_emu__12->GetZaxis()->SetTitleFont(42);
   thirdJetEta_data_wMass_emu__12->Draw("e x0, SCAT");
   canvy_2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
//   c1->SetSelected(thirdJetEta_data_wMass_emu);
   c1->SaveAs("thirdJetEta_wMass.pdf");
}
