void zPt_wMass()
{
//=========Macro generated from canvas: zPairPt_SingleTop_wMass_emu/zPairPt_SingleTop_wMass_emu
//=========  (Wed Aug 21 18:10:17 2019) by ROOT version 6.18/00

   // Set up cavas
   int W = 1280;
   int H = 1024;
   int H_ref = 925; 
   int W_ref = 1024; 

   // references for T, B, L, R
   float T = 0.08*H_ref;
   float B = 0.12*H_ref; 
   float L = 0.12*W_ref;
   float R = 0.04*W_ref;

   TCanvas *c1 = new TCanvas("c1","c1",50,50,W,H);
   c1->cd();
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetLeftMargin( L/W );
   c1->SetRightMargin( R/W );
   c1->SetTopMargin( T/H );
   c1->SetBottomMargin( B/H );
   c1->SetTickx(0);
   c1->SetTicky(0);

// ------------>Primitives in pad: canvy_1
   TPad *canvy_1 = new TPad("canvy_1", "newpad",0.01,0.315,0.99,0.99);
   canvy_1->Draw();
   canvy_1->cd();
   canvy_1->SetFillColor(0);
   canvy_1->SetBorderMode(0);

   canvy_1->SetLeftMargin( L/W );
   canvy_1->SetRightMargin( R/W );
   canvy_1->SetTopMargin( T/H );
   canvy_1->SetBottomMargin( B/H * 0.3 );

   canvy_1->SetFrameFillStyle(0);
   canvy_1->SetFrameBorderMode(0);
   
   THStack *zPairPt_SingleTop_wMass_emu = new THStack();
   zPairPt_SingleTop_wMass_emu->SetName("zPairPt_SingleTop_wMass_emu");
   zPairPt_SingleTop_wMass_emu->SetTitle(";Z boson p_{T} (GeV);Events");
   zPairPt_SingleTop_wMass_emu->SetMaximum(565.4);
   
   TH1F *zPairPt_SingleTop_wMass_emu_stack_2 = new TH1F("zPairPt_SingleTop_wMass_emu_stack_2","Z p_{T}",20,0,400);
   zPairPt_SingleTop_wMass_emu_stack_2->SetMinimum(0);
   zPairPt_SingleTop_wMass_emu_stack_2->SetMaximum(593.67);
   zPairPt_SingleTop_wMass_emu_stack_2->SetDirectory(0);
   zPairPt_SingleTop_wMass_emu_stack_2->SetStats(0);
   zPairPt_SingleTop_wMass_emu_stack_2->SetLineStyle(0);
   zPairPt_SingleTop_wMass_emu_stack_2->SetLineWidth(0);
   zPairPt_SingleTop_wMass_emu_stack_2->SetMarkerStyle(20);
   zPairPt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetTitle("Z boson p_{T} (GeV)");
   zPairPt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetNdivisions(506);
   zPairPt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetLabelFont(42);
   zPairPt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetLabelOffset(999);
   zPairPt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetLabelSize(0.05);
   zPairPt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetTitleSize(0.08);
   zPairPt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   zPairPt_SingleTop_wMass_emu_stack_2->GetXaxis()->SetTitleFont(42);
   zPairPt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetTitle("Events");
   zPairPt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetNdivisions(506);
   zPairPt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetLabelFont(42);
   zPairPt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetLabelOffset(0.01);
   zPairPt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetLabelSize(0.062);
   zPairPt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetTitleSize(0.08);
   zPairPt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetTitleOffset(0.6336);
   zPairPt_SingleTop_wMass_emu_stack_2->GetYaxis()->SetTitleFont(42);
   zPairPt_SingleTop_wMass_emu_stack_2->GetZaxis()->SetLabelFont(42);
   zPairPt_SingleTop_wMass_emu_stack_2->GetZaxis()->SetLabelOffset(0.007);
   zPairPt_SingleTop_wMass_emu_stack_2->GetZaxis()->SetLabelSize(0.05);
   zPairPt_SingleTop_wMass_emu_stack_2->GetZaxis()->SetTitleSize(0.08);
   zPairPt_SingleTop_wMass_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   zPairPt_SingleTop_wMass_emu_stack_2->GetZaxis()->SetTitleFont(42);
   zPairPt_SingleTop_wMass_emu->SetHistogram(zPairPt_SingleTop_wMass_emu_stack_2);
   
   
   TH1D *zPairPt_tZq_wMass_emu_stack_1 = new TH1D("zPairPt_tZq_wMass_emu_stack_1","zPairPt_tZq_wMass_emu",20,0,400);
   zPairPt_tZq_wMass_emu_stack_1->SetBinContent(1,0.01919907);
   zPairPt_tZq_wMass_emu_stack_1->SetBinContent(2,0.06535559);
   zPairPt_tZq_wMass_emu_stack_1->SetBinContent(3,0.05374885);
   zPairPt_tZq_wMass_emu_stack_1->SetBinContent(4,0.0808818);
   zPairPt_tZq_wMass_emu_stack_1->SetBinContent(5,0.03847275);
   zPairPt_tZq_wMass_emu_stack_1->SetBinContent(6,0.02222407);
   zPairPt_tZq_wMass_emu_stack_1->SetBinContent(7,0.02458108);
   zPairPt_tZq_wMass_emu_stack_1->SetBinContent(8,0.007818628);
   zPairPt_tZq_wMass_emu_stack_1->SetBinContent(9,0.006283404);
   zPairPt_tZq_wMass_emu_stack_1->SetBinContent(10,0.01538901);
   zPairPt_tZq_wMass_emu_stack_1->SetBinContent(11,-0.0001688687);
   zPairPt_tZq_wMass_emu_stack_1->SetBinContent(12,0.002492354);
   zPairPt_tZq_wMass_emu_stack_1->SetBinContent(13,0.00113407);
   zPairPt_tZq_wMass_emu_stack_1->SetBinContent(14,0.003051243);
   zPairPt_tZq_wMass_emu_stack_1->SetBinContent(15,0.0005371227);
   zPairPt_tZq_wMass_emu_stack_1->SetBinContent(16,0.002156076);
   zPairPt_tZq_wMass_emu_stack_1->SetBinContent(17,0.0006974229);
   zPairPt_tZq_wMass_emu_stack_1->SetBinContent(18,-0.000392311);
   zPairPt_tZq_wMass_emu_stack_1->SetBinContent(21,0.0009470727);
   zPairPt_tZq_wMass_emu_stack_1->SetEntries(2170);
   zPairPt_tZq_wMass_emu_stack_1->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ffff00");
   zPairPt_tZq_wMass_emu_stack_1->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   zPairPt_tZq_wMass_emu_stack_1->SetLineColor(ci);
   zPairPt_tZq_wMass_emu_stack_1->SetLineWidth(0);
   zPairPt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitle("Z boson p_{T} (GeV)");
   zPairPt_tZq_wMass_emu_stack_1->GetXaxis()->SetLabelFont(42);
   zPairPt_tZq_wMass_emu_stack_1->GetXaxis()->SetLabelSize(0.035);
   zPairPt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleSize(0.035);
   zPairPt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleOffset(1);
   zPairPt_tZq_wMass_emu_stack_1->GetXaxis()->SetTitleFont(42);
   zPairPt_tZq_wMass_emu_stack_1->GetYaxis()->SetLabelFont(42);
   zPairPt_tZq_wMass_emu_stack_1->GetYaxis()->SetLabelSize(0.035);
   zPairPt_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleSize(0.035);
   zPairPt_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleOffset(1);
   zPairPt_tZq_wMass_emu_stack_1->GetYaxis()->SetTitleFont(42);
   zPairPt_tZq_wMass_emu_stack_1->GetZaxis()->SetLabelFont(42);
   zPairPt_tZq_wMass_emu_stack_1->GetZaxis()->SetLabelSize(0.035);
   zPairPt_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleSize(0.035);
   zPairPt_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleOffset(1);
   zPairPt_tZq_wMass_emu_stack_1->GetZaxis()->SetTitleFont(42);
   zPairPt_SingleTop_wMass_emu->Add(zPairPt_tZq_wMass_emu_stack_1,"");
   
   TH1D *zPairPt_ttV_wMass_emu_stack_2 = new TH1D("zPairPt_ttV_wMass_emu_stack_2","zPairPt_ttV_wMass_emu",20,0,400);
   zPairPt_ttV_wMass_emu_stack_2->SetBinContent(1,1.614829);
   zPairPt_ttV_wMass_emu_stack_2->SetBinContent(2,3.869204);
   zPairPt_ttV_wMass_emu_stack_2->SetBinContent(3,5.30313);
   zPairPt_ttV_wMass_emu_stack_2->SetBinContent(4,4.268674);
   zPairPt_ttV_wMass_emu_stack_2->SetBinContent(5,4.514928);
   zPairPt_ttV_wMass_emu_stack_2->SetBinContent(6,3.268269);
   zPairPt_ttV_wMass_emu_stack_2->SetBinContent(7,2.119171);
   zPairPt_ttV_wMass_emu_stack_2->SetBinContent(8,1.00981);
   zPairPt_ttV_wMass_emu_stack_2->SetBinContent(9,0.8499252);
   zPairPt_ttV_wMass_emu_stack_2->SetBinContent(10,0.3580781);
   zPairPt_ttV_wMass_emu_stack_2->SetBinContent(11,0.2883741);
   zPairPt_ttV_wMass_emu_stack_2->SetBinContent(12,0.1355384);
   zPairPt_ttV_wMass_emu_stack_2->SetBinContent(13,0.0002898838);
   zPairPt_ttV_wMass_emu_stack_2->SetBinContent(14,0.1129127);
   zPairPt_ttV_wMass_emu_stack_2->SetBinContent(15,0.03918798);
   zPairPt_ttV_wMass_emu_stack_2->SetBinContent(16,0.06978141);
   zPairPt_ttV_wMass_emu_stack_2->SetBinContent(17,0.02677654);
   zPairPt_ttV_wMass_emu_stack_2->SetBinContent(18,0.006928881);
   zPairPt_ttV_wMass_emu_stack_2->SetBinContent(19,0.002998803);
   zPairPt_ttV_wMass_emu_stack_2->SetBinContent(20,0.009426389);
   zPairPt_ttV_wMass_emu_stack_2->SetBinContent(21,0.01093745);
   zPairPt_ttV_wMass_emu_stack_2->SetEntries(14144);
   zPairPt_ttV_wMass_emu_stack_2->SetDirectory(0);

   ci = TColor::GetColor("#00ff00");
   zPairPt_ttV_wMass_emu_stack_2->SetFillColor(ci);

   ci = TColor::GetColor("#00ff00");
   zPairPt_ttV_wMass_emu_stack_2->SetLineColor(ci);
   zPairPt_ttV_wMass_emu_stack_2->SetLineWidth(0);
   zPairPt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitle("Z boson p_{T} (GeV)");
   zPairPt_ttV_wMass_emu_stack_2->GetXaxis()->SetLabelFont(42);
   zPairPt_ttV_wMass_emu_stack_2->GetXaxis()->SetLabelSize(0.035);
   zPairPt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleSize(0.035);
   zPairPt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleOffset(1);
   zPairPt_ttV_wMass_emu_stack_2->GetXaxis()->SetTitleFont(42);
   zPairPt_ttV_wMass_emu_stack_2->GetYaxis()->SetLabelFont(42);
   zPairPt_ttV_wMass_emu_stack_2->GetYaxis()->SetLabelSize(0.035);
   zPairPt_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleSize(0.035);
   zPairPt_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleOffset(1);
   zPairPt_ttV_wMass_emu_stack_2->GetYaxis()->SetTitleFont(42);
   zPairPt_ttV_wMass_emu_stack_2->GetZaxis()->SetLabelFont(42);
   zPairPt_ttV_wMass_emu_stack_2->GetZaxis()->SetLabelSize(0.035);
   zPairPt_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleSize(0.035);
   zPairPt_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleOffset(1);
   zPairPt_ttV_wMass_emu_stack_2->GetZaxis()->SetTitleFont(42);
   zPairPt_SingleTop_wMass_emu->Add(zPairPt_ttV_wMass_emu_stack_2,"");
   
   TH1D *zPairPt_wJets_wMass_emu_stack_3 = new TH1D("zPairPt_wJets_wMass_emu_stack_3","zPairPt_wJets_wMass_emu",20,0,400);
   zPairPt_wJets_wMass_emu_stack_3->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   zPairPt_wJets_wMass_emu_stack_3->SetFillColor(ci);

   ci = TColor::GetColor("#cccccc");
   zPairPt_wJets_wMass_emu_stack_3->SetLineColor(ci);
   zPairPt_wJets_wMass_emu_stack_3->SetLineWidth(0);
   zPairPt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitle("Z boson p_{T} (GeV)");
   zPairPt_wJets_wMass_emu_stack_3->GetXaxis()->SetLabelFont(42);
   zPairPt_wJets_wMass_emu_stack_3->GetXaxis()->SetLabelSize(0.035);
   zPairPt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleSize(0.035);
   zPairPt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleOffset(1);
   zPairPt_wJets_wMass_emu_stack_3->GetXaxis()->SetTitleFont(42);
   zPairPt_wJets_wMass_emu_stack_3->GetYaxis()->SetLabelFont(42);
   zPairPt_wJets_wMass_emu_stack_3->GetYaxis()->SetLabelSize(0.035);
   zPairPt_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleSize(0.035);
   zPairPt_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleOffset(1);
   zPairPt_wJets_wMass_emu_stack_3->GetYaxis()->SetTitleFont(42);
   zPairPt_wJets_wMass_emu_stack_3->GetZaxis()->SetLabelFont(42);
   zPairPt_wJets_wMass_emu_stack_3->GetZaxis()->SetLabelSize(0.035);
   zPairPt_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleSize(0.035);
   zPairPt_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleOffset(1);
   zPairPt_wJets_wMass_emu_stack_3->GetZaxis()->SetTitleFont(42);
   zPairPt_SingleTop_wMass_emu->Add(zPairPt_wJets_wMass_emu_stack_3,"");
   
   TH1D *zPairPt_VVV_wMass_emu_stack_4 = new TH1D("zPairPt_VVV_wMass_emu_stack_4","zPairPt_VVV_wMass_emu",20,0,400);
   zPairPt_VVV_wMass_emu_stack_4->SetBinContent(1,0.02384236);
   zPairPt_VVV_wMass_emu_stack_4->SetBinContent(2,0.002352466);
   zPairPt_VVV_wMass_emu_stack_4->SetBinContent(4,0.09949837);
   zPairPt_VVV_wMass_emu_stack_4->SetBinContent(5,0.02946448);
   zPairPt_VVV_wMass_emu_stack_4->SetBinContent(9,0.001068281);
   zPairPt_VVV_wMass_emu_stack_4->SetBinContent(10,0.03458785);
   zPairPt_VVV_wMass_emu_stack_4->SetBinContent(11,0.033447);
   zPairPt_VVV_wMass_emu_stack_4->SetEntries(9);
   zPairPt_VVV_wMass_emu_stack_4->SetDirectory(0);

   ci = TColor::GetColor("#00ffff");
   zPairPt_VVV_wMass_emu_stack_4->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   zPairPt_VVV_wMass_emu_stack_4->SetLineColor(ci);
   zPairPt_VVV_wMass_emu_stack_4->SetLineWidth(0);
   zPairPt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitle("Z boson p_{T} (GeV)");
   zPairPt_VVV_wMass_emu_stack_4->GetXaxis()->SetLabelFont(42);
   zPairPt_VVV_wMass_emu_stack_4->GetXaxis()->SetLabelSize(0.035);
   zPairPt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleSize(0.035);
   zPairPt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleOffset(1);
   zPairPt_VVV_wMass_emu_stack_4->GetXaxis()->SetTitleFont(42);
   zPairPt_VVV_wMass_emu_stack_4->GetYaxis()->SetLabelFont(42);
   zPairPt_VVV_wMass_emu_stack_4->GetYaxis()->SetLabelSize(0.035);
   zPairPt_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleSize(0.035);
   zPairPt_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleOffset(1);
   zPairPt_VVV_wMass_emu_stack_4->GetYaxis()->SetTitleFont(42);
   zPairPt_VVV_wMass_emu_stack_4->GetZaxis()->SetLabelFont(42);
   zPairPt_VVV_wMass_emu_stack_4->GetZaxis()->SetLabelSize(0.035);
   zPairPt_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleSize(0.035);
   zPairPt_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleOffset(1);
   zPairPt_VVV_wMass_emu_stack_4->GetZaxis()->SetTitleFont(42);
   zPairPt_SingleTop_wMass_emu->Add(zPairPt_VVV_wMass_emu_stack_4,"");
   
   TH1D *zPairPt_VV_wMass_emu_stack_5 = new TH1D("zPairPt_VV_wMass_emu_stack_5","zPairPt_VV_wMass_emu",20,0,400);
   zPairPt_VV_wMass_emu_stack_5->SetBinContent(1,-0.03366026);
   zPairPt_VV_wMass_emu_stack_5->SetBinContent(2,0.2166178);
   zPairPt_VV_wMass_emu_stack_5->SetBinContent(3,0.2009555);
   zPairPt_VV_wMass_emu_stack_5->SetBinContent(4,0.3160517);
   zPairPt_VV_wMass_emu_stack_5->SetBinContent(5,0.65266);
   zPairPt_VV_wMass_emu_stack_5->SetBinContent(6,0.216538);
   zPairPt_VV_wMass_emu_stack_5->SetBinContent(7,0.1589004);
   zPairPt_VV_wMass_emu_stack_5->SetBinContent(8,0.008806773);
   zPairPt_VV_wMass_emu_stack_5->SetBinContent(9,-0.001874605);
   zPairPt_VV_wMass_emu_stack_5->SetBinContent(11,0.2260857);
   zPairPt_VV_wMass_emu_stack_5->SetBinContent(12,-0.004595168);
   zPairPt_VV_wMass_emu_stack_5->SetBinContent(13,0.3260299);
   zPairPt_VV_wMass_emu_stack_5->SetBinContent(14,0.2085874);
   zPairPt_VV_wMass_emu_stack_5->SetBinContent(15,-0.01148484);
   zPairPt_VV_wMass_emu_stack_5->SetEntries(45);
   zPairPt_VV_wMass_emu_stack_5->SetDirectory(0);

   ci = TColor::GetColor("#ff9933");
   zPairPt_VV_wMass_emu_stack_5->SetFillColor(ci);

   ci = TColor::GetColor("#ff9933");
   zPairPt_VV_wMass_emu_stack_5->SetLineColor(ci);
   zPairPt_VV_wMass_emu_stack_5->SetLineWidth(0);
   zPairPt_VV_wMass_emu_stack_5->GetXaxis()->SetTitle("Z boson p_{T} (GeV)");
   zPairPt_VV_wMass_emu_stack_5->GetXaxis()->SetLabelFont(42);
   zPairPt_VV_wMass_emu_stack_5->GetXaxis()->SetLabelSize(0.035);
   zPairPt_VV_wMass_emu_stack_5->GetXaxis()->SetTitleSize(0.035);
   zPairPt_VV_wMass_emu_stack_5->GetXaxis()->SetTitleOffset(1);
   zPairPt_VV_wMass_emu_stack_5->GetXaxis()->SetTitleFont(42);
   zPairPt_VV_wMass_emu_stack_5->GetYaxis()->SetLabelFont(42);
   zPairPt_VV_wMass_emu_stack_5->GetYaxis()->SetLabelSize(0.035);
   zPairPt_VV_wMass_emu_stack_5->GetYaxis()->SetTitleSize(0.035);
   zPairPt_VV_wMass_emu_stack_5->GetYaxis()->SetTitleOffset(1);
   zPairPt_VV_wMass_emu_stack_5->GetYaxis()->SetTitleFont(42);
   zPairPt_VV_wMass_emu_stack_5->GetZaxis()->SetLabelFont(42);
   zPairPt_VV_wMass_emu_stack_5->GetZaxis()->SetLabelSize(0.035);
   zPairPt_VV_wMass_emu_stack_5->GetZaxis()->SetTitleSize(0.035);
   zPairPt_VV_wMass_emu_stack_5->GetZaxis()->SetTitleOffset(1);
   zPairPt_VV_wMass_emu_stack_5->GetZaxis()->SetTitleFont(42);
   zPairPt_SingleTop_wMass_emu->Add(zPairPt_VV_wMass_emu_stack_5,"");
   
   TH1D *zPairPt_SingleTop_wMass_emu_stack_6 = new TH1D("zPairPt_SingleTop_wMass_emu_stack_6","zPairPt_SingleTop_wMass_emu",20,0,400);
   zPairPt_SingleTop_wMass_emu_stack_6->SetBinContent(1,3.810753);
   zPairPt_SingleTop_wMass_emu_stack_6->SetBinContent(2,12.48721);
   zPairPt_SingleTop_wMass_emu_stack_6->SetBinContent(3,14.54837);
   zPairPt_SingleTop_wMass_emu_stack_6->SetBinContent(4,15.36657);
   zPairPt_SingleTop_wMass_emu_stack_6->SetBinContent(5,15.25093);
   zPairPt_SingleTop_wMass_emu_stack_6->SetBinContent(6,16.55201);
   zPairPt_SingleTop_wMass_emu_stack_6->SetBinContent(7,8.903588);
   zPairPt_SingleTop_wMass_emu_stack_6->SetBinContent(8,6.358491);
   zPairPt_SingleTop_wMass_emu_stack_6->SetBinContent(9,5.358481);
   zPairPt_SingleTop_wMass_emu_stack_6->SetBinContent(10,2.056863);
   zPairPt_SingleTop_wMass_emu_stack_6->SetBinContent(11,1.205232);
   zPairPt_SingleTop_wMass_emu_stack_6->SetBinContent(12,0.842304);
   zPairPt_SingleTop_wMass_emu_stack_6->SetBinContent(13,0.4161526);
   zPairPt_SingleTop_wMass_emu_stack_6->SetBinContent(14,0.1845766);
   zPairPt_SingleTop_wMass_emu_stack_6->SetBinContent(15,0.453957);
   zPairPt_SingleTop_wMass_emu_stack_6->SetBinContent(16,0.3711986);
   zPairPt_SingleTop_wMass_emu_stack_6->SetBinContent(17,0.1783682);
   zPairPt_SingleTop_wMass_emu_stack_6->SetBinContent(18,0.188382);
   zPairPt_SingleTop_wMass_emu_stack_6->SetBinContent(19,0.000867598);
   zPairPt_SingleTop_wMass_emu_stack_6->SetBinContent(20,0.1998297);
   zPairPt_SingleTop_wMass_emu_stack_6->SetEntries(1034);
   zPairPt_SingleTop_wMass_emu_stack_6->SetDirectory(0);

   ci = TColor::GetColor("#ff00ff");
   zPairPt_SingleTop_wMass_emu_stack_6->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   zPairPt_SingleTop_wMass_emu_stack_6->SetLineColor(ci);
   zPairPt_SingleTop_wMass_emu_stack_6->SetLineWidth(0);
   zPairPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitle("Z boson p_{T} (GeV)");
   zPairPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetLabelFont(42);
   zPairPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetLabelSize(0.035);
   zPairPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleSize(0.035);
   zPairPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleOffset(1);
   zPairPt_SingleTop_wMass_emu_stack_6->GetXaxis()->SetTitleFont(42);
   zPairPt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetLabelFont(42);
   zPairPt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetLabelSize(0.035);
   zPairPt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleSize(0.035);
   zPairPt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleOffset(1);
   zPairPt_SingleTop_wMass_emu_stack_6->GetYaxis()->SetTitleFont(42);
   zPairPt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetLabelFont(42);
   zPairPt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetLabelSize(0.035);
   zPairPt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleSize(0.035);
   zPairPt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleOffset(1);
   zPairPt_SingleTop_wMass_emu_stack_6->GetZaxis()->SetTitleFont(42);
   zPairPt_SingleTop_wMass_emu->Add(zPairPt_SingleTop_wMass_emu_stack_6,"");
   
   TH1D *zPairPt_tt_wMass_emu_stack_7 = new TH1D("zPairPt_tt_wMass_emu_stack_7","zPairPt_tt_wMass_emu",20,0,400);
   zPairPt_tt_wMass_emu_stack_7->SetBinContent(1,149.759);
   zPairPt_tt_wMass_emu_stack_7->SetBinContent(2,366.2552);
   zPairPt_tt_wMass_emu_stack_7->SetBinContent(3,412.823);
   zPairPt_tt_wMass_emu_stack_7->SetBinContent(4,428.922);
   zPairPt_tt_wMass_emu_stack_7->SetBinContent(5,411.3983);
   zPairPt_tt_wMass_emu_stack_7->SetBinContent(6,283.331);
   zPairPt_tt_wMass_emu_stack_7->SetBinContent(7,158.0749);
   zPairPt_tt_wMass_emu_stack_7->SetBinContent(8,90.41133);
   zPairPt_tt_wMass_emu_stack_7->SetBinContent(9,49.71907);
   zPairPt_tt_wMass_emu_stack_7->SetBinContent(10,22.82859);
   zPairPt_tt_wMass_emu_stack_7->SetBinContent(11,10.09416);
   zPairPt_tt_wMass_emu_stack_7->SetBinContent(12,9.168676);
   zPairPt_tt_wMass_emu_stack_7->SetBinContent(13,3.893195);
   zPairPt_tt_wMass_emu_stack_7->SetBinContent(14,0.6055197);
   zPairPt_tt_wMass_emu_stack_7->SetBinContent(15,0.9800044);
   zPairPt_tt_wMass_emu_stack_7->SetBinContent(16,1.239635);
   zPairPt_tt_wMass_emu_stack_7->SetBinContent(17,0.3432944);
   zPairPt_tt_wMass_emu_stack_7->SetBinContent(19,0.2894071);
   zPairPt_tt_wMass_emu_stack_7->SetBinContent(21,0.6426235);
   zPairPt_tt_wMass_emu_stack_7->SetEntries(7802);
   zPairPt_tt_wMass_emu_stack_7->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   zPairPt_tt_wMass_emu_stack_7->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   zPairPt_tt_wMass_emu_stack_7->SetLineColor(ci);
   zPairPt_tt_wMass_emu_stack_7->SetLineWidth(0);
   zPairPt_tt_wMass_emu_stack_7->GetXaxis()->SetTitle("Z boson p_{T} (GeV)");
   zPairPt_tt_wMass_emu_stack_7->GetXaxis()->SetLabelFont(42);
   zPairPt_tt_wMass_emu_stack_7->GetXaxis()->SetLabelSize(0.035);
   zPairPt_tt_wMass_emu_stack_7->GetXaxis()->SetTitleSize(0.035);
   zPairPt_tt_wMass_emu_stack_7->GetXaxis()->SetTitleOffset(1);
   zPairPt_tt_wMass_emu_stack_7->GetXaxis()->SetTitleFont(42);
   zPairPt_tt_wMass_emu_stack_7->GetYaxis()->SetLabelFont(42);
   zPairPt_tt_wMass_emu_stack_7->GetYaxis()->SetLabelSize(0.035);
   zPairPt_tt_wMass_emu_stack_7->GetYaxis()->SetTitleSize(0.035);
   zPairPt_tt_wMass_emu_stack_7->GetYaxis()->SetTitleOffset(1);
   zPairPt_tt_wMass_emu_stack_7->GetYaxis()->SetTitleFont(42);
   zPairPt_tt_wMass_emu_stack_7->GetZaxis()->SetLabelFont(42);
   zPairPt_tt_wMass_emu_stack_7->GetZaxis()->SetLabelSize(0.035);
   zPairPt_tt_wMass_emu_stack_7->GetZaxis()->SetTitleSize(0.035);
   zPairPt_tt_wMass_emu_stack_7->GetZaxis()->SetTitleOffset(1);
   zPairPt_tt_wMass_emu_stack_7->GetZaxis()->SetTitleFont(42);
   zPairPt_SingleTop_wMass_emu->Add(zPairPt_tt_wMass_emu_stack_7,"");
   
   TH1D *zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8 = new TH1D("zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8","zPairPt_zPlusJetsMadgraph_wMass_emu",20,0,400);
   zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8->SetLineColor(ci);
   zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8->SetLineWidth(0);
   zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitle("Z boson p_{T} (GeV)");
   zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetLabelFont(42);
   zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetLabelSize(0.035);
   zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleSize(0.035);
   zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleOffset(1);
   zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetXaxis()->SetTitleFont(42);
   zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetLabelFont(42);
   zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetLabelSize(0.035);
   zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleSize(0.035);
   zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleOffset(1);
   zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetYaxis()->SetTitleFont(42);
   zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetLabelFont(42);
   zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetLabelSize(0.035);
   zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleSize(0.035);
   zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleOffset(1);
   zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8->GetZaxis()->SetTitleFont(42);
   zPairPt_SingleTop_wMass_emu->Add(zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8,"");
   zPairPt_SingleTop_wMass_emu->Draw("");
   
   TH1D *zPairPt_data_wMass_emu__4 = new TH1D("zPairPt_data_wMass_emu__4","zPairPt_data_wMass_emu",20,0,400);
   zPairPt_data_wMass_emu__4->SetBinContent(1,154);
   zPairPt_data_wMass_emu__4->SetBinContent(2,406);
   zPairPt_data_wMass_emu__4->SetBinContent(3,494);
   zPairPt_data_wMass_emu__4->SetBinContent(4,514);
   zPairPt_data_wMass_emu__4->SetBinContent(5,424);
   zPairPt_data_wMass_emu__4->SetBinContent(6,324);
   zPairPt_data_wMass_emu__4->SetBinContent(7,168);
   zPairPt_data_wMass_emu__4->SetBinContent(8,85);
   zPairPt_data_wMass_emu__4->SetBinContent(9,36);
   zPairPt_data_wMass_emu__4->SetBinContent(10,29);
   zPairPt_data_wMass_emu__4->SetBinContent(11,19);
   zPairPt_data_wMass_emu__4->SetBinContent(12,6);
   zPairPt_data_wMass_emu__4->SetBinContent(13,5);
   zPairPt_data_wMass_emu__4->SetBinContent(14,1);
   zPairPt_data_wMass_emu__4->SetBinContent(16,2);
   zPairPt_data_wMass_emu__4->SetBinContent(19,1);
   zPairPt_data_wMass_emu__4->SetEntries(2668);
   zPairPt_data_wMass_emu__4->SetDirectory(0);
   zPairPt_data_wMass_emu__4->SetFillColor(1);
   zPairPt_data_wMass_emu__4->SetLineWidth(2);
   zPairPt_data_wMass_emu__4->SetLineColor(1); //
   zPairPt_data_wMass_emu__4->SetMarkerStyle(20);
   zPairPt_data_wMass_emu__4->SetMarkerSize(1.4);
   zPairPt_data_wMass_emu__4->GetXaxis()->SetTitle("Z boson p_{T} (GeV)");
   zPairPt_data_wMass_emu__4->GetXaxis()->SetLabelFont(42);
   zPairPt_data_wMass_emu__4->GetXaxis()->SetLabelSize(0.035);
   zPairPt_data_wMass_emu__4->GetXaxis()->SetTitleSize(0.035);
   zPairPt_data_wMass_emu__4->GetXaxis()->SetTitleOffset(1);
   zPairPt_data_wMass_emu__4->GetXaxis()->SetTitleFont(42);
   zPairPt_data_wMass_emu__4->GetYaxis()->SetLabelFont(42);
   zPairPt_data_wMass_emu__4->GetYaxis()->SetLabelSize(0.035);
   zPairPt_data_wMass_emu__4->GetYaxis()->SetTitleSize(0.035);
   zPairPt_data_wMass_emu__4->GetYaxis()->SetTitleOffset(1);
   zPairPt_data_wMass_emu__4->GetYaxis()->SetTitleFont(42);
   zPairPt_data_wMass_emu__4->GetZaxis()->SetLabelFont(42);
   zPairPt_data_wMass_emu__4->GetZaxis()->SetLabelSize(0.035);
   zPairPt_data_wMass_emu__4->GetZaxis()->SetTitleSize(0.035);
   zPairPt_data_wMass_emu__4->GetZaxis()->SetTitleOffset(1);
   zPairPt_data_wMass_emu__4->GetZaxis()->SetTitleFont(42);
   zPairPt_data_wMass_emu__4->Draw("e x0, same");
   
   TLegend *leg = new TLegend(0.78,0.42,0.98,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("zPairPt_zPlusJetsMadgraph_wMass_emu_stack_8","Z+jets (LO)","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("zPairPt_tt_wMass_emu_stack_7","t#bar{t}","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("zPairPt_SingleTop_wMass_emu_stack_6","Single top","f");

   ci = TColor::GetColor("#ff00ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("zPairPt_VV_wMass_emu_stack_5","VV","f");

   ci = TColor::GetColor("#ff9933");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff9933");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("zPairPt_VVV_wMass_emu_stack_4","VVV","f");

   ci = TColor::GetColor("#00ffff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ffff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("zPairPt_wJets_wMass_emu_stack_3","W+jets","f");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("zPairPt_ttV_wMass_emu_stack_2","t#bar{t}V","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("zPairPt_tZq_wMass_emu_stack_1","tZq","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("zPairPt_data_wMass_emu","Data","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.4);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.968,0.9429101,"35.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.06792969);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.096,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.05419922);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16899,0.9429101,"");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.04119141);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *zPairPt_SingleTop_wMass_emu__5 = new TH1F("zPairPt_SingleTop_wMass_emu__5","Z p_{T}",20,0,400);
   zPairPt_SingleTop_wMass_emu__5->SetMinimum(0);
   zPairPt_SingleTop_wMass_emu__5->SetMaximum(593.67);
   zPairPt_SingleTop_wMass_emu__5->SetDirectory(0);
   zPairPt_SingleTop_wMass_emu__5->SetStats(0);
   zPairPt_SingleTop_wMass_emu__5->SetLineStyle(0);
   zPairPt_SingleTop_wMass_emu__5->SetLineWidth(0);
   zPairPt_SingleTop_wMass_emu__5->SetMarkerStyle(20);
   zPairPt_SingleTop_wMass_emu__5->GetXaxis()->SetTitle("Z boson p_{T} (GeV)");
   zPairPt_SingleTop_wMass_emu__5->GetXaxis()->SetNdivisions(506);
   zPairPt_SingleTop_wMass_emu__5->GetXaxis()->SetLabelFont(42);
   zPairPt_SingleTop_wMass_emu__5->GetXaxis()->SetLabelOffset(999);
   zPairPt_SingleTop_wMass_emu__5->GetXaxis()->SetLabelSize(0.05);
   zPairPt_SingleTop_wMass_emu__5->GetXaxis()->SetTitleSize(0.08);
   zPairPt_SingleTop_wMass_emu__5->GetXaxis()->SetTitleOffset(1);
   zPairPt_SingleTop_wMass_emu__5->GetXaxis()->SetTitleFont(42);
   zPairPt_SingleTop_wMass_emu__5->GetYaxis()->SetTitle("Events");
   zPairPt_SingleTop_wMass_emu__5->GetYaxis()->SetNdivisions(506);
   zPairPt_SingleTop_wMass_emu__5->GetYaxis()->SetLabelFont(42);
   zPairPt_SingleTop_wMass_emu__5->GetYaxis()->SetLabelOffset(0.01);
   zPairPt_SingleTop_wMass_emu__5->GetYaxis()->SetLabelSize(0.062);
   zPairPt_SingleTop_wMass_emu__5->GetYaxis()->SetTitleSize(0.08);
   zPairPt_SingleTop_wMass_emu__5->GetYaxis()->SetTitleOffset(0.6336);
   zPairPt_SingleTop_wMass_emu__5->GetYaxis()->SetTitleFont(42);
   zPairPt_SingleTop_wMass_emu__5->GetZaxis()->SetLabelFont(42);
   zPairPt_SingleTop_wMass_emu__5->GetZaxis()->SetLabelOffset(0.007);
   zPairPt_SingleTop_wMass_emu__5->GetZaxis()->SetLabelSize(0.05);
   zPairPt_SingleTop_wMass_emu__5->GetZaxis()->SetTitleSize(0.08);
   zPairPt_SingleTop_wMass_emu__5->GetZaxis()->SetTitleOffset(1);
   zPairPt_SingleTop_wMass_emu__5->GetZaxis()->SetTitleFont(42);
   zPairPt_SingleTop_wMass_emu__5->Draw("sameaxis");
   
/*   TPaveText *pt = new TPaveText(0.4712366,0.9210254,0.5287634,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Z p_{T}");
   pt->Draw();*/
   canvy_1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: canvy_2
   TPad *canvy_2 = new TPad("canvy_2", "newpad2",0.01,0.01,0.99,0.322);
   canvy_2->Draw();
   canvy_2->cd();
   canvy_2->SetFillColor(0);
   canvy_2->SetBorderMode(0);
   canvy_2->SetGridy();

   canvy_2->SetLeftMargin( L/W );
   canvy_2->SetRightMargin( R/W );
   canvy_2->SetTopMargin( T/H );
   canvy_2->SetBottomMargin( B/H * 2.6 );
   canvy_2->SetFrameFillStyle(0);
   canvy_2->SetFrameBorderMode(0);
   
   TH1D *zPairPt_data_wMass_emu__6 = new TH1D("zPairPt_data_wMass_emu__6","",20,0,400);
   zPairPt_data_wMass_emu__6->SetBinContent(1,0.9923065);
   zPairPt_data_wMass_emu__6->SetBinContent(2,1.06034);
   zPairPt_data_wMass_emu__6->SetBinContent(3,1.141064);
   zPairPt_data_wMass_emu__6->SetBinContent(4,1.144629);
   zPairPt_data_wMass_emu__6->SetBinContent(5,0.9817433);
   zPairPt_data_wMass_emu__6->SetBinContent(6,1.067932);
   zPairPt_data_wMass_emu__6->SetBinContent(7,0.9924319);
   zPairPt_data_wMass_emu__6->SetBinContent(8,0.8691539);
   zPairPt_data_wMass_emu__6->SetBinContent(9,0.6436277);
   zPairPt_data_wMass_emu__6->SetBinContent(10,1.146539);
   zPairPt_data_wMass_emu__6->SetBinContent(11,1.603764);
   zPairPt_data_wMass_emu__6->SetBinContent(12,0.5914584);
   zPairPt_data_wMass_emu__6->SetBinContent(13,1.078329);
   zPairPt_data_wMass_emu__6->SetBinContent(14,0.8971444);
   zPairPt_data_wMass_emu__6->SetBinContent(16,1.188516);
   zPairPt_data_wMass_emu__6->SetBinContent(19,3.409786);
   zPairPt_data_wMass_emu__6->SetBinError(1,0.1128661);
   zPairPt_data_wMass_emu__6->SetBinError(2,0.07553561);
   zPairPt_data_wMass_emu__6->SetBinError(3,0.07512102);
   zPairPt_data_wMass_emu__6->SetBinError(4,0.07393659);
   zPairPt_data_wMass_emu__6->SetBinError(5,0.06711796);
   zPairPt_data_wMass_emu__6->SetBinError(6,0.08531773);
   zPairPt_data_wMass_emu__6->SetBinError(7,0.1080781);
   zPairPt_data_wMass_emu__6->SetBinError(8,0.1288872);
   zPairPt_data_wMass_emu__6->SetBinError(9,0.1375261);
   zPairPt_data_wMass_emu__6->SetBinError(10,0.3119316);
   zPairPt_data_wMass_emu__6->SetBinError(11,0.5936963);
   zPairPt_data_wMass_emu__6->SetBinError(12,0.3046115);
   zPairPt_data_wMass_emu__6->SetBinError(13,0.6952222);
   zPairPt_data_wMass_emu__6->SetBinError(14,1.235699);
   zPairPt_data_wMass_emu__6->SetBinError(16,1.243268);
   zPairPt_data_wMass_emu__6->SetBinError(19,7.160378);
   zPairPt_data_wMass_emu__6->SetMinimum(0.5);
   zPairPt_data_wMass_emu__6->SetMaximum(1.5);
   zPairPt_data_wMass_emu__6->SetEntries(6.379042);
   zPairPt_data_wMass_emu__6->SetDirectory(0);
   zPairPt_data_wMass_emu__6->SetStats(0);
   zPairPt_data_wMass_emu__6->SetFillColor(1);
   zPairPt_data_wMass_emu__6->SetLineWidth(2);
   zPairPt_data_wMass_emu__6->SetLineColor(1); //
   zPairPt_data_wMass_emu__6->SetMarkerStyle(20);
   zPairPt_data_wMass_emu__6->SetMarkerSize(1.6);
   zPairPt_data_wMass_emu__6->GetXaxis()->SetTitle("Z boson p_{T} (GeV)");
   zPairPt_data_wMass_emu__6->GetXaxis()->SetNdivisions(506);
   zPairPt_data_wMass_emu__6->GetXaxis()->SetLabelFont(42);
   zPairPt_data_wMass_emu__6->GetXaxis()->SetLabelOffset(0.013);
   zPairPt_data_wMass_emu__6->GetXaxis()->SetLabelSize(0.13);
   zPairPt_data_wMass_emu__6->GetXaxis()->SetTitleSize(0.13);
   zPairPt_data_wMass_emu__6->GetXaxis()->SetTitleOffset(1);
   zPairPt_data_wMass_emu__6->GetXaxis()->SetTitleFont(42);
   zPairPt_data_wMass_emu__6->GetYaxis()->SetTitle("Data/MC");
   zPairPt_data_wMass_emu__6->GetYaxis()->CenterTitle(true);
   zPairPt_data_wMass_emu__6->GetYaxis()->SetNdivisions(506);
   zPairPt_data_wMass_emu__6->GetYaxis()->SetLabelFont(42);
   zPairPt_data_wMass_emu__6->GetYaxis()->SetLabelOffset(0.01);
   zPairPt_data_wMass_emu__6->GetYaxis()->SetLabelSize(0.12);
   zPairPt_data_wMass_emu__6->GetYaxis()->SetTitleSize(0.16);
   zPairPt_data_wMass_emu__6->GetYaxis()->SetTitleOffset(0.3);
   zPairPt_data_wMass_emu__6->GetYaxis()->SetTitleFont(42);
   zPairPt_data_wMass_emu__6->GetZaxis()->SetLabelFont(42);
   zPairPt_data_wMass_emu__6->GetZaxis()->SetLabelSize(0.035);
   zPairPt_data_wMass_emu__6->GetZaxis()->SetTitleSize(0.035);
   zPairPt_data_wMass_emu__6->GetZaxis()->SetTitleOffset(1);
   zPairPt_data_wMass_emu__6->GetZaxis()->SetTitleFont(42);
   zPairPt_data_wMass_emu__6->Draw("e x0, SCAT");
   canvy_2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
//   c1->SetSelected(zPairPt_SingleTop_wMass_emu);
   c1->SaveAs("zPt_wMass.pdf");
}
